rancher/ui

.drone.yml
Dockerfile
scripts/bootstrap
scripts/build
scripts/ci

The bootstrap script doesn't depend on access to the source directory making it "wrap" script friendly. 
Locked to docker-dind-base v0.4.1 version in both CI and wrap Dockerfile. This forces consistency between the two environments likely to build.
fire off wrapdocker during ci so that containers can be brought in and run if needed.

Made the build/bootstrap scripts 'wrap' friendly and setup for drone

---

app/pods/container/shell/route.js
app/pods/container/shell/view.js
app/pods/overlay/route.js

Change shell to use bash || sh

---

app/components/resource-actions-menu/component.js
app/initializers/extend-bootstrap.js
app/utils/bootstrap-fixes.js
tests/unit/utils/bootstrap-fixes-test.js

There was issue with drop downs that had dynamic data placed into them. The root cause comes from the size of the drop down being calculated on its inner content. The dropdown size and positioning was calculated before the content was placed inside so the dropdown showed up off screen.
Logic was added at some point to calculate the size and position. I took this logic and made it a mixin so it could be called after the dropdown as show.
Can be verified by visiting the environments page and clicking on the active dropdown button. The drop down should appear fully on screen.
N/A
Fixes rancher/rancher#1923

Dropdown positioning

---

app/hosts/new/rackspace/controller.js

Chicago (ORD) was missing from the available locations.

add Chicago (ORD)

---

app/admin-tab/processes/process/route.js

Child processes do not need to be refreshed and doing so while keeping collapse opens its problematic. Removed the logic to refresh child processes on an interval.
rancher/rancher#2242

Remove the interval check for child processes

---

app/components/stack-section/template.hbs

Add missing "#" in href. Required for a functioning collapser.

Fix Stack Collapser

---

app/components/modal-catalog-launch/component.js
app/components/modal-catalog-launch/template.hbs
app/splash/template.hbs

* Added logic to add a drop down in the event of a service question
* Add logic to parse services into an object containing `<stackname>/<servicename>` to send the correct data to the executor 
* Add logic to set default if the stack/service exists already
* Added a new catalog link to the welcome page for clarity 
N/A

Add 'Service' question type to catalog

---

app/admin-tab/processes/process/template.hbs
app/application/controller.js
app/components/modal-process-error/component.js
app/components/modal-process-error/template.hbs
app/components/process-execution-handler-rows/component.js
app/components/process-execution-handler-rows/template.hbs
app/components/process-execution-rows/component.js
app/components/process-execution-rows/template.hbs
app/components/process-executions/template.hbs
app/router.js
app/styles/overlay.scss

* Added view in api button to child processes
* Added new warning icon and background color to processes that have exceptions
* Added new modal to showcase exceptions
Added `overflow:hidden` to the body with LF modal is open. This could affect a lot of stuff but I dont see it causing any issues as it just stops the body from scrolling while a modal is open. Useful for modals that have scrolling content.
N/A

Admin process updates

---

.jshintrc
app/components/common-mark/component.js
app/components/common-mark/template.hbs
app/components/new-catalog/template.hbs
bower.json
ember-cli-build.js
package.json
tests/.jshintrc

* Showdown had an issue with a node dependency that would break sourcemaps on require so we got rid of that.

Removed the showdown markdown processor in favor of Commonmark.

---

app/components/action-menu-item/component.js

* Anchors were causing the page to refresh. This will remove the accessabilty on these links so we need to find another way

Remove anchor tags for action menu items

---

app/applications-tab/compose-waiting/template.hbs

Currently seeing Kubernetes show up in the swarm section when no hosts have been added. If this isn't a typo, then you can go ahead and close this.

Replace kubernetes with swarm in compose waiting template

---

app/admin-tab/audit-logs/template.hbs
config/ember-intl.js
translations/en-us.yaml

This should resolve the admin pages not loading but does not fix the root problem. Polyfills for english are now loaded by default but there seems to be a bug in the ember add on. I will be opening an issue there as well. (rancher/rancher#4954)
Additionally I changed the clear all to clear filters on audit logs search.

load locale polyfills for non-intl supporting browsers

---

app/components/container-logs/component.js
package.json

This PR turns this
into this
Related to https://github.com/rancher/rancher/issues/2768

 show container logs with ansi colors

---

.drone.yml

Add an exclude to 'master' build def such that it does not execute with Drone's non-default merge behavior. I suspect with the non-default merge behavior we have uncommitted changes in the work directory but git still thinks we are on unadulterated master/HEAD?
@cloudnautique @vincent99

prevent attempt to upload on PR with new merge behavior

---

app/admin-tab/auth/localauth/controller.js
app/admin-tab/auth/localauth/template.hbs
app/admin-tab/machine/template.hbs
app/authenticated/project/help/template.hbs
app/components/form-networking/component.js
app/components/form-networking/template.hbs
app/components/new-catalog/template.hbs
app/components/new-container/template.hbs
app/components/new-select/component.js
app/components/stack-graph/component.js
app/models/template.js
app/service/controller.js
app/service/template.hbs
app/styles/layout/_flex-box.scss
app/styles/layout/_sm-screen.scss
app/templates/ldap-config.hbs
translations/en-us.yaml

rancher/rancher#6364
Change logic around retain ip on upgrade
rancher/rancher#5410
Refactor retainIp prop on services
@vincent99 and I had a discussion. Since retainIp is a service level
setting it does not make sense (nor did it ever work) to have retainIp
on sidekicks. So the setting has been removed from that screen. Additionally
since an upgrade does not modify the service but rather the launch config
turning Retain IP on/off during the upgrade does not work. The new requirement
is to disable the checkbox during an upgrade. The upgrade should retain the
origianl value.
rancher/rancher#5410
add password validate desc to local auth config page
rancher/rancher#6362
Change the way stack graph handles route transitions
rancher/rancher#6343
Prevent user from selecting a new catalog template …

Refactor catalog item question css

---

app/styles/vendors/_prism-theme.scss

Improve readability of code blocks

---

app/components/machine/driver-packet/template.hbs

On v1.2.0GA, Packet ui-skelton included variable mismatch between component.js and template.hbs and this PR will enable to deploy machines on several Packet clouds regions.

Fixed variable mismatch for Packet cloud facility

---

translations/en-us.yaml

As supported versions of Docker are documented, the custom host should refer to it instead of stating to install latest version.

Supported Docker version instead of latest

---

app/components/edit-dns/template.hbs
app/components/form-targets/component.js

fix [#8959](https://github.com/rancher/rancher/issues/8959)
and fix the issue that user can not see the existing targets for DNS resolves to service when user update a dns record.

fix service alias issue

---

app/admin-tab/auth/github/controller.js

now we can show the error message from server side
[related issue](https://github.com/rancher/rancher/issues/7369)

Show message if github auth test failed

---

app/components/webhook/new-receiver/component.js
app/components/webhook/new-receiver/template.hbs
app/components/webhook/service-upgrade-config/component.js
app/components/webhook/service-upgrade-config/template.hbs
translations/en-us.yaml
translations/zh-hans.yaml

payload of Alibaba Cloud Docker Hub's webhook is slightly different from Docker Hub.
PR for webhook-service change is [here](https://github.com/rancher/webhook-service/pull/60)
So I have added an option in UI for it [#9175](https://github.com/rancher/rancher/issues/9175)
Also fixed the issues [#7996](https://github.com/rancher/rancher/issues/7996) and [#9022](https://github.com/rancher/rancher/issues/9022)

[1.6] Support Alibaba Cloud Docker Hub webhook

---

app/components/upgrade-dropdown/template.hbs

I replace the `icon` with `button`, so that it look like the follow picture

Fix bug with error page from Up to date button

---

app/components/machine/driver-amazonec2/component.js

Zone a was selected  by default. But sometimes there is no subnets in zone a
https://github.com/rancher/rancher/issues/9871
https://github.com/rancher/rancher/issues/5396

[2.0]Select the first available zone which has at least one subnet.

---

app/components/machine/driver-amazonec2/component.js

Zone a was selected  by default. But sometimes there is no subnets in zone a
https://github.com/rancher/rancher/issues/9871
https://github.com/rancher/rancher/issues/5396

[1.6]Select the first available zone which has at least one subnet.

---

app/components/new-select/component.js

If there is a matching value in options,  set the value manually to avoid the Firefox issue emberjs/ember.js#15484
In chrome and Firefox, the first option will be selected automatically when the value is not in the content array. But we need to trigger the change event, otherwise the value in the model will not be updated.
https://github.com/rancher/rancher/issues/10242
https://github.com/rancher/rancher/issues/10241

Fix the select render issue in Firefox

---

app/components/page-header/component.js
app/models/service.js
app/utils/constants.js

To support Pipeline or other services's access point in the UI
User need to add three label to the service which need access point in page header.
1. `io.rancher.service.ui_link.label` -- This is the label show in the page header. This should be a JSON map used for i18n. it's like 
```JSON
{"de-de":"Deutsch","en-us":"English","fa-ir":"فارسی","fr-fr":"Française","hu-hu":"Magyar","ja-jp":"日本語","none":"None","pt-br":"Português","ru-ru":"Русский","uk-ua":"Українська","zh-hans":"简体中文"}
```
2.  `io.rancher.service.ui_link.path` -- This is the relative router in it's own app. Default will be '/'.
3. `io.rancher.service.ui_link.port` -- This is the private port where the UI is hosted
All of these three label will be combined as access url for magic_proxy, as …

Add new tab as service access point to Rancher UI 1.6

---

app/authenticated/project/api/hooks/index/controller.js

Since the [PR](https://github.com/rancher/webhook-service/pull/66) to add new driver `forwardPost` is merged.
We currently just keep `forwardPost` for internal usage. So, users should not be able to see it.
Related Issue is [here](https://github.com/rancher/rancher/issues/10479)

Filter driver `forwardPost` of webhook-service in UI

---

app/models/service.js

It's caused by `undefined` of 'launchConfig.labels' in Service Alias. I added the valid check here.

Fix issues https://github.com/rancher/rancher/issues/10492

---

app/components/edit-host/component.js
app/components/form-networking/component.js
app/components/machine/driver-custom/component.js
app/components/machine/driver-custom/template.hbs
app/components/stack-header/template.hbs
app/components/stack-section/template.hbs
app/utils/constants.js
app/utils/navigation-tree.js
translations/en-us.yaml
translations/zh-hans.yaml

refer to https://github.com/rancher/rancher/issues/10442
and https://github.com/rancher/rancher/issues/10448
1. Change the add host step for windows environment. Add setting
subnet labels logic.
2. Run command in Windows environment is fetched from rancher
server.
3. Block the webhook link on windows. Because the webhook is not
fully supported in Windows environment.
4. Because the metadata and DNS services are supported, service
alias and external service can be use in Windows environment.

[1.6]Enhance Windows Environment Experience

---

app/components/form-networking/component.js

refer to https://github.com/rancher/rancher/issues/10571,
https://github.com/rancher/rancher/issues/10576 and
https://github.com/rancher/rancher/issues/10570
Manged network option will cause unexpect error when creating service in windows environment. Deprecate it for now.

Managed network option should not be seen in windows

---

app/components/webhook/new-receiver/component.js
app/components/webhook/new-receiver/template.hbs
app/utils/navigation-tree.js

Related issue https://github.com/rancher/rancher/issues/10663
Webhook is enable for Windows.
Webhook only can be scale service or upgrade a service in Windows environment because there is no any machine driver for windows.

[1.6]Webhook for Windows environment

---

lib/shared/addon/components/machine/driver-amazonec2/component.js

This adds the new AWS EC2 eu-west-3 region (Paris) in Rancher UI

Updating AWS EC2 Driver to add new eu-west-3 region

---

lib/global-admin/package.json
lib/login/package.json
lib/shared/app/helpers/t.js
lib/shared/package.json

Fix the issue that translations got compiled 4 times
We can create a `translations` folder in each engine, so that each engine can have it's own translations.

ember-intl

---

lib/global-admin/addon/templates/-ldap-config.hbs

As seen here:
https://github.com/rancher/types/blob/master/apis/management.cattle.io/v3/authn_types.go#L138
There is no `groupDomain` field. The UI should reference the group search base field by its name `groupSearchBase` instead. Without this fix the setting is currently silently dropped when setting up the Active Directory authentication provider.

Fix Active Directory UI using groupDomain key instead of groupSearchBase

---

lib/shared/addon/components/schema/input-hostname/component.js

We have applied a workaround in https://github.com/rancher/charts/pull/2
But it's better to fix it in UI.

Fix the issue that xip.io can not be set in catalog

---

app/components/machine/driver-azure/component.js
app/services/access.js

Sometimes if admin users clean their local storage and refresh the browser.
The admin menu in UI will not display.
Some customer is logging in Rancher without using `login` method of `access` service.

[1.6] Reset userIdentity in local storage if it doesn't exist

---

app/models/node.js

Before this PR, the Unschedulable label only appears for etcd nodes, after this PR it appears for both etcd nodes and controlplane nodes.
This is probably related to rancher/rke#665 which also made controlplane nodes unschedulable.

Display Unschedulable label on controlplane nodes

---

app/workload/template.hbs
translations/en-us.yaml
translations/ja-jp.yaml
translations/ru-ru.yaml
translations/zh-hans.yaml

This PR fixes a spelling error that shows up in the workload view. 
NOTE! There were some ending blankspaces in the file that got removed automatically by the projects .editorconfig. I hope this is not an issue.

Fixed a spelling error in the workload template.

---

lib/shared/addon/helpers/rbac-allows.js
lib/shared/addon/helpers/rbac-prevents.js

`rbac-allows` and `rbac-prevents` do not re-compute when user switch project or cluster.

Fix rbac helper recompute issue

---

translations/en-us.yaml

- K8s docs uses Control Plane
- Our docs uses Control Plane
- kubectl shows `controlplane`
- Our agent command uses `--controlplane`
I think it makes sense to keep naming the same across everything.

Control -> Control Plane

---

package.json

Something, probably ember-cli-eslint or babel, depends on eslint-scope so lets lock it to 3.7.1 
https://github.com/eslint/eslint-scope/issues/39

Lock eslint-scope to pre-hacked package

---

translations/en-us.yaml

This adds a link to https://github.com/rancher/rancher/issues/9322 and changes "not recommended" to "strongly discouraged", as well as makes mention of some of the issues that may arise when `.local` addresses are being used. See the linked issue for the full discussion.
(Sorry for the incredibly long line; I am not sure I can insert line breaks here so I'm just tagging along with the existing code style in the file.)

.local TLD warning: increase severity, add link

---

app/components/namespace-app/template.hbs

[#14485](https://github.com/rancher/rancher/issues/14485)
Allow wrap in endpoints text, so all endpoints are shown and div expands to bottom instead of sidewards (where text is cliped, but div expands anyway).

Fixed wrong displayed endpoints

---

app/components/container/form-command/component.js
app/components/container/form-command/template.hbs

Only a `.spec.template.spec.restartPolicy` equal to` Always` is allowed for deployment, daemonset and statefulset
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/

Fix restart policy issue

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/utils/util.js

support `kube-api` and `kube-controller` in cluster yaml to keep them consistent with RKE cluster yaml.
User can use `kube-api` or `kube_api` in advanced cluster yaml.

Support kube-api and kube-controller in cluster options

---

app/authenticated/cluster/index/controller.js

https://github.com/rancher/rancher/issues/14459
As we need to show the max and min nodes in cluster dashboard, it is easier to just exclude unschedulable nodes.

Exclude unschedulable nodes from cluster dashboard

---

app/authenticated/cluster/projects/new-ns/controller.js
app/authenticated/cluster/projects/new-ns/route.js
app/authenticated/cluster/projects/new-ns/template.hbs
app/authenticated/route.js
app/components/modal-edit-namespace/template.hbs
app/models/namespace.js
app/router.js

This is the first of 2 prs for the new Resource Quotas work
This PR removes all refs to that resource. we will add these
back in when the backend is merged and the ui can be updated
rancher/rancher#14620
remove all references to loading `resourceQuotaTemplate`

Disable Resource Quota Templates route & resources

---

app/components/container-logs/component.js
app/components/container-logs/template.hbs

https://github.com/rancher/rancher/issues/14535
UI will get stuck if server sends a lot of frames in a very short time. The reason is we are using `$body.scrollTop() + $body.outerHeight()` inside `onmessage` callback.

Fix view log performance issue

---

app/components/container/form-volumes/component.js

When click 'Expand All', component didReceiveAttrs and set `volumesArray ` to `[]`. So I rename the function and execute only in component init.

 Fix volumes reset when click 'expand All' in create workload

---

app/authenticated/cluster/projects/index/controller.js
app/authenticated/cluster/projects/index/template.hbs
app/components/namespace-table/template.hbs
app/components/project-group/component.js
app/components/project-group/template.hbs

When a new user had a single project without a namespace we'd fall into branch where we'd see a duplicate no-data row.
The resulting table, a single project row, had incorrect col-span's due to the missing checkbox in the `sortable-table` headers.
rancher/rancher#15296

Display Project row only correctly (namespace-table)

---

translations/ja-jp.yaml
translations/zh-hans.yaml
translations/zh-hant.yaml

Small change to make it super obvious what each of the droplets are. With DigitalOcean there are a few variants since the latest slug updates and sometimes it's not obvious which droplet you have selected. Some even have the same CPU + RAM but slightly varying disk size for a different cost.
N/A
I am unable to get this running locally to provide a screenshot due to an openssl issue.

Display slug for digitalocean in node template creation

---

lib/shared/addon/mixins/display-image.js
translations/en-us.yaml

In workload list page, if there are workloads with sidecars. The image column will not show the image name. It only shows the count like `3 Images`.
If we are using istio, all of the workloads has at least two sidecars. It will be good if we can show the image name of first container in the pod.
n/a
n/a

Show the image name of first container

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/cluster-driver/driver-rke/template.hbs

The cluster creation ui for RKE was adding its own defaults. We added the new editor for these defaults to the settings pages but we were defaulting some of the props on the config so the new defaults were not coming through. 
rancher/rancher#15111
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, …

tweak rke cluster creation to handle the new cluster-defaults

---

app/authenticated/project/ns/index/template.hbs
app/components/namespace-table/template.hbs
app/containers/index/controller.js
app/containers/index/template.hbs
lib/shared/addon/components/sortable-table/component.js
lib/shared/addon/mixins/sortable-base.js

Given 70 workloads under namespace `A`.
We need to show 50 workloads of `A` in page 1 and show the left 20 workloads of `A` in page 2 first then we can show the workloads of other namespaces in page 2.
But now, it shows 30 workloads of namespace `A` first and 20 workloads of namespace `B` in page 1. And 40 workloads of `A` in page 2 .
https://github.com/rancher/rancher/issues/15515
n/a

Fix pagination issue for grouped resources

---

lib/shared/addon/components/save-cancel/component.js
lib/shared/addon/components/save-cancel/template.hbs

In add node template page, even the save button sate is `saving`. It is still clickable. Clicking the save button will trigger the `submit` method [source code link](https://github.com/rancher/ui/blob/master/lib/shared/addon/mixins/new-or-edit.js#L37) 
We can add `disabled=true` to the button, but it will change the color of the button. So I added a `doNothing` action for it.
n/a
n/a

Fix save button issue

---

app/components/form-healthcheck/component.js

Input 20 but requested field `initialDelaySeconds` is 110. 
Change can not pass to parent component.

Fix health check cannot update initialDelaySeconds

---

app/components/container/form-ports/component.js
app/components/container/form-ports/template.hbs
app/components/container/new-edit/template.hbs
app/models/workload.js
lib/shared/addon/utils/constants.js
translations/en-us.yaml

Given a deployment created by `kubectl`.
If you edit it in Rancher UI and update the port mapping, Rancher server will not created related nodePort service or clusterIP service automatically.
A warning message  can help user to notice that when users update a workload created by kubectl.
n/a
n/a

Warning message in ports section for workload not created by Rancher

---

translations/en-us.yaml

The current link takes you to Slack Apps, which has Incoming WebHooks functionality but lacks overriding params. This points the user to the legacy Incoming WebHooks to make sure they create the correct one. Filed https://github.com/rancher/rancher/issues/15569 to make sure this is being investigated/handled.
If …

Use the legacy incoming webhooks to support overriding channel

---

lib/shared/addon/github/service.js

The error message cannot display when auth Github failed.

Fix the error message cannot display when auth Github failed.

---

app/authenticated/cluster/projects/new-ns/template.hbs
app/components/namespace-quota-row/template.hbs
app/components/namespace-resource-quota/component.js
app/components/namespace-resource-quota/template.hbs
app/components/namespace-table/template.hbs
app/components/pod-row/template.hbs
app/components/progress-bar-multi/component.js
app/components/progress-bar-multi/template.hbs
app/components/workload-row/template.hbs
translations/en-us.yaml

Added a progress bar to the Namespace creation page that shows the remaining/total resources for a project if it has quotas enabled. Additionally if you had any Projects without namespaces in the Projects/Namespaces table at the cluster level you would not see the bulk action checkboxes, that has been fixed. 
rancher/rancher#15522
rancher/rancher#15646
N/A

Alert Users of Remaining Project Resource Quotas

---

app/authenticated/cluster/projects/new-ns/controller.js
app/authenticated/cluster/projects/new-ns/template.hbs
app/components/namespace-quota-row/template.hbs
app/components/namespace-resource-quota/component.js
app/components/namespace-resource-quota/template.hbs
app/components/progress-bar-multi/component.js
app/components/progress-bar-multi/template.hbs
app/styles/components/_tables.scss
app/templates/-ns-quota-progressbar.hbs
translations/en-us.yaml

Based on feedback from review I've tweaked the way the progress bar works when creating a NS for a project with quotas. 
rancher/rancher#15522
rancher/rancher#15687

Rework NS Quota Progress Bar

---

lib/global-admin/addon/mixins/saml-auth.js

If we were editing a SAML auth config (e.g., `pingConfig`) the `allowedPrincipalIds` list was being reset. Added a check for editing, if so we reuse the previous configs APIDs.
rancher/rancher#15769
N/A

If Editing Saml will no longer reset the allowedPrincipalIds on save

---

lib/global-admin/addon/mixins/authentication.js
lib/global-admin/addon/security/authentication/activedirectory/route.js
lib/global-admin/addon/security/authentication/adfs/route.js
lib/global-admin/addon/security/authentication/azuread/route.js
lib/global-admin/addon/security/authentication/freeipa/route.js
lib/global-admin/addon/security/authentication/keycloak/route.js
lib/global-admin/addon/security/authentication/openldap/route.js
lib/global-admin/addon/security/authentication/ping/route.js
lib/global-admin/addon/security/authentication/shibboleth/route.js
yarn.lock

Auth providers were not having editing param reset on route exit so that if you decided not to commit your changes by saving and left the route and came back, all the fields would still be in edit mode. 
rancher/rancher#15845
N/A

Reset editing on route exit for all auth providers

---

app/components/container/new-edit/component.js
app/models/workload.js

If we're scaling up or editing a workload container we would automatically add the `capAdd` & `capDrop` properties to the container. This was hosing up deployments created outside of rancher and then scaled via the rancher ui. 
rancher/rancher#15863
n/a

Remove capAdd & capDrop if array is empty

---

lib/shared/addon/mixins/preload.js

Mark schemas as all found so that a subsequent findAll() doesn't make another request

After preload all schemas are found

---

app/components/container/new-edit/component.js
app/models/workload.js
lib/shared/addon/utils/constants.js
translations/en-us.yaml

Adds bulkable redeploy action which sets an annotation and causes the pods of a workload to get recreated, and does the same on workload edit so that clicking Edit -> Save always results in a redeploy instead of being unpredictable.
rancher/rancher#13389
rancher/rancher#15863
rancher/rancher#15844

Redeploy action, update timestamp on edit so edit always redeploys

---

app/components/workload-row/component.js
app/models/workload.js
app/workload/template.hbs
package.json

You should not be able to edit, scale, or redeploy a workload of type=job.
Also cleanup `isReal`, which was just always true for workloads since 2.0.
rancher/rancher#15910

Jobs are not editable or scalable

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js

======
`flannel_backend_type` on the `networkConfig.options` object in the RKE config expects to be non-null. I added a default backend type to the RKE launch page. 
======
Bugfix
Linked Issues
======
rancher/rancher#15936
======
N/A

Set default backend type for Linux RKE hosts with flannel network

---

lib/shared/addon/components/form-certificate-row/component.js
lib/shared/addon/components/form-certificate-row/template.hbs
lib/shared/addon/components/form-ssl-rows/template.hbs
lib/shared/addon/components/form-ssl-termination/component.js
lib/shared/addon/components/form-ssl-termination/template.hbs
lib/shared/app/components/form-certificate-row/component.js
package.json
translations/en-us.yaml

======
Previously we only allowed users to create a TSL Ingress controller if they selected a certificate they created in rancher. We also have the capability to add a TLS Ingress controller by using the default certificate created my nginx so we can allow users to create a TLS Ingress without selecting a cert. 
======
New feature
Linked Issues
======
rancher/rancher#15021
rancher/rancher#16021
======
N/A

Allow TLS Ingress controller to be created without selecting a certificate

---

app/components/form-labels-annotations/template.hbs
app/models/ingress.js
lib/shared/addon/components/form-ssl-termination/template.hbs

======
Because the ingress model was missing the `canHaveLabels` property the detail page would filter out any labels that were present. This did not affect the annotations. 
======
Bugfix
Linked Issues
======
rancher/rancher#15096
rancher/rancher#16112
======
N/A

ingress model missing canHaveLabels property

---

lib/nodes/index.js

======
Rolling back lazy-loading on the node engine to fix a regression. If you visited either the `Node Drivers` or `Node Templates` routes before launching a cluster you would not see this issue, but if you try to add or use a node template from the add cluster you would see this. I've decided to roll this back because we dont add back _that_ much. We could roll this back into the shared repo but I prefer to keep this in a distinct engine because the decoupling is clean and easy to understand.  
======
Bugfix
Linked Issues
======
rancher/rancher#16122
======
N/A

Rollback lazy-load on nodes engine

---

app/mixins/verify-auth.js
app/verify-auth/route.js
lib/shared/addon/github/service.js
translations/en-us.yaml

======
Adds support for an additional redirect to pass the GitHub auth code to (only) another port on localhost, so that the same Rancher install can be used against a Rio UI on another port.

Allow forwarding github auth to other localhost ports

---

app/components/container-logs/component.js
app/components/container-logs/template.hbs
translations/en-us.yaml

======
Users requested having a way to copy container logs without copying the markup on the client. I added a download log button that strips the markup & prepended timestamp from the log content and downloads a plain text `container.log`
======
New feature
Linked Issues
======
rancher/rancher#16229
rancher/rancher#16253
======
N/A

Add 'Download Logs' to container logs

---

app/authenticated/cluster/nodes/index/controller.js
app/authenticated/cluster/nodes/index/template.hbs
app/components/container/form-ports/component.js
app/components/new-edit-ingress/template.hbs
app/ingresses/run/template.hbs
lib/shared/addon/capabilities/service.js
lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
lib/shared/addon/components/cru-private-registry/component.js
lib/shared/addon/components/cru-private-registry/template.hbs
lib/shared/addon/components/form-ingress-rows/component.js
lib/shared/addon/components/form-ingress-rows/template.hbs
lib/shared/addon/components/form-ingress-rule/template.hbs
lib/shared/addon/components/input-yaml/template.hbs
lib/shared/app/capabilities/service.js
translations/en-us.yaml

======
This PR adds logic to the UI to deal with cluster capabilities. Currently we have 4 new fields but only 3 are apart of this PR:
`ingressControllers`
`nodePoolScalingSupported`
`nodePortRange`
`l4loadBalancer` was added as well but we do not currently support l4 load balancers in the UI and this will be coming shortly in a different PR. 
======
New feature
Linked Issues
======
rancher/rancher#15105
======
`ingressControllers`: Adds a new row to ingress rule rows when creating/editing ingress. If there are multiple `ingressControllers` you will have a select, otherwise it will be static text of the default backend provider. 
If the selected `ingressController` has `customDefaultBackend` set to `false` then you should see the `Use As …

Add cluster capabilites ui

---

app/components/cru-secret/component.js

======
- Reson: when clone s2  to s1, `kind` in request body is `Opaque`, but `kind` in respond body have been changed to `opaque`, when clone s2 to s3, `kind: opaque` is a invalid option and get 422 error.
- Solution: Remove `kind` in request body because new a secret does not carry `kind`.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16219
======

Unable to clone a cloned secret

---

lib/shared/addon/components/metrics-summary/component.js
lib/shared/addon/components/metrics-summary/template.hbs

======
Now the graph is under an accordion. 
`accordion` component will add a `display: none` style for the accordion content.
Graph will do the re-draw when resize happens. It will calculate the width during the re-draw.
So it is safe to force to trigger the resize event when user expand the accordion for metrics
======
Linked Issues
======
======

Fix graph area bug

---

lib/monitoring/addon/components/cluster-dashboard/component.js
lib/monitoring/addon/components/cluster-dashboard/template.hbs

======
Graph become stale when switching from one cluster monitoring page to another
We need to force the graphs to re-render after switching from one cluster monitoring page to another
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16973
======

Fix graph issue when switching clusters

---

lib/shared/addon/components/cluster-driver/driver-azureaks/component.js
lib/shared/addon/components/cluster-driver/driver-azureaks/template.hbs
lib/shared/addon/components/cluster-driver/driver-googlegke/component.js
lib/shared/addon/components/cluster-driver/driver-googlegke/template.hbs
lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
lib/shared/addon/components/form-versions/component.js
lib/shared/addon/components/form-versions/template.hbs
lib/shared/addon/components/new-select/component.js
lib/shared/addon/utils/constants.js
lib/shared/addon/utils/parse-version.js
lib/shared/app/components/form-versions/component.js
translations/en-us.yaml

======
New api settings were added (`KubernetesDefaultVersion`, `KubernetesSupportedVersions`) to give us a centralized location to expose our default K8s version and supported version in range formats. This PR adds a new component that will sort and compare version only using versions that are within our ranges. 
======
New feature
Linked Issues
======
rancher/rancher#16113
rancher/rancher#15592
======
When launching any cluster you should see the latest version for Kube selected now regardless of provider. Additionally if the version is outside our two new settings for the ranges we should see either `experimental` or `unsupported` added to the list. In the case of unsupported you should not be able to select that option. 
new settings …

Consolidate version checking cluster logic

---

translations/zh-hans.yaml
translations/zh-hant.yaml

======
In Chinese, "登陆" means someone land on island, while you should use "登录" if you want to say login system by account. 
======
Linked Issues
======
======

[bugfix] Chinese translation wrong written

---

lib/shared/addon/components/cluster-driver/driver-amazoneks/template.hbs
translations/en-us.yaml

======
When setting Public IPs Exposed to false on creation of an eks cluster we should show a note that the user must select 2 subnets
======
Bugfix
Linked Issues
======
rancher/rancher#16766
======
N/A

Add note for private ips on EKS cluster re multiple subnets

---

app/models/storageclass.js

======
Fix setting the default flag on a storage class if the model doesn't already have an annotations object.
======
Bugfix
Linked Issues
======
rancher/rancher#15097

Fix storage class default flag

---

lib/shared/addon/components/cluster-driver/driver-rke/template.hbs

======
We weren't reading the correct parameter to display the text-muted class on the windows support label for rke clusters network config.
======
Bugfix
Linked Issues
======
rancher/rancher#16397
======
N/A

Fix incorrect styling of labels for rke windows support

---

app/authenticated/project/ns/index/template.hbs

======
The grouped namespace view on project level would list namespaces with no project as 'in this project' because we were checking if an  grouped ref obj exist. We need to check if the type exists because ns's with no group still have a ref object in the sortable table. 
======
Bugfix
Linked Issues
======
rancher/rancher#17219
======
N/A

Fix incorrect check on project namespaces for the grouped view

---

lib/nodes/addon/components/driver-vmwarevsphere/component.js
lib/nodes/addon/components/driver-vmwarevsphere/template.hbs
translations/en-us.yaml

This changes adds 4 params to vSphere node template:
- `vappIpprotocol`
- `vappIpallocationpolicy`
- `vappTransport`
- `vappProperty`
rancher/rancher#15817
rancher/machine#13
rancher/os#2490

Support vSphere network protocol profiles

---

lib/pipeline/translations/en-us.yaml

https://github.com/rancher/ui/blob/master/lib/pipeline/translations/en-us.yaml#L368
Related issue: [#17513](https://github.com/rancher/rancher/issues/17513 "#17513")
Changes:
- Fix typo:
`pileine` -> `pipeline`

Resolve typo issue 'pileine'

---

app/models/cluster.js
app/styles/abstracts/_variables.scss
app/styles/components/_banners.scss
app/styles/components/_growl.scss
lib/shared/addon/growl/service.js
translations/en-us.yaml

======
The UI was not providing any feedback to the user after a backup action was performed on the fly. From the backup action I added success and error checks that provide UX feedback via the Growl functionality.
======
Bugfix
Linked Issues
======
rancher/rancher#17504
rancher/rancher#17557
======

Provide UX feedback after backup now action is fired on cluster

---

lib/shared/addon/capabilities/service.js

======
Fix the issue that user cannot select LB for port mapping in imported cluster
As `enabled` field is not set in Imported clusters, therefor its nil
However, users should be able to select LB when the `enabled` field is nil
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17941
======

Fix the issue that user cannot select LB in imported cluster

---

app/apps-tab/detail/template.hbs
app/components/new-catalog/component.js
app/components/new-catalog/template.hbs
lib/global-admin/addon/components/new-multi-cluster-app/template.hbs
lib/shared/addon/components/form-key-value/component.js
lib/shared/addon/components/form-key-value/template.hbs
lib/shared/addon/components/input-answers/component.js
lib/shared/addon/components/input-answers/template.hbs
lib/shared/addon/components/input-custom-answers/component.js
lib/shared/addon/components/input-custom-answers/template.hbs
lib/shared/addon/utils/convert-yaml.js
lib/shared/app/utils/convert-yaml.js

======
Now catalog supports `valuesYaml` field. It means users can pass real yaml to backend.
> For multi-cluster apps:
As it doesn't support `valuesYaml` field in backend. So we need to hide the edit yaml button for it now. It will not impact the existing function.
> For normal catalog app:
- UI will send either `answers` or `valuesYaml` to backend. 
- If it is in YAML mode, it will send `valuesYaml` to backend only.
- If it is in form mode, it will send `answers` only.
- If there is a password type question and the value is a number, it will fallback to use `valuesYaml` even it is in form mode
======
Linked Issues
======
rancher/rancher#13158
rancher/rancher#16680
rancher/rancher#17605
Further …

Support valuesYaml for catalog

---

lib/global-admin/addon/multi-cluster-apps/catalog/launch/route.js
lib/shared/addon/components/form-members-global-access/template.hbs

======
Loads all multi-cluster app member principal info to ensure that we can add/remove members without any errors.
======
Bugfix
Linked Issues
======
rancher/rancher#18242
rancher/rancher#18152
======
An additional bug was found while I was working on the fix for this. The API will not allow you to upgrade an app when a member principal id is included that the current user can't view, e.g. logged in as a local user with github auth turned on and a github user present in the members array. This will be harder to validate until the following bug is resolved. IMO it would be safe to validate rancher/rancher#18242 if the multi-cluster app resource in the ui request when saving includes the new members in its member array. The API will …

Load multi-cluster-app principals so member info is ready

---

lib/shared/addon/components/cru-cluster/template.hbs

======
Don't show empty row when no provider is selected.
======
Linked Issues
======
======
From:
To:

Don't show empty row when no cluster driver.

---

app/instance-initializers/nav.js
app/styles/components/_button.scss
app/styles/pages/_host.scss
lib/nodes/addon/custom-drivers/cluster-drivers/template.hbs
lib/nodes/addon/custom-drivers/index/route.js
lib/nodes/addon/custom-drivers/node-drivers/template.hbs
lib/nodes/addon/custom-drivers/template.hbs
lib/nodes/addon/routes.js
lib/shared/addon/components/cru-cluster/component.js
lib/shared/addon/components/cru-cluster/template.hbs
server/proxies/api.js
translations/en-us.yaml

======
Enhancement
Linked Issues
======
rancher/rancher#18264
======
- Top nav: `Custom Drivers` -> `Drivers`
- Rename routes to be concise and readable (`/n/custom-drivers/{cluster|node}-drivers}` -> `/n/drivers/{cluster|node}`)
- Driver pages: Remove duplicate heading and move add button up to match other tabbed pages
- Add driver buttons: Fix RBAC checks, types need to be lowercase (but you can't exercise them because the schema never says you can't create drivers...)
- Add Cluster:
- Always show 4 sections (not a 5th one for "User" cluster drivers, they're still cluster drivers)
- If there are no enabled cluster drivers, show a message
- If there are no enabled node drivers, show a message
- Reverts rancher/ui#2669 …

Cleanup custom cluster drivers

---

lib/shared/addon/components/cluster-driver/driver-aliyunkcs/component.js
lib/shared/addon/components/cluster-driver/driver-aliyunkcs/template.hbs

======
We would like to fall back to use `searchable-select` for the k8s version on Aliyun hosted k8s 
Aliyun doesn't provide the api to get the available versions. 
We will move the aliyun cluster driver ui out of rancher ui as a long time solution.
Now we would like to support user input a k8s version which is not in the list.
So if Aliyun removed the current available k8s versions in Aliyun side. Rancher users can specify to use the new version without upgrading Rancher.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17827
======

Fix aliyun hosted k8s version issue

---

lib/nodes/addon/components/driver-vmwarevsphere/component.js

======
Fix default vmwarevsphere vapp properties. vSphere doesn't support spaces in expressions.
======
Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/15817
https://github.com/rancher/ui/pull/2308
======
Bug appeared in 3df948e9ab71b30533a98fd37bb32ce0cf730455

fix default vmwarevsphere vapp properties

---

lib/shared/addon/components/cluster-driver/driver-googlegke/component.js
lib/shared/addon/components/cluster-driver/driver-googlegke/template.hbs
lib/shared/addon/components/form-versions/template.hbs

======
kontainer engine framework doesn't support sync configuration back from providers.
For example, if you created a GKE cluster in Rancher UI. Then you go to the GKE console and update a configuration there.
In Rancher, the value for the configuration is still the old one as Rancher will not fetch the current configuration from GKE.
As they are newly added fields and they are not editable in Rancher UI, we can hide those fields in Rancher UI as we don't know the correct values for them.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18464
======

Hide GKE field when upgrade form 2.1

---

app/models/globaldns.js
lib/global-admin/addon/components/global-dns-entry-row/template.hbs
lib/global-admin/addon/global-dns/entries/new/controller.js
lib/global-admin/addon/global-dns/entries/new/route.js
lib/global-admin/addon/global-dns/entries/new/template.hbs

======
Prior to this we did not allow users to change the GDNS entry targets from MC app to Project and visa versa. The backend was updated to allow this. The ui will allow the user to move between the two on edit. It should null the multiClusterAppId when moving to project targets and vice versa. If the `addProject` action fails the UI will stay on the edit page with the error allowing the user to select a different project. 
======
Bugfix
Linked Issues
======
rancher/rancher#18366
======

All users to select project or mc app on gdns entry edit

---

lib/global-admin/addon/global-dns/providers/new/controller.js
lib/global-admin/addon/templates/-alidns-dns-provider.hbs
lib/global-admin/addon/templates/-route53-dns-provider.hbs
translations/en-us.yaml

======
Its okay to not include the secretKey for global dns providers that use this on the update call. This pr adds dropping that key if input was added but then removed.
======
Bugfix
Linked Issues
======
https://github.com/rancherlabs/rancher-security/issues/78
======
N/A

GDNS Provider - remove secret key param

---

lib/shared/addon/components/cluster-driver/driver-googlegke/component.js

======
1. Cannot pass null to the backend.
2. Some field can pass to GKE driver directory because GKE will ignore. For example:
3. `nodeCount` default value is `1`, so it needs reset to `0`.
4. According to `The IP address range for the cluster pod IPs. If this field set, then cluster.cluster_ipv4_cidr must be left blank.`, `clusterIpv4Cidr` needs to reset.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18853
======

Fix GKE cluster goes to updating after edit with no changes

---

lib/shared/addon/mixins/node-driver.js

======
Create a vShpere node template with memory 2048mb
But it shows 2048 GB in node template list
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18856
======

Fix vSphere node template size display issue

---

app/components/page-header-project/template.hbs
app/styles/components/_page-header.scss

======
Change hover color on projects so it's darker than active, move arrow to reflect the cluster you're looking at, add 1px divider so that if you select a cluster and project in the same row it's not just a floating arrow in a solid line of hover color.
======
Bugfix

Project hover, color, arrow, divider

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js

======
When upgrade form 2.1.7. Radio button value change `cluster.rancherKubernetesEngineConfig.services.etcd.snapshot` to `cluster.rancherKubernetesEngineConfig.services.etcd.backupConfig.enabled`.
It makes `backupConfig` is undefined, so it needs to init when edit cluster.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19122
======

Fix backupConfig is undefined when upgrade form 2.1.7

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js

======
When upgrade form 2.1.7. Radio button value change cluster.rancherKubernetesEngineConfig.services.etcd.snapshot to cluster.rancherKubernetesEngineConfig.services.etcd.backupConfig.enabled.
It makes backupConfig is undefined, so it needs to init when edit cluster.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19122
======

Fix backupConfig is undefined

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js

======
Only when `!etcd.snapshot && !etcd.backupConfig` meaning upgrade from 2.1.7.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19122
======

2.2-Fix backupConfig is undefined when upgrade form 2.1.7

---

.gitignore

ignore temp files left by dapper to avoid failing check for uncommitted changes

ignore temp Dockerfile.dapper

---

lib/shared/addon/components/custom-catalog/component.js

======
Add service to access settings which is used to print `appName`
======
Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/19215
======

Add service to access settings in custom-catalog view

---

app/components/cru-persistent-volume-claim/component.js
app/components/cru-persistent-volume-claim/template.hbs
app/components/cru-volume-claim-template/component.js

======
The problem is rancher when creating the PVC don't set the same storage class name for the PVC as the PV. The storage class name field in the PVC spec is an empty string instead of the correct storage class name. 
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19578
======

[2.3]Fix pvc issue

---

app/components/cru-persistent-volume-claim/component.js
app/components/cru-persistent-volume-claim/template.hbs
app/components/cru-volume-claim-template/component.js

======
The problem is rancher when creating the PVC don't set the same storage class name for the PVC as the PV. The storage class name field in the PVC spec is an empty string instead of the correct storage class name. 
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19578
======

[2.2.3]Fix pvc issue

---

app/components/container/form-ports/template.hbs

======
Select a workload and edit service (must had a port mapping)
Focus on docker image box and Press enter
Port mapping disappear
If users don't notice and press upgrade button, the service breaks.
This is kind of a HTML feature. When you press enter.
To improve the user experience, we should make `Add Port` be triggered when users press enter instead of `Remove Port`.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19109
======

Fix port form issue

---

app/components/page-header-project/component.js
lib/shared/addon/components/hover-dropdown/component.js

======
Added `isTransitioning` check to page-header-project and hover-dropdown components. We shouldn't open the dropdown if we're in the middle of a transition but the main culprit are the JQ events that are set on the dom to open and close the page header menu which also shouldn't open if we're in the middle of a transition. Created my own transition check because its not available in the router service and because the component is at the top level it never gets destroyed we can't use the events on the component class. 
======
Bugfix
Linked Issues
======
rancher/rancher#19300
======

Global Menu Open After Transition

---

app/authenticated/cluster/notifier/index/route.js
app/models/notifier.js
lib/alert/addon/edit-rule/route.js
lib/alert/addon/edit/route.js
lib/alert/addon/index/route.js
lib/alert/addon/new-rule/route.js
lib/alert/addon/new/route.js
lib/logging/addon/logging/route.js

======
In alerting and logging module, `findAll` is not used correctly in some cases.
We should use `find` instead of `findAll` if you would like to use `filter` option.
Many places are trying to do something like `findAll('notifier', { filter: { clusterId } })`
However, `findAll` will always returns `all`. So filter stuff won't work sometimes. For example, you will see this https://github.com/rancher/rancher/issues/19599#issuecomment-486828724
======
Linked Issues
======
======

[2.2.2]Fix findAll filter issue in alerting and logging

---

app/authenticated/cluster/notifier/index/route.js
app/models/notifier.js
lib/alert/addon/edit-rule/route.js
lib/alert/addon/edit/route.js
lib/alert/addon/index/route.js
lib/alert/addon/new-rule/route.js
lib/alert/addon/new/route.js
lib/logging/addon/logging/route.js

======
In alerting and logging module, `findAll` is not used correctly in some cases.
We should use `find` instead of `findAll` if you would like to use `filter` option.
Many places are trying to do something like `findAll('notifier', { filter: { clusterId } })`
However, `findAll` will always returns `all`. So filter stuff won't work sometimes. For example, you will see this https://github.com/rancher/rancher/issues/19599#issuecomment-486828724
======
Linked Issues
======
======

Fix findAll filter issue in alerting and logging

---

lib/shared/addon/components/storage-class/provisioner-azure-disk/component.js
lib/shared/addon/components/storage-class/provisioner-azure-disk/template.hbs
translations/en-us.yaml

======
"Unmanaged" disk has become redundant for Azure Disk based storage classes. Both  "kind: shared" and "kind: dedicated" options are unmanaged disk options. Added this indication to the labels in the dropdown so it is clear to the user. 
======
Bugfix
Linked Issues
======
rancher/rancher#19863
======
N/A

[2.2.3] Remove redundant storage option for azure disk storage class

---

translations/en-us.yaml

======
Add the properly cased name for `UpCloud` node driver.
There's already a working [UI Driver](https://github.com/montel-ig/ui-driver-upcloud) and [`docker-machine` driver](https://github.com/montel-ig/docker-machine-driver-upcloud).
======
- New feature
======
It could be useful to have a way to override the default _capitalized_ display name provided by the [`node-driver` model](https://github.com/rancher/ui/blob/master/app/models/nodedriver.js#L49). I'm not entirely familiar with Ember, but maybe a way to override the computed variable?

Add UpCloud node driver

---

lib/alert/addon/components/alert/form-recipients/component.js
lib/alert/addon/components/alert/form-recipients/template.hbs
lib/alert/addon/components/alert/new-edit/component.js
lib/pipeline/addon/components/pipeline-notifier/component.js
lib/pipeline/addon/components/pipeline-notifier/template.hbs

======
Make alert group recipients as non-required field
Backend PR:https://github.com/rancher/types/pull/792
This UI PR can be merged anytime. But we cannot validate it until backend PR in
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19611
======

[2.3]Make alert group recipients as non-required field

---

lib/alert/addon/components/alert/form-recipients/component.js
lib/alert/addon/components/alert/form-recipients/template.hbs
lib/alert/addon/components/alert/new-edit/component.js
lib/pipeline/addon/components/pipeline-notifier/component.js
lib/pipeline/addon/components/pipeline-notifier/template.hbs

======
Make alert group recipients as non-required field
Backend PR:https://github.com/rancher/types/pull/792
This UI PR can be merged anytime. But we cannot validate it until backend PR in
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19614
======

[2.2.x]Make alert group recipients as non-required field

---

app/components/accordion-container/template.hbs
app/components/accordion-pod/template.hbs
app/components/pod-row/template.hbs
app/components/workload-row/template.hbs
app/pod/template.hbs
app/workload/template.hbs
translations/en-us.yaml

======
Add a colon to the end of "Pod Restarts" and "Restarts" (generic.podRestarts, generic.restarts) for improved formatting and readability. One template has this but they all should where needed.
======
Bugfix, non-breaking
Linked Issues
======
https://github.com/rancher/rancher/issues/17891
======
Adds a colon in these areas:
Pod Restarts > Pod Restarts:
Restarts > Restarts:

Add colon to templates that utilize generic.restarts and generic.podRestarts

---

lib/shared/addon/components/cru-private-registry/component.js
lib/shared/addon/components/cru-private-registry/template.hbs
translations/en-us.yaml

======
The UX for the previous iteration of private registry at the cluster level was confusing as it was not quite clear what effect adding private registry did. The UX was simplified to only support a single private registry at this time. 
* You can only add one private registry to the cluster through the UI via `enable` / `disabled`
* The registry is defaulted to `isDefault` true and this is not configurable from the UI
* The copy in the accordion has been updated to add clarity as to what a private registry does at the cluster level. 
======
Refactor
Linked Issues
======
rancher/rancher#19345
======
N/A

[2.2.3] refactor private registry to simplify UX

---

app/styles/components/_page-header.scss

======
On low res (non-hidpi) displays with Firefox only the height of the main nav drops to 49px while the user nav always stays at 50. I'm not sure why it only happens on low-res screens only but we can resolve it by setting the height. This doesn't affect other browsers afaikt.
======
Bugfix
Linked Issues
======
rancher/rancher#19101
======
N/A

Add height to main nav for low-res screen firefox issues.

---

app/components/namespace-app/component.js
lib/global-admin/addon/components/multi-cluster-app/component.js
lib/shared/addon/components/catalog-box/component.js
lib/shared/addon/mixins/lazy-icon.js
lib/shared/app/mixins/lazy-icon.js

======
Refactor the generic icon loading to a mixin to be consumed in multiple components
Only fetch generic icon on render not init to avoid the double load issue as the app moves through states
======
Bugfix
Linked Issues
======
rancher/rancher#17668
======
N/A

Prevent Double Load of Generic Icon on MC Apps

---

app/components/machine/driver-amazonec2/component.js

======
This adds T3a, M5a, M5ad, R5a, R5d, and R5ad AWS instance types
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19826
======
The `a` and `ad` instance types are new and less expensive options for their counterparts.
Full details for each type are located at the pages below.
https://aws.amazon.com/ec2/instance-types/t3/
https://aws.amazon.com/ec2/instance-types/m5/
https://aws.amazon.com/ec2/instance-types/r3/

[1.6] Add additional AWS instance types

---

app/authenticated/cluster/storage/persistent-volumes/detail/edit/controller.js
app/components/cru-persistent-volume/component.js
app/components/cru-persistent-volume/template.hbs
app/components/volume-source/source-cinder/template.hbs
lib/shared/addon/components/input-or-display/component.js
lib/shared/addon/components/input-or-display/template.hbs
translations/en-us.yaml

======
Openstack Cinder volumes were updated in a previous release and the secret ref was never exposed with the schema update. This pr exposes the new ref. It also passes the correct "editing" mode to the components so they may display the inputs correctly in new vs edit. 
======
Bugfix
Linked Issues
======
rancher/rancher#19237
======
N/A

Expose Secret Ref for Cinder Persistent Volumes

---

app/authenticated/cluster/storage/persistent-volumes/detail/edit/controller.js
app/components/cru-persistent-volume/component.js
app/components/cru-persistent-volume/template.hbs
app/components/volume-source/source-cinder/template.hbs
lib/shared/addon/components/input-or-display/component.js
lib/shared/addon/components/input-or-display/template.hbs
translations/en-us.yaml

======
Openstack Cinder volumes were updated in a previous release and the secret ref was never exposed with the schema update. This pr exposes the new ref. It also passes the correct "editing" mode to the components so they may display the inputs correctly in new vs edit. 
======
Bugfix
Linked Issues
======
rancher/rancher#19237
======
N/A

[2.2.4] Expose Secret Ref for Cinder Persistent Volumes

---

lib/shared/addon/components/form-project-targets/component.js

======
`form-project-targets` was calling the `intl` service when it was not being included. This was causing a `uncaught type` error that would prevent the user from selecting a project. I removed the service and filtered out projects without clusters from the target dropdown. 
======
Bugfix
Linked Issues
======
rancher/rancher#20698
======
Why we have projects without clusters is being investigated by the backend team but we have no ticket right now.

Filter projects without clusters from MC apps targets

---

lib/shared/addon/components/form-project-targets/component.js

======
`form-project-targets` was calling the `intl` service when it was not being included. This was causing a `uncaught type` error that would prevent the user from selecting a project. I removed the service and filtered out projects without clusters from the target dropdown. 
======
Bugfix
Linked Issues
======
rancher/rancher#20857
======
Why we have projects without clusters is being investigated by the backend team but we have no ticket right now.

[2.2.x] Filter projects without clusters from MC apps targets

---

lib/global-admin/addon/clusters/new/route.js

======
1. UI should load js and ccs files only for active cluster drivers
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21108

[master]UI should load js and ccs files only for active cluster drivers

---

lib/global-admin/addon/clusters/new/route.js

======
rancher/rancher:v2.2.4
Steps:
Do not enable Baidu cluster driver
Click Add Cluster
Check the network tab in Chrome.
Results:
UI will load js files even for inactive cluster drivers
Expected:
UI should load js and ccs files only for active cluster drivers
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21109

[2.2.5]UI should load js and ccs files only for active cluster drivers

---

lib/logging/addon/components/logging/new-edit/component.js
lib/logging/addon/logging/controller.js
lib/logging/addon/logging/route.js
lib/logging/addon/logging/template.hbs

======
Remove refresh action after clicking the save button.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17782
======
When the first time clicks the save button, a model which is created by store changed to a model which found in store.  When the `model()` function begins, the cert disappear. And display after the request respond. In fact, using the responding data instead of request again will be a better solution. So I remove the refresh action.

Fix Fluentd target logging cert disappear after click test button

---

lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
translations/en-us.yaml

======
======
Enhancement
Linked Issues
======
rancher/rancher#21104
======
QA:
New field is located in Advanced Cluster Options -> etcd Snapshot Backup Target = s3 -> Custom CA Certificate or `rancherKubernetesEngineConfig.services.etcd.backupConfig.s3BackupConfig.customCa` via the api.

[2.2.5] Add custom CA option to s3 backup config for rke clusters

---

lib/shared/addon/components/cluster-driver/driver-azureaks/component.js

======
The AKS UI dies if a virtual network has `null` subnets
======
Bugfix

[2.2] AKS: Don't explode if subnets is null

---

lib/shared/addon/components/cluster-driver/driver-azureaks/component.js

======
The AKS UI dies if a virtual network has `null` subnets
======
Bugfix

AKS: Don't explode if subnets is null

---

app/models/nodetemplate.js

======
Location and Size fields can not display correctly for newly added node driver in node template list page.
We don't want to change Rancher UI code for a new custom node driver.
Add default displayLocation key (config.region) and displaySize key (config.size) in nodetemplate.js file for Node Template Table
If a custom node driver has these two keys, we can show them correctly in node template list page.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21277

[master]Location and Size fields can not display correctly for newly added node driver in node template list page

---

app/components/modal-rotate-certificates/component.js
app/components/modal-rotate-certificates/template.hbs
app/models/cluster.js
app/styles/components/_tooltip.scss
app/styles/themes/_dark.scss
app/styles/themes/_light.scss
lib/global-admin/addon/components/cluster-row/template.hbs
lib/monitoring/addon/components/cluster-dashboard/component.js
lib/monitoring/addon/components/cluster-dashboard/template.hbs
lib/shared/addon/components/tooltip-expiring/component.js
lib/shared/addon/components/tooltip-expiring/template.hbs
lib/shared/app/components/tooltip-expiring/component.js
translations/en-us.yaml

======
Adds new logic to expose a warning when clusters certificates will be expiring in 30 days or less.
At the global level when a cluster has certs that are expiring there will be a small warning icon next to the cluster name with a tooltip explanation and link action to open the rotate certs modal. 
At the cluster level on the cluster page you will see a warning banner above your cluster details with the same explanation/link action that opens the rotate certs modal. 
In the rotate certs modal you will see the cert selection dropdown now adds the time in days until expiration. One choice that may confuse but was talked through with @moelsayed affects the etcd service.  Rke alerts us of every etcd node that has a cert expiring. In the UI we only show the date from the …

Add ui warning about expiring certificates

---

lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
translations/en-us.yaml

======
======
Enhancement
Linked Issues
======
rancher/rancher#20829
======
QA:
New field is located in Advanced Cluster Options -> etcd Snapshot Backup Target = s3 -> Custom CA Certificate or `rancherKubernetesEngineConfig.services.etcd.backupConfig.s3BackupConfig.customCa` via the api.

Add custom CA option to s3 backup config for rke clusters

---

lib/logging/addon/components/logging/new-edit/component.js

======
Fix click save button again, logging config disappear.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21426
======
The fluentForwarderConfig is null when the second save.  So reset a type which can be found in the schema and `createRecord` can fix the issue.

Fix click save button again, logging config disappear

---

app/models/cloudcredential.js
lib/global-admin/addon/components/cru-cloud-credential/component.js
lib/global-admin/addon/components/cru-cloud-credential/template.hbs
lib/shared/addon/mixins/node-driver.js
translations/en-us.yaml

This PR seeks to add support for storing Linode Cloud Credentials
This may be incomplete in its current state and may warrant more discussion about what to do for external node drivers.  A Linode Cloud Credential will also be usable for Linode Global DNS options, which other PRs will begin to address.
Depends on rancher/rancher#20281

add Linode cloud credential

---

lib/global-admin/addon/cluster-templates/new-revision/controller.js
lib/global-admin/addon/cluster-templates/new-revision/template.hbs
lib/global-admin/addon/clusters/index/controller.js
lib/global-admin/addon/clusters/index/route.js
lib/global-admin/addon/clusters/index/template.hbs
lib/global-admin/addon/clusters/new/launch/route.js
lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
lib/shared/addon/components/cru-node-pools/template.hbs
lib/shared/addon/components/cru-private-registry/component.js
lib/shared/addon/components/empty-table/template.hbs
lib/shared/addon/settings/service.js
translations/en-us.yaml

======
Adds cluster template enforcement logic when the global setting is enabled. 
Global Admin is not effected by cluster template enforcement.
Users who have no cluster templates when enforcement is enabled will not be able to select the launch cluster button and will be presented with a tooltip.
Users who have one template will be taken to the cluster add page with the default revision of the single template they have selected as the cluster template to launch with.
Users who have < one cluster template will be presented with the cluster add page with no default selected. These users will not see the cluster options until they select a template. 
======
Enhancement
Linked Issues
======
rancher/rancher#21378
rancher/rancher#21576
rancher/rancher#21679 …

Cluster Template Enforcement

---

app/catalog-tab/controller.js
app/catalog-tab/index/controller.js
app/catalog-tab/index/template.hbs
app/catalog-tab/route.js
app/styles/pages/_catalog.scss
lib/global-admin/addon/multi-cluster-apps/catalog/controller.js
lib/global-admin/addon/multi-cluster-apps/catalog/index/controller.js
lib/global-admin/addon/multi-cluster-apps/catalog/index/template.hbs
lib/global-admin/addon/multi-cluster-apps/catalog/route.js
lib/pipeline/addon/components/steps/step-apply-catalog/component.js
lib/shared/addon/catalog/service.js
lib/shared/addon/components/catalog-box/component.js
lib/shared/addon/components/catalog-index/component.js
lib/shared/addon/components/catalog-index/template.hbs
lib/shared/addon/components/searchable-select/component.js
lib/shared/addon/utils/constants.js
translations/en-us.yaml

======
- Group catalog templates in the launch screen by catalog
- Drops the catalog picker (because you see groups now) and the query params for it
- Fixes category filtering so that it works again
- Removes all the query param -> router refreshModel -> fetchTemplates -> filters everywhere -> needsRefresh -> ... maze
- Buy now and also get browser autocomplete disabled on {{searchable-select}}s
======
Multitudious
Linked Issues
======
rancher/rancher#21895
rancher/rancher#20602
======
A while ago the catalog-index component was changed to use the live templates array.
This broke a few things, but all the caching and refreshModel and filtering around it doesn't really make sense anymore.
- `fetchTemplates()` now just loads all the …

You are in a maze of twisty catalog logic, all slightly different

---

lib/shared/addon/mixins/subscribe.js

======
Due to a typo in `const state = get(this, 'watchState.relevantState');`, the state will be always `undefined`.
So it means every time the state of the cluster changed, the cluster websocket will be closed. And it will never get re-connected.
The lines removed in this PR is only used for cluster websocket. It doesn't work since day one. There is another logic to deal with the case which cluster state changed from inactive to active state. As the function is never used before, so we can just remove them directly.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20988
======

Fix auto-reconnect ws issue

---

app/components/input-edit-password/component.js
app/components/input-edit-password/template.hbs
app/components/modal-edit-password/template.hbs
lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
lib/shared/addon/components/form-versions/component.js
package.json
translations/en-us.yaml

======
Adds a checkbox option to delete all existing API keys (that the user can see) when changing your password.
======

Delete keys option on change password

---

lib/nodes/addon/custom-drivers/cluster-drivers/controller.js
translations/en-us.yaml

======
1. Fix typo on Pipelines warning in windows cluster.
2. Fix wrong file type for rancher-images download.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20951
https://github.com/rancher/rancher/issues/22422
======

[2.3.0] Fix typo and rancher-images issue

---

app/authenticated/cluster/template.hbs

======
Match the "This custer is currently <State>; areas that interact..." message banner color to the state of the cluster so that it's not always red.
======

Match provisioning banner to cluster state color

---

app/models/cluster.js
app/models/nodepool.js
jsconfig.json
lib/global-admin/addon/accounts/index/template.hbs
lib/shared/addon/components/cru-node-pools/component.js

======
Adds the ability to edit clusters that have nodepools which use nodetemplates that the current user can't see (because they are not sharable yet).
Previously in 2.2 the pools were preserved by the UI but not displayed so you couldn't manage them.  And in 2.3/master the rest of the cluster options wree missing due to now knowing what driver to use.
The template will show up in the dropdown as its ID (user-xxxxx:nt-yyyyy) since that's the only info we have.
Requires pending backend change to add `driver` field to `nodePool` resources (backed by nodePool.nodeTemplateId -> nodeTemplate -> nodeTemplate.driver)
======
Linked Issues
======
rancher/rancher#22080

Edit clusters using node templates you can't see (rancher/rancher#22080)

---

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js

Default to m5.large for EKS

---

app/authenticated/cluster/edit/route.js
lib/shared/addon/components/cluster-driver/driver-rke/component.js

======
Disables 2 places that were copying the values from question answers on top of the cluster config, which was overwriting the current rkeConfig.kubernetesVersion=(actual version deployed) with the 1.14.x requested value (that the backend later turns into a concrete version).
======
- Bugfix
Linked Issues
======
rancher/rancher#22085

Don't overwrite cluster config with answers on edit (rancher/rancher#22085)

---

lib/shared/addon/components/confirm-delete/component.js
lib/shared/addon/components/confirm-delete/template.hbs
lib/shared/addon/utils/constants.js
translations/de-de.yaml
translations/en-us.yaml
translations/es-es.yaml
translations/fr-fr.yaml
translations/hu-hu.yaml
translations/ja-jp.yaml
translations/ko-kr.yaml
translations/nb-no.yaml
translations/pt-br.yaml
translations/ru-ru.yaml
translations/tr-tr.yaml
translations/uk-ua.yaml
translations/zh-hans.yaml
translations/zh-hant.yaml

Adds the resource types "namespace", "cluster", "project" as
additional context to the titles of the respective deletion modals
in order to reduce the likelyhood of a user accidentally deleting
an unintented resource.
We changed the title from "Are you sure you want to delete" to
"Are you sure you want to delete the namespace:" with namespace
being bold. The same is true for cluster and project as well.
rancher/rancher#17619
The change where the deletion occurs on a namespace resource type:
The change where the deletion occurs on a project resource type:
The change where the deletion occurs on a cluster resource type:
The change where the deletion occurs on a non-elevated resource type:

Add more context to the title of deletion modals

---

app/components/page-header/component.js
app/styles/components/_page-header.scss

======
In the navigation menu when a user attempted to open a sub-menu the
entire navigation menu instantly closed. To resolve this we now listen
to the router willTransition event to close the navigation rather than
a willRender invocation.
The sub-menu was also overlapping other menu items because it had an
absolute position. To resolve this we now give the sub-menu a static
position.
Old menu:
New menu:
Unaffected desktop menu:
======
Linked Issues
======
rancher/rancher#21914

Improve the mobile sub-navigation UX

---

lib/nodes/addon/components/driver-azure/component.js

======
When editing Azure node templates we failed to
preserve the state of 'Use Private IP To Connect 'when the value of
public ip was 'Static' or 'Dynamic'. We were erroneously overwriting the
value of config.usePrivateIp to false when those public ip values were
chosen.
======
Linked Issues
======
rancher/rancher#22752

Preserve state of 'Use Private IP To Connect'

---

app/authenticated/route.js
app/components/cru-persistent-volume/component.js
app/components/cru-storage-class/component.js
app/components/cru-volume/component.js
app/models/storageclass.js
app/models/volume.js

======
We want to make it more difficult to use unsupported storage providers
to reduce the likelihood of a user accidently using one of these
storage providers.
Persistent storage filtered:
Storage class filtered:
Ephemeral volume filtered:
======
Linked Issues
======
rancher/rancher#22895
======
This is blocked until this is merged rancher/rancher#22899. It may be the case that this will by default filter without the feature flag but I'd be reluctant to merge without it.

Hide unsupported storage providers

---

app/styles/components/_identity-block.scss
app/styles/components/_page-header.scss

======
In mobile the user menu was being overlapped by the main content.
To fix this we just needed to update the z-index of the user menu.
Broken:
Fixed:
======
Linked Issues
======
rancher/rancher#21914

Prevent main content from overlapping user menu

---

lib/shared/addon/components/share-member-row/component.js

======
While editing a cluster template when the template was shared with a
group the group was not visible under the Share Template section. We
needed to ensure that the group was visible.
The reason that this was occurring was because we weren't fetching the
principal for the group because we were only fetching when the
userPrincipalId was present and not when the groupPrincipalId was
present.
Old:
New:
======
Linked Issues
======
rancher/rancher#22971

Make groups visible when editing cluster template

---

lib/shared/addon/components/authorized-endpoint/component.js

======
When creating a cluster using a template localClusterAuthEndpoint was not
using the value provided by the template.  The component assumed that
localClusterAuthEndpoint was a boolean when it was in fact a string that
represented a boolean. To resolve this a string comparison needed to
be made.
======
Linked Issues
======
rancher/rancher#22972

Use template value for localClusterAuthEndpoint

---

lib/shared/addon/components/cluster-driver/driver-rke/template.hbs

======
When selecting a cluster template revision to use when launching a cluster via a template the revision would change the URL and subsequently would not reload the new model and values. This was because the select for this component was attached to the clusterTemplateRevisionId on the model being passed down from the launch route, we specifically pass down `clusterTemplateRevisionId` that is watched as a query param and is marked as mutable. I switched the select to use this param and all works as expected. 
======
Bugfix
Linked Issues
======
rancher/rancher#22977
======
N/A

Cluster Template Revision Select Bug

---

app/catalog-tab/launch/route.js

======
When upgrading an application the template version was set to the
default version instead of the apps current version.
When a current version is present we now use it instead of the
default.
======
Linked Issues
======
rancher/rancher#23051

Use current template version for app upgrades

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
lib/shared/addon/components/cluster-templates-table/template.hbs
lib/shared/addon/components/form-versions/component.js
translations/en-us.yaml

======
This PR contains various bug fixes for RKE Templates
Hides the `Custom Clusters Overrides` section when launching a RKE cluster with a template.
Fixes pagination label for the bulk selector for RKE templates.
Fixes version displayed when cloning an RKE template that used the Major.Minor version.
Fixes data becoming out of sync between form value and override section value when cloning an RKE template. 
Fix k8s version dropdown when editing cluster with prohibited k8s version in the dropdown.
======
Bugfix
Linked Issues
======
rancher/rancher#23056
rancher/rancher#23065
rancher/rancher#23068
rancher/rancher#23069
rancher/rancher#23085
======
N/A

RKE Template Bugs

---

app/models/cluster.js
app/models/clustertemplate.js
app/styles/_rancher.scss
app/styles/base/_icons.scss
app/styles/components/_banners.scss
app/styles/components/_cluster-template-revision-upgrade-notification.scss
app/styles/components/_tables.scss
lib/global-admin/addon/clusters/index/route.js
lib/global-admin/addon/components/cluster-row/template.hbs
lib/monitoring/addon/components/cluster-basic-info/template.hbs
lib/monitoring/addon/index/route.js
lib/shared/addon/components/cluster-template-revision-upgrade-notification/component.js
lib/shared/addon/components/cluster-template-revision-upgrade-notification/template.hbs
lib/shared/app/components/cluster-template-revision-upgrade-notification/component.js
translations/en-us.yaml

======
We want to make it easier for someone that is managing multiple
clusters to see what template and template revision a cluster
is using. We also want to make it easy for a user to notice
that a cluster isn't using the latest revision.
To achieve this we added the template and revision to a column
in the clusters table to display both. We also indicate add
a warning badge beside a revision when the revision isn't
the latest.
Screenshots:
======
Linked Issues
======
rancher/rancher#22047

Include Template/Revision Upgrade Notifications

---

app/components/input-edit-password/component.js
app/components/input-edit-password/template.hbs
app/components/modal-edit-password/template.hbs
translations/en-us.yaml

======
Backporting checkbox option to delete all existing API keys (that the user can see) when changing your password.
======
Bugfix
Linked Issues
======
n/a
======

[2.2.9] Backport 2.2: Add UI element to invalidate User API Keys when resetting password

---

app/components/container/form-ports/template.hbs

======
when deploying workloads with an Istio sidecar the port maps require a specific
name to be entered by the user, http. I've exposed the name param  but do not
autofill the name, this will be a documentation concern.
======
Bugfix
Linked Issues
======
rancher/rancher#23105
======
N/A

expose name param on workload port mapping

---

app/models/cluster.js
app/models/clustertemplate.js
lib/monitoring/addon/components/cluster-basic-info/template.hbs

- We will only conditionally render template/revision section on the
monitoring page if the cluster is using a template. This was
crashing the page before.
- We will now make sure there's a string when invoking replace
when generating the template and revision display names.
- We will now respect the enable flag of template revisions
when determining if an upgrade is available.
======
Linked Issues
======
rancher/rancher#23126

Improve robustness of showing template/revision

---

lib/istio/addon/project-istio/template.hbs

======
When adding the vitual services and destination rules are enabled we were
showing the import yaml button twice. It needs to be visible on both tabs and we
should be able to pass the or to the rbac check so I removed the duplicates and
moved the button to before the potential other buttons in the istio nav.
======
bugfix
Linked Issues
======
rancher/rancher#23155
======

dedup import yaml button when istio feature flag is enabled

---

app/models/cluster.js
app/models/clustertemplate.js

======
The cluster upgrade notification wasn't properly updating when
the user enabled and disabled a revision. It required that the
page was refreshed before display the fresh data.
This resolves this issue by watching more appropriate keys
int he relevant computed properties. The most relevant
being the revision.@each.enabled on the latestRevision property.
======
Linked Issues
======
rancher/rancher#23126

Use more appropriate keys to watch on @computed

---

lib/shared/addon/components/form-members/component.js
lib/shared/addon/components/form-members/template.hbs
lib/shared/addon/components/project-member-row/component.js
lib/shared/addon/components/project-member-row/template.hbs
translations/en-us.yaml

======
project-member-row was using `avatarSrc` on its component which was slightly
different then the same code used in the principal model but really should have
been the same. I got rid of the duplicate code in the component since the model
is the data owner. It really should manage the avatar source building.
I also updated single quotes to doubles in template and refactored the owner
logic since it wasn't doing anything extra that the noUpdate flag was doing.
======
Bugfix
Linked Issues
======
rancher/rancher#21440
======

[2.3.2] Ensure project-member-row uses same identicon as principal model

---

app/components/modal-edit-setting/component.js
app/models/cloudcredential.js
app/models/project.js
lib/global-admin/addon/components/registry-catalog/component.js
lib/global-admin/addon/security/cloud-credentials/index/controller.js
lib/global-admin/addon/security/cloud-credentials/index/template.hbs
lib/istio/addon/components/modal-delete-istio/component.js
lib/shared/addon/azure-ad/service.js
lib/shared/addon/mixins/crud-catalog.js
lib/shared/addon/oauth/service.js
lib/shared/addon/saml/service.js
translations/en-us.yaml

======
We want to provide a quick way to delete unused cloud credentials.
To do this we're going to show the user the number of node templates
that each cloud credential is associated with.
======
Linked Issues
======
rancher/rancher#23064

[2.3.2] Add # Node Templates column to cloud credentials

---

lib/monitoring/addon/components/enable-monitoring/template.hbs

======
The Grafana storage options were confusingly in the middle of the
Prometheus options on the Cluster Monitoring Configuration page.
To resolve this we moved the Grafana options to be below the
Prometheus options and above the advanced otpions.
======
Linked Issues
======
rancher/rancher#22885

Move Grafana options to own section

---

app/authenticated/cluster/notifier/index/route.js
lib/alert/addon/new-rule/route.js
lib/alert/addon/new/route.js
lib/istio/addon/project-istio/destination-rules/index/route.js
lib/istio/addon/project-istio/graph/route.js
lib/istio/addon/project-istio/rules/route.js
lib/istio/addon/project-istio/virtual-services/index/route.js

======
It seems the previous way that the cluster id and project id was fetched from
various addons (alerts and istio) does not work in ember 3.12. After some
investigation it wasn't the correct way to grab those parameters anyway. I've
changed the routes to use the scope service which has the current cluster and
project (if in one) rather than fetch the query params off a parent route
outside the engine.
======
Bugfix
Linked Issues
======
rancher/rancher#23207
======
N/A

Fix routing issues post ember upgrade

---

app/catalog-tab/launch/route.js

======
When upgrading an application the template version was set to the
default version instead of the apps current version.
When a current version is present we now use it instead of the
default.
======
Linked Issues
======
rancher/rancher#23208

[Backport] Use current template version for app upgrades

---

lib/istio/addon/components/istio-catalog/template.hbs
lib/istio/translations/en-us.yaml
lib/shared/addon/components/form-members-catalog-access/component.js
lib/shared/addon/components/form-members-catalog-access/template.hbs
lib/shared/addon/components/input-identity/component.js
lib/shared/addon/components/input-identity/template.hbs
lib/shared/addon/components/principal-search/component.js

======
Due to some oddities in the way that Istio currently allows access to members to
the kiali and jaeger ui's we've decided to restrict the member search to groups
only. I've changed the verbiage on the labels to reflect this. Additionally I've
also exposed the searchOnlyGroups param on the principal search component. I did
not expose the user only param because this is not something we're normally
going to be doing.
======
Bugfix
Linked Issues
======
rancher/rancher#23215
======
I've left the original UI code that correlates the principals to users and manipulates the ID that is passed to Istio until we have a better solution on the backend to handle the RBAC.

Restrict Istio member access to groups only

---

lib/shared/addon/components/cluster-driver/driver-rke/template.hbs

Backport https://github.com/rancher/ui/pull/3416 to 2.3-fixes branch

[Backport] Change windows docker version for custom clusters

---

lib/shared/addon/components/used-percent-gauge/component.js

======
Fix cluster dashboard cannot display after enable monitoring.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/23300
======
Related commit:
https://github.com/rancher/ui/commit/0f85e74fecc42181d69f9a3b6af77310233f4e9e

[forwardport] Gauges in cluster dashboard are missing when monitoring enabled in 2.3.0

---

.gitignore
lib/shared/addon/components/scheduling-toleration/component.js
lib/shared/addon/components/scheduling-toleration/template.hbs

======
Tolerations have two special cases that are not represented in the UI but are still valid.
> An empty key with operator Exists matches all keys, values and effects which means this will tolerate everything.
> An empty effect matches all effects with key key.
In these cases where we target *all* of something I am using the global operator (`*`) to denote these targets. Additionally when you edit the inputs will be empty for these, which is valid because technically the field doesn't exist. This ensures that when you save the workload or pod with tolerations they are saved correctly. 
======
Bugfix
Linked Issues
======
rancher/rancher#18605 
======

Display Atypical Tolerations Correctly

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js

======
The current kubernetes version wasn't being shown if it was no
longer a part of the supported versions when in view mode. Instead
the latest version was being displayed even if that wasn't what was
deployed. To resolve this we include the current version as one of
the choices if it's not present.
======
Linked Issues
======
rancher/rancher#23465

Ensure the current Kubernetes version can display

---

lib/monitoring/addon/components/enable-monitoring/template.hbs

======
The Grafana storage options were confusingly in the middle of the
Prometheus options on the Cluster Monitoring Configuration page.
To resolve this we moved the Grafana options to be below the
Prometheus options and above the advanced otpions.
======
Bugfix
Linked Issues
======
rancher/rancher#22885
======

[Backport] Move Grafana options to own section

---

app/models/template.js
lib/global-admin/addon/multi-cluster-apps/catalog/index/controller.js
lib/shared/addon/utils/constants.js
translations/en-us.yaml

======
The certified property on the catalog template model was not watching the intl.locale so when switching languages these keys never updated. 
======
rancher/rancher#23322
Linked Issues
======
Bugfix
======
I believe this bug caused the side effect of the translation for partner/experimental being borked when the backend refreshed the templates and the view reloaded. I could not reproduce it locally and it only happens intermittently for others with no JS Errors so I am not 100% sure this will resolve that but it was a bug and needed to be fixed.

Fix Partner/Experimental Tag Translation

---

lib/shared/addon/components/check-override-allowed/template.hbs
lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/cluster-driver/driver-rke/template.hbs

======
the check-override-allowed component did not know how to deal with the k8s
version question because of its tri state and how we deal with the patch version
that is an override but not really an override. I added a check to verify the
mode is view and we have the param then display param so we don't initialize the
form-version component which has logic to inject the current version into its
versions dropdown (code we added yesterday) but only if we're new, editing, or cloning.
======
Bugfix
Linked Issues
======
rancher/rancher#23478
rancher/rancher#23465
======

[2.3.x] Display k8s version in all modes of rke driver

---

lib/global-admin/addon/components/new-multi-cluster-app/component.js
lib/global-admin/addon/components/new-multi-cluster-app/template.hbs

======
This enables '.' to be a valid character in answer varaibles.
So we can support sub.key as a key now.
This also resolves a double render issue that was ran into while
reproducing this issue.
======
Linked Issues
======
rancher/rancher#23379
======

Enable '.' in answer variables

---

lib/shared/addon/components/cluster-driver/driver-googlegke/component.js
lib/shared/addon/components/cluster-driver/driver-googlegke/template.hbs
lib/shared/addon/components/gke-access-scope/template.hbs

======
We want the user to be able to see the security options that were
selected even if they can't be edited when editing the cluster.
Old edit missing security options:
New edit with security options for default access:
New edit with security options for full access:
New edit with security options for custom access:
======
Linked Issues
======
rancher/rancher#19070

[WIP] Display security options when editing GKE cluster

---

lib/nodes/addon/custom-drivers/cluster-drivers/controller.js

======
When a standard user attempted to fresh kubernetes metadata on
the drivers/cluster page it would result in an error notification that
stated 'undefined'. This will allow the backend error message
to surface.
======
Linked Issues
======
rancher/rancher#23535
======

Surface Refresh Kubernetes Metadata error message

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js

======
While editing a cluster properly support .x kube version comparisons when
filtering out cluster template revisions.
Coercing a .x version converts it to a .0 which made the revision look like
it was a kube downgrade. By making use of .satisfies when the revision
kube version ends with a '.x' we're now better able to check if the
kube version is a downgrade and filter appropriately.
======
Linked Issues
======
rancher/rancher#23489

Improve kube version inspection on cluster edit

---

lib/shared/addon/components/form-members-catalog-access/component.js

When adding a github group to be an instio member we wanted the
appropriate Member Type to be displayed. We wanted 'Organization'
instead of 'group'.
We noticed that addAuthorizedPrincipal was being invoked with a newly
created member object instead of just passing the principal. Since
everything we could inspect code wise expected a principal instead
of a member I went ahead and just passed the principal.
rancher/rancher#23264
======
======
Linked Issues
======
======

Ensure istio member type is correct on add

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js

======
While editing a cluster properly support .x kube version comparisons when
filtering out cluster template revisions.
Coercing a .x version converts it to a .0 which made the revision look like
it was a kube downgrade. By making use of .satisfies when the revision
kube version ends with a '.x' we're now better able to check if the
kube version is a downgrade and filter appropriately.
======
Linked Issues
======
rancher/rancher#23578

[forwardport] Improve kube version inspection on cluster edit

---

lib/nodes/addon/custom-drivers/cluster-drivers/controller.js

======
When a standard user attempted to fresh kubernetes metadata on
the drivers/cluster page it would result in an error notification that
stated 'undefined'. This will allow the backend error message
to surface.
======
Linked Issues
======
rancher/rancher#23589
======

[forwardport] Surface Refresh Kubernetes Metadata error message

---

lib/shared/addon/helpers/array-includes.js

======
Invoking the constructor instead of just a method causes an error.
This resolves that error.

Deprecate array constructor usage

---

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js

======
After pressing the 'create' button of the EKS driver the user was being
transitioned back to step 3 (Vpc & Subnet) rather than waiting on the
final page until the save is complete and returning to the cluster page.
An observer was being triggered by the save process which subsequently
set the step back to 3. To resolve this we will only enter the branch if
there are initialized values that need to be set back to default.
======
Links to issues
======
rancher/rancher#23609

[forwardport] Fix EKS cluster creation transition

---

lib/shared/addon/components/form-members-catalog-access/component.js

======
When adding a github group to be an instio member we wanted the
appropriate Member Type to be displayed. We wanted 'Organization'
instead of 'group'.
We noticed that addAuthorizedPrincipal was being invoked with a newly
created member object instead of just passing the principal. Since
everything we could inspect code wise expected a principal instead
of a member I went ahead and just passed the principal.
======
Linked Issues
======
rancher/rancher#23612

[forwardport] Ensure istio member type is correct on add

---

lib/shared/addon/components/form-versions/component.js

======
When editing a cluster that was created with a template and then selecting a new template to upgrade the cluster to we were not selecting the correct Kubernetes version from the override.
======
Bugfix
Linked Issues
======
rancher/rancher#23616
======
N/A

Select correct k8s version when changing templates

---

lib/shared/addon/components/form-versions/component.js

======
When editing a cluster that was created with a template and then selecting a new template to upgrade the cluster to we were not selecting the correct Kubernetes version from the override.
======
Bugfix
Linked Issues
======
rancher/rancher#23682
======
N/A

[Forwardport] Select correct k8s version when changing templates

---

lib/nodes/addon/components/driver-vmwarevsphere/component.js
lib/nodes/addon/components/driver-vmwarevsphere/template.hbs
translations/en-us.yaml

======
1. Parse the 'key=value' format of custom attributes
1. We weren't initializing custom attributes because we were not parsing the backend format appropriately. We needed to parse the 'key=value'.
1. Remove cloneFrom and contentLibrary while not used
1. If cloneFrom and contentLibrary shouldn't be used we delete them from the config to prevent them from going being a part of the request.
1. Make creationType use the appropriate values
1. creationType was using the wrong values after refactoring to combine two dropdowns into one. I renamed the existing config.creationType to creationMethod and now observe creationMethod to properly set config.creationType.
======
Linked Issues
====== …

Vsphere master parity with 2.3-fixes

---

app/models/nodetemplate.js
lib/nodes/addon/components/node-template-row/template.hbs
lib/nodes/addon/node-templates/controller.js
lib/nodes/addon/node-templates/route.js
lib/nodes/addon/node-templates/template.hbs
lib/shared/addon/components/node-pool-row/component.js
lib/shared/addon/components/node-pool-row/template.hbs
translations/en-us.yaml

======
We want to provide the owner as additional information when showing
node templates on the node templates page. We also want to make it so
that when selecting a node template the users templates will be grouped
and sorted to the top by default.
======
Linked Issues
======
rancher/rancher#23054
Node Templates Page:
Node Template Selection:

Provide better node template UX

---

app/models/nodetemplate.js
lib/nodes/addon/components/node-template-row/template.hbs
lib/nodes/addon/node-templates/controller.js
lib/nodes/addon/node-templates/route.js
lib/nodes/addon/node-templates/template.hbs
lib/shared/addon/components/node-pool-row/component.js
lib/shared/addon/components/node-pool-row/template.hbs
translations/en-us.yaml

======
We want to provide the owner as additional information when showing
node templates on the node templates page. We also want to make it so
that when selecting a node template the users templates will be grouped
and sorted to the top by default.
======
Linked Issues
======
rancher/rancher#23747
Node Templates Page:
Node Template Selection:

[forwardport] Provide better node template UX

---

app/components/new-edit-project/template.hbs

======
When creating and editing a Project we wanted to only reveal the
PodSecurityPolicy selector if the cluster had the pspEnabled field
set to true.
======
Linked Issues
======
rancher/rancher#23705

[forwardport] Use pspEnabled to gate project PodSecurityPolicy

---

lib/shared/addon/components/cru-cluster/template.hbs

======
When creating an AKS cluster an alert with an EKS message. This
simply switches the message to use the AKS message.
======
Linked Issues
======
rancher/rancher#23601

Use correct AKS messaging for create cluster

---

lib/shared/addon/components/form-contextual-select-array/component.js

======
When there was only one option we the add button was disabled and
we couldn't add the one option.
This change fixes it so that we can still select the single option if
desired.
======
Linked Issues
======
rancher/rancher#23780

Fix FormContextualSelectArray to accept 1 option

---

lib/shared/addon/components/form-contextual-select-array/component.js

======
When there was only one option we the add button was disabled and
we couldn't add the one option.
This change fixes it so that we can still select the single option if
desired.
======
Linked Issues
======
rancher/rancher#23793

[forwardport] Fix FormContextualSelectArray to accept 1 option

---

lib/global-admin/addon/settings/template.hbs

======
There appears to be an issue in the old versions of ember regarding angle bracket link-to's, since this isn't required and was  a nicety that was backported it makes sense to just revert to the old component style. 
======
Bugfix
Linked Issues
======
rancher/rancher#23771
======
N/A

fix issue with angle bracket link-to in old version of ember

---

app/components/new-catalog/component.js
app/components/new-catalog/template.hbs
lib/global-admin/addon/components/new-multi-cluster-app/component.js
lib/global-admin/addon/components/new-multi-cluster-app/template.hbs
lib/shared/addon/mixins/catalog-app.js

======
When editing both single and multi-cluster apps if you modified the
Template Version or the Target Projects and then cancelled it the
underlying store was still modified which then reflected those changes
on other pages like the single and multi-Cluster Apps pages.
To change this I cloned and nested the fields into a nested object named
'editable' and updated the primarySource on willSave for the relevant
targets subfield.
======
Linked Issues
======
rancher/rancher#21228

Prevent App editing from modifying state on cancel

---

app/components/accordion-pod/component.js

======
The node sortkey was displayname instead of node.displayName which
caused sorting to behave strangely.
I switched the correct sortkey of node.displayName.
======
Linked Issues
======
rancher/rancher#21218

Switch node sortkey on Workload page.

---

lib/global-admin/addon/security/cloud-credentials/index/controller.js
lib/global-admin/addon/security/cloud-credentials/index/template.hbs
lib/shared/addon/components/sortable-table/component.js
lib/shared/addon/mixins/sortable-base.js

======
Fixes issues where sorting wasn't working quite right on the cloud credentials page. 
While I was cleaning this up I found that groupByRef in cc this case did nothing so I removed it. This exposed a bug in the sortable-table code where groupByRef was coming back null but when we tried to get it, using embers getter, it would fail because we passed a null value instead of an empty string.
Additionally I found that when using presorts we were continuously pushing into the sort array on the component, which never gets reset, so I decided to clone the array. We rarely use preSorts so it was never caught.
Additionally we never add/remove the descending key to our presorts so I've added that. Without these when we pass the sort to embers sort we'd never correctly sort …

Fix sorting on cloud credentials page

---

lib/nodes/addon/components/driver-vmwarevsphere/component.js
lib/nodes/addon/components/driver-vmwarevsphere/template.hbs

======
When editing a vsphere node template that used a RancherOS ISO
creation method it crashed the page due to an array not existing.
I also noticed that the tags, custom attributes and networks weren't
loading when editing so I resolved those issues too.
======
Linked Issues
======
rancher/rancher#23796

Repair vsphere node template editing

---

lib/nodes/addon/components/driver-vmwarevsphere/component.js
lib/nodes/addon/components/driver-vmwarevsphere/template.hbs

======
When editing a vsphere node template that used a RancherOS ISO
creation method it crashed the page due to an array not existing.
I also noticed that the tags, custom attributes and networks weren't
loading when editing so I resolved those issues too.
======
Linked Issues
======
rancher/rancher#23809

[forwardport] Repair vsphere node template editing

---

lib/monitoring/addon/components/nodes-live/component.js
lib/shared/addon/utils/used-percent-gauge.js

======
Forwardport PR https://github.com/rancher/ui/pull/3522
The usage percent should be used / total * 100.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/23824
======

[Forwardport]Incorrect node memory usage gauge when cluster monitoring is enabled

---

lib/global-admin/addon/security/cloud-credentials/index/controller.js
lib/global-admin/addon/security/cloud-credentials/index/template.hbs
lib/shared/addon/components/sortable-table/component.js
lib/shared/addon/mixins/sortable-base.js

======
While I was cleaning this up I found that groupByRef in cc this case did nothing
so I removed it. This exposed a bug in the sortable-table code where groupByRef
was coming back null but when we tried to get it, using embers getter, it would
fail because we passed a null value instead of an empty string.
Additionally I found that when using presorts we were continuously pushing into
the sort array on the component, which never gets reset, so I decided to clone
the array. We rarely use preSorts so it was never caught.
Additionally we never add/remove the descending key to our presorts so I've
added that. Without these when we pass the sort to embers sort we'd never
correctly sort any presorts based the descending flag.
======
Bugfix
Linked Issues …

[Forwardport] Fix sorting on cloud credentials page

---

app/components/form-contextual-key-value/component.js
app/components/form-contextual-key-value/template.hbs
lib/nodes/addon/components/driver-vmwarevsphere/component.js
lib/nodes/addon/components/driver-vmwarevsphere/template.hbs

======
The keys for custom attributes needed to be unique. To enforce the
unique constraint I created the FormContextualKeyValue component.
This component behaves similarly to the FormContextualSelectArray
but handles key value pairs.
======
Linked Issues
======
rancher/rancher#23782
rancher/rancher#23845 this should could get fixed because this change removes the offending component all together.

Enable unique custom attribute key selection

---

app/components/form-contextual-key-value/component.js
app/components/form-contextual-key-value/template.hbs
lib/nodes/addon/components/driver-vmwarevsphere/component.js
lib/nodes/addon/components/driver-vmwarevsphere/template.hbs

======
The keys for custom attributes needed to be unique. To enforce the
unique constraint I created the FormContextualKeyValue component.
This component behaves similarly to the FormContextualSelectArray
but handles key value pairs.
======
Linked Issues
======
rancher/rancher#23841

[forwardport] Enable unique custom attribute key selection

---

app/components/form-key-to-path/component.js

======
`form-key-to-path` component incorrectly assumed that `configMap.data` key would always be present. Added a check before we try to loop over the key. I did not add a loop for binaryData as its not officially supported by the UI. 
======
Bugfix
Linked Issues
======
rancher/rancher#21349
======

JS Error when Consuming configMap with binaryData key

---

lib/nodes/addon/components/driver-vmwarevsphere/component.js
lib/nodes/addon/components/driver-vmwarevsphere/template.hbs
translations/en-us.yaml

======
The backend has made a new implementation of creationType which allowed
me to remove the creationMethod concept and just use creationType.
This change allows us to properly populate the creation type form fields
when a user edits a vsphere nodetemplate.
======
Linked Issues
======
rancher/rancher#23812
Backend Changes
======
rancher/machine#45
https://github.com/rancher/rancher/pull/23910

Switch to new implementation of creationType

---

app/authenticated/cluster/edit/route.js
lib/global-admin/addon/clusters/new/launch/route.js

======
Ember deprecated `transition.queryParams` private API in favor of using the public api's either on the router service, or from a transitions to/from properties. Without these params the version switching wasn't working correctly for RKE templates when editing a cluster. 
======
Bugfix
Linked Issues
======
rancher/rancher#23682
======
This does not affect the 2.3 branch because 2.3 is on ember 3.9 where master is on 3.12+

Handle Deprecated Transition Params 

---

lib/nodes/addon/components/driver-vmwarevsphere/component.js
lib/nodes/addon/components/driver-vmwarevsphere/template.hbs
translations/en-us.yaml

======
The backend has made a new implementation of creationType which allowed
me to remove the creationMethod concept and just use creationType.
This change allows us to properly populate the creation type form fields
when a user edits a vsphere nodetemplate.
======
Linked Issues
======
rancher/rancher#23875
Backend Changes
======
rancher/machine#45

[forwardport] Switch to new implementation of creationType

---

lib/shared/addon/components/form-labels-annotations/component.js
lib/shared/addon/utils/constants.js

======
Now some annotations which should be user-editable are read-only. 
The primary offender is that Annotations looks for "contains kubernetes.io" instead of "starts with kubernetes.io/ like the Labels section. So that blocks nginx-ingress.kubernetes.io/* and similar. 
We should use `startsWith` for `kubernetes.io`.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/23849
======

[2.3.3] Too many annotations are read-only

---

lib/shared/addon/components/form-labels-annotations/component.js
lib/shared/addon/utils/constants.js

======
Now some annotations which should be user-editable are read-only.
The primary offender is that Annotations looks for "contains kubernetes.io" instead of "starts with kubernetes.io/ like the Labels section. So that blocks nginx-ingress.kubernetes.io/* and similar.
We should use startsWith for kubernetes.io.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/23945
======

[forwardport] Too many annotations are read-only

---

app/styles/base/_helpers.scss
lib/nodes/addon/components/driver-vmwarevsphere/component.js
lib/nodes/addon/components/driver-vmwarevsphere/template.hbs
lib/shared/addon/components/select-value-check/component.js
lib/shared/addon/components/select-value-check/template.hbs
lib/shared/app/components/select-value-check/component.js
translations/en-us.yaml

======
When using an older vsphere node template in the latest version it was
possible that a user entered value would not be a valid option. When
the value isn't a valid option the dropdown has nothing selected. To
improve the UX we now notify the user that the current value is no
longer valid and sask them to select a new value.
======
Linked Issues
======
rancher/rancher#23920

Notify user of value missing from options

---

app/styles/base/_helpers.scss
lib/nodes/addon/components/driver-vmwarevsphere/component.js
lib/nodes/addon/components/driver-vmwarevsphere/template.hbs
lib/shared/addon/components/select-value-check/component.js
lib/shared/addon/components/select-value-check/template.hbs
lib/shared/app/components/select-value-check/component.js
translations/en-us.yaml

======
When using an older vsphere node template in the latest version it was
possible that a user entered value would not be a valid option. When
the value isn't a valid option the dropdown has nothing selected. To
improve the UX we now notify the user that the current value is no
longer valid and sask them to select a new value.
======
Linked Issues
======
rancher/rancher#23980

[forwardport] Notify user of value missing from options

---

lib/shared/addon/components/check-override-allowed/template.hbs
lib/shared/addon/components/form-network-config/template.hbs

======
Fix network plugin being editable on rke clusters. 
======
Bugfix
Linked Issues
======
rancher/rancher#23999
======

[Forwardport] RKE Cluster - network plugin not editable

---

app/styles/pages/_container.scss

======
When looking at a container's logs, there is a checkbox called "Wrap lines". Activating this overrides the width of the page showing the logs, causing vertical scrolling instead of actual line wrapping. This change fixes the issue.
======
Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/23993
======
I have tested and confirmed this fix works.

Fix wrap lines feature

---

lib/global-admin/addon/components/new-multi-cluster-app/component.js
lib/global-admin/addon/components/new-multi-cluster-app/template.hbs

======
This enables '.' to be a valid character in answer varaibles.
So we can support sub.key as a key now.
This also resolves a double render issue that was ran into while
reproducing this issue.
======
Linked Issues
======
rancher/rancher#24025
======

[backport] Enable '.' in answer variables

---

app/models/templateversion.js
lib/global-admin/addon/components/new-multi-cluster-app/component.js
lib/global-admin/addon/components/new-multi-cluster-app/template.hbs

======
There was a bug in multi cluster apps that did not validate the answers to the catalog apps questions correctly. Answers that were empty strings would be validated as okay because of the `!` check. Switched it over to use the `isEmpty` method. 
This revealed a bug where after an error and upon save we did not fetch the latest answers to validate against because we were not watching the correct keys on the computed property.
Additionally I saw a place where upon successful save of an upgrade, the selected template model would recompute and causing any old answer values to briefly flash on the screen before transitioning back to the correct route. I've added a check to this property that recomputes to prevent this. 
======
Bugfix
Linked Issues
====== …

Fix MC App Answer Validation

---

app/models/templateversion.js
lib/global-admin/addon/components/new-multi-cluster-app/component.js
lib/global-admin/addon/components/new-multi-cluster-app/template.hbs

======
There was a bug in multi cluster apps that did not validate the answers to the catalog apps questions correctly. Answers that were empty strings would be validated as okay because of the `!` check. Switched it over to use the `isEmpty` method. 
This revealed a bug where after an error and upon save we did not fetch the latest answers to validate against because we were not watching the correct keys on the computed property.
Additionally I saw a place where upon successful save of an upgrade, the selected template model would recompute and causing any old answer values to briefly flash on the screen before transitioning back to the correct route. I've added a check to this property that recomputes to prevent this. 
======
Bugfix
Linked Issues
====== …

[Forwardport] Fix MC App Answer Validation

---

app/models/cluster.js
lib/global-admin/addon/cluster-templates/detail/template.hbs
lib/shared/addon/components/modal-save-rke-template/component.js
lib/shared/addon/components/modal-save-rke-template/template.hbs
lib/shared/app/components/modal-save-rke-template/component.js
translations/en-us.yaml

======
This exposes the `saveAsTemplate` action on an RKE based cluster. This action is available in the actions drop down on a cluster resource. Selecting the action opens a new modal where the user is asked for the name of the cluster template, the cluster template revision is given a default name of `v1`. After successful action we wait for the `clusterTemplateRevisionId` to be populated on the cluster object where the user is then redirected to the detail view of this revision. On the detail page we've exposed the action menu for the revision where in the user can select the normal actions on a cluster template revision. 
======
New Feature
Linked Issues
======
rancher/rancher#23752
======
N/A

[Forwardport] Convert Existing Cluster to RKE Cluster Template

---

lib/nodes/addon/components/driver-vmwarevsphere/component.js
translations/en-us.yaml

======
The backend was setting the default to legacy so that the legacy
template would still work when users migrate to the latest
version of the driver. This was causing the default value to
be legacy when creating a new vsphere template. Forcing
the backend to change the default will likely lead to problems
with the migration so we're making the change on the front end.
Ultimately we use the existing set default logic if a vsphere template
is being created (as opposed to edited) instead of just when the
creation type doesn't exist or is invalid.
We also changed the text for the legacy value to be friendlier.
======
Linked Issues
======
rancher/rancher#24060

Change the messaging and default creationtype

---

lib/nodes/addon/components/driver-vmwarevsphere/component.js
translations/en-us.yaml

======
The backend was setting the default to legacy so that the legacy
template would still work when users migrate to the latest
version of the driver. This was causing the default value to
be legacy when creating a new vsphere template. Forcing
the backend to change the default will likely lead to problems
with the migration so we're making the change on the front end.
Ultimately we use the existing set default logic if a vsphere template
is being created (as opposed to edited) instead of just when the
creation type doesn't exist or is invalid.
We also changed the text for the legacy value to be friendlier.
======
Linked Issues
======
rancher/rancher#24086

[forwardport] Change the messaging and default creationtype

---

lib/global-admin/addon/components/new-multi-cluster-app/component.js
lib/shared/addon/components/schema/input-password/component.js
lib/shared/addon/mixins/catalog-app.js

======
`templateChanged` which loads the content of what we need for a MC app was
updated to watch a new property, `editable: { selectedTemplateUrl } `. The new
property was declared on the component as an object. Observers watching a static
object that have never been fetched do not recompute. If we set the property
on init to the object it would have been declared with then additional sets on
the watched property cause the observer to recompute.
Also fixes an issue where selecting the `generate password` button causes all input to change to text. 
======
Bugfix
Linked Issues
======
rancher/rancher#24057
rancher/rancher#24122
======
This may have been accomplished another way by always calling `templateChanged` from the init but it's …

Mc.app.display.issues

---

app/styles/components/_tables.scss

======
Sometimes when bulk actions are rendered the JavaScript that sets the width runs before the elements are visible. Rather than add a bunch of logic tracking the visibility to deal with the race condition that is occurring I've just set the overflow of the bulk actions to not break. This is only an issue on init, once the user scrolls or clicks any where on the screen the resize handlers fire and set the width correctly so we should not see any issues on mobile vs desktop widths.
======
Bugfix
Linked Issues
======
rancher/rancher#23784
======

Ensure bulk actions buttons are always on same line

---

app/authenticated/cluster/cis/scan/controller.js
app/authenticated/cluster/cis/scan/template.hbs
translations/en-us.yaml

======
On the CIS Scans page we now show a notification which informs the user
that CIS scans are only available on RKE clusters. The notification is all that is
shown on the page since the user cannot actually run a scan or view any
scans.
======
Linked Issues
======
rancher/rancher#24433

Provide notification for CIS Scan is RKE only

---

app/authenticated/cluster/cis/scan/controller.js
app/authenticated/cluster/cis/scan/detail/controller.js
app/authenticated/cluster/cis/scan/detail/route.js
app/authenticated/cluster/cis/scan/route.js
lib/shared/addon/security-scan-config/service.js
lib/shared/app/security-scan-config/service.js

======
We provide an error notification when the security config is malformed and
the user attempts to run a scan. We also prevent the scan from running.
We also added a default sort by 'id' on the scan detail table.
======
Linked Issues
======
rancher/rancher#24495
rancher/rancher#24496

Provide more feedback when a security config is malformed

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/utils/util.js

======
awsCloudProvider was being removed from custom clusters when editing
the YAML. This change ensures that the field is still present. It also
required modifying the removeEmpty method as it was removing fields that
were in the excludedKeys argument.
======
Linked Issues
======
rancher/rancher#24515

Ensure awsCloudProvider presense for custom cluster

---

app/authenticated/cluster/cis/scan/controller.js
app/authenticated/cluster/cis/scan/detail/controller.js

======
Because the scan will ignore an invalid config map I'm removing
the validation from run scan so the UI can run the scan without issue.
======
Linked Issues
======
rancher/rancher#24496

Remove config map validation from run scan

---

app/models/clusterscan.js
lib/shared/addon/mixins/cattle-transitioning-resource.js

======
I originally changed the color in transitioning which changed the
color elsewhere like the workload progress bars. We decided to
make the color of running an exceptional case in CIS scans since the
meaning of running differs here.
======
Linked Issues
======
rancher/rancher#24440
rancher/rancher#24639

Make special case for the 'running' state color

---

app/authenticated/cluster/cis/scan/detail/route.js
app/authenticated/cluster/cis/scan/route.js
lib/shared/addon/security-scan-config/service.js

======
The security-scan-config wasn't being reloaded when
navigating between clusters because the config map
was getting cached. This forces it to be reloaded.
======
Linked Issues
======
rancher/rancher#24623

Make the security-scan-config load for each route

---

lib/shared/addon/security-scan-config/service.js

======
I don't want to validate the configMap in the skipList
because a malformed configMap is the equivelant of
an empty skipList for the purposes of running a scan
and displaying what is currently being skipped.
======
Linked Issues
======
rancher/rancher#24627

Give the skipList a default value if malformed

---

app/components/registry-row/template.hbs
app/models/dockercredential.js

======
custom registry in registry credentials page will be translated currently.
Don't known why `t` doesn't fallback like `maybe-t` in this case. Tried to add `default`. It still doesn't work
======
Linked Issues
======
https://github.com/rancher/rancher/issues/24659

[UI] Fix the custom address surrounded by '*%' in registry credentials page

---

lib/pipeline/addon/components/settings-git/component.js
lib/shared/addon/components/input-integer/component.js
lib/shared/addon/utils/parse-unit.js

======
If the pipeline is setup with the configuration limits set to nothing an unhandled error would spawn from the parseSi method. I've added a check to this area so the method won't cause the page to explode.
The main crux of this issue though is that the input-integer component did not set the min value if the input was `NaN` which would prevent this from happening in the first place. 
As a back up measure for users who change the values via the API and then use the UI (unlikely) or hit this issue in <= 2.3 I've also added a check to the saveLimit method which only saves values that aren't NaN types. 
======
Bugfix
Linked Issues
======
rancher/rancher#21608
======
The reason this validation doesn't happen at the schema level is the …

Pipeline Setup Error

---

app/styles/components/_code.scss
lib/global-admin/addon/components/cru-cloud-credential/template.hbs
lib/nodes/addon/components/driver-vmwarevsphere/component.js
lib/nodes/addon/components/driver-vmwarevsphere/template.hbs
lib/shared/addon/components/input-yaml/component.js
lib/shared/addon/components/input-yaml/template.hbs
translations/en-us.yaml

======
There was confusion and misuse around cloudinit and cloudconfig.
This change switches things up so cloudinit is only used for the
legacy creation type and cloudconfig is used for all other creation
types.
This also changes the textarea that was used for cloudconfig to
input-yaml to make it clear to users that they can enter yaml.
======
Linked Issues
======
rancher/rancher#24314

Improve Vsphere UX around cloudinit/cloudconfig

---

app/authenticated/cluster/cis/scan/controller.js
app/authenticated/cluster/cis/scan/detail/controller.js
lib/shared/addon/security-scan-config/service.js

======
When the user doesn't have access to the systemProject we just
return an empty configMap so the page can proceed without error.
======
Linked Issues
======
rancher/rancher#24644

Provide empty configMap when it can't be retrieved

---

app/components/cru-dns/component.js

======
Fix the issue that cannot change svc type from clusterIP to nodePort
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21354
======

Fix svc issue

---

app/authenticated/cluster/cis/scan/controller.js
app/authenticated/cluster/cis/scan/detail/controller.js
lib/shared/addon/security-scan-config/service.js

======
We validating the security scan config appropriately when
a version was already present in the skip list. This now
ensures a version exists before verifying that it contains an array.
We were also replacing the existing skip object in the
security-scan-config which prevented us from storing
multiple versions at a time. We now extend the object
instead using the spread operator.
======
Linked Issues
======
rancher/rancher#24733
rancher/rancher#24742

Ensure skipping works for multiple cis versions

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js

======
We were erroneously adding cloud_provider.awsCloudProvider on
digital ocean etc due to rancher/rancher#24515.
This change assumes that the presence of
onfig.rancher_kubernetes_engine_config.cloud_provider.name
implies that the cloud_provider should be present. If that
nested field isn't present we remove cloud_provider.
======
Linked Issues
======

Remove cloud_provider if it's not intended

---

lib/shared/addon/components/form-members/template.hbs
lib/shared/addon/components/project-member-row/component.js
lib/shared/addon/components/project-member-row/template.hbs

======
Changed the remove button logic as noUpdate doesn't mean the user can't remove the member. The remove button should only be disabled for the dummy row that is displayed when creating a cluster or project. The dummy row is displayed so the creator knows they will be added as a member, the backend does this automatically on create so we dont have to do it our selves. 
======
Linked Issues
======
rancher/rancher#24428
======

Allow Cluster/Project Members To Be Removed On Edit

---

lib/shared/addon/components/cluster-driver/driver-rke/template.hbs

======
There is no need to show the `edit yaml` button when launching a custom cluster and you're past step 1 because. Non of the changes applied on the second step of launching a cluster apply to the cluster config and only change the command the user is running. 
======
bugfix
Linked Issues
======
rancher/rancher#24749
======

[2.3] remove display of 'edit yaml' button on step > 1 for custom cluster

---

lib/shared/addon/utils/stateful-promise.js

======
When the promise was rejected it took the error value and
set that as the value of the promise.
This lead to code expecting one shape to completely fail. This
now assigns the errorValue to an errorValue property on the
promise and the defaultValue to value when a promise is rejected.
======
Linked Issues
======
rancher/rancher#24620

Better handle rejected promises in StatefulPromise

---

lib/shared/addon/utils/stateful-promise.js

======
When the promise was rejected it took the error value and
set that as the value of the promise.
This lead to code expecting one shape to completely fail. This
now assigns the errorValue to an errorValue property on the
promise and the defaultValue to value when a promise is rejected.
======
Linked Issues
======
rancher/rancher#24620

[backport] Broken promise 2.3

---

app/authenticated/project/route.js
lib/istio/addon/project-istio/graph/route.js

======
This also fixes a bug where I accidentally removed a wrapping object around the namespaces return object in the route. This caused a bug where the namespaces for the Istio traffic monitoring route were empty which caused nothing to show up on the page. 
While debugging the traffic page issue I stumbled on a race condition with the current project id which I tracked down to the fact that we were finishing the project switch in the `setupController` method of the project route. With clusters we finish the switch in the after model. I moved the project level switch to after model as its consistent and ensures that additional routes, which could rely on the current project id, will defer loading until the project switch finishes.
======
BugFix
Linked …

Istio.bugs

---

lib/istio/addon/components/modal-delete-istio/component.js
translations/en-us.yaml

======
In order for Istio to be redeployed after being disabled we have to remove the istio-system namespace. This PR adds that functionality. I also update the labels to indicate this will happen. 
======
Bugfix
Linked Issues
======
rancher/rancher#24850
======

[2.3.4] delete the istio-system namespace when disabling istio

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
lib/shared/addon/components/form-network-config/template.hbs
translations/en-us.yaml

======
This PR addresses two issues regarding helper text and labels.
Change label and add help block for the CNI Plugin MTU config on RKE based clusters.
Fixes a bug where the k8s version upgrade helper text was not showing up on a cluster launched with a template which was subsequently upgraded to a new template with a new k8s version. 
======
Bugfix
Linked Issues
======
rancher/rancher#24829
rancher/rancher#24929
======

Help Text and Label Text Updates

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
lib/shared/addon/components/form-network-config/template.hbs
translations/en-us.yaml

======
This PR addresses two issues regarding helper text and labels.
Change label and add help block for the CNI Plugin MTU config on RKE based clusters.
Fixes a bug where the k8s version upgrade helper text was not showing up on a cluster launched with a template which was subsequently upgraded to a new template with a new k8s version. 
======
Bugfix
Linked Issues
======
rancher/rancher#24829
rancher/rancher#24929
======

[2.3] Help Text and Label Text Updates

---

app/components/cru-secret/template.hbs
lib/shared/addon/components/form-key-value/component.js

======
**Problem:** 
When adding secrets of RSA private keys, blank lines at the end of the file are trimmed, which breaks its format.
**Solution:** 
Added condition for trimming multiline inputs, and set to false when adding secrets
======
Linked Issues
======
https://github.com/rancher/rancher/issues/24577
======

Fixed trimming blank lines in multiline values of secrets breaks RSA format 

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js

======
Fixed when adding rke templates, edit as YAML in cluster options is not returning, which causes the button stays "saving".
======
Linked Issues
======
https://github.com/rancher/rancher/issues/24767
======

Fixed edit as yaml in cluster options stuck on "saving"

---

app/authenticated/cluster/cis/scan/detail/controller.js
app/authenticated/cluster/cis/scan/detail/template.hbs
app/models/clusterscan.js

======
- Adding the clear button to the detail page search input
- Add nodes to skipped test in the csv download
- We want to display the nodes the test would run on even if it was skipped.
- Add support for lettered suffixes when sorting
- When sorting CIS scan tests by number the lettered suffixes weren't sorting properly. This adds support for sorting numbers such as 1.1.37b.
======
Linked Issues
======
rancher/rancher#24750
rancher/rancher#24725
rancher/rancher#24715

A number of small fixes for CIS Scans

---

lib/shared/addon/components/form-members/template.hbs
lib/shared/addon/components/project-member-row/component.js
lib/shared/addon/components/project-member-row/template.hbs

======
Changed the remove button logic as noUpdate doesn't mean the user can't remove the member. The remove button should only be disabled for the dummy row that is displayed when creating a cluster or project. The dummy row is displayed so the creator knows they will be added as a member, the backend does this automatically on create so we dont have to do it our selves.
======
Bugfix
Linked Issues
======
rancher/rancher#24934
======
N/A

[2.3.5] Missing Remove Button Cluster Members

---

lib/shared/addon/components/cluster-driver/driver-azureaks/component.js

======
Azure config has a default K8s version that is back in the 1.11 era. We should grab the latest satisfying version from the returned versions call. 
======
Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/25100
======
N/A

[2.3] Azure aks get the latest satisfying version from versions

---

lib/shared/addon/components/cluster-driver/driver-azureaks/component.js

======
Azure config has a default K8s version that is back in the 1.11 era. We should grab the latest satisfying version from the returned versions call. 
======
Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/25100
======
N/A

Azure aks get the latest satisfying version from versions

---

app/components/input-files/component.js
lib/logging/addon/components/logging/input-logging-config/component.js
lib/shared/addon/components/input-text-file/component.js
lib/shared/addon/components/input-yaml/component.js
lib/shared/addon/mixins/input-answers.js
lib/shared/addon/mixins/upload.js

======
Fixes broken jquery element targeting in upload-*ish* components. We were not targeting the elements inside the component. In the case of auth setup where we display 3 file inputs on SAML providers this would cause the click to open a file to only target the first component. 
======
Bugfix
Linked Issues
======
rancher/rancher#24960
======

Fix broken jquery dom targeting

---

lib/global-admin/addon/components/new-edit-role/component.js
lib/global-admin/addon/components/new-edit-role/template.hbs
lib/global-admin/addon/components/role-rule-row/component.js
lib/global-admin/addon/components/role-rule-row/template.hbs
lib/global-admin/addon/security/roles/index/template.hbs
lib/shared/addon/components/searchable-select/component.js
translations/en-us.yaml

======
Some roles (e.g. global admin) use the `nonResourceURLs` param on a policy rule model. The UI never exposed entering a `nonResourceURLs` param but did make a special case on detail view. When roles were update to be cloned this was not taken into consideration and when cloning a role that had `nonResourceURLs` in the rules we could get into a state where you could not clone that rule. 
This PR exposes the `nonResourceURLs` param. The new param is mutually exclusive with `resources` so if you are using one you may not use the other. This is all the error checking that occurs with the new param. Technically the param on the Kubernetes side can only take a path or `*` (all) indicator. We could validate this but that doesn't stop someone creating/editing from the API. …

Global Roles Bugs

---

app/fail-whale/route.js
app/initializers/uncaught-exceptions.js

======
Anytime we have an unhandled exception we will now navigate to the
fail whale page.
======
Linked Issues
======
rancher/rancher#25198

Make unhandled exceptions display the fail whale

---

app/models/cluster.js
translations/en-us.yaml

======
Run CIS Scan was broken on the cluster list page because
currentCluster was being used instead of just using the current cluster.
I also removed the redirect and just use a growl notification to
indicate the scan is running.
======
Linked Issues
======
rancher/rancher#25241
rancher/rancher#25159

Fixing Run CIS Scan on the cluster list page

---

lib/shared/addon/components/form-network-config/template.hbs

======
Flannel Network provider does not support overriding network MTU. 
======
Bugfix
Linked Issues
======
rancher/rancher#25267
======

[2.3] Hide mtu input for custom cluster on flannel network provider

---

lib/shared/addon/components/form-network-config/template.hbs

======
Flannel Network provider does not support overriding network MTU. 
======
Bugfix
Linked Issues
======
rancher/rancher#25267
======

Hide mtu input for custom cluster on flannel network provider

---

app/authenticated/cluster/cis/scan/controller.js
app/authenticated/cluster/cis/scan/detail/controller.js
app/authenticated/cluster/cis/scan/detail/template.hbs
app/authenticated/cluster/cis/scan/template.hbs
app/authenticated/cluster/route.js
app/authenticated/route.js
app/models/cluster.js
app/models/clusterscan.js
lib/shared/addon/security-scan-config/service.js

======
This refactoring removed code duplication and
provides a more cohesive experience across all
of the pages that you can run a scan.
This will also now check and ensure the following
- there aren't running ClusterScans
- this isn't a windows cluster
- systemProject is available
- the cluster is active
- the action link is available
When the above isn't the case Run CIS Scan will not be present in
the cluster action drop downs and the Run CIS Scan but
will be disabled on the CIS Scans and CIS Scan Detail
pages.
======
Linked Issues
======
rancher/rancher#24759
rancher/rancher#25298

Refactor how cis scans are disabled.

---

lib/global-admin/addon/components/saml-config/component.js
lib/global-admin/addon/mixins/saml-auth.js

======
Adds some additional logic around sending the openLdapConfig when enabling shibboleth. The previous implementation was not robust enough to handle preexisting configs, nor smart enough to drop the config if it was the default config. The error checking for openLdapConfig will only happen if the user has made some change to the open ldap search area so we don't spam users with missing required fields if they only _opened_ that area and didn't make changes. 
======
Bugfix
Linked Issues
======
rancher/rancher#25459
======

Additional checks around default/existing openLdapConfig Shibboleth

---

app/components/page-header/component.js
app/components/page-header/template.hbs

======
Fix the dashboard link on production builds so that it goes to dashboard instead of trying to load /dashboard within Ember/without really loading the page.
======
Linked Issues
======
rancher/rancher#25168

Fix dashbaord link for prod build

---

app/components/modal-restore-backup/component.js
app/components/modal-restore-backup/template.hbs
translations/en-us.yaml

======
- Update the Available Snapshots labels
- Reverse the order of Available Snapshots
- Change 'Save' button to 'Restore' button
- Add restoration type section 'etcd', 'kubernetes version', 'etcd and
kuberneters version'
======
Linked Issues
======
rancher/rancher#25525
*New Labels and Order*
*Selected snapshot without a recorded kubernetes version*
*Selected snapshot with a recorded kubernetes version**New Labels and Order*
*No selected snapshot*

Improve the Restore Snapshot modal

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/utils/util.js

======
The original intent of ecluding extra_args was actually
to exclude the children of extra_args from being
removed when empty according to https://github.com/rancher/rancher/issues/24794#issuecomment-570043854.
This will now properly handle that intent while also
removing empty extra_args properties.
======
Linked Issues
======
rancher/rancher#25612

Change the way extra_args are excluded

---

lib/global-admin/addon/security/roles/index/controller.js
lib/global-admin/addon/security/roles/index/template.hbs
translations/en-us.yaml

======
Since we allow users to create roles with duplicate
names we're adding the id as a column to allow them
to differentiate between the two.
======
Linked Issues
======
rancher/rancher#24409

Adding id as a column to the roles page

---

app/authenticated/cluster/cis/scan/detail/controller.js
app/models/cluster.js
lib/shared/addon/cis-helpers/service.js
lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
lib/shared/addon/components/run-scan-modal/component.js
lib/shared/addon/components/run-scan-modal/template.hbs
lib/shared/addon/utils/util.js
lib/shared/app/cis-helpers/service.js

======
The profile helper methods were attached to the cluster model.
Unfortunately, the cluster isn't available when creating a new rke
template.
To resolve this I moved all of the cis helpers out of the cluster model
and utils and moved them into a cisHelpers service so they could be
used without access to the cluster itself.
======

Resolve RKE Template issue caused by CIS

---

app/models/clusteralertrule.js
translations/en-us.yaml

======
We were displaying the Condition as Not Configured for
security scan alerts on the alerts page. We needed to define
the displayCondition for cis scans so it would display
appropriately.
It will display as either Failure or Happens depending on the value of
failuresOnly.
======
Linked Issues
======
rancher/rancher#25853

Adding cisScan to displayCondition

---

lib/alert/addon/components/alert/form-alert-rules/component.js
lib/alert/addon/edit/route.js
lib/alert/addon/mixins/edit-or-clone.js
lib/alert/addon/new-rule/route.js

======
The security scan option was only working when creating an alert in
a new group. This was occuring because the default value was not
being created in all the sections expected.
======
Linked Issues
======
rancher/rancher#25904

Ensure clusterScanRule gets default for all alert sections

---

app/authenticated/cluster/cis/scan/controller.js
app/authenticated/cluster/cis/scan/detail/controller.js
app/components/cluster/cis/scan/detail/table-row/template.hbs
app/components/cluster/cis/scan/table-row/template.hbs

======
We're removing the CIS skip button because we decided the current UX
is poort and we don't want to spend a tremendous amount of effort
making a marginally better UX in the short time we have left.
We also removed the 19 of 59 from the main CIS page as the total was
misleading and wasn't actionable.
======
Linked Issues
======
rancher/rancher#25863

Remove CIS skip button and total number

---

lib/shared/addon/cis-helpers/service.js
lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/run-scan-modal/component.js

======
This will now allow KDM to drive what the benchmark options are and what
the default option is for profile selection given a kubernetes version.
The 'cisConfig' type is what we look up for this information.
======
Linked Issues
======
rancher/rancher#25888

Use KDM to drive benchmark options and profile default

---

app/authenticated/cluster/cis/scan/detail/controller.js
app/styles/base/_color.scss
lib/shared/addon/cis-helpers/service.js
lib/shared/addon/components/run-scan-modal/component.js
lib/shared/addon/components/run-scan-modal/template.hbs
translations/en-us.yaml

======
We are going to add a section beneath the profile selector of the run
scan modal. This section is responsible for informing the user of which
tests will not be run and why.
There will be two subsections Not Applicable and Skipped tests.
Skipped tests will only be shown for permissive profiles since
hardened tests shouldn't skip anything.
======
Linked Issues
======
rancher/rancher#25961

Improving the UX of the run scan modal

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js

======
The default rancherKubernetesEngineConfig is only created for new
clusters. This now creates a default upgradeStraegy object when one
doesn't exist in rancherKubernetesEngineConfig.
======
Linked Issues
======
rancher/rancher#25951

Ensure upgrade strategy defaults are used on an upgraded rancher

---

app/authenticated/cluster/cis/scan/template.hbs
app/models/cluster.js

======
Make CIS schedule and alert buttons disabled more in line with run scan button
======
Linked Issues
======
rancher/rancher#25997

Make CIS schedule and alert buttons disabled more in line with run scan button

---

app/authenticated/cluster/cis/scan/route.js
app/authenticated/cluster/cis/scan/template.hbs
app/models/cluster.js

======
This now checks to see if there's and RKE template.
If there is an RKE template and the scheduleScanned is disabled
the button will be disabled unless there's an override available for
the scheduledClusterScan.enabled field.
======
Linked Issues
======
rancher/rancher#26150

Adding yet another condition to the CIS Add Schedule button

---

app/authenticated/cluster/cis/scan/detail/route.js
app/authenticated/cluster/cis/scan/route.js
lib/shared/addon/security-scan-config/service.js

======
The RunScanModal was not getting config map changes after the first
time the modal was opened. The results were getting cached. By creating
a new array each time loadAsyncConfigMap is loaded I can guarentee the
computed properties will get re-evaluated.
I also attempted to watch config maps through the project store but
unfortunately updating the data of the config map doesn't seem to
produce a websocket message. Even if the message was created I
don't think I'd be able to watch the value as I'd have to
watch a sub-object 'config.json' which has a period in it. This causes
problems with watching in ember.
======
Linked Issues
======
rancher/rancher#26161

Changing the way configMaps get loaded for RunScanModal

---

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js

======
After the Amazon cluster was saved but as we were transitioning away from the launch screen the vpcs observer fires because of a dependency change which would fire off the call to load the vpcs. This is not ideal because the cluster credentials have been cleared at this point and the call would fail causing an error message to show. 
======
Bugfix
Linked Issues
======
rancher/rancher#26208
======

EKS Driver Observer Issue

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
translations/en-us.yaml

======
Making the CIS scan enabled radio buttons function on edit
When editing a cluster the value of scheduledClusterScan.enabled comes
back as a string rather than a boolean. I just ensure the value will be a
boolean to make sure the value is displayed on the radio buttons as
expected.
======
Linked Issues
======
rancher/rancher#26245

Making the CIS scan enabled radio buttons function on edit

---

lib/shared/addon/components/cluster-driver/driver-rke/template.hbs

======
Correcting disable field for scheduledClusterScan in RKE
I converted the enabled value back to a boolean instead of it being a string
but I forgot to switch the three disabled fields to expect a boolean.
======
Linked Issues
======
rancher/rancher#26245

Correcting disable field for scheduledClusterScan in RKE

---

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js
lib/shared/addon/components/cluster-driver/driver-amazoneks/template.hbs
lib/shared/addon/components/cluster-driver/driver-azureaks/component.js
lib/shared/addon/components/cluster-driver/driver-azureaks/template.hbs
lib/shared/addon/components/cluster-driver/driver-googlegke/component.js
lib/shared/addon/components/cluster-driver/driver-googlegke/template.hbs
lib/shared/addon/version-choices/service.js
lib/shared/app/version-choices/service.js

======
Adds a new service which parses version from the various cloud provider version
list. I moved this to a new service rather than use form-versions because
form-versions is already fairly complicated with how it has to deal with RKE
Templates and unknown patch versions. It was simpler, cleaner, and faster to
move the CP cluster version parsing to a service and use new select because the
versions coming down do not include unknown patch versions. Addtionally going
this route allows us to not have to test all clusters for regressions, only CP ones.
======
New Feature
Linked Issues
======
rancher/rancher#26255
======

Remove min k8s version check for hosted cloud provider clusters

---

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js
lib/shared/addon/components/cluster-driver/driver-amazoneks/template.hbs
lib/shared/addon/components/cluster-driver/driver-azureaks/component.js
lib/shared/addon/components/cluster-driver/driver-azureaks/template.hbs
lib/shared/addon/components/cluster-driver/driver-googlegke/component.js
lib/shared/addon/components/cluster-driver/driver-googlegke/template.hbs
lib/shared/addon/version-choices/service.js
lib/shared/app/version-choices/service.js

======
Adds a new service which parses version from the various cloud provider version
list. I moved this to a new service rather than use form-versions because
form-versions is already fairly complicated with how it has to deal with RKE
Templates and unknown patch versions. It was simpler, cleaner, and faster to
move the CP cluster version parsing to a service and use new select because the
versions coming down do not include unknown patch versions. Addtionally going
this route allows us to not have to test all clusters for regressions, only CP ones.
======
New Feature
Linked Issues
======
rancher/rancher#26255
======

2.3 Remove min k8s version check for hosted cloud provider clusters

---

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js

======
When we changed the EKS fields to no edit this exposed an issue where sending a null subnet param caused a non-nullable api error on edit because when an input was present we'd always set the subnets to an empty array. This fix ensures that if the subnets are empty we send an empty array until the backend is fixed post 2.4 release.
======
Bugfix
Linked Issues
======
rancher/rancher#26231
rancher/rancher#24652
======

EKS Empty Subnets

---

app/components/notifier/modal-new-edit/component.js

======
After users set a proxy url for a notifier, they can not really remove it in alert manager config.
We need to remove the logic in this PR.
It was added for fixing  https://github.com/rancher/rancher/issues/22144 but it introduced  https://github.com/rancher/rancher/issues/26089
We need to fix it in backend.
======
- Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/26089
======
Related PR:
https://github.com/rancher/rancher/pull/26129

[Master] Fix the issue that users cannot remove proxyUrl of notifier

---

lib/shared/addon/oauth/service.js

======
As discussed in [here](https://github.com/rancher/rancher/issues/23633#issuecomment-590861242), currently the web ui is asking for unnecessary permissions (admin.directory.user.readonly & admin.directory.group.readonly) when redirecting to google page. This causes the consent screen to show "unverified app" and there is a cap on how many users (100)) can be authenticated.
Removing these permissions here should be fine since the rancher server already uses a Service Account with those permissions to get info about user groups.
I've tested it in my organization and the oauth & permissions still works despite having those permissions removed in ui side.
======
Linked Issues
====== …

Remove unnesscary permission request for g suite

---

app/components/notifier/modal-new-edit/component.js

======
After users set a proxy url for a notifier, they can not really remove it in alert manager config.
We need to remove the logic in this PR.
It was added for fixing rancher/rancher#22144 but it introduced rancher/rancher#26089
We need to fix it in backend.
======
- Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/26089
======
Related PR:
https://github.com/rancher/rancher/pull/26393

[2.4] Fix the issue that users cannot remove proxyUrl of notifier

---

lib/shared/addon/components/cluster-driver/driver-amazoneks/template.hbs

======
I mistakenly backported the encrypt ebs input when backporting another fix. 
======
Bugfix
Linked Issues
======
rancher/rancher#26518
======

[2.3.7] remove ebs encryption that didn't need to be backported

---

lib/alert/addon/components/alert-select/component.js

======
When deprecating the old usage of jquery I erroneously
converted this section. The element wasn't being referenced
properly anymore. This fixes an exception which was preventing
the page from rendering monitoring metric options.
======
Linked Issues
======
rancher/rancher#26829

Fixing a jquery usage error

---

app/components/cru-registry/component.js
package.json

======
Not sure this every put registry secrets into the desired namespace. The
`namespaceId` was never set on the primaryResource by the namespace components,
rather those components worked on a namespace object. Ive gotten rid of
`namespaceId` and refactored to use the namespace object in its place.
======
Linked Issues
======
rancher/rancher#26813
======

[2.4] refactor cru-registry ns save logic

---

app/components/volume-source/source-custom-log-path/template.hbs

======
Users cannot click the button for using custom logging format when use log volume
======
Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/26731
======

[2.4.x] Fix log volume format button issue

---

lib/shared/addon/components/form-network-config/template.hbs

======
The default value of MTU is 0, however if user touched the input. Users cannot change it back to 0
======
Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/27016
======

[Master] fix(MTU form): can not set to 0 after blur

---

lib/shared/addon/components/form-network-config/template.hbs

======
The default value of MTU is 0, however if user touched the input. Users cannot change it back to 0
======
Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/27016
======

[2.4.4] fix(MTU form): can not set to 0 after blur

---

Dockerfile.dapper
lib/shared/addon/utils/amazon.js

Backport of https://github.com/rancher/ui/pull/3962

(backport) Add Cape Town (af-south-1) as a supported AWS region.

---

lib/shared/addon/utils/amazon.js

======
Add AWS South Africa (Cape Town) as a supported AWS region.
======
New Feature
Linked Issues
======
https://github.com/rancher/rancher/issues/27042
======
Based this pull request off the one to add Azure South Africa. af-south-1 is not a supported region for EKS, so I have not included that.

Add Cape Town (af-south-1) as a supported AWS region.

---

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js
lib/shared/addon/components/cluster-driver/driver-amazoneks/template.hbs
translations/en-us.yaml

======
Adds a check to ensure that [on edit users can only upgrade by 1 minor version](https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html#aws-management-console). A help block is also rendered to indicate this as well. 
======
New Feature
Linked Issues
======
rancher/rancher#26908
======

[2.4.4] Prevent EKS K8s version upgrades > 1 minor version

---

lib/logging/addon/components/logging/new-edit/component.js
lib/logging/addon/components/logging/new-edit/template.hbs

======
Hide Windows logging warning in k8s 1.18
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20968
======

[2.4.4] Hide Windows logging warning in k8s 1.18

---

lib/logging/addon/components/logging/new-edit/component.js
lib/logging/addon/components/logging/new-edit/template.hbs

======
Hide Windows logging warning in k8s 1.18
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20968
======

[Master] Hide Windows logging warning in k8s 1.18

---

app/components/cru-registry/component.js

======
Object destructuring expects the entire object to be present. When
'Available to all namespaces in this project' is used the namespace
object isn't defined which causes the save to fail due to an null
exception.
======
Linked Issues
======
rancher/rancher#26981
rancher/rancher#27117

Fix registry credentials so that it doesn't crash

---

app/components/cru-registry/component.js

======
Object destructuring expects the entire object to be present. When
'Available to all namespaces in this project' is used the namespace
object isn't defined which causes the save to fail due to an null
exception.
======
Linked Issues
======
rancher/rancher#26981

[backport] Fix registry credentials so that it doesn't crash

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js

======
It appears that sometimes the cisscanconfig schema isn't present (I haven't
been able to consistently reproduce) which causes the UI to prevent the user
from saving changes to their cluster. Though I think this could be fixed
by the backend I'd like to stop the bleeding and have the UI handle this
better and still allow saving.
So there's two things that are here to help out.
1. I added a default value to the initial empty object just in case it never gets set
elsewhere.
2. If an exception is thrown while creating the scanConfig
we now just prevent the schedule from being set since it wouldn't work
anyway.
Either of these should allow saving to proceed.
======
Linked Issues
====== …

[backport] Improving how we handle a failure to get a scanConfig

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js

======
It appears that sometimes the cisscanconfig schema isn't present (I haven't
been able to consistently reproduce) which causes the UI to prevent the user
from saving changes to their cluster. Though I think this could be fixed
by the backend I'd like to stop the bleeding and have the UI handle this
better and still allow saving.
So there's two things that are here to help out.
1. I added a default value to the initial empty object just in case it never gets set
elsewhere.
2. If an exception is thrown while creating the scanConfig
we now just prevent the schedule from being set since it wouldn't work
anyway.
Either of these should allow saving to proceed.
======
Linked Issues
====== …

Improving how we handle a failure to get a scanConfig

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js

======
Enabled was being set to 'false' instead of false but this was being
masked by the execution of initScheduledClusterScan. When the
KDM values werent present initScheduledClusterScan was doing
an early exit and no longer masking the poor 'false' default value.
This will further improve the earlier solution for rancher/rancher#26996.
======
Linked Issues
======
rancher/rancher#26996.

Make the default scheduledClusterScan.enabled to be a boolean

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js

======
Enabled was being set to 'false' instead of false but this was being
masked by the execution of initScheduledClusterScan. When the
KDM values werent present initScheduledClusterScan was doing
an early exit and no longer masking the poor 'false' default value.
This will further improve the earlier solution for rancher/rancher#26996.
======
Linked Issues
======
rancher/rancher#26996.

[backport] Make the default scheduledClusterScan.enabled to be a boolean

---

app/models/nodetemplate.js

======
Cloning annotations was causing problems with how binding tracking
was working. Specifically it caused problems when
annotations.ownerBindingsCreated was present.
This removes the annotations entirely as recommended by @rmweir .
======
Linked Issues
======
rancher/rancher#26946

Removing annotations from nodetemplate clones

---

app/models/nodetemplate.js

======
Cloning annotations was causing problems with how binding tracking
was working. Specifically it caused problems when
annotations.ownerBindingsCreated was present.
This removes the annotations entirely as recommended by @rmweir .
======
Linked Issues
======
rancher/rancher#26946

[backport] Removing annotations from nodetemplate clones

---

lib/shared/addon/oauth/service.js

======
Looks like the undefined scope was getting added to the query
params for the redirect url. This change prevents the scope
param from being present for anything but google.
======
Linked Issues
======
rancher/rancher#27175

[backport] Only adding the scope param in oath logins for google

---

lib/shared/addon/oauth/service.js

======
Looks like the undefined scope was getting added to the query
params for the redirect url. This change prevents the scope
param from being present for anything but google.
======
Linked Issues
======
rancher/rancher#27175

Only adding the scope param in oath logins for google

---

app/components/modal-drain-node/component.js
lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/drain-node/component.js
lib/shared/addon/components/drain-node/template.hbs
translations/en-us.yaml

We no longer have safe and aggressive nodes we now
have two properties 'force' and 'deleteLocalData'.
======
Linked Issues
======
rancher/rancher#27111

Splitting up aggressive drain parameters   

---

app/components/modal-drain-node/component.js
lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/drain-node/component.js
lib/shared/addon/components/drain-node/template.hbs
translations/en-us.yaml

======  
We no longer have safe and aggressive nodes we now
have two properties 'force' and 'deleteLocalData'.
======
Linked Issues
======
rancher/rancher#27111

[backport] Splitting up aggressive drain parameters

---

app/components/cru-registry/component.js

======
Namespace wasn't being set on the component which prevented it from
being visible to OptionallyNamespaced mixin.
======
Linked Issues
======
rancher/rancher#27173

Fixing namespace specific registry clones

---

app/components/cru-registry/component.js

======
Namespace wasn't being set on the component which prevented it from
being visible to OptionallyNamespaced mixin.
======
Linked Issues
======
rancher/rancher#27173

[backport] Fixing namespace specific registry clones

---

lib/shared/addon/components/catalog-index/component.js

======
Fix JS failure when searching through catalog apps if an app is missing the optional description metadata field
======
Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/27188

Fix JS failure when searching through apps without description

---

app/components/modal-drain-node/component.js

======
The modal was persisting the selection state between multiple
closing and openings of the modal. This now resets the selection
state.
======
Linked Issues
======
rancher/rancher#27339

Reset registry modal step on each open

---

app/components/modal-drain-node/component.js

======
The modal was persisting the selection state between multiple
closing and openings of the modal. This now resets the selection
state.
======
Linked Issues
======
rancher/rancher#27339

[backport] Reset registry modal step on each open

---

lib/shared/addon/components/form-key-value/component.js
lib/shared/addon/components/form-key-value/template.hbs
lib/shared/addon/utils/util.js
translations/en-us.yaml

======
When a editing secret with binary non-UTF-8 data (e.g. pkcs12 encoded cert) the UI will break that data upon save. As we do in dashboard we won't allow users to edit secret data rows that contain non-UTF-8 data. Users can still add and remove rows, included the non-UTF-8 data row.
======
Bugfix
Linked Issues
======
rancher/rancher#27439
======

[2.4] Limit Editable Secret Data

---

lib/global-admin/addon/components/form-global-roles/component.js

======
When we assign a new role binding to a group we are actually creating a new global role binding. When an admin (or user with perms) creates additional users after global role bindings have been assigned a group, the creator will see these new global role bindings show up in the role list as checked. This is because the user create page keeps track of all roles that are active on init so that we may add/remove roles on edit, the save logic here see's these unchecked roles as roles that existed and are now removed. Subsequently sending off delete calls and removes the global role binding for that group. The creator is none the wiser since the role is not added to the new user.
Adding a filter (groupPrincipalId=null) to this initialization fixes the issue.
Types of …

Filter Global Role Bindings Creating User

---

lib/global-admin/addon/components/form-global-roles/component.js

======
When we assign a new role binding to a group we are actually creating a new global role binding. When an admin (or user with perms) creates additional users after global role bindings have been assigned a group, the creator will see these new global role bindings show up in the role list as checked. This is because the user create page keeps track of all roles that are active on init so that we may add/remove roles on edit, the save logic here see's these unchecked roles as roles that existed and are now removed. Subsequently sending off delete calls and removes the global role binding for that group. The creator is none the wiser since the role is not added to the new user.
Adding a filter (groupPrincipalId=null) to this initialization fixes the issue.
Types of …

[2.4] Filter Global Role Bindings Creating User

---

app/components/cru-registry/component.js

======
Fix regression in creating registry creds. I misunderstood what willSave was doing with the namespaceId when I added the ternary check in a previous fix. I simplified and hopefully clarified what was actually happening when setting temp_id, now use a local flag to set unset the temp namespace, then allow namespace to handle saving or not saving the namespace.
======
Bugfix
Linked Issues
======
rancher/rancher#27769
======

allow project owners to save reg creds

---

app/components/cru-registry/component.js

======
Fix regression in creating registry creds. I misunderstood what willSave was
doing with the namespaceId when I added the ternary check. I simplified and
hopefully clarified what was actually happening when setting temp_id, now use
a local flag to set unset the temp namespace, then allow namespace to handle
saving or not saving the namespace.
======
bugfix
Linked Issues
======
rancher/rancher#27769
======

[2.4.6] allow project owners to save reg creds

---

lib/nodes/addon/components/driver-vmwarevsphere/component.js

======
I noticed fields wouldn't update if the credentials changed
if the datacenter value stayed the same. This ensures that
all of the other values will recompute by forcing the datacenter
value to change.
======
Linked Issues
======
rancher/rancher#26997

Ensure the datacenter changes value if the credentials change

---

lib/nodes/addon/components/driver-vmwarevsphere/component.js

======
I noticed fields wouldn't update if the credentials changed
if the datacenter value stayed the same. This ensures that
all of the other values will recompute by forcing the datacenter
value to change.
======
Linked Issues
======
rancher/rancher#26997

[backport] Ensure the datacenter changes value if the credentials change

---

lib/login/addon/components/login-saml/component.js
lib/login/addon/login/controller.js
lib/login/addon/login/template.hbs
lib/shared/addon/saml/service.js

======
The backend changes for socketId weren't working with HA clusters so
it was decided to replace socketId with publicKey.
======
Linked Issues
======
rancher/rancher#444

Replacing SAML socketId with publicKey

---

lib/login/addon/components/login-saml/component.js
lib/login/addon/login/controller.js
lib/login/addon/login/template.hbs
lib/shared/addon/saml/service.js

======
The backend changes for socketId weren't working with HA clusters so
it was decided to replace socketId with publicKey.
======
Linked Issues
======
rancher/rancher#444
Verified the publicKey field is getting passed

[backport] Replacing SAML socketId with publicKey

---

lib/shared/addon/cis-helpers/service.js
lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/cluster-driver/driver-rke/template.hbs

======
When upgrading rancher the old 1.4 cis profiles were removed which prevented
the currently selected profile for scheduled scans to be selected.
This adds a selected profile to the options if it's not present allowing the
profile to be selected by default. If a different profile is selected and saved
the option will no longer be present. This option will also not be present in
the manual run scan modal.
======
Linked Issues
======
rancher/rancher#27867
rancher/rancher#27866
rancher/rancher#27374

Adding a selected cis profile to the profile options if it's not present

---

lib/login/addon/components/login-saml/component.js
lib/login/addon/login/controller.js
lib/login/addon/login/template.hbs
lib/shared/addon/saml/service.js

======
I mistakenly didn't add these two fields when replacing socketId with
publicKey.
======
Linked Issues
======
rancherlabs/rancher-security#444

[backport] Adding requestId and responseType to saml logins

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js

======
Turns out that the min value that the backend accepts won't allow
upgrades to complete. This switches the value to the default value to
mitigate that issue.
======
Linked Issues
======
rancher/rancher#27333

[backport] Switching from min value to default value for upgradeStrategy timeout

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js

======
Turns out that the min value that the backend accepts won't allow
upgrades to complete. This switches the value to the default value to
mitigate that issue.
======
Linked Issues
======
rancher/rancher#27333

Switching from min value to default value for upgradeStrategy timeout

---

lib/shared/addon/mixins/cluster-driver.js
lib/shared/addon/mixins/new-or-edit.js

======
Unfortunately the backend is sometimes saving invalid models which causes the validation of appliedSpec to fail. To avoid this validation we're now ignoring the appliedSpec where this can go wrong.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/27333#issuecomment-665244361
Notes
======
The validation is happening in multiple places. To add the plumbing for ignoring the appliedSpec to each place seemed excessive for a temporary fix. If you don't want me to remove the appliedSpec do you have any thoughts on making the change small? If not, I think I'll add the plumbing either to the model that's being validated or as props being passed to the components/mixins.

Removing appliedSpec before saving driver-rke

---

app/components/container/form-scale/template.hbs
lib/shared/addon/components/input-integer/component.js

======
Pod scale minimum was incorrectly set to 1. This sets the default back
to 0. Adds a nullible flag to input-int as this is allowed in most cases
where we are using the component. Defaults to false.
Formatting fixes
======
Bugfix
Linked Issues
======
rancher/rancher#28168
======

[2.4.6] Allow pod scale to be set 0 or null

---

lib/shared/addon/settings/service.js

======
Any exceptions during JSON parsing of `ui-banners` setting are now handled; `showHeaders`/`showFooters` fields are checked for being a string; logic was slightly consolidated.
======
Bugfix to prevent being locked out of the UI when an invalid `ui-banners` setting is present.
Linked Issues
======
- rancher/rancher#28504
======
An explored alternative was enforcing server-side validation of this setting. However, it appears settings in general do not have validation tied to them, requiring this fail-safe UI approach instead.

Ensure no exceptions are thrown when handling UI banners

---

lib/shared/addon/utils/azure-choices.js

Adding German Public locations to the Azure choices
New feature
https://github.com/rancher/rancher/issues/28082
Check the infrastructure pages for double-checking the locations, marked with (Public) are in the `AzurePublicCloud` while the (Sovereign) is in the `AzureGermanCloud`.
- https://azure.microsoft.com/en-us/global-infrastructure/data-residency
- https://azure.microsoft.com/en-us/global-infrastructure/geographies

Add Azure German Public locations to the provider choices

---

lib/shared/addon/components/cluster-driver/driver-oracleoke/component.js
lib/shared/addon/components/cluster-driver/driver-oracleoke/template.hbs

======
This PR adds support for retrieving OKE cluster creation form values dynamically via the OKE [cluster driver](https://github.com/rancher-plugins/kontainer-engine-driver-oke).
======
Improves the usability of OKE cluster creation form values in a backwards compatible manner.
Linked Issues
======
Depends on [rancher/rancher#26963](https://github.com/rancher/rancher/pull/26963)
======
Fetching values from the OCI API is a followup from this[ review/PR.](https://github.com/rancher/ui/pull/3931)

Populate OKE cluster creation values dynamically

---

app/components/modal-edit-apikey/component.js
app/components/modal-edit-apikey/template.hbs

======
- We wanted to allow users to enter a custom date when there isn't a default ttl
- We also wanted to switch from minites to ms to be consistent with the past
======
Linked Issues
======
rancher/rancher#28678

Adding custom field to the simple expire and converting to ms

---

lib/nodes/addon/components/driver-amazonec2/component.js
lib/nodes/addon/components/driver-amazonec2/template.hbs
lib/shared/addon/components/searchable-select/component.js
translations/en-us.yaml

======
Handles the loadKmsKeys call more generically. Prior to this we only displayed the text input for kms keys if the call failed in a specific way but that was too specific. The KMS encryption is not required to create the template so there is no need to throw an error and stop the user from proceeding should the call fail.
======
Bugfix
Linked Issues
======
rancher/rancher#28719
rancher/rancher#28724
======

Forward port EC2 Node Template KMS Keys Error Handling

---

app/styles/components/_page-header.scss
app/styles/layout/_medium.scss

… drop down menues in mobile
======
Overwriting position: absolute on .ember-basic-dropdown-content class is fine for the mobile menu, but makes the submenus unuseable on big screens, where the normal desktop page is rendered. Moved to _medium.scss so it's still present on small screens but doesn't effect big screen-touch devices like iPads.
Seconds change removes fixed height on mobile-menu. If you hold your phone horizontally and open the menu, dropdowns at the end (like Tools) aren't visible, because they are cut by the fixed size of 100vh (which is not very much in horizontal mode).
======
- Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/27833 …

Fixed dropdown menues on touch devices (ipad)

---

lib/shared/addon/components/cluster-driver/driver-azureaks/component.js

======
UI is passing `Calico` to the azure command for AKS and it's not working, but when you us `calico` it works. 
======
Linked Issues
======
https://github.com/rancher/rancher/issues/26710
======
I haven't tested it but it's currently broken so this seems better than nothing. :)

AKS only works with lowercase "calico"

---

app/models/cluster.js
lib/shared/addon/components/cluster-driver/driver-eks/component.js
lib/shared/addon/components/node-group-row/component.js
lib/shared/addon/components/node-group-row/template.hbs
translations/en-us.yaml

======
To add support for syncing between EKS and Rancher both ways the backend has made changes to the way we save clusters on edit. 
When we initialize the EKS cluster component we'll first sync the contents of the upstream spec on to our eks config giving us the synced state. 
When we save the cluster, if the driver is EKS we'll loop through the EKS config, identifying and creating a new delta of only the changed fields by comparing the config to the upstream spec. 
Additionally we must preserve empty arrays and empty maps, so i've made every attempt to distinguish these between actually empty arrays and objects and null values in the upstream vs initialized empty arrays and objects that must exist for UI components to work. For example, the key value component that is …

EKS V2 Clusters Syncing & Save

---

app/models/cluster.js

======
Just needed to invoke intl.t() instead of intl().
======
Linked Issues
======
rancher/rancher#28903
======
I was able to verify that this resolves the console issue and allows the save to proceed further but I tested on a cluster that was in error so couldn't verify a full save.

Fix translation method call

---

app/models/cluster.js

======
For some reason the local variable eksConfig is undefined when
not running locally but the value is present on 'this'. I'm attempting
to just use the eksConfig attached to 'this.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/28541#event-3770683823
======
Since this wasn't reproducible locally I verified this using https://releases.rancher.com/ui/eks-config-undefined/index.html
I'm assuming that this is a bundling issue but I'm not positive. If you have any other ideas so that we don't run into this in the future I'm willing to go down another route.

Correct the value of ec2SshKey to be an empty string instead of null

---

app/models/cluster.js

======
The constructor name used within isObject was having it's value changed in production which caused the equality checks to fail.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/28541
I verified with https://releases.rancher.com/ui/eks-config-undefined-2/index.html using the build command
`./scripts/build-static -u -f -s -v eks-config-undefined-5`.
I saw that by default ec2SshKey was set to empty string and when I selected a value it would still be assigned when creating a cluster. I do not know the best way to verify the diffing portion.

Changing the implementation of isObject.

---

lib/shared/addon/components/settings/danger-zone/component.js

======
In settings `danger-zone` component, suppress exceptions when parsing JSON settings, defaulting to raw value on any failure.
======
Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/28504
======
Resolves error missed by #4136, implements approach proposed in https://github.com/rancher/rancher/issues/28504#issuecomment-685967570.

Suppress exceptions when parsing JSON settings, default to raw value

---

lib/nodes/addon/components/driver-oci/component.js

======
This change updates the (JavaScript) validation logic to allow the tenancy to be used as a valid compartment since it is technically the 'root compartment'.
The driver nor the OCI platform have issues provisioning a compute nodes to the root compartment / tenancy. Therefore, we should loosen up the overly restrictive validation. 
======
Linked Issues
======
[Here](https://github.com/rancher-plugins/rancher-machine-driver-oci/issues/3)
======
Backwards compatible change.
Backport to 2.4 forthcoming.

A tenancy should be a valid compartment (main)

---

lib/nodes/addon/components/driver-oci/component.js

======
This change updates the (JavaScript) validation logic to allow the tenancy to be used as a valid compartment since it is technically the 'root compartment'.
The driver nor the OCI platform have issues provisioning a compute nodes to the root compartment / tenancy. Therefore, we should loosen up the overly restrictive validation. 
======
Linked Issues
======
[Here](https://github.com/rancher-plugins/rancher-machine-driver-oci/issues/3)
======
Backwards compatible change.

A tenancy is a valid compartment (2-4 backport)

---

app/update-password/controller.js
app/update-password/template.hbs
lib/global-admin/addon/clusters/index/controller.js
lib/global-admin/addon/components/cluster-row/component.js
lib/global-admin/addon/components/cluster-row/template.hbs
translations/en-us.yaml

- Hide the option for the default landing page from the first-login modal.  It will just always be Ember for now.  You can still set this in user prefs.
- Add Dashboard link on each row of the cluster list

Dashboard integration

---

lib/monitoring/addon/cluster-setting/route.js
lib/monitoring/addon/cluster-setting/template.hbs
lib/monitoring/addon/components/enable-monitoring/component.js
lib/monitoring/addon/components/enable-monitoring/template.hbs
translations/en-us.yaml

======
Adds Check for the `cattle-monitoring-system` namespace, if the namespace exists we assume the new Rancher Monitoring chart has been installed. 
This may not cover all edge cases because this only verifies the namespace exists. One issue I see is that the chart was installed then removed and the namespace still exists for what ever reason. We'd still show this warning. Afaict, there is no way to load the workloads for the new chart as the workloads exists in the namespace without a project. Loading the workloads would let us do the same podspec check we do in dashboard. I dont see this as being a deal breaker though, as this is only a warning, its doesn't stop the user from actually enabling monitoring. If that is the desired result perhaps the backend should …

Add warning when Rancher Monitoring Namespace exists

---

app/authenticated/cluster/cis/scan/template.hbs
app/authenticated/cluster/notifier/index/template.hbs
lib/alert/addon/index/template.hbs
lib/global-admin/addon/components/cluster-row/template.hbs
lib/global-admin/addon/multi-cluster-apps/catalog/template.hbs
lib/global-admin/addon/multi-cluster-apps/index/template.hbs
lib/istio/addon/components/istio-catalog/template.hbs
lib/logging/addon/components/logging/new-edit/component.js
lib/logging/addon/components/logging/new-edit/template.hbs
lib/monitoring/addon/components/enable-monitoring/template.hbs
lib/monitoring/addon/index/template.hbs
lib/pipeline/addon/components/enable-repositories/template.hbs
lib/pipeline/addon/settings/template.hbs

======
Wraps all cluster explorer warnings in a check for `cluster.isReady` because linking to these areas before the cluster is ready (and dashboard) causes 404's.
======
Bugfix
Linked Issues
======
rancher/rancher#29199
======
While testing I found an issue where the logging page would die because we do a version check on `version.gitVersion` which is only populated after the cluster is ready. Added some try catch logic around this.

Cluster Explorer Links

---

lib/global-admin/addon/components/new-multi-cluster-app/template.hbs

======
Cosmetic request
There is a feature in Rancher UI, not sure what the correct name is -- I'm calling it the 'chart preview' feature. It can be found by navigating from the main menu **Apps->Launch->Chart->PREVIEW** and looks like this:
This feature can be a convenient way to quickly evaluate new charts. 👍 
With that said, I'm seeing some cosmetic behavior that could be better - a "quality of life" opportunity having to do with the its responsiveness currently works.
I'm seeing that at smaller browser window widths (breakpoints) this dropdown presents at full width, but at higher widths (e.g. MBP16" maximized browser window for one example) the current [classes](https://github.com/rancher/ui/blob/3c711f751829946eca72131efb1f1df47f1b94d1/lib/global-admin/addon/componen …

[2.5] cosmetic: template dropdown full width consistent across all breakpoints

---

app/components/modal-edit-setting/component.js

======
Handle possible exception thrown when opening JSON setting editor modal.
======
Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/28504
======
Resolves bug found in https://github.com/rancher/rancher/issues/28504#issuecomment-699702037

Fix frozen settings modal when parsing invalid JSON setting

---

lib/nodes/addon/components/driver-vmwarevsphere/component.js

Changes the label for a resource pool to be the full path minus the first two pieces.
e.g. `/RNCH-HE-FMT/host/FMT2.R620.1/Resources/luther/testerrr`
label was: `testerrr`
label will be `FMT2.R620.1/Resources/luther/testerrr`
https://github.com/rancher/rancher/issues/24507

[v2.4] Vsphere Resource Pool Sub-Directory Fix

---

app/update-password/template.hbs

Set image radio action to not prevent default, closure actions set preventDefault true by default. When prevent is set true the radio button click gets swallowed up by the closure. 
======
======
Bugfix
Linked Issues
======
rancher/rancher#29434
======

Rancher Welcome Screen

---

app/update-password/template.hbs

Set image radio action to not prevent default, closure actions set preventDefault true by default. When prevent is set true the radio button click gets swallowed up by the closure. 
======
======
Bugfix
Linked Issues
======
rancher/rancher#29434
======

[2.5-fixes] Rancher Welcome Screen

---

app/components/volume-source/source-csi-volume-longhorn/component.js

======
Longhorn driver no longer uses the options key, so use the correct volume attributes key instead. 
======
bug
Linked Issues
======
rancher/rancher#29484
======

[2.5] Longhorn Uses Default Values on View

---

lib/shared/addon/components/cluster-driver/driver-googlegke/component.js
lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
lib/shared/addon/components/cru-cloud-provider/component.js
lib/shared/addon/components/cru-cloud-provider/template.hbs

======
This issue cropped up after a large dependency upgrade and I believe it has to do with some underlying ember changes. Basically we'd hit a race condition where we'd click next before the observer has had a chance to update the project id.
Found an additional issue where the observer on zone change would cause all the fetchs to fire again after the cluster has saved because we merge the results, I added checks to see if we'd saved as saving was already set false but we hadn't started destroying yet.
Also adds update for broken cloud provider selection
======
bugfix
Linked Issues
======
rancher/rancher#29646
rancher/rancher#29685
======

gke project id not set before fetching cluster resources

---

lib/shared/addon/components/cluster-driver/driver-googlegke/component.js
lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
lib/shared/addon/components/cru-cloud-provider/component.js
lib/shared/addon/components/cru-cloud-provider/template.hbs

======
This issue cropped up after a large dependency upgrade and I believe it has to do with some underlying ember changes. Basically we'd hit a race condition where we'd click next before the observer has had a chance to update the project id.
Found an additional issue where the observer on zone change would cause all the fetchs to fire again after the cluster has saved because we merge the results, I added checks to see if we'd saved as saving was already set false but we hadn't started destroying yet.
Also adds update for broken cloud provider selection
======
bugfix
Linked Issues
======
rancher/rancher#29646
rancher/rancher#29685
======

[2.5.2] gke project id not set before fetching cluster resources

---

app/authenticated/cluster/route.js
app/authenticated/project/route.js
app/components/page-header-project/component.js
lib/global-admin/addon/clusters/index/controller.js
lib/global-admin/addon/clusters/index/template.hbs
lib/global-admin/addon/clusters/route.js
lib/shared/addon/components/cru-cloud-provider/component.js
lib/shared/addon/settings/service.js
lib/shared/addon/utils/constants.js

If the new setting `hide-local-cluster` exists and is true we will hide the local cluster from the page header/search and global admin cluster lists page. this doesnt prevent api access.
Additionally if the setting is true and a user attempts to navigate directly to a cluster or project route we will redirect them to the authenticated index route which subsequently redirects to global admin.
======
======
New Feature
Linked Issues
======
rancher/rancher#29325
======

Hide Local Cluster 

---

app/authenticated/cluster/route.js
app/authenticated/project/route.js
app/components/page-header-project/component.js
lib/global-admin/addon/clusters/index/controller.js
lib/global-admin/addon/clusters/index/template.hbs
lib/global-admin/addon/clusters/route.js
lib/shared/addon/components/cru-cloud-provider/component.js
lib/shared/addon/settings/service.js
lib/shared/addon/utils/constants.js

If the new setting `hide-local-cluster` exists and is true we will hide the local cluster from the page header/search and global admin cluster lists page. this doesnt prevent api access.
Additionally if the setting is true and a user attempts to navigate directly to a cluster or project route we will redirect them to the authenticated index route which subsequently redirects to global admin.
======
======
New Feature
Linked Issues
======
rancher/rancher#29325
======

[2.5.2] Hide Local Cluster

---

lib/nodes/addon/components/driver-oci/component.js

[2.5] Filter out OL-8.x images until it is supported by OCI machine driver.

---

lib/nodes/addon/components/driver-oci/component.js

[2.4] Filter out OL-8.x images until it is supported by OCI machine driver.

---

lib/shared/addon/mixins/store-tweaks.js

======
volatile was deprecated, during the ember 3.12 -> 3.20 upgrade the headers computed property was incorrectly changed to a regular computed property when it should have actually been converted to a native getter as this property is not intended to be tracked.
======
Bugfix
Linked Issues
======
rancher/rancher#29751
======

[2.5.2] Logout Bug - CSFR not being refetched

---

lib/shared/addon/components/confirm-delete/component.js
lib/shared/addon/components/confirm-delete/template.hbs
translations/en-us.yaml

======
Rancher UI does not allow a user to create a 2 node etcd cluster but that is not a hard requirement on the ETCD side so they can exist. If a user is running a 2 node etcd cluster the UI will show a warning when removing an etcd node from a 2 node cluster. 
======
New Feature
Linked Issues
======
rancher/rancher#29665
======
Since the UI does not allow a user to create this type of cluster (you can only have 1, 3, 5, etc etcd nodes) the 2 node cluster has to be created via the RKE CLI or some other manner outside of Rancher UI.

2 ETCD Node Delete Warning

---

lib/shared/addon/components/confirm-delete/component.js
lib/shared/addon/components/confirm-delete/template.hbs
translations/en-us.yaml

======
Rancher UI does not allow a user to create a 2 node etcd cluster but that is not a hard requirement on the ETCD side so they can exist. If a user is running a 2 node etcd cluster the UI will show a warning when removing an etcd node from a 2 node cluster. 
======
New Feature
Linked Issues
======
rancher/rancher#29665
======
Since the UI does not allow a user to create this type of cluster (you can only have 1, 3, 5, etc etcd nodes) the 2 node cluster has to be created via the RKE CLI or some other manner outside of Rancher UI.

[2.5.3] 2 ETCD Node Delete Warning

---

lib/shared/addon/components/container-shell/component.js

======
Rather than add a warning the user needs to exit I've added a send to the socket for `exit\r\n` to disconnect the process before the socket closes
======
bugfix
Linked Issues
======
rancher/rancher#16192
======

[2.5.3] Send exit to container exec on close of container-shell

---

lib/shared/addon/components/container-shell/component.js

======
Rather than add a warning the user needs to exit I've added a send to the socket for `exit\r\n` to disconnect the process before the socket closes
======
bugfix
Linked Issues
======
rancher/rancher#16192
======

[2.4.10] Send exit to container exec on close of container-shell

---

lib/global-admin/addon/components/form-global-roles/component.js
lib/global-admin/addon/security/accounts/new/controller.js
lib/global-admin/addon/security/accounts/new/route.js
lib/global-admin/addon/security/accounts/new/template.hbs

======
If a user was created and the subsequent global role calls failed there was no way to re-save the roles from the create page.
Now if a user creates but the roles fail the creator may select different roles and re-save to create the roles with out creating the new user.
======
Bugfix
Linked Issues
======
rancher/rancher#29315
======

[2.5.3] Global User Create Error Handling 

---

lib/shared/addon/version-choices/service.js

When selecting UAE central parseCloudProviderVersionChoices was returning 2 undefined elements which then broke the dropdown. It seemed that parseCloudProviderVersionChoices should only return valid choices so I filtered out falsey values.
======
Linked Issues
======
rancher/rancher#28341

Fixing azure k8s version dropdown from breaking when selecing uae-central

---

lib/shared/addon/components/cluster-driver/driver-eks/template.hbs

======
previously we prevented users from changing the choice of standard or custom vpc which also loads the security groups, this adds the same logic back in for eks v2
======
Bugfix
Linked Issues
======
rancher/rancher#30301
======

EKS prevent users from changing vpc/sub net choice after selected

---

lib/shared/addon/components/cluster-driver/driver-eks/template.hbs

======
previously we prevented users from changing the choice of standard or custom vpc which also loads the security groups, this adds the same logic back in for eks v2
======
Bugfix
Linked Issues
======
rancher/rancher#30301
======

[2.5.4] EKS prevent users from changing vpc/sub net choice after selected

---

lib/shared/addon/components/cru-cluster/component.js

======
When we changed up how the cluster selection and creation was done to account for the provider param there was a bug in HA local clusters that prevented the save and cancel buttons from showing up. 
======
Bugfix
Linked Issues
======
rancher/rancher#30354
======

[2.5.4] Missing Save/Cancel Buttons Imported Cluster

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js

======
~When we embed comments into the yaml on Cluster Edit if the comment is embedded in a multi-line string the yaml editor breaks and users have to remove the comments (or nest them correctly) to save the cluster. AFAICT without implementing some pretty complex logic it would be pretty hard to detect if we are in a mulit-line string while looping over the yaml lines to build the content for the editor.~
~I am proposing the following solution:
While looping, keep track of the lines whitespace. If we embed comments, prepend tracked whitespace to the comment line. 
Before dumping the yaml to an object, so it can be parsed over the cluster config (clusters dont take a yaml file), strip all comment lines. Normally we dont have to do this because js-yaml will drop comments …

Edit Yaml Comments Nesting Level

---

app/components/modal-rotate-encryption-key/component.js
app/components/modal-rotate-encryption-key/template.hbs
app/models/cluster.js
lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
translations/en-us.yaml

======
This PR exposes the `rotateEncryptionKey` action on RKE clusters. Adds a new modal and warning about taking a backup before proceeding.
Additionally, I have added some logic around when we show the action in the UI. We explicitly do not expose the action until the cluster has at least one backup, and that backup is within the last 6 hours (or 360 min). Six hours is an arbitrary time frame, and one could argue the 'time since last backup' check should be in the backend, but the implementation was minimal and I think the UX is improved since we want users to make a backup. The backups can take a while depending on the size of the cluster and six hours seems sufficient. 
======
New Feature
Linked Issues
======
rancher/rancher#30077 …

Expose rotate encryption keys action and modal

---

app/components/modal-rotate-encryption-key/component.js
app/components/modal-rotate-encryption-key/template.hbs
app/models/cluster.js
lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
translations/en-us.yaml

======
This PR exposes the `rotateEncryptionKey` action on RKE clusters. Adds a new modal and warning about taking a backup before proceeding.
Additionally, I have added some logic around when we show the action in the UI. We explicitly do not expose the action until the cluster has at least one backup, and that backup is within the last 6 hours (or 360 min). Six hours is an arbitrary time frame, and one could argue the 'time since last backup' check should be in the backend, but the implementation was minimal and I think the UX is improved since we want users to make a backup. The backups can take a while depending on the size of the cluster and six hours seems sufficient. 
======
New Feature
Linked Issues
======
rancher/rancher#30077 …

[2.5.x] Expose rotate encryption keys action and modal

---

app/authenticated/cluster/route.js
app/models/cluster.js

======
Adds isActive to computed check for canRotateEncryptionKey. Originally I only keyed on Transition doesn't always update as often or as fast and isActive. I dont see a downside in checking both though its unlikely we'd ever get into a state where they are both not true or false.
Add `etcdBackup` to the list of preloads for RKE cluster to ensure rotate encryption keys works from a fresh load of the ui at the cluster level.
======
Bugfix
Linked Issues
======
rancher/rancher#30552
rancher/rancher#30553
======

Rotate Secrets Encryption Bugs

---

app/authenticated/cluster/route.js
app/models/cluster.js

======
Adds isActive to computed check for canRotateEncryptionKey. Originally I only keyed on Transition doesn't always update as often or as fast and isActive. I dont see a downside in checking both though its unlikely we'd ever get into a state where they are both not true or false.
Add `etcdBackup` to the list of preloads for RKE cluster to ensure rotate encryption keys works from a fresh load of the ui at the cluster level.
======
Bugfix
Linked Issues
======
rancher/rancher#30552
rancher/rancher#30553
======

[2.5.4] Rotate Secrets Encryption Bugs

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js

======
Adds in one off check for secretsEncryption.customConfig. The custom config has a type of `map[json]` and when we process this for the edit yaml view we can goof some of the keys in the arbitrary JSON.
Specifically the `Resources` key gets dasherized and lower cased which borks  the cluster on save.
======
Linked Issues
======
rancher/rancher#30555
======

Edit As Yaml Resources Key Name Bug

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js

======
Adds in one off check for secretsEncryption.customConfig. The custom config has a type of `map[json]` and when we process this for the edit yaml view we can goof some of the keys in the arbitrary JSON.
Specifically the `Resources` key gets dasherized and lower cased which borks  the cluster on save.
======
Linked Issues
======
rancher/rancher#30555
======

[2.5.4] Edit As Yaml Resources Key Name Bug

---

lib/nodes/addon/components/driver-vmwarevsphere/component.js

======
For props that have options which depend on the selected credentials or datacenter this ensures that the props are reinitialized to one of the options.
======
Linked Issues
======
rancher/rancher#30074
======
This one was a little difficult to verify since I only have access to one vsphere datacenter. I ended up mocking the responses in a way that I think will be sufficient but we may encounter more edge cases.

Ensuring the initial values are set on vsphere template when switching credentials

---

lib/nodes/addon/components/driver-vmwarevsphere/component.js

======
For props that have options which depend on the selected credentials or datacenter this ensures that the props are reinitialized to one of the options.
======
Linked Issues
======
rancher/rancher#30074
======
This one was a little difficult to verify since I only have access to one vsphere datacenter. I ended up mocking the responses in a way that I think will be sufficient but we may encounter more edge cases.

[backport 2.5] Ensuring the initial values are set on vsphere template when switching credentials

---

lib/nodes/addon/components/driver-vmwarevsphere/component.js

======
For props that have options which depend on the selected credentials or datacenter this ensures that the props are reinitialized to one of the options.
======
Linked Issues
======
rancher/rancher#30074
======
This one was a little difficult to verify since I only have access to one vsphere datacenter. I ended up mocking the responses in a way that I think will be sufficient but we may encounter more edge cases.

[backport 2.4] Ensuring the initial values are set on vsphere template when switching credentials

---

lib/global-admin/addon/mixins/ldap-auth.js
lib/global-admin/addon/security/authentication/activedirectory/controller.js
lib/global-admin/addon/security/authentication/freeipa/controller.js
lib/global-admin/addon/security/authentication/openldap/controller.js
lib/global-admin/addon/templates/-ldap-config.hbs
translations/en-us.yaml

======
refactor ldap auth provider encryption to a radio group and mixin for
all auth providers. exposes the option on all ldap providers as well.
expose CA cert input when user selects STARTTLS
======
Bugfix
Linked Issues
======
rancher/rancher#30348
rancher/rancher#30783
======
Sorted ldap yaml keys

[2.4.13] LDAP auth provider encryption options and bugs

---

lib/global-admin/addon/mixins/ldap-auth.js
lib/global-admin/addon/security/authentication/activedirectory/controller.js
lib/global-admin/addon/security/authentication/freeipa/controller.js
lib/global-admin/addon/security/authentication/openldap/controller.js
lib/global-admin/addon/templates/-ldap-config.hbs
translations/en-us.yaml

======
refactor ldap auth provider encryption to a radio group and mixin for
all auth providers. exposes the option on all ldap providers as well.
expose CA cert input when user selects STARTTLS
======
Bugfix
Linked Issues
======
rancher/rancher#30348
rancher/rancher#30783
======
Sorted ldap yaml keys

[2.5.x] LDAP auth provider encryption options and bugs

---

lib/global-admin/addon/mixins/ldap-auth.js
lib/global-admin/addon/security/authentication/activedirectory/controller.js
lib/global-admin/addon/security/authentication/freeipa/controller.js
lib/global-admin/addon/security/authentication/openldap/controller.js
lib/global-admin/addon/templates/-ldap-config.hbs
translations/en-us.yaml

======
refactor ldap auth provider encryption to a radio group and mixin for
all auth providers. exposes the option on all ldap providers as well.
expose CA cert input when user selects STARTTLS
======
Bugfix
Linked Issues
======
rancher/rancher#30348
rancher/rancher#30783
======
Sorted ldap yaml keys

LDAP auth provider encryption options and bugs

---

lib/shared/addon/components/select-value-check/component.js

======
This added the watcher for options
======
Linked Issues
======
rancher/rancher#30074
======
This apparently only got missed for 2.4. 2.5 and master both have this change which is why I don't have forward ports.
- https://github.com/rancher/ui/blob/master/lib/shared/addon/components/select-value-check/component.js
- https://github.com/rancher/ui/blob/2.5-fixes/lib/shared/addon/components/select-value-check/component.js

SelectValueCheck wasn't updating when the options were changed

---

lib/shared/addon/utils/constants.js

======
======
LKE does not report component status. Adding LKE to this constant appears to hide false alerts.
Linked Issues
======
======

Gray out scheduler status for linode lke

---

translations/en-us.yaml

======
Update `en-us` translation for Docker version and Windows Server version to refer to docs rather than give a concrete number. **Reasoning**: Windows Server 1903 SAC has reached EOM. The current wording suggests that all Windows Server versions at and above 1809 are valid, when that is not the case. In fact, Windows Server SAC releases reach EOM after ~1 year and release about ~6 months. Referring to the docs would provide one source of truth that's easier to maintain and would provide consistent messaging (note: the docs should be updated as well to reflect 1903 SAC EOM, but that is a separate issue).
======
Updating `yaml` file(s) to change the text that appears on screen. This is a non-breaking, "text-only" change.
Linked Issues
====== …

Update Windows Server version to refer to docs

---

lib/shared/addon/components/custom-command/component.js

======
windows nodes can only be workers, if a user switches to windows and has cp or etcd set we need to set it to false
======
bugfix
Linked Issues
======
rancher/rancher#30903
======

[2.5.x] custom cluster command set etcd/cp false if windows

---

app/models/node.js

======
Change node `displayName` to actually return the prefix (unique data) of a node that has siblings with the same domain in the name.
======
Linked Issues
======
rancher/rancher#27873
======
@deniseschannon @gaktive  A few years back some code was added reduce the size of the node names because users would ask for `requestedHostname: thing-you-asked-for` but then the actual node name would be something like `thing-you-asked-for.us-west-3.aws.compute.internal` after the node was finished creating. In order to reduce the redundant info on the nodes page we added logic to strip the domain off a node name if there are multiple nodes with the same domain. As you can see in my screenshot resolving fixing the code displays the correct …

display prefix of node name (drop domain)

---

lib/logging/addon/components/logging/input-logging-config/component.js
lib/logging/addon/components/logging/new-edit/component.js

======
Removed a scheduled wrapper around the value update of the `input-logging-config` that would prevent the value from being updated in some cases. This seemed to be a race condition that was maybe amplified by some frame work updates because the original change was QA'd and passed. I believe that the `next` wrapper was put in place because the update function were being called numerous times from the different observers in the file. I added a throttle wrapper to help this as well. 
The fluent config has a weight param that is a type `int`, I added code to cast this back to int from string during the formSync. 
======
Bugfix
Linked Issues
======
rancher/rancher#31149
rancher/rancher#31184
======

V1 Logging Bugs

---

lib/logging/addon/components/logging/input-logging-config/component.js
lib/logging/addon/components/logging/new-edit/component.js

======
Removed a scheduled wrapper around the value update of the `input-logging-config` that would prevent the value from being updated in some cases. This seemed to be a race condition that was maybe amplified by some frame work updates because the original change was QA'd and passed. I believe that the `next` wrapper was put in place because the update function were being called numerous times from the different observers in the file. I added a throttle wrapper to help this as well. 
The fluent config has a weight param that is a type `int`, I added code to cast this back to int from string during the formSync. 
======
Bugfix
Linked Issues
======
rancher/rancher#31149
rancher/rancher#31184
======

[2.5.x] V1 Logging Bugs

---

lib/shared/addon/components/cru-cloud-provider/component.js
lib/shared/addon/components/cru-cloud-provider/template.hbs
translations/en-us.yaml

======
Provide more context around in-tree and out-of-tree cloud providers
- Add helper text to help people find the out-of-tree providers for vsphere
- Label each in-tree provider with (In-tree) label
- Show a deprecated message for each in-tree option
======
Linked Issues
======
rancher/rancher#31162

Provide more context around in-tree and out-of-tree cloud providers

---

lib/shared/addon/components/node-group-row/component.js
lib/shared/addon/components/node-group-row/template.hbs

======
While investigating another issue that was reopened I discovered an assumption that the UI was making was incorrect leading to the refactor. When using a launch template the UI parses the data for various fields onto the model from the launch template version info after it is loaded. This has never presented an issue so my assumption that this data would always be present was incorrect. There is a 5 min window after the cluster has provision where in a sync between the upstream and rancher versions of the cluster happens, if the node group is using a launch template then any data from the managed fields is dropped. I did not see this because while developing I apparently never waiting 5 min between when a cluster came up and when I edited it.
This PR addresses the …

EKS V2 Node Group Refactor

---

lib/shared/addon/components/node-group-row/component.js
lib/shared/addon/components/node-group-row/template.hbs

======
While investigating another issue that was reopened I discovered an assumption that the UI was making was incorrect leading to the refactor. When using a launch template the UI parses the data for various fields onto the model from the launch template version info after it is loaded. This has never presented an issue so my assumption that this data would always be present was incorrect. There is a 5 min window after the cluster has provision where in a sync between the upstream and rancher versions of the cluster happens, if the node group is using a launch template then any data from the managed fields is dropped. I did not see this because while developing I apparently never waiting 5 min between when a cluster came up and when I edited it.
This PR addresses the …

[2.5.x] EKS V2 Node Group Refactor

---

lib/nodes/addon/components/driver-vmwarevsphere/component.js

======
The tags and custom attribute requests were never being made due to a recent change.
This change filtered out requests that didn't have a datacenter degined for everything but the datacenter resource. However this should've included 3 other resources that don't need a datacenter during the request.
======
Linked Issues
======
rancher/rancher#31285

Fixing a problem where tags and custom attributes couldn't be added

---

app/components/modal-about/component.js

The about page has a link to downloat the list of linux & windows images, but produces a file that starts with a dot for no obvious reason and will just make the file hidden on Mac/Linux systems and hard to find.

Don't produce a dotfile-hidden images list

---

app/authenticated/cluster/edit/route.js
lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
lib/shared/addon/components/cru-cluster/component.js
lib/shared/addon/components/cru-cluster/template.hbs
lib/shared/addon/components/form-agent-env-var/component.js

======
- Fixed issues with determining the provider when editing clusters that are still provisioning.
- Fixed empty values causing problems
- Fixed an issue where the default value wasn't getting set properly for configmaps and secrets when selecting the type and nothing else
- Adding agent env vars to import cluster
======
Linked Issues
======
https://github.com/rancher/rancher/issues/31023#issuecomment-784717552
rancher/rancher#31505

[forwardport] Fixing several issues with agentEnvVars/adding to import cluster

---

lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
lib/shared/addon/components/form-agent-env-var/component.js
lib/shared/addon/components/form-agent-env-var/template.hbs
translations/en-us.yaml

======
Since the reference types can't exist until the cluster is created I added an option to disable all reference types and use it during RKE create
Even though the backend doesn't indicate the variable name is required we're marking it as such because it casues cluster to fail. No validation will be done at this time.
======
Linked Issues
======
rancher/rancher#31528

Disabling all reference types on rke create for agentenvvar and marking variable name field as required

---

lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
lib/shared/addon/components/form-agent-env-var/component.js
lib/shared/addon/components/form-agent-env-var/template.hbs
translations/en-us.yaml

======
Since the reference types can't exist until the cluster is created I added an option to disable all reference types and use it during RKE create
Even though the backend doesn't indicate the variable name is required we're marking it as such because it casues cluster to fail. No validation will be done at this time.
======
Linked Issues
======
rancher/rancher#31528

[backport] Disabling all reference types on rke create for agentenvvar and marking variable name field as required

---

lib/shared/addon/components/cru-cluster/template.hbs

======
Regression introduced with Eks Imported clusters that prevented generic imported clusters from getting saved. Added some comments to clarify the branches logic as well. Didn't want to refactor because we're so close to release. 
======
bugfix
Linked Issues
======
rancher/rancher#31547
======

enable save on edit if cluster is generic import

---

lib/shared/addon/components/cru-cluster/template.hbs

======
Regression introduced with Eks Imported clusters that prevented generic imported clusters from getting saved. Added some comments to clarify the branches logic as well. Didn't want to refactor because we're so close to release. 
======
bugfix
Linked Issues
======
rancher/rancher#31547
======

[2.5.x] enable save on edit if cluster is generic import

---

app/authenticated/cluster/edit/controller.js
app/models/cluster.js
lib/shared/addon/components/cru-cluster/template.hbs

======
In a prior PR I put in a dependency on a computed property to show the correct save. While reviewing another PR I saw that this was actually incorrect. The change technically worked but in the case of `K3s` clusters which are technically an import, we would show a second save button. This ensures that when selecting edit, we send the importProvider (added for eks imports) which will ensure the DriverImport component is shown with the correct save button and no double buttons will be produced for `K3s` edits.
======
bugfix
Linked Issues
======
rancher/rancher#31547
======

[2.5.x] explicitly pass import provider for edit import

---

lib/istio/addon/components/istio-catalog/component.js
lib/istio/addon/components/istio-catalog/template.hbs
translations/en-us.yaml

======
During istio configuration we previously hide a collection of keys with static answers we set to ensure the default setup would work correctly. This created  a case when a user made could make an edit to one of those hidden keys on initial configuration but when editing or upgrading the key would be hidden. 
I've removed the logic that hides those keys from the custom answers section on edit. 
Updated the create case to populate the custom answers object with the hidden keys on init.
Added a warning banner informing the user that changing these keys is an advanced use case.
Warning: 
`Custom Answers are an advanced configuration option. Rancher pre-configures custom answers to ensure that specific prerequisites are met for the default Istio configuration. Adding or …

Show istio hidden answers

---

lib/shared/addon/components/cluster-driver/driver-import/component.js
lib/shared/addon/components/cluster-driver/driver-import/template.hbs
lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
lib/shared/addon/components/cru-cluster/component.js
lib/shared/addon/components/cru-cluster/template.hbs

======
If a user wants to edit the environment vars on a custom cluster and rerun the registration command they must first save the cluster. EnvVars are not simply appended to the cluster registration command as some of the other params are but are actually apart of the command as fetched from the backend. Rather than try to slice up the command to append our new vars before save I've refactored the logic for both custom and imported clusters to not show the command on edit until the cluster has been saved. This breaks the previous UX pattern of displaying the command on initialization of the edit view but I think this is a better UX regardless. This explicitly requires action from the user before just fetching the command, which if that is all they want can be done from …

Cluster Reg Commands Not Updating on Edit of Env Vars

---

lib/istio/addon/components/istio-catalog/component.js
lib/istio/addon/components/istio-catalog/template.hbs
translations/en-us.yaml

======
During istio configuration we previously hide a collection of keys with static answers we set to ensure the default setup would work correctly. This created  a case when a user made could make an edit to one of those hidden keys on initial configuration but when editing or upgrading the key would be hidden. 
I've removed the logic that hides those keys from the custom answers section on edit. 
Updated the create case to populate the custom answers object with the hidden keys on init.
Added a warning banner informing the user that changing these keys is an advanced use case.
Warning: 
`Custom Answers are an advanced configuration option. Rancher pre-configures custom answers to ensure that specific prerequisites are met for the default Istio configuration. Adding or …

[2.5.x] Show istio hidden answers

---

lib/shared/addon/components/cluster-driver/driver-import/component.js
lib/shared/addon/components/cluster-driver/driver-import/template.hbs
lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
lib/shared/addon/components/cru-cluster/component.js
lib/shared/addon/components/cru-cluster/template.hbs

======
If a user wants to edit the environment vars on a custom cluster and rerun the registration command they must first save the cluster. EnvVars are not simply appended to the cluster registration command as some of the other params are but are actually apart of the command as fetched from the backend. Rather than try to slice up the command to append our new vars before save I've refactored the logic for both custom and imported clusters to not show the command on edit until the cluster has been saved. This breaks the previous UX pattern of displaying the command on initialization of the edit view but I think this is a better UX regardless. This explicitly requires action from the user before just fetching the command, which if that is all they want can be done from …

[2.5.x] Cluster Reg Commands Not Updating on Edit of Env Vars 

---

lib/global-admin/addon/security/authentication/azuread/controller.js

As part of this https://github.com/rancher/rancher/issues/31562 I changed azure auth to use the same redirect url as other auth types, `/verify-auth`. This works as expected for new setups, but while looking at a different azuread issue I realized it was a poor decision, and will break preexisting  azuread configs that use `/verify-auth-azure`. Both ui's should use `/verify-auth-azure` for azuread, which leverages the same redirect logic as` /verify-auth`. Related Dashboard PR: https://github.com/rancher/dashboard/pull/2564

use verify-auth-azure instead of verify-auth

---

lib/shared/addon/oauth/service.js

See https://github.com/rancher/dashboard/pull/2631  azureAD and googleoauth state params happen to encode without more than 1 `=` here, so no bug to reproduce on this side, but the same flaw in encoding is present here.

fix base64 url-safe regex

---

lib/shared/addon/oauth/service.js

See https://github.com/rancher/dashboard/pull/2631  azureAD and googleoauth state params happen to encode without more than 1 `=` here, so no bug to reproduce on this side, but the same flaw in encoding is present here.

[2.5.x] fix url-safe base64 regex

---

app/models/cluster.js
lib/shared/addon/components/cluster-driver/driver-gke/component.js
lib/shared/addon/components/cluster-driver/driver-gke/template.hbs
lib/shared/addon/components/gke-node-pool-row/component.js
lib/shared/addon/components/gke-node-pool-row/template.hbs

======
This was my bad, I accidentally left the edit syncing out because I had so much trouble getting clusters launched when I was working on it. Added in the sync, which is slightly different then EKS where we loop over the config keys and grab items off the upstreamspec. But for GKE the config doesn't always contain all the keys (not values) of the upstream spec so we miss some data when looping over it. This loops over the keys on the upstream spec and writes them to the config to sync. 
Change an accidental ref from nodeGroup to nodePool
Adds logic to move to the correct step automatically after user selects cloud credentials on the edit flow.
Changes the default location type to zonal instead of regional.
======
Bugfix
Linked Issues
====== …

[2.5.x] GKE V2 Edit Sync Upstream Config

---

app/models/cluster.js
lib/shared/addon/components/cluster-driver/driver-gke/component.js
lib/shared/addon/components/cluster-driver/driver-gke/template.hbs
lib/shared/addon/components/gke-node-pool-row/component.js
lib/shared/addon/components/gke-node-pool-row/template.hbs

======
This was my bad, I accidentally left the edit syncing out because I had so much trouble getting clusters launched when I was working on it. Added in the sync, which is slightly different then EKS where we loop over the config keys and grab items off the upstreamspec. But for GKE the config doesn't always contain all the keys (not values) of the upstream spec so we miss some data when looping over it. This loops over the keys on the upstream spec and writes them to the config to sync. 
Change an accidental ref from nodeGroup to nodePool
Adds logic to move to the correct step automatically after user selects cloud credentials on the edit flow.
Changes the default location type to zonal instead of regional.
======
Bugfix
Linked Issues
====== …

GKE V2 Edit Sync Upstream Config

---

lib/shared/addon/oauth/service.js

https://github.com/rancher/dashboard/issues/2116 - this issue is not visible in Ember but this url-safe base64 code is the same, so same flaw exists; when `char = '==' m[char] = undefined` and the returned string isn't valid base64
related dashboard pr: https://github.com/rancher/dashboard/pull/2692

[2.5] fix base64 encode

---

lib/shared/addon/oauth/service.js

https://github.com/rancher/dashboard/issues/2116 - this issue is not visible in Ember but this url-safe base64 code is the same, so same flaw exists; when `char = '==' m[char] = undefined` and the returned string isn't valid base64
related dashboard pr: https://github.com/rancher/dashboard/pull/2692

fix base64 encoding function

---

app/models/principal.js

======
Updating the principal logicalType to account for okta
This will allow the group principals to be displays on the project members section.
======
Linked Issues
======
rancher/rancher#30401

Updating the principal logicalType to account for okta

---

lib/shared/addon/components/cru-cluster/component.js

======
We would spuriously skip the command step because we skipped post save and occasionally the cluster would have its state set to active which is an indication to skip the command.
======
Linked Issues
======
rancher/rancher#32242

Now we always show the command for custom import clusters

---

lib/shared/addon/components/cru-cluster/component.js

======
We would spuriously skip the command step because we skipped post save and occasionally the cluster would have its state set to active which is an indication to skip the command.
======
Linked Issues
======
rancher/rancher#32242

[backport 2.5] Now we always show the command for custom import clusters

---

app/models/cluster.js
lib/shared/addon/components/cluster-driver/driver-gke/component.js
lib/shared/addon/components/cluster-driver/driver-gke/template.hbs

======
Fixes a typo in the logic that decides if we should show the registration command for private GKE clusters.
======
Bugfix
Linked Issues
======
rancher/rancher#32303
======
Also swaps the Region and Zone drop downs from a select to searchable select. There can be a lot of these so it makes sense to allow a user to search.

GKE v2 - Import Command Bug

---

app/models/cluster.js
lib/shared/addon/components/cluster-driver/driver-gke/component.js
lib/shared/addon/components/cluster-driver/driver-gke/template.hbs

======
Fixes a typo in the logic that decides if we should show the registration command for private GKE clusters.
======
Bugfix
Linked Issues
======
rancher/rancher#32303
======
Also swaps the Region and Zone drop downs from a select to searchable select. There can be a lot of these so it makes sense to allow a user to search.

[2.5.x] GKE v2 - Import Command Bug

---

lib/shared/addon/components/gke-node-pool-row/component.js
lib/shared/addon/components/gke-node-pool-row/template.hbs
translations/en-us.yaml

======
Add warning for imported clusters when the node pool does not contain the autoUpgrade and autoRepair management fields in a disabled state. 
======
Bugfix
Linked Issues
======
rancher/rancher#32282
======
N/A

GKE Imported Cluster warning

---

lib/shared/addon/components/gke-node-pool-row/component.js
lib/shared/addon/components/gke-node-pool-row/template.hbs
translations/en-us.yaml

======
Add warning for imported clusters when the node pool does not contain the autoUpgrade and autoRepair management fields in a disabled state. 
======
Bugfix
Linked Issues
======
rancher/rancher#32282
======
N/A

[2.5.x] GKE Imported Cluster warning

---

lib/shared/addon/components/cluster-driver/driver-gke/component.js
lib/shared/addon/components/cluster-driver/driver-gke/template.hbs

======
The field is not actually required. GKE will make up its own if not included.
======
Bugfix
Linked Issues
======
rancher/rancher#32351
======
Fixes a change that hide the cluster and service ranges from auto created subnetworks, when in fact it should only be disabled if a range name for either has been selected OR  a shared subnetwork has been selected.

[2.5.x] GKE V2 Remove Required from Subnetwork Name

---

lib/shared/addon/components/cluster-driver/driver-gke/component.js
lib/shared/addon/components/cluster-driver/driver-gke/template.hbs

======
The field is not actually required. GKE will make up its own if not included.
======
Bugfix
Linked Issues
======
rancher/rancher#32351
======
Fixes a change that hide the cluster and service ranges from auto created subnetworks, when in fact it should only be disabled if a range name for either has been selected OR  a shared subnetwork has been selected.

GKE V2 Remove Required from Subnetwork Name

---

lib/shared/addon/components/cluster-driver/driver-gke/component.js
lib/shared/addon/components/cluster-driver/driver-gke/template.hbs

======
If a user attempts to launch a GKE cluster but the cluster fails to provision (indicated by an error state and empty gke upstream spec) then we want to allow the user to edit the cluster fields they may not normally be able to edit. This only works if we're erroring, transitioning message is error and state is provisioning. 
======
Bugfix
Linked Issues
======
======

[2.5.x] GKE V2 Add logic to handle error never provisioned editing case

---

lib/shared/addon/components/cluster-driver/driver-gke/component.js
lib/shared/addon/components/cluster-driver/driver-gke/template.hbs

======
If a user attempts to launch a GKE cluster but the cluster fails to provision (indicated by an error state and empty gke upstream spec) then we want to allow the user to edit the cluster fields they may not normally be able to edit. This only works if we're erroring, transitioning message is error and state is provisioning. 
======
Bugfix
Linked Issues
======
======
Waiting on https://github.com/rancher/rancher/pull/32308

GKE V2 Add logic to handle error never provisioned editing case

---

app/app.js
app/application/route.js
app/authenticated/controller.js
app/initializers/route-spy.js
app/styles/components/_page-header.scss
lib/global-admin/addon/security/cloud-credentials/index/template.hbs
lib/nodes/addon/node-templates/template.hbs

This PR adds hooks into the Ember UI to enable it to be embedded into the Dashboard UI.
When embedded:
- Adds a class to the page to hide the header and footer
- Listens to route events and sends messages to the outer app
- Sends loading events during page load
- Adds a class 'hide-when-embedded' that can then be used to hide elements that should be hidden when embedded (e.g. certain buttons)
- Adds support for ensuring the theme is set the same as the outer UI

Add support for Embedding in the Dashboard UI

---

lib/shared/addon/components/cluster-driver/driver-oracleoke/component.js
lib/shared/addon/components/cluster-driver/driver-oracleoke/template.hbs
translations/en-us.yaml

======
This PR adds support for opting for a private control-plane and setting custom pod and service CIDRs and node subnet names when configuring the custom VPC/VCN settings.  
The OKE kontainer cluster driver itself is backwards compatible if these new parameters are not specified.
======
New feature.
Linked Issues
======
**Depends on:**
- https://github.com/rancher/rancher/pull/32658
Other tracking issue:
- https://github.com/rancher-plugins/kontainer-engine-driver-oke/issues/26
- https://github.com/rancher-plugins/kontainer-engine-driver-oke/issues/30
======
**OKE cluster driver allowing for setting custom CIDRs and a private control plane. Note warning if a private control plane is selected:**
**OKE cluster driver asking for user to …

Add support for private control-plane and speicying network params

---

lib/shared/addon/components/cluster-driver/driver-gke/component.js
lib/shared/addon/components/cluster-driver/driver-gke/template.hbs
lib/shared/addon/components/gke-node-pool-row/component.js
lib/shared/addon/components/gke-node-pool-row/template.hbs
translations/en-us.yaml

======
This exposes Zones on a regional cluster type. This also adds a small label below each initial node count in each node pool that displays how many nodes in all zones for that node pool like GKE does. There is some weirdness here though, when we send off a regional cluster without any additional zones I believe it defaults to initialNodeCount in each zone available for this cluster.
======
New Feature
Linked Issues
======
rancher/rancher#32345
======

[2.5.x] GKE V2 Expose zones for a regional cluster

---

lib/shared/addon/components/cluster-driver/driver-gke/component.js
lib/shared/addon/components/cluster-driver/driver-gke/template.hbs
lib/shared/addon/components/gke-node-pool-row/component.js
lib/shared/addon/components/gke-node-pool-row/template.hbs
translations/en-us.yaml

======
This exposes Zones on a regional cluster type. This also adds a small label below each initial node count in each node pool that displays how many nodes in all zones for that node pool like GKE does. There is some weirdness here though, when we send off a regional cluster without any additional zones I believe it defaults to initialNodeCount in each zone available for this cluster.
======
New Feature
Linked Issues
======
rancher/rancher#32345
======

GKE V2 Expose zones for a regional cluster

---

app/application/controller.js
app/application/template.hbs
app/initializers/route-spy.js

This PR:
- Hides the fixed customizable banners, since they are already present in the Vue UI when embedded
- Adds the ability for the Vue UI to inform the Ember UI of the primary color and primary text color - we will then inject minimal stylesheet overrides to use this color in a couple of places. This is enough to reflect the primary color as set in the Vue UI. This means that when the SUSE theme is set, the buttons in the embedded UI and the dropdowns will also use green.

Minor improvements when embedded

---

lib/shared/addon/components/cluster-driver/driver-oracleoke/component.js
lib/shared/addon/components/cluster-driver/driver-oracleoke/template.hbs

======
This PR builds on this [previous PR](https://github.com/rancher/ui/pull/4249) by adding a helper to detect when _any_ flexible shape is selected so that the user can specify the number of oCPUs. 
Previously, only the `VM.Standard.E3.Flex` shape was detected (missing new shapes like `VM.Standard.E4.Flex`, `VM.Standard.A1.Flex` and shapes to come). 
======
Bugfix.
Linked Issues
======
**Relates to:**
- https://github.com/rancher/ui/pull/4249
======
[Back-port](https://github.com/rancher/ui/pull/4638) to 2.5 release.

Add helper to detect when any flexible shape is selected.

---

lib/global-admin/addon/components/feature-flags/component.js

The user is not allowed to turn it off in 2.6, but it still exists as a flag for internal use because of how downstream clusters are provisioned.

Hide fleet feature flag

---

lib/shared/addon/scope/service.js

A small fix when embedded - the help lints for fleet went straight to dashboard, resulting in the dashboard UI being embedded in itself.
This PR updates the link only when embedded to use the different route which is is then captured to ensure that the dashboard does the appropriate route navigation rather than embedding itself.
Now uses the same pattern as `dashboardLink` in the code below.

Fix fleet link when embedded

---

lib/monitoring/addon/components/cluster-dashboard/component.js
lib/monitoring/addon/components/cluster-dashboard/template.hbs

This PR addresses https://github.com/rancher/dashboard/issues/3218
When monitoring is installed but not ready we show the events tab - this should not be shown when embedded.

Don't show events tab when embedded

---

lib/shared/addon/components/cluster-driver/driver-oracleoke/component.js
lib/shared/addon/components/cluster-driver/driver-oracleoke/template.hbs
translations/en-us.yaml

======
Adds support for creating an OKE cluster where the Kubernetes secrets are encrypted at rest in etcd using the private kms vault master key.  
======
New feature which adds functionality.  Supports adding this key from the UI.
Linked Issues
======
Related Issue
https://github.com/rancher-plugins/kontainer-engine-driver-oke/issues/32
Related PR's
https://github.com/rancher-plugins/kontainer-engine-driver-oke/pull/41
https://github.com/rancher/rancher/pull/33138
======

Add support for KMS key encryption during cluster creation

---

lib/istio/addon/components/modal-delete-istio/component.js

After disabling istio, the page reloads itself - when embedded, this causes problems.
This fix will post a message to the outer UI (dashboard) when embedded, so it can properly reload the embedded frame - otherwise we get dashboard embedded in dashboard

Fix reload issue when embedding istio configuration

---

translations/vi-vn.yaml

Vietnamese Language should be written in
Tiếng Việt (vi-vn)
Tiếng Anh (vi-vn) means English

fix languageName of Vietnamese

---

lib/shared/addon/components/cluster-driver/driver-googlegke/component.js

 Making gkev1 use the region parameter instead of the zone parameter when availavble

---

lib/shared/addon/components/cluster-driver/driver-googlegke/component.js

Region is set by default so it was getting chosen over zone even when zone was set.
https://github.com/rancher/rancher/issues/33527#issuecomment-878476927

Now just choose region/zone based on location type instead of preferring region over zone

---

lib/shared/addon/components/cluster-driver/driver-linodelke/component.js

======
This change sets the default config option `kubernetesVersion` to the latest supported LKE version. Previously, the default value was hardcoded as `1.18` (which is no longer supported and throws a `400 bad request`).
Since this state is only updated when the drop down selection is changed, if the user were to keep the drop down as-is with the latest version displayed and continue on with cluster creation, the driver would erroneously attempt to create a `1.18` cluster.
======
Bugfix
Linked Issues
======
======

default to latest LKE version

---

lib/shared/addon/components/cluster-driver/driver-eks/component.js
lib/shared/addon/components/form-auth-cloud-credential/component.js
lib/shared/addon/components/form-auth-cloud-credential/template.hbs
translations/en-us.yaml

https://github.com/rancherlabs/rancher-security/issues/820
Disable Next if a credential isn't selected:
Show an error message and don't proceed past step 1 if there was an error pertaining to credentials (would happen if the user had access to a credential which didn't have access to the cluster):

Preventing users from editing an eks cluster when the cloud credential is inaccessible

---

lib/global-admin/addon/components/cloud-credential-azure/component.js
lib/global-admin/addon/components/cloud-credential-azure/template.hbs
lib/shared/addon/components/cluster-driver/driver-aks/component.js
lib/shared/addon/utils/amazon.js
translations/en-us.yaml

The backend will look this up so the user does not need to provide it.

Hide tenantId option in Azure cloud creds

---

app/authenticated/route.js
lib/shared/addon/utils/constants.js

If the R_REDIRECTED cookie is not present and you load a standalone page (not iframed), redirect to Dashboard once.  If you load it iframed, set the cookie but don't redirect.  This should get most users into Dashboard once on upgrade from older->2.6+

Redirect to dashboard once if cookie is not present

---

lib/shared/addon/components/cluster-driver/driver-oracleoke/component.js

======
This PR fixes a typo in the private-control-plane option that prevents the value from being properly set on the driver. Note, this feature is not yet exposed on the 2.4 and 2.5 branches. 
======
Bugfix.
Linked Issues
======
======
The backport of this feature to the 2.4 and 2.5 have the typo fix included:
- https://github.com/rancher/ui/pull/4720
- https://github.com/rancher/ui/pull/4719

Fix typo in private control-plane property.

---

lib/nodes/addon/components/driver-oci/component.js
lib/nodes/addon/components/driver-oci/template.hbs
translations/en-us.yaml

======
This PR adds support for specifying the number of CPUs and the amount of memory in the node-template when a flexible shape has been selected. 
======
New feature.
Linked Issues
======
**Depends on:**
- https://github.com/rancher/rancher/pull/33631
- https://github.com/rancher/rancher/pull/33647 (2.5 back-port)
- https://github.com/rancher/rancher/pull/33648 (2.4 back-port)
Other tracking issues:
- https://github.com/rancher-plugins/rancher-machine-driver-oci/issues/7
======
**OCI node-template prompting the user to set the required CPU and memory setting when a flex-shape has been selected in the instance details:**

Add support for setting oCPUs and memory for flex node templates

---

translations/en-us.yaml

Spelling and grammar changes to the `helpBlock` portion of the `Public Access Endpoints` section.

Fix EKS Access Endpoints wording

---

app/styles/components/_tables.scss
lib/shared/addon/components/sortable-table/template.hbs

Fixes broken close icon alignemnt:

Fix close icon alignment in search box

---

lib/shared/addon/components/cluster-driver/driver-gke/component.js

When `Network Policy for Nodes` is selected `Network Policy Config (master only)` is also selected when creating a new cluster
https://github.com/rancher/dashboard/issues/3941#issuecomment-877325656

Improving the default selection behavior for network policy in gkev2

---

lib/shared/addon/components/cluster-driver/driver-aks/component.js

======
This updates the initial kubernetes version from the string '1.19.9' to an actual value in the list of versions.
======
Bugfix for rancher/dashboard#4262 - Kubernetes version defaults to 1.21.2 in Cluster Options and 19.9.9 in Node Pools
Linked Issues
======
rancher/dashboard#4262
======
Backports #4765 into 2.6-fixes

[2.6] Update initial kubernetes version for AKS

---

lib/shared/addon/components/cluster-driver/driver-aks/component.js

======
This updates the initial kubernetes version from the string '1.19.9' to an actual value in the list of versions.
======
Bugfix for rancher/dashboard#4262 - Kubernetes version defaults to 1.21.2 in Cluster Options and 19.9.9 in Node Pools
Linked Issues
======
rancher/dashboard#4262
======

[master] Update initial kubernetes version for AKS

---

lib/shared/addon/components/catalog-index/component.js

Addresses https://github.com/rancher/rancher/issues/35670
When we show the charts, we only show those that have versions. In the category dropdown, however, we were not using this same filter, so the counts in the dropdown can be different to what we show.
This PR applies the same filter.

Ensure we use same catalog filtering in the dropdown

---

lib/monitoring/addon/components/cluster-dashboard/component.js

Addresses [#4734](https://github.com/rancher/dashboard/issues/4734)
This is a trivial fix for this issue - the `componentStatuses` property of the cluster is undefined and we are not expecting that.
Although this PR fixes the problem in this case, we need to understand why we are no longer getting the component statuses metadata.

Don't fail if we don't get component statuses

---

lib/monitoring/addon/components/cluster-dashboard/component.js
lib/monitoring/addon/components/cluster-dashboard/template.hbs

Addresses https://github.com/rancher/dashboard/issues/4734
Hides the component statuses when not available

Hide component statuses when not available

---

lib/shared/addon/components/cluster-driver/driver-gke/component.js
lib/shared/addon/google/service.js

This PR addresses https://github.com/rancher/dashboard/issues/4763 by adding a `label` property to the shared subnet data, which is required in order for the items to display properly in the dropdown.
I didn't get access to a shared VPC, so in order to test this PR, I mocked the data - Colleen provided JSON output for the list of shared subnets and I added the output to `lib/shared/addon/google/service.js`. So during testing I changed to the async method `fetchSharedSubnets` to:
```
async fetchSharedSubnets(cluster, saved = false) {
if (saved) {
return;
}
const config = get(cluster, 'gkeConfig');
const neuConfig = { ...config };
delete neuConfig?.zone;
delete neuConfig?.region;
const neuURL = this.parseRequestData('/meta/gkeSharedSubnets', neuConfig, cluster?.id);
try {
const xhr = await …
```

Shared subnets are shown in dropdown when provisioning GKE clusters

---

app/catalog-tab/launch/route.js
app/models/app.js
lib/shared/addon/catalog/service.js

This PR partly addresses https://github.com/rancher/dashboard/issues/4774 by using the `currentVersion` parameter when requesting template details in the form to upgrade a legacy app.
The currentVersion parameter takes advantage of this fix https://github.com/rancher/rancher/issues/35680 which made it so that the available `versionLinks` are not empty when you try to upgrade a legacy app after upgrading Rancher to a version that is no longer supported by the legacy app.
1. In Rancher v2.6.2, I enabled the legacy feature flag and installed legacy apps in the local `system` project.
2. I upgraded Rancher to v2.6.3-rc5 (because v2.6-head is considered prior to v2.6.0 for version compatibility)
3. I went to the legacy apps in the system project and tried to upgrade them
4. I …

Use currentVersion parameter to upgrade legacy apps

---

lib/shared/addon/components/managed-import-cluster-info/component.js

======
This adds `(experimental)' to labels that fall outside of the k8s supported version range for the in the Kubernetes Version dropdown. At this time of writing, K3S v1.22 and above should be marked as experimental, but this flag was not showing when attempting to edit an imported cluster. 
======
Bugfix
Linked Issues
======
rancher/dashboard#4787
======
I took some time to search for K3S appropriate version ranges, but did not find any associated settings that already existed. There were some potential leads in `lib/shared/addon/release-versions/service.js` and `server/proxies/api.js`, but I didn't see any associated settings being set anywhere.. Opted to stick with the supported k8s versions as a result.

Display "(experimental)" if version is not in supported range

---

app/catalog-tab/launch/route.js

This PR addresses https://github.com/rancher/rancher/issues/35907 by making it so that the UI only tries to use the current app version in the routes for the app install/upgrade form if the app is already installed.
1. I installed Rancher v2.6.3-rc7
2. Enabled the legacy feature flag
3. Deployed a downstream RKE2 cluster
4. Opened Ember by going to `<serverURL>/g/clusters`
5. Clicked the new RKE2 cluster name
6. Clicked **Projects/Namespaces**
7. Clicked **Project: System**
8. Clicked **Launch** and verified that the form rendered successfully
9. Clicked **longhorn** and installed it
10. Changed a value in the **longhorn** upgrade form and it upgraded successfully

Catalog app route only uses current version when necessary

---

lib/global-admin/addon/multi-cluster-apps/catalog/launch/route.js

This PR addresses https://github.com/rancher/dashboard/issues/4774 by making it so that the currentVersion parameter is used when fetching the template details for multi-cluster apps.
The changes are nearly identical to the ones around here https://github.com/rancher/ui/pull/4794 and here https://github.com/rancher/ui/pull/4791 for adding the currentVersion parameter to the legacy app upgrade route. The only difference is that it's in a different file and the app id is taken from `templateVersionId` instead of `externalId`
To test this PR, 
1. I installed Rancher v2.6.2
2. Enabled the legacy feature flag
3. Installed multi-cluster apps
4. Upgraded Rancher to v2.6.3-rc8
5. Upgraded the multi-cluster apps successfully
6. Also verified that the change did not break the ability to install new …

Can upgrade legacy multi-cluster apps

---

translations/en-us.yaml

This PR addresses https://github.com/rancher/dashboard/issues/4894 by changing the label for the maintenance window dropdown in the GKE cluster provisioning form.
1. I created Google cloud credentials
2. Went to cluster manager and opened the form to create a GKE cluster
3. Used the `rancher-qa` project ID and Google cloud credentials to get farther down in the form
4. In the Additional Options section, confirmed that the label for the maintenance window is now **Maintenance Window - UTC**

Clarify that GKE maintenance window time is UTC

---

app/styles/components/_searchable-select.scss
lib/nodes/addon/components/driver-vmwarevsphere/component.js

======
- The content library library templates weren't being requested because the data center wasn't being passed.
- Made searchable select look the same as new select.
- Made it so content library contents didn't get updated when the content library was selected
======
Linked Issues
======
rancher/dashboard#4302

[backport 2.6.3-fixes] Fix vSphere content library creation type and minor visual issues

---

app/styles/components/_searchable-select.scss
lib/nodes/addon/components/driver-vmwarevsphere/component.js

======
- The content library library templates weren't being requested because the data center wasn't being passed.
- Made searchable select look the same as new select.
- Made it so content library contents didn't get updated when the content library was selected
======
Linked Issues
======
rancher/dashboard#4302

Fix vSphere content library creation type and minor visual issues

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js

======
The front end wasn't sending answers to the backend when a user set the the
privateRegistries field when using an RKE template which allowed the field to
be overriden. This was happening because we weren't handling the bracket
notation properly.
======
Linked Issues
======
Front End issue: https://github.com/rancher/dashboard/issues/3940
Back End Issue: https://github.com/rancher/rancher/issues/27166
Before the fix
======
After the fix
======

Fixing how the frontend handles the bracket annotation when building cluster answers

---

lib/shared/addon/components/managed-import-cluster-info/component.js

This PR addresses https://github.com/rancher/dashboard/issues/4543 by making it so that only the latest version (i.e., only one 1.21.x version, and only one 1.22.x version etc) are shown as options when editing K3s clusters.
Nancy already did this PR https://github.com/rancher/dashboard/pull/4154 which limits the versions when editing K3s clusters in the dashboard UI. However, this PR needed to make the same change to Ember. When you edit a K3s cluster, you are shown either the dashboad OR the Ember UI depending on whether the cluster was imported into Rancher or provisioned by Rancher. If you provisioned the K3s cluster in Rancher, you would see the new RKE2/K3s dashboard edit form. However, if you import a K3s cluster into Rancher, you will see the error reported in the above linked …

Only show latest minor K8s version when editing K3s cluster

---

app/components/new-catalog/component.js
app/components/new-catalog/template.hbs

Addresses https://github.com/rancher/dashboard/issues/4803
Only an issue in production.
You can run a production build locally with:
`./node_modules/.bin/ember serve --environment production`
This PR uses the LazyIcon mixin that is used elsewhere.

Fix issue with constantly requested catalog image

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js

Addresses: https://github.com/rancher/dashboard/issues/4870
Previously had fixed one issue - PR: https://github.com/rancher/ui/pull/4799/files
This fixed the reported issue when using an RKE template.
There is also another issue (which was why issue 4870 was re-opened) that occurs when not using an RKE template - we format the value and add a % when saving the form - if the validation fails, we don't undo that, so we end up adding a % to the value in the input box and this keeps getting added with each save.
This PR adds code to remove the % is the form validation fails.

Fix issue where we keep adding a % char to the maxWorkersUnavailable field

---

lib/shared/addon/components/managed-import-cluster-info/component.js
lib/shared/addon/utils/parse-version.js

https://github.com/rancher/dashboard/issues/5257
This issue impacts an Ember page iFramed into the dashboard. There are two parts: fixing the version comparison function and ensuring we use that function to compare versions in the `includeOnlyLatestMinorVersions` filter. The `compare` function wasn't parsing build versions (separated with `+`). Note the difference in the [dashboard code](https://github.com/rancher/dashboard/blob/master/utils/version.js#L14)
The dashboard ticket includes repro steps, but to clarify: 
> To Reproduce
...
>2. Point KDM to dev-v2.6
This will already be correct if your local cluster is a dev version eg you installed v2.6-head. If not, you'll need to change the rke metadata config global setting: 
```
{
"refresh-interval-minutes": "1440",
"url": …
```

fix version sorting util and imported cluster upgrade versions listed

---

app/styles/components/_forms.scss

#5414
Prevented `form` content to overflow in some cases by setting max width, e.g. RKE1 Node Template cloud-config field for Sphere.

Set max-width to the form to avoid overflow of their own components

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js

This PR addresses https://github.com/rancher/dashboard/issues/5032 by making it so that if you create a cluster from an RKE template and override some values, the next time you edit the form, your own values are used as the defaults instead of the defaults for provisioning a new cluster.
To test this PR:
1. I created an RKE template and set the 'Node Port Range' to `30000-32767`. Set 'Allow user override' for the Node Port Range.
2. Created an RKE1 cluster from the RKE template. Overrode the value for node port range and set it to `30000-31000`.
3. In cluster manager, went to the new cluster and clicked **Edit Config.**
4. Confirmed that my override value - `30000-31000` - was shown as the default instead of the default value from the RKE template.
Related issue: …

Use existing cluster config as defaults for RKE template clusters

---

lib/shared/addon/components/cru-node-pools/component.js
lib/shared/addon/components/form-members/component.js

======
This PR updates the cluster edit/create node pool and member components to re-initialize pools and members respectively when the cluster changes. This bug appears in the iFramed UI running in the dashboard, but not in the Ember UI running in standalone. It seems that when using the dashboard to navigate between editing RKE1 clusters, the embedded Ember UI navigates directly between the two clusters' edit views, so any relevant components' `init` function isn't re-run, and consequently the node pools and cluster members displayed aren't updated to reflect the new cluster.
Linked Issues
======
https://github.com/rancher/dashboard/issues/5343 - in addition to this problem with cluster members, you can see that the node pools section also shows the previous RKE1 …

reinitialize node pools and members when cluster changes

---

translations/de-de.yaml

======
Correct german spelling for certificates:
certificates = Zertifikate (like certificate = Zertifikat)
======

Fix german translation for certificates

---

lib/shared/addon/utils/amazon.js

======
Add EKS 1.22, Remove unsupported EKS 1.18
See https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html
Cluster provisioning screen
Provisioned cluster
======
Linked Issues
======
https://github.com/rancher/dashboard/issues/5716

Add EKS 1.22, Remove EKS 1.18

---

translations/en-us.yaml

Addresses Github issue: [#5745](https://github.com/rancher/dashboard/issues/5745)
Addresses Zube issue: [#5774](https://zube.io/rancher/dashboard-ui/c/5774)
- Change label in Project monitoring page from `Project Monitoring Configuration` to `V1 Project Monitoring Configuration`
**Preview**

Change label in Project monitoring page

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/cru-cluster-template/component.js
lib/shared/addon/utils/constants.js

backport of: https://github.com/rancher/ui/pull/4826

[2.5.14]: Backport: Apply weave network config when using an RKE template

---

lib/nodes/addon/components/driver-vmwarevsphere/component.js

- The content library library templates weren't being requested because the data center wasn't being passed.
- Made it so content library contents didn't get updated when the content library was selected
fixes rancher/dashboard#5978
backport of https://github.com/rancher/ui/pull/4805

[backport] Fix vSphere content library creation type and minor visual issues

---

lib/shared/addon/components/form-engine-opts/template.hbs
translations/en-us.yaml

This PR addresses https://github.com/rancher/dashboard/issues/5821 by adding new fields for RKE1 node templates. It adds new inputs to add key-value pairs for log options (`logOpt`) and storage options (`storageOpt`).
There are only a few changes made because the engine options are reused across multiple node templates for different cloud providers.
1. I created Digital Ocean cloud credentials
2. From cluster management, went to **RKE1 Node Configuration > Node Templates**
3. Started to create a Digital Ocean node template
4. Confirmed that the Log Options and Storage Options are available
5. Confirmed that when you expand them, you can enter key-value pairs
9. Confirmed that the values are sent in the POST request when the node template is saved

Add Storage Options and Log Options fields to RKE1 node template

---

lib/shared/addon/components/cru-node-pools/component.js
lib/shared/addon/components/cru-node-pools/template.hbs
translations/en-us.yaml

Addresses https://github.com/rancher/dashboard/issues/4465
Addresses https://github.com/rancher/dashboard/issues/4444
There are issues if you create a cluster with node pools where the name prefix used for the node pools is non-unique.
This PR adds validation to prevent the user doing this and also displays a banner as the edit the from to indicate that this is not allowed.

Prevent creation of clusters with node pools with non-unique names

---

app/styles/components/_forms.scss
lib/shared/addon/components/cluster-driver/driver-amazoneks/template.hbs
lib/shared/addon/components/cluster-driver/driver-eks/template.hbs

Addresses https://github.com/rancher/dashboard/issues/6272
Straight-forward PR.
Ensures that the radio buttons stay vertically-stacked when browser window is wide.

Fix eks radio button layout

---

lib/shared/addon/azure-ad/service.js

[#6316](https://github.com/rancher/dashboard/issues/6316) - As part of the endpoint migration process @maxsokolovsky found that the UI has been using a redirect url with a duplicated query parameter, which ultimately causes an error. 
This PR resolves the issue by only adding query params that are not already present in the url obtained from the backend (via an `authProvider` resource). I've opted to implement this in a way that only affects azure ad auth to negate the need to re-test other areas of the UI.

do not add duplicate query params to oauth redirects

---

lib/global-admin/addon/clusters/index/controller.js
lib/global-admin/addon/clusters/index/template.hbs
lib/shared/addon/components/form-network-config/template.hbs
translations/en-us.yaml

Adding windows deprecated banners for rke1 on the clusters and provisioning pages

---

lib/shared/addon/growl/service.js

https://github.com/rancher/dashboard/issues/6460
I had a hard time reliably producing websocket error growls in the embedded ember ui and ended up uncommenting code [here](https://github.com/rancher/ui/blob/master/lib/shared/addon/mixins/subscribe.js#L292) to test.

Disable growls when embedded

---

lib/shared/addon/components/cluster-driver/driver-aks/component.js
lib/shared/addon/version-choices/service.js

Marking aks k8s versions >= 1.24.0 as experimental

---

lib/nodes/addon/components/driver-harvester/template.hbs

======
According to discussion of Harvester team, it's not applicable to display Pod Scheduling on harvester cluster config page.
======
Linked Issues
======
- https://github.com/harvester/harvester/issues/2642
======

Harvester: Remove Pod Scheduling from harvester RKE1

---

lib/monitoring/addon/components/cluster-dashboard/template.hbs
lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
lib/shared/addon/components/modal-show-command/template.hbs

This PR addresses https://github.com/rancher/dashboard/issues/6549 by adding RKE1 Windows deprecation warnings in more places.
To test,
1. In the Ember global view, go to add a cluster. Under **Create a new Kubernetes cluster,** click **Existing nodes.**
2. Enter a cluster name, set the network provider to Flannel, enable Windows support
5. Click Next
6. Confirm that the Windows deprecation warning is displayed:
7. Click Done without running the registration command
8. Go to the detail page of the new Windows enabled cluster and confirm that the warning is shown there as well:
9. Click Get Registration Command
10. Confirm that the warning is also displayed on the modal that appears (this one was not specifically requested in the linked issue, but it's in the same spirit):
12. Confirm that …

Add more deprecation warnings for Windows with RKE1

---

lib/shared/addon/components/node-group-row/template.hbs

Issue: 
https://github.com/rancher/rancher/issues/38698
https://github.com/rancher/dashboard/issues/6731
We are updating the AWS SDK to [version 1.44](https://github.com/aws/aws-sdk-go/releases/tag/v1.44.83) and with that, comes the ability to scale a node group in an EKS cluster to 0 nodes. The rancher ui won't allow you to set a 0 value for `desiredSize` and `minSize` in the node group config so this change updates the ui to allow that.

Update eks node group asg desired and minsize to 0

---

app/models/cluster.js

Fixes https://github.com/rancher/dashboard/issues/6769
======
This changes the default image type for gke nodes to `Container-Optimized OS with Containerd`
The image options can be located [here](https://github.com/rancher/ui/blob/be0c5d60c0941ad8e6b5a8dcbbcc357ab2fb7f51/lib/shared/addon/google/service.js#L58-L83).

Update default image for gke nodes

---

app/styles/components/_forms.scss
lib/nodes/addon/components/driver-digitalocean/component.js

Addresses: https://github.com/rancher/dashboard/issues/6774
This PR:
- Adds Ubuntu 22.04 support for Digital Ocean
- Fixes a styling issue: on Linux, disabled options in the default OS select drop down can not be distinguished from normal ones.

[2.6.9] Add support for Ubuntu 22.04 on Digital Ocean

---

.drone.yml
README.md
config/environment.js
package.json
scripts/build-static
scripts/ci

- This used this commit as a basis - https://github.com/rancher/ui/commit/9b6c4e6258fd7054a8e92abcfdc53f384ab735cf
- Most of the work already existed, added the changes to config/environment.js as well
- Otherwise it's udpates to branch names (have aligned this with dashboard's)

Updated build process to work from the new `release-2.6.9` branch

---

.drone.yml

- Last 2.7.0 RC tag failed to trigger build (https://drone-publish.rancher.io/rancher/ui/2594)
- This was due to references to v2.6 in their triggers
- I've updated these now to v.2.7 (these could probably be just `v*`, but we'll stick to a safer fix)

Drone builds were restricted to 2.6, update to match 2.7

---

translations/en-us.yaml

This PR addresses the Ember part of https://github.com/rancher/dashboard/issues/6918
Before: 
After:
Updated private registry description in edit config form for RKE1 clusters
When creating or editing an RKE1 cluster, confirm that the language has been updated

Change language around private registry in RKE1 cluster config form

---

lib/shared/addon/utils/amazon.js

Partly adresses https://github.com/rancher/dashboard/issues/7203
Before:
After:

Remove K8s 1.22 and older from EKS creation form

---

app/apps-tab/index/template.hbs
app/authenticated/cluster/cluster-catalogs/template.hbs
app/authenticated/project/project-catalogs/template.hbs
lib/global-admin/addon/catalog/template.hbs
lib/global-admin/addon/global-dns/entries/index/template.hbs
lib/global-admin/addon/global-dns/providers/index/template.hbs
translations/en-us.yaml

Addresses https://github.com/rancher/dashboard/issues/7210
Adds deprecation banners for features being deprecated in 2.7.
Deprecates:
- Global DNS Providers
- Global DNS Entries
- Catalogs (global, cluster and project)
- Apps (project)
- Adds an info banner on the Apps page about migrating Longhorn
Example banner:
Apps banner with Longhorn banner:

Add banners for 2.7 v1 deprecations

---

lib/shared/addon/components/cluster-driver/driver-aks/component.js

Addresses https://github.com/rancher/dashboard/issues/7217
Before: 
After:

Change AKS experimental label to apply to K8s 1.25+

---

lib/shared/addon/components/cluster-driver/driver-aks/component.js
lib/shared/addon/components/cluster-driver/driver-gke/component.js
lib/shared/addon/version-choices/service.js

This PR addresses https://github.com/rancher/dashboard/issues/7203 by setting a minimum value, 1.23, for AKS and GKE cluster provisioning.
K8s options for AKS are now these:
K8s options for GKE are now these:

Set 1.23 as minimum version for GKE and AKS

---

app/instance-initializers/nav.js

Addresses https://github.com/rancher/dashboard/issues/6874
Updates the nav to hide the v1 tools that have been removed in 2.7

Remove v1 tools from nav

---

lib/shared/addon/version-choices/service.js

This PR fixes https://github.com/rancher/dashboard/issues/7276 by changing the logic for hiding unsupported GKE and AKS versions.
Previously, K8s versions 1.22 and below were always hidden. This change creates an exception for the edit form if the AKS or GKE cluster is already 1.22, in which case it shows the current version as the default.

Current GKE/AKS version is shown even if below min version

---

lib/shared/addon/components/gke-node-pool-row/template.hbs

Fixes https://github.com/rancher/dashboard/issues/3774
It seems that the `box` CSS class was adding colors to the form inputs that makes them look disabled. I removed this class, so now this section looks like the rest of the form.
Before:
After:

GKE inputs no longer look disabled

---

app/components/container/new-edit/template.hbs
lib/shared/addon/components/form-name-description/component.js
lib/shared/addon/components/form-name-description/template.hbs
translations/en-us.yaml

Addresses https://github.com/rancher/dashboard/issues/4861
Adds an optional check to the name/description input control that can check for underscores in name. Wires this in only for deployments.
Message is displayed below input box - this does cause other controls to move, but this is okay given the ember UI is deprecated.

Deployments: Check name for underscores

---

Dockerfile.dapper

The drone pr test runs are failing with the error:  `Unable to correct problems, you have held broken packages.`
I poked around a bit and it seems we're using a version of Debian that hasn't been supported since June (and an outdated node version). Updating the debian version caused another error with the  `update-alternatives` command, but I couldn't work out why it was there in the first place and removing that command altogether doesn't appear to break anything. Just to be sure, I altered the CI script to build the ui from this PR (then reverted that change).

update debian version in ci

---

lib/nodes/addon/components/driver-azure/component.js
lib/nodes/addon/components/driver-azure/template.hbs
translations/en-us.yaml

https://github.com/rancher/dashboard/issues/7164
This PR adds the "Azure Tags" button for RKE1 Azure node templates:

Can add Azure tags to RKE1 node template

---

lib/shared/addon/utils/azure-choices.js

This PR partly addresses https://github.com/rancher/dashboard/issues/7177 by adding StandardSSD to Azure storage options.
1. Went to Cluster Management > RKE1 Configuration > Node Templates
2. Clicked Add Template
3. Clicked Azure
4. Went to the Instance section
5. Went to the Storage Type dropdown menu
6. Selected Standard SSD LRS, the new storage option
8. Added a name for the node template
9. Clicked Create
10. Created an RKE1 Kubernetes cluster in Azure using the new node template
11. Confirm that `StandardSSD_LRS` is sent in the network request

Add StandardSSD as a storage option for Azure cluster provisioning

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js
translations/en-us.yaml

Addresses https://github.com/rancher/dashboard/issues/7235
- Renames FQDN to Endpoint.
- Accepts port number and validates

Allow Authorization endpoint FQDN to accept port

---

app/components/modal-view-template-diff/component.js
app/components/modal-view-template-diff/template.hbs
app/styles/components/_modals.scss
lib/global-admin/addon/cluster-templates/index/controller.js
lib/global-admin/addon/cluster-templates/index/template.hbs
lib/shared/addon/components/cluster-templates-table/component.js
lib/shared/addon/components/cluster-templates-table/template.hbs
lib/shared/addon/components/sortable-table/component.js
translations/en-us.yaml

Addresses https://github.com/rancher/dashboard/issues/5954
Select two RKE revisions and a new 'Compare' button will be enabled - clicking this brings up a modal dialog showing the diff between the two template revisions.
(note ember images shown - these pages also appear embedded in the vue UI)
This PR:
- Adds a selectionChanged to sortable table and the cluster revisions table
- Wires this in to the cluster revisions view and adds a compare button (enabled when 2 revisions selected)
- Shows diff in a modal

Add ability to compare RKE template revisions

---

lib/shared/addon/utils/amazon.js

Fixes [#7219](https://github.com/rancher/dashboard/issues/7219)
edit: because we keep having to do this, tech debt issue to look for a better way is here: https://github.com/rancher/dashboard/issues/7295

add 1.24 to hardcoded EKS versions

---

.drone.yml
README.md
package.json
scripts/build-static
scripts/ci

- Follows same process as https://github.com/rancher/ui/pull/4896

Updated build process to work from the new `release-2.6` branch

---

app/authenticated/cluster/route.js
app/authenticated/route.js
lib/shared/addon/cis-helpers/service.js

This PR fixes three bugs:
https://github.com/rancher/dashboard/issues/7699
To test, I went to create an RKE1 custom cluster and confirmed that the RKE1 custom cluster creation form appears instead of the old Ember cluster list view.
https://github.com/rancher/dashboard/issues/7688
To test, I created an RKE1 cluster, went to Edit Config, and confirmed that the cluster edit form appears instead of the old Ember cluster list view.
https://github.com/rancher/dashboard/issues/7636
To test, I went to create all types of RKE1 node driver clusters, including vSphere, and confirmed that the correct form appears instead of the old Ember cluster list view.

RKE1 cluster create/edit forms no longer throw 404s

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js

Addresses https://github.com/rancher/dashboard/issues/6582
When editing as Yaml, an empty `fromValue` key gets added which causes problems - this PR goes through the agent env vars before save and removes `fromValue` from each var if it is empty.

Fix issue editing cluster with agent env vars

---

lib/nodes/addon/components/driver-azure/template.hbs
translations/en-us.yaml

Addresses https://github.com/rancher/dashboard/issues/7743
The StandardSSD_LRS storage option requires managed disks to work. So if StandardSSD_LRS is selected, and managed disks are not selected, there should now be an error message:
If managed disks are enabled, the error message disappears:
This change applies to Azure RKE1 node templates. I'll be creating a similar PR for RKE2

If Azure storage type StandardSSD_LRS is selected, show managed disks warning

---

lib/nodes/addon/components/driver-azure/component.js
lib/nodes/addon/components/driver-azure/template.hbs
lib/shared/addon/components/sortable-table/component.js
translations/en-us.yaml

Addresses https://github.com/rancher/dashboard/issues/7753 and https://github.com/rancher/dashboard/issues/7752
This PR is functionally the same as https://github.com/rancher/dashboard/pull/7687, but for RKE1 node templates.
- Can select an availability zone.
- Can enable accelerated networking.
- The VM size dropdown is grouped so that you can see which VMs support accelerated networking and which do not.
- VMs are refetched when the region changes because different sizes are available per region.
- Warn the user when the selected VM size is not in the selected region.
- Warn the user if they have selected availability zones, but that is not supported for the region or VM size.
- For example, South Africa North has availability zones for some sizes but not others. So `Standard_A2_v2` in …

RKE1 Azure node templates have accelerated networking and availability zones

---

lib/nodes/addon/components/driver-harvester/component.js

======
The network created by harvester storage-network should be excluded on harvester node driver page(RKE1)
======
Linked Issues
======
- https://github.com/harvester/harvester/issues/3163
======

HARVESTER: exclude the network created by storage-network

---

lib/login/addon/login/controller.js
lib/login/addon/login/route.js
lib/login/addon/login/template.hbs

Addresses https://github.com/rancher/dashboard/issues/7293
For a production deployment, redirect `/login` to `/dashboard`.
This PR ensures that the Ember UI's login page is not shown when redirecting.
See Issue above - some users bookmark the old login page, so we want to redirect them to the new dashboard UI.

Redirect /login to /dashboard

---

app/models/kontainerdriver.js
app/models/nodedriver.js
lib/nodes/addon/custom-drivers/cluster-drivers/controller.js
lib/nodes/addon/custom-drivers/cluster-drivers/template.hbs
lib/nodes/addon/custom-drivers/node-drivers/controller.js
lib/nodes/addon/custom-drivers/node-drivers/template.hbs
lib/shared/addon/components/modal-confirm-deactivate/component.js
lib/shared/addon/components/modal-confirm-deactivate/template.hbs

Addresses https://github.com/rancher/dashboard/issues/7762
The 'deactivate' dialog and the way it is wired into the drivers does not support multiple resources - we dispatch the confirmation dialog for each resource individually, so if you have 2 drivers selected, we dispatch twice - the 2nd time closes the dialog from the first. Thus, if you select 3 drivers, you will see the confirmation, but only that 3rd driver will be deactivated if you proceed. 
This PR updates the dialog to show multiple driver names and to deactivate multiple when invoked as such.
It then updates the two driver lists to override the bulk action handler so that we can open the dialog once and pass it multiple items. This is a pattern already used elsewhere in the code.
Finally, I corrected a typo in the action …

Fix confirmation dialog for multiple deactivation

---

lib/shared/addon/components/cluster-driver/driver-eks/component.js
lib/shared/addon/components/node-group-row/template.hbs

Fixes [#7755](https://github.com/rancher/dashboard/issues/7755) [#7756](https://github.com/rancher/dashboard/issues/7756) [#7754](https://github.com/rancher/dashboard/issues/7754)
The nodeRole field should use the Arn value, see comment [here](https://github.com/rancher/dashboard/issues/7754#issuecomment-1355822573). Additionally, aws role data may be paginated...afaict the `IsTruncated`/`Marker` pattern is used across this version of the aws sdk so making this change to the more general `describeResource` function seems safe. 
In addition to depaginating data when relevant, I've increased the max number of items that may be returned to the maximum allowed, 1000, which lets us fetch all our roles in one request; the easiest way to test the depagination code is probably to change MaxItems …

Eks custom node role

---

lib/shared/addon/components/cluster-driver/driver-import-aks/component.js

Addresses https://github.com/rancher/dashboard/issues/7781
This PR fixes the above issue.
Simple fix - we are calling the callback with no parameters in the success case, where the callback is expecting a first argument to indicate success - thus undefined is passed in which is treated as an error. The 2nd error argument is also not specified, so we end up pushing `undefined` to the list of errors which results in the empty banner.

Fix imported AKS empty banner

---

lib/nodes/addon/components/driver-azure/component.js

This PR addresses the RKE1 portion of https://github.com/rancher/dashboard/issues/7878
The VMs that support AN now appear first in the dropdown:

Show VMs that support AN first

---

lib/nodes/addon/components/driver-azure/component.js

This PR addresses the RKE1 part of this issue https://github.com/rancher/dashboard/issues/7877
The Azure availability zones should always be in order now:

Availability zones are sorted

---

lib/nodes/addon/components/driver-azure/component.js
lib/nodes/addon/components/driver-azure/template.hbs

This PR addresses a comment with QA feedback requesting that the AZ dropdown be disabled if empty. https://github.com/rancher/dashboard/issues/7753#issuecomment-1376002025
Before:
After:

Dropdown menu for AZs is grayed out if empty

---

app/models/cluster.js
lib/shared/addon/mixins/new-or-edit.js

Addresses https://github.com/rancher/dashboard/issues/7631
This PR fixes the above issue.
We are not sending the labels or annotations for hosted providers.
This PR adds an extra arg to the save method, so that we can determine if the labels or annotations have changed, and only send those it they have.
Tested with an Azure AKS cluster.

Fix labels not being saved on hosted providers

---

app/authenticated/cluster/edit/route.js
lib/global-admin/addon/cluster-templates/detail/route.js
lib/global-admin/addon/cluster-templates/detail/template.hbs
lib/global-admin/addon/cluster-templates/new-revision/route.js
lib/global-admin/addon/cluster-templates/new-revision/template.hbs
lib/global-admin/addon/cluster-templates/new/route.js
lib/global-admin/addon/cluster-templates/new/template.hbs
lib/global-admin/addon/clusters/new/launch/route.js
lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
lib/shared/addon/components/cru-cluster-template/template.hbs
lib/shared/addon/utils/constants.js
translations/en-us.yaml

https://github.com/rancher/dashboard/issues/7575
This PR adds PSA support during RKE1 configuration. This is only available for  kubernetes versions >=1.23.0. Users creating clusters with versions <1.25 should have the same experience as before, with the addition of a banner informing them that psp support will be disabled in later versions. 
* no psp options and a banner explaining why
* psa dropdown with a default of 'privileged'
* field being set is `rancherKubernetesEngineConfig.services.kubeApi.podSecurityConfiguration`
* if psp support is enabled, there should be a banner warning to disable it and an error on attempting to create
* if there are psp resources within the cluster (one or more projects with a psp set) there should be a banner asking the user to delete these psp …

RKE1 pod security admission support

---

lib/shared/addon/azure-ad/service.js

Fixes https://github.com/rancher/dashboard/issues/7330
Forwardport of https://github.com/rancher/ui/pull/4875
This bug can be reproduced by enabling then logging in via azuread auth. If you look at the redirect url the UI is using, you'll see there is a duplicated query param: apparently the microsoft graph api we've switched to does not like this and throws an error.

[2.6 forwardport]fix oauth redirect param duplicates

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
translations/en-us.yaml

[#7575](https://github.com/rancher/dashboard/issues/7575)
* add default (empty) option
* set the correct field, `spec.defaultPodSecurityAdmissionConfigurationTemplateName` (`default_pod_security_admission_configuration_template_name` in yaml)
* remove unused `kubeApiPSAC` computed prop

Psa rke1 fixes

---

.drone.yml

This bumps `rancher/dapper` to v0.6.0. 
There is a potential bug between drone and the `rancher/dapper` version that might be causing CI to fail. It is recommended to bump the version number and test builds again.
https://drone-publish.rancher.io/rancher/ui/2688/1/1
Signed-off-by: Phillip Rak <rak.phillip@gmail.com>
======
======
Linked Issues
======
======

Bump `rancher/dapper` to v0.6.0

---

.drone.yml

This bumps `rancher/dapper` to v0.6.0. 
There is a potential bug between drone and the `rancher/dapper` version that might be causing CI to fail. It is recommended to bump the version number and test builds again.
https://drone-publish.rancher.io/rancher/ui/2688/1/1
backports #4957
Signed-off-by: Phillip Rak <rak.phillip@gmail.com>
======
======
Linked Issues
======
======

Backport: Bump `rancher/dapper` to v0.6.0

---

lib/shared/addon/components/node-group-row/component.js
lib/shared/addon/components/node-group-row/template.hbs

https://github.com/rancher/dashboard/issues/4568#issuecomment-1381051958
`input-or-display` referenced a nonexistent value (`nodeRole` vs `model.nodeRole` in the select) - I've also added a computed prop to get a better display value (`<role>.Arn` is not very human-readable)

display node role name on eks edit/view

---

app/authenticated/controller.js
app/authenticated/template.hbs
app/styles/layout/_layout.scss
translations/en-us.yaml

https://github.com/rancher/dashboard/issues/7330#issuecomment-1424855747
This PR adds a warning banner when azure ad is enabled with the old (soon to be deprecated) endpoint configuration, taken from this 2.5 PR: https://github.com/rancher/ui/pull/4873/files The changes to ember azure ad auth configuration are not included here; it needs to be configured through the dash in 2.6.11

[2.6] azuread migration warning

---

lib/shared/addon/utils/amazon.js

[#7931](https://zube.io/rancher/dashboard-ui/c/7978)
Fixed - [Backport 2.6.x] - ensure all EKS versions are in 2.6.x branches

Backport all EKS versions are in 2.6.x

---

lib/shared/addon/components/cluster-driver/driver-linodelke/component.js

This pull request alters the Linode LKE node pool type filtering logic to only include valid instance types. Previously the filter would allow certain invalid types and exclude valid types (`highmem`).
See: https://www.linode.com/docs/api/linode-types/#type-view__responses
Related issue: https://github.com/rancher/dashboard/issues/6424

fix: Only display valid Linode types for LKE node pools

---

README.md

======
The current example project for custom docker-machine driver was deprecated years ago. This PR updates the link to https://github.com/rancher/ui-driver-skel which is the current sample project.

Update custom driver skeleton project URL

---

lib/nodes/addon/components/driver-azure/component.js
lib/nodes/addon/components/driver-azure/template.hbs
translations/en-us.yaml

For is for the rke1 side of this issue; rancher/dashboard will have a similar PR https://github.com/rancher/dashboard/issues/8014
* add checkbox for `enablePublicIpStandardSku`
* when az is selected, automatically set standard sku, public ip, and managed disk options to the values required when availability zones are used, and disable those form controls
* fix a bug where an availability zone appears to be selected when the dropdown options initialize, but is not actually set in the config

Add standard SKU checkbox and required defaults for azure availability zones

---

app/models/cluster.js

Fixes https://github.com/rancher/dashboard/issues/6769
======
This changes the default image type for gke nodes to `Container-Optimized OS with Containerd`
The image options can be located [here](https://github.com/rancher/ui/blob/be0c5d60c0941ad8e6b5a8dcbbcc357ab2fb7f51/lib/shared/addon/google/service.js#L58-L83).
backports #4891
references rancher/dashboard#8183

BACKPORT: Update default image for gke nodes

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
translations/en-us.yaml

Fixes https://github.com/rancher/dashboard/issues/8174
This PR moves the psp deprecation/removal banner closer to the psp/psa inputs and changes the text for versions >= 1.25
<1.25 with or without psp support enabled:
\>=1.25 without psp support previously enabled:
Upgrading to >=1.25 with psp support previously enabled:

update rke1 psp banner

---

lib/shared/addon/components/cluster-driver/driver-linodelke/component.js
lib/shared/addon/components/cluster-driver/driver-linodelke/template.hbs
translations/en-us.yaml

======
This pull request adds an option to the LKE UI component for provisioning and updating Linode Kubernetes Engine clusters with [High Availability Control Planes](https://www.linode.com/docs/guides/introduction-to-high-availability/).
======
- New Feature
Linked Issues
======
Feature Request: https://github.com/rancher/rancher/issues/38189
======
- There is currently a bug in `kontainer-engine-driver-lke` when updating **only** the `High Availability` field
- https://github.com/linode/kontainer-engine-driver-lke/pull/19

Add High Availability LKE cluster support

---

translations/en-us.yaml

https://github.com/rancher/dashboard/issues/8225
This PR renames the pod security policy page to more accurately reflect the relevant resource name.

rename pod security policies to pod security policy templates

---

lib/shared/addon/components/cluster-driver/driver-import/component.js
lib/shared/addon/components/cluster-driver/driver-import/template.hbs
lib/shared/addon/components/modal-confirm-imported-upgrade/component.js
lib/shared/addon/components/modal-confirm-imported-upgrade/template.hbs
lib/shared/app/components/modal-confirm-imported-upgrade/component.js
translations/en-us.yaml

https://github.com/rancher/dashboard/issues/8126
https://github.com/rancher/dashboard/issues/8124

Add warning modal when upgrading imported k3s or rke2 clusters from <1.25.x to >=1.25.x

---

lib/shared/addon/components/form-members/component.js
lib/shared/addon/components/form-members/template.hbs

Addresses https://github.com/rancher/dashboard/issues/8266
This improves the check for whether a user can add members - used during cluster create/edit.
I have the kept the existing mechanism, but we first now check whether the user has POST permission on the collection for the given membership type - this is the same as what dashboard does.

Fix issue where standard user can not add cluster members

---

lib/shared/addon/components/cluster-driver/driver-import/component.js

Addresses #8278
`driverSave` is an action not a method, so we need to use `send` as used elsewhere.
Not sure how this worked during test.

Fix incorrect call to driverSave action

---

lib/shared/addon/components/cluster-driver/driver-aks/component.js
lib/shared/addon/version-choices/service.js

This reverts commit ef983d665e8daebefe8213f77cfb2fcbe34e0f15.
Fixes rancher/dashboard#8280
My Azure credentials no longer work so I haven't been able to verify for myself yet. I've requested access and will verify after I do but I figured it was reasonable to put the PR up since it's just a revert.

[2.7.2] Revert "Marking aks k8s versions >= 1.24.0 as experimental"

---

lib/shared/addon/components/cluster-driver/driver-aks/component.js
lib/shared/addon/version-choices/service.js

This reverts commit ef983d665e8daebefe8213f77cfb2fcbe34e0f15.
Fixes rancher/dashboard#8280
My Azure credentials no longer work so I haven't been able to verify for myself yet. I've requested access and will verify after I do but I figured it was reasonable to put the PR up since it's just a revert.

[2.6.11] Revert "Marking aks k8s versions >= 1.24.0 as experimental"

---

lib/shared/addon/utils/constants.js

Addresses https://github.com/rancher/dashboard/issues/8299
This PR was added in 2.6.11 to add the warning banner: https://github.com/rancher/ui/pull/4962/files
If references the constant `AZURE_AD.ANNOTATION_MIGRATED` - but that is not defined in `constants.js`, so the banner is always shown when azuerad is enabled.
This PR fixes this by adding the missing constant:
```
ANNOTATION_MIGRATED: 'auth.cattle.io/azuread-endpoint-migrated'
```
Validated with a test AzureAD auth provider.

Add missing constant

---

.drone.yml
README.md
package.json
scripts/build-static
scripts/ci

This updates all references from `release-2.6` to point to the new `release-2.6.11` branch. 
#4896 used as a reference for this PR.

Bump release-2.6 references to 2.6.11

---

.drone.yml
package.json
scripts/build-static
scripts/ci

This PR updates references from `master` to `release-2.7.2`, in the same vein as https://github.com/rancher/ui/pull/4896

update build process to reference release-2.7.2 branch

---

lib/shared/addon/digital-ocean/service.js

======
It is not possible to load the Digital Ocean Node Template form if any of the Digital Ocean API requests return more than a single page. This PR fixes this issue.
======
Linked Issues
======
Closes SURE-6021

Fix Digital Ocean request pagination

---

lib/shared/addon/components/cluster-driver/driver-import/component.js

https://github.com/rancher/dashboard/issues/8452
I was able to reproduce the same behavior/console error by attempting to edit the local cluster for a rancher instance running in docker.

fix upgrade warning modal check for clusters that can't be upgraded

---

lib/shared/addon/components/cluster-driver/driver-import/component.js

https://github.com/rancher/dashboard/issues/8477
backport of https://github.com/rancher/ui/pull/4996

[2.7.2] fix upgrade warning modal check for clusters that can't be upgraded

---

translations/en-us.yaml

This PR updates a k3s doc link to point directly to the relevant section, same vein as https://github.com/rancher/ui/pull/4993

update k3s hardened cluster doc link

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js

Addresses https://github.com/rancher/dashboard/issues/8188
This ensures that when 'Edit as YAML" is used within the RKE template, that we ensure empty `value_from` keys are removed from the agent env vars.

RKE Templates: Fix issue with 'value_from' being added to agent env vars

---

app/models/cluster.js

Addresses https://github.com/rancher/dashboard/issues/4964
Rancher does not manage the local cluster, so the 'Import Host' option should not be shown - currently it is:
With this PR it is now not shown:
This PR adds an additional check for the local (internal) cluster.

Disable "import host" for local cluster

---

.drone.yml
README.md
package.json
scripts/build-static
scripts/ci

This updates all references from release-2.6 to point to the new release-2.6.12 branch.

Bump release-2.6 references to 2.6.12

---

lib/shared/addon/google/service.js

**What this PR does / why we need it:**
Adds  'asia-northeast3' region to the list of regions for GKE
Related to: https://github.com/rancher/rancher/issues/41140

Add 'asia-northeast3' region for GKE

---

lib/shared/addon/components/cluster-driver/driver-import-gke/component.js

Addresses https://github.com/rancher/dashboard/issues/8256
Ensures we send the `location` configuration for the cluster when importing.

Fix issue where can not import multi-zone GKE cluster

---

lib/shared/addon/components/form-engine-opts/component.js
translations/en-us.yaml

Addresses https://github.com/rancher/dashboard/issues/8682
Adds Docker Engine 20.10 to the docker engine option list.
Currently the default engine is 20.10, so this PR also ensures that versions are not repeated. This means as is, 20.10 only shows once. As and when the backend add 23.10, this will show up correctly.
As is:
After setting the default engine setting to 23.10:

Add Docker Engine 20.10 support

---

.drone.yml
README.md
package.json
scripts/build-static
scripts/ci

This updates all references from release-2.7.2 to point to the new release-2.7.4 branch.

Bump release-2.7.2 references to 2.7.4

---

.drone.yml
README.md
package.json
scripts/build-static
scripts/ci

This updates all references from release-2.6 to point to the new release-2.6.13 branch.

Bump release-2.6 references to 2.6.13

---

lib/shared/addon/components/cluster-driver/driver-eks/component.js

https://github.com/rancher/dashboard/issues/8721
Currently, the default kubernetes version set during eks provisioning is the highest version in the hardcoded list defined in `lib/shared/addon/utils/amazon.js`...we need to account for the possibility that the list includes versions outside the range defined in the `ui-k8s-default-version-range` setting. The dropdown shown in the EKS provisioning form properly filters versions using this setting, so I've updated the eks config initialization to reference this filtered list instead of the full hardcoded list. 
The current list of supported EKS versions doesn't include anything outside the default range in 2.7-head rancher instances. To test this PR:
* update the `ui-k8s-default-version-range` setting to `<=v1.23.x`
* print out …

set eks default kubernetes version to highest supported version

---

lib/shared/addon/utils/amazon.js

Signed-off by: Furkat Gofurov (furkat.gofurov@suse.com)
Updates hardcoded EKS supported k8s versions list with newer versions based on https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html
Since tech debt https://github.com/rancher/dashboard/issues/7295 is still open, we need to manually update this. 
@mjura @pgonin

Add new available EKS k8s versions to hardcoded list

---

app/models/cluster.js
lib/shared/addon/components/aks-node-pool-row/template.hbs
lib/shared/addon/components/cluster-driver/driver-aks/component.js
translations/en-us.yaml

This PR addresses feedback for https://github.com/rancher/dashboard/issues/8073.
It:
- Allows maxSurge to be editable after cluster creation
- Sets defaulr for maxSurge to 1
- Adds validation for maxSurge so it is either a percentage (1-100) or an integer greater than 1

AKS MaxSurge: Address QA feedback

---

lib/shared/addon/components/form-match-expressions-k8s/component.js
lib/shared/addon/components/form-match-expressions-k8s/template.hbs
translations/en-us.yaml

https://github.com/rancher/dashboard/issues/8856
The `value` field wasn't populating with the default affinity values correctly because the key was wrong, should be `values` not `value`: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#nodeselectorrequirement-v1-core
I've also updated the label in the UI to more accurately reflect the spec:

Correct agent config matchExpressions values

---

lib/shared/addon/components/form-agent-config/template.hbs
lib/shared/addon/components/resource-list/component.js

https://github.com/rancher/dashboard/issues/8871
https://github.com/rancher/dashboard/issues/8864
This PR updates the unit parsing/formatting for cpu requests to use the same utility function used for other mCPU inputs around the Ember UI. The previous solution implemented runs into problems w/ floating point arithmetic accuracy, eg when the value inputted is `1001m` this is parsed to `1.001` and `1.001*1000` returns `1000.99...`.

fix agent config cpu req unit formatting

---

lib/shared/addon/components/aks-node-pool-row/component.js
lib/shared/addon/components/cluster-driver/driver-aks/component.js

Addresses https://github.com/rancher/dashboard/issues/8073
- Fixes maxSurge can not be 1 or 1%
- Ensures maxSurge is set to 1 when editing a cluster provisioned prior to these AKS UI changes

AKS MaxSurge fixes

---

app/models/cluster.js

https://github.com/rancher/dashboard/issues/8887
When pre-existing imported EKS clusters are saved, the upstream `eksConfig` spec is grabbed and only the difference between that and the `eksConfig` the user is attempting to save is sent in the network request:
https://github.com/rancher/ui/blob/a471895e9b78c36bbdf4435d74364b40e4bcbfd8/app/models/cluster.js#L1244-L1290
This PR updates the cluster `save` method to check if the cluster or fleet agent configs have been changed and include them in the save request if so. I opted to just compare the entire config object; it felt a little extra to check each field within it for changes and this solution seems to work just fine from my own testing. 
We hit a similar problem saving labels and annotations previously: …

Fix editing agent config in imported EKS clusters

---

lib/shared/addon/components/cru-cluster/template.hbs

======
- Button was disbaled via 'editing' = false
- I've gone through the history trying to find out why editing members of a k3s cluster (and previously imported rke2) was disabled
- There's no info in any of the PRs or issues
- Going to take the plunge and say we're find doing this
- K3S editing disabled via https://github.com/rancher/ui/pull/3766/files
- RKE2 editing disabled via https://github.com/rancher/ui/pull/4074/files
- RKE2 editing enabled via https://github.com/rancher/ui/pull/4866
Linked Issues
======
Fixes https://github.com/rancher/dashboard/issues/8940
Note - Both RKE (handled by this UI) and RKE2 (handled by dashboard) both allowed the removal of cluster members in their respective edit pages

Enable editing of members in the edit k3s cluster page

---

lib/login/addon/login/controller.js
lib/login/addon/login/route.js

Addresses https://github.com/rancher/dashboard/issues/8964
Re-enabled the legacy login page if the URL contains a query string - this ensures it can be used by the Rancher CLI.

Allow legacy login page to be used by Rancher CLI

---

lib/shared/addon/utils/amazon.js

======
- This means when users create creds they can be validated against one of the new regions 
- This also means users can select these creds when creating EC2 based RKE1 clusters
Linked Issues
======
https://github.com/rancher/dashboard/issues/8701
======
I haven't managed to successfully test EKS OR RKE1 EC2 in these regions, they're blocked to me

Ensure new EKS regions can be selected when validating creds

---

app/app.js
app/application/controller.js
app/application/route.js
app/authenticated/controller.js
app/authenticated/embed/route.js
app/authenticated/project/controller.js
app/authenticated/route.js
app/components/security-header/component.js
app/initializers/route-spy.js
lib/istio/addon/components/modal-delete-istio/component.js
lib/monitoring/addon/components/cluster-dashboard-tabs/component.js
lib/monitoring/addon/components/cluster-dashboard/component.js
lib/monitoring/addon/index/controller.js
lib/shared/addon/components/accordion-list-item/component.js
lib/shared/addon/components/accordion-list-item/template.hbs
lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
lib/shared/addon/components/cru-cluster/template.hbs
lib/shared/addon/components/form-members/template.hbs
lib/shared/addon/components/form-name-description/template.hbs
lib/shared/addon/components/modal-add-custom-roles/template.hbs
lib/shared/addon/growl/service.js
lib/shared/addon/scope/service.js
lib/shared/addon/user-theme/service.js
lib/shared/addon/utils/util.js
lib/shared/app/utils/util.js

- Create helper functions to determine if running in embedded mode, and the target window for dashboard messages
- Wasn't sure where to put this, hopefully choice the right location
- isEmbedded `window.top !== window` weirdly didn't work in cypress runner, so now we check if window.top has ember available (only scenario where isEmbedded is false)
- window used for messaging dashboard is now window.parent, window.top can be cypress runner
Note - This should merge after we release /  branch 2.7q2
Note 2 - Snuck in some identifiers for e2e tests. There must be a nice way to assign attributes to top level elements used by elemental components... stooped to use the easier class one instead

Ensure embedded ember pages in dashboard work with cypress / e2e

---

lib/shared/addon/components/form-engine-opts/component.js

Addresses https://github.com/rancher/dashboard/issues/9222
Addresses https://github.com/rancher/dashboard/issues/9177
This PR adds Docker 23.0.x support - so when 23 is added, this will come from the backend as the default version and will be added to the list. Docker 23 is currently the default, so adding 23 here will ensure that when it is no longer the default, it will continue to be listed.
Code added in the previous release ensures that if a hard-code entry in the list is also the default, it will only be shown once.

Add docker 23.0.x support

---

app/models/cluster.js
lib/shared/addon/components/form-agent-config/component.js
lib/shared/addon/components/form-match-expressions-k8s/component.js
lib/shared/addon/components/form-match-expressions-k8s/template.hbs
lib/shared/addon/components/form-node-affinity-k8s/component.js
lib/shared/addon/components/form-node-selector-term-k8s/component.js
lib/shared/addon/components/form-pod-affinity-k8s/component.js
lib/shared/addon/components/form-pod-affinity-term-k8s/component.js
lib/shared/addon/components/form-pod-affinity-term-k8s/template.hbs
lib/shared/addon/components/input-array-as-string/component.js

https://github.com/rancher/dashboard/issues/9003
In addition to the issue above this PR also fixes an issue where switching an affinity term between from required to preferred clears out other required terms, and some instances in which the match expressions/field select appeared in pod affinity terms (which should only be available in node affinity terms)

Bugfix agent config

---

lib/shared/addon/components/form-network-config/component.js
lib/shared/addon/components/form-network-config/template.hbs
translations/en-us.yaml

Addresses: https://github.com/rancher/dashboard/issues/9556
Shows a deprecation banner if the user selects Weave network and a Kubernetes version >= 1.27
This will need manual testing as it requires a configured cloud credential to get to cluster provisioning.

Show banner that Weave is deprecated for k8s >= 1.27

---

lib/shared/addon/components/cru-cloud-provider/component.js
lib/shared/addon/components/cru-cloud-provider/template.hbs
translations/en-us.yaml

RKE1 side of https://github.com/rancher/dashboard/issues/9204
Requirements from internal design docs:
If k8s version >= 1.27 is selected during cluster creation, the aws in-tree provider option should be hidden.
If k8s version >=1.27 is selected while editing a cluster and the aws in-tree provider had previously been configured, the provider options are made editable, and the provder is switched to 'external.' 
If the k8s version is changed back to <1.27, the cloud provider choice is reverted.
Since 1.27 isn't available yet, you can manually add the option [here](https://github.com/mantis-toboggan-md/ui/blob/5551da85705b1101d2cc84dadd13f73cf72e98bd/lib/shared/addon/components/form-versions/component.js#L144)
```
mappedVersions.push({
disbaled:     false,
experimental: false,
label: …
```

Remove support for aws in-tree provider for k8s >=1.27

---

lib/shared/addon/components/cluster-driver/driver-gke/template.hbs
lib/shared/addon/components/gke-node-pool-row/component.js

======
Set the initial node version to the cluster's max valid version, also disabled upgradeVersion when cluster version is higher than the max valid version.
Fixes [#9507](https://github.com/rancher/dashboard/issues/9507)
https://github.com/rancher/ui/assets/135728925/b08fccff-2fa3-49aa-ac80-a11a7ebf3b5f

9507 - [GKE] Fixed inconsistency between node and cluster versions

---

.drone.yml

2.7 update for reference - https://github.com/rancher/ui/pull/4897 
We need to update drone.yml so UI builds are triggered when v2..8 tags are made.

update drone jobs to run on v2.8.* tags

---

lib/shared/addon/utils/amazon.js

Updates v1.27 k8s versions list with newer versions based on https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html
https://github.com/rancher/eks-operator/issues/264

Add v1.27 k8s versions to EKS hardcoded list

---

lib/shared/addon/google/service.js
translations/en-us.yaml

Addresses: https://github.com/rancher/dashboard/issues/9401
I recreated this issue with an invalid Project ID and a valid cloud credential:
- Add a valid GKE cloud credential
- Go to create a GKE Cluser
- Select the credential
- Enter project ID `"TEST//"`(with the quotes)
- You'll get the 500 and the error message
Note: It appears you get the 500 error from Google if you use a project ID that does match up with the selected cloud credential.
This PR fixes this issue - in some cases we can't parse the response error from Google, so it is returned as a string and not an object - hence when we access `error.body`, it fails.
With this PR, we fall back to a generic error message if we can not parse the error response.

Fix issue handling error from GKE zone list request

---

lib/shared/addon/utils/amazon.js

Remove v1.23 and v1.24 k8s versions frome the EKS list based on 
rancher/eks-operator#259

Remove K8s v1.23 and v1.24 from EKS hardcoded list

---

lib/shared/addon/components/cru-cloud-provider/component.js

[#9933](https://github.com/rancher/dashboard/issues/9933) 
I botched this - cloud provider form inputs aren't setting cluster config fields directly; those are set in the `constructConfig` function which defaults to an empty object
https://github.com/rancher/ui/assets/42977925/ed64ffb7-6f14-4b17-a428-2d57212d7905

update constructConfig to handle external-aws cloud provider

---

lib/shared/addon/components/cru-cloud-provider/component.js
translations/en-us.yaml

https://github.com/rancher/dashboard/issues/9204#issuecomment-1773556413
upgrading when the cloud provider was set to amazon in-tree:
https://github.com/rancher/ui/assets/42977925/56b91165-e6cc-4da1-8e0c-f6a617499e0d
upgrading without cloud provider set:
https://github.com/rancher/ui/assets/42977925/6890578f-e331-4e95-bff2-4beeac00da8e

Set cloud provider to external-aws when upgrading from <1.27

---

lib/nodes/addon/components/driver-vmwarevsphere/template.hbs
translations/en-us.yaml

Linked Issues
======
Fixes RKE1 part of [this issue](https://github.com/rancher/dashboard/issues/9620).
Videos
======
https://github.com/rancher/ui/assets/135728925/fe408a9e-2f5f-4bbe-be8c-6aedc7a10d36
https://github.com/rancher/ui/assets/135728925/e0775fee-06b4-4010-bb4c-3e6dcafaeb63

RKE1 gracefulShutdownTimeout option for vSphere node template

---

yarn.lock

Updates caniuselite to remove the warnings when building or running in dev.

Update caniuselite to latest version

---

app/models/cluster.js

Addresses https://github.com/rancher/dashboard/issues/10105
Fixes issue where cluster labels are not shown when editing a cluster and the cluster being edited does not support labels being edited - currently in this case, the labels are not shown and only the annotations are presented to the user.

Fix issue where labels are not shown for clusters

---

lib/shared/addon/utils/amazon.js

Updates v1.28 k8s versions list with newer versions based on https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html

Add v1.28 k8s versions to EKS hardcoded list

---

.drone.yml
README.md
package.json
scripts/build-static
scripts/ci

This updates environment values for CI scripts so that they target the `release-2.7` branch.

Bump versions for `release-2.7` branch

---

.drone.yml
README.md
package.json
scripts/build-static
scripts/ci

This updates environment values for CI scripts so that they target the `release-2.8` branch.

Bump versions for release-2.8 branch

---

lib/shared/addon/components/cluster-driver/driver-gke/template.hbs
lib/shared/addon/components/gke-node-pool-row/component.js
lib/shared/addon/components/gke-node-pool-row/template.hbs

Fixes https://github.com/rancher/dashboard/issues/9507
Within the `driver-gke` logic, if the cluster version is not present in the list of available version choices, the first item (maximum version) is automatically selected. However, the same behavior was not extended to the node version.

Syncing node version with cluster version

---

lib/shared/addon/components/cru-cloud-provider/component.js

https://github.com/rancher/dashboard/issues/10290 - the banner warning the user that the cloud provider has been changed should be hidden when the cloud provider change is reverted.
https://github.com/rancher/ui/assets/42977925/23de0233-4bca-46be-b56d-0d3cc36addb4

fix aws-external warning banner visibility

---

lib/shared/addon/components/form-network-config/component.js
lib/shared/addon/components/form-network-config/template.hbs
translations/en-us.yaml

https://github.com/rancher/dashboard/issues/10291
Backport of https://github.com/rancher/ui/pull/5062

[2.7] Show banner that Weave is deprecated for k8s >= 1.27

---

lib/shared/addon/components/cru-cloud-provider/component.js
lib/shared/addon/components/cru-cloud-provider/template.hbs
lib/shared/addon/components/radio-button/component.js
translations/en-us.yaml

https://github.com/rancher/dashboard/issues/10297
https://github.com/rancher/dashboard/issues/10266 - this issue also has an rke2 portion to be backported in rancher/dashboard.
This is a backport of a few PRs: 
https://github.com/rancher/ui/pull/5064 (remove the aws in-tree option for k8s >=1.27)
https://github.com/rancher/ui/pull/5078 (add an external-aws option)
https://github.com/rancher/ui/pull/5082 (improve the banners around the above 2 PRs)
For testing purposes, you can add 1.27 to the list of available versions by adding code [here](https://github.com/mantis-toboggan-md/ui/blob/5551da85705b1101d2cc84dadd13f73cf72e98bd/lib/shared/addon/components/form-versions/component.js#L144)
```
mappedVersions.push({
disbaled:     false,
experimental: false,
label:        'v1.27.0-rancher1-1', …
```

[2.7] Backport AWS external cloud provider support; removal of aws in-tree cloud provider

---

lib/shared/addon/components/cluster-driver/driver-gke/component.js
translations/en-us.yaml

Addresses https://github.com/rancher/dashboard/issues/8749
This PR fixes the above bug:
- Ensures that if you use a range name, we do NOT also send the ipv4 cidr block as well
- Ensures that we add a '<None>' option to the range selector, so that a user can clear the range name and set the ipv4 cidr block if they select a range - currently once you select a range name, there is no way to clear it
This requires manual test as you need access to GKE.
Instructions to test are in the issue at the top - you need to create a VPN with subnets that have secondary ranges. Then create a cluster, selecting a secondary range name and validate that the cluster creates okay.

Fix GKE range name and CidrBlock conflict

---

lib/shared/addon/components/cluster-driver/driver-aks/component.js
lib/shared/addon/components/cluster-driver/driver-eks/component.js
lib/shared/addon/components/cluster-driver/driver-gke/component.js
translations/en-us.yaml

Addresses https://github.com/rancher/dashboard/issues/9987
Addresses https://github.com/rancher/dashboard/issues/4465
This PR adds node pool/group duplicate name validation for gke, aks and eks.
Same pattern is used in each - for simplicity, added to each provider, rather than attempt to factor into some common code. Ember code is legacy, so this feels like a reasonable approach to address this issue.
Code is straight-forward - adds to the validation method to check each node pool/group name - adds an error with the names of the duplicates if found.
To test, for each provider, add several node pools/groups with some duplicates and validate that you see the error message. Pleas also test with node groups without names.

Add node pool/group duplicate name validation for hosted providers

---

lib/shared/addon/components/cru-cloud-provider/component.js

Backport of https://github.com/rancher/ui/pull/5105
GH issue for the backport is https://github.com/rancher/dashboard/issues/10298

[2.8] fix aws-external warning banner visibility

---

app/authenticated/project/config-maps/index/controller.js
app/authenticated/project/config-maps/index/template.hbs
app/components/security-header/template.hbs
translations/en-us.yaml

- Added deprecation warning to Secrets tab
- Added deprecation warning and an info banner to Config Maps tab
Linked Issues
======
Fixes https://github.com/rancher/dashboard/issues/10321

Added deprecation warnings to embedded Secrets and Config Maps tabs

---

lib/shared/addon/components/managed-import-cluster-info/component.js
lib/shared/addon/components/managed-import-cluster-info/template.hbs
translations/en-us.yaml

This displays an info banner that informs users about changes regarding in-tree cloud providers when upgrading to a version of Kubernetes >=1.27 from a version that is <=1.27.
closes rancher/dashboard#10414

Show info banner when upgrading Kubernetes 1.27 or greater

---

lib/shared/addon/components/managed-import-cluster-info/component.js
lib/shared/addon/components/managed-import-cluster-info/template.hbs
translations/en-us.yaml

This displays an info banner that informs users about changes regarding in-tree cloud providers when upgrading to a version of Kubernetes >=1.27 from a version that is <=1.27.
backports rancher/dashboard#10414
closes rancher/dashboard#10419

[backport v2.7.patch1] Show info banner when upgrading Kubernetes 1.27 or greater

---

lib/shared/addon/components/managed-import-cluster-info/component.js
lib/shared/addon/components/managed-import-cluster-info/template.hbs
translations/en-us.yaml

This displays an info banner that informs users about changes regarding in-tree cloud providers when upgrading to a version of Kubernetes >=1.27 from a version that is <=1.27.
backports rancher/dashboard#10414
closes rancher/dashboard#10420

[backport v2.8.next1] Show info banner when upgrading Kubernetes 1.27 or greater

---

lib/shared/addon/components/cluster-driver/driver-aks/component.js
lib/shared/addon/components/cluster-driver/driver-aks/template.hbs
translations/en-us.yaml

======
Allowing users to disable project network isolation when editing an aks cluster
Linked Issues
======
Specifically addressing the comment here https://github.com/rancher/dashboard/issues/9905#issuecomment-1921549735
======
Reading the jira issue I think there may be more to the original issue because the comment only addresses aks. I do think that this change will be necessary but I suspect more changes will follow in separate PRs.
Dev Testing
======
I do not currently have access to AKS. In order to test this I modified the driver-aks component directly by touching these fields

Allowing users to disable project network isolation when editing an aks cluster

---

.github/workflows/port-pr.yaml

This adds the Port PR github action to `rancher/ui`. 
Tested in my fork and appears to be working without modification at this point: https://github.com/rak-phillip/ui/actions/runs/8190980685
closes rancher/dashboard#10570

Add Port PR workflow

---

lib/shared/addon/components/cru-cloud-provider/component.js

This uses the `initialCloudProvider` to determine if the cloud provider needs to be set to `external-aws` when changing Kubernetes versions.
The previous implementation that used the selected cloud provider would toggle `selectedCloudProvider` between `external-aws` and `amazonec2` when selecting different kubernetes versions that are >= 1.27.0.
closes rancher/dashboard#10516

Use `initialCloudProvider` for comparison when upgrading Kubernetes from <1.27

---

translations/en-us.yaml

Fix Typo
======
Smallest of small changes. Just noticed a small typo when running through through a manual deployment of cluster on AWS. 
In the networking section, fixed the incorrect spelling of 'private'. 
======
Spelling. 
Linked Issues
======
No linked issues. 
======
Nothing else, not a dramatic change, no functional changes.

Fixing Misspelling 

---

lib/shared/addon/components/form-engine-opts/component.js

fixes rancher/dashboard#10806
This PR adds Docker 24.0.x support - so when 24 is added, this will come from the backend as the default version and will be added to the list. Docker 24 is currently the default, so adding 24 here will ensure that when it is no longer the default, it will continue to be listed.
Code added in the previous release ensures that if a hard-code entry in the list is also the default, it will only be shown once.

Add docker 24.0.x support

---

lib/shared/addon/components/form-engine-opts/component.js

Address https://github.com/rancher/dashboard/issues/10841
This PR adds docker 26 to the dropdown list.
It also adds in 25, which is the current version.
Note that the UI retrieves the current version (the one marked as recommended) from a setting - so 25 is not currently in the list, but appears via the setting. 26 is now added, so we have to add 25 to the maintained list.
Also adding 26, although this will now come from the setting - the UI will de-dup from the hard-coded list and the setting, so 26 will only show once as recommened.

Add docker 26 option

---

lib/shared/addon/utils/amazon.js

======
Fixes https://github.com/rancher/dashboard/issues/11132
======
Linked Issues
======
======
In rancher 2.8.x/2.7.x version, region, and instance type are hardcoded in the old EKS form.
EKS  cluster provisioning UI uses the iFramed Ember page ... 
Currently, an issue rancher/dashboard gh#8083 to provision public cloud clusters (AKS, EKS & GKE), the cloud provisioning pages are iFramed from Ember into Vue. which dynamically updates these values from rancher-2.9.0(targetted version)...

add eks m6&c6 instance types

---

lib/shared/addon/components/form-engine-opts/component.js

Addresses https://github.com/rancher/dashboard/issues/10996
Swaps out Docker Install URL 26.0 for 26.1

Swap out docker install URL 26.0 to 26.1

---

lib/shared/addon/components/cluster-driver/driver-gke/component.js
lib/shared/addon/components/gke-node-pool-row/component.js
lib/shared/addon/components/gke-node-pool-row/template.hbs

https://github.com/rancher/dashboard/issues/11357
There are two semi-related issues in 11357
1. The cluster kubernetes version (sometimes called control plane version in the code) is being set to the latest version google provides (1.29 right now) instead of the latest version Rancher supports (1.28 in 2.8-head)
2. The node pool versions are being set to the latest available version instead of syncing with the control plane version
Fix for problem 1 was fairly straightforward: instead of using the defaultClusterVersion from the GCP API call we set the cluster version to the latest version shown in the version dropdown. In addition to respecting Rancher-specific versioning limitations this has the added bonus of ensuring that the cluster version is _never_ automatically set to something …

Fix GKE default version and tweak node pool upgrade versioning logic

---

lib/shared/addon/components/cluster-driver/driver-import-aks/component.js

This PR addresses https://github.com/rancher/dashboard/issues/7913#issuecomment-2220495013
The catch block in driver-import-aks is expecting errors in a different format than the UI receives when an invalid credential is used. I wasn't sure if the expected format would show up if a different error were produced, so I have added onto the logic rather than replacing it entirely.

fix azure error message formatting

---

translations/de-de.yaml
translations/en-us.yaml
translations/es-es.yaml
translations/ja-jp.yaml
translations/uk-ua.yaml
translations/zh-hans.yaml
translations/zh-hant-tw.yaml
translations/zh-hant.yaml

https://github.com/rancher/dashboard/issues/9361
The assorted "ICU argument missing..." errors shown when running the UI locally are mostly a result of translation strings in en-us being updated to no longer reference arguments still present in other l18n files. This seems to throw errors even if the arguments are still be provided in template files.  Some translation strings have drifted so much in en-us that it was unclear to me how to rewrite the corresponding translations to remove arguments in other files, so I wound up removing them entirely.
Other things going on:
- A bunch of shibboleth translations still referenced in templates were removed from en-us, maybe unintentionally? https://github.com/rancher/ui/pull/3721/files#diff-93bba6cdcf2bf03eb02ffd57e800a775e4b3879683bad0d0f4f3f750 …

clean up l18n

---

lib/shared/addon/components/form-engine-opts/component.js

Backport - Addresses https://github.com/rancher/dashboard/issues/11530
Adds Docker Install URL 27.0 and 27.1

BP: Add docker install URL for 27.0 and 27.1

---

lib/shared/addon/components/cru-cloud-provider/component.js
lib/shared/addon/components/cru-cloud-provider/template.hbs
translations/en-us.yaml

Fixes https://github.com/rancher/dashboard/issues/11520
- Azure is removed from the list of cloud providers when k8s version is `>= 1.30`
- When selected k8s version is  `>=1.27 or < 1.30` the Azure option will be displayed
- While the supported version is selected If you change that to an unsupported version `External` option automatically gets selected and a warning banner will be displayed that includes a documentation link
- By switching to a different cloud provider or a supported k8s version the warning banner will disappear
https://github.com/user-attachments/assets/dbf8fe0e-9fea-4a55-8f1c-58f4124d62de
- Watch the video and test the same scenarios
- Also try to finish creating an Azure RKE1 cluster, I did not test that in my video, and there was an issue that got fixed later

Update azure cloud provider option based on k8s version support

---

app/components/container/form-image/component.js

Update to the current samples repo. The old samples repro will be deleted.
See: https://github.com/dotnet/dotnet-docker/issues/4755
FYI on other breaking changes: https://github.com/dotnet/dotnet-docker/discussions/4764

Update Windows Container Samples Repository URL

---

app/authenticated/cluster/cis/scan/controller.js
lib/pipeline/addon/components/edit-pipeline-config/component.js
lib/shared/addon/bulk-action-handler/service.js
lib/shared/addon/mixins/cattle-transitioning-resource.js
lib/shared/addon/utils/download-files.js
lib/shared/package.json
package.json
yarn.lock

This PR removes the JsZip library.
This was only being used in 2 parts of the codebase - cis scans and pipelines - both of these are no longer shown in the UI.
For simplicity, the code has been removed and errors are logged - these code paths should not be reachable in the UI - we will prune this code in the future as part of a larger tidy-up effort.

Remove use of JsZip

---

lib/shared/addon/utils/amazon.js

It looks like the included AWS EC2 instance list in Rancher is a bit stale.  I've attempted to update the existing instance types with the latest Intel/AMD versions excluding some of the fancier EC2 types for networking/storage .  Graviton instances look like they're still marked as "experimental" for use in Rancher so those have been excluded too.

update ec2 instances list in amazon.js

---

app/authenticated/route.js
app/fail-whale/controller.js
app/fail-whale/template.hbs
scripts/patch-docker
translations/en-us.yaml

Addresses https://github.com/rancher/dashboard/issues/11371
If the UI is not running in development mode and not embedded, then send the user to the error page.
Only the pages embedded in the new dashboard UI are supported - this PR adds a check to see if the old UI is being accessed standalone and shows an error message if so.
Access to `/g` should show the new error page:
This PR:
- Updates the fail page to include support for showing a specific message related to removing standalone access
- Update authentication guard to check access and throw an error if being accessed standalone, which causes the fail page to be shown
- Added translations as needed
- Adds a script to help with testing - it builds the static UI assets and copies them into a running Rancher container, allowing testing …

Remove standalone access to the legacy UI

---

lib/shared/addon/components/cru-cluster/component.js
lib/shared/addon/utils/constants.js

https://github.com/rancher/dashboard/issues/11852
This PR adds an annotation when creating rke1 clusters and importing aks/eks/gke clusters. See the dashboard side https://github.com/rancher/dashboard/pull/12233 for more details

Set creator principal id annotation when creating clusters

---

README.md
package.json
scripts/build-static

Release activities for `release-2.10` branch. 
Related #5153

Branch for 2.10

---

lib/shared/addon/components/cluster-driver/driver-linodelke/component.js
lib/shared/addon/components/cluster-driver/driver-linodelke/template.hbs
translations/en-us.yaml

======
This change adjusts the LKE cluster creation UI to represent upcoming LKE Node Pool pricing changes. 
======
- Adjusts the displayed hourly and monthly pricing for each LKE Node Pool plan to reflect region-specific pricing exceptions.
- Adds a notice displayed when a user's Node Pool configuration is affected by any region-specific pricing exceptions.
Linked Issues
======
Related issue https://github.com/rancher/rancher/issues/42702
Preview
======
Configuring node pools in a region with pricing exceptions (id-cgk):

new: Represent region-specific pricing when configuring LKE Node Pools

---

lib/shared/addon/components/form-engine-opts/component.js

Addresses https://github.com/rancher/dashboard/issues/12912 and https://github.com/rancher/dashboard/issues/12913
This PR adds the requested docker install URLs.

[2.9] Add docker install URL for 27.3 and 27.4

---

lib/shared/addon/components/form-engine-opts/component.js

Addresses https://github.com/rancher/dashboard/issues/12911 and https://github.com/rancher/dashboard/issues/12910
This PR adds the requested docker install URLs.

[2.10] Add docker install URL for 27.3 and 27.4

---

lib/shared/addon/components/form-engine-opts/component.js

Addresses https://github.com/rancher/dashboard/issues/12908 and https://github.com/rancher/dashboard/issues/12909 
This PR adds the requested docker install URLs.

[2.11] Add docker install URL for 27.3 and 27.4

---

app/authenticated/cluster/edit/template.hbs
lib/global-admin/addon/clusters/new/template.hbs
translations/en-us.yaml

======
A warning banner added to the cluster's create and edit pages.
Linked Issues
======
https://github.com/rancher/dashboard/issues/13284
https://github.com/user-attachments/assets/2c64ff11-7519-4d1d-a8dd-81967deed760

RKE1 deprecation banner on create and edit pages

---

app/authenticated/cluster/edit/template.hbs
lib/global-admin/addon/clusters/new/route.js
lib/global-admin/addon/clusters/new/template.hbs
lib/shared/addon/components/cru-cluster/component.js
lib/shared/addon/components/cru-cluster/template.hbs
translations/en-us.yaml

Addresses https://github.com/rancher/dashboard/issues/14286
This PR changes re-uses the RKE1 deprecation banner for deprecation of Ember-based UI plugins.
It also fixes a bug with the code that handles error loading custom javascript for a plugin and now correctly handles this and shows an error on the creation screen when this happens - previously users get a partially-rendered page.
To test:
- Enable a cluster driver from the Drivers page - suggested one is `Open Telekom Cloud CCE`
Go to create and choose this driver.
Check that the page shows the new deprecation banner:
Go the Drivers and edit the for the drvier  - add some junk to the end of the URL, eg:
Reload the UI (since the plugin is cached and we need to reload to remove it)
Go to the cluster create again and verify that the …

Deprecate ember-based UI Plugins

---

app/authenticated/cluster/edit/route.js
app/authenticated/route.js
app/models/cloudcredential.js
lib/global-admin/addon/clusters/new/launch/route.js

https://github.com/rancher/dashboard/issues/14753
The network tab showed additional 404's, but removing these requests to fetch node templates appears to be sufficient.

remove requests to load nodeTemplates during kontainer cluster provisioning

---

app/authenticated/cluster/edit/template.hbs
lib/global-admin/addon/clusters/new/template.hbs
translations/en-us.yaml

Addresses: https://github.com/rancher/dashboard/issues/15257
This PR removes the Ember deprecation banner.
The banner will be moved to the Cluster Drivers page in the dashboard UI.
This PR removes the banner from the Edit and Create cluster pages:

Remove Ember deprecation banner

---

app/authenticated/cluster/edit/template.hbs
lib/global-admin/addon/clusters/new/template.hbs
translations/en-us.yaml

Backport of https://github.com/rancher/ui/pull/5241
Addresses: https://github.com/rancher/dashboard/issues/15258
This PR removes the banner from the Edit and Create cluster pages:

[Backport 2.12.2] Remove Ember deprecation banner 
