rancher/ui

app/initializers/authentication.js
app/pods/components/github-avatar/component.js
app/pods/components/github-avatar/template.hbs
app/pods/components/page-header/template.hbs
app/pods/login/controller.js
app/pods/settings/auth/controller.js
app/pods/settings/auth/route.js
app/pods/settings/auth/template.hbs
app/pods/settings/route.js
app/styles/layout.scss
package.json

- Check Github API and automatically remove users/orgs that don't exist
- Saving/Saved state on the authorization save button to show state
- Waiting state on test button to show state
- Size GitHub popup window bigger to show content

Access Control config enhancements

---

app/initializers/store.js
app/mixins/authenticated-route.js
app/pods/authenticated/route.js
app/pods/login/controller.js
app/pods/settings/auth/controller.js
app/pods/settings/auth/route.js
app/pods/settings/auth/template.hbs
app/utils/session-storage.js
package.json

- Save all properties of the token response into session, so orgs can be read later

Show dropdown of user's organizations

---

app/pods/apikey/controller.js
app/pods/authenticated/view.js
app/pods/components/action-menu-item/component.js
app/pods/components/container-widget/component.js
app/pods/components/container-widget/template.hbs
app/pods/components/host-widget/component.js
app/pods/components/host-widget/template.hbs
app/pods/components/page-header/template.hbs
app/pods/components/page-nav/template.hbs
app/pods/components/resource-actions-menu/component.js
app/pods/components/resource-actions-menu/template.hbs
app/pods/components/resource-actions/template.hbs
app/pods/container/controller.js
app/pods/container/shell/route.js
app/pods/host/controller.js
app/pods/project/controller.js
app/pods/volume/controller.js
app/styles/host.scss
app/styles/layout.scss
app/styles/resource-actions.scss
app/utils/cattle.js
app/utils/stats.js
bower.json
package.json

- Set TERM environment variable on shell

Reskin: action menus on host & containers

---

Brocfile.js
app/pods/authenticated/route.js
app/pods/components/zero-clipboard/component.js
app/pods/container/template.hbs
app/pods/hosts/new/controller.js
app/pods/hosts/new/custom/controller.js
app/pods/hosts/new/custom/template.hbs
app/styles/app.scss
app/styles/zero-clipboard.scss
bower.json
config/environment.js
package.json

- Show imageUuid on containers
- Update Host IP address when ipAddress change events come in

Copy To Clipboard

---

app/mixins/throttled-resize.js
app/pods/authenticated/route.js
app/pods/hosts/index/view.js
app/styles/host.scss
package.json

- Catch race condition on leaving throttled-resize view after a resize

Fix host/instance change updating

---

app/initializers/authentication.js
app/initializers/config.js
app/initializers/extend-ember-route.js
app/initializers/extend-ember-view.js
app/initializers/extend-jquery.js
app/initializers/lookup.js
app/initializers/session.js
app/initializers/store.js
app/initializers/touch.js
app/pods/application/route.js
app/pods/authenticated/controller.js
app/pods/authenticated/route.js
app/pods/authenticated/template.hbs
app/pods/components/page-header/component.js
app/pods/components/page-header/template.hbs
app/pods/container/route.js
app/pods/containers/index/view.js
app/pods/host/host-containers/route.js
app/pods/overlay/route.js
app/styles/layout.scss
app/utils/platform.js

- Remember the previous route as a property on the application route
- Move overlay goToPrevious into application route
- Alternate action key -> Cmd on Mac, Ctrl on others
- Document initializers

Back on container page goes back to the screen you were previous on

---

app/index.html
public/static/index.html

Partially addresses rancherio/rancher#140

Switch CDN URLs to SSL-capable Google ones

---

app/pods/components/host-widget/template.hbs
app/pods/components/resource-actions-menu/template.hbs
app/pods/container/edit/view.js
app/pods/containers/new/controller.js
app/pods/containers/new/route.js
app/pods/containers/new/template.hbs
app/pods/containers/new/view.js
app/pods/host/controller.js
app/pods/host/template.hbs
app/styles/host.scss
app/styles/layout.scss
app/templates/container/edit-links.hbs
app/templates/container/edit-ports.hbs
app/templates/container/new-command.hbs
app/templates/container/new-network.hbs
app/templates/container/new-security.hbs
app/templates/container/new-volumes.hbs
public/assets/images/circle-menu.svg
public/assets/images/circle-plus.svg
public/assets/images/circle-x.svg

- Additional host info on hosts (cpu, ram, storage, os)
- Advanced options toggle on add container
- Fancy SVG circle buttons that are actually centered

Host info, advanced new container

---

app/pods/authenticated/route.js
app/pods/containers/new/view.js
app/pods/host/controller.js
app/pods/hosts/new/route.js
app/pods/hosts/new/template.hbs
app/pods/hosts/setup/controller.js
app/pods/hosts/setup/route.js
app/pods/hosts/setup/template.hbs
app/pods/hosts/setup/view.js
app/router.js
app/styles/layout.scss
app/templates/container/new-volumes.hbs
app/utils/constants.js
app/utils/unpurged-array-proxy.js
package.json

- Focus container name on add container
- Hide OS info until bug is fixed where it always shows ubuntu
- Don't blow up if cpuInfo or diskInfo are empty objects
- Fix round button press states

Hosts Setup to set api.host setting

---

app/index.html
app/initializers/authentication.js
app/initializers/prefs.js
app/pods/application/template.hbs
app/pods/authenticated/controller.js
app/pods/authenticated/route.js
app/pods/authenticated/template.hbs
app/pods/components/page-articles/component.js
app/pods/components/page-articles/template.hbs
app/pods/components/page-header/component.js
app/pods/components/page-header/template.hbs
app/pods/components/page-nav/template.hbs
app/pods/host/route.js
app/pods/host/template.hbs
app/styles/github-avatar.scss
app/styles/layout.scss
app/utils/browser-storage.js
app/utils/constants.js
app/utils/local-storage.js
app/utils/session-storage.js
config/environment.js
public/static/index.html
scripts/build-static
tests/unit/components/page-header-test.js

- Move access control is not configured message to top ("ARTICLE"s)
- Add preference to hide the access control message
- Show the logged-in-user box in the top right even when auth is off
- Add host registration screen to the user menu
- Rearrange how HEADER, NAV, and ASIDE are rendered
- s/cdn.rancher.io/releases.rancher.com/g

Access Control disabled message

---

app/environment/code/template.hbs
app/environment/graph/template.hbs
app/environment/graph/view.js
app/service/controller.js

- Fix graph covering buttons with auth off
- Copy .yml files to clipboard
- Scale up button

Service tweaks

---

app/hosts/new/digitalocean/digitalocean_regions.js

@vincent99 Grouped the DO regions so that NYC 2/3 and Amsterdam 2/3 would be together.

Group order of DigitalOcean regions

---

app/authenticated/route.js
app/utils/cattle.js
app/utils/util.js

- Fix transitioning polling of resources changing frequently
- Spread out transition poll timers by 10%

Fix initial projectId detection

---

app/mixins/github-info.js
app/styles/github-avatar.scss
app/styles/header.scss
app/styles/layout.scss

UI fixes for the menu, red top band, color change for active icon in add host

---

app/hosts/new/digitalocean/controller.js

@vincent99 This should hide the Ubuntu 14.10 from DO. Assuming I found the right place. :)
(rancher/#1666)

Hide Ubuntu 14.10

---

.jshintrc
app/admin-tab/processes/controller.js
app/admin-tab/processes/index/controller.js
app/admin-tab/processes/index/template.hbs
app/admin-tab/processes/process/controller.js
app/admin-tab/processes/process/route.js
app/admin-tab/processes/process/template.hbs
app/admin-tab/processes/route.js
app/admin-tab/processes/template.hbs
app/components/page-header/template.hbs
app/components/process-execution-handler-rows/component.js
app/components/process-execution-handler-rows/template.hbs
app/components/process-execution-rows/component.js
app/components/process-execution-rows/template.hbs
app/components/process-executions/component.js
app/components/process-executions/template.hbs
app/mixins/sortable.js
app/processinstance/model.js
app/router.js
app/styles/bootstrap-tweak.scss
app/styles/layout.scss
bower.json
tests/unit/admin-tab/processes/controller-test.js
tests/unit/admin-tab/processes/process/controller-test.js
tests/unit/admin-tab/processes/process/route-test.js
tests/unit/admin-tab/processes/route-test.js

Users wanted access to the processes logs which are helpful to debug or find problematic processes in Rancher.
* Added new tab `Processes` to admin ui
* Added components for various rows that will be displayed to allow for log recursion since the logs are recursive for an ambiguous count
* Added new css mixin for adding padding/margin util classes (e.g. `r-mt20` => `{margin-right: 20px;}`
N/A
???

Admin tabs update

---

app/admin-tab/processes/index/controller.js
app/admin-tab/processes/index/template.hbs
app/admin-tab/processes/process/controller.js
app/admin-tab/processes/process/route.js
app/admin-tab/processes/process/template.hbs
app/admin-tab/processes/route.js
app/admin-tab/processes/template.hbs
app/components/process-executions/component.js
app/components/process-executions/template.hbs
app/styles/layout.scss
package.json

After review with @ibuildthecloud I needed to make a few updates and fix a couple bugs. This PR addresses those.
* Update ember api store
* Add new search filters
* Add poller for child process view
* Add distinction between child process views
* Fix bug with expand all so it only expands its own children and not siblings children
* Increase indentation
* Limit results to most recent 100 results to increase performance
N/A
Fixes rancher/rancher#2167

Updates for Admin - Processes page

---

app/application/controller.js
app/applications-tab/catalog/controller.js
app/applications-tab/catalog/route.js
app/applications-tab/catalog/template.hbs
app/components/modal-catalog-launch/component.js
app/components/modal-catalog-launch/template.hbs
app/components/page-header/template.hbs
app/router.js
app/styles/app.scss
app/styles/bootstrap-tweak.scss
app/styles/catalog.scss
server/proxies/api.js
tests/unit/initializers/inject-router-test.js

Catalog is a new feature that allows users to easily launch common stacks with a couple clicks.
N/A
???
This can not launch until the new API has been integrated into the rancher API. When that is done we can remove the proxie that was added for the development of this feature.
The Image map helper can be removed as can a couple other hacks that have been added to the code.

New Page - Catalog [WIP]

---

app/components/modal-catalog-launch/component.js
app/components/modal-catalog-launch/template.hbs
app/styles/catalog.scss

* Added yml file preview to the modals
* Update the post call to create an environment to send variables/answers collection and uuid

Catalog updates

---

app/components/modal-catalog-launch/template.hbs

Fix typo to view Rancher Compose

---

app/components/modal-catalog-launch/component.js
app/components/modal-catalog-launch/template.hbs
app/styles/catalog.scss

* Moved preview under config and add collapse 
* Changed some styles for preview
* Add PRISM to `<code>`

Fix issues based on reviews

---

app/components/modal-catalog-launch/component.js
app/components/modal-catalog-launch/template.hbs

* Added support for new field `multiline`
* Added default values for answers and pass default values if answer is not changed
* Added more error checking

Add multiline support and some error checking

---

app/admin-tab/processes/index/controller.js
app/admin-tab/processes/index/template.hbs

Added logic for the following conditions
Search Button -
* Resource Type selected - Search button enabled
* Resource Type and ID - Search button enabled
* Resource Name - Search button enabled
Clear Button -
* Search executed - Clear button enabled
* Query strings exist - Clear button enabled
ID Input -
* Type Selected - Id input enabled
N/A
rancher/rancher#2325

updates logic for search running processes

---

app/components/lb-addtl-info/component.js
app/components/lb-addtl-info/template.hbs
app/components/service-addtl-info/template.hbs
app/environment/graph/view.js
app/styles/service-addtl-info.scss
app/templates/service-addtl-info.hbs

Fixing issues found in review.
* tighten the whole popup up for smaller screens
* add some contrast
* cleanup various cruft
N/A
N/A

Pop up fixes

---

app/components/form-volumes/template.hbs
app/container/index/route.js
app/container/labels/route.js
app/container/labels/template.hbs
app/container/ports/route.js
app/container/ports/template.hbs
app/container/template.hbs
app/container/volumes/route.js
app/container/volumes/template.hbs
app/host/template.hbs
app/router.js
app/styles/multi-stats.scss
tests/unit/container/labels/route-test.js
tests/unit/container/ports/route-test.js
tests/unit/container/volumes/route-test.js

* Add new tabs/routes labels, ports, and volumes
* fix styling

Updates to the container details page

---

app/hosts/new/ubiquity/controller.js

Need to get images on initial load, based on the zone of the first element in Location dropdown.
Signed-off-by: Justin Canington <justin.canington@nobistech.net>

images not populating on page load

---

app/components/lb-addtl-info/template.hbs
app/components/service-addtl-info/template.hbs
app/styles/header.scss
app/styles/service-addtl-info.scss
app/templates/alias-service-addtl-info.hbs
app/templates/ext-service-addtl-info.hbs

* rancher/rancher#2744
* rancher/rancher#2743
* rancher/rancher#2739
* Fix issues with user dropdown positioning

Resolves the following issues

---

app/components/info-multi-stats/component.js
app/components/spark-line/component.js
app/host/containers/template.hbs
app/styles/fonts.scss
app/styles/multi-stats.scss

* Fix colors on network graph
* Fix sparkline colors
* Fix icon issue on graph page

Fix performance issues on graphs.

---

app/components/edit-host/template.hbs
app/components/form-user-labels/component.js
app/environments/index/controller.js
app/environments/index/template.hbs
app/service/containers/route.js
app/styles/bootstrap-tweak.scss
app/utils/constants.js

Change all badges to have 0 border radius should resolve an issue in rancher/rancher#2745
update btn-default Added  background and font colors to bring the focus of default buttons up a little
Fix issue with trying to get instances that don't have instances
Add new user pref for sticky sort on stats page should resolve rancher/rancher#2760

Reskin issues

---

app/admin-tab/accounts/index/template.hbs
app/certificates/index/template.hbs
app/components/storagepool-section/template.hbs
app/containers/index/template.hbs
app/host/containers/template.hbs
app/host/storage/template.hbs
app/router.js
app/service/containers/template.hbs
app/service/index/route.js
app/service/links/route.js
app/service/links/template.hbs
app/service/template.hbs
app/settings/apikeys/template.hbs
app/settings/projects/template.hbs
app/settings/registries/template.hbs
app/styles/layout.scss
app/templates/ext-service-addtl-info.hbs

* For external services add host name/ips if present (rancher/rancher#2798)
* Add links to detailed service pages (rancher/rancher#2781)
* Add width to labels th to accomidate 'started-once' label (rancher/rancher#)

Updates to service details

---

app/styles/bootstrap-tweak.scss
app/styles/fonts.scss
app/styles/layout.scss

inconsistency on dropdowns and inputs resolved

resolving #2812

---

app/components/environment-header/template.hbs
app/components/host-pod/template.hbs

* Add clip class to stack names on the host display (rancher/rancher#2714)
* Add some padding to stack name dropdown so the name doesnt go behind the caret

Style changes

---

app/applications-tab/catalog/index/template.hbs
app/applications-tab/catalog/launch/route.js
app/components/new-catalog/component.js
app/components/new-catalog/template.hbs
app/components/upgrade-btn/component.js
app/utils/constants.js
app/utils/parse-externalid.js
bower.json
package.json

* Update catalog page to support new fields in the catalog api
* Update the upgrade button to support new fields in the catalog api and
* remove some hackery

Update the catalog UI to support the refactored catalog api.

---

app/admin-tab/settings/route.js
app/components/catalog-settings/component.js
app/components/host-settings/component.js
package.json

This should fix a few issues
New catalog entries not being saved (rancher/rancher#3005)
Not able to save the default api$host value (rancher/rancher#3011)
Fix issue with loading speeds (rancher/rancher#3009)
Add default value for VM setting

Fix error with setting catalog items

---

app/hosts/new/ubiquity/template.hbs

Signed-off-by: Justin Canington <justin.canington@nobistech.net>

Change Client ID to Reseller ID

---

app/components/modal-about/template.hbs
app/mixins/cattle-transitioning-resource.js
package.json

Tidy up of old URL's. @vincent99 now with less human errors too ;)

rancherio > rancher fixes

---

app/admin-tab/audit-logs/controller.js
app/admin-tab/audit-logs/route.js
app/admin-tab/audit-logs/template.hbs
app/components/modal-auditlog-info/component.js
app/helpers/auth-type.js
app/models/auditlog.js
app/utils/constants.js

This PR will deal with a few issues 
rancher/rancher#3091
rancher/rancher#3086
rancher/rancher#3074
rancher/rancher#3069

Fix a bunch of issues found during QA

---

app/admin-tab/audit-logs/template.hbs

Fix some issues around filter placement. They must have got messed up in my refactor.
(rancher/rancher#3111)

style fixes

---

app/admin-tab/audit-logs/template.hbs
app/components/identity-block/component.js

Changed the link-to from self to resource.
Added some logic to the identity-block component to display the identity external id if a name is not present.

Couple minor changes to audit log

---

app/admin-tab/accounts/index/template.hbs
app/admin-tab/auth/template.hbs
app/admin-tab/settings/template.hbs
app/applications-tab/catalog/index/template.hbs
app/certificates/index/template.hbs
app/components/environment-header/template.hbs
app/components/new-container/template.hbs
app/components/page-footer/template.hbs
app/containers/index/template.hbs
app/environments/index/template.hbs
app/environments/new/template.hbs
app/host/template.hbs
app/hosts/index/template.hbs
app/hosts/new/template.hbs
app/settings/projects/template.hbs
app/settings/registries/template.hbs
app/styles/growl.scss
app/styles/layout.scss
app/virtualmachines/index/template.hbs

styling growl error removing right- and left- dividers but adding relative margin helpers

dividers and growl

---

app/authenticated/help/controller.js
app/authenticated/help/route.js
app/authenticated/help/template.hbs
app/components/page-header/component.js
app/components/page-header/template.hbs
app/styles/components/_progress-bar.scss
app/styles/layout/_layout.scss
app/styles/vendors/_bootstrap-tweak.scss
app/utils/constants.js

Added dynamic content to help page
Cleaned up styles
Add logic around new setting (help.enabled) to be able to turn off the help page. If help page is disabled but you've got no host we'll fall back to old welcome screen.

Finalize Help Page

---

app/components/info-multi-stats/template.hbs
app/container/template.hbs
app/host/template.hbs
app/service/template.hbs
app/styles/app.scss
app/styles/components/_multi-stats.scss
app/styles/layout/_flex-box.scss
app/styles/layout/_layout.scss
app/virtualmachine/template.hbs

Added a new container-flex and col-flex to replace the weird multi stat container on hosts, vms, and container details pages. Flex works much better as it gives us a full height column with out a lot of hackery.

Fixing various style bugs

---

app/authenticated/controller.js
app/authenticated/help/controller.js
app/authenticated/help/route.js
app/authenticated/template.hbs
app/components/page-footer/template.hbs
app/components/page-header/template.hbs
app/services/settings.js
app/styles/layout/_flex-box.scss
app/styles/layout/_layout.scss

* fix the footer to hide rancher links when help is disabled
* move the download cli back to footer

Minor fixes that got borked in a rebase

---

app/styles/components/_multi-stats.scss
app/styles/components/_spark-line.scss
app/styles/layout/_flex-box.scss
app/styles/layout/_header.scss
app/styles/pages/_host.scss
app/styles/themes/_light.scss

few unthemed tables and nav on light

few unthemed tables and nav on light

---

app/initializers/polyfill-svg.js
package.json

http://jointjs.com/blog/get-transform-to-element-polyfill.html

Fix graph line rendering in Chrome 48+

---

app/components/action-menu/component.js
app/components/action-menu/template.hbs
app/components/add-subpod/component.js
app/components/container-dot/component.js
app/components/container-dot/template.hbs
app/components/container-subpod/component.js
app/components/container-subpod/template.hbs
app/components/host-pod/component.js
app/components/host-pod/template.hbs
app/components/tooltip-action-menu/component.js
app/components/tooltip-element/component.js
app/hosts/index/controller.js
app/hosts/index/template.hbs
app/mixins/grouped-instances.js
app/services/resource-actions.js
app/services/scrolling.js
app/services/tooltip.js
app/styles/components/_pod.scss
app/templates/fast-action-menu.hbs

* reworking the group/stack view
* removed the container view
* remove old styling

UI tweaks to host page layout

---

app/styles/themes/_dark.scss

dropdown fix up

---

app/services/user-theme.js

* Dont write the css node every halfhour if the theme has not changed
* Cancel auto update timer on theme switch
* I may have inadvertently fixed an issue where the theme was undefined, i was having trouble reproducing it but after changes were made i did not see it happen. 
(rancher/rancher#3544)
(rancher/rancher#3551)
(rancher/rancher#3546)

Updates to fix various bugs in the theme switching

---

app/components/action-menu/component.js
app/mixins/grouped-instances.js
app/mixins/tooltip.js
app/styles/components/_tooltip.scss

* Change tooltip to be position fixed to resolve issues around scrolling
* Fix issue with tooltips staying up when changing routes
* Fix tooltips staying up on the action menu when clicked
rancher/rancher#3464
rancher/rancher#3578

Fix various bugs in Tooltips

---

app/admin-tab/audit-logs/controller.js
app/admin-tab/audit-logs/route.js
app/admin-tab/processes/route.js
app/application/controller.js
app/authenticated/project/help/route.js
app/components/action-menu/component.js
app/components/columns-section/component.js
app/components/host-pod/template.hbs
app/components/modal-confirm-deactivate/component.js
app/components/modal-confirm-deactivate/template.hbs
app/components/page-header/component.js
app/components/page-header/template.hbs
app/components/stack-section/template.hbs
app/components/theme-toggle/component.js
app/components/theme-toggle/template.hbs
app/models/environment.js
app/models/project.js
app/models/service.js
app/router.js
app/services/resource-actions.js
app/services/user-theme.js
app/styles/components/_pod.scss
app/styles/layout/_layout.scss
app/templates/service-addtl-info.hbs
app/templates/tabs/admin-tab.hbs
app/templates/tabs/applications-tab.hbs
app/templates/tabs/infrastructure-tab.hbs
app/templates/tabs/k8s-tab.hbs

* Remove subpod collapse functionality
* Refactor theme toggler to use actions not click
* Add confirmation for deactivating stacks and service
* Add new hover over top nav -> display sub-nav functionality
* Refactor admin processes to use run.later rather then setInterval
* Fix right click issue on tooltips with action menus * Reset the resource-actions model so the next time a right click occurs the menu will show
rancher/rancher#3546
rancher/rancher#3532

General Bug Fixes

---

app/admin-tab/settings/controller.js
app/admin-tab/settings/route.js
app/admin-tab/settings/template.hbs
app/application/controller.js
app/components/catalog-settings/component.js
app/components/catalog-settings/template.hbs
app/components/dynamic-driver-settings/component.js
app/components/dynamic-driver-settings/template.hbs
app/components/host-settings/component.js
app/components/host-settings/template.hbs
app/components/modal-new-driver/component.js
app/components/modal-new-driver/template.hbs
app/components/save-cancel/component.js
app/components/save-cancel/template.hbs
app/components/virtual-machine-settings/component.js
app/components/virtual-machine-settings/template.hbs
app/mixins/cattle-transitioning-resource.js
app/models/machinedriver.js
app/router.js
app/styles/layout/_layout.scss
app/templates/save-cancel.hbs
ember-cli-build.js
package.json

* break individual sections into there own components and let them handle the saving of there own data
* Add new dynamic driver settings component

Refactor settings page

---

app/components/page-header/template.hbs
app/components/stack-section/template.hbs
app/styles/pages/_k8s.scss

and accessibility on info circle

k8s dropdown

---

app/admin-tab/processes/index/controller.js
app/admin-tab/processes/index/template.hbs
app/hosts/new/amazonec2/template.hbs
app/hosts/new/exoscale/template.hbs
app/styles/layout/_layout.scss
app/styles/vendors/_bootstrap-tweak.scss
app/styles/vendors/_power-select.scss

@westlywright will look at logic of actions between audit logs and processes

Process dropdown actions

---

app/models/volume.js

Addresses https://github.com/rancher/rancher/issues/3378
EDIT:
Now also addresses https://github.com/rancher/rancher/issues/3917

Don't show inactive mounts for volumes

---

app/components/action-menu-item/component.js
app/components/page-header/template.hbs

https://github.com/rancher/rancher/issues/3674

a11y: ability to switch environments

---

app/admin-tab/auth/github/controller.js
app/admin-tab/auth/github/template.hbs
app/admin-tab/processes/index/controller.js
app/admin-tab/processes/index/template.hbs
app/authenticated/route.js
app/components/container-subpod/component.js
app/components/container-subpod/template.hbs
app/components/new-catalog/template.hbs
app/components/stack-section/template.hbs
app/components/tooltip-action-menu/component.js
app/components/tooltip-action-menu/template.hbs
app/helpers/log-external-link.js
app/hosts/new/amazonec2/template.hbs
app/mixins/stripped-name.js
app/not-found/controller.js
app/not-found/route.js
app/not-found/template.hbs
app/router.js
app/services/access.js
app/styles/components/_multi-stats.scss
app/styles/components/_tooltip.scss
app/templates/tooltip-container-subpod.hbs

Remove some disabled properties to match the ux of audit-logs ux
(rancher/rancher#3306)
Add project url to catalog template if it exists
rancher/rancher#3897
Swap row link for name link in process logs table in prep for more changes coming
Add external links to resource type on Process Logs
Add 404 handler and route
rancher/rancher#1506
Add stack description on stack detail page
Also fix color issue with host descriptions
rancher/rancher#555
Remove tooltip from container-dot, add tooltip to host container name
rancher/rancher#1415
Add 10 min timer to authenticated to check for github auth token expire
rancher/rancher#255
Add link to rancher AMIs for amazon to ec2 add host
rancher/rancher#1520
Add option to use non-secure http for github enterprise auth
rancher/rancher#1410

GA Bugfixes 

---

app/components/delete-confirmation/component.js
app/components/delete-confirmation/template.hbs
app/components/input-command/component.js
app/components/new-catalog/template.hbs
app/hosts/new/custom/controller.js
app/hosts/new/custom/template.hbs
app/mixins/faster-links-and-menus.js
app/models/environment.js

Add CATTLE_AGENT_IP option to custom host generation
rancher/rancher#872
rancher/rancher#1601
Trigger body click on path change for fast-action-menu
rancher/rancher#3377
Add link to new project url on catalog items if project url exist
rancher/rancher#3897
Disable edit on deleted stacks
rancher/rancher#1547
Update term.js for paste support
rancher/rancher#2181
Add warning info to delete environment confirmation modal
rancher/rancher#2132
Fix issue with input-commands for new containers and the shell pattern matching
rancher/rancher#2692

GA Bugfixes V2

---

app/applications-tab/compose-services/index/template.hbs
app/catalog-tab/index/template.hbs
app/components/scheduling-rule-row/template.hbs
app/k8s-tab/namespace/pods/index/template.hbs
app/styles/pages/_catalog.scss

resolves https://github.com/rancher/rancher/issues/3995

add clip to resolve 3995

---

app/admin-tab/auth/github/controller.js
app/components/action-menu-item/component.js
app/components/container-subpod/template.hbs
app/components/delete-confirmation/component.js
app/components/delete-confirmation/template.hbs
app/components/new-catalog/template.hbs
app/components/process-execution-handler-rows/component.js
app/components/process-execution-handler-rows/template.hbs
app/components/process-execution-rows/component.js
app/components/process-execution-rows/template.hbs
app/components/process-executions/component.js
app/components/process-executions/template.hbs
app/models/template.js
app/services/resource-actions.js

Add init getters and refactor names to clarify logic in process-executions
In the process fix an issue with child rows only expanding 3 levels deep
rancher/rancher#3934
Add logic to handle Catalog projectUrl without protocols
rancher/rancher#3897
Add missing service
rancher/rancher#2132
Fix issue with scroll bars in terminals
rancher/rancher#4018
remove un-needed Ember.run the broken opening other action menus
rancher/rancher#3891
Add keypress enter logic to action menus
rancher/rancher#3674
Add container-dot component back to host -> sidekick
Fix issue with double protocol
rancher/rancher#1410

GA Bugs V3

---

app/hosts/new/custom/controller.js

GA Bugs V5

---

app/admin-tab/settings/controller.js
app/admin-tab/settings/route.js
app/admin-tab/settings/template.hbs
app/hosts/new/controller.js
app/hosts/new/route.js
app/hosts/new/template.hbs

Fix secondary back to hosts issue

---

app/components/copy-to-clipboard/component.js
app/services/resource-actions.js
app/styles/layout/_header.scss

Fix sub-nav route indicator to match body color
Fix issue with action menus causing firefox to scroll to bottom of page

GA Bugs V6

---

app/catalog-tab/index/template.hbs
app/catalog-tab/route.js
app/components/catalog-settings/template.hbs
app/components/new-catalog/template.hbs
app/components/page-header/component.js
app/styles/base/_colors.scss
app/styles/pages/_catalog.scss
app/templates/tabs/catalog-tab.hbs

Changes for catalog

---

app/components/copy-to-clipboard/template.hbs
app/components/tooltip-element/component.js
app/mixins/tooltip.js

Fix regression due to removed button class (derrrrrrrrrrrrrrp)
Fix tooltip issue with static width
Fix side issue with reseting tooltip opts when entering a new tooltip
rancher/rancher#4350
rancher/rancher#4216

Tooltip Fixes

---

app/models/host.js
app/models/machine.js

Fix a couple links to the new hosts page

---

app/admin-tab/auth/github/template.hbs
app/admin-tab/auth/localauth/template.hbs
app/admin-tab/processes/index/template.hbs
app/admin-tab/settings/template.hbs
app/components/catalog-settings/template.hbs
app/components/dynamic-driver-settings/template.hbs
app/components/host-settings/template.hbs
app/components/virtual-machine-settings/template.hbs
translations/en-us.yaml

Update admin processes page for i18n
Update admin settings page for i18n

i18n updates 

---

translations/en-us.yaml

Change identitity to identity in en-us.yaml

Fix a problem in en-us.yaml

---

app/admin-tab/audit-logs/template.hbs
app/catalog-tab/index/template.hbs
app/components/labels-section/template.hbs
app/components/machine/driver-azure/template.hbs
app/console/template.hbs
app/fail-whale/template.hbs
app/k8s-tab/kubectl/template.hbs
app/k8s-tab/namespace/pods/index/template.hbs
app/k8s-tab/namespace/pods/pod/template.hbs
app/k8s-tab/namespace/rcs/index/template.hbs
app/k8s-tab/namespace/rcs/rc/template.hbs
app/k8s-tab/namespace/services/index/template.hbs
app/k8s-tab/namespace/services/service/template.hbs
app/k8s-tab/namespaces/index/template.hbs
app/service/containers/template.hbs
app/service/links/template.hbs
app/service/ports/template.hbs
app/settings/projects/index/template.hbs
app/styles/layout/_header.scss
translations/en-us.yaml

this should fix quite a few empty translations as well.

More updates for I18N

---

app/admin-tab/auth/github/template.hbs
translations/en-us.yaml

Fix label authPage.github.notAuthenticated.ul.li3.text and add to en-us.yaml
Add noData: 'This container has no ports.' to en-us.yaml

Fix label authPage.github.notAuthenticated.ul.li3.text and add to en-us.yaml

---

app/components/info-multi-stats/template.hbs

Changed
infoMultiStats.storageSection._**storageSection**_.labelText -> infoMultiStats.storageSection.labelText.
It caused a problem.

Fixed Translate problem again.

---

README.md
app/fail-whale/controller.js
app/fail-whale/template.hbs
app/instance-initializers/intl.js
app/mixins/fallback-translations.js
app/not-found/controller.js
app/not-found/route.js
app/not-found/template.hbs
app/services/user-language.js
app/utils/constants.js
app/utils/intl/missing-message.js
config/ember-intl.js
tests/unit/mixins/fallback-translations-test.js
translations/en-us.yaml

Add static fall backs for error pages incase transitions dont load
update readme
add supported locales link to read me

Update intl to have a fall back langauge

---

app/components/page-header-environment/template.hbs
app/components/page-header/template.hbs
app/styles/layout/_header.scss
app/styles/vendors/_bootstrap-tweak.scss

0523issues

---

app/components/service-addtl-info/component.js
app/service/links/template.hbs
app/templates/service-addtl-info.hbs
translations/en-us.yaml

Refactor earlier fix for making service links a little clearer (rancher/rancher#2823)
Fix one more issue with containers count not zeroing (rancher/rancher#1703)

Minor refactors

---

app/utils/digitalocean-choices.js

Digital Ocean added a new region BLR today and it is not visible in Rancher UI

Added BLR region

---

translations/en-us.yaml
translations/pt-br.yaml

Translation to Portuguese Brazil (pt-BR).

Translation to Portuguese Brazil (pt-BR).

---

app/service/links/template.hbs
translations/en-us.yaml

Various bugs

---

app/components/environment-header/template.hbs
app/components/form-userdata/template.hbs
app/components/modal-confirm-deactivate/component.js
app/components/tooltip-link/component.js
app/components/upgrade-btn/component.js
app/environment/graph/view.js
translations/en-us.yaml

rancher/rancher#5107
Fix issue with graph view cutting svg off 
rancher/rancher#5145
translation fixes 
rancher/rancher#4942

Resolve route display and tool tip issue on stack details

---

app/components/storagepool-section/template.hbs
app/hosts/index/template.hbs
translations/en-us.yaml

remove storage pool detial link until detail page ready rancher/rancher#4527

Host view options broken rancher/rancher#5107

---

app/authenticated/route.js
app/components/labels-section/component.js
app/environment/graph/controller.js
app/environment/graph/template.hbs
app/environment/graph/view.js
app/fail-whale/route.js
app/host/containers/route.js
app/host/storage/template.hbs
app/hosts/index/controller.js
app/mixins/manage-labels.js
app/models/service.js
app/services/store-reset.js
app/storagepools/new-volume/template.hbs

rancher/rancher#5146
Fix issue with mis-declared variable
rancher/rancher#4329
Add safety check for no services on stacks graph view
rancher/rancher#5211
Refactor container hosts to reconnect socket when transition to new host view
rancher/rancher#4408
Fix incorrect session timeout message
rancher/rancher#3218
Add new observer for labels to refresh labels section component
rancher/rancher#4421
Refactor host index to correctly set the show system checkbox
rancher/rancher#5186
Ensure the store is cleared on error
rancher/rancher#5065

Add safety check for consumedServiceFor on a service incase of reset

---

translations/zh-Hans-CN.yaml

Chinese localization with 1.1-dev5 udpate

resync with master and update chinese localization file

---

app/mixins/hover-dropdowns.js
app/styles/app-dark.scss
app/styles/app-light.scss
app/styles/layout/_header.scss
app/styles/layout/_layout.scss
app/styles/layout/_lg-screen.scss
app/styles/layout/_md-screen.scss
app/styles/layout/_sm-screen.scss
app/styles/layout/_small-screen.scss
app/styles/layout/_xs-screen.scss
app/styles/vendors/_bootstrap-tweak.scss
vendor/bootswatch-cosmo/_variables.scss

reorganizing breakpoints into stylesheets and breaking at a smaller point

Breakpoints

---

app/utils/azure-choices.js

https://github.com/rancher/rancher/issues/5283

Fix for China North in Azure

---

app/components/page-header-environment/template.hbs
app/styles/layout/_header.scss
app/styles/vendors/_power-select.scss

matchTriggerWidth=false may theoretically help but the issues was the width:auto but pulling this thread may unravel someone else's sweater

power select rancher/rancher#4409

---

app/authenticated/route.js
app/container/route.js
app/container/volumes/template.hbs
app/models/container.js
app/models/mount.js
app/services/store-reset.js

add new shared containers logic to the mount model

---

app/login/controller.js
app/login/route.js
package.json

Correctly remove the farm class on route deactivate

---

app/components/snapshot-timeline/component.js

Fix issue with volume data but empty snapshot array

---

app/admin-tab/machine/controller.js
app/admin-tab/machine/template.hbs
app/components/info-multi-stats/template.hbs
app/container/template.hbs
app/host/template.hbs
app/mixins/hover-dropdowns.js
app/styles/pages/_catalog.scss
app/virtualmachine/template.hbs

update machine drivers (rancher/rancher#5156)

Update remaining details pages

---

app/components/new-container/component.js
app/components/new-container/template.hbs

Fix sidekick volume bug

---

app/admin-tab/machine/controller.js
app/catalog-tab/index/controller.js
app/catalog-tab/launch/route.js
app/catalog-tab/route.js
app/components/form-volumes/component.js
app/host/containers/template.hbs
app/mixins/catalog-resource.js
app/service/new/route.js
app/services/catalog-service.js
app/styles/components/_multi-stats.scss
app/styles/layout/_md-screen.scss

rancher/rancher#5554
rancher/rancher#3914
rancher/rancher#5737

Refactor catalog fetching into service

---

translations/en-us.yaml

Update link text for kubectl download text

---

app/components/machine/driver-azure/component.js
app/components/machine/driver-azure/template.hbs
app/utils/azure-choices.js
translations/en-us.yaml

caveats:
This should not be merged into master until @wlan0 puts his PR in for the actual driver upgrade
This will not work until the azureConfig schema is updated to reflect the image change to
canonical:UbuntuServer:16.04.0-LTS:latest

[WIP] Adds support for azure machine driver v0.8

---

app/admin-tab/machine/controller.js
app/application/route.js
app/components/machine/driver-amazonec2/component.js
app/components/machine/driver-amazonec2/template.hbs
app/components/machine/driver-azure/template.hbs
app/components/machine/driver-exoscale/template.hbs
app/helpers/include.js
app/styles/layout/_layout.scss
translations/en-us.yaml

Machine update wo GitHub

---

app/components/machine/driver-amazonec2/component.js

Related to https://github.com/rancher/machine/pull/11

driver-amazonec2: update region list to match the machine driver

---

app/admin-tab/auth/controller.js
app/admin-tab/auth/github/controller.js
app/admin-tab/auth/github/route.js
app/admin-tab/auth/github/template.hbs
app/admin-tab/route.js
app/authenticated/route.js
app/components/identity-block/component.js
app/components/input-identity/component.js
app/components/input-identity/template.hbs
app/components/machine/driver-azure/component.js
app/components/machine/driver-azure/template.hbs
app/components/modal-about/component.js
app/initializers/auth-store.js
app/instance-initializers/auth-store.js
app/services/access.js
app/services/github.js
config/environment.js
server/proxies/api.js

This should not be merged until @prachidamle opens/merges her PR for backend service changes.

Update github auth to use new v1-auth service

---

app/admin-tab/auth/shibboleth/controller.js
app/admin-tab/machine/controller.js
app/admin-tab/machine/route.js
app/admin-tab/machine/template.hbs
app/components/api-field/component.js
app/components/form-scheduling/template.hbs
app/components/machine/driver-azure/component.js
app/components/modal-confirm-deactivate/template.hbs
app/components/modal-container-stop/component.js
app/components/modal-container-stop/template.hbs
app/components/modal-shell/component.js
app/components/view-edit-project/component.js
app/container/networking/template.hbs
app/host/template.hbs
app/models/container.js
app/service/links/template.hbs
app/styles/pages/_stack.scss
translations/en-us.yaml

Driver upgrade options should not be visible if the state is inactive
(rancher/rancher#6186)
Resolve issues with catalog drivers and refreshing
(rancher/rancher#6184)
issue with erroneous verbiage
(rancher/rancher#6178
issue whe svg z-index blocking dropdown
(rancher/rancher#5882)
bug in azure driver
Labels show up correctly on container details
(rancher/rancher#5650)
Remove old code
(rancher/rancher#6248)
Move no rules verbiage to right location
(rancher/rancher#5641)
Allow users to disable esc to close in modals
(rancher/rancher#6302)
Handle empty allowedIdentities field for shibboleth
add new modal stop component to container stops
rancher/rancher#6214

Driver upgrade option removed on state

---

app/admin-tab/machine/template.hbs
app/models/machinedriver.js

Add method to retrieve icons for activated cat drivers

---

app/components/form-security/component.js
app/components/limit-parameters/component.js
app/components/modal-shell/component.js
app/initializers/app.js
app/mixins/driver.js
app/mixins/hover-dropdowns.js
app/styles/pages/_stack.scss

Fix init of memory limit value on hosts
rancher/rancher#6548
Preserve memory reservation value on clone
rancher/rancher#6549
Fix missing grid lines
rancher/rancher#6425
Update driver mixin for new name fields
rancher/rancher#6313
inject ember-shortcuts to components to disable shift+L in the shell

resolve issues with touch laptops

---

app/components/lb-addtl-info/component.js
app/components/lb-addtl-info/template.hbs
app/components/machine/driver-digitalocean/component.js
app/components/page-header-environment/template.hbs
app/components/upgrade-btn/template.hbs
app/mixins/hover-dropdowns.js
app/mixins/subscribe.js
app/mixins/upgrade-component.js
app/service/template.hbs
app/styles/layout/_header.scss
app/styles/layout/_sm-screen.scss
translations/en-us.yaml

rancher/rancher#6553
Refactor env dropdown for mobile compat
rancher/rancher#5891
Add template version to stack upgrade button tooltip
rancher/rancher#5619

fix load balancer details and links tab

---

app/mixins/upgrade-component.js

Refactor reference for this vs obj in ugrade btn

---

app/admin-tab/machine/template.hbs
app/components/action-menu/template.hbs
app/components/container-dot/template.hbs
app/components/container-subpod/template.hbs
app/components/copy-to-clipboard/template.hbs
app/components/input-text-file/template.hbs
app/components/k8s/stack-section/template.hbs
app/components/page-header/template.hbs
app/components/snapshot-section/template.hbs
app/components/snapshot-timeline/template.hbs
app/components/stack-section/template.hbs
app/components/storagepool-section/template.hbs
app/components/tooltip-element/component.js
app/components/tooltip-link/template.hbs
app/components/upgrade-btn/template.hbs
app/host/template.hbs
app/mixins/upgrade-component.js

add check for string type

---

app/mixins/upgrade-component.js

Changed the type check to check for string or number. In the case that its neither the tooltip will not be displayed per discussion with @vincent99 
rancher/rancher#6653

refactor type check

---

app/components/schema/input-multiline/component.js

Helps when editing env vars, etc.

Monospace multiline inputs

---

app/utils/packet-choices.js

Added new Packet Tokyo region support and I'll be check region code gap after GA released of Tokyo region.

WIP: Add new Packet region(Tokyo)

---

app/bulk-action-handler/service.js
app/components/container-row/component.js
app/components/container-row/template.hbs
app/components/modal-container-stop/component.js
app/components/modal-container-stop/template.hbs
app/containers/index/controller.js
app/containers/index/template.hbs
app/host/containers/template.hbs
app/mixins/cattle-transitioning-resource.js
app/models/container.js
app/service/containers/template.hbs
app/styles/app-dark.scss
app/styles/app-light.scss
app/styles/components/_sortable.scss
app/styles/layout/_sm-screen.scss
app/utils/constants.js
app/virtualmachines/index/template.hbs
tests/unit/bulk-action-handler/service-test.js

will need the review, merge, and release of this pr 
https://github.com/rancher/lacsso/pull/6

Add sortable searchable paged tables lacsso comp

---

app/components/action-menu/template.hbs
app/components/confirm-delete/component.js
app/components/confirm-delete/template.hbs
app/components/container-row/component.js
app/components/container-row/template.hbs
app/containers/index/controller.js
app/containers/index/template.hbs
app/host/containers/template.hbs
app/service/containers/template.hbs
app/styles/components/_sortable.scss
app/virtualmachines/index/template.hbs
translations/en-us.yaml

Address issues found during qa

---

app/components/container-row/template.hbs
app/components/container-subpod/template.hbs
app/components/spark-line/component.js
app/components/tooltip-action-menu/component.js

rancher/rancher#7154
add tooltip back to sparklines
rancher/rancher#7089

Add details and action menu to host tooltip

---

app/bulk-action-handler/service.js
app/utils/constants.js

Add altActions to bulk actions

---

app/components/modal-welcome/template.hbs

Links were updated in https://github.com/rancher/ui/commit/36d83bf551e1219328cd3e32da90607a566bbec1 but welcome popup has been forgotten

Resolve telemetry link from docsBase for welcome popup

---

server/caas/registration/api.js

Check password active before finishing account

---

app/templates/host/cloud/browse.hbs
translations/en-us.yaml

Forgot to include this on the previous PR

Add link to old rancher hosts page

---

app/components/container-shell/component.js
app/components/container-shell/template.hbs
app/components/modal-shell/component.js
app/console/template.hbs
app/models/container.js
app/styles/components/_container-shell.scss
app/utils/xterm-fit-addon.js
ember-cli-build.js
package.json

make shell larger and resizable.
xterm has been upgraded for bug fix and inserting international (including Chinese, Japanese, Korean) characters using IME input with keyboard.

upgrade xterm and make container shell larger

---

app/components/add-host-template/component.js
app/components/add-host-template/template.hbs
app/components/cloud-host-add-or-edit/component.js
app/components/cloud-host-add-or-edit/template.hbs
app/hosts/container-cloud/add/route.js
app/hosts/container-cloud/add/template.hbs
app/hosts/route.js
app/models/hosttemplate.js

Adds the hostTemplate functionality to new hosts page.

New cloud dev

---

translations/en-us.yaml

https://github.com/rancher/rancher/issues/8548

Evacutate -> Evacuate

---

app/container/template.hbs

Add physical attributes to service

---

translations/zh-hans.yaml

Chinese UI Translation Update

---

app/components/caas-login/component.js
app/components/caas-login/template.hbs
app/login/index/controller.js
app/login/index/template.hbs
app/signup/controller.js
app/signup/route.js
app/signup/template.hbs
app/verify-reset-password/route.js
server/caas/registration/api.js
server/util/util.js
translations/en-us.yaml

Bug fixes Signup and Login

---

app/components/machine/driver-azure/template.hbs
app/utils/azure-choices.js

According to Sizes provided by china region, I added Basic group for user to select, and grouped the sizes to make it more friendly for user.
Just like screenshot below

enhance Azuer Machine Driver to support more sizes

---

translations/ja-jp.yaml

Update Japanese translations with newest resources.

Update translation for Japanese

---

app/admin-tab/auth/activedirectory/controller.js
app/templates/ldap-config.hbs
package.json
translations/en-us.yaml

Change AD edit test flow

---

app/admin-tab/auth/activedirectory/controller.js
app/admin-tab/auth/activedirectory/route.js
app/admin-tab/auth/openldap/controller.js
app/admin-tab/auth/openldap/route.js
app/templates/ldap-config.hbs

Revert "Revert Active Directory auth service switch"

---

app/components/form-env-var/template.hbs
app/models/launchconfig.js
app/models/secondarylaunchconfig.js
app/models/stack.js
app/service/controller.js
app/service/route.js
app/service/template.hbs
translations/en-us.yaml

Sidekick details

---

app/components/machine/driver-amazonec2/template.hbs
app/models/amazonec2config.js
translations/en-us.yaml

[1.6] Allow users to enter ec2 tags for new ec2 machines

---

app/components/machine/driver-aliyunecs/component.js
app/components/machine/driver-aliyunecs/template.hbs
translations/en-us.yaml
translations/fa-ir.yaml
translations/fr-fr.yaml
translations/hu-hu.yaml
translations/ja-jp.yaml
translations/zh-hans.yaml

fixed bug of https://github.com/rancher/rancher/issues/9575
related pr is:
https://github.com/rancher/ui/pull/1316

fix bug of https://github.com/rancher/rancher/issues/9575

---

app/components/new-secret/component.js
app/templates/ldap-config.hbs

Fix encoding on secrets - Backport rancher/rancher#7670

---

app/components/host-pod/template.hbs

related issue [[Feature Request] IP address copy on click](https://github.com/rancher/rancher/issues/7515)

[2.0]Support copy host ip to the clipboard in box and dot views

---

app/components/new-select/component.js

[related issue](https://github.com/rancher/rancher/issues/5762)

Trigger change event after render for new-select

---

app/container/template.hbs
app/helpers/linkify.js
app/service/template.hbs
app/stack/index/template.hbs
app/volume/template.hbs
package.json
yarn.lock

[related issue 5282](https://github.com/rancher/rancher/issues/5282)

Show links in stack description

---

app/components/container/new-edit/component.js
app/components/container/new-edit/template.hbs
app/components/form-metadata/component.js
app/components/form-metadata/template.hbs
app/components/json-editor/component.js
app/components/json-editor/template.hbs
app/styles/_rancher.scss
app/styles/components/_json-editor.scss
ember-cli-build.js
translations/en-us.yaml
vendor/json-sanitizer/LICENSE.txt
vendor/json-sanitizer/NOTICE.txt
vendor/json-sanitizer/json-sanitizer.js

[Related issue 2243](https://github.com/rancher/rancher/issues/2243)
Before,
After focus out,

Expose metadata field in add service and edit service pages

---

app/authenticated/project/controller.js
app/hosts/index/controller.js
app/utils/constants.js

[rancher/rancher#9952](https://github.com/rancher/rancher/issues/9952)

put view choice in user preference

---

app/authenticated/clusters/cluster/import/controller.js
app/authenticated/clusters/cluster/import/template.hbs
app/components/cluster-welcome/template.hbs
app/components/container-logs/template.hbs
app/components/container/form-service-links/component.js
app/components/form-stickiness/template.hbs
app/components/host-row/template.hbs
app/components/modal-host-evacuate/template.hbs
app/components/modal-root/component.js
app/components/modal-wechat/component.js
app/components/new-edit-cluster/template.hbs
app/components/page-footer/template.hbs
app/components/settings/host-registration/template.hbs
app/container/template.hbs
app/hosts/index/controller.js
app/k8s/template.hbs
app/service/template.hbs
app/stack/index/route.js
translations/en-us.yaml
translations/zh-hans.yaml

[rancher/rancher#9975](https://github.com/rancher/rancher/issues/9975)
[rancher/rancher#9976](https://github.com/rancher/rancher/issues/9976)
[rancher/rancher#9977](https://github.com/rancher/rancher/issues/9977)

Update Chinese i18n file and some bug fixes

---

app/components/machine/driver-aliyunecs/component.js
app/components/machine/driver-aliyunecs/template.hbs
translations/en-us.yaml
translations/zh-hans.yaml

Add validation for name, access key, access secret and ssh password.
Add selection for region, instance type, and disk category.
Fixed following issue.
https://github.com/rancher/rancher/issues/9575
https://github.com/rancher/rancher/issues/9778
https://github.com/rancher/rancher/issues/9787
@Tracy1994 @yasker

[1.6] Add enhancement for aliyunecs driver.

---

app/components/machine/driver-otc/component.js

This PR should probably be merged as well 
https://github.com/rancher/cattle/pull/2405

Fix bug with error message from OTC driver

---

app/mixins/sortable-base.js

[rancher/rancher#9656](https://github.com/rancher/rancher/issues/9656)

Fix sortable table issue

---

app/components/webhook/new-receiver/component.js
app/registries/new/controller.js

[rancher/rancher#3706](https://github.com/rancher/rancher/issues/3706)

Focus the first field for add registry and webhook page

---

app/mixins/subscribe.js
app/services/growl.js
app/utils/constants.js
app/utils/socket.js
translations/en-us.yaml
translations/zh-hans.yaml

[rancher/rancher#7389](https://github.com/rancher/rancher/issues/7389)

Show proper growl when websocket connection failed.

---

app/components/upgrade-dropdown/template.hbs

https://github.com/rancher/rancher/issues/9786
This PR is used to be fix the 2.0 issue

Fix bug with error page from Up to date button (2.0)

---

app/components/new-catalog/component.js

[rancher/rancher#6470](https://github.com/rancher/rancher/issues/6470)

[1.6]Clear selected template Url when catalog changed

---

app/authenticated/route.js
app/utils/azure-choices.js

https://github.com/rancher/rancher/issues/4049
https://github.com/rancher/rancher/issues/10073

[1.6]Bug Fix

---

app/authenticated/route.js
app/utils/azure-choices.js

https://github.com/rancher/rancher/issues/4049
https://github.com/rancher/rancher/issues/10073

[2.0]Bug Fix

---

app/application/route.js
app/login/index/controller.js
app/login/index/template.hbs
translations/en-us.yaml

https://github.com/rancher/rancher/issues/1307

Show third-party access limitations warning for github auth

---

app/mixins/cattle-transitioning-resource.js
app/templates/ldap-config.hbs
translations/en-us.yaml

https://github.com/rancher/rancher/issues/4510

Show proper error message for fields in ldap auth setup page

---

app/components/machine/driver-amazonec2/component.js
app/components/machine/driver-amazonec2/template.hbs

https://github.com/rancher/rancher/issues/5029

Show AWS network tags when adding a host

---

app/mixins/cattle-transitioning-resource.js
app/templates/ldap-config.hbs
translations/en-us.yaml

https://github.com/rancher/rancher/issues/4510

[1.6]Show proper error message for fields in ldap auth setup page

---

crowdin.yml
scripts/update-translations

https://github.com/rancher/rancher/issues/10078
```
Step 1. Uploading en-us.yaml to Crowdin ...
File 'ui.yaml' - SKIPPED
Step 2. Build and download the latest translations build ...
Building ZIP archive with the latest translations for 'sq' - OK
Extracting: '/sq-AL.yaml'
Building ZIP archive with the latest translations for 'zh-CN' - OK
Extracting: '/zh-hans.yaml'
Building ZIP archive with the latest translations for 'zh-TW' - OK
Extracting: '/zh-hant.yaml'
Building ZIP archive with the latest translations for 'zh-HK' - OK
Extracting: '/zh-HK.yaml'
Building ZIP archive with the latest translations for 'ak' - OK
Extracting: '/ak-GH.yaml'
Step 3. Checking translations status
**** Retrieving: /opt/translations/status.xml ****
**** Processing: /opt/translations/status.xml ****
There are 2 …
```

Add the script for updating i18n files

---

app/components/edit-host/component.js
app/components/edit-host/template.hbs
app/components/form-user-labels/component.js
app/components/form-user-labels/template.hbs
app/mixins/manage-labels.js
app/utils/constants.js
package.json

https://github.com/rancher/rancher/issues/10133

[1.6]Make per-host-subnet as readonly label on edit host page

---

app/components/form-user-labels/component.js
app/components/form-user-labels/template.hbs
app/components/modal-edit-host/component.js
app/components/modal-edit-host/template.hbs
app/mixins/manage-labels.js
app/utils/constants.js

https://github.com/rancher/rancher/issues/10133

[2.0] Make per-host-subnet as readonly label on edit host page

---

app/mixins/subscribe.js
app/utils/socket.js

Reverts rancher/ui#1414 -- this shows the growl every time you switch projects now..

Revert "Show disconnected growl when socket closing"

---

app/components/new-catalog/component.js
app/components/new-catalog/template.hbs

https://github.com/rancher/rancher/issues/6470

Fix flash issue when switch catalog through drop-down

---

app/components/machine/driver-aliyunecs/component.js
app/utils/validate-dns.js
tests/unit/utils/validate-dns-test.js
translations/en-us.yaml
translations/zh-hans.yaml

Because Aliyun changes his rules of the instance hostname, we are going to fit his rules.
Fix the reopen issue https://github.com/rancher/rancher/issues/9778.
@yasker @kingsd041

Hostname Validation Change for Aliyun Machine Driver

---

app/components/graph-area/component.js
app/components/info-multi-stats/component.js
app/components/info-multi-stats/template.hbs
app/components/svg-gradients/component.js
app/styles/_rancher.scss
app/styles/components/_graph-area.scss
app/utils/graph-area.js
app/utils/graph-tooltip.js
translations/en-us.yaml

[rancher/rancher#9932](https://github.com/rancher/rancher/issues/9932)

Add graph area component

---

app/admin-tab/auth/github/route.js

https://github.com/rancher/rancher/issues/10247

Fix github enterprise auth issue

---

package.json

https://github.com/rancher/rancher/issues/10237

Make modal in the top of screen

---

app/components/container-shell/component.js
app/components/container-shell/template.hbs
app/components/modal-shell/component.js
app/console/template.hbs
app/k8s-tab/kubectl/template.hbs
app/models/container.js
app/styles/components/_container-shell.scss
app/styles/layout/_layout.scss
app/swarm-tab/console/template.hbs
app/utils/xterm-fit-addon.js
ember-cli-build.js
package.json

backport https://github.com/rancher/ui/pull/1079
https://github.com/rancher/rancher/issues/2182

Upgrade xterm and make container shell resizable

---

app/k8s-tab/kubectl/controller.js

https://github.com/rancher/rancher/issues/7937

Explicit port 80 in kubectl config

---

app/components/container-shell/template.hbs
app/styles/components/_container-shell.scss

https://github.com/rancher/rancher/issues/10313

Fix shell selecting lines issue

---

app/components/edit-service/component.js
app/components/new-container/component.js
app/components/schema/input-service/component.js
app/models/service.js

https://github.com/rancher/rancher/issues/10281

[WIP] Fix the issue that cross environment links break UI

---

app/authenticated/route.js
app/components/form-balancer-rules/template.hbs

https://github.com/rancher/rancher/issues/10473

Load regions if the region schema exists

---

app/styles/base/_helpers.scss
lib/global-admin/addon/components/new-edit-role/component.js
lib/global-admin/addon/components/new-edit-role/template.hbs
lib/global-admin/addon/components/other-role-row/component.js
lib/global-admin/addon/components/other-role-row/template.hbs
lib/global-admin/addon/components/policy-row/component.js
lib/global-admin/addon/components/policy-row/template.hbs
lib/global-admin/addon/components/role-rule-row/component.js
lib/global-admin/addon/components/role-rule-row/template.hbs
lib/global-admin/addon/routes.js
lib/global-admin/addon/security/policies/index/controller.js
lib/global-admin/addon/security/policies/index/template.hbs
lib/global-admin/addon/security/roles/detail/route.js
lib/global-admin/addon/security/roles/detail/template.hbs
lib/global-admin/addon/security/roles/index/controller.js
lib/global-admin/addon/security/roles/index/template.hbs
lib/global-admin/addon/security/roles/new/route.js
lib/shared/addon/components/searchable-select/component.js
lib/shared/addon/components/searchable-select/template.hbs
translations/en-us.yaml

https://github.com/rancher/rancher/issues/10478

Bug fix for role page

---

app/components/new-balancer/component.js
app/models/machinedriver.js
translations/en-us.yaml

https://github.com/rancher/rancher/issues/10501
rancher/rancher#10457

Fix the issue that it shows invalid weight when it is not a region rule

---

app/components/machine/driver-custom/component.js

refer to bug https://github.com/rancher/rancher/issues/10521

Fix add labels problem when adding host in Windows environment

---

app/components/edit-projecttemplate/component.js

https://github.com/rancher/rancher/issues/10510

Force IPsec to be enabled when clicking back from windows

---

app/authenticated/cluster/import/controller.js

Fix https://github.com/rancher/rancher/issues/10710

There should be a restriction to access import page of active cluster.

---

app/components/form-engine-opts/component.js

https://github.com/rancher/rancher/issues/10730

[1.6]Update docker install url

---

app/components/new-balancer/component.js

https://github.com/rancher/rancher/issues/10769

[1.6]Change the default value of non-region port rule from 0 to 1

---

app/components/new-balancer/component.js
app/components/stack-graph/component.js
package.json

https://github.com/rancher/rancher/issues/10769

[1.6]Set weight only for region rule

---

app/styles/components/_container-shell.scss
package.json

https://github.com/rancher/rancher/issues/10816

[1.6]Fix kubectl shell issue

---

app/components/webhook/new-receiver/component.js
app/components/webhook/service-upgrade-config/component.js
app/components/webhook/service-upgrade-config/template.hbs
translations/en-us.yaml
translations/zh-hans.yaml

https://github.com/rancher/rancher/issues/10654
https://github.com/rancher/rancher/issues/10639

[1.6]Webhhook

---

app/utils/azure-choices.js

https://github.com/rancher/rancher/issues/10943

[1.6]Update azure regions

---

app/components/form-balancer-rules/component.js
package.json

[1.6]Region

---

lib/global-admin/addon/clusters/new/cloud/controller.js
lib/global-admin/addon/clusters/new/cloud/route.js
lib/global-admin/addon/clusters/new/cloud/template.hbs
lib/global-admin/addon/components/driver/driver-azureaks/component.js
lib/global-admin/addon/components/driver/driver-azureaks/template.hbs
lib/global-admin/addon/components/driver/driver-googlegke/component.js
lib/global-admin/addon/components/driver/driver-googlegke/template.hbs
lib/shared/addon/components/new-select/component.js
lib/shared/addon/utils/azure-choices.js
lib/shared/app/utils/azure-choices.js
translations/en-us.yaml

@vincent99 up to you if you want to merge this now or wait for @nathan-jenan-rancher to put in a fix for the driver and talking to azure proper

WIP Azure Cloud Add

---

lib/global-admin/addon/clusters/new/rke/controller.js
lib/global-admin/addon/clusters/new/rke/route.js
lib/global-admin/addon/clusters/new/rke/template.hbs
translations/en-us.yaml

https://github.com/rancher/rancher/issues/10896

Clean up for RKE

---

app/components/machine/driver-exoscale/component.js
app/components/machine/driver-exoscale/template.hbs
translations/en-us.yaml
translations/fr-fr.yaml

Hi Rancher,
A little update to the exoscale driver letting the customer choosing a data-center as well as a template.
Cheers,

exoscale: zones and templates

---

app/components/schema/input-secret/component.js
app/components/schema/input-service/component.js
package.json

https://github.com/rancher/rancher/issues/11320

[1.6] Fix catalog question issue and Bump version

---

app/models/pod.js
app/styles/components/_container-shell.scss
app/styles/pages/_container.scss
lib/shared/addon/components/container-logs/component.js
lib/shared/addon/components/container-logs/template.hbs
lib/shared/addon/components/container-shell/component.js
lib/shared/addon/components/container-shell/template.hbs
lib/shared/addon/components/modal-container-logs/component.js

https://github.com/rancher/rancher/issues/11051

Fix pod exec and log issue

---

app/apps-tab/index/route.js
app/models/app.js
lib/global-admin/addon/catalog/controller.js
lib/global-admin/addon/catalog/template.hbs
lib/shared/addon/components/common-mark/component.js
lib/shared/addon/components/common-mark/template.hbs
lib/shared/addon/components/new-catalog/component.js
lib/shared/addon/components/page-header/template.hbs
lib/shared/addon/components/view-edit-project/template.hbs
lib/shared/addon/utils/constants.js
lib/shared/addon/utils/parse-externalid.js
lib/shared/app/utils/parse-externalid.js
translations/en-us.yaml

I was unsure if we'd ever support our old catalog style again so I didn't want to remove all that logic. If we won't then I'll remove all the old logic in a new pr. i'm still cleaning the catalog stuff up so it wont be long.

Tech preview

---

app/authenticated/cluster/notifier/index/route.js
app/models/notifier.js
lib/alert/addon/components/alert-table/component.js
lib/alert/addon/components/alert-table/template.hbs
lib/alert/addon/components/alert/form-cluster-rules/template.hbs
lib/alert/addon/components/cluster-alert-row/component.js
lib/alert/addon/components/cluster-alert-row/template.hbs
lib/alert/addon/components/project-alert-row/component.js
lib/alert/addon/components/project-alert-row/template.hbs
lib/alert/addon/models/clusteralert.js
lib/alert/addon/models/projectalert.js
lib/alert/addon/new/route.js
lib/alert/translations/en-us.yaml
lib/logging/addon/mixins/target-elasticsearch.js
lib/shared/addon/components/notifier/modal-new-edit/component.js
lib/shared/addon/components/notifier/modal-new-edit/template.hbs
lib/shared/addon/components/notifier/notifier-row/component.js
lib/shared/addon/components/notifier/notifier-row/template.hbs
lib/shared/addon/components/notifier/notifier-table/component.js
lib/shared/addon/components/notifier/notifier-table/template.hbs
translations/en-us.yaml

Fixed issues:
https://github.com/rancher/rancher/issues/11581
https://github.com/rancher/rancher/issues/11580
https://github.com/rancher/rancher/issues/11578
https://github.com/rancher/rancher/issues/11577
https://github.com/rancher/rancher/issues/11574
https://github.com/rancher/rancher/issues/11573
https://github.com/rancher/rancher/issues/11572
https://github.com/rancher/rancher/issues/11568
https://github.com/rancher/rancher/issues/11567

Alert update & bug fixes

---

lib/alert/addon/components/alert-table/component.js
lib/alert/addon/components/alert-table/template.hbs
lib/alert/addon/components/alert/form-cluster-rules/component.js
lib/alert/addon/components/alert/form-cluster-rules/template.hbs
lib/alert/addon/components/alert/form-project-rules/component.js
lib/alert/addon/components/alert/form-project-rules/template.hbs
lib/alert/addon/components/alert/form-recipients/component.js
lib/alert/addon/components/alert/new-edit/template.hbs
lib/alert/addon/components/cluster-alert-row/component.js
lib/alert/addon/components/cluster-alert-row/template.hbs
lib/alert/addon/components/project-alert-row/component.js
lib/alert/addon/components/project-alert-row/template.hbs
lib/alert/addon/index/route.js
lib/alert/addon/index/template.hbs
lib/alert/addon/mixins/model-alert.js
lib/alert/addon/mixins/notifier.js
lib/alert/addon/new/route.js
lib/shared/addon/components/notifier/notifier-table/component.js

Fixed:
https://github.com/rancher/rancher/issues/11605
https://github.com/rancher/rancher/issues/11597
https://github.com/rancher/rancher/issues/11596
https://github.com/rancher/rancher/issues/11576
https://github.com/rancher/rancher/issues/11575
https://github.com/rancher/rancher/issues/11574

Alert: Fixed sorting & searching and filtering bugs.

---

lib/alert/addon/components/alert/form-cluster-rules/template.hbs
lib/alert/addon/components/alert/form-project-rules/template.hbs

Fixed:
https://github.com/rancher/rancher/issues/11637

Added back Accidentally removed warning radio option in Add Alert

---

lib/alert/addon/components/alert-table/component.js
lib/alert/addon/components/cluster-alert-row/template.hbs
lib/alert/addon/components/project-alert-row/template.hbs
lib/alert/addon/mixins/model-alert.js
lib/logging/addon/components/logging/new-edit/component.js
lib/logging/addon/components/logging/new-edit/template.hbs
lib/logging/addon/components/logging/target-kafka/component.js
lib/logging/addon/components/logging/target-kafka/template.hbs
lib/logging/addon/components/logging/target-syslog/component.js
lib/logging/addon/logging/route.js
lib/logging/addon/mixins/logging-model.js
lib/logging/translations/en-us.yaml
lib/shared/addon/components/notifier/modal-new-edit/component.js
lib/shared/addon/components/notifier/notifier-table/component.js

- Improved alerts, notifiers sorting.
- Validate notifier before sending a notifier test request.
- Removed hardcoded endpoints and handle logging  Elasticsearch/Kibana deploying state.
- Updated logging.
Related issues:
https://github.com/rancher/rancher/issues/11597
https://github.com/rancher/rancher/issues/11581
https://github.com/rancher/rancher/issues/11571
https://github.com/rancher/rancher/issues/11610

Alert/Logging improvements & bugfix

---

app/app.js
lib/pipeline/addon/components/pipeline-jobs-table/component.js
lib/pipeline/addon/components/pipeline-jobs-table/template.hbs
lib/pipeline/addon/components/pipeline-steps/component.js
lib/pipeline/addon/engine.js
lib/pipeline/addon/pipelines/controller.js
lib/pipeline/addon/pipelines/route.js
lib/pipeline/addon/pipelines/template.hbs
lib/pipeline/addon/services/pipeline.js
lib/pipeline/addon/settings/route.js
lib/pipeline/translations/en-us.yaml
lib/shared/addon/components/containers-header/component.js
lib/shared/addon/components/containers-header/template.hbs

Fix bugs
rancher/rancher#11700
rancher/rancher#11733
rancher/rancher#11745
rancher/rancher#11744

Pipeline Bug fix

---

lib/alert/addon/components/alert/form-project-rules/component.js
lib/alert/addon/components/alert/form-project-rules/template.hbs
lib/alert/addon/components/project-alert-row/template.hbs
lib/alert/addon/models/projectalert.js
lib/alert/addon/new/route.js

Related issue:
https://github.com/rancher/rancher/issues/11768
[WIP] Backend need to do the update to support this.

Remove workload types

---

lib/shared/addon/components/form-members/component.js
lib/shared/addon/components/form-scoped-roles/template.hbs
lib/shared/addon/components/input-identity/component.js
lib/shared/addon/components/input-identity/template.hbs
lib/shared/addon/components/principal-search/component.js
lib/shared/addon/components/project-member-row/component.js
lib/shared/addon/components/project-member-row/template.hbs

rancher/rancher#11691
rancher/rancher#11853
rancher/rancher#11891
rancher/rancher#11660
rancher/rancher#11720

Update for principals

---

lib/logging/addon/components/logging/new-edit/component.js

Fixed:
https://github.com/rancher/rancher/issues/11879

Logging bugfix

---

lib/shared/addon/components/principal-search/component.js

value not set null on focus for principal select

---

lib/shared/addon/components/input-identity/component.js
lib/shared/addon/components/principal-search/component.js

Prevent duplicates in principal store

---

lib/shared/addon/components/input-identity/component.js
lib/shared/addon/components/principal-search/component.js

undefined error from old update code that needs rework.

---

lib/global-admin/addon/components/role-rule-row/template.hbs
lib/shared/addon/utils/constants.js
translations/en-us.yaml

update the rules list with the correct kube roles

---

app/authenticated/cluster/security/members/index/template.hbs
app/authenticated/project/security/members/index/template.hbs
app/models/roletemplate.js
app/workload/controller.js
app/workload/template.hbs
lib/shared/addon/components/container/form-networking/template.hbs
lib/shared/addon/components/container/form-scale/component.js
lib/shared/addon/components/container/form-scale/template.hbs
lib/shared/addon/components/container/form-upgrade-daemon-set/template.hbs
lib/shared/addon/components/container/form-upgrade-deployment/template.hbs
lib/shared/addon/components/container/form-upgrade-stateful-set/template.hbs
lib/shared/addon/components/container/form-volumes/component.js
lib/shared/addon/components/container/form-volumes/template.hbs
lib/shared/addon/components/form-annotations/component.js
lib/shared/addon/components/form-annotations/template.hbs
translations/en-us.yaml

https://github.com/rancher/rancher/issues/11834
https://github.com/rancher/rancher/issues/11980

Update workload detail page

---

lib/global-admin/addon/accounts/edit/controller.js
lib/global-admin/addon/accounts/edit/template.hbs
lib/global-admin/addon/accounts/new/controller.js
lib/global-admin/addon/accounts/new/template.hbs
lib/global-admin/addon/components/form-global-roles/component.js
lib/global-admin/addon/components/form-global-roles/template.hbs
lib/shared/addon/components/form-scoped-roles/component.js
lib/shared/addon/components/form-scoped-roles/template.hbs
translations/en-us.yaml

global roles custom select issues

---

lib/logging/translations/en-us.yaml

https://github.com/rancher/rancher/issues/11942

Update embedded elasticsearch resource requirement tips

---

app/components/container-row/template.hbs
app/components/form-networking/template.hbs
app/components/form-security/template.hbs
app/components/machine/driver-amazonec2/component.js
app/components/schema/input-service/template.hbs
app/container/template.hbs
app/utils/errors.js
app/utils/navigation-tree.js
package.json
translations/en-us.yaml
translations/zh-hans.yaml

https://github.com/rancher/rancher/issues/11376
rancher/rancher#5325
rancher/rancher#7722
rancher/rancher#7973
rancher/rancher#8510
rancher/rancher#9482
rancher/rancher#8954
rancher/rancher#9911

[1.6]Add AWS eu-west-3 region and bump version

---

lib/alert/translations/en-us.yaml
lib/logging/translations/en-us.yaml
translations/en-us.yaml

https://github.com/rancher/rancher/issues/12065

Fixed typo

---

lib/shared/addon/components/searchable-select/component.js

Related issue:
https://github.com/rancher/rancher/issues/12003

Update searchable-component search algorithm

---

lib/shared/addon/components/cru-node-pools/component.js
lib/shared/addon/components/storage-class/provisioner-azure-disk/component.js
lib/shared/addon/components/storage-class/provisioner-azure-disk/template.hbs
lib/shared/addon/components/storage-class/provisioner-cinder/component.js
lib/shared/addon/components/storage-class/provisioner-cinder/template.hbs
lib/shared/addon/components/storage-class/provisioner-scaleio/component.js
lib/shared/addon/components/storage-class/provisioner-scaleio/template.hbs
lib/shared/addon/components/storage-class/provisioner-vsphere-volume/component.js
lib/shared/addon/components/storage-class/provisioner-vsphere-volume/template.hbs
lib/shared/addon/mixins/storage-class-provisioner.js
translations/en-us.yaml

https://github.com/rancher/rancher/issues/12133

Fix edit cluster issue and update storage class

---

lib/global-admin/addon/security/authentication/activedirectory/route.js
lib/global-admin/addon/templates/-ldap-config.hbs
package.json
translations/en-us.yaml

This PR makes use of a new method on the api store so this should be merged
and published to npm before this pr
https://github.com/rancher/ember-api-store/pull/19
rancher/rancher#11729

Load defaults for AD and Reconfig cert logic

---

app/authenticated/apikeys/template.hbs
app/authenticated/cluster/edit/route.js
app/authenticated/cluster/projects/edit/route.js
app/authenticated/cluster/projects/new/route.js
app/authenticated/route.js
app/models/user.js
lib/global-admin/addon/clusters/new/route.js
lib/pipeline/addon/components/pipeline-jobs-table/template.hbs
lib/pipeline/addon/components/pipeline-trigger/component.js
lib/pipeline/addon/components/pipeline-trigger/template.hbs
lib/pipeline/addon/components/step-scm/component.js
lib/pipeline/addon/components/step-scm/template.hbs
lib/pipeline/addon/import/controller.js
lib/pipeline/translations/en-us.yaml
lib/shared/addon/components/modal-feedback/component.js
lib/shared/addon/components/modal-kubeconfig/component.js
lib/shared/addon/components/page-header/template.hbs
lib/shared/addon/components/site-access/component.js
lib/shared/addon/components/site-access/template.hbs
lib/shared/addon/user-language/service.js

Fix issue:
1. Add Pull Request Webhook 
2. Fix issue rancher/rancher#11675
3. Enable user to use the public repository to create Pipeline 
4. Set `access.principal` instead of overriding `access.me`

Pipeline fix 18/3

---

app/authenticated/cluster/index/controller.js
app/models/cluster.js
app/models/volume.js
lib/shared/addon/components/cru-persistent-volume/component.js
lib/shared/addon/components/cru-volume/component.js
lib/shared/addon/components/form-key-to-path/component.js
lib/shared/addon/components/form-key-to-path/template.hbs
lib/shared/addon/components/volume-source/source-empty-dir/component.js
lib/shared/addon/components/volume-source/source-empty-dir/template.hbs
lib/shared/addon/components/volume-source/source-secret/component.js
lib/shared/addon/components/volume-source/source-secret/template.hbs
lib/shared/addon/mixins/volume-source.js
lib/shared/app/components/form-key-to-path/component.js
lib/shared/app/components/volume-source/source-empty-dir/component.js
lib/shared/app/components/volume-source/source-secret/component.js
translations/en-us.yaml

Add secret and empty dir volume

---

app/models/cluster.js
app/volumes/index/template.hbs
lib/shared/addon/components/cru-persistent-volume-claim/component.js
lib/shared/addon/components/modal-edit-driver/component.js
lib/shared/addon/components/modal-edit-driver/template.hbs
lib/shared/addon/components/node-gauges/component.js
translations/en-us.yaml

https://github.com/rancher/rancher/issues/12268
https://github.com/rancher/rancher/issues/12280
https://github.com/rancher/rancher/issues/12038
https://github.com/rancher/rancher/issues/12113
https://github.com/rancher/rancher/issues/12281

Fix dashboard issue

---

lib/alert/addon/components/alert/form-cluster-rules/component.js
lib/alert/addon/edit/route.js

Related issue:
https://github.com/rancher/rancher/issues/11778

Update alert targetEvent type

---

app/models/storageclass.js
app/models/volume.js
lib/pipeline/addon/components/step-scm/component.js
lib/pipeline/addon/components/step-scm/template.hbs
lib/shared/addon/components/cru-persistent-volume/component.js
lib/shared/addon/components/cru-volume/component.js
lib/shared/addon/components/storage-class/provisioner-longhorn/component.js
lib/shared/addon/components/storage-class/provisioner-longhorn/template.hbs
lib/shared/addon/components/volume-source/source-cephfs/template.hbs
lib/shared/addon/components/volume-source/source-fc/template.hbs
lib/shared/addon/components/volume-source/source-flex-volume-longhorn/component.js
lib/shared/addon/components/volume-source/source-flex-volume-longhorn/template.hbs
lib/shared/addon/components/volume-source/source-flex-volume/component.js
lib/shared/addon/components/volume-source/source-flex-volume/template.hbs
lib/shared/addon/components/volume-source/source-iscsi/template.hbs
lib/shared/addon/components/volume-source/source-rbd/template.hbs
lib/shared/addon/components/volume-source/source-secret/template.hbs
lib/shared/app/components/storage-class/provisioner-longhorn/component.js
lib/shared/app/components/volume-source/source-flex-volume-longhorn/component.js
translations/en-us.yaml

1. Add errors hint in the page of new-pipeline
2. Fix errors of changing different source when creating new PVC
3. Add longhorn storageClass/volume-source

Bug fix && Enhancement

---

app/authenticated/cluster/index/template.hbs
app/node/template.hbs
lib/pipeline/addon/settings/route.js
translations/en-us.yaml

Fix issue
1. rancher/rancher#12348
2.  https://github.com/rancher/rancher/issues/12331
3. https://github.com/rancher/rancher/issues/12336

Fix issues

---

app/styles/components/_container-shell.scss
lib/shared/addon/components/container-shell/component.js
lib/shared/addon/components/container-shell/template.hbs
translations/en-us.yaml

https://github.com/rancher/rancher/issues/12454

Support exec to sidekick

---

app/containers/run/controller.js
app/containers/run/route.js
app/containers/run/template.hbs
lib/shared/addon/components/container/form-volume-row/template.hbs
lib/shared/addon/components/container/form-volumes/component.js
lib/shared/addon/components/container/form-volumes/template.hbs
lib/shared/addon/components/container/new-edit/template.hbs
lib/shared/addon/components/volume-source/source-custom-log-path/component.js
lib/shared/addon/components/volume-source/source-custom-log-path/template.hbs
lib/shared/app/components/volume-source/source-custom-log-path/component.js
translations/en-us.yaml

Related issue:
https://github.com/rancher/rancher/issues/11625

Add custom log path

---

lib/logging/addon/components/logging/new-edit/component.js
lib/logging/addon/components/logging/target-embedded/component.js
lib/logging/addon/components/logging/target-embedded/template.hbs
lib/logging/addon/logging/route.js
lib/logging/addon/mixins/logging-model.js
lib/logging/translations/en-us.yaml

Related issue:
https://github.com/rancher/rancher/issues/11779

Add Embedded ES resource quota configuration UI

---

lib/pipeline/addon/components/pipeline-stages/component.js
lib/pipeline/addon/components/pipeline-stages/template.hbs
lib/pipeline/addon/components/pipeline-steps/template.hbs

Fix issue https://github.com/rancher/rancher/issues/12808

Fix issue https://github.com/rancher/rancher/issues/12808

---

lib/logging/addon/components/logging/target-embedded/component.js
lib/logging/addon/components/logging/target-embedded/template.hbs
lib/shared/addon/components/container/form-volumes/component.js
lib/shared/addon/components/volume-source/source-custom-log-path/component.js
lib/shared/addon/components/volume-source/source-custom-log-path/template.hbs
translations/en-us.yaml

Waiting for the backend part to be merged.
related issues:
https://github.com/rancher/rancher/issues/12768

Update embedded es limitsMemory & custom log path

---

app/apps-tab/detail/template.hbs
app/container/template.hbs
app/models/app.js
app/node/template.hbs
app/styles/components/_code.scss
app/workload/template.hbs
lib/shared/addon/components/cluster-driver/driver-import/component.js
lib/shared/addon/components/cluster-driver/driver-import/template.hbs
lib/shared/addon/components/container/form-scale/template.hbs
lib/shared/addon/components/container/form-sources/component.js
lib/shared/addon/components/container/form-sources/template.hbs
lib/shared/addon/components/cru-cloud-provider/component.js
lib/shared/addon/components/form-env-var/template.hbs
lib/shared/addon/components/modal-rollback-app/component.js
lib/shared/addon/components/resource-condition-list/component.js
lib/shared/addon/components/resource-condition-list/template.hbs
lib/shared/addon/components/save-cancel/component.js
lib/shared/addon/components/settings/danger-zone/template.hbs
translations/en-us.yaml

rancher/rancher#12845
rancher/rancher#12798
https://github.com/rancher/rancher/issues/12908
rancher/rancher#12891

Catalog and Fixes

---

app/models/notifier.js
translations/en-us.yaml

Related issue: https://github.com/rancher/rancher/issues/12914

Prevent notifier from being deleted when there are alerts referencing it

---

lib/pipeline/addon/components/input-image/component.js
lib/pipeline/addon/components/input-image/template.hbs
lib/pipeline/translations/en-us.yaml
lib/shared/addon/components/container/form-scale/component.js
lib/shared/addon/components/container/form-scale/template.hbs

Fix issue https://github.com/rancher/rancher/issues/12807

Enable use edit registry in Pipeline Page

---

app/styles/components/_dropdown.scss

z-index issue for touch enabled devices

---

lib/logging/addon/components/logging/new-edit/component.js
lib/logging/addon/components/logging/new-edit/template.hbs
lib/logging/addon/components/logging/target-embedded/template.hbs
lib/logging/addon/logging/route.js
lib/logging/addon/logging/template.hbs
lib/logging/translations/en-us.yaml

Related issuse: 
https://github.com/rancher/rancher/issues/11676

Use condition for embedded ES deployment

---

lib/shared/addon/components/input-answers/component.js
lib/shared/addon/components/input-answers/template.hbs

Group catalog answers

---

app/authenticated/cluster/projects/new-ns/controller.js
app/container/template.hbs
app/instance-initializers/nav.js
lib/shared/addon/components/form-ingress-rows/component.js
lib/shared/addon/components/form-ingress-rule/component.js
lib/shared/addon/components/form-ingress-rule/template.hbs
lib/shared/addon/settings/service.js
translations/en-us.yaml

rancher/rancher#13210
rancher/rancher#13209
rancher/rancher#13216
rancher/rancher#13205
https://github.com/rancher/rancher/issues/13275
https://github.com/rancher/rancher/issues/13238
https://github.com/rancher/rancher/issues/13241

Fixes for v2.0.1

---

lib/shared/addon/components/container-dot/template.hbs
lib/shared/addon/components/container/new-edit/component.js

https://github.com/rancher/rancher/issues/13290

Fix sidekick volume issue

---

translations/en-us.yaml
translations/ja-jp.yaml
translations/zh-hans.yaml

Changed to documentation to a Kubernetes-related document on microsoft's site.

Change the link and wording to the Azure AD SP documentation.

---

app/components/volume-source/source-custom-log-path/component.js

https://github.com/rancher/rancher/issues/13368

[Fix] Remove syslog format

---

app/styles/components/_dropdown.scss
app/styles/components/_tooltip.scss
lib/global-admin/addon/components/site-access/component.js
lib/global-admin/addon/security/authentication/azuread/controller.js
lib/global-admin/addon/security/authentication/azuread/route.js
lib/global-admin/addon/security/authentication/azuread/template.hbs
lib/global-admin/addon/security/authentication/controller.js
lib/login/addon/components/login-user-pass/component.js
lib/login/addon/login/controller.js
lib/login/addon/login/template.hbs
lib/shared/addon/components/action-menu/component.js
lib/shared/addon/components/action-menu/template.hbs
lib/shared/addon/components/cluster-driver/driver-azureaks/template.hbs
lib/shared/addon/components/language-dropdown/template.hbs
lib/shared/addon/mixins/hover-dropdowns.js
lib/shared/addon/tooltip/service.js
translations/en-us.yaml
yarn.lock

rancher/rancher#13395
rancher/rancher#13479
rancher/rancher#13420
rancher/rancher#13419
rancher/rancher#13453
rancher/rancher#13491

Azure AD Fixes and Bugs

---

lib/pipeline/addon/components/pipeline-activity-step/template.hbs
lib/pipeline/addon/components/pipeline-steps/template.hbs

Fix issue https://github.com/rancher/rancher/issues/13459

Fix issue https://github.com/rancher/rancher/issues/13459

---

translations/en-us.yaml

https://github.com/rancher/rancher/issues/13553

More descriptive IAM label

---

lib/shared/addon/github/service.js
package.json

fix github auth

---

app/apps-tab/detail/controller.js
app/apps-tab/detail/template.hbs
app/components/form-endpoints/template.hbs
app/components/namespace-app/template.hbs
app/components/new-catalog/component.js
app/components/new-catalog/template.hbs
app/models/app.js
app/models/service.js
app/models/templateversion.js
lib/shared/addon/utils/evaluate.js

rancher/rancher#13519
rancher/rancher#13692
rancher/rancher#13693

Catalog fix

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
lib/shared/addon/components/cluster-options-rke/component.js
lib/shared/addon/components/cluster-options-rke/template.hbs
lib/shared/app/components/cluster-options-rke/component.js
lib/shared/package.json
package.json
translations/en-us.yaml

https://github.com/rancher/rancher/issues/13076

Support cluster advanced options

---

app/models/node.js
translations/en-us.yaml

https://github.com/rancher/rancher/issues/13623

Support cordon, uncordon and drain for node

---

lib/pipeline/addon/components/step-scm/component.js

https://github.com/rancher/rancher/issues/13458

Fix pipeline clone issue

---

lib/pipeline/addon/components/step-scm/component.js
lib/pipeline/addon/components/step-scm/template.hbs
lib/pipeline/translations/en-us.yaml

https://github.com/rancher/rancher/issues/13722

Show error message if import pipeline failed

---

app/models/publicendpoint.js
lib/shared/addon/mixins/endpoint-ports.js

Related issue: https://github.com/rancher/rancher/issues/13805
The public endpoint will be only shown when a full dns hostname
is generated with xip.io

Shows Ingress public endpoint when ready

---

lib/global-admin/addon/components/modal-edit-catalog/template.hbs
translations/en-us.yaml

Update verbiage for adding custom catalog for clarity

---

lib/pipeline/addon/components/pipeline-step-task/template.hbs
lib/pipeline/addon/helpers/pipeline-status-to-icon.js

https://github.com/rancher/rancher/issues/13459
https://github.com/rancher/rancher/issues/13768

Fix pipeline icon issue

---

app/components/new-catalog/component.js

https://github.com/rancher/rancher/issues/13843
https://github.com/rancher/rancher/issues/13842

Fix catalog answer preview issue

---

app/components/new-catalog/component.js
app/components/new-catalog/template.hbs
translations/en-us.yaml
translations/zh-hans.yaml

https://github.com/rancher/rancher/issues/13839

Improve for catalog preview decoding

---

lib/pipeline/addon/components/step-scm/component.js

https://github.com/rancher/rancher/issues/13287

Focus repository by default

---

lib/global-admin/addon/catalog/template.hbs
lib/global-admin/addon/components/modal-edit-catalog/component.js
lib/global-admin/addon/components/modal-edit-catalog/template.hbs
lib/shared/addon/components/cluster-driver/driver-azureaks/component.js
translations/en-us.yaml

Verbiage fixes

---

app/components/new-catalog/component.js
app/containers/run/route.js
lib/shared/addon/components/container-shell/component.js

https://github.com/rancher/rancher/issues/13519
https://github.com/rancher/rancher/issues/13958

Do not create namespace for app to kube-system

---

app/components/container/form-ports/template.hbs
app/container/controller.js
app/container/route.js
app/container/template.hbs
lib/shared/addon/mixins/endpoint-ports.js
lib/shared/addon/utils/util.js

rancher/rancher#12498
rancher/rancher#13694

Fix remove pod issue and sort display endpoints

---

lib/shared/addon/components/node-driver/driver-vmwarevsphere/component.js
translations/en-us.yaml
translations/ja-jp.yaml
translations/zh-hans.yaml

vSphere, using RancherOS as default instead of boot2docker

---

lib/logging/addon/components/logging/form-log-docker/component.js
lib/logging/addon/components/logging/form-log-docker/template.hbs
lib/logging/addon/components/logging/form-log-ssl/component.js
lib/logging/addon/components/logging/form-log-ssl/template.hbs
lib/logging/addon/components/logging/new-edit/component.js
lib/logging/addon/components/logging/new-edit/template.hbs
lib/logging/addon/components/logging/target-elasticsearch/component.js
lib/logging/addon/components/logging/target-elasticsearch/template.hbs
lib/logging/addon/components/logging/target-embedded/component.js
lib/logging/addon/components/logging/target-embedded/template.hbs
lib/logging/addon/components/logging/target-kafka/component.js
lib/logging/addon/components/logging/target-kafka/template.hbs
lib/logging/addon/components/logging/target-splunk/component.js
lib/logging/addon/components/logging/target-splunk/template.hbs
lib/logging/addon/components/logging/target-syslog/component.js
lib/logging/addon/components/logging/target-syslog/template.hbs
lib/logging/addon/mixins/logging-model.js
lib/logging/translations/en-us.yaml

Related issue:
https://github.com/rancher/rancher/issues/13526
https://github.com/rancher/rancher/issues/13065

Support logging SSL for splunk, ES and kafka

---

lib/shared/addon/components/cluster-driver/driver-azureaks/component.js
lib/shared/addon/components/cluster-driver/driver-azureaks/template.hbs
translations/en-us.yaml

Adds dynamic fetching for supported kube version to azureaks cluster creation

---

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js
lib/shared/addon/components/cluster-driver/driver-amazoneks/template.hbs
package.json

Add new eks fields

---

lib/shared/addon/components/cluster-driver/driver-import/component.js
lib/shared/addon/components/cluster-driver/driver-import/template.hbs
translations/en-us.yaml

https://github.com/rancher/rancher/issues/14030

Show notes for cluster admin role

---

app/components/container-logs/component.js

View log doesn't work if the message contains Chinese

Fix view log issue

---

lib/shared/addon/utils/azure-choices.js

https://github.com/rancher/rancher/issues/14225

Update azure regions

---

app/components/resource-event-list/component.js
app/components/resource-event-list/template.hbs
app/container/template.hbs
app/workload/template.hbs
translations/en-us.yaml
translations/zh-hans.yaml

https://github.com/rancher/rancher/issues/13714

Add events list in workload and pod detail page

---

lib/logging/addon/components/logging/new-edit/component.js
lib/logging/addon/components/logging/target-elasticsearch/component.js
lib/logging/addon/components/logging/target-elasticsearch/template.hbs
lib/logging/translations/en-us.yaml

https://github.com/rancher/rancher/issues/13943

Notify users that Elasticsearch endpoint has to be an URL

---

app/components/container/new-edit/template.hbs
app/components/cru-config-map/template.hbs
app/components/cru-registry/template.hbs
app/components/cru-secret/template.hbs

[14094](https://github.com/rancher/rancher/issues/14094)

do not allow edting name for registry, config map and secret

---

app/components/cru-persistent-volume-claim/component.js

https://github.com/rancher/rancher/issues/14156

Fix pvc issue with new namespace

---

app/components/modal-about/template.hbs

https://github.com/rancher/rancher/issues/14103

Fix links to components in about modal

---

app/container/template.hbs

[#14181](https://github.com/rancher/rancher/issues/14181)

Show namespace information in POD information UI

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js

https://github.com/rancher/rancher/issues/14147

Change default networking to flannel

---

app/components/container-logs/component.js
lib/shared/addon/components/container-shell/component.js

Fix log and shell issue

---

lib/shared/addon/components/cluster-driver/driver-amazoneks/template.hbs

https://github.com/rancher/rancher/issues/14238

EKS Form Needs to Validate Min/Max ASG Size

---

app/models/node.js

https://github.com/rancher/rancher/issues/14274
Change introduced here: https://github.com/rancher/rke/commit/fc48d8239206539c84d7f9d1ab00178494c98651

Mark NoExecute and NoSchedule as Unschedulable

---

app/components/cluster-dashboard/component.js
app/components/cluster-dashboard/template.hbs

[13555](https://github.com/rancher/rancher/issues/13555)

cluster in unavailable state shows green components and counter/gauges

---

lib/global-admin/addon/accounts/edit/controller.js
lib/global-admin/addon/accounts/edit/template.hbs
lib/global-admin/addon/components/site-access/component.js
lib/global-admin/addon/security/authentication/activedirectory/controller.js
lib/shared/addon/components/cluster-driver/driver-azureaks/template.hbs
lib/shared/addon/components/cru-cloud-provider/component.js
translations/en-us.yaml

rancher/rancher#13422
rancher/rancher#14066
rancher/rancher#14245
rancher/rancher#14257

2.0.5 bugs

---

app/models/storageclass.js

Resolves https://github.com/rancher/rancher/issues/14333

Fix typo vpshere -> vsphere

---

app/components/cru-dns/component.js

https://github.com/rancher/rancher/issues/14332

Fix the DNS edit issue

---

app/authenticated/cluster/route.js
app/components/accordion-pod/component.js
app/components/accordion-pod/template.hbs

https://github.com/rancher/rancher/issues/14321

Show nodes in pods list

---

lib/global-admin/addon/components/site-access/component.js
lib/global-admin/addon/templates/-ldap-config.hbs

rancher/rancher#14344
rancher/rancher#14343

missing info

---

lib/global-admin/addon/templates/-ldap-config.hbs
lib/shared/addon/components/cluster-driver/driver-azureaks/template.hbs
translations/en-us.yaml

Missing translation

---

lib/global-admin/addon/components/new-edit-role/component.js

https://github.com/rancher/rancher/issues/14351

Fix update cluster owner role issue

---

app/verify-auth/route.js
lib/global-admin/addon/security/authentication/azuread/template.hbs
lib/global-admin/addon/security/authentication/github/template.hbs
lib/global-admin/addon/security/authentication/template.hbs
lib/global-admin/addon/templates/-ldap-config.hbs
package.json

2.0.5 bugs part 3

---

lib/logging/addon/components/logging/new-edit/component.js

https://github.com/rancher/rancher/issues/14411

ElasticSearch logging - 422 Unprocessable Entity when saving logging configuration

---

.eslintrc.js
app/verify-auth-azure/route.js
app/verify-auth/route.js
package.json

rancher/rancher#14430
I also removed a conflicting eslint rule, `arrow-body-style`, which when paired with `padded-blocks` made for a situation where you would have to add some kind of variable declaration when it wasn't needed in order to get around the rule.

missing globalStore error

---

app/admin-tab/auth/azuread/template.hbs
package.json

https://github.com/rancher/rancher/issues/11614

[1.6]Remove admin credentials field from Azure AD

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js
package.json

This reverts commit ab681a244c5abba02c25246004fb19a56138f515.

Revert "Change default networking to flannel"

---

app/components/taints-section/component.js
app/components/taints-section/template.hbs
app/node/template.hbs
translations/en-us.yaml
translations/zh-hans.yaml

https://github.com/rancher/rancher/issues/14305

Show taints in Node view

---

lib/global-admin/addon/mixins/authentication.js
lib/global-admin/addon/security/authentication/github/controller.js
lib/global-admin/addon/security/authentication/github/template.hbs
lib/global-admin/addon/templates/-ldap-config.hbs
lib/global-admin/addon/templates/-shibboleth-config.hbs
lib/global-admin/addon/templates/-shibboleth-configured.hbs
lib/shared/addon/components/cluster-driver/driver-azureaks/component.js
lib/shared/addon/components/cluster-driver/driver-azureaks/template.hbs
lib/shared/addon/components/cluster-driver/driver-googlegke/template.hbs
lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
lib/shared/addon/components/form-user-labels/template.hbs
lib/shared/addon/components/node-driver/driver-azure/component.js
lib/shared/addon/github/service.js
lib/shared/addon/utils/azure-choices.js
translations/en-us.yaml

rancher/rancher#14374
rancher/rancher#14310
rancher/rancher#14455
rancher/rancher#14325
rancher/rancher#14455
rancher/rancher#14386

Refactor GH auth page

---

app/components/container-logs/component.js
app/components/container-logs/template.hbs
app/styles/pages/_container.scss
lib/shared/addon/utils/constants.js
translations/en-us.yaml
translations/zh-hans.yaml

https://github.com/rancher/rancher/issues/13636

Wrap log lines

---

app/catalog-tab/launch/route.js

https://github.com/rancher/rancher/issues/14629

Fix catalog clone issue

---

app/models/workload.js

Related to [Issue 14627](https://github.com/rancher/rancher/issues/14627)

Allowed scaling a workload to zero pods

---

lib/shared/addon/helpers/maybe-t.js

Fix maybe-t issue

---

lib/shared/addon/utils/util.js

https://github.com/rancher/rancher/issues/14471

Fix array issue in edit cluster yaml

---

lib/shared/addon/components/cluster-driver/driver-googlegke/component.js
lib/shared/addon/components/cluster-driver/driver-googlegke/template.hbs
translations/en-us.yaml

New Params for GKE

---

app/authenticated/cluster/security/members/index/template.hbs
app/authenticated/project/ns/index/template.hbs
app/components/namespace-list/template.hbs
app/components/namespace-table/template.hbs
app/components/project-group/template.hbs

https://github.com/rancher/rancher/issues/14556

Description fields for Projects and Namespaces

---

app/components/cru-persistent-volume/component.js
app/components/cru-persistent-volume/template.hbs
app/components/form-node-affinity/component.js
app/components/form-node-affinity/template.hbs
app/components/form-node-requirement/component.js
app/components/form-node-requirement/template.hbs
app/components/form-node-selector/component.js
app/components/form-node-selector/template.hbs
lib/shared/addon/utils/constants.js
translations/en-us.yaml
translations/zh-hans.yaml

https://github.com/rancher/rancher/issues/13864

Support nodeAffinity in PV

---

lib/logging/addon/components/logging/form-log-ssl/template.hbs
lib/logging/addon/components/logging/new-edit/template.hbs
lib/logging/addon/components/logging/target-syslog/component.js
lib/logging/addon/components/logging/target-syslog/template.hbs
lib/logging/translations/en-us.yaml

https://github.com/rancher/rancher/issues/14465

Support Keyless tags for syslog

---

app/models/principal.js
app/verify-auth/route.js
lib/global-admin/addon/security/authentication/controller.js
lib/global-admin/addon/security/authentication/ping/controller.js
lib/global-admin/addon/security/authentication/ping/route.js
lib/global-admin/addon/security/authentication/ping/template.hbs
lib/global-admin/addon/templates/-ldap-config.hbs
lib/global-admin/app/security/authentication/ping/controller.js
lib/global-admin/app/security/authentication/ping/route.js
lib/login/addon/components/login-ping/component.js
lib/login/addon/components/login-ping/template.hbs
lib/login/addon/login/controller.js
lib/login/addon/login/template.hbs
lib/pipeline/addon/services/pipeline-github.js
lib/shared/addon/github/service.js
lib/shared/addon/saml/service.js
lib/shared/addon/utils/constants.js
lib/shared/app/saml/service.js
translations/en-us.yaml

UI for Ping Federate

---

lib/global-admin/addon/security/roles/index/controller.js

https://github.com/rancher/rancher/issues/14737

Fix role table update issue

---

app/components/catalog-index/template.hbs

https://github.com/rancher/rancher/issues/14703

Fix categories drop down issue

---

lib/global-admin/addon/security/roles/index/controller.js
lib/global-admin/addon/security/roles/index/template.hbs

https://github.com/rancher/rancher/issues/14739

Remove built-in column in global view table

---

app/components/cru-certificate/template.hbs

https://github.com/rancher/rancher/issues/14693

Do not allow user to edit certificate name

---

app/apps-tab/detail/controller.js
app/apps-tab/detail/template.hbs
app/authenticated/project/config-maps/index/controller.js
app/models/app.js
app/models/namespace.js
translations/en-us.yaml

https://github.com/rancher/rancher/issues/14491

Add config maps section in app detail page

---

app/components/cru-config-map/template.hbs
app/components/cru-secret/template.hbs

k8s supports config map and secret which has empty value.
https://github.com/rancher/rancher/issues/14689

Allow empty value for config map and secret

---

lib/shared/addon/components/node-driver/driver-azure/component.js

https://github.com/rancher/rancher/issues/14677

Fix azure node driver region issue

---

app/components/accordion-pod/template.hbs

Fix the issue that pods sections in workload detail page breaks

---

app/containers/run/route.js

https://github.com/rancher/rancher/issues/14511

Fix changed workload type after cloning are ignored

---

lib/global-admin/addon/components/new-edit-role/template.hbs
lib/global-admin/addon/security/roles/detail/template.hbs
lib/global-admin/addon/security/roles/index/route.js
lib/shared/addon/role-template/service.js

https://github.com/rancher/rancher/issues/14736
https://github.com/rancher/rancher/issues/14782

Show locked role in global roles page

---

lib/logging/addon/components/logging/target-syslog/component.js

https://github.com/rancher/rancher/issues/14793

Fix syslog issue

---

lib/global-admin/addon/security/roles/index/template.hbs

https://github.com/rancher/rancher/issues/14783

Fix global role detail issue

---

app/components/cluster-dashboard/component.js

https://github.com/rancher/rancher/issues/14659

Do not show alerts for cordon node

---

lib/alert/addon/models/clusteralert.js
lib/alert/addon/models/projectalert.js
lib/alert/addon/new/controller.js
lib/alert/addon/new/route.js

https://github.com/rancher/rancher/issues/14811

Alerts clone

---

lib/shared/addon/components/form-key-value/component.js
lib/shared/addon/components/form-key-value/template.hbs
lib/shared/addon/components/input-paste/component.js

https://github.com/rancher/rancher/issues/14536

Fix paste issue in form-key-value component

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/utils/util.js

https://github.com/rancher/rancher/issues/14750

Keep virtual center and cloud provider in cluster yaml consistent with RKE

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
translations/en-us.yaml

https://github.com/rancher/rancher/issues/14775
rancher/rancher#14626
rancher/rancher#14625
https://github.com/rancher/rancher/issues/14787

Fix add cluster issue

---

lib/alert/addon/new/route.js

https://github.com/rancher/rancher/issues/14811

Fix clone project alert issue

---

lib/global-admin/addon/security/roles/detail/route.js
lib/global-admin/addon/security/roles/edit/route.js
lib/global-admin/addon/security/roles/new/route.js

https://github.com/rancher/rancher/issues/14228

Fix the issue that inherited external roles not displayed

---

app/styles/base/_helpers.scss
lib/global-admin/addon/catalog/template.hbs
lib/global-admin/addon/security/authentication/azuread/template.hbs
lib/global-admin/addon/templates/-saml-config.hbs
lib/shared/addon/components/node-driver/driver-amazonec2/component.js
lib/shared/addon/components/settings/danger-zone/template.hbs
translations/en-us.yaml
translations/zh-hans.yaml

https://github.com/rancher/rancher/issues/14800

Fix hardcoded app name issue

---

lib/shared/addon/mixins/upgrade-component.js

https://github.com/rancher/rancher/issues/14861

Coerce catalog item version before compare

---

lib/global-admin/addon/mixins/saml-auth.js
lib/shared/addon/azure-ad/service.js
lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js
lib/shared/addon/github/service.js
lib/shared/addon/saml/service.js

rancher/rancher#14891
rancher/rancher#14893
rancher/rancher#14918
rancher/rancher#14920

2.0.7 Auth Bugs

---

app/components/modal-edit-setting/template.hbs

https://github.com/rancher/rancher/issues/14926

Fix setting server URL issue

---

lib/shared/addon/components/cluster-driver/driver-googlegke/template.hbs
translations/en-us.yaml

rancher/rancher#14639
This should not be merged until are merged in master:
rancher/kontainer-engine#77
rancher/types#531
rancher/rancher#14923

Rename GKE fields

---

lib/shared/addon/access/service.js

https://github.com/rancher/rancher/issues/14360

Show proper error message in login page if server is unreachable

---

app/components/container/form-volumes/component.js
app/components/form-key-to-path/component.js
app/components/volume-source/source-secret/template.hbs
package.json
translations/en-us.yaml
translations/ja-jp.yaml
translations/zh-hans.yaml

https://github.com/rancher/rancher/issues/14740

Use secretName for secret volume

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
translations/en-us.yaml

https://github.com/rancher/rancher/issues/13999

Add node name in advacned options when adding custom cluster

---

app/components/accordion-pod/template.hbs

https://github.com/rancher/rancher/issues/15074

Support bulk actions for pod list in workload detail page

---

translations/en-us.yaml

@deniseschannon @vincent99 @westlywright Can you take a look at this? Thanks

Spelling Corrections

---

app/components/input-answers/component.js
app/components/input-answers/template.hbs
app/components/input-custom-answers/component.js
app/components/input-custom-answers/template.hbs
app/components/new-catalog/component.js
app/components/new-catalog/template.hbs
lib/shared/package.json
package.json
translations/en-us.yaml
translations/zh-hans.yaml

https://github.com/rancher/rancher/issues/13064
https://github.com/rancher/rancher/issues/9771

Support edit yaml for catalog without questions

---

app/models/externalservice.js

https://github.com/rancher/rancher/issues/13754

[1.6] Fix the issue that stack page breaks sometimes

---

app/mixins/manage-labels.js

https://github.com/rancher/rancher/issues/13492

[1.6] Fix scheduling display issue

---

app/components/page-header/component.js

https://github.com/rancher/rancher/issues/11634

[1.6] Fix the issue that navigation menu closes constantly sometimes

---

lib/global-admin/addon/catalog/template.hbs

https://github.com/rancher/rancher/issues/14020

Show catalog transitioning message

---

app/components/container/form-ports/component.js
app/components/container/form-ports/template.hbs
app/components/input-random-port/template.hbs
lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
translations/en-us.yaml
translations/zh-hans.yaml

https://github.com/rancher/rancher/issues/11732

Support service node port range in cluster options

---

lib/shared/addon/components/confirm-delete/component.js
lib/shared/addon/components/confirm-delete/template.hbs
translations/en-us.yaml

https://github.com/rancher/rancher/issues/11070

Show note when removing user in cluster

---

lib/nodes/addon/components/driver-vmwarevsphere/component.js

https://github.com/rancher/rancher/issues/14334

Enable cfgparam disk.enableUUID=TRUE by default

---

app/authenticated/project/controller.js
app/authenticated/project/template.hbs
app/models/project.js
translations/en-us.yaml

https://github.com/rancher/rancher/issues/15081

Show warning in system project

---

translations/en-us.yaml

https://github.com/rancher/rancher/issues/15091

Fix the PVC detail page heading issue

---

app/components/cru-persistent-volume-claim/template.hbs
app/components/cru-persistent-volume/template.hbs
app/components/resource-event-list/component.js
app/container/template.hbs
app/workload/template.hbs
translations/en-us.yaml

https://github.com/rancher/rancher/issues/15090

Show events for pv and pvc

---

lib/shared/addon/components/cluster-driver/driver-import/component.js

https://github.com/rancher/rancher/issues/15072

Fix import cluster issue

---

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js
lib/shared/addon/components/cluster-driver/driver-amazoneks/template.hbs

https://github.com/rancher/rancher/issues/15008

Fix EKS custom vpc issue

---

lib/global-admin/addon/components/azuread-endpoints/component.js
lib/global-admin/addon/components/azuread-endpoints/template.hbs
lib/global-admin/addon/security/authentication/azuread/controller.js
lib/global-admin/addon/security/authentication/azuread/template.hbs
lib/shared/addon/utils/constants.js
translations/en-us.yaml

https://github.com/rancher/rancher/issues/15175

Enhance Azure AD

---

app/models/certificate.js
translations/en-us.yaml
translations/zh-hans.yaml

Needs backend: https://github.com/rancher/rancher/issues/14718 / https://github.com/rancher/types/pull/516
https://github.com/rancher/rancher/issues/14745

[WIP] Read Certificate SANs from list

---

app/components/cru-config-map/component.js
app/components/cru-registry/component.js
app/components/cru-secret/component.js
app/components/new-catalog/component.js
app/components/new-catalog/template.hbs

https://github.com/rancher/rancher/issues/15013

Use lower case for name

---

lib/shared/addon/components/input-yaml/component.js
lib/shared/addon/components/input-yaml/template.hbs
lib/shared/addon/components/modal-yaml/component.js
lib/shared/addon/components/modal-yaml/template.hbs

https://github.com/rancher/rancher/issues/15221

Show loading spinner in yaml modal

---

app/authenticated/cluster/route.js
lib/shared/addon/components/confirm-delete/component.js
lib/shared/addon/components/confirm-delete/template.hbs
translations/en-us.yaml

https://github.com/rancher/rancher/issues/15081

System project

---

app/styles/base/_color.scss
lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
lib/shared/addon/components/container-shell/component.js
translations/en-us.yaml

Backend PR: https://github.com/rancher/rancher/pull/13796

Windows deploy supported

---

lib/nodes/addon/components/driver-exoscale/component.js
lib/nodes/addon/components/driver-exoscale/template.hbs

Remove ingress rule port 9099, 10254.
Modify ingress rule port 2379-2380 (just open between nodes),
refactoring HTMLBars template helpers conditions statements

 Exoscale: Improve provider port security

---

app/components/new-catalog/component.js
app/components/new-catalog/template.hbs

https://github.com/rancher/rancher/issues/15252

Fix catalog issue

---

app/models/nodedriver.js

https://github.com/rancher/rancher/issues/15092

Fix node driver issue

---

lib/shared/addon/components/cru-cluster/template.hbs
translations/en-us.yaml

https://github.com/rancher/rancher/issues/11070

Fix remove user warning issue

---

app/components/cluster-dashboard/component.js
lib/shared/addon/utils/constants.js

https://github.com/rancher/rancher/issues/15301

Fix node alert issue

---

lib/global-admin/addon/components/modal-edit-catalog/component.js
lib/global-admin/addon/components/modal-edit-catalog/template.hbs

Remove the branch input disable check because the backend handles verifying whether its a git branch or not.

Add Catalog - branch should always be enabled

---

app/components/container-logs/component.js
app/components/modal-container-logs/component.js
app/components/modal-container-logs/template.hbs
app/container/template.hbs
app/models/container.js
app/models/pod.js
lib/shared/addon/components/container-shell/component.js
lib/shared/addon/components/modal-shell/component.js
lib/shared/addon/components/modal-shell/template.hbs

https://github.com/rancher/rancher/issues/12656

Support exec and logs to selected container

---

app/components/container/new-edit/component.js

https://github.com/rancher/rancher/issues/14588

Fix statefulset serviceName issue

---

app/models/app.js
app/models/node.js
app/models/pipelineexecution.js

Undefined error on the nodes page

---

.github/PULL_REQUEST_TEMPLATE.md

Pull requests have increased as of late and it would be super helpful for me to have a standard template we use when making new pull-requests.
I am not using the template here simply because I'd like feedback and the template may evolve.

WIP - Add a pull request template

---

app/components/container/form-volume-row/template.hbs
app/components/container/form-volumes/component.js
app/components/container/form-volumes/template.hbs
app/components/volume-source/source-certificate/component.js
app/components/volume-source/source-certificate/template.hbs
lib/shared/addon/components/schema/input-secret/component.js
lib/shared/addon/components/schema/input-secret/template.hbs
lib/shared/addon/utils/constants.js
translations/en-us.yaml

https://github.com/rancher/rancher/issues/15198

Support certificate type volume

---

app/authenticated/route.js
lib/login/addon/login/controller.js

Sometimes user might want to jump to a particular URL. But if the user is not unauthenticated, it will go to login page. After login, it will take user to the global cluster page instead of the URL the user wants to go to.
https://github.com/rancher/rancher/issues/15429
n/a

Support redirect

---

app/components/input-answers/component.js
app/components/input-custom-answers/component.js
app/components/input-files/component.js
lib/shared/addon/components/input-text-file/component.js
lib/shared/addon/components/input-yaml/component.js

Show related error message if read file failed.
Also remove the jQuery `on` method as the `change` function will be triggered without manually `on` the change event.
https://github.com/rancher/rancher/issues/15426
n/a

Refine file reader

---

lib/shared/addon/utils/pipeline-constants.js

Add GO example in pipeline example repos 
n/a
n/a

Add pipeline go example

---

lib/logging/translations/zh-hans.yaml
lib/logging/translations/zh-hant.yaml
lib/pipeline/translations/zh-hant.yaml
translations/zh-hans.yaml
translations/zh-hant.yaml

update zh-hans and zh-hant
N/A
N/A

update zh-hans.yaml and zh-hant.yaml

---

app/models/service.js

The port info is missing in the proxy endpoint url for catalog app.
n/a
n/a

Fix proxy endpoint url issue

---

translations/en-us.yaml

Typo addition

---

lib/shared/addon/components/cluster-driver/driver-rke/template.hbs

1. Remove the duplicated label section in adding custom node page as it has been moved to advanced options.
2. Change the indent of the template for adding custom node
https://github.com/rancher/rancher/issues/15382
n/a

Remove unused label section when adding custom node

---

lib/shared/addon/utils/constants.js

Do not show label starts with `cattle.io/`
https://github.com/rancher/rancher/issues/15431
n/a

Hide cattle.io label

---

app/models/user.js
lib/global-admin/addon/accounts/index/route.js

Added error handling to activate/deactive users

---

lib/global-admin/addon/catalog/template.hbs

Show transitioning message for Library, Helm Stable and Helm Incubator.
https://github.com/rancher/rancher/issues/14020
n/a

Show transitioning message for catalog

---

lib/shared/addon/components/cru-node-pools/component.js

Do not validate etcd count when edit cluster
https://github.com/rancher/rancher/issues/15494
n/a

Not validate etcd count when edit cluster

---

translations/en-us.yaml

GitHub authentication typos/better sentences

Fix GitHub auth typos/sentences

---

app/components/page-footer/template.hbs
app/styles/base/_helpers.scss
lib/shared/addon/settings/service.js
translations/de-de.yaml
translations/en-us.yaml
translations/es-es.yaml
translations/fa-ir.yaml
translations/fr-fr.yaml
translations/hu-hu.yaml
translations/it-it.yaml
translations/ja-jp.yaml
translations/ko-kr.yaml
translations/nb-no.yaml
translations/nl-nl.yaml
translations/pt-br.yaml
translations/ru-ru.yaml
translations/sv-se.yaml
translations/uk-ua.yaml

@loganhz, can you look at zh-hant and why there's so many lines removed?  Not clear to me if they are things that were never traditional, were intentionally removed, were the same as simplified, were mistakenly removed, or what.

Update translations from crowdin

---

lib/shared/addon/components/cru-node-pools/component.js

Revert "Not validate etcd count when edit cluster"

---

app/models/namespace.js
lib/shared/addon/components/modal-move-namespace/component.js

projectId on the namespace was changed to be un-editable. A move action was introduced to provide the user a mechanism to move namespaces.

---

lib/logging/translations/zh-hans.yaml
lib/logging/translations/zh-hant.yaml
lib/pipeline/translations/zh-hans.yaml
lib/pipeline/translations/zh-hant.yaml
translations/zh-hans.yaml
translations/zh-hant.yaml

update zh-hans and zh-hant
N/A
N/A

update zh-hans and zh-hant

---

lib/shared/addon/components/cluster-driver/driver-amazoneks/template.hbs
lib/shared/addon/components/cluster-driver/driver-azureaks/template.hbs
translations/en-us.yaml

Add warning for EKS/AKS users about lack of ingress creation

---

lib/shared/addon/utils/amazon.js

Add r5 and r5d instances for amazon ec2

---

app/components/machine/driver-amazonec2/component.js

Update AWS instance types
https://github.com/rancher/rancher/issues/15502
n/a

[1.6] Update AWS instance types

---

lib/pipeline/addon/components/pipeline-stages/template.hbs

The stage name of clone should be capitalized
n/a

Capitalize text for clone stage

---

translations/en-us.yaml

Update placeholder for local node disk path input
n/a
n/a

Update placeholder for local node disk path input

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js

Fix Windows enable bug

---

app/authenticated/route.js

Fix redirect issue. We should save the url before `transitionTo` method.
n/a
n/a

Fix redirect issue

---

translations/en-us.yaml

* PagerDuty calls it Integration Key now.
* Changed link for correct integration instructions

Use Integration Key for PagerDuty notifier

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/cluster-driver/driver-rke/template.hbs

New cluster defaults fields were stepping all over the config when setting. We were also overwriting some defaults on init, I removed those.

---

app/components/container/form-security/template.hbs
app/components/container/new-edit/component.js
app/components/container/new-edit/template.hbs
app/models/container.js
app/models/workload.js

Validate limits and requests if resource quota is enabled in project.
As the limits and requests are in the advanced option which is hidden by default, so it's better to expand the security section if the error happens. Otherwise, it's hard for users to find out where should they input the limits and requests for cpu/memory.
https://github.com/rancher/rancher/issues/15508
n/a

Validate limits and requests if resource quota is enabled in project

---

app/components/container/form-volume-row/template.hbs
app/components/container/form-volumes/component.js
app/components/container/form-volumes/template.hbs
app/components/volume-source/source-custom-log-path/template.hbs
app/container/template.hbs
app/workload/template.hbs

Fix log volume issue
https://github.com/rancher/rancher/issues/15513
n/a

Fix log volume issue

---

lib/global-admin/addon/security/authentication/controller.js
lib/global-admin/addon/security/authentication/template.hbs
lib/shared/addon/components/input-url/component.js
translations/en-us.yaml

Only allow a single (+local) auth provider to be enabled
rancher/rancher#15544
N/A

Single Auth Providers

---

app/container/controller.js

If a pod is a standalone pod, it will jump to workload list page when pod is removed.
If not, it will jump to workload detail page when pod is removed
https://github.com/rancher/rancher/issues/12498
n/a

Jump to workload detail page if it belongs to a workload

---

app/components/modal-drain-node/component.js
app/components/modal-drain-node/template.hbs
translations/en-us.yaml

Set ignoreDaemonSets to true by default.
If users set it to false,  it will show a note message. 
https://github.com/rancher/rancher/issues/15548
n/a

Set ignoreDaemonSets to true by default

---

app/models/app.js

If user navigates to catalog app list page and switch to another project, UI will always show `up to date` for all apps even there is higher version.
n/a
n/a

Fix catalog up to date issue

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/utils/parse-label.js
package.json
translations/en-us.yaml

`host-override` can only contain lower case alphanumeric characters, `-` or `.`.
n/a

Convert node name to lowercase in registration command

---

lib/shared/addon/components/cru-node-pools/component.js
lib/shared/addon/components/cru-node-pools/template.hbs
translations/en-us.yaml

Show warning if etcd count is invalid when editing cluster
https://github.com/rancher/rancher/issues/15494
n/a

Show warning if etcd count is invalid when editing cluster

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
lib/shared/addon/utils/constants.js
yarn.lock

Mounting issues with cluster defaults caused the feature to drop out of the next release. I've left the front end changes I made (only commented it out and swapped out the old variable names) and added back the old code.
rancher/rancher#15577
N/A

Cluster defaults rollback

---

lib/shared/addon/components/cluster-driver/driver-amazoneks/template.hbs
lib/shared/addon/components/cluster-driver/driver-azureaks/template.hbs
lib/shared/addon/components/cru-cluster/template.hbs

The original placement was weird so its fixed above the name/description component now.
rancher/rancher#15496
N/A

Move EKS/AKS ingress warning above name/description

---

app/components/container/form-ports/template.hbs

Fix cluster IP port placeholder issue
n/a
n/a

Fix cluster IP port placeholder issue

---

lib/global-admin/addon/templates/-ldap-config.hbs
translations/en-us.yaml

Add custom user and group search filter for AD auth
https://github.com/rancher/rancher/issues/15534
n/a

Add custom user and group search filter for AD auth

---

app/authenticated/apikeys/controller.js

We're filtering the current UI Session key so you can't delete it and hose yourself. 
rancher/rancher#11182
N/A

Filter current session key from the api keys route

---

app/container/template.hbs

Now pod detail page breaks if a standalone pod or a pod created by CRD. 
https://github.com/rancher/rancher/issues/15199

Fix pod detail page issue

---

lib/shared/addon/components/cluster-driver/driver-azureaks/component.js

Validation logic for the new AKS network inputs, in particular Docker Bridge CIDR input.
rancher/rancher#15564
N/A

Fix AKS field validation

---

lib/shared/addon/components/modal-move-namespace/component.js
lib/shared/addon/components/modal-move-namespace/template.hbs

If you fell into an error state while moving a namespace the saving button would never reset to save. 
rancher/rancher#15612
N/A

Added error handler for move namespace

---

lib/shared/addon/components/cluster-driver/driver-amazoneks/template.hbs
translations/en-us.yaml

New AMI field was added to EKS Config, added this new field to the UI. Also fixed some translation issues and shifted the flow of the eks step 4 area.
rancher/rancher#15573
N/A

Add ami field to the EKS config

---

app/models/container.js
translations/en-us.yaml

Update error message for resource quota
https://github.com/rancher/rancher/issues/14854
n/a

Update error message for resource quota

---

app/components/namespace-resource-quota/component.js

I introduced a bug by moving this to use a switch statement but not giving any default values. I've fixed my grievous error. 
N/A
N/A

Add defaults for values not in switch

---

app/authenticated/cluster/projects/edit/route.js

We need to clone the project in route for edit project page
https://github.com/rancher/rancher/issues/15647
n/a

Fix edit project issue

---

lib/global-admin/addon/templates/-ldap-config.hbs
translations/en-us.yaml

Show Search Filter attribute for Users and Groups
https://github.com/rancher/rancher/issues/15654
n/a

Show Search Filter attribute for Users and Groups

---

lib/shared/addon/components/cru-cloud-provider/template.hbs
translations/en-us.yaml

Add text `If your cloud provider is not listed, please use the Custom option`
https://github.com/rancher/rancher/issues/15652
n/a

Add text for cloud provider

---

app/styles/abstracts/_variables.scss
app/styles/components/_forms.scss
app/styles/components/_searchable-select.scss
app/styles/themes/_light.scss
lib/alert/addon/components/alert/form-cluster-rules/template.hbs
lib/alert/addon/components/alert/form-project-rules/template.hbs
translations/en-us.yaml

These are a couple changes adjusting 2 forms and minor variable changes.
No related issues open

form cluster/project rules

---

app/components/notifier/modal-new-edit/component.js
app/components/notifier/modal-new-edit/template.hbs
app/components/notifier/notifier-row/template.hbs
app/mixins/model-alert.js
app/mixins/notifier.js
app/models/notifier.js
lib/alert/addon/components/alert/form-recipient-item/template.hbs
lib/alert/translations/en-us.yaml
lib/shared/addon/utils/constants.js
translations/en-us.yaml

https://github.com/rancher/rancher/issues/15393

Configurable notifiers parameters are confusing

---

app/models/pod.js

Fix the edit pod yaml issue
n/a
n/a

Fix edit YAML issue

---

lib/shared/addon/components/cru-cloud-provider/template.hbs

Move cloud provider help text
https://github.com/rancher/rancher/issues/15652
n/a

Move cloud provider help text

---

app/components/modal-edit-namespace/component.js
app/components/modal-edit-namespace/template.hbs

Edit namespace hadn't been update to add the new fields required to display the project quota progress bar. 
rancher/rancher#15690
N/A

Add missing required fields for edit namespace

---

lib/shared/addon/components/form-members/component.js

Update hasOwner check logic
https://github.com/rancher/rancher/issues/15475
n/a

Update hasOwner check logic

---

lib/shared/app/helpers/pretty-cron.js

Apply same workaround module import for prettycron as it exists for url-regex/linkify
https://github.com/rancher/rancher/issues/15628

Import workaround for prettycron

---

app/authenticated/cluster/projects/new-ns/controller.js
app/authenticated/cluster/projects/new-ns/template.hbs
app/components/modal-edit-namespace/component.js
app/components/modal-edit-namespace/template.hbs
app/models/namespace.js

Fix quota issue when switch project in add/edit namespace page
https://github.com/rancher/rancher/issues/15720
_Tip: `yarn lint` or `npm run …

Fix quota issue when switch project in add namespace page

---

app/components/pod-row/template.hbs
app/styles/base/_helpers.scss

Fix pod row style issue. Node link in Workloads Flat List is not aligned properly
https://github.com/rancher/rancher/issues/15733
_Tip: `yarn …

Fix pod row style issue

---

app/authenticated/cluster/security/members/index/template.hbs
app/authenticated/project/security/members/index/template.hbs
app/components/namespace-table/template.hbs

Some table's paging label is missing or wrong.
If this is a relatively large or complex change, kick off …

Fix paging label issue

---

app/components/namespace-quota-row/template.hbs
app/components/namespace-resource-quota/component.js
app/styles/abstracts/_mixins.scss
app/styles/abstracts/_variables.scss
app/styles/components/_tables.scss
app/styles/components/_tooltip.scss

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
rancher/rancher#15742
n/a

Tweak colors and fix bug in ns resource prog bar

---

lib/login/addon/components/login-saml/template.hbs
translations/en-us.yaml

Fix login button issue for AD FS
https://github.com/rancher/rancher/issues/15460

Fix login button issue

---

app/components/new-edit-project/template.hbs

Support to edit project name. the `update` of `name` field  is true in the project schema. Some user wants to edit it via UI. Now we can only do it via API.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before …

Support to edit project name

---

lib/pipeline/addon/components/build-detail/template.hbs

Fix pipeline commit message issue
https://github.com/rancher/rancher/issues/15722
n/a

Fix pipeline commit message issue

---

lib/shared/addon/components/cluster-driver/driver-import/template.hbs
translations/en-us.yaml

Describe in more detail what needs to be done when importing GKE clusters (or clusters with an user without cluster-admin)
https://github.com/rancher/rancher/issues/15806
If this is a relatively large or complex change, kick off the …

Add more info on user and cluster-admin clusterrole on import

---

lib/login/addon/login/controller.js

Fix the issue that it always redirects to login page after login sometimes.
n/a
n/a

Fix the issue that it always redirects to login page after login

---

lib/shared/addon/helpers/linkify.js

`linkify` is used to find the link in string and change it to `a` tag  
But if the string is too long, it might make the browser stuck. 
n/a
n/a

Add max length limit to linkify

---

app/components/container/new-edit/component.js
app/models/workload.js

Revert "Remove capAdd & capDrop if array is empty"

---

app/components/form-labels-annotations/template.hbs
app/components/new-edit-ingress/template.hbs
app/ingress/template.hbs
lib/shared/addon/components/form-ingress-backends/template.hbs
lib/shared/addon/components/form-ingress-rows/template.hbs
lib/shared/addon/components/form-ingress-rule/template.hbs
lib/shared/addon/components/schema/input-dns-record/component.js
lib/shared/addon/components/schema/input-dns-record/template.hbs
lib/shared/addon/components/schema/input-workload/component.js
lib/shared/addon/components/schema/input-workload/template.hbs
translations/en-us.yaml

======
Ingress detail page was missing labels and annotations. The components consumed by the detail page also had no `edit` knowledge so they just became read only and it looked wonky. 
======
Linked Issues
======
rancher/rancher#15096
======
Before:
After:

Missing Data from Ingress Detail Page

---

app/workload/template.hbs

https://github.com/rancher/rancher/issues/15987
======
Fix healthcheck readonly mode issue.
======
Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/15987
======

Fix healthcheck readonly mode issue

---

lib/logging/translations/en-us.yaml

======
Clean up logging driver description
======
Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/14341
======

Clean up logging driver description

---

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js
lib/shared/addon/components/cluster-driver/driver-amazoneks/template.hbs

======
When provisioning an EKS cluster and using a custom service role we were
sending the RoleId but should have sent RoleName.
======
Bugfix
Linked Issues
======
rancher/rancher#16080
rancher/rancher#16082
======
N/A

EKS - send custom role name instead of role id

---

app/index.html

======
Currently Rancher UI will load `vendor.css` twice.
======
Linked Issues
======
======

Fix the issue that UI loads vendor css twice

---

ember-cli-build.js
lib/shared/addon/components/container-shell/component.js
lib/shared/index.js
lib/shared/package.json

======
Didn't need to alias the xterm fit module. with auto importer we are
able to reference the file directly in the xterm lib
======
Bugfix
Linked Issues
======
rancher/rancher#16095
======
N/A

Load xterm fit module correctly

---

lib/nodes/package.json
lib/pipeline/package.json

======
Fix nodes engine dependency issue. `intl` is used in aliyun ecs driver UI.
Also removed the duplicated entries in pipeline dependency
======
Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/16121
======

Fix engine dependency issue

---

app/components/modal-edit-setting/template.hbs
app/components/settings/server-url/component.js
app/components/settings/server-url/template.hbs
app/update-critical-settings/template.hbs
lib/shared/addon/components/input-url/component.js

======
Fix server-url issue
======
Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/16123
======

Fix server-url issue

---

app/components/container/new-edit/component.js
app/containers/run/template.hbs

======
Fix container name have been changed to service name when upgrade. 
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16143
======

Fix container name have been changed when upgrade

---

app/styles/components/_code.scss

======
======
<!-- 
change requested by seb, no issue submitted

inline code change

---

app/models/cluster.js
lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js
lib/shared/addon/components/cluster-driver/driver-amazoneks/template.hbs
lib/shared/addon/components/modal-delete-eks-cluster/component.js
lib/shared/addon/components/modal-delete-eks-cluster/template.hbs
lib/shared/addon/mixins/cattle-transitioning-resource.js
lib/shared/addon/utils/constants.js
lib/shared/app/components/modal-delete-eks-cluster/component.js
translations/en-us.yaml

======
Expose a new session token for AWS EKS cluster creation. The new field is optional. If it is excluded the field will be ignored. If it is included users will need to enter new auth tokens on edit and delete.
======
New feature
Linked Issues
======
rancher/rancher#16087
rancher/rancher#16091
======
@tfiduccia you will need to ping @nathan-jenan-rancher as he has a magical endpoint you can hit to genereate the new access key, access secret, and session token used to test this.

Add optional session token to eks config

---

app/apps-tab/index/route.js
lib/shared/addon/catalog/service.js

======
Catalog templates were being loaded from the wrong store.
======
bugfix
Linked Issues
======
rancher/rancher#16207
======
Does not need to be backported to 2.1 because this is a multi-level catalog problem

correctly load catalog data from global store

---

lib/logging/addon/components/logging/form-log-ssl/component.js
lib/logging/addon/components/logging/form-log-ssl/template.hbs
lib/logging/addon/components/logging/new-edit/component.js
lib/logging/translations/en-us.yaml
lib/logging/translations/zh-hans.yaml

======
Add `sslVersion`  for elasticsearch
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16070
https://github.com/rancher/rancher/issues/16042
======

 Support tls version config for elasticsearch 

---

app/components/container/new-edit/template.hbs
app/components/form-healthcheck/component.js
app/components/form-healthcheck/template.hbs
app/container/template.hbs
app/workload/template.hbs

======
The ready check for success on a liveness prob does not require more
then 1 check. Since this check is only checking for cluster up and
traffic received adding additonal checks will make it slower. As a
result we hard code this to 1 all the time.
======
Bugfix
Linked Issues
======
rancher/rancher#16161
======
N/A

Add tooltip info about liveness ready check wkl

---

lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
lib/shared/addon/components/cru-private-registry/component.js
lib/shared/addon/components/cru-private-registry/template.hbs
lib/shared/app/components/cru-private-registry/component.js
translations/en-us.yaml

======
Allow users to pass private registries to the cluster when creating RKE clusters. 
======
New feature
Linked Issues
======
rancher/rancher#15554
======
N/A

Add private registry to cluster create

---

lib/shared/addon/mixins/node-driver.js

======
Show location for exoscale node template
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16226
======

Fix exoscale location issue

---

lib/logging/addon/components/logging/form-log-ssl/component.js
lib/logging/addon/components/logging/form-log-ssl/template.hbs
lib/logging/translations/en-us.yaml
lib/logging/translations/zh-hans.yaml

======
Backport: Support tls version config for elasticsearch
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16283
======

Backport: Support tls version config for elasticsearch

---

app/components/modal-drain-node/component.js
app/components/modal-drain-node/template.hbs
app/models/node.js
lib/shared/addon/bulk-action-handler/service.js
translations/en-us.yaml

======
Make the Drain action on nodes bulkable, and rewrite the options to be less confusing.
======
Enhancement
Linked Issues
======
rancher/rancher#16280

Drain should be bulkable and make more sense

---

app/components/form-scoped-roles/component.js
translations/en-us.yaml

======
There is a logic to check if the user already has a role. 
But it is using the current login user's existing roles instead of the target user's existing roles.
======
Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/16320
======

Fix adding member issue

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/cru-private-registry/component.js
lib/shared/addon/components/cru-private-registry/template.hbs
lib/shared/addon/components/input-url/component.js
translations/en-us.yaml

======
When using private registry for RKE clusters we must have a default set if at least 1 is included. 
======
Bugfix
Linked Issues
======
rancher/rancher#16375
======
n/a

Set default private registry

---

lib/nodes/addon/components/driver-digitalocean/component.js

======
- Change SSH username to `core` for CoreOS images
- Update valid images array for droplets
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16382
https://github.com/rancher/rancher/issues/16383
======

Change CoreOS droplet username and update droplet images

---

app/components/settings/danger-zone/component.js

======
Add a setting to specify whitelisted domains that SAML auth provider can redirect to/from
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16232
======

Add setting to whitelist redirect domains for auth

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
translations/en-us.yaml

======
Based on feedback there were changes to the order of inputs for RKE
Cluster Options.
This also addresses the windows support buttons not being enabled after the correct network provider was selected.
======
Bugfix
Linked Issues
======
rancher/rancher#16396
rancher/rancher#16397
======
N/A

Tweak RKE Cluster Options based on feedback

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
translations/en-us.yaml

======
3 new rke cluster etcd service paramters were added and exposed via the
ui.
Create cluster -> Any RKE cluster -> Advanced
======
Bugfix
Linked Issues
======
rancher/rancher#16414
rancher/rancher#16415
======

Expose etcd snapshot params on rke clusters

---

app/models/cluster.js
lib/global-admin/addon/components/cluster-row/template.hbs
lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js
lib/shared/addon/components/modal-delete-eks-cluster/component.js
lib/shared/addon/components/modal-delete-eks-cluster/template.hbs
lib/shared/addon/components/sortable-table/component.js
translations/en-us.yaml

======
Tweaks to the delete flow for amazon eks clusters created with a session token. 
======
Bugfix
Linked Issues
======
rancher/rancher#16420
rancher/rancher#16421
rancher/rancher#16423
rancher/rancher#16425
======
N/A

Amazon EKS session token bugs

---

lib/shared/addon/components/modal-delete-eks-cluster/component.js
lib/shared/addon/components/modal-delete-eks-cluster/template.hbs
translations/en-us.yaml

======
Added required field indicators to eks session token cluster delete
flow. Added validation to check that fields are included and reset the
form if they are missing.
======
Bugfix
Linked Issues
======
rancher/rancher#16459
rancher/rancher#16458
======
N/A

Add required indicator and validation to eks delete

---

lib/shared/addon/components/modal-delete-eks-cluster/component.js

======
Porting fixes made in the 2.1 branch
======
Bugfix
Linked Issues
======
rancher/rancher#16458
rancher/rancher#16464
======
N/A

Port EKS Session token fixes from 2.1.x

---

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js

======
When editing an EKS cluster if the keys were empty we weren't properly
catching the error.
======
Bugfix
Linked Issues
======
rancher/rancher#16470
======
N/A

Missing keys cause error eks session token

---

lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
translations/en-us.yaml

======
Added a little help text to make it clearer to the user what the input
expects
======
New feature
Linked Issues
======
rancher/rancher#16509
======
N/A

Add help text to rke snapshot inputs

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js
translations/en-us.yaml

======
Had to tweak the validation logic for etcd retention/duration inputs to
accept different formats.
Updated help text to specify new formats
======
Bugfix
Linked Issues
======
rancher/rancher#16509
======
N/A

Rework validation logic for etcd services on rke

---

app/login/shibboleth-auth/route.js
translations/en-us.yaml

======
We were using the wrong translation api to grab errors for shibboleth auth. This caused us to hit a weird error when we got an unexpected error code from shibboleth redirect. Changed that method and added `403`, and `422` specific cases. 
======
Bugfix
Linked Issues
======
rancher/rancher#16554
rancher/rancher#16534
======
N/A

Add case 403 and 422 for shibboleth auth

---

app/authenticated/project/project-catalogs/template.hbs
app/models/catalog.js
lib/shared/addon/components/custom-catalog/component.js
lib/shared/addon/components/modal-edit-catalog/component.js
lib/shared/addon/components/modal-edit-catalog/template.hbs
translations/en-us.yaml

======
UI Support private catalog for auth
- After: 
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16244
======

UI Support private catalog for auth

---

app/components/new-edit-ingress/component.js
app/components/new-edit-ingress/template.hbs
lib/shared/addon/components/form-certificate-row/component.js
lib/shared/addon/components/form-certificate-row/template.hbs
lib/shared/addon/components/form-ssl-termination/component.js
lib/shared/addon/components/form-ssl-termination/template.hbs
translations/en-us.yaml
translations/zh-hans.yaml

======
- Fixed the issue that it shows two `Add Certificate` buttons in new/edit ingress page
- Fixed the issue that it always selects `Use default ingress controller certificate` in ingress edit page
- Validate host field when user select `Use default ingress controller certificate` and show error message if user don't input any host
- Validate host field when user select a wildcard cert and show error message if user don't input any host
======
Linked Issues
======
https://github.com/rancher/rancher/issues/14051
======

Validation for ingress

---

app/models/setting.js

======
======
Linked Issues
======
https://github.com/rancher/rancher/issues/15273
======

Block editing of cacerts in UI

---

app/components/accordion-pod/template.hbs

======
======
Linked Issues
======
https://github.com/rancher/rancher/issues/15761
======

Pod created time in workload detail

---

app/container/template.hbs
app/styles/base/_helpers.scss
translations/en-us.yaml
translations/zh-hans.yaml

======
======
Linked Issues
======
https://github.com/rancher/rancher/issues/15762
======

Replace node IP to nodename in Pod detail view

---

app/index.html
lib/shared/addon/components/cluster-driver/driver-rke/component.js
translations/en-us.yaml

Only validate etcd snapshot config if the service is enabled.
Consolidate version checking cluster logic
======
Bugfix
Linked Issues
======
rancher/rancher#16113
======
N/A

ETCD Snapshot validation

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js

======
======
Bugfix
Linked Issues
======
rancher/rancher#16578
======
N/A

Tweak etcd duration logic

---

lib/nodes/addon/components/driver-amazonec2/component.js

======
When users edit an existing aws template, the availability zone will be set to the first option instead of the real selected zone.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/15607
======

Fix editing aws node template issue

---

app/components/container/form-job-config/template.hbs
app/components/container/form-scale/component.js
translations/en-us.yaml

======
- After
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16559
======

Add UI for toggle cron status

---

lib/shared/addon/components/sortable-table/component.js

======
It shows `Pod` instead of Namespace: XXXX after creating a new service
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16591
======

Fix group issue

---

app/components/container/new-edit/component.js

======
When user tries to add a sidecar with invalid input,  UI got stuck. 
User can not add sidecar even with correct input.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16505
======

Fix sidecar issue

---

app/components/container/form-networking/component.js
app/components/container/form-networking/template.hbs
app/models/workload.js
translations/en-us.yaml

======
Support dnsConfig in UI for workload
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16126
======

Support dnsConfig

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js

======
We should show args with empty value under `extra_args` in cluster YAML
```
ingress:
provider: nginx
options:
map-hash-bucket-size: "128"
ssl-protocols: SSLv2
extra_args:
enable-ssl-passthrough: ""
```
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16149
======

Show param with empty value in extra_args

---

app/components/accordion-pod/template.hbs
app/components/pod-row/template.hbs
app/container/template.hbs
app/models/pod.js
translations/en-us.yaml

======
- Show pod restart count in UI
- Show transitioning message in pod section under workload detail page
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16245
======

Show pod restarts in UI

---

app/authenticated/cluster/projects/new-ns/template.hbs
app/components/modal-edit-namespace/template.hbs
app/components/namespace-resource-quota/component.js
app/models/namespace.js

======
- Allow user to set quota to 0
- Fixed the issue editing ns shows wrong used value
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16570
https://github.com/rancher/rancher/issues/16368
https://github.com/rancher/rancher/issues/16363
======

Fix quota issues

---

app/components/modal-import/template.hbs
app/styles/components/_modals.scss

======
The button will be out of the screen if the line is too long. We need to set the max-width to it.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16273
======

Fix import yaml style issue

---

app/models/cluster.js
lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js

======
We weren't clearing the Access Key on EKS clusters created with session tokens on edit.
======
Bugfix
Linked Issues
======
rancher/rancher#16576
======
N/A

Clear EKS Access Token on Edit of Session Token Cluster

---

lib/shared/addon/components/cluster-driver/driver-rke/template.hbs

======
the windows support radios were watching the incorrect field to update
the disabled state.
======
bugfix
Linked Issues
======
rancher/rancher#16397
======
N/A

Enable windows support flag correctly

---

app/components/project-group/template.hbs

======
grouped namespaces/projects on a local cluster view broke because we'd
try linking without an id
======
Bugfix
Linked Issues
======
rancher/rancher#16612
======
N/A

add check for id in project/ns view

---

app/styles/components/_container-shell.scss
lib/shared/addon/components/container-shell/component.js
lib/shared/addon/components/container-shell/template.hbs

======
1. Add socket.onerror. 
2. Grey out the window when status is closed.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/15246
======

Show API response in embedded kubectl view

---

app/instance-initializers/nav.js

======
Bug fix for - Resource drop-down pops up in upper left if I'm on node template page
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16594
======

Fix pipeline menu issue

---

lib/shared/addon/components/cru-private-registry/component.js

======
The init function was automatically adding a new private reg if one
didn't exist. A user should have to explicitly call the add, otherwise
we get issues on edit.
======
Bugfix
Linked Issues
======
rancher/rancher#16647
======
N/A

Private Registry Bug

---

lib/shared/addon/utils/amazon.js

======
Add M5D and C5D instance types for AWS EC2
https://aws.amazon.com/ec2/instance-types/c5/
https://aws.amazon.com/ec2/instance-types/m5/
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16417
======

Add M5D and C5D instance types for AWS EC2

---

app/components/input-resource-quota/template.hbs

======
Not allow negative numbers in project/namespace quotas
======
Linked Issues
======
https://github.com/rancher/rancher/issues/15673
======

Not allow negative numbers in project/namespace quotas

---

app/components/page-header-project/component.js
app/components/page-header-project/template.hbs
translations/en-us.yaml

Show messages when there are no projects or clusters to switch to
======

No project/cluster messages

---

lib/shared/addon/components/project-member-row/component.js
lib/shared/addon/components/project-member-row/template.hbs

======
Show role template name instead of template id in edit project page
======
Linked Issues
======
https://github.com/rancher/rancher/issues/15658
======

Fix member role display issue in edit project page

---

lib/global-admin/addon/components/site-access/component.js
lib/global-admin/addon/components/site-access/template.hbs
lib/global-admin/addon/security/authentication/activedirectory/route.js
lib/global-admin/addon/security/authentication/adfs/route.js
lib/global-admin/addon/security/authentication/azuread/route.js
lib/global-admin/addon/security/authentication/azuread/template.hbs
lib/global-admin/addon/security/authentication/freeipa/route.js
lib/global-admin/addon/security/authentication/github/route.js
lib/global-admin/addon/security/authentication/github/template.hbs
lib/global-admin/addon/security/authentication/keycloak/route.js
lib/global-admin/addon/security/authentication/openldap/route.js
lib/global-admin/addon/security/authentication/ping/route.js
lib/global-admin/addon/security/authentication/route.js
lib/global-admin/addon/templates/-ldap-config.hbs
lib/global-admin/addon/templates/-saml-config.hbs

======
Add cancel button in config auth page.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/15889
======

Cancel button in auth config

---

app/components/cru-dns/component.js
app/components/cru-dns/template.hbs
app/components/cru-persistent-volume-claim/component.js
app/components/cru-persistent-volume-claim/template.hbs

======
Fix the issue that UI hangs if there is no namespace selected in create DNS / PVC page
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16692
======

Fix the issue that UI hangs if there is no ns selected

---

app/components/namespace-quota-row/template.hbs
app/components/progress-bar-multi/template.hbs

======
Fix progress bar edge style issue
======
Linked Issues
======
https://github.com/rancher/rancher/issues/15914
======

Fix progress bar edge issue

---

lib/logging/addon/components/logging/new-edit/component.js
lib/logging/addon/mixins/target-elasticsearch.js
lib/logging/translations/en-us.yaml

======
Validate elasticsearch prefix
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16009
======

Validate elasticsearch prefix

---

lib/shared/addon/components/cluster-driver/driver-rke/template.hbs

======
Expand the cluster options by default when creating RKE cluster
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16108
======

Expand the cluster options by default for RKE cluster

---

app/authenticated/cluster/security/members/index/controller.js
app/authenticated/project/security/members/index/controller.js

======
Fix sorting issue
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16130
======

Fix member sorting issue

---

app/container/template.hbs
app/workload/template.hbs

======
Fix liveness title issue
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16162
======

Fix liveness title issue

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js

======
Add check on mandatory fields for Azure cloud provider
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16334
======

Add check on mandatory fields for Azure cloud provider

---

lib/pipeline/translations/en-us.yaml
translations/en-us.yaml

======
Update directions for Github Enterprise
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16667
======

Update directions for Github Enterprise

---

app/components/form-sources-row/component.js
app/components/form-sources-row/template.hbs
translations/en-us.yaml

======
Support environment variables from downward API fields
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16189
======

Support environment variables from downward API fields

---

lib/global-admin/addon/mixins/saml-auth.js
lib/global-admin/addon/security/authentication/adfs/route.js
lib/global-admin/addon/security/authentication/keycloak/route.js
lib/global-admin/addon/security/authentication/ping/route.js

======
Prefill Rancher API Host field
======
Linked Issues
======
https://github.com/rancher/rancher/issues/15463
======

Prefill Rancher API Host field

---

app/components/form-scoped-roles/component.js

======
Fix the issue that cluster roles are showing up in project member assignment view
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16700
======

Fix member issue

---

app/models/service.js

======
We need to check if the port name is `http` or `https`. 
For Kubernetes dashboard, we have to specify `https` in the service endpoint link.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16463
======

Fix service endpoint issue

---

lib/shared/addon/utils/azure-choices.js

Just like the subject, the Azure China Cloud has new region ready since 2 months ago

Add support for the new Azure China Cloud region

---

app/components/page-header-project/component.js

======
Escape unsafe HTML characters in search results of (unreleased) new project dropdown
======

Fix HTML escaping of search results

---

app/styles/components/_code.scss
app/styles/components/_dropdown.scss
app/styles/components/_page-header.scss
lib/shared/addon/components/settings/danger-zone/template.hbs

This is making minor fixes to the main navigation, as well as a couple changes on the settings page.
linked issues:
https://github.com/rancher/rancher/issues/16738
https://github.com/rancher/rancher/issues/16732
https://github.com/rancher/rancher/issues/16708
https://github.com/rancher/rancher/issues/16712

nav and theme issues

---

lib/logging/translations/en-us.yaml

minor typo fix; feel free to issue an issue, but I wouldn't do that :)

add missing comma and word

---

app/app.js
lib/pipeline/addon/components/edit-pipeline-config/component.js
lib/pipeline/addon/components/edit-pipeline-config/template.hbs
lib/pipeline/addon/components/form-recipient-item/component.js
lib/pipeline/addon/components/form-recipient-item/template.hbs
lib/pipeline/addon/components/pipeline-notifier/component.js
lib/pipeline/addon/components/pipeline-notifier/template.hbs
lib/pipeline/addon/engine.js
lib/pipeline/addon/pipelines/edit/route.js
lib/pipeline/translations/en-us.yaml
lib/pipeline/translations/zh-hans.yaml
lib/shared/addon/utils/constants.js

======
UI support for pipeline notification config
- After:
======
Linked Issues
======
https://github.com/rancher/rancher/issues/15666
======

UI support for pipeline notification config

---

lib/pipeline/addon/components/github-setting/component.js

======
There is a typo in pipeline code.
======
Linked Issues
======
======

Fix pipeline issue

---

lib/shared/addon/components/cru-cluster/component.js

======
======
Linked Issues
======
======

fix bug with editing clusters from kontainers

---

lib/shared/addon/components/marked-down/component.js

======
markdown component doesn't work well.
It doesn't render the content after `marked` loaded.
======
Linked Issues
======
======

Fix markdown component issue

---

lib/shared/addon/components/cluster-driver/driver-aliyunkcs/component.js

======
Upgrade Aliyun hosted k8s version
======
Linked Issues
======
======

Upgrade Aliyun hosted k8s version

---

lib/shared/addon/components/cluster-driver/driver-huaweicce/component.js
lib/shared/addon/components/cluster-driver/driver-huaweicce/template.hbs
translations/en-us.yaml
translations/zh-hans.yaml

======
The backend logic for huawei hosted k8s changed a bit.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16809
======

Enable external server by default for Huawei hosted k8s

---

lib/shared/addon/components/graph-area/component.js
lib/shared/addon/components/metrics-graph/component.js
lib/shared/addon/components/metrics-graph/template.hbs
lib/shared/addon/mixins/metrics.js
translations/en-us.yaml
translations/zh-hans.yaml

======
- Show graphs only when there are at least two points.
- Fix an uncaught error .
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16900
======

Monitoring

---

lib/shared/addon/components/cluster-driver/driver-huaweicce/component.js
lib/shared/addon/components/cluster-driver/driver-huaweicce/template.hbs
translations/en-us.yaml
translations/zh-hans.yaml

======
======
Linked Issues
======
======

Fix external server in huawei cce driver

---

app/catalog-tab/index/controller.js

======
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16836
======

UI- Launch catalog: Select the catalog of cluster/project level, catalog name is not updated

---

app/components/form-scoped-roles/component.js

======
Fix the issue that cannot add same user to different clusters/projects
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16929
======

Fix the issue that cannot add same user to different clusters/projects

---

lib/monitoring/translations/en-us.yaml
lib/monitoring/translations/zh-hans.yaml
translations/en-us.yaml

======
- Fixed a typo in translation file.
- Rename Rancher Components to Rancher Logging as now we will only have logging related metrics under that section.
======
Linked Issues
======
======

Fix translation issues

---

lib/monitoring/translations/en-us.yaml

======
Fix text typo issue
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16916
======

Fix text typo

---

lib/shared/addon/mixins/metrics.js

======
Fix the issue that If you refresh the Rancher Logging Metrics area the charts will change order randomly. 
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16917
======

Fix fluentd graph issue

---

lib/shared/addon/mixins/metrics.js

======
Fix the issue that line color changed after refresh
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16917
======

Fix the issue that line color changed after refresh

---

lib/alert/addon/components/alert/form-project-rule-row/component.js
lib/alert/addon/edit-rule/route.js
lib/alert/addon/edit/route.js

======
1. Fixed edit cluster alert not show right targetType.
2. Fixed project rule cannot show the metric graph.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16936
https://github.com/rancher/rancher/issues/16943
======

Fix edit cluster alert not show right targetType

---

lib/shared/addon/components/metrics-action/component.js
lib/shared/addon/mixins/metrics.js

======
UI will send another call to query the metrics after the last call returned for 5s (based on what period is selected in UI).
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16920
======

Update Graph on interval

---

lib/shared/addon/components/cluster-driver/driver-huaweicce/component.js
lib/shared/addon/components/cluster-driver/driver-huaweicce/template.hbs
translations/en-us.yaml
translations/zh-hans.yaml

======
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16809
======

Fix CCE driver bug

---

lib/shared/addon/components/sortable-table/component.js

======
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16601
======

Click on checkbox for bulk action doesn't work

---

lib/shared/addon/components/cluster-driver/driver-azureaks/component.js

======
This is a temp patch to fix the azure k8s version number. A proper fix will go in post alpha.(rancher/ui#2391)
======
Bugfix
Linked Issues
======
N/A (patch)
======

patch azure k8s version until after alpha

---

lib/monitoring/addon/components/cluster-dashboard/template.hbs
lib/monitoring/addon/components/k8s-component-status/component.js
lib/monitoring/addon/components/k8s-component-status/template.hbs
lib/shared/addon/grafana/service.js

======
- Hide Etcd Grafana link for non-rke cluster
- Fix the issue that Grafana link messed up when switching between clusters
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16970
======

Fix Grafana issue when switching between cluster or project

---

app/instance-initializers/nav.js
lib/global-admin/addon/catalog/controller.js
lib/monitoring/addon/components/enable-monitoring/template.hbs
lib/shared/addon/components/custom-catalog/component.js
lib/shared/addon/components/custom-catalog/template.hbs
lib/shared/addon/mixins/metrics.js
lib/shared/addon/utils/constants.js

======
- Do not show error message when re-enter enabling monitoring page
- Fix etcd graph flip flop issue
- Support more durations for alerting
- Show project level monitoring for system project as well
- Hide system library in project/cluster level catalog config page
- Clicking on Enable Monitoring link causes both Cluster and Tools to be highlighted on nav bar
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16985
https://github.com/rancher/rancher/issues/16915
======

Small UI Bug fixes for alpha release

---

app/components/form-healthcheck/component.js

======
The backend schema changed for http headers fields from map to array.
Backend changed quietly..
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16853
======

Fix healthcheck http headers field issue

---

app/components/cru-dns/component.js
app/components/cru-dns/template.hbs
app/components/cru-persistent-volume-claim/component.js
app/components/cru-persistent-volume-claim/template.hbs

======
Error shows up before click on Create. 
This is not consistent with rest of the application. 
We should throw the error but wait until they click the create button.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16692
======

Fix the ns issue in creating dns/pvc page

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/input-yaml/template.hbs

======
We should use `flannelBackendType` instead of `flannel_backend_type`
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16863
======

Fix windows option issue

---

lib/alert/addon/new-rule/route.js

======
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17007
======

Clone project alert rule result UI crash

---

lib/shared/addon/mixins/preload.js

======
======
Linked Issues
======
https://github.com/rancher/rancher/issues/15571
======

Route to cluster list if user doesn't have access to the cluster

---

lib/global-admin/addon/components/account-row/template.hbs

======
Show more info for the user in global user list
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16679
======

Show more info for the user in global user list

---

app/components/form-scoped-roles/template.hbs

======
Use description for roles in member screens
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16734
======

Use description for roles in member screens

---

lib/shared/addon/components/cluster-driver/driver-azureaks/template.hbs
lib/shared/addon/components/cluster-driver/driver-googlegke/template.hbs

======
Expand the cluster options section for GKS and AKS by default
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16762
======

Expand the cluster options section for GKS and AKS

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/utils/constants.js
package.json

======
Updates the experimental rancher version to the latest 1.12 so we mark 1.12 as experimental in the UI again.
======
Bugfix
Linked Issues
======
rancher/rancher#17050
======
N/A

Update rancher experimental version to latest version

---

app/components/container/form-ports/component.js
lib/monitoring/addon/components/cluster-dashboard/component.js
lib/shared/addon/capabilities/service.js
lib/shared/addon/components/form-ingress-rows/component.js
translations/en-us.yaml

======
Disable the ability to select an l4 load balancer and "Use as the default backend" as options when cluster capabilities do not support.
======
Bugfix
Linked Issues
======
rancher/rancher#16783
rancher/rancher#16784
======

Cluster capabilities updates

---

lib/shared/addon/utils/azure-choices.js

======
Update list of AKS locations
This was generated using:
```
az provider show -n Microsoft.ContainerService | jq -r '.resourceTypes[] | select(.resourceType=="managedClusters") | .locations[]' | sort | while IFS='' read location; do az account list-locations | jq --arg location "$location" -r '.[] | select(.displayName==$location) | {name: .name, displayName: $location}'; done
```
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17054
======

Update AKS locations

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/cru-private-registry/component.js

======
remove unneeded code that prevented us from removing a single private registry on an edited cluster. 
======
bugfix
Linked Issues
======
rancher/rancher#16767
======
N/A

Allow Single Private Registry Removal

---

app/components/node-row/component.js
lib/shared/addon/mixins/resource-usage.js

======
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16944
======

Fixed Pods, Memory And Cpu Column Does Not Sort Numerically

---

lib/shared/addon/components/schema/input-hostname/component.js

======
Cannot switch to custom hostname option when deploy catalog
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17058
======

Fix hostname answer issue in catalog

---

lib/shared/addon/components/cluster-driver/driver-azureaks/component.js

======
Validate AKS required fields
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17010
======

Validate AKS required fields

---

lib/monitoring/translations/en-us.yaml

======
Fix typo
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17017
======

Disk operations should be capitalized

---

app/components/accordion-pod/template.hbs
app/components/pod-row/template.hbs
app/components/workload-row/template.hbs
app/pod/template.hbs
app/templates/tooltip-multi-lines.hbs
lib/shared/addon/mixins/display-image.js

======
Show images tooltip when a pod has multiple images
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17043
======

Show images tooltip

---

lib/shared/addon/capabilities/service.js

======
We can change it to 
```
const { ingressCapabilities = [] } = capabilities;
```
But if `capabilities.ingressCapabilities` is `null`, the default value `[]` will not be used.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17087
======

Fix ingress issue

---

app/catalog-tab/launch/route.js
app/components/input-answers/template.hbs
app/components/input-edit-password/component.js
lib/shared/addon/components/schema/input-password/component.js
lib/shared/addon/utils/util.js

======
Support generate password by regex for catalog password answer
```
- group: "App Settings"
variable: app.session.secret
default: ""
description: "secret will be auto-generated if not specified"
min_length: 64
max_length: 64
valid_chars: "a-zA-Z0-9"
type: password
label: Session Secret
```
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17055
======

Support generate password by regex

---

app/authenticated/project/route.js
app/catalog-tab/index/route.js
app/catalog-tab/launch/route.js

======
Fix catalog routing issue
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17089
======

Fix catalog routing issue

---

app/styles/_rancher.scss
app/styles/components/_logging.scss
lib/logging/addon/components/logging/code-block/component.js
lib/logging/addon/components/logging/code-block/template.hbs
lib/logging/addon/components/logging/form-log-format/template.hbs
lib/logging/addon/components/logging/new-edit/component.js
lib/logging/addon/components/logging/target-flentd/component.js
lib/logging/addon/components/logging/target-splunk/component.js
lib/logging/addon/components/logging/targets-nav/component.js
lib/logging/translations/en-us.yaml
lib/logging/translations/zh-hans.yaml

======
It seems `{{{highlighted}}}` cannot be wrapped by `<code>`
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17023
https://github.com/rancher/rancher/issues/16966
======

Fix logging log preview throw an error

---

app/models/node.js

======
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16894
======

Fix Drain action not working when select a node

---

app/containers/run/route.js

======
We weren't correctly loading the shell-quote module that is used in the input-command and entry-point modules when launching a new container.
======
Bugfix
Linked Issues
======
rancher/rancher#17085
======
N/A

Fix shell-quote lazy module loading for container launch

---

lib/global-admin/addon/components/modal-revert-setting/template.hbs
translations/en-us.yaml

======
fix incorrect action target in revert setting modal
moved bare strings to translations file
======
Bugfix
Linked Issues
======
rancher/rancher#16717
======
N/A

Fix Unable to Cancel Revert Setting

---

app/models/roletemplate.js
translations/en-us.yaml
translations/zh-hans.yaml

======
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16890
======

Fix inherited roles can be deleted

---

app/styles/_rancher.scss
app/styles/components/_identity-block.scss
lib/shared/addon/components/identity-block/template.hbs

======
Add `identity-block` class to wrap.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16818
======

Member list is cutting off on screen

---

lib/global-admin/addon/security/roles/index/controller.js
lib/global-admin/addon/security/roles/index/route.js
lib/global-admin/addon/security/roles/index/template.hbs
translations/en-us.yaml

======
We weren't filtering the non-active states from the roles pages
changes single to double quotes in template
bit of clean up
======
Bugfix
Linked Issues
======
rancher/rancher#16733
======
N/A

fix content filters for roles

---

lib/alert/translations/en-us.yaml
lib/alert/translations/zh-hans.yaml
lib/alert/translations/zh-hant.yaml

======
Change text from na to not configured in alerts table
======
Enhancement
Linked Issues
======
rancher/rancher#17110
======
N/A

Change text from na to not configured

---

app/models/notifier.js

======
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17103
======

Fix notifier can be deleted when an alert group use

---

lib/alert/addon/components/alert-table/component.js
lib/alert/addon/components/cluster-alert-row/template.hbs
lib/alert/addon/components/project-alert-row/template.hbs

======
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17108
======

Add tooltip of alert name

---

lib/shared/addon/components/cluster-driver/driver-googlegke/template.hbs
lib/shared/addon/components/input-text-file/component.js
lib/shared/addon/components/input-text-file/template.hbs

======
======
Linked Issues
======
https://github.com/rancher/rancher/issues/13783
======

Hide the service account text for GCE

---

lib/shared/addon/components/cru-node-pools/component.js
translations/en-us.yaml
translations/zh-hans.yaml

======
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16381
======

Fix DigitalOcean provider name prefix

---

app/components/modal-edit-namespace/component.js

======
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16617
======

Fix edit namespace cannot change project

---

lib/shared/addon/components/form-versions/component.js

======
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17141
======

Fix unable to edit existing cluster K8s version

---

ember-cli-build.js

======
Engine assets did not have a cache-buster so we added one via the generateUri method.
======
Bugfix
Linked Issues
======
rancher/rancher#16472
======
N/A

Add query string version to all engine assets

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js
lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
translations/en-us.yaml

======
Added weave to the network providers dropdown for RKE clusters
Fixed HTML formatting issues
======
New Feature
Linked Issues
======
rancher/rancher#12909
======
N/A

Add weave network support to RKE clusters

---

app/components/catalog-index/component.js
lib/pipeline/addon/components/pipeline-steps/component.js
lib/pipeline/addon/components/step-summary/template.hbs
lib/pipeline/addon/components/steps/step-apply-catalog/component.js
lib/pipeline/addon/components/steps/step-apply-catalog/template.hbs
lib/pipeline/addon/components/steps/step-push-catalog/component.js
lib/pipeline/addon/components/steps/step-push-catalog/template.hbs
lib/pipeline/app/components/steps/step-apply-catalog/component.js
lib/pipeline/app/components/steps/step-push-catalog/component.js
lib/pipeline/translations/en-us.yaml
lib/shared/addon/utils/pipeline-constants.js
lib/shared/addon/utils/util.js
lib/shared/app/utils/util.js

======
Catalog integration in Pipeline
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16154
======

Catalog integration in Pipeline

---

lib/shared/addon/components/principal-search/component.js
package.json
yarn.lock

======
Reworked the ember-concurrency flow we use for principal search. There seemed to be a few cases where our search results were out of sync with the entered search. I was unable to reproduce this but after some analysis of the code I think that in some cases we'd return the promise, start another search and before the new search completed the `then` statement from the previous would fire. Since we can't technically abort a promised call I have a feeling this may be the problem. I tweaked the flow so that we only parse the results after the yield has finished. 
======
Bug Fix
Linked Issues
======
rancher/rancher#15961
======
QA: I could not reproduce this so we should verify that the search is working as it was before.

Principal search bug

---

lib/shared/addon/components/cluster-driver/driver-amazoneks/template.hbs
translations/en-us.yaml

======
Update the help text to alert users to only use IAM access keys.
======
Enhancement
Linked Issues
======
rancher/rancher#16157
======
N/A

Update help text for amazon eks access keys

---

app/components/scheduling-toleration/component.js
app/components/scheduling-toleration/template.hbs
lib/shared/addon/utils/constants.js
package.json

======
Backport Adding tolerations to a workload via the UI does not work
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17220
======

Backport Adding tolerations to a workload via the UI does not work

---

app/catalog-tab/launch/route.js
app/components/catalog-index/component.js
app/components/catalog-index/template.hbs
app/models/template.js
lib/shared/addon/components/modal-edit-catalog/component.js
translations/en-us.yaml

======
Fixes catalog filter dropdown alignment
Fixes dynamic params on back to route with catalog launch page
Fixes verbiage issue with cluster/project level catalog display
Fixes filtering of different catalogs on catalog index
Fixes sort order of scope dropdown in catalog management
======
Bugfix
Linked Issues
======
rancher/rancher#17162
rancher/rancher#17163
rancher/rancher#17165
rancher/rancher#17206
======
N/A

Catalog fixes

---

lib/shared/addon/mixins/subscribe.js

======
Was seeing some weirdness with sockets not respecting the reconnect logic. Removed a second connect which was causing us to immediately try to reconnect. 
======
Bugfix
Linked Issues
======
No issue
======
QA:
We should ensure that the events and status still update as expected because there was no real reproducible case for this.

Reset tries count when switching clusters or projects

---

app/components/scheduling-toleration/component.js
app/components/scheduling-toleration/template.hbs
lib/shared/addon/utils/constants.js

======
Fix toleration issue
======
Linked Issues
======
https://github.com/rancher/rancher/issues/15585
======

Fix toleration issue

---

app/components/form-key-to-path/component.js

======
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17199
======

Fix form-key-to-path bug

---

app/components/page-header-project/template.hbs
app/styles/components/_button.scss
app/styles/components/_page-header.scss
app/styles/layout/_header.scss
yarn.lock

adjusting line heights and paddings for button baseline adjustment
https://github.com/rancher/rancher/issues/16924

button fixes for 16924

---

app/models/cluster.js
translations/en-us.yaml

======
Adds cert rotation action to the available actions if present
======
New Feature
Linked Issues
======
rancher/rancher#16795
======
N/A

Add cert rotation action to clusters available actions

---

app/catalog-tab/route.js
lib/shared/addon/catalog/service.js

======
Need to filter catalog categories so its only pulling categories in the global, cluster, and project spaces it belongs too at that point.
======
Bug Fix
Linked Issues
======
rancher/rancher#17279
======
N/A

filter catalog categories by cluster and project

---

lib/global-admin/addon/security/roles/index/controller.js

======
Remove call to missing action for roles page
fix filteredContent to return the correct content for global rows
======
Bugfix
Linked Issues
======
rancher/rancher#16733
======
The secondary issue here was that no global roles were loading. filteredContent on the roles controller used to filter by active-ish states but global roles do not have a state so I added a type check to fix empty global roles.

Fix roles page role removal

---

app/components/modal-rotate-certificates/component.js
app/components/modal-rotate-certificates/template.hbs
app/models/cluster.js
translations/en-us.yaml

======
Missed params that need to be sent to the rke cluster certificate rotation api. 
======
Bugfix
Linked Issues
======
rancher/rancher#16795
======

Added missing params to send to rke cluster cert rotation api

---

lib/pipeline/addon/components/steps/step-apply-catalog/component.js
lib/pipeline/addon/components/steps/step-apply-catalog/template.hbs
lib/pipeline/translations/en-us.yaml
lib/pipeline/translations/zh-hans.yaml

======
Pipeline catalog backend changed some params.  
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16154
======

Fix pipeline catalog issue

---

app/components/modal-rotate-certificates/component.js
app/models/cluster.js
lib/shared/addon/helpers/array-includes.js

======
I was using the wrong service list to build the services keys for the rotate certs dropdown
======
Bugfix
Linked Issues
======
rancher/rancher#16795
======
N/A

load service default keys from schema

---

app/components/container/form-volume-row/component.js
app/components/container/form-volume-row/template.hbs
app/components/container/form-volumes/component.js
app/components/container/form-volumes/template.hbs
app/components/container/new-edit/template.hbs
app/components/cru-volume-claim-template/component.js
app/components/cru-volume-claim-template/template.hbs
app/components/modal-new-vct/component.js
app/components/modal-new-vct/template.hbs
translations/en-us.yaml

======
Add support for Volume Claim Templates on StatefulSet workloads
======
New feature
Linked Issues
======
rancher/rancher#15519
https://github.com/rancher/rancher/issues/17283
======
Currently there is an upstream k8s bug that prevents updates to statefulset workloads with volume templates so edits to workloads like this fail to update.

Add support for volume claim templates

---

app/styles/components/_page-header.scss

======
Fixed global header project links being too tall
Fixed global header cluster & project link hover colors
Fixed paddings on li's and links
======
Bugfix
Linked Issues
======
rancher/rancher#17310
======
N/A

fix the global header dropdown menu styles

---

app/models/cluster.js

======
I guess this is a typo introduce in https://github.com/rancher/ui/pull/2553/files#diff-23384eb2c488b394fc290b7dc3b6e627R13
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17333
https://github.com/rancher/rancher/issues/17335
https://github.com/rancher/rancher/issues/17334
======

Fix cluster auto update issue

---

app/components/container/form-volumes/component.js

======
Only set workload `statefulSetConfig` field if the workload is a stateful set.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17338
======

Fix workload deploy issue

---

app/authenticated/project/route.js
app/catalog-tab/launch/controller.js
app/catalog-tab/launch/route.js
app/models/cluster.js
lib/monitoring/addon/cluster-setting/template.hbs
lib/monitoring/addon/components/enable-monitoring/component.js
lib/monitoring/addon/components/enable-monitoring/template.hbs
lib/monitoring/addon/project-setting/template.hbs
lib/monitoring/translations/en-us.yaml
lib/monitoring/translations/zh-hans.yaml

======
Simplify enable cluster monitoring page
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17306
======

Simplify enable cluster monitoring page

---

lib/pipeline/addon/components/settings-git/component.js
lib/pipeline/addon/components/settings-git/template.hbs
lib/pipeline/translations/en-us.yaml
lib/pipeline/translations/zh-hans.yaml

======
Support configuring custom CA root certificate in pipeline
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17314
======

Support configuring custom CA root certificate in pipeline

---

lib/pipeline/addon/components/step-summary/template.hbs
lib/pipeline/addon/components/steps/step-apply-catalog/component.js
lib/pipeline/addon/components/steps/step-apply-catalog/template.hbs
lib/pipeline/addon/components/steps/step-push-catalog/component.js
lib/pipeline/addon/components/steps/step-push-catalog/template.hbs
lib/pipeline/translations/en-us.yaml
lib/pipeline/translations/zh-hans.yaml

======
At the moment it is called catalog but we are using it as the catalog template. Rename it to avoid confusion in API/pipeline file.
We use catalogTemplate + version to locate the chart we want to deploy/upgrade.
Backend changed the field name. So we should change it as well.
As this is a new feature in 2.2, so it's not a breaking api change.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17277
======

Rename catalog field to catalogTemplate in pipeline

---

lib/alert/addon/components/alert/form-project-rule-row/component.js
lib/alert/addon/components/alert/form-project-rule-row/template.hbs
lib/shared/addon/components/input-slider/component.js
lib/shared/addon/components/input-slider/template.hbs

======
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17353
======

Alert Group - Slider sync sliding of multiple Alert Rules

---

app/components/volume-source/source-custom-log-path/component.js
app/mixins/logging-model.js
app/styles/layout/_layout.scss
lib/logging/addon/components/logging/form-log-format/template.hbs
lib/logging/addon/components/logging/form-log-ssl/component.js
lib/logging/addon/components/logging/form-log-ssl/template.hbs
lib/logging/addon/components/logging/form-test/component.js
lib/logging/addon/components/logging/form-test/template.hbs
lib/logging/addon/components/logging/input-logging-config/component.js
lib/logging/addon/components/logging/input-logging-config/template.hbs
lib/logging/addon/components/logging/new-edit/component.js
lib/logging/addon/components/logging/new-edit/template.hbs
lib/logging/addon/components/logging/target-elasticsearch/component.js
lib/logging/addon/components/logging/target-elasticsearch/template.hbs
lib/logging/addon/components/logging/target-kafka/component.js
lib/logging/addon/components/logging/target-kafka/template.hbs
lib/logging/addon/components/logging/target-splunk/component.js
lib/logging/addon/components/logging/target-splunk/template.hbs
lib/logging/addon/components/logging/target-syslog/component.js
lib/logging/addon/components/logging/target-syslog/template.hbs
lib/logging/translations/en-us.yaml
lib/logging/translations/zh-hans.yaml
lib/shared/addon/components/input-text-file/component.js
lib/shared/addon/components/input-text-file/template.hbs
lib/shared/addon/components/textarea-autogrow/component.js
lib/shared/addon/utils/constants.js

======
1. Add the test button to test logging.
2. Add system log checkbox.
3. Remove ssl hide.
4. Add advanced mode for edit as a file.
5. Add 'none' format.
======
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
Linked Issues
======
https://github.com/rancher/rancher/issues/17226
https://github.com/rancher/rancher/issues/17228
https://github.com/rancher/rancher/issues/16374
https://github.com/rancher/rancher/issues/17229
======

Logging feature && bug

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js
translations/en-us.yaml
translations/zh-hans.yaml

======
======
Linked Issues
======
https://github.com/rancher/rancher/issues/15396
======

Add cluster root filed for edit as a file

---

lib/login/addon/components/login-user-pass/component.js
lib/login/addon/components/login-user-pass/template.hbs
lib/login/addon/login/controller.js
lib/login/addon/login/template.hbs
translations/en-us.yaml
translations/zh-hans.yaml

======
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17153
======

Use one set of fields for external and local auth

---

app/components/container/form-security/component.js

======
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17267
======

Fix units for CPU/Memory resource reservation

---

lib/alert/addon/components/alert-rule/new-edit/template.hbs
lib/alert/addon/components/alert/form-advanced/component.js
lib/alert/addon/components/alert/form-advanced/template.hbs
lib/alert/addon/components/alert/new-edit/template.hbs

======
======
Linked Issues
======
https://github.com/rancher/rancher/issues/15663
======

Support more alert group config

---

lib/alert/addon/edit-rule/route.js
lib/alert/addon/mixins/edit-or-clone.js
lib/alert/addon/new-rule/route.js

======
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17475
======

Fix clone cluster alert rule throw an error

---

lib/alert/addon/components/alert/form-project-rule-row/component.js
lib/alert/addon/components/alert/form-project-rule-row/template.hbs
lib/shared/addon/components/input-slider/component.js

======
The input slider was never setting its value correctly as it was using a destructured `orig` variable that didn't exist. 
I also refactored out the dynamic element id added in https://github.com/rancher/ui/commit/a2b5a95750798f30df8c63442c6d08dd0eaa3b05#diff-6320704a1fe24a29c92ef00724263ead because the elementId is already dynamically generated by the framework at runtime and we were hitting errors caused by resetting the dynamic elementId after init. 
======
Bugfix
Linked Issues
======
rancher/rancher#17522
======

fix input-slider not sliding and elementId after init errors

---

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js
lib/shared/addon/components/cluster-driver/driver-amazoneks/template.hbs
lib/shared/addon/components/form-versions/component.js
lib/shared/addon/utils/parse-version.js
translations/en-us.yaml
translations/zh-hans.yaml

======
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17082
======

Update EKS regions and add k8s version

---

app/models/workload.js
app/styles/base/_helpers.scss
app/styles/components/_banners.scss
app/workload/template.hbs
translations/en-us.yaml
translations/zh-hans.yaml

======
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17246
======

Add current scale in Workload view

---

lib/alert/addon/components/alert/form-cluster-rule-row/component.js
lib/alert/addon/components/alert/form-cluster-rule-row/template.hbs
lib/alert/addon/components/alert/form-project-rule-row/template.hbs

======
1. In cluster alert, the passed rightly param to `remove` action.
2. In project alert, add the missed action.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17448
======

Unable to remove alert rules from an alert group

---

app/models/service.js

======
Add missed scope service.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17530
======

Service proxy endpoint doesn't work in master

---

lib/global-admin/addon/components/new-multi-cluster-app/component.js

======
Fixes a weird edge case where a project doesn't have a cluster associated with it
======
Bug 
Linked Issues
======
======

Fix issue with a getting display name on project with no cluster

---

lib/login/addon/login/template.hbs

======
Add a condition that when not init error, the auth shows. when there is init error, only reload button display.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17578
======

Fix Login dialog display both reload and local auth

---

lib/shared/addon/components/form-ingress-backends/component.js

======
There is a breaking change in API. We have to use array for ingress rule path.
There is no UX change in UI.
Backend PR is https://github.com/rancher/rancher/pull/17129
We need to merge backend and frontend PRs together to make sure the feature is not broken in master build
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17529
======

Use array for ingress rule path

---

app/models/globaldnsprovider.js
app/styles/abstracts/_mixins.scss
app/styles/pages/_host.scss
lib/global-admin/addon/global-dns/providers/new/controller.js
lib/global-admin/addon/global-dns/providers/new/route.js
lib/global-admin/addon/global-dns/providers/new/template.hbs
lib/global-admin/addon/templates/-cloudflare-dns-provider.hbs
public/assets/images/providers/cloudflare.svg
translations/en-us.yaml

======
Global DNS UI: Add option for cloudflare provider in UI
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17551
======

Add option for cloudflare provider in UI for global dns

---

lib/login/addon/components/login-user-pass/template.hbs

======
Add `name` to  `login-user-pass` template `login-username` and `login-password` inputs 
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17591

add name property to login-user-pass template inputs

---

app/components/modal-rotate-certificates/component.js
app/components/modal-rotate-certificates/template.hbs
translations/en-us.yaml

======
The previous UX for rotate certs was not as clear as it could be, tweaked the UX to indicate to users the different options available to them when rotating certs.
======
Bugfix
Linked Issues
======
rancher/rancher#17453
======
N/A

change the way rotate certificates modal works

---

app/models/ingress.js
lib/shared/addon/components/form-ingress-backends/component.js

======
Fix the issue that the url in ingress role is incorrect
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17622
======

Fix the issue that the url in ingress role is incorrect

---

lib/shared/addon/components/form-engine-opts/component.js
lib/shared/addon/components/form-engine-opts/template.hbs

======
New engine options for node templates
======
New Feature
Linked Issues
======
rancher/rancher#17547
======

Update recommended node template engine and choices

---

app/models/template.js

======
Fallback to use catalog id for catalog display name if there is no permission.
Project owner can not list catalogs or cluster catalogs. So we can fallback to use the catalog id for project owner
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17625
======

Fallback to use catalog id for catalog display name if there is no permission

---

lib/global-admin/addon/templates/-cloudflare-dns-provider.hbs
lib/global-admin/addon/templates/-route53-dns-provider.hbs

======
Error messages are not presented global dns page
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17636
======

Error messages are not presented global dns page

---

app/models/service.js

======
If you add an ingress with a service as the target, you can only select the port number in UI.
However, Kubernetes supports port name as the target. So we should add port name into the choices as well
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17640
======

Support port name for ingress rule

---

app/components/new-edit-ingress/template.hbs
app/ingress/template.hbs
app/ingresses/run/template.hbs
lib/shared/addon/components/form-ingress-backends/template.hbs
lib/shared/addon/components/form-ingress-rows/template.hbs
lib/shared/addon/components/form-ingress-rule/component.js
lib/shared/addon/components/form-ingress-rule/template.hbs
lib/shared/addon/components/schema/input-dns-record/template.hbs
translations/en-us.yaml

======
1. After user created an ingress, users have to refresh the browser to see the ingress detail page
2. If the target of the ingress is a server, you cannot go to the service detail page with the link in ingress detail page
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17644
https://github.com/rancher/rancher/issues/17575
======
For issue 1, we should not pass `model.ingress.namespace` into `form-namespace`
`form-namespace` will update `namespace` field of ingress. 
So the record in cache will has an own property `namespace`. However, the new data comes from websocket doesn't have the own property `namespace` 
`ember-api-store` will remove the `namespace` …

Fix ingress detail page issue

---

lib/logging/addon/components/logging/target-kafka/template.hbs
lib/logging/translations/en-us.yaml
lib/logging/translations/ja-jp.yaml
lib/logging/translations/zh-hans.yaml
lib/logging/translations/zh-hant.yaml

======
Fix translations issues
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17498
https://github.com/rancher/rancher/issues/17588
======

Fix translations issues

---

lib/shared/addon/utils/amazon.js

======
https://aws.amazon.com/ec2/instance-types/p3/
Add the following aws instance types
p3.2xlarge
p3.8xlarge
p3.16xlarge
p3dn.24xlarge
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17377
======

Add P3 AWS instance types

---

lib/logging/addon/components/logging/target-elasticsearch/template.hbs
lib/logging/translations/en-us.yaml

======
Fix translations issues
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17497
======

Fix translation issue

---

lib/global-admin/addon/multi-cluster-apps/catalog/launch/route.js

======
Pass the correct number of args to randomStr utility
======
Bugfix
Linked Issues
======
rancher/rancher#17651
======
N/A

Fix incorrect arguments that prevents mc app cloning

---

lib/global-admin/addon/components/new-multi-cluster-app/component.js
lib/global-admin/addon/multi-cluster-apps/catalog/launch/route.js
lib/global-admin/addon/multi-cluster-apps/catalog/launch/template.hbs
lib/shared/addon/growl/service.js
lib/shared/addon/mixins/cattle-transitioning-resource.js

======
Fixed growl notifications that was found while testing MC apps
Fixed missing workloads for cloned MC apps
Fixed extra target that was being added to cloned MC apps
======
Bugfixes
Linked Issues
======
rancher/rancher#17669
rancher/rancher#17680
rancher/rancher#17679
======
N/A

Multi-Cluster App Bugs

---

lib/logging/addon/components/logging/form-log-ssl/template.hbs
lib/logging/addon/components/logging/new-edit/component.js
lib/logging/addon/components/logging/target-kafka/component.js
lib/logging/addon/components/logging/target-kafka/template.hbs
lib/logging/translations/en-us.yaml
lib/logging/translations/zh-hans.yaml

======
1. Add 4 fields for backend API added: 
```
saslPassword
saslPassword
saslType
saslScramMechanism
```
2. Refactor Kafka `wiilSave` function.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17555
======

Support Kafka sasl/scram-256

---

lib/pipeline/addon/components/steps/step-apply-catalog/component.js

======
Fix pipeline deploy catalog issue. It doesn't show the correct selected project/cluster level catalog when edit the step.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17685
======

Fix pipeline deploy catalog issue

---

lib/monitoring/addon/components/enable-monitoring/template.hbs

======
Fix node exporter config issue
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17691
======

Fix node exporter config issue

---

lib/global-admin/addon/components/new-multi-cluster-app/component.js
lib/shared/addon/components/answer-override-row/component.js
lib/shared/addon/mixins/catalog-app.js
translations/en-us.yaml

======
Fixes Missing project/cluster indicator broke answer overrides for mc apps
Fix missing mc app answer overrides and upgrade answer overrides
Add a clearer mc app target error message when no pId 
======
Bugfix
Linked Issues
======
rancher/rancher#16941
rancher/rancher#17678
rancher/rancher#17706
======
N/A

Multi Cluster App Fixes

---

app/models/user.js
lib/global-admin/addon/accounts/index/controller.js
lib/global-admin/addon/accounts/index/template.hbs
lib/global-admin/addon/components/site-access/component.js
lib/global-admin/addon/components/site-access/template.hbs
lib/global-admin/addon/security/authentication/controller.js
lib/global-admin/addon/security/authentication/template.hbs
translations/en-us.yaml

======
Tweak the UX of the `refreshauthprovideraccess` action  for the collection (moved to user page)
Add individual `refreshauthprovideraccess` action to the user model
Add description for the related settings
======
Bugfix/Enhancement
Linked Issues
======
rancher/rancher#17707
rancher/rancher#17075
======
N/A

Auth Token Refresh Bugs

---

lib/monitoring/addon/components/node-conditions/component.js

======
Fix incorrect status bar issue in node dashboard
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17767
======

Fix incorrect status bar issue in node dashboard

---

lib/global-admin/addon/multi-cluster-apps/index/route.js
lib/shared/addon/catalog/service.js

======
Refactor index page and how we load template versions for the upgrade info on the mc  app.
======
Bugfix
Linked Issues
======
rancher/rancher#17790
======
N/A

MC Apps Performance

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js

======
======
Bugfix
Linked Issues
======
rancher/rancher#17772
======
N/A

Fix backup settings being overwritten on edit of cluster

---

lib/shared/addon/components/cru-cluster/template.hbs

======
Fix cluster error message missing issue when cluster members try to edit the members
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17801
======

Fix cluster error message missing issue

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js

======
Added logic to ensure that the backup strategy is set correctly on init. 
======
Bugfix
Linked Issues
======
rancher/rancher#17772
======
N/A

Ensure backup strategy is initialized correctly

---

lib/global-admin/addon/components/new-multi-cluster-app/component.js
lib/shared/addon/components/answer-override-row/component.js

======
======
bug
Linked Issues
======
rancher/rancher#17820
======

Fix defaults overwriting inputs

---

lib/shared/addon/components/cluster-driver/driver-azureaks/component.js
lib/shared/addon/components/cluster-driver/driver-azureaks/template.hbs
translations/en-us.yaml
translations/zh-hans.yaml

======
1. Change filed name:  osDiskSizeGb => agentOsdiskSize
2. Add fields 
```
enableMonitoring  
logAnalyticsWorkspaceResourceGroup
 logAnalyticsWorkspace
// according backend implement, UI won’t show logAnalyticsWorkspaceResourceGroup and 
// logAnalyticsWorkspace now.
enableHttpApplicationRouting
tags
networkPolicy
```
3. Support AKS editable in UI.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17262
======

Add new field for AKS

---

lib/pipeline/addon/components/settings-git/component.js
lib/pipeline/addon/components/settings-git/template.hbs
lib/pipeline/translations/en-us.yaml

======
Support config the cpu/memory request and limit in pipeline setting page
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17569
======

Support request and limit for pipeline executor

---

lib/nodes/addon/components/driver-amazonec2/component.js

======
Fix aws node template save button text issue
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17781
======

Fix aws node template issue

---

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js
lib/shared/addon/components/cluster-driver/driver-amazoneks/template.hbs
lib/shared/addon/components/new-select/component.js
translations/en-us.yaml

======
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17762
======

EKS form-version align issue

---

lib/shared/addon/components/catalog-index/component.js

======
======
Bugfix
Linked Issues
======
rancher/rancher#17837
======
N/A

add truthy check for catalogid's when launching MC apps

---

app/components/container/form-volumes/component.js
app/components/container/new-edit/template.hbs

======
Update check for `isStatefulSet` to properly show and hide the volume claim template option when creating workloads
Do not save VCT resources when workload saves, they are not individual resources but belong to the `statefulsetconfig`
======
Bugfix
Linked Issues
======
rancher/rancher#17738
rancher/rancher#17739
======
N/A

Volume Claim Template Bugs

---

app/styles/components/_button.scss

adjust css for better alignment
https://github.com/rancher/rancher/issues/16924

button alignment

---

lib/global-admin/addon/components/new-multi-cluster-app/component.js
lib/global-admin/addon/components/new-multi-cluster-app/template.hbs
lib/global-admin/addon/multi-cluster-apps/catalog/launch/route.js
lib/shared/addon/components/answer-override-row/component.js
lib/shared/addon/components/answer-override-row/template.hbs
lib/shared/addon/components/input-custom-answers/component.js
lib/shared/addon/components/input-custom-answers/template.hbs

======
Fix bugs with question-less helm charts
======
Bugfix
Linked Issues
======
rancher/rancher#17888
======

Mc apps bugs

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js

======
localClusterAuthEndpoint does not require CA certs but I was checking for them.
======
Bugfix
Linked Issues
======
rancher/rancher#17927
======

fix error check on un-required field

---

lib/pipeline/translations/en-us.yaml

======
Fix text issues on pipeline page
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17943
======

Fix text issues on pipeline page

---

lib/shared/addon/utils/constants.js

======
Show locked roles
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17925
======

Show locked roles

---

app/authenticated/cluster/projects/new-ns/controller.js
app/authenticated/cluster/projects/new-ns/template.hbs
app/components/container-default-limit/component.js
app/components/container-default-limit/template.hbs
app/components/container/new-edit/component.js
app/components/modal-edit-namespace/component.js
app/components/modal-edit-namespace/template.hbs
app/components/new-edit-project/component.js
app/components/new-edit-project/template.hbs
app/components/project-quota-row/template.hbs
app/components/project-resource-quota/template.hbs
app/models/container.js
lib/shared/addon/components/form-namespace/component.js
translations/en-us.yaml

======
1. Users can config them in new/edit project page.
2. Users can config them in new/edit namespace page.
3. The default values for them in create namespace page are from project's containerDefaultResourceLimit field
4. Do not force specifying resource limit if related ns containerDefaultResourceLimit is defined
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16753
======

Support container default resource limit

---

lib/shared/addon/components/cluster-driver/driver-amazoneks/template.hbs
translations/en-us.yaml

======
Add an advanced option for user data in `Nodes` section
Add node volume size field in `Nodes` section
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17711
https://github.com/rancher/rancher/issues/17690
======

Support user-data and volume size for EKS

---

lib/logging/addon/components/logging/form-log-sasl/component.js
lib/logging/addon/components/logging/form-log-sasl/template.hbs
lib/logging/addon/components/logging/form-log-ssl/component.js
lib/logging/addon/components/logging/form-log-ssl/template.hbs
lib/logging/addon/components/logging/input-logging-config/component.js
lib/logging/addon/components/logging/input-logging-config/template.hbs
lib/logging/addon/components/logging/new-edit/component.js
lib/logging/addon/components/logging/new-edit/template.hbs
lib/logging/addon/components/logging/target-kafka/template.hbs
lib/logging/addon/components/logging/target-syslog/component.js
lib/logging/addon/components/logging/target-syslog/template.hbs
lib/logging/translations/en-us.yaml
lib/shared/addon/components/copy-to-clipboard/component.js

======
1. File target will synch with the form target.
2. Fix Kafka SASL issue.
3. Add CA config for custom target.
4. Change the custom target CA path format.
5. https://github.com/rancher/rancher/issues/17829
Add `enableTls` for syslog, and refactor syslog `willSave`  function. It needs backend merged first.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17751
https://github.com/rancher/rancher/issues/17659
https://github.com/rancher/rancher/issues/17697
https://github.com/rancher/rancher/issues/17598
https://github.com/rancher/rancher/issues/17829
======

Logging issue

---

app/initializers/aws-sdk.js
app/instance-initializers/nav.js
app/models/cloudcredential.js
lib/global-admin/addon/components/cru-cloud-credential/component.js
lib/global-admin/addon/components/cru-cloud-credential/template.hbs
lib/global-admin/addon/components/modal-add-cloud-key/component.js
lib/global-admin/addon/components/modal-add-cloud-key/template.hbs
lib/global-admin/addon/routes.js
lib/global-admin/addon/security/cloud-keys/index/controller.js
lib/global-admin/addon/security/cloud-keys/index/route.js
lib/global-admin/addon/security/cloud-keys/index/template.hbs
lib/global-admin/app/components/cru-cloud-credential/component.js
lib/global-admin/app/components/modal-add-cloud-key/component.js
lib/nodes/addon/components/driver-amazonec2/component.js
lib/nodes/addon/components/driver-amazonec2/template.hbs
lib/nodes/addon/components/driver-azure/component.js
lib/nodes/addon/components/driver-azure/template.hbs
lib/nodes/addon/components/driver-digitalocean/component.js
lib/nodes/addon/components/driver-digitalocean/template.hbs
lib/nodes/addon/components/driver-vmwarevsphere/component.js
lib/nodes/addon/components/driver-vmwarevsphere/template.hbs
lib/nodes/addon/node-templates/route.js
lib/shared/addon/components/form-auth-cloud-credential/component.js
lib/shared/addon/components/form-auth-cloud-credential/template.hbs
lib/shared/addon/mixins/modal-base.js
lib/shared/addon/mixins/node-driver.js
lib/shared/app/components/form-auth-cloud-credential/component.js
translations/en-us.yaml

======
This adds the new feature of cloud credentials which adds a new cloud keys page and the ability to select or add a new cloud key via the node templates. It swaps out using the old credentials to proxy data from various cloud providers to using the cloud credential.
======
New feature
Linked Issues
======
rancher/rancher#16796
======
N/A

cloud credentials

---

app/components/namespace-group/template.hbs

======
`model` always has a default value. So we need to use `displayName`.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17894
======

Fix namespace group text issue

---

lib/shared/addon/utils/azure-choices.js

======
Add new region to AKS
======
"bugfix"
Linked Issues
======
https://github.com/rancher/rancher/issues/18009
======

Add australiasoutheast to AKS regions

---

app/mixins/verify-auth.js
app/verify-auth/route.js
lib/shared/addon/saml/service.js

======
Add error parsing and new params to verify-auth route to handle errors from the SAML auth provider when turning on auth for the first time
======
Bugfix
Linked Issues
======
rancher/rancher#15530
======
N/A

Saml Redirect Issues

---

lib/shared/addon/mixins/node-driver.js

======
======
Linked Issues
======
======

fix typo that prevents DO keys from showing in select

---

app/mixins/logging-model.js
lib/logging/addon/components/logging/form-log-format/template.hbs
lib/logging/addon/components/logging/new-edit/component.js
lib/logging/translations/en-us.yaml

======
API Changed
Change `excludeSystemComponent` to `includeSystemComponent`
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18026
======

Change `excludeSystemComponent` to `includeSystemComponent`

---

lib/shared/addon/components/cluster-driver/driver-googlegke/component.js
lib/shared/addon/components/cluster-driver/driver-googlegke/template.hbs
lib/shared/addon/components/form-gke-taints/component.js
lib/shared/addon/components/form-gke-taints/template.hbs
lib/shared/addon/components/form-value-array/template.hbs
lib/shared/addon/components/gke-access-scope/component.js
lib/shared/addon/components/gke-access-scope/template.hbs
lib/shared/addon/components/searchable-select/component.js
lib/shared/app/components/form-gke-taints/component.js
lib/shared/app/components/gke-access-scope/component.js
translations/en-us.yaml
translations/zh-hans.yaml

======
1. Add two request to obtain GKE data.
```
/meta/gkeSubnetworks
/meta/gkeServiceAccounts
```
2. Add fields according to backend API added.
https://github.com/rancher/kontainer-engine/pull/106#issue-240984502
It needs backend merged first.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/16412
https://github.com/rancher/rancher/issues/17990
https://github.com/rancher/rancher/issues/17991
https://github.com/rancher/rancher/issues/17992
https://github.com/rancher/rancher/issues/17993
======

Add GKE fields

---

app/components/form-node-affinity/template.hbs
app/models/globaldnsprovider.js
app/styles/abstracts/_mixins.scss
app/styles/pages/_host.scss
lib/alert/addon/components/alert/form-alert-rules/template.hbs
lib/global-admin/addon/global-dns/providers/new/controller.js
lib/global-admin/addon/global-dns/providers/new/route.js
lib/global-admin/addon/templates/-alidns-dns-provider.hbs
lib/shared/addon/components/form-ingress-rule/template.hbs
lib/shared/addon/components/form-ssl-termination/template.hbs

======
Support Aliyun dns
======
Linked Issues
======
rancher/rancher#17839
======

Support Aliyun dns

---

lib/global-admin/addon/components/new-multi-cluster-app/component.js
lib/global-admin/addon/components/new-multi-cluster-app/template.hbs
lib/global-admin/addon/multi-cluster-apps/catalog/launch/controller.js
lib/shared/addon/components/form-multi-cluster-targets/component.js
lib/shared/addon/components/form-multi-cluster-targets/template.hbs
lib/shared/addon/components/searchable-select/component.js
lib/shared/addon/components/searchable-select/template.hbs
lib/shared/addon/mixins/cattle-transitioning-resource.js
lib/shared/app/components/form-multi-cluster-targets/component.js
translations/en-us.yaml

======
Add roles selection to multi-cluster apps
Refactor multi-cluster apps add target section into component
Add new project target actions for multi-cluster apps
======
Enhancement & Bug
Linked Issues
======
rancher/rancher#17853
rancher/rancher#17975
======
N/A

Multi cluster app RBAC and Actions features

---

lib/logging/addon/components/logging/form-log-format/component.js
lib/logging/addon/components/logging/form-log-format/template.hbs
lib/logging/translations/zh-hans.yaml

======
Remove project level `includeSystemComponent` according to https://github.com/rancher/rancher/issues/15555#issuecomment-463461965
======
Linked Issues
======
https://github.com/rancher/rancher/issues/15555
======

Remove project level includeSystemComponent 

---

lib/global-admin/addon/components/new-multi-cluster-app/component.js

======
======
bug fix
Linked Issues
======
rancher/rancher#18130
======
N/A

fix the way projects are added and removed that stops saving

---

app/models/cluster.js
lib/monitoring/addon/components/enable-monitoring/component.js
lib/monitoring/addon/components/enable-monitoring/template.hbs
lib/monitoring/translations/en-us.yaml
lib/monitoring/translations/zh-hans.yaml
lib/shared/addon/components/metrics-summary/template.hbs
lib/shared/addon/mixins/grafana.js

======
Support edit monitoring config
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18004
https://github.com/rancher/rancher/issues/17745
https://github.com/rancher/rancher/issues/17734
https://github.com/rancher/rancher/issues/17392
======

Support edit monitoring config

---

app/models/member.js
lib/global-admin/addon/components/new-multi-cluster-app/component.js
lib/global-admin/addon/components/new-multi-cluster-app/template.hbs
lib/global-admin/addon/global-dns/entries/new/controller.js
lib/global-admin/addon/global-dns/entries/new/route.js
lib/global-admin/addon/global-dns/entries/new/template.hbs
lib/global-admin/addon/global-dns/providers/new/controller.js
lib/global-admin/addon/global-dns/providers/new/route.js
lib/global-admin/addon/global-dns/providers/new/template.hbs
lib/global-admin/addon/templates/-alidns-dns-provider.hbs
lib/global-admin/addon/templates/-cloudflare-dns-provider.hbs
lib/global-admin/addon/templates/-route53-dns-provider.hbs
lib/shared/addon/components/form-members-global-access/component.js
lib/shared/addon/components/form-members-global-access/template.hbs
lib/shared/app/components/form-members-global-access/component.js
translations/en-us.yaml

======
Adds new Members section to Global DNS Providers and Entries. Members will only have owner role.
Adds logic to handle the switch editable projectIds to the add/remove project ids actions. The UX will not change for this, but when saving the actions to add and remove new projects will fire instead the project ids being sent with the resource. 
This also adds the TTL input to Global DNS Entry creation. 
======
Enhancement
Linked Issues
======
rancher/rancher#17976
rancher/rancher#18101
======
N/A

Add Global DNS Provider and Entry RBAC

---

app/components/new-catalog/component.js

======
Bug fix for yaml issue
false was converted to 'false'
======
Linked Issues
======
https://github.com/rancher/rancher/issues/13158
======

Bug fix for yaml issue

---

lib/monitoring/addon/components/cluster-dashboard/component.js
lib/shared/addon/components/form-engine-opts/component.js
server/proxies/api.js

======
If a particular component status is missing from the cluster, call that component "healthy".  K3s and some cloud providers are missing some statuses.
Also support dev proxying to a L7 load balancer better
======
Enhancement

Consider missing cluster component status healthy, engine versions, dev proxy

---

lib/shared/addon/components/cluster-driver/driver-aliyunkcs/component.js
lib/shared/addon/components/cluster-driver/driver-aliyunkcs/template.hbs
translations/en-us.yaml
translations/zh-hans.yaml

======
Support alibaba ACK managed kubernetes
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17825
https://github.com/rancher/rancher/issues/17827
======
We need to merge https://github.com/rancher/kontainer-engine-driver-aliyun/pull/7/files first

Support alibaba ACK managed kubernetes

---

app/components/new-edit-ingress/component.js

======
Fix the issue that ns is wrong in edit ingress page
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18168
======

Fix the issue that ns is wrong in edit ingress page

---

lib/global-admin/addon/components/cru-cloud-credential/template.hbs

======
======
Linked Issues
======
======

fix css on amazon cloudkey

---

lib/shared/addon/components/cluster-driver/driver-aliyunkcs/component.js
lib/shared/addon/components/cluster-driver/driver-aliyunkcs/template.hbs

======
- Aliyun normal k8s and managed k8s support different k8s versions
- Managed k8s requires at least 2 nodes
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17825
======

Fix aliyun hosted k8s cluster version issue

---

app/models/kontainerdriver.js
translations/en-us.yaml
translations/zh-hans.yaml

======
Fix the issue that cluster driver name is incorrect
name field will change after the cluster driver is downloaded
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18208
======

Fix the issue that cluster driver name is incorrect

---

app/models/target.js
lib/global-admin/addon/clusters/new/route.js
lib/global-admin/addon/components/multi-cluster-app/template.hbs
lib/shared/addon/components/form-multi-cluster-targets/template.hbs
translations/en-us.yaml

======
Ensure we show unlinked project id when displaying mc-app that the user doesn't have access to some of or all of the projects
Ensure cloud credentials are loaded on a fresh page load from add cluster -> add node template modal.
======
Bug Fix
Linked Issues
======
https://github.com/rancher/rancher/issues/18153
https://github.com/rancher/rancher/issues/18225
======

Blocker Bugs

---

lib/shared/addon/components/cluster-driver/driver-googlegke/component.js

======
It shouldn't send `https://www.googleapis.com/auth/none` to GKE driver. So I remove it.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18226
======

Fix GKE cluster custom access scope

---

app/components/container/new-edit/template.hbs
app/instance-initializers/nav.js
lib/monitoring/addon/components/enable-monitoring/template.hbs
lib/monitoring/translations/en-us.yaml
lib/monitoring/translations/zh-hans.yaml

======
Support enable project monitoring only
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18204
======

Support enable project monitoring only

---

lib/monitoring/addon/components/enable-monitoring/template.hbs

======
Update the button text in enable monitoring page
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18004
======

Update the button text in enable monitoring page

---

app/authenticated/cluster/backups/controller.js
app/authenticated/cluster/backups/template.hbs

======
======
New Feature
Linked Issues
======
rancher/rancher#18257
======
N/A

add state badge to etcd backups page

---

app/models/cloudcredential.js
lib/global-admin/addon/components/cru-cloud-credential/component.js
lib/global-admin/addon/components/cru-cloud-credential/template.hbs
lib/global-admin/addon/components/modal-add-cloud-key/template.hbs
lib/global-admin/addon/security/cloud-keys/index/controller.js
lib/global-admin/addon/security/cloud-keys/index/template.hbs
lib/shared/addon/components/form-auth-cloud-credential/component.js
lib/shared/addon/components/form-auth-cloud-credential/template.hbs
lib/shared/addon/mixins/node-driver.js
translations/en-us.yaml

======
Set default cloud credential config to amazon
Cloud credential design changes
Sort cloud credentials correctly in the dropdown
Select the only cloud credential if only a single credential exists
Changes for cloud credential search
Make cloud credential editable
======
Bugfix
Linked Issues
======
rancher/rancher#18079
rancher/rancher#18091
rancher/rancher#18094
rancher/rancher#18095
rancher/rancher#18096
rancher/rancher#18097
======

Cloud Key Bugs

---

lib/shared/addon/components/form-engine-opts/component.js
lib/shared/addon/utils/constants.js

======
======
Enhancement
Linked Issues
======
rancher/rancher#18306
======
N/A

update experimental version of RKE K8s

---

lib/logging/addon/components/logging/input-logging-config/component.js
lib/logging/addon/components/logging/new-edit/component.js

======
Add init customTarget function after save.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18220
======

Fix logging does not clear the cache after save

---

lib/shared/addon/components/answer-override-row/template.hbs

======
When the question cannot be selected, display an input.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18132
======

Fix question cannot input for catalog app

---

lib/logging/addon/components/logging/form-test/component.js
lib/logging/addon/components/logging/form-test/template.hbs
lib/logging/addon/components/logging/new-edit/template.hbs
lib/logging/translations/en-us.yaml
lib/logging/translations/zh-hans.yaml

======
Test                         => Dry Run
Testing                    => Running
Settings validated. => Dry run success.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18364
======

Change button text from "Test" to "Dry Run" for advance mode logging target

---

lib/logging/addon/components/logging/target-flentd/template.hbs

======
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18354
======

Fix Fluentd `CA Certificate PEM` prompt message

---

app/styles/components/_percent-gauge.scss
lib/monitoring/addon/components/nodes-live/component.js
lib/monitoring/addon/components/nodes-live/template.hbs
lib/shared/addon/components/percent-gauge/component.js
lib/shared/addon/utils/percent-gauge.js
lib/shared/addon/utils/used-percent-gauge.js

======
1. Group dashboard gauge text 
https://github.com/rancher/rancher/issues/17040#issuecomment-466628969
2. Using `parseSi ` to parse memory insteadof `parseInt`. It can make sure `used / reserved < 1`.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17040
======

 Group dashboard gauge text

---

app/models/globaldnsprovider.js
lib/global-admin/addon/global-dns/providers/new/route.js
lib/global-admin/addon/templates/-alidns-dns-provider.hbs
lib/global-admin/addon/templates/-cloudflare-dns-provider.hbs
lib/global-admin/addon/templates/-route53-dns-provider.hbs

======
Moving RootDomain field to GlobalDNSProviderSpec
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18359
======

Moving RootDomain field to GlobalDNSProviderSpec

---

app/instance-initializers/nav.js
app/styles/components/_dropdown.scss
lib/global-admin/addon/components/new-multi-cluster-app/component.js
lib/global-admin/addon/components/new-multi-cluster-app/template.hbs
lib/global-admin/addon/global-dns/entries/new/controller.js
lib/global-admin/addon/global-dns/entries/new/template.hbs
lib/nodes/addon/components/driver-amazonec2/template.hbs
lib/nodes/addon/components/modal-edit-node-template/component.js
lib/nodes/addon/components/modal-edit-node-template/template.hbs
lib/shared/addon/components/top-errors/component.js
translations/en-us.yaml

======
Move gdns and MCapp under tools at the global level
top-errors should set errors to empty array on init to ensure that we always have a fresh errors object when initializing the top-errors component
Fix role label on mc app
Fix ec2 nt "next" label
Fix hbs styles and added label for's + id's for accessability
======
bugfixes
Linked Issues
======
rancher/rancher#18378
rancher/rancher#18376
rancher/rancher#18373
rancher/rancher#18227
======
N/A

2.2 Bug fixes

---

app/styles/components/_badge-state.scss
lib/global-admin/addon/components/multi-cluster-app/template.hbs
lib/shared/addon/components/badge-state/component.js
lib/shared/addon/components/badge-state/template.hbs

======
Show individual app states for mc-apps
======
Bugfix
Linked Issues
======
rancher/rancher#18337
======

Show individual app states for mc-apps

---

lib/monitoring/addon/components/enable-monitoring/component.js
lib/shared/addon/components/graph-area/component.js
lib/shared/addon/components/metrics-summary/template.hbs

======
Fix monitoring expand all issue
Fix monitoring status display issue when switching between projects
======
Linked Issues
======
rancher/rancher#18317
rancher/rancher#18330
======

Monitoring fix

---

lib/logging/addon/components/logging/input-logging-config/component.js
lib/logging/addon/components/logging/new-edit/component.js
lib/logging/addon/components/logging/new-edit/template.hbs

======
After save, when the current target is not `customTarget`, set `customContent` to `<match *>\n</match>`.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18220
======

Fix Logging does not clear the cache

---

lib/logging/addon/components/logging/input-logging-config/component.js

======
It needs backend merge. https://github.com/rancher/rancher/issues/18396
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18374
======

Fix fluentd client cert path and client key path.

---

lib/monitoring/addon/components/nodes-live/component.js
lib/shared/addon/utils/percent-gauge.js
lib/shared/addon/utils/used-percent-gauge.js

======
1. Fix errors throw in the console when cannot obtain metrics.
2. Fix outer ring radius.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18317
======

Fix dashboard gauge when cannot obtain metrics

---

lib/logging/addon/components/logging/input-logging-config/component.js
lib/logging/addon/components/logging/input-logging-config/template.hbs

======
1. Delete `client_cert_key` when CA field change.
It already added in another commit. 
https://github.com/rancher/ui/blob/419cdb64dc41c6ae27a9d3ae36ea031d4e1de14f/lib/logging/addon/components/logging/input-logging-config/component.js#L89
2. Switch target also changes the CA path.
3. Remove useless code.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18394
======

Delete 'client_cert_key' when CA field change

---

lib/logging/addon/components/logging/form-log-ssl/component.js
lib/logging/addon/components/logging/new-edit/component.js
lib/logging/addon/components/logging/target-elasticsearch/component.js
lib/logging/addon/components/logging/target-splunk/component.js

======
Move SSL config deal with to `willSave` function. It can protect from CA change to null when SSL is enabled.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18397
======

Fix ES and Splunk page slide up  after click save and test

---

lib/alert/addon/components/alert-rule/new-edit/template.hbs
lib/alert/addon/components/alert/form-advanced/component.js
lib/alert/addon/components/alert/form-advanced/template.hbs
lib/alert/addon/components/alert/time-duration/template.hbs
lib/alert/translations/en-us.yaml
lib/alert/translations/zh-hans.yaml

======
Alert rule advance option:
Both cluster and project are supported. The default value is `enabled`.
It needs backend merge. 
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17604
======

Add isInherited for alert rule

---

app/models/nodetemplate.js

======
Location and Size fields can not display correctly for newly added node driver in node template list page.
We don't want to change Rancher UI code for a new custom node driver.
Add default displayLocation key (config.region)  and  displaySize key (config.size) in nodetemplate.js file for Node Template Table
If a custom node driver has these two keys, we can show them correctly in node template list page.
======
Linked Issues
======
======

ecs node-driver

---

lib/logging/addon/components/logging/input-logging-config/component.js
lib/logging/addon/components/logging/new-edit/component.js

======
1. Fix `<match *>   ` parse error.
https://github.com/rancher/rancher/issues/18479
2. `<match *>\n${ body }  ${ str }\n</match>` should add `\n`.
https://github.com/rancher/rancher/issues/18476
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18476
https://github.com/rancher/rancher/issues/18479
======

Fix logging adavance mode issue

---

app/styles/components/_percent-gauge.scss
lib/shared/addon/utils/percent-gauge.js
lib/shared/addon/utils/used-percent-gauge.js

======
1. Reduce reserved label strok-width to 2px.
2. Exchange used color and Reserved color for CPU/Memory.
3. Reduce the gap between used-label and reserved-percent.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18377
======

Dashboard used ring style Change

---

lib/shared/addon/mixins/cattle-transitioning-resource.js

======
Change 'Updating' to have text-warning instead of text-info bootstrap class.
This change is to address the request expressed in the below issue for the 'Updating' state to be highlighted yellow.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18062
======
None.

Change updating bootstrap class

---

lib/monitoring/addon/components/nodes-live/component.js
lib/monitoring/translations/en-us.yaml
lib/monitoring/translations/zh-hans.yaml
lib/shared/addon/utils/used-percent-gauge.js
translations/zh-hans.yaml

======
1. Fix tooltip text, `Value` => `Reserved`.
2. Using `nodeName` to match metrics graph name instead of `hostname`.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18500
======

Fix `nodeName` and tooltip text

---

lib/logging/addon/components/logging/new-edit/component.js

======
When `model` change, it should use `didReceiveAttrs` instead of `init`.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18541
======

Fix switch to other projects logging, display wrong config

---

lib/shared/addon/components/cluster-driver/driver-rke/component.js

======
`flannelBackendType` change to `flannel_backend_type ` accoring RKE doc.
https://rancher.com/docs/rke/v0.1.x/en/config-options/add-ons/network-plugins/#flannel-network-plug-in-options
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18542
======

Fix Windows - host-gw network cannot setup

---

lib/shared/addon/components/cluster-driver/driver-azureaks/component.js
lib/shared/addon/components/form-engine-opts/component.js

======
Updates docker engine options
Ensure that Azure uses the latest supported version from the versions call
======
Bugfix
Linked Issues
======
rancher/rancher#18536
rancher/rancher#18532
======
N/A

Update engine version suggestions

---

lib/shared/addon/components/sortable-table/component.js

======
This issue introduced in https://github.com/rancher/ui/commit/4f0ad7ecbe0932c3e95b14088de7159ab7861878
It should not return false in the loop. Now if only one field doesn't match the search, the whole row will be filtered out.
I guess we only need to keep the `return false` outside of the loop
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18513
======

Fix table search issue

---

lib/logging/addon/components/logging/new-edit/component.js
lib/logging/addon/components/logging/new-edit/template.hbs

======
These two issues are caused by https://github.com/rancher/ui/pull/2713, It should init custom config when `originModel` is changed every time.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18551
https://github.com/rancher/rancher/issues/18570
======

Fix logging issue about swtich project

---

lib/shared/addon/utils/azure-choices.js

======
Add new GA region francecentral to AKS regions
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18598
======

Add francecentral to AKS regions

---

lib/pipeline/translations/en-us.yaml
lib/pipeline/translations/zh-hans.yaml

======
Update text for publish catalog template step
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18579
======

Update text for publish catalog template step

---

lib/shared/addon/utils/amazon.js

======
Add eu-north-1 as AWS region
======
"bugfix"
Linked Issues
======
https://github.com/rancher/rancher/issues/18589
======

Add eu-north-1 to AWS regions

---

lib/shared/addon/utils/util.js

======
Return in correct scope when validating certificate key. The return done in forEach won't actually be returned in the function.
======
bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/18620
======

Return in correct scope when validating certificate key

---

lib/shared/addon/components/cluster-driver/driver-aliyunkcs/component.js
lib/shared/addon/components/cluster-driver/driver-aliyunkcs/template.hbs

======
- k8s Version
- Worker Nodes Count
Needs backend PR merge.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18496
======

Only ACK version and worker node are editable

---

lib/shared/addon/components/cluster-driver/driver-tencenttke/component.js
lib/shared/addon/components/cluster-driver/driver-tencenttke/template.hbs
translations/en-us.yaml
translations/zh-hans.yaml

======
1. Fix the issue that users cannot update tke cluster
2. Gray the fields which can not be updated 
3. Change the field from `goodsNum` to `nodeCount` due to backend changes
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18525
======
Tested. I can create, scale up, scale down and delete TKE cluster successfully. 
Backend PR is https://github.com/rancher/kontainer-engine-driver-tencent/pull/6

Support update tke cluster

---

lib/global-admin/addon/components/multi-cluster-app/template.hbs

remove badge state component in multicluster apps
https://github.com/rancher/rancher/issues/18447

wip minor issues

---

translations/de-de.yaml
translations/es-es.yaml
translations/fa-ir.yaml
translations/fr-fr.yaml
translations/hu-hu.yaml
translations/it-it.yaml
translations/ja-jp.yaml
translations/ko-kr.yaml
translations/nb-no.yaml
translations/nl-nl.yaml
translations/pt-br.yaml
translations/ru-ru.yaml
translations/sh-hr.yaml
translations/sv-se.yaml
translations/uk-ua.yaml
translations/vi-vn.yaml

======
Sync translations with crowdin
======
Enhancement
Linked Issues
======
N/A
======
N/A

Upgrade translations

---

lib/shared/addon/components/cluster-driver/driver-aliyunkcs/template.hbs

======
When editing an ACK cluster:
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18496
======

ACK region cannot be edit

---

lib/shared/addon/components/cru-cluster/component.js

======
state:  current state
active: target state
We should use `state` to filter the available driver instead of `active`.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18662
======

Should use "state" to filter available driver

---

lib/pipeline/addon/components/settings-git/component.js

======
Reset client id and secret  when switch between pages
======
Linked Issues
======
https://github.com/rancherlabs/rancher-security/issues/80
======

Reset client id and secret  when switch between pages

---

lib/monitoring/addon/components/enable-monitoring/component.js
lib/monitoring/addon/components/enable-monitoring/template.hbs
lib/monitoring/translations/en-us.yaml

======
1. Set default prometheus retention period to 12 hours
2. Support set Prometheus Resource limits from cluster enable page
======
Linked Issues
======
rancher/rancher#18695
rancher/rancher#18693
======

Monitoring update
