lib/alert/addon/components/alert/form-recipients/template.hbs, lib/alert/translations/en-us.yaml, lib/pipeline/addon/components/pipeline-notifier/template.hbs
======
Change the text for pipeline notification
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18702
======
=> Fix text issue

lib/logging/addon/components/logging/target-kafka/template.hbs, lib/logging/addon/components/logging/target-splunk/template.hbs, lib/logging/translations/en-us.yaml, lib/logging/translations/zh-hans.yaml
======
Placeholder port text change:
```
splunk: 9200 => 8088
kafka:
broker: 9200 => 9092
zookeeper: 9200 => 2181
```
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18708
======
=> Logging placeholder port is incorrect

lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, translations/en-us.yaml
======
Adds support for explicitly enabling/disabling etcd backup configs
======
New Feature
Linked Issues
======
Backend PR -> rancher/rancher#18647
======
Can't be merged until backend is
=> new backupConfig enabled flag

lib/monitoring/addon/components/cluster-dashboard-tabs/component.js, lib/monitoring/addon/components/cluster-dashboard-tabs/template.hbs, lib/shared/addon/mixins/metrics.js
======
Switch from detail to summary for the graphs in cluster dashboard if there are more that 10 nodes
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17038
======
=> minitoring

translations/en-us.yaml, translations/zh-hans.yaml
======
Requested by QA team
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18801
======
=> Change Tools > Backups to Snapshots

translations/en-us.yaml
======
change "Container Default Limit" label to a "Container Default Resource Limit"
======
Translation Fix
Linked Issues
======
rancher/rancher#18808
======
=> change "Container Default Limit" label to a "Container Default Resource Limit"

app/styles/components/_page-header.scss
fix background color and after
=> global menu hover fix 18792

app/authenticated/cluster/projects/new-ns/controller.js
======
Use another way to jump back to project level ns list. So the UI will not refresh
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18809
======
=> Fix the refresh issue when add ns

lib/monitoring/addon/components/nodes-reservation/component.js
======
When the node is not active, `nodeName` is null, so using `requestedHostname` to display.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18812
======
=> Fix node is not active show "undefined" in dashboard

lib/monitoring/addon/components/enable-monitoring/component.js, lib/monitoring/addon/components/enable-monitoring/template.hbs
======
There are too many configurable options for monitoring. However, UI can not show all of them in the enabling monitoring form.
We need to support key/value answers in enable monitoring page to let users configure more options such as the limit for grafana.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18578
======
=> Support more options for monitoring

app/styles/components/_page-header.scss
nested project menu was inheriting background color on hover of its parent
=> nested project menu background hover fix

app/components/node-row/template.hbs, app/models/node.js
======
Support showing containerd instead of docker version on nodes
======
New feature
Linked Issues
======
=> Show containerd version/icon on nodes

app/styles/components/_page-header.scss
=> active state on global

lib/monitoring/addon/components/nodes-live/component.js
======
Live value should filter unschedulable node.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18857
======
=> Live value should filter unschedulable node

app/styles/components/_page-header.scss
=> active state global menu

app/components/modal-edit-namespace/template.hbs
======
Expand container default resource limit panel when editing a namespace
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18893
======
=> Expand container default resource limit panel when editing a namespace

app/apps-tab/detail/controller.js, app/authenticated/apikeys/controller.js, app/authenticated/cluster/backups/controller.js, app/authenticated/cluster/security/members/index/controller.js, app/authenticated/project/ns/index/controller.js, app/authenticated/project/security/members/index/controller.js, app/components/namespace-list/component.js, app/components/namespace-table/component.js, app/components/project-table/component.js, app/ingresses/index/controller.js, lib/global-admin/addon/accounts/detail/controller.js, lib/global-admin/addon/global-dns/entries/index/controller.js, lib/global-admin/addon/global-dns/providers/index/controller.js, lib/global-admin/addon/security/cloud-credentials/index/controller.js, lib/global-admin/addon/security/policies/index/controller.js, lib/global-admin/addon/security/roles/index/controller.js
======
We mask the created field in display rows with a human readable time stamp. Searching on this while not displaying it is confusing. In order to exclude a header from serach in the sortable tables you must explicitly set the `searchField` false. 
======
Bugfix
Linked Issues
======
rancher/rancher#18889
======
N/A
=> Explicitly exclude created from search fields

lib/monitoring/addon/components/nodes-live/component.js, lib/shared/addon/utils/percent-gauge.js, lib/shared/addon/utils/used-percent-gauge.js
======
1. Fixed outer wheel greater than inner when reserved greater than used. 
2. Change styles according to https://github.com/rancher/rancher/issues/18553#issuecomment-469404081. 
3. I will change the circle to the triangle in the future.  @vincent99 
When reserved greater than used:
Normal situation:
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18553
======
=> Fix outer wheel greater than inner

lib/shared/addon/components/graph-area/component.js
======
Fix graph oom issue
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18883
======
=> Fix graph issue

lib/nodes/addon/components/driver-vmwarevsphere/component.js
======
We need to set network to empty array if there is no network defined
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18894
======
=> Fix vsphere update issue

app/styles/components/_page-header.scss
=> more global menu fixes

app/authenticated/cluster/projects/new-ns/template.hbs
======
======
Bugfix
Linked Issues
======
rancher/rancher#18893
======
=> expand resource quotas on init when creating

lib/shared/addon/components/graph-area/component.js, lib/shared/addon/components/metrics-graph/component.js
======
Fix the memory leak issue
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18929
======
=> graph issue

app/models/globaldns.js, lib/global-admin/addon/components/global-dns-entry-row/component.js, lib/global-admin/addon/components/global-dns-entry-row/template.hbs, lib/global-admin/addon/components/new-multi-cluster-app/template.hbs, lib/global-admin/addon/global-dns/entries/new/controller.js, lib/global-admin/addon/global-dns/entries/new/template.hbs, lib/shared/addon/components/form-project-targets/component.js, lib/shared/addon/components/form-project-targets/template.hbs, lib/shared/app/components/form-multi-cluster-targets/component.js, lib/shared/app/components/form-project-targets/component.js, translations/en-us.yaml
======
Ensure that GDNS project targets are added correctly on update and new.
Update the GDNS final step banner for clarity
======
Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/18937
https://github.com/rancher/rancher/issues/18939
rancher/rancher#18954
rancher/rancher#18960
======
N/A
=> 2.2 GDNS Fixes

lib/global-admin/addon/components/cru-cloud-credential/template.hbs, translations/en-us.yaml
======
======
Enhancement
Linked Issues
======
rancher/rancher#18963
======
N/A
=> Chang Cloud Cred Name/Desc Placeholder

lib/shared/addon/components/cluster-driver/driver-googlegke/template.hbs
======
GKE master version filed is disabled in edit gke page
We should let user update it
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18966
======
=> Edit GKE master version

lib/shared/addon/mixins/metrics.js
======
Update graph unit
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18962
======
=> Fix graph unit issue

app/components/modal-restore-backup/component.js
======
======
Bugfix
Linked Issues
======
rancher/rancher#18975
======
N/A
=> remove unneeded error catch

lib/global-admin/addon/components/global-dns-entry-row/component.js, lib/global-admin/addon/components/global-dns-entry-row/template.hbs, lib/global-admin/addon/global-dns/entries/new/route.js, lib/global-admin/addon/global-dns/providers/new/route.js
======
On edit the global DNS entry was not being cloned properly. Subsequently when the page was edit was cancelled reset logic in the controller set the projectIds or MC App targets to null. 
======
bugfix
Linked Issues
======
rancher/rancher#18977
======
QA
=> Missing Targets in the Global DNS Entry List

lib/shared/addon/utils/percent-gauge.js, lib/shared/addon/utils/used-percent-gauge.js
======
1. Change tooltip radius to wheel `thickness / 2`.
2. Fix range path when max or min equal to the value. 
Memory live wheel: max is 15, min is 14
pod wheel: max is 11, min is 10
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19005
https://github.com/rancher/rancher/issues/19006
======
=> Wheel Gauge issue

app/styles/components/_github-avatar.scss, app/styles/components/_page-header.scss, lib/shared/addon/components/project-member-row/template.hbs
https://github.com/rancher/rancher/issues/18933
=> global nav

app/styles/components/_page-header.scss
======
Adds the missing style to show the hover highlight class when hovering over a project in a cluster to give the user a clear indication of what cluster the project belongs to. 
======
Bugfix
Linked Issues
======
rancher/rancher#18933
======
N/A
=> Add hover style to page-header-project when hovering proj in cluster

app/components/modal-rotate-certificates/template.hbs, translations/en-us.yaml
======
Commented the code out because it will come back eventually. 
======
Bugfix
Linked Issues
======
rancher/rancher#19052
======
N/A
=> Drop "Rotate CA Certs" option from rotate certs modal

lib/pipeline/translations/en-us.yaml
======
Fix pipeline typo
======
Linked Issues
======
======
=> Fix pipeline typo

lib/pipeline/translations/en-us.yaml
======
Fix pipeline typo. No need to fix it in 2.2.0. But we would like to fix it in 2.2.1
======
Linked Issues
======
======
=> [2.2]Fix pipeline typo

lib/shared/addon/components/cluster-driver/driver-aliyunkcs/component.js, lib/shared/addon/components/cluster-driver/driver-huaweicce/component.js
======
- update ACK k8s version
- Fix Huawei cce edit issue
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19148
https://github.com/rancher/rancher/issues/19147
======
=> [2.3]Fix China hosted k8s issue

lib/global-admin/addon/global-dns/entries/new/controller.js, lib/global-admin/addon/global-dns/entries/new/template.hbs, lib/global-admin/addon/global-dns/providers/new/controller.js, lib/global-admin/addon/global-dns/providers/new/template.hbs, lib/shared/addon/components/form-members-global-access/component.js, lib/shared/addon/components/form-members-global-access/template.hbs
======
======
Enhancement
Linked Issues
======
rancher/rancher#18938
======
N/A
=> gdns providers - allow read only + owner when adding members

lib/global-admin/addon/global-dns/entries/new/template.hbs, translations/en-us.yaml
======
Changes location of the finalization message as well as updates the text to make it a little clearer about what is required for the entry to work. 
======
Enhancement
Linked Issues
======
rancher/rancher#19162
======
N/A
=> Change finalization message for GDNS Entries

lib/nodes/addon/components/modal-edit-node-template/component.js, lib/shared/addon/growl/service.js, lib/shared/addon/utils/load-script.js, translations/en-us.yaml
======
Ensure that newly added custom node driver is always fetched when navigating to add node template page. 
======
Bugfix
Linked Issues
======
rancher/rancher#19066
======
Should be merged after final 2.2 tag is declared.
=> 2.2.1 - Fix custom node driver not loading after activation

app/components/node-conditions/component.js
======
Backport: Node Status - Disk space bar is red even there is no disk pressure
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18733
======
=> [2.1.8]Fix incorrect status bar issue in node dashboard

lib/shared/addon/utils/azure-choices.js
======
Add South Africa Azure Regions to list of Azure Choices
======
New feature
Linked Issues
======
https://github.com/rancher/rancher/issues/19227
=> Add South Africa Azure Regions

lib/monitoring/addon/components/enable-monitoring/component.js, lib/monitoring/addon/components/enable-monitoring/template.hbs, lib/monitoring/translations/en-us.yaml, lib/shared/addon/mixins/reservation-check.js
======
Add resource check before enable monitoring
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19078
======
=> Add resource check before enable monitoring

lib/shared/addon/components/identity-block/template.hbs
======
Fix the missing name issue for azure ad
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18425
======
=> Fix the missing name issue for azure ad

lib/shared/addon/components/identity-block/template.hbs
======
Fix the missing name issue for azure ad
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18425
======
=> [2.2]Fix the missing name issue for azure ad

lib/logging/addon/components/logging/target-elasticsearch/template.hbs, lib/monitoring/addon/components/nodes-live/component.js, lib/monitoring/addon/components/nodes-reservation/component.js
======
1. Fix code warning according to
```
DEPRECATION: Please refactor `{{input focus-out="alertMessage"}}` to `{{input focus-out=(action "alertMessage")}}. ('logging/components/logging/target-elasticsearch/template.hbs' @ L7:C6)  [deprecation id: ember-component.send-action] See https://emberjs.com/deprecations/v3.x#toc_ember-component-send-action for more details.
```
2. Remove gauge outline and dots
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19249
======
=> Remove gauge outline and dots

lib/monitoring/addon/components/nodes-live/component.js, lib/monitoring/addon/components/nodes-reservation/component.js
======
Remove gauge outline and dots
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19249
======
=> 2.2-Remove gauge outline and dots

lib/monitoring/addon/components/enable-monitoring/component.js, lib/monitoring/addon/components/enable-monitoring/template.hbs, lib/monitoring/translations/en-us.yaml, lib/shared/addon/mixins/reservation-check.js
======
Add resource check before enable monitoring
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19078
======
=> [2.2.2]Add resource check before enable monitoring

lib/monitoring/addon/components/cluster-basic-info/template.hbs
======
Fix cluster created time issue
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19285
======
=> Fix cluster created time issue

lib/shared/addon/components/custom-catalog/component.js, lib/shared/addon/components/custom-catalog/template.hbs
======
Show system chart in catalog list
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19017
======
=> Show system chart in catalog list

lib/monitoring/addon/components/enable-monitoring/component.js
======
Node selector for monitoring doesn't work if the value is `true`, `false` or a number. So we need to wrap it in UI with `"`
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19218
======
=> Fix prometheus node selector issue

lib/monitoring/addon/components/cluster-basic-info/template.hbs
======
Fix cluster created time issue
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19309
======
=> [2.2.2]Fix cluster created time issue

lib/monitoring/addon/components/enable-monitoring/component.js
======
Node selector for monitoring doesn't work if the value is `true`, `false` or a number. So we need to wrap it in UI with `"`
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19324
======
=> [2.2.2]Fix monitoring node selector issue

app/models/cluster.js, app/models/project.js
======
When MonitoringEnabled === True, monitoring is ready.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19326
======
=> [2.2.2]Backport: Fallback to old dashboard view if monitoring is not healthy

lib/nodes/addon/components/driver-amazonec2/component.js, lib/nodes/addon/components/driver-azure/component.js, lib/nodes/addon/components/driver-digitalocean/component.js, lib/nodes/addon/components/driver-vmwarevsphere/component.js, lib/shared/addon/mixins/node-driver.js, translations/en-us.yaml
======
======
Bugfix
Linked Issues
======
rancher/rancher#19335
======
N/A
=> [2.2.2] Add cloud credential id check to node template mixin

lib/shared/addon/components/custom-catalog/component.js
======
======
Bugfix
Linked Issues
======
rancher/rancher#19339
======
N/A
=> Add service to access settings in custom-catalog view

app/components/new-catalog/component.js, app/components/new-catalog/template.hbs, lib/global-admin/addon/components/global-dns-entry-row/template.hbs, lib/shared/addon/components/form-namespace/component.js
======
form-namespace in the new-catalog component wasn't updated when we added the child-hook mixin to register its own hooks properly.
Fix errors not bubbling correctly.
Don't show mc app links of the linked project is not available to the user.
======
Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/19337
https://github.com/rancher/rancher/issues/19336
https://github.com/rancher/rancher/issues/19174
======
N/A
=> [2.2.2] Fix app launch double click & no errors

lib/monitoring/addon/components/enable-monitoring/component.js, lib/monitoring/addon/components/enable-monitoring/template.hbs, lib/monitoring/translations/en-us.yaml, lib/monitoring/translations/zh-hans.yaml
======
Support config cpu and memory limit for node exporter
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19343
======
=> [2.2.2]Support cpu and memory limit for node exporter

lib/monitoring/addon/components/enable-monitoring/component.js, lib/monitoring/addon/components/enable-monitoring/template.hbs, lib/monitoring/translations/en-us.yaml, lib/monitoring/translations/zh-hans.yaml
======
Support config cpu and memory limit for node exporter
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19145
======
=> Support node exporter cpu and memory limit for mon

lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cru-private-registry/component.js, translations/en-us.yaml
======
Forward port -
remove always set first item to default system reg
remove cluster create check for 1 system default
change header label for clarity
======
Bugfix
Linked Issues
======
rancher/rancher#19325
======
N/A
=> Refactor cru-private-registry

lib/monitoring/addon/components/enable-monitoring/component.js
======
Change the default Prometheus memory limits to 1GB
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19349
======
=> Change the default Prometheus memory limits to 1GB

lib/nodes/addon/components/driver-amazonec2/component.js, lib/nodes/addon/components/driver-azure/component.js, lib/nodes/addon/components/driver-digitalocean/component.js, lib/nodes/addon/components/driver-vmwarevsphere/component.js, lib/shared/addon/mixins/node-driver.js, translations/en-us.yaml
======
Master forward port of cc id node template check 2.2 pr.
======
Bugfix
Linked Issues
======
rancher/rancher#19275
======
N/A
=> Add cloud credential id check to node template mixin

lib/monitoring/addon/components/enable-monitoring/component.js
======
Change the default Prometheus memory limits to 1GB
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19350
======
=> [2.2.2] Change the default Prometheus memory limits to 1GB

lib/global-admin/addon/components/global-dns-entry-row/template.hbs
======
Dont show app link if the project is not available to user on GDNS
======
Bugfix
Linked Issues
======
rancher/rancher#19174
======
=> Missing MC Apps link

lib/nodes/addon/components/modal-edit-node-template/component.js
======
reload global schemas so we have access to new custom nt's
======
Bugfix
Linked Issues
======
rancher/rancher#19066
======
N/A
=> Load Custom Node Driver Templates Correctly

lib/nodes/addon/components/modal-edit-node-template/component.js
======
reload global schemas so we have access to new custom nt's
======
Bugfix
Linked Issues
======
rancher/rancher#19330
======
N/A
=> [2.2.2] Load Custom Node Driver Templates Correctly

server/proxies/api.js
During development, we might want to click view api to see the json in our dev env
=> Add api-ui in proxy

lib/monitoring/addon/components/enable-monitoring/component.js, lib/monitoring/addon/components/enable-monitoring/template.hbs, lib/monitoring/translations/en-us.yaml, lib/monitoring/translations/zh-hans.yaml, lib/pipeline/addon/components/enable-repositories/template.hbs
======
======
Enhancement
Linked Issues
======
rancher/rancher#19394
======
N/A
=> [2.2.2] add resource limits doc link to monitoring page

lib/monitoring/addon/components/enable-monitoring/component.js, lib/monitoring/addon/components/enable-monitoring/template.hbs, lib/monitoring/translations/en-us.yaml, lib/monitoring/translations/zh-hans.yaml, lib/pipeline/addon/components/enable-repositories/template.hbs
======
======
Enhancement
Linked Issues
======
rancher/rancher#19392
======
N/A
=> add resource limits doc link to monitoring page

lib/global-admin/addon/components/cru-cloud-credential/component.js, lib/global-admin/addon/components/cru-cloud-credential/template.hbs, lib/global-admin/addon/components/modal-add-cloud-credential/component.js, lib/global-admin/addon/components/modal-add-cloud-credential/template.hbs, lib/nodes/addon/components/driver-amazonec2/template.hbs, lib/nodes/addon/components/driver-azure/template.hbs, lib/nodes/addon/components/driver-digitalocean/template.hbs, lib/nodes/addon/components/driver-vmwarevsphere/template.hbs, lib/shared/addon/components/form-auth-cloud-credential/component.js, lib/shared/addon/components/form-auth-cloud-credential/template.hbs, lib/shared/addon/mixins/node-driver.js
======
Refactored the error handling to DDAU instead of manipulating the errors object being passed around. 
======
Bugfix
Linked Issues
======
rancher/rancher#19377
======
N/A
=> Fix Double Error on Node Template Cloud Cred Error

app/authenticated/cluster/index/route.js, app/components/page-header-project/component.js, lib/global-admin/addon/clusters/new/route.js, lib/global-admin/addon/global-dns/providers/new/route.js, lib/global-admin/addon/security/roles/index/route.js, lib/monitoring/addon/index/route.js, lib/shared/addon/components/catalog-index/component.js, lib/shared/addon/components/catalog-index/template.hbs, package.json, yarn.lock
======
Fixes global menu sometimes staying open on its own after clicking a cluster link
Fixes catalog menus not dismissing correctly
======
Bugfix
Linked Issues
======
rancher/rancher#19185
rancher/rancher#19300
======
Upgrades the drop down dependency
Upgrades Ember to 3.9 to deal with small engines bug where lazy engine routes with QP's didn't refresh correctly.
=> Dropdown Menu Bugs

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js
======
======
Enhancement 
Linked Issues
======
rancher/rancher#19414
======
EKS API doesn't support fetching k8s versions yet.
=> [2.2.2] Update eks k8s to 1.12

app/models/project.js, lib/monitoring/addon/components/enable-monitoring/component.js, lib/monitoring/addon/components/nodes-live/component.js, lib/shared/addon/mixins/metrics.js
======
1.  Fix project level monitoring not ready issue
2. Fix the dashboard flash issue when monitoring recovered 
======
Linked Issues
======
rancher/rancher#19326
rancher/rancher#19404
======
=> [2.2.2]Monitoring

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js
======
======
Enhancement 
Linked Issues
======
rancher/rancher#19406
======
EKS API doesn't support fetching k8s versions yet.
=> Update eks k8s to 1.12

lib/monitoring/addon/components/enable-monitoring/component.js, lib/monitoring/addon/components/enable-monitoring/template.hbs, lib/monitoring/translations/en-us.yaml, lib/monitoring/translations/zh-hans.yaml
======
1. In 2.2.1, the default node exporter memory limit is 50mb. We changed it to 200 in 2.2.2. But we still need to show 50 for the monitoring which enabled in 2.2.1
2. Check if there is an available node has enough resource for Prometheus pod.
3. Check if there is an available node matches node selectors has enough resource for Prometheus pod.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19403
https://github.com/rancher/rancher/issues/19405
https://github.com/rancher/rancher/issues/19422
======
=> [2.3]Monitoring reservation check enhancement

app/components/form-engine-opts/component.js
======
======
New Feature
Linked Issues
======
rancher/rancher#18596
======
Default is set via setting on backend and change in another ticket.
=> add docker 18.09 to the list of engines

lib/monitoring/addon/components/enable-monitoring/component.js
======
Add checking before fetch monitoring config
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19423
======
=> [2.2.2]Add checking before fetch monitoring config

lib/monitoring/addon/components/enable-monitoring/component.js
======
Add checking before fetch monitoring config
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19423
======
=> [2.3]Add checking before fetch monitoring config

app/instance-initializers/nav.js, lib/monitoring/addon/components/enable-monitoring/component.js
======
======
Linked Issues
======
======
=> [2.2.2]Disable project level monitoring

app/components/new-catalog/component.js
======
Do not check the required field when using yaml as a workaround.
We will add the check back in https://github.com/rancher/rancher/issues/19060
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19511
======
=> [WIP][2.2.2]Do not check the required fields for catalog app when using yaml

app/models/nodetemplate.js, lib/nodes/addon/components/driver-digitalocean/component.js, lib/nodes/addon/node-templates/controller.js, lib/nodes/addon/node-templates/template.hbs, lib/shared/addon/mixins/node-driver.js, yarn.lock
======
Refactors the node template location and size computed properties. Previously the properties on the model were using `volatile` and `notifyPropteryChange` which didn't work because the keys to watch were dynamic. Additionally `volatile` is deprecated. Instead I've refactored the computed properties into an API that generates the computed prop at run time with the correct watch keys. This also opens up the api to be used by 3rd party NT's in the future. 
======
Bugfix
Linked Issues
======
rancher/rancher#19396
======
N/A
=> Node Template Computed Property Bugs

lib/nodes/addon/components/driver-amazonec2/template.hbs, lib/shared/addon/components/form-auth-cloud-credential/component.js, translations/en-us.yaml
======
======
Linked Issues
======
rancher/rancher#19390
rancher/rancher#19378
rancher/rancher#19372
======
=> Node Template Bugs

lib/shared/addon/utils/azure-choices.js
======
Added aks regions for South Central US, Korea South, and Korea Central.
======
bugfix?
Linked Issues
======
https://github.com/rancher/rancher/issues/19475
======
=> Add AKS regions

lib/global-admin/addon/mixins/authentication.js, lib/global-admin/addon/security/authentication/keycloak/template.hbs, server/proxies/api.js
======
======
Bugfix
Linked Issues
======
N/A
======
N/A
=> Small bug fixes

lib/shared/addon/utils/percent-gauge.js, lib/shared/addon/utils/used-percent-gauge.js
======
It is `updateValue` did not `getConfig` after svg width is changed.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19102
======
=> Fix Outer ring display wrong position

app/models/nodetemplate.js
======
Didn't account for the drivers that have null display/size props like vsphere. 
======
Bugfix
Linked Issues
======
rancher/rancher#19566
======
N/A
=> Fix null keys error for dynamic node template props

lib/shared/addon/utils/used-percent-gauge.js
======
Add reserved percentages update.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19387
======
=> Fix reserved percentages not updating when switching between cluster

lib/global-admin/addon/components/new-multi-cluster-app/component.js
======
Fix MCA view answer yaml issue
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18196
======
=> [2.3]Fix MCA view answer yaml issue

lib/shared/addon/components/cluster-driver/driver-huaweicce/component.js
======
Update Huawei CCE driver node os options.
There is no API we can use to query it
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18674
======
=> [2.3]Update Huawei CCE driver node os options

lib/monitoring/addon/components/enable-monitoring/component.js, lib/monitoring/addon/components/enable-monitoring/template.hbs, lib/monitoring/translations/en-us.yaml, lib/monitoring/translations/zh-hans.yaml, lib/shared/addon/components/save-cancel/component.js
======
Update enable monitoring page to match other enable/disable page
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19402
======
=> [2.3]Update enable monitoring page

lib/shared/addon/components/metrics-action/component.js, lib/shared/addon/components/metrics-action/template.hbs
======
Fix the issue that cannot increase time when have Custom timeframe
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19588
======
=> [2.3]Fix monitoring date picker issue

lib/monitoring/addon/components/enable-monitoring/component.js, lib/monitoring/addon/components/enable-monitoring/template.hbs
======
Fails to deploy in some cases due to insufficient vCPU 
We need to consider node exporter and add some buffer for it to make sure we can enable monitoring
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19624
======
=> [2.3]Improve monitoring resource check

lib/shared/addon/components/custom-catalog/component.js, lib/shared/addon/components/custom-catalog/template.hbs
======
Show system chart in catalog list
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19310
======
=> [2.2.x]Show system chart in catalog list

lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cru-private-registry/component.js, translations/en-us.yaml
======
remove always set first item to default system reg
remove cluster create check for 1 system default
change header label for clarity
======
Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/19345
======
N/A
=> [2.2.3] Refactor cru-private-registry

lib/global-admin/addon/components/cru-cloud-credential/component.js, lib/global-admin/addon/components/cru-cloud-credential/template.hbs, lib/global-admin/addon/components/modal-add-cloud-credential/component.js, lib/global-admin/addon/components/modal-add-cloud-credential/template.hbs, lib/nodes/addon/components/driver-amazonec2/template.hbs, lib/nodes/addon/components/driver-azure/template.hbs, lib/nodes/addon/components/driver-digitalocean/template.hbs, lib/nodes/addon/components/driver-vmwarevsphere/template.hbs, lib/shared/addon/components/form-auth-cloud-credential/component.js, lib/shared/addon/components/form-auth-cloud-credential/template.hbs, lib/shared/addon/mixins/node-driver.js, translations/en-us.yaml
======
Refactored the error handling to DDAU instead of manipulating the errors object being passed around. 
======
Bugfix
Linked Issues
======
rancher/rancher#19401
rancher/rancher#19510
rancher/rancher#19513
======
N/A
=> [2.2.x] Node Template Bugs

app/models/nodetemplate.js, lib/nodes/addon/components/driver-digitalocean/component.js, lib/nodes/addon/node-templates/controller.js, lib/nodes/addon/node-templates/template.hbs, lib/shared/addon/mixins/node-driver.js, yarn.lock
======
Refactors the node template location and size computed properties. Previously the properties on the model were using `volatile` and `notifyPropteryChange` which didn't work because the keys to watch were dynamic. Additionally `volatile` is deprecated. Instead I've refactored the computed properties into an API that generates the computed prop at run time with the correct watch keys. This also opens up the api to be used by 3rd party NT's in the future. 
======
Bugfix
Linked Issues
======
rancher/rancher#19503
======
N/A
=> [2.2.x] Node Template Computed Property Bugs 

lib/shared/addon/utils/percent-gauge.js, lib/shared/addon/utils/used-percent-gauge.js
======
It is `updateValue` did not `getConfig` after svg width is changed.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19575
======
=> [2.2.x] Fix Outer ring display wrong position

lib/monitoring/addon/components/enable-monitoring/component.js, lib/monitoring/addon/components/enable-monitoring/template.hbs, lib/monitoring/translations/en-us.yaml, lib/monitoring/translations/zh-hans.yaml
======
Update enable monitoring page to match other enable/disable page
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19601
======
=> [2.2.x]Update enable monitoring page

lib/global-admin/addon/components/new-multi-cluster-app/component.js
======
Fix MCA view answer yaml issue
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19605
======
=> [2.2.x] Fix MCA view answer yaml issue

lib/shared/addon/components/cluster-driver/driver-huaweicce/component.js
======
Update Huawei CCE driver node os options.
There is no API we can use to query it
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19607
======
=> [2.2.x]Update Huawei CCE driver node os options

lib/shared/addon/components/metrics-action/component.js, lib/shared/addon/components/metrics-action/template.hbs
======
Fix the issue that cannot increase time when have Custom timeframe
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19641
======
=> [2.2.x]Fix monitoring date picker issue

lib/monitoring/addon/components/enable-monitoring/component.js, lib/monitoring/addon/components/enable-monitoring/template.hbs
======
Fails to deploy in some cases due to insufficient vCPU 
We need to consider node exporter and add some buffer for it to make sure we can enable monitoring
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19649
======
=> [2.2.x]Improve monitoring resource check

lib/shared/addon/components/metrics-action/template.hbs
======
Disable seconds in monitoring time picker
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19588
======
=> [2.3]Disable seconds in monitoring time picker

lib/logging/addon/logging/controller.js, lib/logging/addon/logging/route.js
======
Cluster logging page breaks in master due to the send action deprecation change.
======
Linked Issues
======
======
=> Fix logging action issue

lib/global-admin/addon/components/new-multi-cluster-app/template.hbs, lib/shared/addon/components/form-members-global-access/template.hbs
======
Missed a couple actions on the big `sendAction` deprecation pr.
======
Bug
Linked Issues
======
rancher/rancher#19676
======
=> Add missing actions to form-members-global-access

lib/shared/addon/utils/azure-choices.js
======
Backport new regions
======
Enhancement
Linked Issues
======
https://github.com/rancher/rancher/issues/19562
https://github.com/rancher/rancher/issues/19563
======
N/A
=> 2.2 region additions

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js, lib/shared/addon/components/cluster-driver/driver-amazoneks/template.hbs
======
Disabled and hid edit input for EKS fields that cannot be changed. Prior, users could change these fields and cluster would go to updating and a request would be sent, but EKS would not respect their new values.
======
Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/18391
=> Disable non-editable EKS fields

lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, lib/shared/addon/components/cru-private-registry/component.js
======
======
Bugfix
Linked Issues
======
rancher/rancher#19325
======
N/A
=> remove incorrectly defined alias

lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, lib/shared/addon/components/cru-private-registry/component.js
======
Backport
======
Bugfix
Linked Issues
======
N/A (hasn't been qa'd yet)
======
N/A
=> [2.2.3] remove incorrectly defined alias

app/models/namespace.js
======
The `availableActions` computed property was not watching `actionLinks` for key changes so it never updated when `move` became unavailable.
======
Bugfix
Linked Issues
======
rancher/rancher#13931
======
N/A
=> watch the correct keys for ns available actions cp

lib/alert/addon/components/alert-table/component.js, lib/alert/addon/components/alert-table/template.hbs, lib/alert/addon/components/alert/alert-group/component.js, lib/alert/addon/components/alert/alert-group/template.hbs, lib/alert/translations/en-us.yaml
======
Show alert group without any rules
======
Linked Issues
======
======
=> [2.2.3]Show alert group without any rules

lib/alert/addon/components/alert-table/component.js, lib/alert/addon/components/alert-table/template.hbs, lib/alert/addon/components/alert/alert-group/component.js, lib/alert/addon/components/alert/alert-group/template.hbs, lib/alert/translations/en-us.yaml
======
Show alert group without any rules
======
Linked Issues
======
======
=> [2.3]Show alert group without any rules

lib/shared/addon/utils/used-percent-gauge.js
======
Add reserved percentages update.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19577
======
=> [2.2.x] CPU/Memory Reserved percentages not updating when switching between cluster

lib/monitoring/addon/components/enable-monitoring/template.hbs
======
Fix the issue that monitoring setting on Firefox fields are out of place
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19587
======
=> [2.3]Monitoring setting on Firefox fields are out of place

app/components/cru-dns/template.hbs
======
DNS page broken in master
======
Linked Issues
======
======
=> Fix dns button issue

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js, lib/shared/addon/components/cluster-driver/driver-amazoneks/template.hbs, lib/shared/addon/components/searchable-select/component.js, translations/en-us.yaml
======
Loads the available SSH keys after AWS Login and exposes SSH key selection at cluster configuration step.
======
Bugfix
Linked Issues
======
rancher/rancher#17875
======
=> Add SSH Key Selection to Amazon EKS Cluster Driver

app/catalog-tab/launch/route.js, app/catalog-tab/launch/template.hbs, app/components/new-catalog/component.js, app/components/new-catalog/template.hbs, translations/en-us.yaml
======
When `requiredNamespace` was added it was only ever set on the `doSave` hook which worked at the time because the `form-namespace` component was hidden. When the UI exposed `form-namespace` by default it revealed some bugs relating to when and where the namespace name was being set.
Now, when we come into to the Catalog Tab launch route we will fetch either the default template version or the current template version on a clone or upgrade and check for requiredNamespace here and set it. The old functionality of "every app gets its own namespace" and subsequent name de-duplication remains intact for apps that do not require a specific namespace. If launching multiple apps that have the same required namespace will still have their name de-duplicated but will be …
=> Refactor Catalog App Launch 

app/containers/run/template.hbs, translations/en-us.yaml
======
- Update taints section text
- Update edit workload text
- Fix typo
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19579
https://github.com/rancher/rancher/issues/19158
https://github.com/rancher/rancher/issues/18129
======
=> [2.3]Fix text issue

app/components/container/form-command/template.hbs, app/components/input-command/component.js, app/components/persistent-volume-table/template.hbs, app/workload/route.js, app/workload/template.hbs, translations/en-us.yaml
https://github.com/rancher/rancher/issues/19356
======
1. Swap out the scale info for the job info
2. Show cron job schedule in detail page
3. Fix command format issue in detail page
======
Linked Issues
======
======
=> [2.3]Fix cron job detail page issue

app/catalog-tab/launch/route.js, app/catalog-tab/launch/template.hbs, app/components/new-catalog/component.js, app/components/new-catalog/template.hbs, package.json, translations/en-us.yaml
======
Brings the long horn fixes back into 2.2
======
Bugfix
Linked Issues
======
N/A
======
=> 2.2.2 longhorn fixes

lib/monitoring/addon/components/node-conditions/template.hbs
======
Fix the issue that tick symbol used in dashboard to represent failure
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19061
======
=> Fix node dashboard icon issue

lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
======
Fix show advanced issue in add cluster page
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18880
======
=> Fix show advanced issue in add cluster page

lib/global-admin/addon/global-dns/providers/new/route.js, lib/global-admin/addon/templates/-cloudflare-dns-provider.hbs, lib/global-admin/addon/templates/-route53-dns-provider.hbs, translations/en-us.yaml
======
Adds the following params to the respective configs
```
Cloud Flare:
proxySetting
Route 53:
credentialsPath
region
roleArn
zone
```
======
Enhancement
Linked Issues
======
rancher/rancher#19425
======
=> New Global DNS Provider Params

lib/global-admin/addon/global-dns/providers/new/route.js, lib/global-admin/addon/templates/-cloudflare-dns-provider.hbs, lib/global-admin/addon/templates/-route53-dns-provider.hbs, translations/en-us.yaml
======
Adds the following params to the respective configs
```
Cloud Flare:
proxySetting
Route 53:
credentialsPath
region
roleArn
zone
```
======
Enhancement
Linked Issues
======
rancher/rancher#19833
======
=> [2.2.3] - New Global DNS Provider Params

lib/shared/addon/components/cluster-driver/driver-amazoneks/template.hbs
======
======
Enhancement
Linked Issues
======
rancher/rancher#17875
======
N/A
=> Move Amazon EKS sshkeypair to node customization section

app/models/cluster.js, app/models/project.js, lib/monitoring/addon/components/enable-monitoring/component.js, lib/monitoring/addon/components/enable-monitoring/template.hbs
======
Disable enable/save/disable button if users don't have related permission.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19074
======
=> Disable monitoring buttons if users don't have related permission

app/mixins/model-alert.js, lib/alert/addon/index/route.js
======
Fix remove alert rule issue
======
Linked Issues
======
======
=> [2.2.3]Fix remove alert rule issue

app/mixins/model-alert.js, lib/alert/addon/index/route.js
======
Fix remove alert rule issue
======
Linked Issues
======
======
=> Fix remove alert rule issue

lib/shared/addon/utils/evaluate.js
======
Add support of != logic in catalog show_if condition
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18859
======
=> Add support of != logic in catalog show_if condition

lib/nodes/addon/components/driver-vmwarevsphere/component.js
======
Fix the issue that cannot change docker install URL in vsphere
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19141
======
=> Fix the issue that cannot change docker install URL in vsphere

lib/shared/addon/components/storage-class/provisioner-azure-disk/component.js, lib/shared/addon/components/storage-class/provisioner-azure-disk/template.hbs, translations/en-us.yaml
======
"Unmanaged" disk has become redundant for Azure Disk based storage classes. Both  "kind: shared" and "kind: dedicated" options are unmanaged disk options. Added this indication to the labels in the dropdown so it is clear to the user. 
======
Bugfix
Linked Issues
======
rancher/rancher#19744
======
N/A
=> Remove redundant storage option for azure disk storage class

app/components/workload-row/template.hbs, app/models/workload.js, app/workload/template.hbs, translations/en-us.yaml
======
Pod restarts
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17891
======
=> Pod restarts

app/components/container/form-job-config/template.hbs, app/components/container/form-scale/component.js, translations/en-us.yaml
======
Support successfulJobsHistoryLimit and failedJobsHistoryLimit in UI 
Update the default values of successfulJobsHistoryLimit and failedJobsHistoryLimit to k8s default value.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17841
======
=> Support more options for cron job

app/components/new-catalog/component.js, app/models/templateversion.js, lib/shared/addon/components/catalog-box/component.js, lib/shared/addon/components/input-answers/component.js, lib/shared/addon/components/input-answers/template.hbs, lib/shared/addon/components/input-custom-answers/component.js, lib/shared/addon/components/input-custom-answers/template.hbs, lib/shared/addon/components/modal-confirm-yaml-switch/component.js, lib/shared/addon/components/modal-confirm-yaml-switch/template.hbs, lib/shared/addon/mixins/input-answers.js, lib/shared/addon/utils/flat-map.js, lib/shared/app/components/modal-confirm-yaml-switch/component.js, lib/shared/app/utils/flat-map.js, package.json, translations/en-us.yaml, yarn.lock
======
Adds a warning to alert users when moving from yaml -> form based editing that displays the key paths of the data that will be lost.
Adds a flat map utility that will produce a flat map of a POJO. Array fields are identified with bracket notation instead of dot.
Adds yaml answer validation for answers in the questions map.
Prevent catalog icons from trying to reload after the page has been exited
======
Bugfix
Linked Issues
======
rancher/rancher#19060
rancher/rancher#17668
======
Shouldn't be merged until rancher/rancher#19634 is resolved.
=> [WIP] Project level catalog answer yaml->form sync

app/components/container/new-edit/component.js, app/components/container/new-edit/template.hbs, app/models/cluster.js, lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, translations/de-de.yaml, translations/en-us.yaml, translations/es-es.yaml, translations/ja-jp.yaml, translations/uk-ua.yaml, translations/zh-hans.yaml, translations/zh-hant.yaml
======
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19176
======
=> Windows 1809 support

app/components/page-footer/template.hbs, app/components/page-header-project/component.js, app/components/page-header-project/template.hbs, app/components/page-header/component.js, app/components/page-header/template.hbs, app/instance-initializers/nav.js, app/styles/components/_page-header.scss, lib/login/package.json, lib/shared/addon/components/hover-dropdown/component.js, lib/shared/addon/components/hover-dropdown/template.hbs, lib/shared/addon/components/language-dropdown/component.js, lib/shared/addon/components/language-dropdown/template.hbs
======
Prevent double header dropdown menus
Ensure correct tabbing order on menus
======
Bugfix/New Feature
Linked Issues
======
rancher/rancher#16709
======
This PR introduces a few new changes to the header nav as well as resolving bugs. See new points below
* User may use tab or left/right arrows to move horizontally across the header nav
* User may use enter/space/down arrow to open a dropdown
* User may use tab or arrow keys to move through dropdown
** Tab on last element will focus out to next tabbable node and close dropdown (standard pattern)
** Arrow keys up/down will cycle through but not out of a dropdown (standard patter)
* User may use Esc to close dropdown
* Dropdown triggers no longer contain links to the top most route in …
=> Nav Header Keyboard Navigation

lib/global-admin/addon/templates/-route53-dns-provider.hbs, lib/shared/addon/components/cluster-driver/driver-rke/component.js
======
Push new private registries into the correct config object
Typo on new GDNS Rt 53 zoneType param
======
Bugfix
Linked Issues
======
rancher/rancher#19833
rancher/rancher#19871
======
=> [2.2.3] Typo Bugs

lib/alert/addon/components/alert-table/component.js
======
Fix the issue that see extra groups under Alerts
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19913
======
=> [2.3]Fix groups without alert issue

app/components/container/form-ports/template.hbs, app/components/container/new-edit/component.js, app/components/container/new-edit/template.hbs, app/models/cluster.js, translations/en-us.yaml
======
* In a windows env, we still need to add at least one linux worker.So we need to have one more option to run all pods on linux worker only.
* Show warning for host port with vxlan as it's not supported yet. We need to wait Flannel side to support it.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19176
======
=> Windows support

lib/alert/addon/components/alert-table/component.js
======
Fix the issue that see extra groups under Alerts
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19913
======
=> [2.2]Fix the issue that see extra groups under Alerts

app/catalog-tab/launch/route.js, lib/shared/addon/components/modal-confirm-yaml-switch/component.js, lib/shared/addon/mixins/input-answers.js
======
Resolve a couple small issues found during initial qa
* Canceling out of yaml -> form works correctly now
* For questions that may have some form of data loss during the switch I added a check to make sure the user actually input an answer in the Yaml. No need to alert the user if they didn't answer the question. 
======
Bugfix
Linked Issues
======
N/A
======
N/A
=> Catalog question sync

app/models/nodetemplate.js, package.json, server/proxies/api.js, yarn.lock
======
* Check for location and size object before creating dynamic computed prop
* Add JQ 3.4.1 resolution for sec concerns 
* Add xfwrd false and follow redirect true to proxy for local dev
======
Linked Issues
======
rancher/rancher#19973
======
N/A
=> Linode Node Template Error

app/components/new-catalog/component.js
======
Cannot install non Rancher based Helm Charts with v2.2.3-rc4
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19984
======
=> [2.2]Fix non rancher catalog app issue

app/components/new-catalog/component.js
======
Cannot install non Rancher based Helm Charts with v2.2.3-rc4
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19890
======
=> Fix non rancher catalog app issue

lib/nodes/addon/components/driver-azure/component.js
======
Add node exporter port in azure security group for monitoring
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19187
======
=> [2.3]Add node exporter port in azure security group

lib/nodes/addon/components/driver-azure/component.js
======
Add node exporter port in azure security group for monitoring
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19187
======
=> [2.2]Add node exporter port in azure security group

lib/shared/addon/components/input-answers/component.js
======
======
Linked Issues
======
======
=> delay initialization on yaml editor until component is rendered

app/components/page-header-project/component.js, app/styles/components/_page-header.scss
======
Fix styling issue found in header drop downs where links were smaller than before.
Fix undefined error when checking tab lists in header nav
======
Linked Issues
======
======
=> Styling issue with nav dropdowns being rendered in place

app/models/cluster.js, app/models/project.js, lib/monitoring/addon/components/enable-monitoring/component.js, lib/shared/addon/mixins/reservation-check.js
======
When `isMonitoringReady` status changed, UI will send requests to backend. In some setup, the conditions keep updating sometimes. But `MonitoringEnabled` condition didn't change at all. We should not send the requests in this case
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19564
======
=> [2.3]monitoring

lib/monitoring/addon/components/enable-monitoring/component.js
======
Fix monitoring pvc issue
Backend will add a new param `prometheus.persistent.useReleaseName` for backward compatibility.
Note:
This PR can be merged anytime as it won't break anything. But we cannot validate it until backend change is in. 
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19608
======
=> [2.3]Fix monitoring pvc issue

app/models/cluster.js, app/models/project.js, lib/monitoring/addon/components/enable-monitoring/component.js, lib/shared/addon/mixins/reservation-check.js
======
When `isMonitoringReady` status changed, UI will send requests to backend. In some setup, the conditions keep updating sometimes. But `MonitoringEnabled` condition didn't change at all. We should not send the requests in this case
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19600
======
=> [2.2.x]monitoring

lib/monitoring/addon/components/enable-monitoring/component.js
======
Fix monitoring pvc issue
Backend will add a new param `prometheus.persistent.useReleaseName` for backward compatibility.
Note:
This PR can be merged anytime as it won't break anything. But we cannot validate it until backend change is in. 
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19610
======
=> [2.2.x]Fix monitoring pvc issue

app/instance-initializers/nav.js
https://github.com/rancher/rancher/issues/19771
======
Add project monitoring back
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19771
======
=> [2.2.2]Project monitoring

app/authenticated/route.js, config/environment.js, package.json, server/proxies/api.js, yarn.lock
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
-->
======
Linked Issues
======
======
=> HA proxying

lib/shared/addon/catalog/service.js, lib/shared/addon/components/catalog-index/component.js
======
Adds the allTemplates object which uses the live templates store.
Catalog index uses this now instead of the model passed down so that the catalog
index live updates as it should.
======
Bugfix
Linked Issues
======
rancher/rancher#19301
======
N/A
=> Add allTemplates logic to catalog service

lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, translations/en-us.yaml, translations/zh-hans.yaml, translations/zh-hant.yaml
======
Old Windows feature is deprecated now.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20025
======
=> [2.2] Remove windows option in UI

lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, translations/en-us.yaml, translations/zh-hant.yaml
======
Old Windows feature is deprecated now.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20025
======
=> [2.1]Remove windows option

app/authenticated/project/security/members/index/controller.js, lib/shared/addon/components/form-members/component.js
======
Backend introduced the project role template binding for service account when enabling project monitoring.
We should hide it in UI.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19381
======
=> [2.2] Hide app prtb

app/authenticated/project/security/members/index/controller.js, lib/shared/addon/components/form-members/component.js
======
Backend introduced the project role template binding for service account when enabling project monitoring.
We should hide it in UI.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19381
======
=> Hide app prtb

lib/monitoring/addon/components/enable-monitoring/component.js, lib/monitoring/addon/components/enable-monitoring/template.hbs, lib/monitoring/translations/en-us.yaml, lib/monitoring/translations/zh-hans.yaml
======
Support prometheus operator memory limit
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19693
======
=> Support prometheus operator memory limit

lib/monitoring/addon/components/enable-monitoring/component.js, lib/monitoring/addon/components/enable-monitoring/template.hbs, lib/monitoring/translations/en-us.yaml, lib/monitoring/translations/zh-hans.yaml
======
Support prometheus operator memory limit
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20022
======
=> [2.2]Support prometheus operator memory limit

app/components/modal-edit-apikey/template.hbs, translations/en-us.yaml
======
Add helper text to cluster scope selection when creating new 
======
Enhancement
Linked Issues
======
rancher/rancher#18639
======
N/A
=> Add help text to cluster scoped api key creation

app/components/modal-edit-apikey/template.hbs, translations/en-us.yaml
======
Add helper text to cluster scope selection when creating new 
======
Enhancement
Linked Issues
======
rancher/rancher#20031
======
N/A
=> [2.2.3] Add help text to cluster scoped api key creation

app/catalog-tab/launch/route.js, app/components/new-catalog/component.js, app/models/templateversion.js, lib/shared/addon/components/catalog-box/component.js, lib/shared/addon/components/input-answers/component.js, lib/shared/addon/components/input-answers/template.hbs, lib/shared/addon/components/input-custom-answers/component.js, lib/shared/addon/components/input-custom-answers/template.hbs, lib/shared/addon/components/modal-confirm-yaml-switch/component.js, lib/shared/addon/components/modal-confirm-yaml-switch/template.hbs, lib/shared/addon/mixins/input-answers.js, lib/shared/addon/utils/flat-map.js, lib/shared/app/components/modal-confirm-yaml-switch/component.js, lib/shared/app/utils/flat-map.js, package.json, translations/en-us.yaml, yarn.lock
======
Backport of rancher/ui#2897
======
Bugfix
Linked Issues
======
rancher/rancher#19060
======
N/A
=> [2.2.3] Backport catalog q&a sync yaml->form edit

lib/shared/addon/components/cluster-driver/driver-rke/component.js
======
Fix the issue that cannot enable Windows
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20039
======
=> Fix the issue that cannot enable Windows

app/components/page-footer/template.hbs
======
Change position to above
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20053
======
=> Fix language-dropdown position to above

lib/monitoring/addon/components/cluster-dashboard/template.hbs, lib/monitoring/addon/components/k8s-component-status/template.hbs, lib/monitoring/addon/index/template.hbs
======
For AKS Clusters only, remove the warnings generated when the CM and Scheduler status reports unhealthy and grayed out the status bars.
======
Enhancement
Linked Issues
======
rancher/rancher#17344
======
Cleaned up quotes and indents in the files I touched.
=> AKS Controller Manager/Scheduler Status

lib/monitoring/addon/components/cluster-dashboard/template.hbs, lib/monitoring/addon/components/k8s-component-status/template.hbs, lib/monitoring/addon/index/template.hbs
======
For AKS Clusters only, remove the warnings generated when the CM and Scheduler status reports unhealthy and grayed out the status bars.
======
Enhancement
Linked Issues
======
rancher/rancher#20066
======
Cleaned up quotes and indents in the files I touched.
=> [2.2.3] AKS Controller Manager/Scheduler Status 

lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cru-cloud-provider/component.js, lib/shared/addon/components/cru-cloud-provider/template.hbs
======
backport rancher/ui#2979
======
Bugfix
Linked Issues
======
rancher/rancher#20117
======
N/A
=> [2.2.3] Ensure that password cloud provider fields are present on edit for azure

app/components/container/form-ports/component.js, app/components/container/form-ports/template.hbs, app/components/container/new-edit/component.js, app/components/container/new-edit/template.hbs, app/components/node-row/template.hbs, app/models/cluster.js, app/models/node.js, app/styles/components/_button.scss, lib/shared/addon/utils/constants.js, translations/en-us.yaml
======
* Use input-group for target  OS 
* Hide windows labels in node list
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20119
======
=> [Windows Support] changes to Deploy Workload page

lib/monitoring/addon/components/nodes-live/component.js
======
UI sends 2 requests in cluster dashboard. It should be only one.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19600
======
=> Fix 2 requests sent issue in cluster dashboard

lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, lib/shared/addon/components/cru-cloud-provider/component.js
======
Need to reset the cloud provider object to account for the missing field being added back in.
======
Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/20117
======
N/A
=> DDAU for cru-cloud-provider

lib/shared/addon/utils/azure-choices.js
======
Backport rancher/rancher#19853
======
New Feature
Linked Issues
======
rancher/rancher#20203
======
N/A
=> [2.2.4] Add North Central US to AKS Driver

lib/shared/addon/components/cru-private-registry/component.js, lib/shared/addon/components/cru-private-registry/template.hbs, translations/en-us.yaml
======
The UX for the previous iteration of private registry at the cluster level was confusing as it was not quite clear what effect adding private registry did. The UX was simplified to only support a single private registry at this time. 
* You can only add one private registry to the cluster through the UI via `enable` / `disabled`
* The registry is defaulted to `isDefault` true and this is not configurable from the UI
* The copy in the accordion has been updated to add clarity as to what a private registry does at the cluster level. 
======
Refactor
Linked Issues
======
rancher/rancher#19871
======
N/A
=> Cluster Private Reg Refactor

lib/shared/addon/utils/azure-choices.js
======
======
New Feature
Linked Issues
======
rancher/rancher#19853
======
N/A
=> Add North Central US to AKS Driver

app/components/page-header-project/component.js, app/styles/components/_identity-block.scss, app/styles/layout/_medium.scss, lib/alert/addon/components/cluster-alert-row/template.hbs, lib/alert/addon/components/project-alert-row/template.hbs, lib/global-admin/addon/accounts/index/controller.js, lib/global-admin/addon/components/account-row/template.hbs, lib/shared/addon/components/identity-block/component.js, lib/shared/addon/components/identity-block/template.hbs, lib/shared/addon/mixins/tooltip.js
======
* Fix weird 1px border/offset that seems to be happening sometimes in firefox.
* Fix username overlapping on members page
* Fix display of long names for projects in tiered dropdown
* Fix tooltip showing up column edge for long tooltip items in alerts rows
======
Bugfix
Linked Issues
======
rancher/rancher#17203
rancher/rancher#17381
rancher/rancher#17410
rancher/rancher#19101
======
N/A
=> General Style Fixes

lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, lib/shared/addon/components/cru-cloud-provider/component.js, lib/shared/addon/components/cru-cloud-provider/template.hbs
======
Azures cloud provider password fields are dropped from the config when editing. The PR ensures that the password fields are added to the config on edit both in form and yaml.
======
Bugfix
Linked Issues
======
rancher/rancher#20044
======
N/A
=> Ensure that password cloud provider fields are present on edit for azure

lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, lib/shared/addon/components/cru-cloud-provider/component.js, lib/shared/addon/components/cru-cloud-provider/template.hbs
======
Dont check aadClientSecret on edit, not required to edit
======
Bugfix
Linked Issues
======
rancher/rancher#20117
======
N/A
=> Dont check aadClientSecret on edit, not required to edit

lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, lib/shared/addon/components/cru-cloud-provider/component.js, lib/shared/addon/components/cru-cloud-provider/template.hbs
======
Dont check aadClientSecret on edit, not required to edit
======
Bugfix
Linked Issues
======
rancher/rancher#20044
======
N/A
=> Azure Cloud Provider Credentials Fix

lib/shared/addon/components/cru-private-registry/component.js
======
======
Bugfix
Linked Issues
======
rancher/rancher#19325
======
N/A
=> Set isDefault true by default for private registry

lib/shared/addon/components/cru-private-registry/component.js
======
======
Bugfix
Linked Issues
======
rancher/rancher#19345
======
N/A
=> [2.2.4] Set isDefault true by default for private registry

translations/en-us.yaml
======
Fix cruPrivateRegistry section of en.us.yaml translations file. We can only have 1 private registry at a time for the cluster the translations file now uses singular term instead of plural.
======
Bugfix, non-breaking
Linked Issues
======
https://github.com/rancher/rancher/issues/20343
======
Low-risk change to en-us.yaml translations file.
=> Fix cruPrivateRegistry section

app/authenticated/cluster/edit/template.hbs, app/models/cluster.js
======
Choose the correct provider and pass to cru-cluster when editing so the user can select the correct provider when we can't find the correct one because the user doesn't have access to the node template that was used to create the cluster.
======
Bugfix
Linked Issues
======
rancher/rancher#20292
======
N/A
=> [2.2.x] User Not Able to Edit Cluster

app/authenticated/cluster/edit/template.hbs, app/models/cluster.js, lib/shared/addon/components/cru-cluster/component.js, lib/shared/addon/components/cru-cluster/template.hbs
======
Added additional template logic for if we are in the main app or an engine that links to the correct route for editing a cluster and allows the user to select the right provider if we don't have it. This also contains the fix for a regular user not being able to edit a cluster which again had to do with he lack of provider info. 
======
Bugfix
Linked Issues
======
rancher/rancher#20340
======
N/A
=> Edit Cluster Page Won't Load & User Not Able to Edit Cluster

app/verify-auth/route.js, lib/login/addon/login/controller.js, lib/login/addon/login/route.js, lib/login/addon/login/template.hbs, translations/en-us.yaml
======
Rancher server used to send an errorMsg as an arbitrary string, now they will send an error message code that corresponds to a translation string. If the code doesn't match a corresponding string the user will see a generic error message.
======
Bugfix
Linked Issues
======
rancher/rancher#20216
======
I believe this is the only place this needs to change. There is another variable in the UI called `errorMsg` but it does not correlate to the query param here. 
After approved review I will create a backport PR for 2.2.4.
=> Login Web Params 

app/verify-auth/route.js, lib/login/addon/login/controller.js, lib/login/addon/login/route.js, lib/login/addon/login/template.hbs, translations/en-us.yaml
=> [2.2.4] Login Web Params

app/app.js, lib/monitoring/addon/cluster-setting/route.js, lib/monitoring/addon/cluster-setting/template.hbs, lib/monitoring/addon/components/enable-monitoring/component.js, lib/monitoring/addon/components/enable-monitoring/template.hbs, lib/monitoring/addon/engine.js, lib/monitoring/addon/mixins/catalog-upgrade.js, lib/monitoring/addon/project-setting/route.js, lib/monitoring/addon/project-setting/template.hbs, lib/monitoring/translations/en-us.yaml, lib/monitoring/translations/zh-hans.yaml, lib/shared/addon/mixins/upgrade-component.js
======
Support one click upgrade option for cluster/project monitoring.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20304
======
=> Support one click upgrade option for cluster/project monitoring.

app/app.js, lib/monitoring/addon/cluster-setting/route.js, lib/monitoring/addon/cluster-setting/template.hbs, lib/monitoring/addon/components/enable-monitoring/component.js, lib/monitoring/addon/components/enable-monitoring/template.hbs, lib/monitoring/addon/engine.js, lib/monitoring/addon/mixins/catalog-upgrade.js, lib/monitoring/addon/project-setting/route.js, lib/monitoring/addon/project-setting/template.hbs, lib/monitoring/translations/en-us.yaml, lib/monitoring/translations/zh-hans.yaml, lib/shared/addon/mixins/upgrade-component.js
======
Support one click upgrade option for cluster/project monitoring.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20326
======
=> [2.2.4]Support one click upgrade option for cluster/project monitoring.

app/catalog-tab/launch/route.js
======
Add check for matching app name in existing namespace and reuse that namespace as the target if there are no matched apps.
Fix new app name dedupe that was occurring. 
======
Bugfix
Linked Issues
======
rancher/rancher#19697
======
N/A
=> Catalog App Name Deduplication

app/catalog-tab/launch/route.js
======
Add check for matching app name in existing namespace and reuse that namespace as the target if there are no matched apps.
Fix new app name dedupe that was occurring. 
======
Bugfix
Linked Issues
======
rancher/rancher##19752
======
N/A
=> [2.2.4] Catalog App Name Deduplication

app/catalog-tab/launch/route.js, app/models/app.js, app/models/multiclusterapp.js, lib/global-admin/addon/components/multi-cluster-app/template.hbs, lib/global-admin/addon/multi-cluster-apps/index/route.js, lib/shared/addon/mixins/upgrade-component.js, translations/en-us.yaml
======
We fetch the catalog template of both global and project apps for upgrade info among other things. This pr adds logic to handle the missing template info including removing the ability to upgrade or clone an app that is missing it's corresponding catalog. The app can still function but we can't really upgrade if we don't have any of the template info, nor can we clone since we could be missing question data from the template that may not exist in the current iteration fo the app. 
======
Bugfix
Linked Issues
======
rancher/rancher#19592
rancher/rancher#19593
======
N/A
=> Better Error Handling When Deployed Apps Catalog is Deleted

app/catalog-tab/launch/route.js, app/models/app.js, app/models/multiclusterapp.js, lib/global-admin/addon/components/multi-cluster-app/template.hbs, lib/global-admin/addon/multi-cluster-apps/index/route.js, lib/shared/addon/mixins/upgrade-component.js, translations/en-us.yaml
======
Backport rancher/ui#3010
======
Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/20432
https://github.com/rancher/rancher/issues/20433
======
=> [2.2.4] Better Error Handling When Deployed Apps Catalog is Deleted

app/catalog-tab/launch/route.js, lib/monitoring/addon/components/cluster-dashboard/component.js, lib/monitoring/addon/components/cluster-dashboard/template.hbs, lib/monitoring/addon/components/enable-monitoring/component.js, lib/monitoring/addon/components/enable-monitoring/template.hbs, lib/monitoring/addon/index/route.js, lib/monitoring/addon/index/template.hbs, lib/monitoring/addon/mixins/catalog-upgrade.js, lib/monitoring/translations/en-us.yaml, lib/monitoring/translations/zh-hans.yaml, lib/shared/addon/mixins/upgrade-component.js, package.json
======
Update the UX for monitoring one click upgrade
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20439
======
=> [2.2]Update the UX for monitoring one click upgrade

lib/monitoring/addon/components/cluster-dashboard/component.js, lib/monitoring/addon/components/cluster-dashboard/template.hbs, lib/monitoring/addon/components/enable-monitoring/component.js, lib/monitoring/addon/components/enable-monitoring/template.hbs, lib/monitoring/addon/index/route.js, lib/monitoring/addon/index/template.hbs, lib/monitoring/addon/mixins/catalog-upgrade.js, lib/monitoring/translations/en-us.yaml, lib/monitoring/translations/zh-hans.yaml, lib/shared/addon/mixins/upgrade-component.js
======
Update the UX for monitoring one click upgrade
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20400
======
=> Upgrade UX for one click upgrade

lib/monitoring/addon/components/cluster-dashboard/template.hbs
======
Should not show upgrade available if only operator is not upgrade to date
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20468
======
=> [2.2]Should not show upgrade available if only operator is not upgrade to date

lib/shared/addon/utils/amazon.js
======
Support aws ec2 ap-east-1 and us-gov-east-1
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20474
======
=> Support aws ec2 ap-east-1 and us-gov-east-1

lib/shared/addon/utils/amazon.js
======
Support aws ec2 ap-east-1 and us-gov-east-1
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20515
======
=> [2.2]Support aws ec2 ap-east-1 and us-gov-east-1

lib/monitoring/addon/components/enable-monitoring/template.hbs, lib/monitoring/translations/en-us.yaml, lib/monitoring/translations/zh-hans.yaml
======
Show upgrade available in monitoring setting page
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20469
======
=> [2.2]Show upgrade available in monitoring setting page

translations/en-us.yaml, translations/zh-hans.yaml
https://github.com/rancher/rancher/issues/19838
=> update amazon ecs for amazon eks for cluster driver

translations/en-us.yaml, translations/zh-hans.yaml
Backport rancher/rancher#20555
=> [2.2.4] update amazon ecs for amazon eks for cluster driver

lib/shared/addon/components/cru-cloud-provider/cloud-provider-info.js, lib/shared/addon/utils/constants.js, translations/en-us.yaml
======
Support loadBalancerSku Azure cp param
Backend is in
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20240
======
=> Support loadBalancerSku Azure cp param

lib/monitoring/addon/components/enable-monitoring/template.hbs, lib/monitoring/translations/en-us.yaml
======
Show warning if no permission to config monitoring
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19074
======
=> Show warning if no permission to config monitoring

app/models/app.js, app/models/multiclusterapp.js, package.json, yarn.lock
======
A change was made in ember-api-store that fixed a bug where deleted references were not notifying the correct store that the reference was deleted. 
Also added a check to the `isIstio` check so that we don't hide apps that do not have a catalog template. 
======
Bugfix
Linked Issues
======
rancher/rancher#19593
======
N/A
=> Catalog App Catalog Deleted Issues

lib/global-admin/addon/components/registry-catalog/component.js, lib/global-admin/addon/components/registry-catalog/template.hbs, lib/istio/addon/components/istio-catalog/component.js, lib/istio/addon/components/istio-catalog/template.hbs, lib/istio/translations/en-us.yaml, lib/shared/addon/components/catalog-persistence-row/template.hbs, lib/shared/addon/components/form-reservation/template.hbs, lib/shared/addon/helpers/parse-camelcase.js, lib/shared/addon/mixins/reservation-check.js, lib/shared/addon/utils/util.js, lib/shared/app/helpers/parse-camelcase.js, lib/shared/app/utils/util.js, translations/en-us.yaml
======
Bug fix for Istio and Registry enabling page
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20673
https://github.com/rancher/rancher/issues/20660
https://github.com/rancher/rancher/issues/20658
https://github.com/rancher/rancher/issues/20645
======
=> Bug fix for enabling istio and registry page

app/models/app.js, app/models/multiclusterapp.js, package.json, yarn.lock
======
Backport rancher/ui#3032
======
Bugfix
Linked Issues
======
rancher/rancher#20433
======
N/A
=> Update rancher/ember-api-store for notifiers fix

app/components/modal-edit-namespace/component.js, app/components/modal-edit-namespace/template.hbs
======
Add check to see if the namespace can be moved on edit. If not, display the project name. 
======
Linked Issues
======
rancher/rancher#13931
======
N/A
=> Disable Namespace Move When Editing Namespace

app/authenticated/cluster/projects/new-ns/template.hbs, app/components/modal-edit-namespace/component.js, app/components/modal-edit-namespace/template.hbs, lib/istio/addon/cluster-setting/template.hbs, lib/istio/addon/components/istio-nav/component.js, lib/istio/addon/components/istio-nav/template.hbs, lib/istio/addon/components/traffic-monitoring/component.js, lib/istio/addon/graph/controller.js, lib/istio/addon/graph/route.js, lib/istio/addon/graph/template.hbs, lib/istio/addon/metrics/controller.js, lib/istio/addon/metrics/template.hbs, lib/istio/addon/rules/controller.js, lib/istio/addon/rules/template.hbs, lib/istio/translations/en-us.yaml
======
Support Project owner to see istio links
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20695
https://github.com/rancher/rancher/issues/20713
======
=> Support Project owner to see istio links

app/components/hpa-row/template.hbs, lib/global-admin/addon/components/registry-catalog/component.js, lib/global-admin/addon/components/registry-catalog/template.hbs, lib/istio/addon/components/istio-catalog/component.js, lib/istio/addon/components/istio-catalog/template.hbs, lib/istio/translations/en-us.yaml, lib/shared/addon/mixins/reservation-check.js, translations/en-us.yaml
======
* Update label and placeholder text harbor admin password field
* Fix the issue that s3 region is not required
* Make Encryption field editable
* Fix HPA error message style issue
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20687
rancher/rancher#20689
rancher/rancher#20688
======
=> HPA and Registry

lib/global-admin/addon/components/new-edit-role/template.hbs, lib/global-admin/addon/components/role-rule-row/component.js, lib/global-admin/addon/components/role-rule-row/template.hbs, translations/en-us.yaml
======
Before we hard code apigroup for `*`, when users create a role template in Rancher UI.
To improve the UX for admin users especially when they config istio stuff , we should expose api groups in UI.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20666
https://github.com/rancher/rancher/issues/16254
======
=> Show API groups in UI instead of hard code *

package.json, yarn.lock
======
Add yarn dep resolutions to ensure we are using versions outside of security risk versions.
======
Bugfix
Linked Issues
======
N/A
======
N/A
=> Security Fixes

lib/istio/translations/en-us.yaml, lib/monitoring/translations/en-us.yaml, translations/en-us.yaml
======
- Change confirmDisable en-us translation strings to remove the word "really"
======
Bugfix (non-breaking change, low risk)
Linked Issues
======
https://github.com/rancher/rancher/issues/20710
======
Very low risk change to en-us translations files.
=> update confirmDisable translation strings

lib/monitoring/addon/components/cluster-dashboard/component.js, lib/monitoring/addon/components/cluster-dashboard/template.hbs
======
Hide controller manager and scheduler for ACK cluster
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20560
======
=> Hide controller manager and scheduler for ACK cluster

lib/nodes/addon/components/driver-other/component.js, lib/nodes/addon/components/driver-other/template.hbs, lib/nodes/addon/components/modal-edit-node-template/component.js, lib/nodes/addon/components/modal-edit-node-template/template.hbs, lib/nodes/addon/node-templates/template.hbs, lib/shared/addon/components/api-field/component.js, lib/shared/addon/components/api-field/template.hbs, lib/shared/addon/utils/constants.js
======
Node drivers received an update that adds a new annotation label, `io.cattle.nodedriver/ui-field-hints`. This object carries any special fields, currently limited to multiline, so the UI can swap out the input component. The scope was intentionally kept small since the change will be backported to earlier versions of Rancher, this could be made smarter in the future. 
======
New Feature
Linked Issues
======
rancher/rancher#20787
======
=> Add support for special fields in 3rd party Node Drivers

lib/nodes/addon/components/driver-other/component.js, lib/nodes/addon/components/driver-other/template.hbs, lib/nodes/addon/components/modal-edit-node-template/component.js, lib/nodes/addon/components/modal-edit-node-template/template.hbs, lib/nodes/addon/node-templates/template.hbs, lib/shared/addon/components/api-field/component.js, lib/shared/addon/components/api-field/template.hbs, lib/shared/addon/utils/constants.js
======
Node drivers received an update that adds a new annotation label, `io.cattle.nodedriver/ui-field-hints`. This object carries any special fields, currently limited to multiline, so the UI can swap out the input component. The scope was intentionally kept small since the change will be backported to earlier versions of Rancher, this could be made smarter in the future. 
======
New Feature
Linked Issues
======
rancher/rancher#20789
======
=> [2.2.x] Add support for special fields in 3rd party Node Drivers

app/authenticated/project/security/members/index/controller.js, lib/shared/addon/components/form-members/component.js, lib/shared/addon/components/project-member-row/template.hbs
======
This PR fixes two issues, the first being when adding group members to a project they would not show up on the index page. This [change](https://github.com/rancher/ui/pull/2969/files) filtered out all the PRTBs on the members page that didn't contain the users id to filter the service account the would surface from enabling project monitoring. Instead we'll filter by the service account param. The second was when adding a member from the form-members component a type error would occur and cause the member to not be added. A closure action was missed when the deprecations were dealt with. 
======
Bugfix
Linked Issues
======
rancher/rancher#19760
rancher/rancher#20760
======
N/A
=> Add Project Member Issues

app/authenticated/project/security/members/index/controller.js, lib/shared/addon/components/form-members/component.js, lib/shared/addon/components/project-member-row/template.hbs
======
This PR fixes two issues, the first being when adding group members to a project they would not show up on the index page. This [change](https://github.com/rancher/ui/pull/2969/files) filtered out all the PRTBs on the members page that didn't contain the users id to filter the service account the would surface from enabling project monitoring. Instead we'll filter by the service account param. The second was when adding a member from the form-members component a type error would occur and cause the member to not be added. A closure action was missed when the deprecations were dealt with. 
======
Bugfix
Linked Issues
======
rancher/rancher#20826
rancher/rancher#20825
======
N/A
=> [2.2.x] Add Project Member Issues

app/authenticated/project/hpa/index/template.hbs
======
Disable add HPA button if hpa v2beta2 api is not supported in the cluster
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20758
======
=> Disable add HPA button if not supported

lib/istio/addon/components/istio-catalog/component.js
======
Enable istio mixer policy by default
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20840
======
=> Enable istio mixer policy by default

lib/monitoring/addon/components/nodes-reservation/component.js, lib/shared/addon/utils/percent-gauge.js
======
1. Gauge length max is 100.
2. Used and total are in the same unit.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19413
======
=> Fix gauge greater 100 and unit

lib/global-admin/addon/components/registry-catalog/template.hbs, translations/en-us.yaml
======
Now if users re-use the PVC, the admin password will not take effect. 
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20797
======
=> [Preview 2 Release]Show warning for registry admin password

app/components/cru-hpa/component.js, app/components/cru-hpa/template.hbs, app/components/hpa-metric-row/component.js, app/components/hpa-metric-row/template.hbs, app/models/container.js, translations/en-us.yaml
======
Show warning messages for HPA
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20861
https://github.com/rancher/rancher/issues/20866
======
=> [Preview 2 Release]Warning messages for HPA

app/authenticated/project/ns/index/template.hbs, app/components/hpa-metric-row/template.hbs, app/components/modal-edit-namespace/component.js, app/components/modal-edit-namespace/template.hbs, app/components/namespace-list/template.hbs, app/components/namespace-table/template.hbs, app/models/namespace.js, app/styles/components/_istio-graph.scss, app/styles/pages/_settings.scss, lib/istio/addon/components/istio-catalog/component.js, lib/istio/addon/components/istio-catalog/template.hbs, lib/istio/addon/components/traffic-graph/template.hbs, lib/istio/translations/en-us.yaml, public/assets/images/providers/istio.svg, translations/en-us.yaml
======
After the demo, got some feedback from the team.
- Change "service mesh" links to "Istio", Change "Cluster Service Mesh" to "Istio"
-  Note/Warning in the UI that sidecar injection needs to be enabled for each namespace. For any existing namespaces, you will need to enable the feature and re-deploy. "In order to leverage Istio, you will need to enable Istio sidecar auto injection for each namespace. If you enable it on an existing namespace, any existing workloads will need to be re-deployed to leverage the sidecar auto injection."
-  Add Istio icon next to namespace names for any namespace that has sidecar injection turned on.
-  In traffic graph view, add in kiali logo with a note that says "Powered by Kiali" in the bottom right corner
-  Add in version dropdown …
=> [Preview 2 Release]Istio preview release

lib/shared/addon/helpers/maybe-t.js
======
Make sure locale is not undefined and recompute when the locale is changed.
related `ember-intl` issue: https://github.com/ember-intl/ember-intl/issues/768
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20790
======
=> [Preview 2 Release]Fix default locale is lost

app/components/notifier/modal-new-edit/template.hbs, translations/en-us.yaml
======
Support proxy url for notifier
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20867
======
=> [2.2]Support proxy url for notifier

app/instance-initializers/nav.js
======
Hide Global Registry as we are not going to ship it in Preview 2
======
Linked Issues
======
======
=> Hide Global Registry menu

package.json, translations/ar-sa.yaml, translations/de-de.yaml, translations/es-es.yaml, translations/fa-ir.yaml, translations/fr-fr.yaml, translations/hu-hu.yaml, translations/it-it.yaml, translations/ja-jp.yaml, translations/ko-kr.yaml, translations/nb-no.yaml, translations/nl-nl.yaml, translations/pt-br.yaml, translations/ru-ru.yaml, translations/sh-hr.yaml, translations/sv-se.yaml, translations/tr-tr.yaml, translations/uk-ua.yaml, translations/vi-vn.yaml, yarn.lock
======
Fixes a small issue in the translation yaml files that was throwing warnings during dev compile and adds a security resolution for underscore.string
======
Bugfix
Linked Issues
======
N/A
======
N/A
=> Translation.bug

lib/istio/addon/components/istio-catalog/component.js
======
Update UI for istio to match the version that the catalog will be 
======
Linked Issues
======
======
=> fix istio versioning

lib/istio/addon/components/istio-catalog/component.js
======
======
Linked Issues
======
======
=> another istio version fix

lib/shared/addon/components/cluster-driver/driver-googlegke/component.js, lib/shared/addon/components/cluster-driver/driver-googlegke/template.hbs, translations/en-us.yaml
======
Fix gke node pool issue
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20936
======
=> [2.2]Fix gke node pool issue

app/catalog-tab/launch/route.js
======
Fix edit catalog issue when app installed failed. websocket keeps sending updates to UI. So answers fields get overridden.  So we need to clone it
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21027
======
=> [2.2]Fix edit catalog issue when app installed failed

app/components/notifier/modal-new-edit/template.hbs, translations/en-us.yaml
======
Support proxy url for notifier
======
Linked Issues
======
https://github.com/rancher/rancher/issues/17885
======
=> Support proxy url for notifier

lib/shared/addon/components/cluster-driver/driver-googlegke/component.js, lib/shared/addon/components/cluster-driver/driver-googlegke/template.hbs, translations/en-us.yaml
======
Fix gke node pool issue
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20355
======
=> Fix gke node pool issue

.ackrc, .bowerrc, .eslintignore, .gitignore, .ignore, jsconfig.json
======
Remove Bower-related config
======
- Non-breaking bug(ish) fix
Linked Issues
======
Can't create an issue, they seem to be disabled on this repo.
======
I was interested in the source for the Rancher UI, so took a look at this repo, and was a little surprised to see some Bower config (since Bower has been more or less deprecated for years). It doesn't look like any of it is actually being used by anything, though, so this change just removes it.
=> chore(config): remove bower

app/catalog-tab/launch/route.js
======
Fix edit catalog issue when app installed failed. websocket keeps sending updates to UI. So answers fields get overridden.  So we need to clone it
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20655
======
=> Fix edit catalog issue when app installed failed

lib/global-admin/addon/components/cru-cloud-credential/template.hbs
======
Digital Ocean cloud config was missing required asterisk.
======
Bug Fix
Linked Issues
======
rancher/rancher#19754
======
N/A
=> Add field required to DO cloud provider

app/styles/components/_page-header.scss, lib/monitoring/addon/components/cluster-basic-info/template.hbs
Remove second basics bar:
https://github.com/rancher/rancher/issues/19896
https://github.com/rancher/rancher/issues/19359
=> 2.3 issues dashboard and monitoring

app/authenticated/cluster/edit/route.js
======
We also need to filter by active when editing a cluster. 
======
Bugfix
Linked Issues
======
rancher/rancher#21108
======
N/A
=> Filtering Active External Cluster Drivers

app/authenticated/cluster/edit/route.js
======
We also need to filter by active when editing a cluster. 
======
Bugfix
Linked Issues
======
rancher/rancher#21109
======
N/A
=> filter active external kontainer engine drivers on edit

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js
======
Add EKS regions and k8s 1.13
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21136
=> Add EKS regions and k8s 1.13

lib/istio/addon/cluster-setting/route.js, lib/istio/addon/cluster-setting/template.hbs, lib/istio/addon/components/istio-catalog/component.js, lib/istio/addon/components/istio-catalog/template.hbs, lib/monitoring/addon/components/cluster-dashboard/component.js, lib/monitoring/addon/components/enable-monitoring/component.js, lib/shared/addon/mixins/catalog-upgrade.js, lib/shared/addon/mixins/crud-catalog.js
======
1. Enable Istio page: Display upgrade available in `version` select when it can upgrade.
2. Support upgrade a version by selecting a version.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20617
======
=> Support one click upgrade for Istio

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js
======
Backport support for k8s 1.13 on EKS
======
Enhancement
Linked Issues
======
rancher/rancher#21156
======
N/A
=> [2.2.5] Backport support for k8s 1.13 on EKS

app/components/modal-rotate-certificates/component.js, app/components/modal-rotate-certificates/template.hbs, app/models/cluster.js, app/styles/components/_tooltip.scss, app/styles/themes/_dark.scss, app/styles/themes/_light.scss, lib/global-admin/addon/components/cluster-row/template.hbs, lib/monitoring/addon/components/cluster-dashboard/component.js, lib/monitoring/addon/components/cluster-dashboard/template.hbs, lib/shared/addon/components/tooltip-expiring/component.js, lib/shared/addon/components/tooltip-expiring/template.hbs, lib/shared/app/components/tooltip-expiring/component.js, translations/en-us.yaml
======
Adds new logic to expose a warning when clusters certificates will be expiring in 30 days or less.
At the global level when a cluster has certs that are expiring there will be a small warning icon next to the cluster name with a tooltip explanation and link action to open the rotate certs modal. 
At the cluster level on the cluster page you will see a warning banner above your cluster details with the same explanation/link action that opens the rotate certs modal. 
In the rotate certs modal you will see the cert selection dropdown now adds the time in days until expiration. One choice that may confuse but was talked through with @moelsayed affects the etcd service.  Rke alerts us of every etcd node that has a cert expiring. In the UI we only show the date from the …
=> [2.2.5] Add ui warning about expiring certificates

lib/global-admin/addon/components/registry-catalog/template.hbs, lib/istio/addon/components/istio-catalog/template.hbs, lib/monitoring/addon/components/enable-monitoring/template.hbs
======
Remove Umbrella Icon from
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20717
======
=> Remove Umbrella Icon from "Disable Monitoring/Istio/Global Registry"

lib/monitoring/addon/components/node-dashboard/template.hbs, lib/monitoring/addon/node-detail/template.hbs, lib/shared/addon/components/node-ip/template.hbs
https://github.com/rancher/rancher/issues/19897
https://github.com/rancher/rancher/issues/21096
=> fix for 19897

lib/shared/addon/utils/azure-choices.js
======
Update AKS regions
Linked Issues
======
https://github.com/rancher/rancher/issues/21232
=> Update AKS regions

app/components/modal-rotate-certificates/component.js, app/models/cluster.js, app/styles/themes/_light.scss, lib/monitoring/addon/components/cluster-dashboard/template.hbs, lib/shared/addon/components/tooltip-expiring/template.hbs, translations/en-us.yaml
======
Adds some fixes to resolve minor issues around verbiage. Fixes JS Error on mixed etcd expirations. 
======
Bugfix
Linked Issues
======
rancher/rancher#21197
rancher/rancher#21196
rancher/rancher#21193
rancher/rancher#21220
======
N/A
=> 2.2.5 Resolve Minor Issues with cert expiration

app/models/cronjob.js, lib/shared/addon/mixins/cattle-transitioning-resource.js, translations/en-us.yaml
======
Add suspend and resume actions for cronjob
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18945
======
=> Add suspend and resume actions for cronjob

lib/istio/addon/cluster-setting/route.js
======
Fix project store find apps did not change project id. 
It should use `followLink` instead of change the project store base URL. 
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21267
======
=> Fix Istio app not change when switching another cluster

.drone.yml, app/components/modal-telemetry/component.js, app/update-password/route.js, lib/shared/addon/settings/service.js, lib/shared/addon/utils/parse-version.js, scripts/build-static, scripts/ci
Drone autobuild for 2.2-fixes -> releases.rancher.com/ui/latest-2.2
=> Autobuild latest-2.2, consider *-head a dev build

app/components/modal-telemetry/component.js, app/components/node-row/component.js, app/update-password/route.js, lib/shared/addon/settings/service.js, lib/shared/addon/utils/parse-version.js
======
Nodes should be sorted numerically ( node1, ..., node9, node10, node11 ), not ASCII-betically ( node1, node10, node11, node2, ... node9 )
======
Bugfix
=> Sort nodes by sortable name

lib/global-admin/addon/cluster-templates/new/route.js, lib/global-admin/addon/components/cluster-templates-table/component.js
======
Was removed on the API side. 
======
Linked Issues
======
======
=> Remove enabled flag for clusterTemplateRevision

app/styles/components/_tooltip.scss
======
Change the color of rotate text in the tooltip when the cluster certs are expiring.
======
Bugfix
Linked Issues
======
rancher/rancher#21370
======
=> Change rotate text color in expire tooltip

app/styles/components/_tooltip.scss
======
Change the color of rotate text in the tooltip when the cluster certs are expiring.
======
Bugfix
Linked Issues
======
rancher/rancher#21283
======
=> [2.2.5] Change rotate text color in expire tooltip

lib/global-admin/addon/clusters/new/cluster-template/controller.js
======
Enabled was removed as  property of the cluster template. 
======
Bugfix
Linked Issues
======
rancher/rancher#20268
======
=> Remove enabled filter on clusterTemplates that caused js error

app/components/namespace-table/component.js
======
Fix namespace page can not search project name
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21380
======
=> Fix namespace page can not search project name

app/components/namespace-table/component.js, app/components/namespace-table/template.hbs
======
Fix cannot search projects
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21379
======
=> [2.2.5] Fix cannot search projects

lib/global-admin/addon/global-dns/providers/new/route.js
======
Alidns is broken in 2.2.4
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21387
======
=> [2.2.5]Fix Global DNS alidns issue

lib/global-admin/addon/global-dns/providers/new/route.js
======
Fix Alidns issue
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21305
======
=> Fix Alidns issue

lib/shared/addon/components/storage-class/provisioner-rbd/component.js, translations/en-us.yaml
======
Ceph RBD userSecretNamespace missing
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21188
======
=> Fix Ceph RBD issue

lib/shared/addon/utils/amazon.js
======
Support AWS node driver t3a and m5a
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20372
======
=> Support AWS node driver t3a and m5a

lib/shared/addon/components/share-member-row/component.js
======
======
Linked Issues
======
======
=> correct creation of shared member for cluster templates

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js, lib/shared/addon/components/cluster-driver/driver-amazoneks/template.hbs, lib/shared/addon/components/searchable-select/component.js, translations/en-us.yaml
======
Missed critical cherrypick when backporting. 
======
Bugfix
Linked Issues
======
rancher/rancher#21433
======
=> Load ssh keys and add ssh key selection to amazon eks

lib/shared/addon/components/cluster-driver/driver-amazoneks/template.hbs
======
remove double key pairs input
======
bug fix
Linked Issues
======
======
=> fix mixed up commit

app/models/principal.js
- Adds appropriate google user icon post authentication
======
Adds the google auth profile picture to the user once he/she has been authenticated.
======
Linked Issues
======
rancher/rancher#21435
======
=> Bugfix #21435

lib/global-admin/addon/clusters/new/route.js, lib/global-admin/addon/clusters/new/select/route.js
======
kontainer engines were not being loaded on the new cluster launch routes.
======
bugfix
Linked Issues
======
N/A
======
=> Load Kontainer Engine Drivers Correctly

app/authenticated/cluster/projects/index/template.hbs, app/components/namespace-table/component.js, app/components/namespace-table/template.hbs, app/components/project-group/template.hbs
======
Fix: cannot search a project without namespaces.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21415
======
=> Fix can not search a project without namespaces

lib/shared/addon/components/cru-node-pools/component.js, lib/shared/addon/components/cru-node-pools/template.hbs, lib/shared/addon/components/node-pool-row/component.js, lib/shared/addon/components/node-pool-row/template.hbs, lib/shared/app/components/node-pool-row/component.js, translations/en-us.yaml
======
This PR exposes the new `deleteNotReadyAfterSecs` property on the node pool model. Additionally I've wrapped the input in a tooltip to explain the property a more clearly.
======
Enhancement
Linked Issues
======
rancher/rancher#20862
======
The current table view of node pools needs to change and has an issue open to track this at rancher/rancher#21508
=> Expose DeleteNotReadyAfterSecs on node pool

translations/en-us.yaml
======
This is a small change to en-us translations around Googleoauth.
This makes it a little more clear to the user what to do in the Google Developer Console UI when they are trying to set up Google Auth and fixes some grammar, etc.
======
Bugfix, non breaking changes, low risk
Linked Issues
======
https://github.com/rancher/rancher/issues/21511
======
Low-risk change to just en-us.yaml translations file
=> Update googleoauth en-us translations (make instructions more clear)

lib/monitoring/addon/components/cluster-dashboard/template.hbs, lib/monitoring/translations/en-us.yaml, lib/monitoring/translations/zh-hans.yaml
======
Fix click "Enable monitoring" link in cluster dashboard cannot go to cluster monitoring page.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21541
======
=> Fix click "Enable monitoring" link in cluster dashboard cannot go to cluster monitoring page

app/styles/pages/_host.scss, lib/global-admin/addon/clusters/new/select/template.hbs, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, lib/shared/addon/components/cru-node-pools/component.js, translations/en-us.yaml
======
Text changes & Vincent moved infrastructure provider above kubernetes provider in Select Cluster Provider page
======
- Bug fixes: Low impact, mostly just text changes.
=> Text fixes and alignment for Add Cluster

app/models/cluster.js, app/models/clustertemplaterevision.js, lib/global-admin/addon/components/cluster-template-row/template.hbs, lib/global-admin/addon/components/cluster-templates-table/component.js, lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, lib/shared/addon/components/cluster-template-question-row/template.hbs, lib/shared/addon/components/cru-cluster-template-questions/component.js, lib/shared/addon/components/cru-cluster-template-questions/template.hbs, lib/shared/addon/components/cru-cluster/component.js, lib/shared/addon/components/cru-node-pools/template.hbs, lib/shared/addon/components/cru-private-registry/component.js, lib/shared/addon/components/cru-private-registry/template.hbs, translations/en-us.yaml
======
Fix node pool alert to be full width on cluster creation.
Add enable/disable actions to cluster template revision.
Fixes bug with canDelete on the cluster template revision.
Fixes backup target (local/s3) and private registry overrides by added UI defined questions that are hidden and never answered.
Add ui action to expand all accordions when switching to a cluster template when launching a cluster.
======
Bugfix
Linked Issues
======
rancher/rancher#21407
rancher/rancher#21439
rancher/rancher#21447
rancher/rancher#21510
rancher/rancher#21563
rancher/rancher#21567
rancher/rancher#21576
======
=> Cluster Template Fixes

app/authenticated/cluster/projects/new-ns/route.js
======
Fix the issue that the default `containerDefaultResourceLimit` for a namespace when creating namespace is not applied.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21664
======
=> Fix default container limit issue

app/catalog-tab/launch/route.js, app/models/template.js, lib/global-admin/addon/components/new-multi-cluster-app/component.js
======
When using a project level catalog, if a template has a defaultVersion but that version is not available in the versionLinks due to the rancher version not supporting it, clicking view details on the app will cause the UI will go back to the apps page instead of showing details of the app to launch.
Fallback to latest version if default version not exists in a catalog app
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21008
======
=> Fallback to latest version if default version not exists in a catalog app

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js
======
Set 1.13 as default Kubernetes version for EKS
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20759
======
=> Set 1.13 as default Kubernetes version for EKS

lib/global-admin/addon/components/cru-cloud-credential/template.hbs
======
no error message shows if the name exists when creating a cloud credential
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20577
======
=> Fix cloud credential error message issue

app/models/container.js, app/models/pod.js, app/models/workload.js, lib/shared/addon/components/container-shell/component.js, lib/shared/addon/utils/constants.js
======
Allow exec shell to not ready container
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20493
======
=> Allow exec shell to not ready container

app/components/form-scoped-roles/component.js
======
Selecting to other roles doesn't work when adding role to a user. 
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19860
======
=> Fix adding role issue

app/components/cru-dns/component.js
======
Edit svc which pointing to workloads and click save.
The selector field will be set to null.
The svc will not work any more.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21670
======
=> Fix edit service issue

lib/shared/addon/components/confirm-delete/component.js, lib/shared/addon/components/confirm-delete/template.hbs, lib/shared/addon/utils/constants.js, translations/en-us.yaml
======
Add a warning message when deleting a system chart app.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19170
======
=> Should show a warning when deleting a system chart app

app/authenticated/cluster/edit/route.js, app/models/clustertemplate.js, app/models/clustertemplaterevision.js, lib/global-admin/addon/cluster-templates/new-revision/controller.js, lib/global-admin/addon/cluster-templates/new-revision/template.hbs, lib/global-admin/addon/cluster-templates/new/controller.js, lib/global-admin/addon/cluster-templates/new/template.hbs, lib/global-admin/addon/clusters/index/controller.js, lib/global-admin/addon/clusters/index/route.js, lib/global-admin/addon/clusters/index/template.hbs, lib/global-admin/addon/clusters/new/launch/route.js, lib/global-admin/addon/clusters/new/select/controller.js, lib/global-admin/addon/clusters/new/select/route.js, lib/global-admin/addon/clusters/new/select/template.hbs, lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cru-cluster-template/component.js, lib/shared/addon/components/form-share-member/component.js, lib/shared/addon/components/form-share-member/template.hbs, translations/en-us.yaml
======
Fixed undefined errors that popped up at random times
Rollback read-only checks as this all falls apart when we're using groups, dynamic RBAC is a must for this to function correctly in the UI. 
Fix the correct landing page after launching cluster template.
Fix enforcement bug
Change share public button to a checkbox in form-share-members
Fix translation conflict bug
======
Bugs
Linked Issues
======
rancher/rancher#21569
rancher/rancher#21576
rancher/rancher#21617
rancher/rancher#21685
rancher/rancher#21689
rancher/rancher#21691
rancher/rancher#21694
======
=> Cluster Template Bugs

app/authenticated/cluster/edit/template.hbs, app/models/clustertemplate.js, lib/global-admin/addon/clusters/new/launch/route.js, lib/global-admin/addon/clusters/new/launch/template.hbs, lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, lib/shared/addon/components/cru-cluster-template/template.hbs
======
Fix minor issue when global template enforcement is enabled and non-admin not being able to see the cluster template options.
======
Bugfix
Linked Issues
======
rancher/rancher#21717
======
=> Cluster Templates Enforcement Bug

app/authenticated/cluster/edit/route.js, app/models/cluster.js, lib/global-admin/addon/cluster-templates/new-revision/route.js, lib/global-admin/addon/clusters/new/launch/route.js, lib/shared/addon/components/cru-cluster/component.js
======
Reset controller variable on navigate away so the cluster template version isn't cached.
Fix cluster template change not persisting on edit. 
Fix rke config cache when falling into error state on cluster launch. 
======
Bugfix
Linked Issues
======
rancher/rancher#21680
rancher/rancher#21723
rancher/rancher#21726
======
=> Cluster Template Edit Bugs

app/styles/base/_color.scss
https://github.com/rancher/rancher/issues/21713
=> darken help text for better contrast on gray bg

app/components/modal-edit-host/template.hbs, app/components/modal-edit-node-pool/component.js, app/components/modal-edit-node-pool/template.hbs, app/components/node-row/template.hbs, lib/nodes/addon/components/driver-aliyunecs/template.hbs, lib/nodes/addon/components/driver-amazonec2/template.hbs, lib/nodes/addon/components/driver-azure/template.hbs, lib/nodes/addon/components/driver-digitalocean/template.hbs, lib/nodes/addon/components/driver-exoscale/template.hbs, lib/nodes/addon/components/driver-other/template.hbs, lib/nodes/addon/components/driver-packet/template.hbs, lib/nodes/addon/components/driver-rackspace/template.hbs, lib/nodes/addon/components/driver-vmwarevsphere/template.hbs, lib/nodes/addon/node-templates/controller.js, lib/nodes/addon/node-templates/template.hbs, lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, lib/shared/addon/components/cru-node-pools/component.js, lib/shared/addon/components/cru-node-pools/template.hbs, lib/shared/addon/components/form-node-taints/component.js, lib/shared/addon/components/form-node-taints/template.hbs, lib/shared/addon/components/node-pool-row/component.js, lib/shared/addon/components/node-pool-row/template.hbs, lib/shared/addon/components/node-taints/component.js, lib/shared/addon/components/node-taints/template.hbs, lib/shared/addon/mixins/cattle-transitioning-resource.js, lib/shared/app/components/form-node-taints/component.js, lib/shared/app/components/node-taints/component.js, translations/en-us.yaml
======
1. Support taints for node pool
2. Support taints for node
3. Support taints for node template
4. Support taints when adding custom node
5. Show taints in node list
======
Linked Issues
======
https://github.com/rancher/rancher/issues/13972
https://github.com/rancher/rancher/issues/21085
======
=> Support taints

app/styles/pages/_settings.scss
https://github.com/rancher/rancher/issues/21713
=> help block margins

README.md, translations/en-us.yaml
======
Small fix to README.md to remove leading / for yarn start. This was causing the server to crash when launch the UI.
Small fix to en-us translations for https://github.com/rancher/rancher/issues/21785 that fixes grammar/etc.
UI was tested.
======
Bugfix, minor, non-breaking
Linked Issues
======
https://github.com/rancher/rancher/issues/21785
======
UI was tested. This is a low-risk change.
=> small fix to README and en-us translations

lib/shared/addon/components/form-engine-opts/component.js
https://github.com/rancher/rancher/issues/21804
=> Docker v19.03.x support

lib/shared/addon/components/form-engine-opts/component.js
https://github.com/rancher/rancher/issues/21805
=> [release 2.2] Docker v19.03.x support

lib/shared/addon/components/form-engine-opts/component.js
https://github.com/rancher/rancher/issues/21807
=> [release 2.1] Docker v19.03.x support

lib/pipeline/addon/components/build-detail/template.hbs, lib/pipeline/addon/components/pipeline-detail/template.hbs, lib/pipeline/translations/en-us.yaml, lib/pipeline/translations/zh-hans.yaml, lib/pipeline/translations/zh-hant.yaml
Small changes for wrong wording in templates and language files.
=> Changes wrong wording of "repositry" in templates and language files

lib/istio/addon/components/istio-nav/component.js
======
The namespace should be `cattle-prometheus` when the user has access to the cluster monitoring.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21845
======
=> Fix Istio Grafana URL issue

translations/en-us.yaml
======
Change systemChartNote text.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19170
======
=> Change systemChartNote text

app/styles/abstracts/_mixins.scss, app/styles/components/_catalog-box.scss, lib/shared/addon/components/catalog-box/component.js, lib/shared/addon/components/catalog-box/template.hbs, lib/shared/addon/components/catalog-index/template.hbs
related: https://github.com/rancher/rancher/issues/20602
https://xd.adobe.com/view/c1a93038-6113-43c1-628b-781b5c952fd8-b798/
=> catalog page redesign

app/authenticated/project/hpa/detail/edit/route.js, app/authenticated/project/hpa/detail/edit/template.hbs, app/authenticated/project/hpa/new/route.js, app/authenticated/project/hpa/new/template.hbs, app/components/cru-hpa/component.js, app/components/cru-hpa/template.hbs, app/components/hpa-metric-row/template.hbs, translations/en-us.yaml
======
If there is no metrics server deployed, we need to show a warning in HPA page.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20931
======
=> Show warning in creating HPA page

lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, lib/shared/addon/components/form-versions/component.js
======
======
Linked Issues
======
rancher/rancher#21721
rancher/rancher#21866
rancher/rancher#21579
======
=> Cluster Edit Yaml

lib/istio/addon/components/istio-catalog/template.hbs, lib/istio/translations/en-us.yaml
https://github.com/rancher/rancher/issues/21688
=>  istio accorions

lib/istio/addon/components/cru-destination-rule/template.hbs, lib/istio/addon/components/cru-virtual-service/template.hbs
======
Show labels for Istio Virtual Service and Destination Rule by default
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21894
======
=> Show labels for Istio Virtual Service and Destination Rule by default

lib/nodes/addon/components/driver-azure/component.js, lib/nodes/addon/components/driver-azure/template.hbs, translations/en-us.yaml
======
Add managed disk option to azure driver
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21533
======
=> Add managed disk option to azure driver

server/proxies/api.js
======
Proxy bundled UI driver assets for dev server
======
- Bugfix
=> Proxy bundled drivers

app/models/clustertemplaterevision.js, lib/global-admin/addon/clusters/new/launch/route.js, lib/global-admin/package.json, lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, lib/shared/addon/components/cru-cloud-provider/component.js, lib/shared/addon/components/cru-cluster-template-questions/component.js, lib/shared/addon/components/cru-cluster-template/component.js, lib/shared/addon/components/cru-cluster/component.js, lib/shared/addon/components/cru-cluster/template.hbs, lib/shared/addon/components/form-versions/component.js, lib/shared/addon/mixins/new-or-edit.js, package.json, translations/en-us.yaml, yarn.lock
======
Fixes null array check bug that caused the page to not finish loading.
Fixes bug where we were always setting max version to satisfies.
Fix bug in form-versions init.
Fix bug applying cluster template revision answers.
Fix bug in editing cluster with yaml.
Fix bug in cluster template/revision validation.
Remove check for required fields in azure cloud provider when creating template.
Split cluster template/revision selection into two select's.
======
Bugfix
Linked Issues
======
rancher/rancher#21816
rancher/rancher#21898
rancher/rancher#21882
rancher/rancher#21815
rancher/rancher#21866
rancher/rancher#21616
rancher/rancher#21759
rancher/rancher#21892
rancher/rancher#21891
rancher/rancher#21928
======
N/A
=> Cluster Templates 

app/styles/components/_banners.scss, app/styles/layout/_medium.scss, app/styles/layout/_small.scss, lib/monitoring/addon/components/nodes-live/template.hbs
Fixing mobile issues https://github.com/rancher/rancher/issues/16926
=> mobile ui fixes

app/models/cluster.js, lib/global-admin/addon/components/cluster-row/template.hbs
======
Show inactive nodes and unhealthy components in cluster list
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21933
======
=> Show inactive nodes and unhealthy components in cluster list

app/templates/tooltip-container-dot.hbs, lib/monitoring/addon/components/enable-monitoring/component.js
======
- Support node selector and tolerations for other monitoring components
- Show node name in pod dot tooltip
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20730
======
=> Support node selector and tolerations for other monitoring components

lib/shared/addon/components/cru-cloud-provider/component.js, lib/shared/addon/components/cru-cloud-provider/template.hbs, translations/en-us.yaml
======
- Add external option for cloud provider
- Fix the issue that cannot select custom option for cloud provider
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21301
======
=> Add external option for cloud provider

package.json, yarn.lock
======
Adds resolutions to deal with security issues in dependencies. Most of these can be removed post ember 3.11 upgrade as we should upgrade the dependencies as well. 
======
Linked Issues
======
======
=> Add resolutions until ember upgrade

lib/global-admin/addon/mixins/authentication.js
======
Remove PUT request after disable action.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21803
======
=> Remove PUT request on disabling auth

app/components/container/form-ports/component.js
======
Per David, we should allow users to config host port for Windows cluster
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20940
======
=> Allow users to config host port for Windows cluster

translations/en-us.yaml
======
Typo fix.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21995
======
=> [UI] Istio - Fix new Istio Auto Injection button typo

lib/monitoring/addon/components/enable-monitoring/component.js
======
Pass monitoring version to backend
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21460
======
=> Pass monitoring version to backend

lib/shared/addon/mixins/catalog-app.js
======
Fix catalog file display issue
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20828
======
=> Fix catalog file display issue

lib/nodes/addon/components/driver-azure/template.hbs
======
Fix Azure node pool input range issue
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22015
======
=> Fix Azure node pool input range issue

lib/istio/addon/components/istio-catalog/template.hbs, lib/istio/translations/en-us.yaml, lib/monitoring/addon/components/enable-monitoring/template.hbs, lib/monitoring/translations/en-us.yaml, lib/shared/addon/components/save-cancel/template.hbs
======
Update the UX for enabling istio
- Have all accordions expect Member Access collapsed by default
- Remove "Cancel" button from bottom of page
- Move Disable button to the bottom for Istio and Monitoring
- Add own accordion for custom answers
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21688
======
=> Update the UX for enabling istio

app/components/cru-hpa/component.js, app/components/cru-hpa/template.hbs, app/components/hpa-metric-row/component.js, app/components/hpa-metric-row/template.hbs, lib/shared/addon/components/form-namespace/component.js, lib/shared/addon/components/form-namespace/template.hbs, translations/en-us.yaml
======
Fixed some UX issues in https://github.com/rancher/rancher/issues/21632
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21632
======
=> Fix HPA UX issue

lib/istio/addon/components/istio-nav/component.js
======
Fix project-level istio Prometheus URL
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22023
======
=> Fix project-level Istio Prometheus URL

app/authenticated/cluster/edit/route.js, app/models/cluster.js, lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, lib/shared/addon/components/cluster-template-question-row/template.hbs, lib/shared/addon/components/cru-cluster-template/template.hbs, lib/shared/addon/components/form-network-config/template.hbs, lib/shared/addon/components/form-versions/component.js, translations/en-us.yaml
======
Various Cluster Template fixes
======
Bugfix
Linked Issues
======
rancher/rancher#21414
rancher/rancher#21756
rancher/rancher#22018
rancher/rancher#21778
rancher/rancher#21616
rancher/rancher#21473
rancher/rancher#22021
rancher/rancher#22038
======
N/A
=> Cluster Template / Cluster Create fixes

app/instance-initializers/nav.js, lib/shared/addon/components/settings/danger-zone/template.hbs, translations/en-us.yaml
======
Minor text changes
======
Bug fix
Linked Issues
======
https://github.com/rancher/rancher/issues/21824 
https://github.com/rancher/rancher/issues/21985
=> minor text issues

translations/en-us.yaml
======
Remove term "Rancher" and "rancher" in appropriate areas in the en-us.yaml translations file.
======
Bugfix, non-breaking, low risk
Linked Issues
======
https://github.com/rancher/rancher/issues/21690
======
Low risk change to en-us.yaml
=> remove Rancher term in appropriate areas

lib/shared/addon/components/cluster-driver/driver-azureaks/component.js, lib/shared/addon/components/cluster-driver/driver-azureaks/template.hbs, lib/shared/addon/utils/azure-choices.js
======
Support China AKS
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21668
======
=> Support China AKS

app/components/node-selector/component.js, lib/shared/addon/utils/constants.js
======
- `>=` and `<=` are not valid operators `https://kubernetes.io/docs/concepts/configuration/assign-pod-node/`, We should remove them.
- `NotIn` should work
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22058
======
=> Fix node selector issue

app/components/cru-registry/template.hbs, translations/en-us.yaml
======
Show Artifactory as an option for registry
There is no difference with custom.
nothing except that list aritfactory as a radio button
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20394
======
=> Add Artifactory as an option for registry

app/app.js, lib/global-admin/addon/components/cru-cloud-credential/component.js, lib/global-admin/addon/components/cru-cloud-credential/template.hbs, lib/shared/addon/linode/service.js, lib/shared/addon/mixins/node-driver.js, lib/shared/app/linode/service.js
https://github.com/rancher/rancher/issues/21838
=> [UI] Linode ui fix

app/models/cluster.js, lib/global-admin/addon/cluster-templates/detail/controller.js, lib/global-admin/addon/cluster-templates/detail/route.js, lib/global-admin/addon/cluster-templates/detail/template.hbs, lib/global-admin/addon/routes.js, lib/shared/addon/components/authorized-endpoint/template.hbs, lib/shared/addon/components/check-override-allowed/template.hbs, lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, lib/shared/addon/components/cluster-template-row/template.hbs, lib/shared/addon/components/cru-cloud-provider/template.hbs, lib/shared/addon/components/cru-cluster-template-questions/template.hbs, lib/shared/addon/components/cru-cluster-template/template.hbs, lib/shared/addon/components/cru-private-registry/template.hbs, lib/shared/addon/components/form-network-config/template.hbs, lib/shared/addon/components/form-share-member/template.hbs, lib/shared/addon/components/form-versions/component.js, lib/shared/addon/components/form-versions/template.hbs, lib/shared/addon/components/input-yaml/component.js, lib/shared/addon/components/share-member-row/component.js, lib/shared/addon/components/share-member-row/template.hbs, lib/shared/addon/mixins/view-new-edit.js, translations/en-us.yaml
======
Adds revision detail page.
Adds yaml but make read only on details page.
Removes the ability to add arbitrary overrides.
Fixes bug where private registry params were not populating.
Disables cluster template selection when editing.
Reverts change made for editing cluster when unknown node-template.
Adds check for missing rke config in the yaml editor.
======
Linked Issues
======
rancher/rancher#21716
rancher/rancher#22084
rancher/rancher#22072
rancher/rancher#22043
rancher/rancher#22080
rancher/rancher#22076
======
=> Cluster Templates

lib/logging/addon/components/logging/form-log-ssl/template.hbs, lib/logging/addon/components/logging/new-edit/component.js, lib/logging/addon/components/logging/target-flentd/template.hbs
======
Add `SSL Verify`, `Client Key Password`, `Client Certificate` and `Client Private Key` for Fluentd forward.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18437
======
Level | UI Field Name | Yaml Field Name
-- | -- | --
cluster Fluentd | Client Private Key | Secrets.rancher-logging-fluentd-ssl.'cluster_clusterId_client-key.pem'
  | Client Certificate | Secrets.rancher-logging-fluentd-ssl.'cluster_clusterId_client-cert.pem'
  | Client Key Password | Secrets.rancher-logging-fluentd.'cluster.conf'.tls_client_private_key_passphrase
  | SSL Verify | Secrets.rancher-logging-fluentd.'cluster.conf'.tls_verify_hostname
  | CA Certificate PEM | …
=> Add Client key and certificate in Fluentd normal mode

app/models/clusteralertrule.js, app/models/projectalertrule.js, lib/alert/addon/components/alert-rule/new-edit/component.js, lib/alert/addon/components/alert/form-cluster-rule-row/component.js, lib/alert/addon/components/alert/form-cluster-rule-row/template.hbs, lib/alert/addon/components/alert/form-comparison-row/component.js, lib/alert/addon/components/alert/form-comparison-row/template.hbs, lib/alert/addon/components/alert/form-project-rule-row/component.js, lib/alert/addon/components/alert/form-project-rule-row/template.hbs, lib/alert/addon/components/alert/new-edit/component.js, lib/alert/addon/mixins/alert-rule.js, lib/alert/translations/en-us.yaml, lib/shared/addon/utils/constants.js
======
Add "Not Null" option for metrics rule.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21790
======
=> Support exist condition for metric alert

translations/en-us.yaml
======
Fix lack of translation
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21985
======
=> Fix lack of translation

lib/global-admin/addon/security/authentication/googleoauth/template.hbs, translations/en-us.yaml
======
Add flag to enable/disable nested groups for google auth
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22044
======
=> Add flag to enable/disable nested groups for google auth

README.md
======
Added a callout to non-standard items in the rancher ui project.
======
Linked Issues
======
======
=> updates for new developers

app/containers/run/template.hbs
======
When we refactor catalog page, edit sidecar page is impacted. They are sharing the same component
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22120
======
=> Fix sidecar edit issue

lib/shared/addon/utils/util.js
======
UI will not convert `kube-controller` to `kubeController`, so backend can not populate it.
In RKE docs and previous versions, users don't have to use `kube_controller`.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22119
======
=> Fix cluster yaml issue

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js, lib/shared/addon/components/cluster-driver/driver-amazoneks/template.hbs, translations/en-us.yaml
======
Refactor EKS node ASG-size fields due to backend changes. You can find more info in the issue.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22097
======
=> Refactor EKS node ASG-size fields

lib/nodes/addon/custom-drivers/cluster-drivers/controller.js, lib/nodes/addon/custom-drivers/cluster-drivers/template.hbs, translations/en-us.yaml
======
Show refresh action for k8s metadata
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21366
======
=> Show refresh button for k8s metadata

lib/shared/addon/components/form-user-labels/template.hbs
======
When editing node tags, "enter" deletes the 1st tag
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18445
======
=> Fix enter key issue

lib/global-admin/addon/components/new-multi-cluster-app/component.js
======
Fix launch multi-cluster apps error issue 
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20871
======
=> Fix launch multi-cluster apps issue

lib/global-admin/addon/components/new-multi-cluster-app/component.js
======
Multi cluster app upgrade issue. 
Fix the issue that cannot remove a project and add the project back before upgrading the app
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21801
======
=> Multi cluster app upgrade issue

lib/shared/addon/components/cluster-driver/driver-googlegke/component.js
======
Fix missing gke k8s version issue
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22117
======
=> Fix gke k8s version issue

lib/nodes/addon/components/driver-aliyunecs/component.js, vendor/aliyun-sdk.js
======
Show available instances types only for Aliyun ecs
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22111
======
=> Show available instances types only for Aliyun ecs

app/verify-auth/route.js, lib/shared/addon/oauth/service.js
======
Google Auth - UI doesnt handle invalid inputs in OAuth credentials well
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21430
======
=> Fix google auth issue

app/components/modal-restore-backup/component.js, app/components/modal-restore-backup/template.hbs
======
Backups stuck in "Activating" state should not be selected.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/18699
======
=> Backups stuck in "Activating" state should not be selected

lib/shared/addon/components/form-versions/component.js
======
Fix form-version error
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19478
======
=> Fix form-version error

lib/shared/addon/mixins/crud-catalog.js
======
Fix Istio error handle
======
Linked Issues
======
https://github.com/rancherlabs/rancher-security/issues/182
======
=> Fix Istio error handle

lib/shared/addon/mixins/node-driver.js
======
Show azure node template location for region
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19565
======
=> Show azure node template location for region

lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, lib/shared/addon/components/cru-cluster/template.hbs, lib/shared/addon/components/form-network-config/template.hbs
======
Fix Windows cluster template
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21557
======
=> Windows cluster template

lib/global-admin/addon/cluster-templates/new/route.js, lib/shared/addon/components/cru-cloud-provider/component.js, lib/shared/addon/components/cru-cluster-template/component.js, translations/en-us.yaml
======
Move required Azure fields to the top.  The required ones must either be set or marked overrideable for a cluster template.
======
Linked Issues
======
rancher/rancher#22041
=> Azure fields are required in template (rancher/rancher#22041)

lib/istio/addon/components/traffic-monitoring/component.js, lib/istio/addon/components/traffic-monitoring/template.hbs, lib/istio/translations/en-us.yaml
======
Discussed with Will and Tani.
Add a "Refresh Graph" button next to the Namespace drop-down.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21811
======
=> Show refresh btn for istio graph

lib/istio/addon/components/istio-catalog/template.hbs, lib/istio/translations/en-us.yaml
======
Fixes to Istio text & translations
======
text - non-breaking
Linked Issues
======
https://github.com/rancher/rancher/issues/22156
https://github.com/rancher/rancher/issues/21994
=> Istio page text changes & fixes to translations

app/models/clustertemplaterevision.js, lib/global-admin/addon/cluster-templates/new/route.js, lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, lib/shared/addon/components/cluster-template-row/template.hbs, lib/shared/addon/components/cluster-templates-table/component.js, lib/shared/addon/components/cru-cluster-template/component.js, lib/shared/addon/components/form-versions/component.js, lib/shared/addon/components/sortable-table/component.js, lib/shared/addon/mixins/cattle-transitioning-resource.js, translations/en-us.yaml
======
Cluster template cleanup & bugs
======
Linked Issues
======
rancher/rancher#22085
=> Cluster template

translations/en-us.yaml
======
Text changes on Add Cluster & Cluster Template
======
Text changes - non-breaking
Linked Issues
======
https://github.com/rancher/rancher/issues/22078
======
=> Cluster template verbiage change

app/authenticated/cluster/edit/template.hbs
======
Show driver name in edit cluster page
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21562
======
=> Show driver name in edit cluster page

app/components/namespace-app/component.js
======
Fix apps icon missing issue
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22152
======
=> Fix apps icon missing issue

lib/shared/addon/mixins/tooltip.js
======
The caret position is incorrect sometimes.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22154
======
=> Fix tooltip issue

lib/shared/addon/components/cru-cluster/template.hbs
======
Fix gke style issue
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22151
======
=> Fix gke style issue

lib/global-admin/addon/components/new-multi-cluster-app/component.js
======
Bug fix - Able to supply no target projects on app upgrade
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22130
======
=> Able to supply no target projects on app upgrade

lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, lib/shared/addon/components/input-yaml/component.js, lib/shared/addon/components/input-yaml/template.hbs
======
Linked Issues
======
rancher/rancher#22076
======
======
Linked Issues
======
======
=> Missing RKE config

lib/global-admin/addon/components/cru-cloud-credential/component.js
https://github.com/rancher/rancher/issues/22128
=> [UI] Check Linode cloud credential against profile

lib/shared/addon/components/cluster-driver/driver-googlegke/component.js, lib/shared/addon/components/cluster-driver/driver-googlegke/template.hbs, translations/en-us.yaml
======
Support GKE regional or zonal clusters
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22045
======
=> Support GKE regional or zonal clusters

app/authenticated/cluster/backups/template.hbs
======
Show transitioning message for snapshots
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20685
======
=> Show transitioning message for snapshots

app/styles/components/_banners.scss
======
removed break-all so words in banner aren't being cut off and started on new line
======
bug fix - non-breaking
Linked Issues
======
https://github.com/rancher/rancher/issues/22178
======
=> removed break-all from banner

app/components/accordion-pod/component.js, app/styles/pages/_host.scss, lib/shared/addon/components/cluster-templates-table/template.hbs, lib/shared/app/components/cluster-templates-table/template.hbs
machine driver bg:
https://github.com/rancher/rancher/issues/22017
ip address cut off in table:
https://github.com/rancher/rancher/issues/21767
empty table img container templates:
https://github.com/rancher/rancher/issues/22163
=> 22017, 21767

app/components/notifier/modal-new-edit/component.js, app/components/notifier/modal-new-edit/template.hbs
======
defaultRecipient of slackConfig is not a required field.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/20067
======
=> slackConfig should not require slackConfig should not require defaultRecipient

lib/shared/addon/components/input-answer-row/component.js, lib/shared/addon/components/input-answer-row/template.hbs
======
Pass namespace.id to schema/input-secret
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22092
======
=> Fix can't select existing secret in the catalog ui

lib/pipeline/addon/components/edit-pipeline-config/component.js, lib/pipeline/addon/components/modal-pipeline-yaml/component.js, lib/pipeline/addon/components/steps/step-scm/component.js
======
Added a new backend API to fix it.
Fix pipeline missing branch issue.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22049
======
=> Fix pipeline missing branch issue

lib/global-admin/addon/cluster-templates/new/route.js, lib/shared/addon/components/cru-cluster-template/component.js
======
======
Linked Issues
======
======
=> First revision, azure cloud provider

lib/shared/addon/components/confirm-delete/component.js, lib/shared/addon/components/confirm-delete/template.hbs, translations/en-us.yaml
======
Force delete pod
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21672
======
=> Force delete pod

lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
======
Prevent submitting a cluster with missing rancher_kubernetes_engine_config YAML
======
Linked Issues
======
rancher/rancher#22076
=> Don't submit if there are errors

lib/alert/translations/en-us.yaml, lib/istio/translations/en-us.yaml, lib/pipeline/translations/en-us.yaml, translations/en-us.yaml
======
change empty table text to be more consistent
======
- Text change - non-breaking
Linked Issues
======
https://github.com/rancher/rancher/issues/22187
======
=> change empty table text to be more consistent

lib/alert/addon/components/alert/form-comparison-row/component.js
======
Fix threshold is reset when edit alert rule
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22210
======
=> Fix threshold is reset when edit alert rule

lib/global-admin/addon/components/form-google-auth/template.hbs, lib/global-admin/addon/security/authentication/googleoauth/template.hbs
======
Add Edit button for Google Auth.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22214
======
=> Add Edit button for Google Auth

app/models/kontainerdriver.js, app/models/nodedriver.js, lib/shared/addon/components/form-share-member/component.js, lib/shared/addon/components/form-share-member/template.hbs, lib/shared/addon/components/modal-confirm-deactivate/component.js, lib/shared/addon/components/modal-confirm-deactivate/template.hbs, lib/shared/addon/components/share-member-row/component.js, lib/shared/addon/components/share-member-row/template.hbs, translations/en-us.yaml
======
- Update access type text for sharing template
- Show an information tip for sharing template
- Show confirm popup when deactivating driver
======
Linked Issues
======
rancher/rancher#22200
rancher/rancher#22201
rancher/rancher#19876
======
=> Warning messages

lib/global-admin/addon/components/form-global-roles/component.js, package.json
======
Fix custom role issue
======
Linked Issues
======
======
=> [v2.2]Fix custom role issue

lib/global-admin/addon/components/form-global-roles/component.js
======
Fix custom role issue
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19640
======
=> Fix custom role issue

lib/shared/addon/components/confirm-delete/template.hbs, translations/en-us.yaml
======
Text changes for Cluster Certificate section & force delete pod
======
bugfix - non-breaking
Linked Issues
======
https://github.com/rancher/rancher/issues/20009
https://github.com/rancher/rancher/issues/21672
======
=> Add cluster Cert & Force delete text improvements

lib/shared/addon/utils/constants.js
======
Remove access type Member for cluster template
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22280
======
=> Remove access type Member for cluster template

lib/shared/addon/components/badge-state/template.hbs, lib/shared/addon/mixins/cattle-transitioning-resource.js
======
======
Linked Issues
======
======
=> Cache translated states

app/components/page-header/template.hbs, app/instance-initializers/nav.js
======
Add condiction to check cluster isReady for cluster Istio.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22213
======
=> Add condiction to check cluster isReady for cluster Istio

lib/shared/addon/components/accordion-list-item/component.js, lib/shared/addon/components/accordion-list-item/template.hbs
======
Cannot click the a tag inside accordion detail text
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22273
======
=> Fix accordion issue

app/components/new-edit-project/template.hbs, lib/shared/addon/components/modal-confirm-deactivate/template.hbs, translations/en-us.yaml
======
- Support annotations and labels for project
- Fix typo
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19876
https://github.com/rancher/rancher/issues/21700
======
=> Support annotations and labels for project

lib/istio/translations/en-us.yaml
======
Fix warning text for Istio
======
Text fix - non-breaking
Linked Issues
======
https://github.com/rancher/rancher/issues/22040
======
=> Fix warning text for Istio

app/components/page-header-project/template.hbs, app/styles/components/_page-header.scss
======
Add link for page-header-dropdown transition to project/namespace page.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21345
======
=> Add Edit Project link from within project views

lib/global-admin/addon/components/new-multi-cluster-app/component.js, lib/shared/addon/mixins/catalog-app.js
======
In launch catalog page, we can control if an input should show or not.
But now, no matter if the fields show or not. We will pass the answers to backend. 
For example, if users select `false` for `Enable PVC`.  We still put the pvc size and other fields in answers.
Another example, if users select `true` for `Use default Image`. We will still put `image.tag` into answers. For example, `image.tag=v0.0.1`. When we upgrade to `v0.0.2`, rancher will still use `v0.0.1` for it due to the answer.
So I think we should filter out the hidden fields as users don't care about them. Also it will make chart developer easier, they don't have to add many if-else block in the template. Then it will use the default values in the charts.
======
- Bugfix (non-breaking …
=> Do not pass answers it they are hidden fields in catalog answers

translations/en-us.yaml, translations/zh-hans.yaml
======
Update internationalization documents
1.  add baidu and pingan driver name translation
=> [UI] add baidu and pingan driver name translation

lib/shared/addon/components/cluster-driver/driver-huaweicce/component.js
======
availableZones can change default value when using custom region.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22294
======
=> Fix CCE availableZones doesn't change when using custom region

translations/en-us.yaml
======
tooltip fix for cluster template
======
Text Edit - Non-breaking
Linked Issues
======
https://github.com/rancher/rancher/issues/22229
======
=> tooltip fix for cluster template

lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
======
1. Change for windows CMD.
2. Remove windowsPreferedCluster, it should let node taints show in windows cluster.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22059
https://github.com/rancher/rancher/issues/22157
======
=> Fix Windows Unable to set windows node advanced options

lib/istio/addon/components/istio-catalog/component.js, lib/istio/addon/components/istio-catalog/template.hbs
======
Add tracing toleration for Istio
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22413
======
=> [2.3.0]Support tracing toleration

app/models/clustertemplaterevision.js
======
Use disable/enable actions on ClusterTemplateRevision object instead of  using `save()`.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22374
======
=> [2.3.0]Use disable/enable actions on ClusterTemplateRevision object

lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, lib/shared/addon/components/form-network-config/component.js, translations/en-us.yaml
======
Disable Windows in k8s 1.14
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22375
======
=> [2.3.0]Disable Windows in k8s 1.14

translations/en-us.yaml
======
Translation fix on github auth page
======
bugfix - non-breaking
Linked Issues
======
https://github.com/rancher/rancher/issues/22460
======
=> translation fix

lib/global-admin/addon/components/form-google-auth/template.hbs, lib/global-admin/addon/security/authentication/googleoauth/template.hbs, translations/en-us.yaml
https://github.com/rancher/rancher/issues/21389
=> google auth

lib/shared/addon/components/cluster-driver/driver-azureaks/component.js, lib/shared/addon/components/cluster-driver/driver-azureaks/template.hbs
======
1. Fix network mode display wrong when editing.
2. Change `netMode` style.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22500
======
=> [AKS] Fix network mode display wrong when editing

lib/shared/addon/components/custom-catalog/component.js, lib/shared/addon/components/custom-catalog/template.hbs
======
Hide system-library from Catalogs page
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22490
======
=> Hide system-library from Catalogs page

app/components/container-logs/component.js, app/components/container-logs/template.hbs, translations/en-us.yaml, translations/zh-hans.yaml
Signed-off-by: Zhiyu Wang <cloudsky.newbis@gmail.com>
======
The log plane cannot see the log before the container crashed.
======
=> [UI] add previous log support

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js
======
add ap-east-1 to eks region dropdown
======
enhancement
Linked Issues
======
UI: https://github.com/rancher/rancher/issues/22339
======
=> Add ap-east-1 to eks region dropdown

app/authenticated/project/ns/index/template.hbs
======
Remove "In this Project" bar from NS page
======
Bugfix - No reason for extra grey title bar to be on page.
Linked Issues
======
https://github.com/rancher/rancher/issues/21629
======
=> Remove "In this Project" bar from NS page

app/components/page-header/template.hbs, app/instance-initializers/nav.js, lib/global-admin/addon/clusters/index/template.hbs, lib/global-admin/addon/clusters/new/launch/route.js, lib/global-admin/addon/routes.js, lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cru-cluster-template-questions/component.js, translations/en-us.yaml, translations/zh-hans.yaml
https://github.com/rancher/rancher/issues/22529
=> cluster template to rke template

app/models/cluster.js, lib/monitoring/addon/components/cluster-dashboard/template.hbs, lib/monitoring/addon/node-detail/template.hbs, lib/monitoring/translations/en-us.yaml, lib/shared/addon/components/node-taints/component.js, lib/shared/addon/components/node-taints/template.hbs, lib/shared/addon/mixins/cattle-transitioning-resource.js, lib/shared/addon/utils/constants.js
======
- Make k8s taints readonly.
- Hide k8s role taints in node list.
- Sort display taints display string.
- Show role info in node detail view
- Show warning for node has disk pressure.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22545
======
=> [2.3.0] Taints

app/components/notifier/modal-new-edit/component.js, app/components/notifier/modal-new-edit/template.hbs, translations/en-us.yaml
======
1. Add SendResolved field to Notifier
2. Only select a notifier type can click save button and show test button.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22348
======
=> [2.3.0] Add SendResolved field to Notifier

translations/en-us.yaml
https://github.com/rancher/rancher/issues/22492
=> google auth translation fix

app/components/input-edit-password/component.js, app/instance-initializers/nav.js, lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cru-cloud-provider/component.js, lib/shared/addon/components/cru-cluster-template/template.hbs, lib/shared/addon/components/cru-node-pools/component.js
Linked Issues
======
rancher/rancher#21815
rancher/rancher#22041
=> Fix azure required fields, rke templates option location

app/components/node-row/template.hbs, lib/shared/addon/mixins/cattle-transitioning-resource.js, lib/shared/addon/utils/constants.js
======
Show k8s role taints and remove unschedule label
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22565
======
=> Show k8s role taints and remove unschedule label

lib/nodes/addon/custom-drivers/cluster-drivers/controller.js, lib/nodes/addon/custom-drivers/cluster-drivers/template.hbs, translations/en-us.yaml
======
1. Change the "Download rancher Images" button to dropdown, it has two options: Linux and Windows.
2. Click Linux will download list as `rancher-linux-images.txt`, Click Windows will download list as `rancher-windows-images.txt`.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22569
======
=> Add link for downloading windows system images

translations/en-us.yaml, translations/zh-hans.yaml
======
Changed text in rke template to refer to Create Cluster Template role.  Can't change role name, so changing info box to refer to that role and added a link to page.
======
bug fix- non-breaking
Linked Issues
======
https://github.com/rancher/rancher/issues/22608
======
=> Change text in rke template

lib/shared/addon/utils/constants.js, translations/en-us.yaml
======
Show setting `rke-metadata-config` under settings
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22573
======
=> Show setting `rke-metadata-config` under settings

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js, lib/shared/addon/utils/amazon.js
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
https://github.com/rancher/rancher/issues/22630
=> Add Bahrain/me-south-1 to EKS regions

lib/shared/addon/utils/constants.js
======
Hide failure-domain label in node list
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22331
======
=> [2.3.0]Hide failure-domain label in node list

lib/global-admin/addon/global-dns/entries/index/template.hbs, lib/global-admin/addon/global-dns/providers/index/template.hbs, translations/en-us.yaml
======
dns provider/entries translation fix
======
Bugfix - non-breaking
Linked Issues
======
https://github.com/rancher/rancher/issues/22652
======
=> dns provider/entries translation fix

lib/shared/addon/components/form-auth-cloud-credential/component.js
======
Fix cloud credential issue
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22662
======
=> [2.3.0]Fix cloud credential issue

app/components/modal-about/component.js, app/components/modal-about/template.hbs, lib/nodes/addon/custom-drivers/cluster-drivers/controller.js, lib/nodes/addon/custom-drivers/cluster-drivers/template.hbs, translations/en-us.yaml
======
Move download Image list to Version pop-up
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22664
======
=> Move download Image list to Version pop-up

lib/shared/addon/components/cru-node-pools/component.js, lib/shared/addon/components/cru-node-pools/template.hbs, lib/shared/addon/components/node-pool-row/component.js, lib/shared/addon/components/node-pool-row/template.hbs
======
Hide "Edit Taints" button when taintSupport is not true on edit RKE cluster.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22671
======
=> Cannot edit taints when taintSupport is not true on edit rke cluster

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js
https://docs.aws.amazon.com/eks/latest/userguide/platform-versions.html
=> Add Amazon EKS 1.14

app/styles/components/_forms.scss, lib/shared/addon/components/cru-private-registry/template.hbs
======
Strip off https:// for private registry
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21591
======
=> Strip off https:// for private registry

app/authenticated/project/certificates/detail/index/template.hbs, app/components/cru-config-map/template.hbs, app/components/cru-persistent-volume-claim/template.hbs, app/components/cru-secret/template.hbs, app/components/form-related-workloads/component.js, app/components/form-related-workloads/template.hbs, app/models/certificate.js, app/models/configmap.js, app/models/persistentvolumeclaim.js, app/models/secret.js, translations/en-us.yaml
======
Show related workloads in PVC/ConfigMap/Secret/Certificate detail page
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22745
======
=> Workload detail

app/components/resource-event-list/component.js, app/components/resource-event-list/template.hbs
======
Fix expand all issue
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22766
======
=> Fix expand all issue

lib/pipeline/addon/components/settings-git/component.js, lib/pipeline/addon/components/settings-git/template.hbs, lib/pipeline/translations/en-us.yaml, lib/pipeline/translations/zh-hans.yaml
======
Fix project member navigating to Project Pipeline Settings issue
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21362
======
=> Fix project member navigating to Project Pipeline Settings issue

app/apps-tab/index/controller.js, app/apps-tab/index/template.hbs, app/components/namespace-table/component.js, app/components/pod-dots/component.js, lib/global-admin/addon/multi-cluster-apps/index/controller.js, lib/global-admin/addon/multi-cluster-apps/index/template.hbs, lib/shared/addon/components/search-text/component.js, lib/shared/addon/components/search-text/template.hbs, lib/shared/addon/components/sortable-table/component.js, lib/shared/addon/utils/search-text.js, lib/shared/app/components/search-text/component.js, lib/shared/app/utils/search-text.js, translations/en-us.yaml
======
Support search in apps and multi-cluster apps list page
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22744
======
=> Support search in apps and multi-cluster apps list page

app/apps-tab/index/controller.js, app/components/namespace-table/component.js, app/components/pod-dots/component.js, lib/global-admin/addon/multi-cluster-apps/index/controller.js, lib/shared/addon/components/project-member-row/component.js, lib/shared/addon/utils/search-text.js
=> Disable read-only role for cluster members

app/authenticated/project/ns/index/template.hbs
=> Revert "Remove "In this Project" bar from NS page"

app/catalog-tab/launch/route.js, lib/shared/addon/mixins/catalog-upgrade.js
======
Show current version even it doesn't match min max Rancher version
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22842
======
=> Fix current version missing issue

lib/shared/addon/components/resource-event-list/component.js, lib/shared/addon/components/resource-event-list/template.hbs
======
Support paging for events list
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22858
======
=> Support paging for events list

lib/nodes/addon/components/driver-amazonec2/component.js, lib/nodes/addon/components/driver-amazonec2/template.hbs, translations/en-us.yaml
=> Revert "Add standard volume type for AWS"

translations/en-us.yaml
======
This should just say `CA Certificate`
======
Linked Issues
======
======
=> Corrected CA certificate label for auth endpoint

lib/shared/addon/components/form-versions/component.js
======
Version compare need `coerceVersion()` first. After `coerceVersion`, 1.14 will be 1.14.0.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22894
======
=> Fix cannot edit v1.14 k8s EKS cluster

lib/global-admin/addon/components/form-google-auth/template.hbs, translations/en-us.yaml
======
Fix translation according to issue comment.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22887
======
=> Fix Google Auth translation

app/components/container/new-edit/component.js, app/components/container/new-edit/template.hbs, lib/shared/addon/utils/constants.js
======
Fix label missing issue. 
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22913
======
=> Fix label missing issue

lib/shared/addon/catalog/service.js
======
Remove rancherVersion in its requests
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22921
======
=> Remove rancherVersion in its requests

lib/shared/addon/components/storage-class/provisioner-gce-pd/component.js, lib/shared/addon/components/storage-class/provisioner-gce-pd/template.hbs, translations/en-us.yaml
======
Add missing gce-pd fields
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22932
======
=> Add missing gce-pd fields

lib/global-admin/addon/components/form-google-auth/template.hbs, translations/en-us.yaml
======
Fix google auth text issue
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22968
======
=> Fix google auth text issue

lib/shared/addon/components/authorized-endpoint/component.js, lib/shared/addon/components/authorized-endpoint/template.hbs
======
Tweaking a change made in rancher/ui#3376 to account for both cases. the fix
added would allow the case when deploying from a template but would break for
non-template launches when the value would be a bool again. Added a type check to
handle both cases.
======
Bugfix
Linked Issues
======
rancher/rancher#22972
======
A ticket should be opened up for the `listquestions` api to fix the incorrect storage issue. 
https://github.com/rancher/rancher/issues/23039 was created.
=> Cluster Template Local Auth Endpoint Init Bugfix

app/models/catalog.js, lib/shared/addon/components/catalog-index/component.js, lib/shared/addon/components/custom-catalog/component.js, lib/shared/addon/utils/constants.js
======
Add Alibaba App Hub in catalog list and disable it by default
======
Linked Issues
======
https://github.com/rancher/rancher/issues/23042
======
=> Add Alibaba App Hub in catalog list and disable it by default

lib/shared/addon/components/cluster-driver/driver-azureaks/template.hbs, translations/en-us.yaml
======
Update aks ssh field placeholder
======
Linked Issues
======
https://github.com/rancher/rancher/issues/23073
======
=> Update aks ssh field placeholder

lib/istio/addon/components/istio-nav/template.hbs, lib/istio/addon/project-istio/template.hbs, lib/istio/translations/en-us.yaml
======
I commented out the destinationRules and virtualServices tabs from the
istio-project template, changed some verbiage in the remaining nav tabs, and
added to import yaml link to both tabs to make the ux a little less confusing.
In the next release this page will undergo a redesign so I did not remove the
code.
======
Bugfix
Linked Issues
======
rancher/rancher#23108
======
=> Remove Istio nav tabs and simplify UX

lib/shared/addon/components/form-auth-cloud-credential/component.js
======
Fix cloud credential issue
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22663
======
=> [2.2.9]Fix cloud credential issue

lib/global-admin/addon/components/new-multi-cluster-app/component.js, lib/shared/addon/mixins/catalog-app.js
======
Do not pass hidden fields in catalog answers
======
Linked Issues
======
https://github.com/rancher/rancher/issues/23115
======
=> [2.2][Backport]Do not pass hidden fields in catalog answers

lib/istio/addon/components/istio-nav/component.js, lib/istio/addon/components/istio-nav/template.hbs, lib/istio/addon/project-istio/template.hbs, lib/shared/addon/utils/constants.js
======
Virtual Service UI support is hidden.
Instead of removing it, we can use feature flag to turn it off.
Users can turn it on if they want.
Confirmed with Bill
======
Linked Issues
======
https://github.com/rancher/rancher/issues/23137
======
=> [2.3.0]Istio Virtual Service feature flag

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js
======
.
======
Bugfix
Linked Issues
======
rancher/rancher#23150
======
N/A
=> Add two new EKS regions to eks driver list

testem.js, tests/unit/utils/sort-test.js
======
This is just a proof of concept demonstrating how to do util tests.
-disable-gpu was removed so the tests can run.
-Chrome was removed from launch_in_dev because it caused
so many browsers to open.
======
=> Putting together a POC for util unit tests

lib/alert/addon/components/alert/form-cluster-rule-row/template.hbs, lib/alert/addon/components/alert/form-project-rule-row/template.hbs
======
Change no-data message to text-muted like table no-data message.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/22742
======
=> [2.3.1][Alerting] Change no-data message to text-muted

app/components/node-row/template.hbs, app/models/node.js, lib/monitoring/addon/components/node-dashboard/template.hbs, translations/en-us.yaml
======
Checks the os info of a cluster to see if its docker or container d and display the appropriate label in each case.
=====
Enhancement 
Linked Issues
======
rancher/rancher#21099
======
N/A
=> [2.3.2] Dynamically change version label on node dashboard 

lib/global-admin/addon/components/cru-cloud-credential/template.hbs
======
Cloud credential schema allows for the name field to be edited, this PR simply exposes that functionality in the UI.
======
Enhancement
Linked Issues
======
rancher/rancher#23059
======
N/A
=> [2.3.2] Allow edits to cloud credential name

app/components/new-catalog/component.js
======
The answers preview tab on the catalog launch page for project level apps did
not sync answer changes when editing the answers from the yaml view because the
answers string was not watching nor was it fetching the yaml values for answers
======
Bugfix
Linked Issues
======
rancher/rancher#20087
======
N/A
=> [2.3.2] Parse yaml answers from project level app & edit as yaml

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js
======
Change eks default ami to m5.large from m4.large. m4.large does not support new regions. 
======
Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/23189
=> Make default m5.large

lib/global-admin/addon/components/new-multi-cluster-app/component.js
======
When upgrading a multi-cluster-application the template version was set
to the default version instead of the apps current version.
When a current version is present we now use it before using the
default.
======
New Feature
Linked Issues
======
rancher/rancher#23209
======
=> [Backport] Use current template version for app upgrades

lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
======
Update the version for rke command and windows clusters 
======
Linked Issues
======
rancher/rancher#23219
======
=> Change windows docker version for custom clusters

lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
======
Backport issue in master
======
Linked Issues
======
rancher/rancher#23219
======
=> [Backport] Change windows docker version for custom clusters

lib/istio/addon/components/istio-catalog/template.hbs, lib/shared/addon/components/form-members-catalog-access/component.js, lib/shared/addon/components/form-members-catalog-access/template.hbs, lib/shared/addon/components/input-identity/component.js, lib/shared/addon/components/input-identity/template.hbs, lib/shared/addon/components/principal-search/component.js, translations/en-us.yaml
=> [Forwardport] Restrict Istio member access to groups only

Dockerfile.dapper, ember-cli-build.js, yarn.lock
======
To further increase our initial, warm, and rebuild build times I've made a couple tweaks. 
The original change I made to the tests flag was looking at the wrong env variable. Looking at the correct variable fixes the issue we had where tests would fail in dev. Tests pass when running `yarn test` or `ember test` manually. This also reduces initial build time during dev because we don't need to run our tests at that point. When the app is compiled on drone it runs the tests with the env set to test so they should pass there as well. 
I've disabled build time for production builds to reduce that time as well. We should have caught any lint errors prior to this step.
I accidentally remove source maps (scss/js) on dev which is pretty handy, so i've reenabled that. …
=> Ember 3.12 build perf

lib/istio/addon/components/istio-catalog/component.js, lib/istio/addon/components/istio-catalog/template.hbs, lib/shared/addon/components/form-members-catalog-access/component.js, lib/shared/addon/components/form-members-catalog-access/template.hbs
======
======
Bugfix
Linked Issues
======
rancher/rancher#23247
======
=> Exclude local user from principal search

translations/en-us.yaml
======
======
Bugfix
Linked Issues
======
rancher/rancher#23219
======
N/A
=> Update windows support version

app/components/form-scoped-roles/component.js, app/models/mountentry.js, lib/global-admin/addon/accounts/edit/controller.js, lib/global-admin/addon/accounts/new/controller.js, lib/global-admin/addon/components/new-edit-role/component.js, lib/shared/addon/components/input-identity/component.js, lib/shared/addon/components/principal-search/component.js, lib/shared/addon/components/searchable-select/component.js, lib/shared/addon/mixins/upgrade-component.js
======
Fixes a few issues from the jquery deprication change and some intl errors found while working around the ui. 
======
Bugfix
Linked Issues
======
N/A
======
N/A
=> Random Bugs

.drone.yml, scripts/build-static
======
forgot to do this when we branched
======
Linked Issues
======
======
=> update drone and build script to point towards 2.3-fixes branch

lib/shared/addon/components/new-select/component.js, lib/shared/addon/components/percent-gauge/component.js
======
Found a couple more bugs around jQuery deprecation fixes. 
======
Bugfix
Linked Issues
======
N/A
======
N/A
=> Master jQuery Bugs

lib/global-admin/addon/security/authentication/template.hbs, vendor/ember-shortcuts.js
======
Fixes bugs in global admin engine with links reading off a prop
Fixes bugs with ember shortcuts
======
Bugfix
Linked Issues
======
N/A
======
N/A
=> Ember Upgrade Bugs

lib/shared/addon/utils/amazon.js
======
======
Enhancement
Linked Issues
======
rancher/rancher#22907
======
t3a instances were already added at 0694319e3daa66904ffd05c65a0c243ab46c555c
=> Add missing c5.* instance types to amazon utils

lib/shared/addon/components/catalog-index/component.js
======
catalog app is still showing when all of the templates are hidden by max_rancher_version
======
Linked Issues
======
https://github.com/rancher/rancher/issues/23295
======
=> [2.3.1] Hide catalog items if there is no templates

lib/shared/addon/mixins/lazy-icon.js
======
All catalog apps are showing the same icon.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/23291
======
=> Fix catalog app icon issue

README.md, scripts/build-static, scripts/ci
======
======
Linked Issues
======
======
=> update build steps for latest-2.3

lib/shared/addon/utils/amazon.js
======
======
Enhancement 
Linked Issues
======
rancher/rancher#23354
======
N/A
=> [Forwardport] Add missing c5.* instance types to amazon utils

lib/shared/addon/components/catalog-index/component.js
======
catalog app is still showing when all of the templates are hidden by max_rancher_version
======
Linked Issues
======
https://github.com/rancher/rancher/issues/23336
======
=> [forwardport] Hide catalog items if there is no templates

lib/shared/addon/components/scheduling-toleration/component.js, lib/shared/addon/components/scheduling-toleration/template.hbs
Forwardport https://github.com/rancher/ui/pull/3439
linked issue => https://github.com/rancher/rancher/issues/23353
=> [Forwardport] Display Atypical Tolerations Correctly

lib/global-admin/addon/cluster-templates/new-revision/route.js, lib/shared/addon/components/cluster-driver/driver-rke/component.js
======
Adds logic to properly parse a Kubernetes patch release selection vs a Kubernetes version override when creating/clone RKE templates. 
======
Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/23404
https://github.com/rancher/rancher/issues/23413
https://github.com/rancher/rancher/issues/23415
======
N/A
=> [2.3.1] RKE Template Bugs

lib/shared/addon/components/form-versions/component.js
======
When launching a cluster via a template where we selected the patch version k8s version but did not provide an override we never selected the correct current version of the cluster we are editing. 
======
Bugfix
Linked Issues
======
rancher/rancher#23413
======
=> Correct K8s Version Override

.drone.yml, scripts/build-static
======
======
Linked Issues
======
======
=> add new steps to drone to further automation efforts

.drone.yml
=> More Drone Changes

package.json
======
======
Linked Issues
======
======
=> bump package for drone automation test

.drone.yml
it is tested at this point in time no need to test again
======
======
Linked Issues
======
======
=> remove depends on test for building release

.drone.yml, package.json
======
======
Linked Issues
======
======
=> 2.3.automation

.drone.yml, package.json
======
======
Linked Issues
======
======
=> fix drone refs paths for automation

.drone.yml, package.json
======
======
Linked Issues
======
======
=> Drone Automation Fixes

lib/shared/addon/components/cluster-driver/driver-azureaks/component.js, lib/shared/addon/components/cluster-driver/driver-azureaks/template.hbs, translations/en-us.yaml
======
This adds the Network Plugin param as well as the PodCidr param.
======
Linked Issues
======
rancher/rancher#23518
======
=> Add network plugin and supporting param

app/styles/pages/_container.scss
======
Before :
After :
======
Bugfix in CSS
Linked Issues
======
N/A
======
N/A
=> Honor white spaces in container logs

lib/shared/addon/components/cluster-driver/driver-azureaks/component.js, lib/shared/addon/components/cluster-driver/driver-azureaks/template.hbs, translations/en-us.yaml
======
This adds the Network Plugin param as well as the PodCidr param.
======
Bugfix
Linked Issues
======
rancher/rancher#22616
======
=> [2.3.2] Add network plugin and supporting param

app/models/template.js, lib/global-admin/addon/multi-cluster-apps/catalog/index/controller.js, lib/shared/addon/utils/constants.js, translations/en-us.yaml
Forward porting rancher/rancher#23522
=> Catalog Translations Bug

lib/shared/addon/components/check-override-allowed/template.hbs, lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
Forwardport of rancher/rancher#23523
=> disp k8s ver correctly when editing cluster or clone rev

.drone.yml, config/environment.js, package.json, scripts/build-static, scripts/ci-release
======
======
Linked Issues
======
======
=> More automation tweaks

.drone.yml, .gitignore, config/environment.js, package.json, scripts/build-static, scripts/ci
======
Porting the changes from 2.3 branch to build tagged release builds by triggering a tag only.
======
New Feature
Linked Issues
======
N/A
======
N/A
=> Drone automation updates for 2.2 dev branch

app/models/destinationrule.js, app/models/gateway.js, app/models/virtualservice.js, lib/istio/addon/components/cru-gateway/component.js, lib/istio/addon/components/cru-virtual-service/component.js, lib/istio/addon/components/istio-gateway-select/component.js, lib/istio/addon/gateway/detail/edit/route.js, lib/istio/addon/gateway/detail/edit/template.hbs, lib/istio/addon/gateway/detail/index/template.hbs, lib/istio/addon/gateway/detail/route.js, lib/istio/addon/project-istio/gateways/index/route.js
======
Fix comments in https://github.com/rancher/ui/pull/3443
======
Linked Issues
======
======
=> [2.3.2] Fix comments for Istio Gateway

translations/en-us.yaml
======
Applying changes made in rancher/ui#3378
======
Enhancement 
Linked Issues
======
N/A
======
N/A
=> Update translation text for enabling Prometheus 

translations/en-us.yaml
======
Text change
======
Text change
Non-breaking change to delete text.
Linked Issues
======
https://github.com/rancher/rancher/issues/22600
https://github.com/rancher/rancher/issues/23510
https://github.com/rancher/rancher/issues/20329
======
=> Text changes

app/styles/components/_catalog-box.scss
======
Change color of text in partner banner for catalog apps
======
Bugfix - non-breaking
Linked Issues
======
https://github.com/rancher/rancher/issues/22859
======
=> Change color in apps for partner

app/styles/components/_forms.scss
======
Increased the alpha of placeholder text to make it easier to see.
======
Linked Issues
======
rancher/rancher#22917
======
=> Improve form placeholder text legibility

lib/global-admin/addon/accounts/edit/controller.js, lib/global-admin/addon/accounts/edit/template.hbs, lib/global-admin/addon/accounts/new/controller.js, lib/global-admin/addon/accounts/new/template.hbs, lib/global-admin/addon/components/form-global-roles-row/component.js, lib/global-admin/addon/components/form-global-roles-row/template.hbs, lib/global-admin/addon/components/form-global-roles/component.js, lib/global-admin/addon/components/form-global-roles/template.hbs, translations/en-us.yaml
======
When global roles were added the `user-base` role was hidden by default. Due to this the frontend had to make some assumptions about non-admin users to ensure they always had, at a minimum, `user-base` which only gives login access. This was the old `login access` read only role at the bottom of the custom section. This role was changed to be exposed by default but the frontend was still making the assumptions and always adding the role to non-admin users.
With this change it made sense to refactor the global permissions logic to not make any assumptions on behalf of the user. I've remove the concept of Admin, User, and Custom modes. The three major roles, Admin, User, User-Base are surfaced to the top of the section and user is still selected by default. Custom …
=> Global Permissions Bug

lib/global-admin/addon/accounts/edit/template.hbs
======
During refactor I grabbed the wrong variable while cleaning up some of the code. Caused a JS error and the page never finished loading. 
======
Linked Issues
======
rancher/rancher#21749
======
N/A
=> Edit User Error

app/models/feature.js, lib/global-admin/addon/components/feature-flags/component.js, lib/global-admin/addon/components/feature-flags/template.hbs, lib/global-admin/addon/routes.js, lib/global-admin/addon/settings/advanced/template.hbs, lib/global-admin/addon/settings/features/route.js, lib/global-admin/addon/settings/features/template.hbs, lib/global-admin/addon/settings/template.hbs, tests/index.html, tests/test-helper.js, translations/en-us.yaml, yarn.lock
======
Adds UI for Feature Flags api.
======
New Feature
Linked Issues
======
rancher/rancher#23520
======
Removed the failing test for now as I am still stuck on getting engine tests to work.
=> Feature Flags UI

package.json
======
Bumping the version of ember-api-store to 2.9.4
======
Linked Issues
======
rancher/rancher#23576
=> Bumping the version of ember-api-store to 2.9.4

app/styles/components/_forms.scss
======
Increased the alpha of placeholder text to make it easier to see.
======
Linked Issues
======
rancher/rancher#23577
======
=> [forwardport] Improve form placeholder text legibility

.ember-cli, app/styles/_rancher.scss, app/styles/components/_forms.scss, app/styles/components/_new-select.scss, app/styles/components/_searchable-select.scss, lib/nodes/addon/components/driver-vmwarevsphere/component.js, lib/nodes/addon/components/driver-vmwarevsphere/template.hbs, lib/shared/addon/components/form-contextual-select-array/component.js, lib/shared/addon/components/form-contextual-select-array/template.hbs, lib/shared/addon/components/form-key-value/component.js, lib/shared/addon/components/form-key-value/template.hbs, lib/shared/addon/components/form-value-array/component.js, lib/shared/addon/components/form-value-array/template.hbs, lib/shared/addon/components/new-select/component.js, lib/shared/addon/components/new-select/template.hbs, lib/shared/addon/components/searchable-select/component.js, lib/shared/addon/components/searchable-select/template.hbs, lib/shared/addon/utils/stateful-promise.js, lib/shared/app/components/form-array/component.js, lib/shared/app/components/form-contextual-select-array/component.js, translations/en-us.yaml
======
-We now prepopulate fields as select component instead of just
free-form text fields.
-We added support for cloning from different sources.
-We also added support for custom attributes and tags.
To implement the above features we also added support for promise
based content for new-select and search-select and created a new
component contextual-select-array which provides a method for
filtering content based on previous selections.
======
Linked Issues
======
rancher/rancher#23583
Screenshots
======
Full page:
Spinner on loading search-select:
=> [forwardport] Improve vsphere driver UX

app/styles/layout/_footer.scss, app/styles/layout/_small.scss, lib/shared/addon/components/cru-node-pools/template.hbs, translations/en-us.yaml
help text on node pools edit
https://github.com/rancher/rancher/issues/22782
a few items 
https://github.com/rancher/rancher/issues/22010
=> node pools help text

lib/global-admin/addon/components/form-fsgroup-policy/component.js, yarn.lock
======
`form-fsgroup-policy` was incorrectly importing the observer method.
The last package bump also didn't update the yarn lock file. 
======
Bugfix
Linked Issues
======
======
=> Fix Incorrect Observer Import

.drone.yml
======
Add step to upload tar.
Narrow down tag watching to ensure we are only getting v2.3.x tags.
======
Linked Issues
======
======
=> Add upload tar step to drone release

lib/istio/addon/components/istio-nav/component.js, lib/istio/addon/components/istio-nav/template.hbs
======
Instead of removing the feature flag in backend directly, we would like to change it to true by default. So we need to add the UI logic back
======
Linked Issues
======
https://github.com/rancher/rancher/issues/23582
======
=> [2.3.2] Add istio feature flag back

lib/global-admin/addon/accounts/edit/controller.js, lib/global-admin/addon/accounts/edit/template.hbs, lib/global-admin/addon/accounts/new/controller.js, lib/global-admin/addon/accounts/new/template.hbs, lib/global-admin/addon/components/form-global-roles-row/component.js, lib/global-admin/addon/components/form-global-roles-row/template.hbs, lib/global-admin/addon/components/form-global-roles/component.js, lib/global-admin/addon/components/form-global-roles/template.hbs, translations/en-us.yaml
Forwardport of rancher/ui#3493
rancher/rancher#23644
=> [Forwardport] Global Permission Bug

lib/shared/addon/components/form-versions/component.js
======
Since k8s 16 is GA but still experiencing a bit of instability we're making 1.15 the default but removing the experimental tag from 1.16.
======
Bugfix
Linked Issues
======
rancher/rancher#23690
======
=> add satisfies check for experimental label for 1.16

lib/shared/addon/components/new-select/component.js
======
Select was grabbing the wrong element to get the selected index which caused some undefined errors to crop up. 
======
Bugfix
Linked Issues
======
rancher/rancher#23682
======
=> jQuery Issue

.ember-cli, app/styles/_rancher.scss, app/styles/components/_forms.scss, app/styles/components/_new-select.scss, app/styles/components/_searchable-select.scss, lib/nodes/addon/components/driver-vmwarevsphere/component.js, lib/nodes/addon/components/driver-vmwarevsphere/template.hbs, lib/shared/addon/components/form-contextual-select-array/component.js, lib/shared/addon/components/form-contextual-select-array/template.hbs, lib/shared/addon/components/form-key-value/component.js, lib/shared/addon/components/form-key-value/template.hbs, lib/shared/addon/components/form-value-array/component.js, lib/shared/addon/components/form-value-array/template.hbs, lib/shared/addon/components/new-select/component.js, lib/shared/addon/components/new-select/template.hbs, lib/shared/addon/components/searchable-select/component.js, lib/shared/addon/components/searchable-select/template.hbs, lib/shared/addon/utils/stateful-promise.js, lib/shared/app/components/form-array/component.js, lib/shared/app/components/form-contextual-select-array/component.js, translations/en-us.yaml
======
-We now prepopulate fields as select component instead of just
free-form text fields.
-We added support for cloning from different sources.
-We also added support for custom attributes and tags.
To implement the above features we also added support for promise
based content for new-select and search-select and created a new
component contextual-select-array which provides a method for
filtering content based on previous selections.
======
Linked Issues
======
rancher/rancher#21580
rancher/rancher#23031
rancher/rancher#23002
rancher/rancher#19032
Screenshots
======
Full page:
Spinner on loading search-select:
=> Improve vsphere driver UX

translations/en-us.yaml, translations/ja-jp.yaml, translations/zh-hant.yaml
======
Fix typo "Ctitical" on the logging configuration page.
======
Fix typo "Ctitical" on the logging configuration page.
Linked Issues
======
Closes: rancher/rancher#23673
=> Fix typo "Ctitical"

app/models/feature.js, lib/global-admin/addon/components/feature-flags/component.js, lib/global-admin/addon/components/feature-flags/template.hbs, lib/global-admin/addon/routes.js, lib/global-admin/addon/settings/advanced/template.hbs, lib/global-admin/addon/settings/features/route.js, lib/global-admin/addon/settings/features/template.hbs, lib/global-admin/addon/settings/template.hbs, tests/index.html, tests/test-helper.js, translations/en-us.yaml, yarn.lock
======
Backport of rancher/ui#3432
======
New Feature
Linked Issues
======
rancher/rancher#23184
======
N/A
=> [2.3.3] Feature Flags UI

app/components/modal-edit-setting/component.js, app/models/cloudcredential.js, app/models/project.js, lib/global-admin/addon/components/cru-cloud-credential/template.hbs, lib/global-admin/addon/components/registry-catalog/component.js, lib/global-admin/addon/security/cloud-credentials/index/controller.js, lib/global-admin/addon/security/cloud-credentials/index/template.hbs, lib/istio/addon/components/modal-delete-istio/component.js, lib/shared/addon/azure-ad/service.js, lib/shared/addon/components/form-members/component.js, lib/shared/addon/components/form-members/template.hbs, lib/shared/addon/components/project-member-row/component.js, lib/shared/addon/components/project-member-row/template.hbs, lib/shared/addon/mixins/crud-catalog.js, lib/shared/addon/oauth/service.js, lib/shared/addon/saml/service.js, translations/en-us.yaml
======
This PR is backporting a few issues that were marked to test but weren't actually backported to the 2.3 branch. These issues have been verified on master. 
======
Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/21440
https://github.com/rancher/rancher/issues/23059
https://github.com/rancher/rancher/issues/23064
======
N/A
=> Backport Missing Fixes

lib/monitoring/addon/components/nodes-live/component.js, lib/shared/addon/utils/used-percent-gauge.js
======
The usage percent should be `used / total * 100`.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/23786
======
=> [2.3.3] Incorrect node memory usage gauge when cluster monitoring is enabled

app/components/cru-dns/template.hbs, lib/shared/addon/components/form-value-array/component.js, lib/shared/addon/components/form-value-array/template.hbs
======
We updated form-value-array in the process of making another similar component but the update didn't work for all scenarios. Since we ended up making a new component it made sense to revert this file to its previous working version. 
I also fixed a weird alignment issue on the page where the component is consumed. 
======
Bugfix
Linked Issues
======
rancher/rancher#23772
======
=> revert change to form-value-array

app/components/cru-dns/template.hbs, lib/shared/addon/components/form-value-array/component.js, lib/shared/addon/components/form-value-array/template.hbs
======
We updated form-value-array in the process of making another similar component but the update didn't work for all scenarios. Since we ended up making a new component it made sense to revert this file to its previous working version. 
I also fixed a weird alignment issue on the page where the component is consumed. 
======
Bugfix
Linked Issues
======
rancher/rancher#23791
======
=> [forwardport] revert change to form-value-array

app/models/roletemplate.js
https://github.com/rancher/rancher/issues/23823
======
Cannot delete cluster role. API returns `roleTemplateIds : null` in some case.
So `const { roleTemplateIds = [] } = { roleTemplateIds : null }; ` will be `null` instead of `[]`
======
Linked Issues
======
https://github.com/rancher/rancher/issues/23823
======
=> Cannot delete cluster role

app/models/roletemplate.js
======
Cannot delete cluster role. API returns roleTemplateIds : null in some case.
So const { roleTemplateIds = [] } = { roleTemplateIds : null }; will be null instead of []
======
Linked Issues
======
https://github.com/rancher/rancher/issues/23825
======
=> [Forwardport] Fix the issue that cannot delete role sometimes

config/environment.js
======
I was always stripping off the first character because `dev` always has a v in it ;) 
======
Dev Bug
Linked Issues
======
N/A
======
N/A
=> fix error in package version displayed in UI

app/components/new-catalog/template.hbs, lib/global-admin/addon/components/new-multi-cluster-app/template.hbs, translations/en-us.yaml
======
App and Multi-cluster App schemas now expose `timeout` and `wait` params. This pr exposes the new fields in the UI.
======
New Feature
Linked Issues
======
rancher/rancher#22373
======
=> Expose wait and timeout on mc and regular apps

app/components/workload-row/component.js, app/components/workload-row/template.hbs
======
Use a computed property for the pod count of a workload row so they value is recomputed when new pods are added.  
======
Bugfix
Linked Issues
======
rancher/rancher#23866
======
N/A
=> [Forwardport] Fix pod count on workload list page

app/components/workload-row/component.js, app/components/workload-row/template.hbs
======
Use a computed property for the pod count of a workload row so they value is recomputed when new pods are added.
======
Bugfix
Linked Issues
======
rancher/rancher#23842
======
N/A
=> Fix pod count on workload list page

app/components/node-row/template.hbs, app/models/node.js, lib/monitoring/addon/components/node-dashboard/template.hbs
======
Checks the os info to see if its docker or container d and display the
appropriate label in each case.
======
Bugfix
Linked Issues
======
rancher/rancher#21099
======
N/A
=> Dynamically change version label on node dashboard for dock/contd

translations/en-us.yaml
======
Linked Issues
======
rancher/rancher#23737
=> Update a translation string

translations/en-us.yaml
======
Linked Issues
======
rancher/rancher#23892
=> [forwardport] Update a translation string

package.json, translations/en-us.yaml
======
Fix translation typo. Update master package version number to reduce confusion from other devs. Since we automated builds to trigger from tags it doesn't make sense to keep the tag version in the package as its confusing to QA and Devs looking for a version on latest. 
======
Bugfix
Linked Issues
======
rancher/rancher#23924
======
=> [2.4] Translations Typo

app/styles/components/_forms.scss, lib/shared/addon/components/form-project-targets/component.js, lib/shared/addon/components/searchable-select/component.js, lib/shared/addon/components/searchable-select/template.hbs, translations/en-us.yaml
======
Fixes a typo in the templates dropdown.
Fixes a bug where grouped content was showing the missing translation wrapper around a group name. 
Fixes weird FF select>opt styling issue. 
======
Bugfix
Linked Issues
======
rancher/rancher#23925
rancher/rancher#23922
======
N/A
=> [2.3.3] Translations Typos

app/styles/components/_forms.scss, lib/shared/addon/components/form-project-targets/component.js, lib/shared/addon/components/searchable-select/component.js, lib/shared/addon/components/searchable-select/template.hbs
======
Fixes a typo in the templates dropdown.
Fixes a bug where grouped content was showing the missing translation wrapper around a group name. 
Fixes weird FF select>opt styling issue. 
======
Bugfix
Linked Issues
======
rancher/rancher#23946
======
N/A
=> Translation Typos

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js
======
The observers that initialize the data for the VPC and Subnet selections were not initializing correctly when we edit. 
======
Bugfix
Linked Issues
======
rancher/rancher#23879
======
=> Select Correct EKS VPS & Subnet on Edit

app/application/route.js, app/ie/template.hbs
======
We don't support the EdgeHTML browsers just like we don't support
Internet Explorer. I added EdgeHTML to the blacklist so that we will
display the unsupported page.
======
Linked Issues
======
rancher/rancher#23909
=> Include EdgeHTML based browers to blacklist

app/application/route.js, app/ie/template.hbs
======
We don't support the EdgeHTML browsers just like we don't support
Internet Explorer. I added EdgeHTML to the blacklist so that we will
display the unsupported page.
======
Linked Issues
======
rancher/rancher#23971
=> [forwardport] Include EdgeHTML based browers to blacklist

lib/shared/addon/components/cluster-driver/driver-googlegke/component.js, lib/shared/addon/components/cluster-driver/driver-googlegke/template.hbs, translations/en-us.yaml
======
This PR refactors the network/subnetwork/ip address allocation inputs for GKE. It resolves a bug where you could not deselect a subnetwork when using the `Create Subnetwork` option. There were two problems with this. You can only create a subnet when you don't have one selected. That lead to discovering most of the option configuration for this section was somewhat borked. 
I moved the advanced options for network out of advanced because they are directly affected by what network and subnet the user selects. I removed the `Create Subnetwork` section completely. If you're using a network without any available subnets you have you must auto create a subnet anyway so it made sense to display this as an option of the subnet dropdown and remove the radio buttons. If you …
=> Refactor the logic backing GKE network/subnetwork selections

lib/shared/addon/components/check-override-allowed/template.hbs, lib/shared/addon/components/form-network-config/template.hbs
======
Fix network plugin being editable on rke clusters. 
======
Bugfix
Linked Issues
======
rancher/rancher#23950
======
=> RKE Cluster - network plugin not editable

app/styles/components/_forms.scss
======
Make the select arrow visible on :hover
======
Linked Issues
======
rancher/rancher#23987
=> Make the select arrow visible on :hover

app/styles/components/_forms.scss
======
Make the select arrow visible on :hover
======
Linked Issues
======
rancher/rancher#24001
=> [forwardport] Make the select arrow visible on :hover

app/components/container-logs/component.js
======
while reviewing rancher/ui#3560 i stumbled on a case where opening the pod logs
would cause an undefined error to crash the local ui server. `exec` is called
correctly from the `watchReconnect` observer which needs to happen first as it
parses the container name. If we call exec before we have a container name we
get an undefined error
======
bugfix
Linked Issues
======
======
=> Pod Logs Race Condition

lib/shared/addon/components/cru-cloud-provider/template.hbs
======
Changing a cloud provider after the fact causes much chaos and failure. This PR makes the field uneditable. 
======
Bugfix
Linked Issues
======
rancher/rancher#22852
======
N/A
=> make cloud provider uneditable

lib/shared/addon/components/cru-cloud-provider/template.hbs
======
Changing a cloud provider after the fact causes much chaos and failure. This PR makes the field uneditable. 
======
Bugfix
Linked Issues
======
rancher/rancher#24008
======
N/A
=> [Forwardport] make cloud provider uneditable

lib/nodes/addon/components/driver-vmwarevsphere/component.js, lib/nodes/addon/components/driver-vmwarevsphere/template.hbs, translations/en-us.yaml
======
Add datastore cluster as an option for vsphere
======
Linked Issues
======
rancher/rancher#24002
backend changes: rancher/rancher#19706
=> Add datastore cluster as an option for vsphere

lib/nodes/addon/components/driver-vmwarevsphere/component.js, lib/nodes/addon/components/driver-vmwarevsphere/template.hbs, translations/en-us.yaml
======
Add datastore cluster as an option for vsphere
======
Linked Issues
======
rancher/rancher#24027
backend changes: rancher/rancher#19706
=> [backport] Add datastore cluster as an option for vsphere

package.json, yarn.lock
======
Temporarily reverting a change that borked live updating of resources that were not already loaded into the store. 
======
Bugfix
Linked Issues
======
rancher/rancher#23973
rancher/rancher#23842
======
A new change will be made with the fix rolled back in and the nesscary changes made to the UI repro to deal with these.
=> Revert cache change that caused a regression on live updating

lib/shared/addon/mixins/subscribe.js, package.json, yarn.lock
======
Ensures that the type check is the next thing processed before returning control back to the system so our node counts do not become out of sync. 
======
Linked Issues
======
rancher/rancher#23973
rancher/rancher#23842
======
=> Fix node/pod counts that were not updating correctly

lib/shared/addon/mixins/subscribe.js, package.json, yarn.lock
======
Ensures that the type check is the next thing processed before returning control back to the system so our node counts do not become out of sync. 
======
Linked Issues
======
rancher/rancher#23866
rancher/rancher#24034
======
=> [Forwardport] Fix node/pod counts that were not updating correctly

app/styles/components/_forms.scss
======
Make the arrow visible for select components when the component is
focused.
======
Linked Issues
======
rancher/rancher#24001
=> [forwardport]Show arrow on select:focus

app/styles/components/_forms.scss
======
Make the arrow visible for select components when the component is
focused.
======
Linked Issues
======
rancher/rancher#23987
=> Show arrow on select:focus

lib/global-admin/addon/multi-cluster-apps/catalog/launch/route.js
======
When upgrading a mc app we were always using the main mc app resource so any changes not saved would persist on the mc app when canceling or leaving the page without a refresh. By using a clone but not one cloned for new, we are able to ensure the user has the correct object when visiting the upgrade page. 
======
Linked Issues
======
rancher/rancher#22733
======
N/A
=> when upgrading mc app ensure we are using a fresh copy of mc app

lib/global-admin/addon/multi-cluster-apps/catalog/launch/route.js
======
When upgrading a mc app we were always using the main mc app resource so any changes not saved would persist on the mc app when canceling or leaving the page without a refresh. By using a clone but not one cloned for new, we are able to ensure the user has the correct object when visiting the upgrade page. 
======
Linked Issues
======
rancher/rancher#24057
======
N/A
=> [forwardport] when upgrading mc app ensure we are using a fresh copy of mc app

app/components/new-catalog/component.js, lib/shared/addon/mixins/catalog-app.js
======
I forgot to update the non-mc app catalog validator to pass the answers. 
======
Bugfix
Linked Issues
======
rancher/rancher#24080
======
N/A
=> pass answers to validation method for catalog apps

app/components/new-catalog/component.js, lib/shared/addon/mixins/catalog-app.js
======
I forgot to update the non-mc app catalog validator to pass the answers. 
======
Bugfix
Linked Issues
======
rancher/rancher#24084
======
N/A
=> [forwardport] pass answers to validation method for catalog apps

lib/global-admin/addon/accounts/edit/controller.js, lib/global-admin/addon/accounts/new/controller.js
======
======
Linked Issues
https://github.com/rancher/rancher/issues/24064
======
======
=> fix ui error message never pop up

translations/zh-hans.yaml
======
Fix zh-hans issue
======
Linked Issues
======
======
=> [Forwardport] Fix zh-hans issue

translations/zh-hans.yaml
======
======
Linked Issues
======
======
=> [2.3] Update zh-hans

app/models/globalrole.js, app/styles/components/_searchable-select.scss, lib/global-admin/addon/components/new-edit-role/component.js, lib/global-admin/addon/components/new-edit-role/template.hbs, lib/global-admin/addon/components/role-rule-row/component.js, lib/global-admin/addon/components/role-rule-row/template.hbs, lib/global-admin/addon/security/roles/detail/template.hbs, lib/global-admin/addon/security/roles/edit/template.hbs, lib/global-admin/addon/security/roles/index/controller.js, lib/global-admin/addon/security/roles/index/route.js, lib/global-admin/addon/security/roles/index/template.hbs, lib/global-admin/addon/security/roles/new/controller.js, lib/global-admin/addon/security/roles/new/route.js, lib/global-admin/addon/security/roles/new/template.hbs
======
This PR exposes the functionality to crud global roles with the caveat that they can only edit/delete non-built-in roles. 
======
New Feature
Linked Issues
======
rancher/rancher#23453
======
N/A
=> Global Roles

translations/zh-hans.yaml, translations/zh-hant.yaml
======
Fix zh-hans issue
======
Linked Issues
======
======
=> Fix zh-hans issue

translations/zh-hans.yaml, translations/zh-hant.yaml
======
Fix zh-hans issue
======
Linked Issues
======
======
=> [2.3] Fix zh-hans issue

translations/en-us.yaml
======
To reduce confusion we should use the PV volume type names as they are in the kubernetes documentation. 
======
Enhancement
Linked Issues
======
rancher/rancher#24081
======
=> Rename some persistent volume names to match k8s names

lib/shared/addon/components/cluster-driver/driver-azureaks/component.js
======
======
Linked Issues
======
rancher/rancher#24199
======
=> update default k8s version for AKS cluster

lib/shared/addon/components/cluster-driver/driver-azureaks/component.js
======
======
Linked Issues
======
rancher/rancher#24239
======
=> update aks default k8s version

lib/istio/addon/project-istio/gateways/index/route.js
======
Fix Isitio route issue
======
Linked Issues
======
https://github.com/rancher/rancher/issues/23370
======
=> Fix Isitio route issue

lib/global-admin/addon/components/account-group-row/template.hbs, lib/global-admin/addon/security/authentication/localauth/template.hbs
======
======
Linked Issues
======
======
=> Group Role Fixes

app/authenticated/cluster/cis/scan/controller.js, app/authenticated/cluster/cis/scan/detail/controller.js, app/authenticated/cluster/cis/scan/detail/route.js, app/authenticated/cluster/cis/scan/detail/template.hbs, app/authenticated/cluster/cis/scan/route.js, app/authenticated/cluster/cis/scan/template.hbs, app/components/cluster/cis/scan/detail/nodes-table/component.js, app/components/cluster/cis/scan/detail/nodes-table/table-row/component.js, app/components/cluster/cis/scan/detail/nodes-table/table-row/template.hbs, app/components/cluster/cis/scan/detail/nodes-table/template.hbs, app/components/cluster/cis/scan/detail/table-row/component.js, app/components/cluster/cis/scan/detail/table-row/template.hbs, app/components/cluster/cis/scan/table-row/component.js, app/components/cluster/cis/scan/table-row/template.hbs, app/instance-initializers/nav.js, app/models/clusterscan.js, app/router.js, app/styles/base/_helpers.scss, app/styles/components/_tables.scss, lib/shared/addon/components/confirm-delete/component.js, package.json, translations/en-us.yaml, yarn.lock
======
This adds and implements the /c/<clusterid>/cis/scan
and /c/<clusterid>/cis/scan/detail/<scanid> routes.
======
Linked Issues
======
rancher/rancher#20425
======
List View:
Detail View:
Report View:
=> Implement the list and detail views for CIS scan

app/models/globalrole.js, lib/global-admin/addon/components/form-global-roles/component.js, lib/global-admin/addon/components/form-global-roles/template.hbs, lib/global-admin/addon/security/accounts/edit/controller.js, lib/global-admin/addon/security/accounts/new/controller.js, lib/global-admin/addon/security/roles/index/controller.js, lib/global-admin/addon/security/roles/index/template.hbs, lib/shared/addon/components/confirm-delete/component.js, lib/shared/addon/components/confirm-delete/template.hbs, translations/en-us.yaml
======
Adds a warning to the groups page when a default user role does not exist.
Adds user count to custom global role delete modal that shows the count of users with this role. 
Refactor role permissions validator to check rules on the roles a user has for login access. 
Fixes a few broken links and various minor bugs found while fixing other bugs.
======
Bugfix
Linked Issues
======
rancher/rancher#24301
rancher/rancher#24341
rancher/rancher#24362
======
N/A
=> Global Role Bugs

lib/global-admin/addon/components/form-global-roles/component.js
======
======
Linked Issues
======
======
=> populate default roles for custom roles

lib/shared/addon/components/confirm-delete/template.hbs, translations/en-us.yaml
======
======
Bugfix
Linked Issues
======
rancher/rancher#24375
======
=> Add pluralization to user count on delete custom global role modal

lib/global-admin/addon/components/form-global-roles/component.js
======
When validating whether a user can login with the roles they have we gather all the rules on a role. This pr adds the check for empty rules and skips if so. 
======
Bugfix
Linked Issues
======
rancher/rancher#24438
======
=> check for empty rules before pusing into rules array

app/authenticated/cluster/cis/scan/detail/controller.js, app/authenticated/cluster/cis/scan/detail/template.hbs, app/models/clusterscan.js, translations/en-us.yaml
======
-Fix CIS detail table id sorting
-Change CIS Detail download and delete button color
-Add failed to parse security-scan-cfg growl
======
Linked Issues
======
rancher/rancher#24417
======
**JSON Parse error growl**
**New button color**
**Better 'Number' sorting**
=> CIS Scan issues

app/components/container/new-edit/template.hbs, app/workload/template.hbs, lib/monitoring/addon/project-setting/controller.js, lib/monitoring/addon/project-setting/template.hbs, lib/monitoring/translations/en-us.yaml
======
Do not allow users to enable Project Monitoring In System Project. Change was made in https://github.com/rancher/ui/commit/a224ed6a361a61dc6c5e1a0b67d1ee30dc9cbbdb
We would like to backport it to 2.2
======
Linked Issues
======
https://github.com/rancher/rancher/issues/23445
======
=> [2.2] [Backport]  System project monitoring

.drone.yml, config/environment.js, yarn.lock
======
Adds tag watched release steps to this branch. Also updates lock file.
======
Linked Issues
======
======
=> Drone release tag fixes

translations/en-us.yaml
======
======
Linked Issues
======
rancher/rancher#24454
======
=> fix typo in group memberships 

app/authenticated/cluster/cis/scan/detail/controller.js, translations/en-us.yaml
======
If the security-config map wasn't present the detail view wouldn't work
properly. To resolve this we now create a new config map if it's not
present.
======
Linked Issues
======
rancher/rancher#24432
=> Create default config map if it's not present.

translations/ar-sa.yaml, translations/de-de.yaml, translations/en-us.yaml, translations/es-es.yaml, translations/fa-ir.yaml, translations/fr-fr.yaml, translations/hu-hu.yaml, translations/it-it.yaml, translations/ja-jp.yaml, translations/ko-kr.yaml, translations/nb-no.yaml, translations/nl-nl.yaml, translations/pt-br.yaml, translations/ru-ru.yaml, translations/sh-hr.yaml, translations/sv-se.yaml, translations/tr-tr.yaml, translations/uk-ua.yaml, translations/vi-vn.yaml, translations/zh-hans.yaml, translations/zh-hant.yaml
======
This syncs that translations files from Crowdin and fixes a small bug with the key path for a nav item in uk-ua.
======
Bugfix
Linked Issues
======
rancher/rancher#24300
======
=> Sync translations

lib/global-admin/addon/components/form-global-roles/component.js
======
This occurs when a non-admin or user that doesn't have access to global roles
lands on the page.
======
Bugfix
Linked Issues
======
rancher/rancher#24458
======
=> remove null/undefined entries from baseRoles array

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js, lib/shared/addon/components/cluster-driver/driver-amazoneks/template.hbs
======
`vpcSubnetModeDidChange` was updated to be an observer but would this would cause field to be reset on edit when the steps changed.  Additionally the VPC and Subnet modes weren't being intialized correctly on edit so the fields were never set to the right state regardless of what VPC or Subnet data existed on the cluster. 
======
Linked Issues
======
rancher/rancher#23879
rancher/rancher#24481
======
=> EKS VPC/Subnet Bugs

app/models/app.js
======
Filter out removed pods in app status bar
======
Linked Issues
======
https://github.com/rancher/rancher/issues/24500
======
=> Fix app progress bar issue

lib/logging/addon/components/logging/form-log-format/template.hbs, translations/en-us.yaml
======
Exposes the `enableJSONParsing` on cluster and project logging configs.
Backend PR: https://github.com/rancher/rancher/pull/24361
======
New Feature
Linked Issues
======
rancher/rancher#24367
======
This [commit](https://github.com/rancher/ui/commit/1e040aa32096a8f83cc1085e25d0b19d19308e74) exposes the new param.
This [commit](https://github.com/rancher/ui/commit/80ebfb3a04b571a86eca7a2342ff65c6828557c1) is the clean up and formatting.
=> Expose JSON Parsing in Logging Config

lib/logging/addon/components/logging/form-log-format/template.hbs, translations/en-us.yaml
======
Exposes the `enableJSONParsing` on cluster and project logging configs.
Backend PR: ???
======
New Feature
Linked Issues
======
rancher/rancher#24367
======
=> [2.3.x] Expose JSON Parsing in Logging Config

package.json, yarn.lock
======
======
Linked Issues
======
======
=> Update dependencies for missing file in intl

app/components/cru-registry/component.js
======
Cloned registry items were never taken into account on validation and save. 
======
Bugfix
Linked Issues
======
rancher/rancher#24231
======
=> Refactor validation on cloned registry items

app/components/cru-registry/component.js
======
Cloned registry items were never taken into account on validation and save. 
======
Bugfix
Linked Issues
======
rancher/rancher#24231
======
=> [2.3.x] Refactor validation on cloned registry items

app/components/form-scoped-roles/component.js, app/models/mountentry.js, lib/global-admin/addon/accounts/edit/controller.js, lib/global-admin/addon/accounts/new/controller.js, lib/global-admin/addon/components/new-edit-role/component.js, lib/shared/addon/components/input-identity/component.js, lib/shared/addon/mixins/upgrade-component.js
======
Remove deprecated API call when Ember Intl was upgraded. 
======
Bugfix
Linked Issues
======
rancher/rancher#24437
======
=> [2.3] Translations Fixes

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js
======
Update EKS regions
======
update
Linked Issues
======
https://github.com/rancher/rancher/issues/24484
======
Depends on https://github.com/rancher/kontainer-engine/pull/206
=> [2.3-fixes] Add Sao Paulo/Canada Central to EKS regions

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js
======
Update EKS regions
======
update
Linked Issues
======
https://github.com/rancher/rancher/issues/24484
======
Depends on https://github.com/rancher/kontainer-engine/pull/205
=> Add Sao Paulo/Canada Central to EKS regions

app/authenticated/cluster/cis/scan/controller.js, app/authenticated/cluster/cis/scan/detail/controller.js, app/authenticated/cluster/cis/scan/detail/route.js, lib/shared/addon/mixins/cattle-transitioning-resource.js, lib/shared/addon/security-scan-config/service.js
- Adding support for the nodes field in the CIS report
- Fix running cis scan and change the color of running state
- Adding support to CIS for versioned skipping
======
Linked Issues
======
rancher/rancher#24431
rancher/rancher#24440
=> Resolving several CIS issues

lib/shared/addon/components/storage-class/provisioner-aws-ebs/component.js, lib/shared/addon/components/storage-class/provisioner-aws-ebs/template.hbs, translations/en-us.yaml
======
Support fsType field to Storage Class Amazon EBS Disk
======
Linked Issues
======
https://github.com/rancher/rancher/issues/19933
======
=> Add fsType to Storage Class Amazon EBS Disk

app/authenticated/cluster/route.js, app/authenticated/cluster/storage/classes/index/template.hbs, app/authenticated/cluster/storage/persistent-volumes/index/template.hbs, app/components/modal-import/template.hbs
======
Import yaml in storage classes and Persistent Volumes page
======
Linked Issues
======
https://github.com/rancher/rancher/issues/24611
======
=> Import yaml in storage classes and Persistent Volumes page

app/authenticated/cluster/storage/classes/new/route.js, app/components/cru-storage-class/component.js, app/components/cru-storage-class/template.hbs, app/models/storageclass.js, lib/shared/addon/components/storage-class/provisioner-local-storage/component.js, lib/shared/addon/components/storage-class/provisioner-local-storage/template.hbs, lib/shared/app/components/storage-class/provisioner-local-storage/component.js, translations/en-us.yaml
======
Support creating storage class for local persistent volumes
======
Linked Issues
======
https://github.com/rancher/rancher/issues/24082
======
=> Support creating storage class for local persistent volumes

app/components/container/form-sources/template.hbs, app/components/container/form-volumes/template.hbs, app/components/volume-source/source-config-map/template.hbs
======
Make navigating to config maps mapped as volume or environment more convenient
======
Linked Issues
======
https://github.com/rancher/rancher/issues/24188
======
=> Navigating to config maps mapped

lib/logging/addon/components/logging/form-log-format/template.hbs, lib/logging/addon/components/logging/target-elasticsearch/template.hbs, lib/logging/addon/components/logging/target-flentd/template.hbs, lib/logging/addon/components/logging/target-kafka/template.hbs, lib/logging/addon/components/logging/target-splunk/template.hbs, lib/logging/addon/components/logging/target-syslog/template.hbs
======
`enabledJSONParsing` was attached to the wrong model. This PR passes the logging config down to the correct component so the flag is set at the correct level. 
======
Bugfix
Linked Issues
======
rancher/rancher#24367
======
N/A
=> Logging Parse JSON Bug

lib/logging/addon/components/logging/form-log-format/template.hbs, lib/logging/addon/components/logging/target-elasticsearch/template.hbs, lib/logging/addon/components/logging/target-flentd/template.hbs, lib/logging/addon/components/logging/target-kafka/template.hbs, lib/logging/addon/components/logging/target-splunk/template.hbs, lib/logging/addon/components/logging/target-syslog/template.hbs
======
`enabledJSONParsing` was attached to the wrong model. This PR passes the logging config down to the correct component so the flag is set at the correct level. 
======
Bugfix
Linked Issues
======
rancher/rancher#24367
======
N/A
=> [2.3] Logging Parse JSON Bug

lib/shared/addon/components/modal-add-custom-roles/component.js, translations/en-us.yaml
=> Memeber[s]

lib/shared/addon/components/form-network-config/component.js, lib/shared/addon/components/form-network-config/template.hbs, translations/en-us.yaml
======
Expose MTU on CNI network provider for RKE based clusters.
======
New Feature
Linked Issues
======
rancher/rancher#24460
======
Additionally fixed some weird layout choices.
=> Expose MTU Param 

lib/shared/addon/components/form-network-config/component.js, lib/shared/addon/components/form-network-config/template.hbs, translations/en-us.yaml
======
Expose MTU on CNI network provider for RKE based clusters.
======
New Feature
Linked Issues
======
rancher/rancher#24460
======
Additionally fixed some weird layout choices.
=> [2.3.4] Expose MTU Param

app/models/podsecuritypolicytemplate.js, lib/global-admin/addon/components/new-edit-policy/template.hbs
======
Labels and annotation aren't read-only in pod security policy detail page
======
Linked Issues
======
https://github.com/rancher/rancher/issues/24621
======
=> Fix psp labels issues

lib/shared/addon/components/form-versions/component.js
======
Most of the hosted providers do not allow a Kubernetes version downgrade, and the single one that does only allows 1 patch version. We will prevent K8s version downgrade on edit as a result. 
======
Bugfix
Linked Issues
======
rancher/rancher#24071
======
N/A
=> [2.3.4] Prevent Kubernetes Version Downgrade on Edit

lib/shared/addon/components/form-versions/component.js
======
Most of the hosted providers do not allow a Kubernetes version downgrade, and the single one that does only allows 1 patch version. We will prevent K8s version downgrade on edit as a result. 
======
Bugfix
Linked Issues
======
rancher/rancher#24071
======
N/A
=> Prevent Kubernetes Version Downgrade on Edit

Dockerfile.dapper
======
======
Linked Issues
======
======
=> Remove unneeded npm install yarn since its installed by apt

Dockerfile.dapper
======
======
Linked Issues
======
======
=> [2.3] Remove unneeded npm install yarn since its installed by apt

lib/shared/addon/components/cluster-driver/driver-amazoneks/template.hbs, translations/en-us.yaml
======
We've added a new parameter, `ebsEncryption`, to the EKS config that enables EBS encryption on worker nodes. 
======
New Feature
Linked Issues
======
rancher/rancher#22633
======
=> expose aks ebsEncryption param

app/authenticated/cluster/cis/scan/detail/controller.js, app/models/clusterscan.js, lib/shared/addon/utils/util.js, lib/shared/app/utils/util.js
======
The downloaded report now has:
- A column for passed_nodes
- A column for failed_nodes
- A column for all nodes the test ran against
- The benchmark version in the header
======
Linked Issues
======
rancher/rancher#24671
=> Update the downloaded report

app/components/container/new-edit/template.hbs
======
Disabled the option to add description in workload as API doesn't support it. Description field is not in the workload schema
======
Linked Issues
======
https://github.com/rancher/rancher/issues/21357
======
=> Disabled the option to add description in workload

app/authenticated/cluster/cis/scan/detail/controller.js, app/components/cluster/cis/scan/detail/nodes-table/table-row/template.hbs, translations/en-us.yaml
======
If nodes have been deleted previous reports with missing nodes were
breaking. To resolve that we now only show links to nodes that we can
find.
======
Linked Issues
======
rancher/rancher#24676
=> Conditionally show node links in CIS Scans

app/authenticated/project/hpa/detail/edit/route.js, app/authenticated/project/hpa/new/route.js, translations/en-us.yaml
======
Support StatefulSet in HPA UI. It is supported in backend.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/24677
======
=> Support StatefulSet in HPA UI

app/components/cru-volume/component.js, app/components/volume-source/source-csi/component.js, app/components/volume-source/source-csi/template.hbs, app/models/volume.js, translations/en-us.yaml
======
Cannot edit PV which provisioned by CSI driver such as Longhorn.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/24665
======
=> Fix CSI plugin issue

app/styles/components/_code.scss, lib/global-admin/addon/components/cru-cloud-credential/template.hbs, lib/nodes/addon/components/driver-vmwarevsphere/component.js, lib/nodes/addon/components/driver-vmwarevsphere/template.hbs, lib/shared/addon/components/input-yaml/component.js, lib/shared/addon/components/input-yaml/template.hbs, translations/en-us.yaml
======
Backport of https://github.com/rancher/ui/pull/3654
======
Bugfix
Linked Issues
======
rancher/rancher#24314
======
=> [2.3] Improve Vsphere UX around cloudinit/cloudconfig

translations/en-us.yaml
======
Change confusing text to indicate windows is available in versions greater than 1.15.
======
Bugfix
Linked Issues
======
rancher/rancher#24746
======
=> [2.4] Change windows support help label to include later versions

translations/en-us.yaml
======
Change confusing text to indicate windows is available in versions greater than 1.15.
======
Bugfix
Linked Issues
======
rancher/rancher#24746
======
=> Change windows support help label to include later versions

lib/shared/addon/components/cluster-driver/driver-rke/component.js
======
cpConfig can be undefined so we need to check that it isn't before we try to pull a property off the object.
======
Bugfix
Linked Issues
======
rancher/rancher#24749
======
=> [2.3] Fix Edit As Yaml Button

lib/shared/addon/components/cluster-driver/driver-rke/component.js
======
cpConfig can be undefined so we need to check that it isn't before we try to pull a property off the object.
======
Bugfix
Linked Issues
======
rancher/rancher#24749
======
=> Fix Edit As Yaml button 

lib/nodes/addon/components/driver-vmwarevsphere/component.js
======
Making the clearing on save more comprehensive. Now clear the
following fields when appropriate:
- cloneFrom
- boot2dockerUrl
- contentLibrary
======
Linked Issues
======
rancher/rancher#24747
=> Making vsphere node templates more robust

lib/nodes/addon/components/driver-vmwarevsphere/component.js
======
Making the clearing on save more comprehensive. Now clear the
following fields when appropriate:
- cloneFrom
- boot2dockerUrl
- contentLibrary
======
Linked Issues
======
rancher/rancher#24747
=> [forwardport] Making vsphere node templates more robust

lib/shared/addon/components/modal-yaml/component.js
======
Caught the exception when the input is in the wrong YAML format, which caused the edit page stuck at 'saving'.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/24767
======
=> Fixed stucking at 'saving' while editing yaml

lib/shared/addon/components/input-paste/component.js
======
`input-paste` was not attaching to the correct element so the paste action was never firing. 
======
bugfix
Linked Issues
======
rancher/rancher#23587
======
N/A
=> input-paste action bug

lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
======
There is no need to show the `edit yaml` button when launching a custom cluster and you're past step 1 because. Non of the changes applied on the second step of launching a cluster apply to the cluster config and only change the command the user is running. 
======
bugfix
Linked Issues
======
rancher/rancher#24749
======
=> remove display of 'edit yaml' button on step > 1 for custom cluster

lib/shared/addon/components/cluster-driver/driver-rke/component.js
======
On Cluster edit if a cluster didn't have cloud config the cloud config object still has a name property and the empty configs so we would see the null objects being injected in the yaml. I've added an extra set of conditionals to deal with this case. 
======
Bugfix
Linked Issues
======
======
=> Edit As Yaml Cloud Config Bug

lib/shared/addon/components/cluster-driver/driver-rke/component.js
======
On Cluster edit if a cluster didn't have cloud config the cloud config object still has a name property and the empty configs so we would see the null objects being injected in the yaml. I've added an extra set of conditionals to deal with this case. 
======
Bugfix
Linked Issues
======
======
=> [2.3] Edit As Yaml Cloud Config Bug

app/components/cru-config-map/template.hbs, app/components/cru-secret/template.hbs, app/models/configmap.js, app/models/secret.js
======
Added form to config labels and annotations while adding a Config Map
======
Linked Issues
======
rancher/rancher#21513
======
=> Enable add labels and annotations while adding Secret and Config Maps

app/components/accordion-pod/component.js
======
Need to sort on `sortname` of the resource which will sort names with numerical values in them correctly. 
======
bugfix
Linked Issues
======
rancher/rancher#24528
======
=> [2.3] Fix Pod Accordion Sort 

lib/shared/addon/components/input-integer/component.js
======
Having this min num check here is not really incorrect but it makes for a weird
UX. The users typed value is overridden because it never reaches the minimum
since each keystroke causes the change event to fire.
======
Bugfix
Linked Issues
======
rancher/rancher#24724
======
=> remove min num check from input integer

lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, translations/en-us.yaml
======
Removes unnecessary labels 
Fixes inconsistent spacing
Matches table styles 
Swapped banner component in
Made some label text more consistent
======
Bugfix
Linked Issues
======
rancher/rancher#24640
======
=> Fix Style and Markup Issues - Node Options Custom Cluster

lib/istio/addon/components/config-validation-list/component.js, lib/istio/addon/components/istio-catalog/component.js, lib/istio/addon/components/istio-catalog/template.hbs, lib/istio/addon/components/istio-nav/component.js, lib/istio/addon/components/traffic-monitoring/component.js, lib/istio/addon/project-istio/route.js, lib/shared/addon/mixins/crud-catalog.js
======
Istio >=1.4.2 changes the path to Kiali dashboard. This PR updates those links.
Additionally it exposes the `forceUpgrade` option on the Isitio upgrade flow. 
======
New Feature
Linked Issues
======
rancher/rancher#24701
======
N/A
=> [2.4] Isitio/Kiali Breaking Changes - Links

lib/istio/addon/components/config-validation-list/component.js, lib/istio/addon/components/istio-catalog/component.js, lib/istio/addon/components/istio-catalog/template.hbs, lib/istio/addon/components/istio-nav/component.js, lib/istio/addon/components/traffic-monitoring/component.js, lib/istio/addon/project-istio/route.js, lib/shared/addon/mixins/crud-catalog.js
======
Istio >=1.4.2 changes the path to Kiali dashboard. This PR updates those links.
Additionally it exposes the `forceUpgrade` option on the Isitio upgrade flow. 
======
New Feature
Linked Issues
======
rancher/rancher#24701
======
N/A
=> [WIP] [2.3] Isitio/Kiali Breaking Changes - Links

lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/utils/util.js
======
I originally tried to fix rancher/rancher#24704 without completely
special casing. Unfortunately that lead to other issues:
rancher/rancher#24794
rancher/rancher#24814
I decided to revert all of the related changes and to just special
case this one instance. Ultimately I think the removeEmpty is the
culprit but it requires backend changes in order to properly fix
and those changes are not happening right now.
======
Linked Issues
======
rancher/rancher#24704
rancher/rancher#24794
rancher/rancher#24814
=> Making awsCloudProvider a special case

lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/utils/util.js
======
I originally tried to fix rancher/rancher#24704 without completely
special casing. Unfortunately that lead to other issues:
rancher/rancher#24794
rancher/rancher#24814
I decided to revert all of the related changes and to just special
case this one instance. Ultimately I think the removeEmpty is the
culprit but it requires backend changes in order to properly fix
and those changes are not happening right now.
======
Linked Issues
======
rancher/rancher#24704
rancher/rancher#24794
rancher/rancher#24814
=> [backport] Making awsCloudProvider a special case 

lib/istio/addon/components/config-validation-list/component.js, lib/istio/addon/components/istio-catalog/component.js, lib/istio/addon/components/istio-nav/component.js, lib/istio/addon/components/traffic-monitoring/component.js, lib/istio/addon/project-istio/graph/route.js, lib/istio/addon/project-istio/route.js, lib/shared/addon/istio/service.js, lib/shared/app/istio/service.js
======
This PR changes the default links for the Kiali service for Istio version >=1.4.2 (rancher catalog version 0.1.2). Prior to this version the link to Kiali had a different format and port. The ui will respond accordingly when launching or editing by checking the version on the the Istio app. When we're at the project level the logged in user may not be able to access the system project to get the app version though, so I've piggybacked on the previous method to determine if the link as available and fire a request to each endpoint and use the working link. 
Note that the `config-validation-list` component fires off the call to check the status of the links on init where as the other components that may use this do not and instead we fire the call on the route. The …
=> New Kiali Links for Istio version >=1.4.2

lib/istio/addon/components/config-validation-list/component.js, lib/istio/addon/components/istio-catalog/component.js, lib/istio/addon/components/istio-nav/component.js, lib/istio/addon/components/traffic-monitoring/component.js, lib/istio/addon/project-istio/graph/route.js, lib/istio/addon/project-istio/route.js, lib/shared/addon/istio/service.js, lib/shared/app/istio/service.js
======
This PR changes the default links for the Kiali service for Istio version >=1.4.2 (rancher catalog version 0.1.2). Prior to this version the link to Kiali had a different format and port. The ui will respond accordingly when launching or editing by checking the version on the the Istio app. When we're at the project level the logged in user may not be able to access the system project to get the app version though, so I've piggybacked on the previous method to determine if the link as available and fire a request to each endpoint and use the working link. 
Note that the `config-validation-list` component fires off the call to check the status of the links on init where as the other components that may use this do not and instead we fire the call on the route. The …
=> [2.3.4] New Kiali Links for Istio version >=1.4.2

lib/shared/addon/components/form-versions/template.hbs, translations/en-us.yaml
======
Adds a help block just below the k8s version selector to clusters and templates on edit.
======
New Feature
Linked Issues
======
rancher/rancher#24829
======
N/A
=> Add Label to K8s Version Select

lib/shared/addon/components/form-versions/template.hbs, translations/en-us.yaml
======
Adds a help block just below the k8s version selector to clusters and templates on edit.
======
New Feature
Linked Issues
======
rancher/rancher#24829
======
N/A
=> [2.3] Add Label to K8s Version Select

app/authenticated/project/route.js, lib/istio/addon/project-istio/graph/route.js, lib/istio/addon/project-istio/route.js
======
When back-porting the Istio link changes a couple services were missed during a conflict resolution.
This also fixes a bug where I accidentally removed a wrapping object around the namespaces return object in the route. This caused a bug where the namespaces for the Istio traffic monitoring route were empty which caused nothing to show up on the page. 
While debugging the traffic page issue I stumbled on a race condition with the current project id which I tracked down to the fact that we were finishing the project switch in the `setupController` method of the project route. With clusters we finish the switch in the after model. I moved the project level switch to after model as its consistent and ensures that additional routes, which could rely on the current …
=> [2.3] Istio Link Change Bugs

lib/istio/addon/components/modal-delete-istio/component.js, translations/en-us.yaml
======
In order for Istio to be redeployed after being disabled we have to remove the istio-system namespace. This PR adds that functionality. I also update the labels to indicate this will happen. 
======
Bugfix
Linked Issues
======
rancher/rancher#24850
======
=> delete the istio-system namespace when disabling istio

app/components/cru-config-map/template.hbs, app/components/settings/server-url/component.js, app/components/settings/server-url/template.hbs, translations/en-us.yaml, translations/zh-hans.yaml
======
- Hide description filed for configmap as it's not supported in schema
- Fix CATTLE_UI_PL issue
======
Linked Issues
======
rancher/rancher#23736
rancher/rancher#23681
======
=> Fix CATTLE_UI_PL issue

lib/global-admin/addon/clusters/index/controller.js, lib/global-admin/addon/clusters/index/template.hbs, lib/global-admin/addon/components/cluster-row/template.hbs
======
Add node name and node ip as `extraSearchSubFields` for cluster table
======
Linked Issues
======
https://github.com/rancher/rancher/issues/23305
======
=> Add extraSearchSubFields in cluster list

lib/nodes/addon/components/driver-vmwarevsphere/component.js
======
Folders can share the same suffix so I'm now showing
the full path so users can differtiate when the
suffix is the same.
======
Linked Issues
======
rancher/rancher#24853
=> [backport] Now displaying the full path for Folder

lib/nodes/addon/components/driver-vmwarevsphere/component.js
======
Folders can share the same suffix so I'm now showing
the full path so users can differtiate when the
suffix is the same.
======
Linked Issues
======
rancher/rancher#24853
=> Now displaying the full path for Folder

app/components/accordion-pod/template.hbs, app/components/pod-row/template.hbs, app/models/workload.js
======
- Show pod message
- Fix scale workload issue
======
Linked Issues
======
https://github.com/rancher/rancher/issues/24884
======
=> Show pod message

app/models/clustertemplaterevision.js
======
There is an old back end bug where the revisions are not getting cleaned up correctly and if we hit this case we can't load the UI because the revision id doesn't check first if it exists. With this check we should be safe from hitting this case even though we should really never hit it when the back end issue is resolved. 
======
Linked Issues
======
======
=> add error check on default check for RKE templates

translations/zh-hant.yaml
======
======
Linked Issues
======
rancher/rancher#24300
======
=> fix pathing issue in zh-hant

lib/shared/addon/mixins/crud-catalog.js
======
During the upgrade process of Istio we were not updating the external id for the new version of the app we are using. Since we recently added the `maxVersion` logic to the system chart of Istio an error would show up because of this bug. Updating the version on the external id resolves this error from the api. 
======
Bugfix
Linked Issues
======
rancher/rancher#24956
======
=> [2.3] Ensure Istio app version is upgraded correctly during upgrade process

lib/shared/addon/mixins/crud-catalog.js
======
During the upgrade process of Istio we were not updating the external id for the new version of the app we are using. Since we recently added the `maxVersion` logic to the system chart of Istio an error would show up because of this bug. Updating the version on the external id resolves this error from the api. 
======
Bugfix
Linked Issues
======
rancher/rancher#24956
======
=> Ensure Istio app version is upgraded correctly during upgrade process

lib/shared/addon/utils/util.js
======
This was erroneously removed during a revert.
======
Linked issues
======
- rancher/rancher#24952
=> Putting extractUniqueStrings util back in

lib/shared/addon/components/cluster-driver/driver-rke/component.js
======
Wrap the validation method for new clusters in a next block. Doing so ensure that the config edits are applied before we validate the config. 
======
Bugfix
Linked Issues
======
rancher/rancher#24971
======
=> Ensure Cluster Name in Yaml is Applied

app/models/configmap.js
=====
Config maps started processing and displaying binary data. When this was setup the computed watch keys had a bug and were trying to watch the 'model.<key>`. This made it so when you edited the config map the data didn't update on the detail page until page refresh. Dropping the model off the watch makes it wall work again. 
======
Bugfix
Linked Issues
======
rancher/rancher#24748
=====
N/A
=> Misconfigured Computed Property

lib/shared/addon/components/cluster-driver/driver-azureaks/component.js
======
we should let the version picker choose the latest version
======
Bugfix
Linked Issues
======
rancher/rancher#25100
======
=> [2.3] Remove default k8s version value from AKS cluster

lib/shared/addon/components/cluster-driver/driver-azureaks/component.js
======
we should let the version picker choose the latest version
======
Bugfix
Linked Issues
======
rancher/rancher#25100
======
=> Remove default k8s version value from AKS cluster

lib/shared/addon/mixins/crud-catalog.js
======
This pr removes a version check that was added previously as part of ensuring the external id is updated correctly. There is no need to do this version check here as it happens as part of the upgrade process later. 
======
Bugfix
Linked Issues
======
rancher/rancher#25114
======
=> [2.3] Istio Edit Error

lib/shared/addon/mixins/crud-catalog.js
======
This pr removes a version check that was added previously as part of ensuring the external id is updated correctly. There is no need to do this version check here as it happens as part of the upgrade process later. 
======
Bugfix
Linked Issues
======
rancher/rancher#25114
======
=> Istio Edit Error

lib/shared/addon/scope/service.js
======
We shouldn't need this param any longer and including it ensure that a new call
is made every time the methods are called. This is fine at small scale but will start to
slow everything down when at scale.
======
Bugfix
Linked Issues
======
rancher/rancher#25024
rancher/rancher#25026
======
=> Scaling Improvments: Remove `forceReload` param from getAllClusters & getAllProjects

app/authenticated/cluster/cis/scan/controller.js, app/authenticated/cluster/cis/scan/detail/controller.js, app/models/cluster.js, translations/en-us.yaml
======
Improving the UX of CIS based on the feedback that was received during
the review.
- Sort scans by date so newest will be on top.
- Details should be sorted by state in Fail, Skipped, Pass order
- Add a Run CIS Scan action to the cluster action menu.
======
Linked Issues
======
rancher/rancher#25159
======
Sort by date
Sort by state
Add Run CIS Scan to cluster action menu
=> Improve UX of CIS

app/components/registry-row/template.hbs, app/models/dockercredential.js
======
`displayAddress` was only returning the translation path and since we removed `maybe-t` helper we need to use INTL to fetch the translation. 
======
Linked Issues
======
rancher/rancher#25069
======
=> Change registry displayAddress to use intl service

lib/shared/addon/components/cru-cluster/template.hbs
======
This is actually a backport of https://github.com/rancher/ui/commit/7a956b1fa5a0d1d1ddd07ad925cb71976ba2f611#diff-3461d5a025bb99139d3bf89ab2060efb in master.
======
Bugfix
Linked Issues
======
rancher/rancher#25120
======
=> Use correct AKS banner message in cru-cluster

app/components/modal-drain-node/component.js, app/components/modal-drain-node/template.hbs, app/styles/components/_forms.scss, app/styles/components/_new-select.scss, lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, lib/shared/addon/components/drain-node/component.js, lib/shared/addon/components/drain-node/template.hbs, lib/shared/app/components/drain-node/component.js, translations/en-us.yaml
======
This required refactoring the drain modal into a reusable component
since these fields were going to be used in more than one place.
======
Linked Issues
======
rancher/rancher#24110
=> Add zero downtime upgrade options to rke driver

lib/global-admin/addon/clusters/new/launch/route.js, lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cru-cluster/component.js, lib/shared/addon/components/form-name-description/component.js, lib/shared/addon/utils/util.js
======
Adds an empty name to the cluster model creation so it isn't missing if the user
opens yaml editor and knows they should input it
Removes incorrect next usage
Adds logic to handle overriding the name in name-desc when updateYaml is called
Updates form-name-description model observer to watch the two props it actually
cares about
Fixes bug in removeEmpty util which would remove excludedKeys during filter phase
======
Bugfix
Linked Issues
======
rancher/rancher#24971
======
=> Ensure Name in Cluster Create Yaml is Used

app/models/workload.js
======
If the server-side redeploy action is present on a workload, use that instead of manipulating the annotation on the client-side.
======
Enhancement
Linked Issues
======
rancher/rancher#23053 (Server issue)
rancher/rancher#24777 (Server PR)
=> Use server-side redeploy action if it exists (rancher/rancher#23053)

lib/global-admin/addon/components/cru-cloud-credential/component.js, lib/global-admin/addon/components/cru-cloud-credential/template.hbs, translations/en-us.yaml
======
Region was added to the amazon cloud credential config. This PR exposes the param in the UI.
======
New Feature
Linked Issues
======
rancher/rancher#23060
======
=> Expose region on Amazon Cloud Credential

app/models/node.js
======
Logic for replacing OS name for RHEL8 as its different to RHEL7
======
"new feature"
Linked Issues
======
https://github.com/rancher/rancher/issues/23045
=> Shorten OS name for RHEL8

app/components/container-logs/component.js, app/models/pod.js
======
Logs were only connecting on the first run. I refactored the observer to fire on init and added some safety checks to ensure we're not throwing errors. Logs connect every time now. 
======
Bugfix
Linked Issues
======
rancher/rancher#25297
======
N/A
=> Refactor logs connect so the logs connect every time

translations/en-us.yaml
"Delete and recreate resources if needed during the upgrade" does not explain well what this does...referencing the helm equivalent will allow the user to refer to helm docs for explanation.
======
======
Linked Issues
======
======
=> explain how functionality works in Helm

lib/global-admin/addon/mixins/saml-auth.js
======
======
Bugfix
Linked Issues
======
rancher/rancher#25426
======
=> Fix destructuring error

lib/global-admin/addon/mixins/saml-auth.js
======
When fixing a previous issue I missed adding back in the not comparitor and we never set the API Host when empty like we should have. 
======
Bugfix
Linked Issues
======
rancher/rancher#25449
======
=> SAML - Incorrect comparison

lib/global-admin/addon/components/saml-config/component.js, lib/global-admin/addon/components/saml-config/template.hbs, server/proxies/api.js
======
I've overloaded the expand function for shibboleth when using the open ldap
search. Upon open we'll pre-populate with all the data from the schema, on close
we'll assume the user doesn't want this feature and delete the fields.
======
Bugfix
Linked Issues
======
rancher/rancher#25459
======
=> SAML Shibboleth Config Error

lib/global-admin/addon/components/saml-config/template.hbs, lib/global-admin/addon/components/site-access/component.js, lib/global-admin/addon/mixins/authentication.js, lib/global-admin/addon/mixins/saml-auth.js
======
Adds logic to correctly validate rancherApiHost when enabling SAML (all providers)
Adds logic to close edit inputs when canceling from the SAML Edit view.
======
Linked Issues
======
rancher/rancher#25456
rancher/rancher#25477
======
=> Shibboleth Issues

app/components/page-header/component.js, app/components/page-header/template.hbs, lib/shared/addon/utils/constants.js, package.json, translations/en-us.yaml
=> Add toggle to Dashboard if Steve feature is enabled

app/components/input-edit-password/component.js, app/components/input-edit-password/template.hbs, app/styles/components/_login.scss, app/update-password/controller.js, app/update-password/template.hbs, lib/shared/addon/access/service.js, lib/shared/addon/settings/service.js, lib/shared/addon/utils/constants.js, translations/en-us.yaml
=> Agree to eula on first login

lib/nodes/addon/components/driver-amazonec2/template.hbs, translations/en-us.yaml
======
======
New Feature
Linked Issues
======
rancher/rancher#25266
======
=> Expose encryptEbsVolume param on EC2 Node Template

lib/nodes/addon/components/driver-amazonec2/template.hbs, translations/en-us.yaml
======
======
New feature
Linked Issues
=====
rancher/rancher#25266
======
=> [2.3.6] Expose encryptEbsVolume param on EC2 Node Template

translations/en-us.yaml
======
Fixing strings based on feedback
======
Linked Issues
======
rancher/rancher#25525
=> Fixing strings based on feedback

app/authenticated/cluster/edit/route.js, app/models/cluster.js, lib/global-admin/addon/components/cluster-row/template.hbs, lib/shared/addon/components/cluster-driver/driver-import/component.js, lib/shared/addon/components/k3s-cluster-info/component.js, lib/shared/addon/components/k3s-cluster-info/template.hbs, lib/shared/addon/k3s/service.js, lib/shared/app/k3s/service.js, server/proxies/api.js, translations/en-us.yaml
======
Adds the missing channel api to the k3s service and exposes the input in a select.
Fixes a few minor bugs found during dev. 
======
Linked Issues
======
rancher/rancher#25400
rancher/rancher#25401
======
N/A
=> Import K3S Cluster Missing Version Feature & Fixes

app/components/modal-restore-backup/component.js, app/components/modal-restore-backup/template.hbs, translations/en-us.yaml
======
The select and the radio options were updated.
======
Linked Issues
======
rancher/rancher#25630
rancher/rancher#25525
=> Updating text for snapshots

lib/shared/addon/settings/service.js
======
If we're on a master build of rancher we dont have a version to parse and the link for docBase is all goofed. This adds a 2.x fallback version so we dont have 404's.
======
Bugfix
Linked Issues
======
rancher/rancher#25600
======
=> Add 2.x fallback for telemetry docs link if on master

app/models/cluster.js, lib/global-admin/addon/components/cluster-row/template.hbs, lib/monitoring/addon/components/cluster-dashboard/template.hbs, lib/shared/addon/components/tooltip-expiring/template.hbs
======
We were showing the rotate link in banners and tooltips even though the action didn't exist. This hides if it doesn't.
======
Bugfix
Linked Issues
======
rancher/rancher#25563
======
=> Only show rotate action in tooltips and banners if exists on model

lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
======
The backend renamed maxUnavailable so we're doing the same.
======
Linked Issues
======
rancher/rancher#25670
=> Rename maxUnavailable to maxUnavailableWorker

lib/shared/addon/components/cluster-driver/driver-rke/component.js
======
Now load the rke upgrade strategy defaults and use them
appropriately after they've been loaded.
======
Linked Issues
======
rancher/rancher#25501
=> Ensure rke upgrade strategy defaults are used

lib/global-admin/addon/components/saml-config/template.hbs
======
Value defaults to false so there is no need for any other action than removing the input. 
======
Linked Issues
======
rancher/rancher#25471
======
=> Remove nested group search from Shibboleth OpenLdap Config

lib/shared/addon/components/node-pool-row/component.js
======
Add sortby to node templates select on cluster create page for RKE based clusters. 
======
Linked Issues
======
rancher/rancher#25316
======
=> sort node templates select options in cluster create

lib/shared/addon/components/cluster-driver/driver-rke/component.js
======
Prevent default from overwriting the existing value of max_unavailable_controlplane
======
Linked Issues
======
rancher/rancher#25670
=> Prevent default from overwriting the existing value of max_unavailable_controlplane

lib/shared/addon/components/cluster-driver/driver-rke/component.js
======
Was previously using the presence of nodeDrainInput to determine
the value of drain. Drain is now a part of the backend so I'm using
that value instead of inferring.
======
Linked Issues
======
rancher/rancher#25732
=> Use the drain property instead of inferring

app/components/modal-rollback-app/template.hbs, app/components/modal-rollback-mc-app/component.js, app/components/modal-rollback-mc-app/template.hbs, translations/en-us.yaml
======
Adds protip text in the modals of both project and global apps to indicate you are creating a new revision when rolling back. 
Adds additional fields to the hidden fields for the diff in MC app rollback. 
======
Bugfix
Linked Issues
======
rancher/rancher#25512
======
=> MC/Project App Rollback hide fields & add help text to modals

app/components/workload-row/template.hbs
======
Fixes image name clipping in workload rows. 
======
Bugfix
Linked Issues
======
rancher/rancher#24828
======
=> Fix clipping on workload image name

lib/global-admin/addon/components/cluster-row/template.hbs, lib/shared/addon/components/cluster-driver/driver-import/component.js, lib/shared/addon/components/k3s-cluster-info/component.js, lib/shared/addon/components/k3s-cluster-info/template.hbs
======
The params of the k3sConfig changed this update matches that spec. 
======
Bugfix
Linked Issues
======
rancher/rancher#25720
======
=> Update k3sConfig shape based on new api design

lib/global-admin/addon/components/saml-config/template.hbs
======
======
Bugfix
Linked Issues
======
rancher/rancher#25775
======
=> target the correct cofig for openldap search shibb

app/styles/app-dark.scss, app/styles/app-light.scss, lib/shared/addon/components/k3s-cluster-info/template.hbs, lib/shared/addon/k3s/service.js
======
Only show version selector on edit if we have more that the current version.
Fix pre coloring on light and dark themes
Update k3s versions service to use new release api
======
Bugfix
Linked Issues
======
rancher/rancher#25720
======
=> k3s Cluster Import Feedback

app/components/modal-rollback-mc-app/component.js
======
We werent watching all the correct props on the answers diff so we weren't recalculating the props like we should have. 
======
Bugfix
Linked Issues
======
rancher/rancher#25512
======
=> Fix computed prop cache error

app/styles/app-dark.scss, app/styles/app-light.scss, lib/shared/addon/components/k3s-node-args/component.js, lib/shared/addon/components/k3s-node-args/template.hbs, lib/shared/addon/components/k3s-node-env-var/component.js
======
The global pre changes affected some specific pre elements on the settings page, so I rolled back the global change and fixed k3s import node info instead. 
======
Linked Issues
======
======
=> Rollback pre color changes

lib/istio/addon/components/cru-destination-rule/component.js
======
Istio destination rules are not required to have a subset but the backend will error on an empty subset array so if we have that on save we now drop the key from the rule. 
======
Bugfix
Linked Issues
======
rancher/rancher#25513
======
=> Istio Dest Rule Empty Subset

app/components/modal-rollback-app/template.hbs, app/components/modal-rollback-service/template.hbs
https://github.com/rancher/rancher/issues/25800
=> fix diffs for 25800

lib/global-admin/addon/components/saml-config/component.js
======
When turning on TLS for Shibboleth OpenLDAP search the port will now auto update. 
======
Bugfix
Linked Issues
======
rancher/rancher#25799
======
=> Update Shibboleth OpenLDAP config port on tls enable

app/application/route.js, app/authenticated/cluster/cis/scan/controller.js, app/authenticated/cluster/cis/scan/detail/controller.js, app/authenticated/cluster/cis/scan/detail/template.hbs, app/authenticated/cluster/cis/scan/template.hbs, app/authenticated/cluster/edit/controller.js, app/authenticated/cluster/edit/route.js, app/components/cluster/cis/scan/detail/table-row/component.js, app/models/cluster.js, app/models/clusteralertrule.js, app/models/clusterscan.js, lib/alert/addon/components/alert/form-alert-rules/component.js, lib/alert/addon/components/alert/form-cluster-rule-row/component.js, lib/alert/addon/components/alert/form-cluster-rule-row/template.hbs, lib/alert/addon/components/alert/new-edit/component.js, lib/alert/addon/mixins/alert-rule.js, lib/alert/addon/new/controller.js, lib/alert/addon/new/route.js, lib/alert/addon/new/template.hbs, lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, lib/shared/addon/components/run-scan-modal/component.js, lib/shared/addon/components/run-scan-modal/template.hbs, lib/shared/addon/utils/util.js, lib/shared/app/components/run-scan-modal/component.js, translations/en-us.yaml
======
- Improve CIS UX.
- Add support for scheduling.
- Add support for alerting.
======
Linked Issues
======
rancher/rancher#25349
rancher/rancher#25327
rancher/rancher#24697
=> Improve CIS UX

lib/shared/addon/components/catalog-index/component.js
======
======
Linked Issues
======
======
=> Fix cluster/project catalog ref check in helm3 check

lib/shared/addon/mixins/cattle-transitioning-resource.js
======
Two new states were created by CIS. This adds the
default treatment of both pass and fail.
======
Linked Issues
======
rancher/rancher#25789
=> Add pass and fail as recognized states

lib/shared/addon/components/cluster-driver/driver-rke/component.js
======
Exposes the RKE DNS Nodelocal config params on cluster create/edit in yaml view only. 
======
New Feature
Linked Issues
======
rancher/rancher#25811
======
=> Ensure nodelocal shows up in cluster create yaml view for rke
