rancher/ui

lib/shared/addon/components/k3s-cluster-info/template.hbs, translations/en-us.yaml
======
======
New Feature
Linked Issues
======
rancher/rancher#25851
======
=> Add drain options to k3s imported clusters edit

app/models/catalog.js, lib/shared/addon/utils/constants.js
======
Exclude system catalog and new helm3 catalog from the canClone check on catalog models.
======
Bugfix
Linked Issues
======
rancher/rancher#25850
======
=> add new helm3 and system keys to catalog canClone check

app/components/cluster/cis/scan/detail/nodes-table/table-row/template.hbs, translations/en-us.yaml
======
Removing this link because we cannot accurately link to the node if a
node has been replaced.
======
Linked Issues
======
rancher/rancher#24734
=> Removing the link to nodes in the cis scans

app/authenticated/cluster/cis/scan/controller.js, app/components/cluster/cis/scan/table-row/template.hbs, app/models/clusterscan.js, translations/en-us.yaml
======
Adding the Not Applicable column to CIS Scans
======
Linked Issues
======
rancher/rancher#25857
=> Adding the Not Applicable column to CIS Scans

lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
======
CIS scheduling isn't supported on windows clusters.
======
Linked Issues
======
rancher/rancher#25864
=> Disable CIS scheduling for windows clusters

app/application/route.js
this ensures we have a new token for immediate use if the user wants to log back
in.
======
======
bugfix
Linked Issues
======
rancher/rancher#25714
======
=> Use window.location.replace to go back to login after logout

lib/shared/addon/components/form-versions/component.js
======
Improves the readabliity and ensures that if the initialVersion is good we use
that version rather that max version.
======
Bugfix
Linked Issues
======
rancher/rancher#25335
======
=> Refactor form-version init val method

app/components/modal-rollback-app/template.hbs
https://github.com/rancher/rancher/issues/25800
=> fix pre styling on app rollback

lib/shared/addon/components/cluster-driver/driver-import/component.js, lib/shared/addon/components/cluster-driver/driver-import/template.hbs
======
I was firing both an action and directly editing the value of the nodeForInfo which caused race conditions on setting a value of a param on an object that didn't exit yet. Just going to use the action as its what we need for this implementation. 
======
Bugfix
Linked Issues
======
rancher/rancher#25860
======
=> Drop direct value edit on args selector k3s info box

lib/shared/addon/components/k3s-cluster-info/component.js
======
sort k3s version same as rke k8s versions
======
Bugfix
Linked Issues
======
rancher/rancher#25840
======
=> sort k3s version same as rke k8s versions

lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
======
Ensure drain default is recognized and maxUnavailableWorker is enabled
======
Linked Issues
======
rancher/rancher#25732
rancher/rancher#25875
=> Ensure drain default is recognized and maxUnavailableWorker is enabled

app/components/form-key-to-path/component.js
======
Missing secret data was causing an undefined error to be thrown and lock the UI up.
======
Linked Issues
======
rancher/rancher#25304
======
=> Handle Missing Secret Data

lib/shared/addon/components/input-slider/component.js
======
Target correct element with jquery for input-slider
======
Linked Issues
======
rancher/rancher#25908
======
=> Input Slider Bug

app/authenticated/cluster/cis/scan/template.hbs, translations/en-us.yaml
======
- Changed Set Alert and Set Schedule to Add Alert and Add Schedule
- Updated all references of Security Scan to CIS Scan
- Updated the CIS action buttons to have spaces on the CIS Scans page
======
Linked Issues
======
rancher/rancher#25852
=> Make CIS visual tweaks

app/styles/pages/_catalog.scss, lib/shared/addon/components/custom-catalog/template.hbs
======
Reduced size of helm3 catalog icon by 10%
======
Linked Issues
======
rancher/rancher#25850
======
=> Adjust size of helm3 catalog icon

lib/global-admin/addon/components/feature-flags/component.js, lib/global-admin/addon/components/feature-flags/template.hbs
======
Use the description from the back end rather than the temp descriptions built into the UI for feature flags page. 
======
New Feature
Linked Issues
======
rancher/rancher#25909
======
=> Use built in descriptions for feature flags

app/models/cluster.js, lib/global-admin/addon/components/cluster-row/template.hbs
======
Updates the computed watchers to ensure we are displaying the correct provider on the clusters overview page.
Removes erroneous check for k3sConfig kube version. We should always use the gitVersion.
=====
Bugfix
Linked Issues
======
rancher/rancher#25930
rancher/rancher#25876
======
=> K3s Import Tweaks

lib/shared/addon/components/form-versions/component.js
======
Since we're always passing the initValue method the initial version as a coerced version (without the .x) we dont need to check that here. We will either set the value to the initial version (no x) or the max version from semver based on our satisfies checks. 
======
Bugfix
Linked Issues
======
rancher/rancher#25335
======
=> Remove unneeded valueIsPatchVersion

app/authenticated/cluster/cis/scan/controller.js, app/components/cluster/cis/scan/detail/table-row/component.js, app/components/cluster/cis/scan/table-row/template.hbs, app/models/clusterscan.js, lib/shared/addon/components/cluster-driver/driver-rke/component.js, translations/en-us.yaml
======
- Prevent the skip button from showing for N/A tests
- Add profile column to CIS Scans page and modify cron default
======
Linked Issues
======
rancher/rancher#25863
rancher/rancher#25890
rancher/rancher#25933
rancher/rancher#25857
=> Several small CIS fixes

lib/global-admin/addon/clusters/new/select/controller.js, lib/global-admin/addon/clusters/new/select/template.hbs, translations/en-us.yaml
======
======
Linked Issues
======
======
=> update verbiage for k3s cluster import

lib/shared/addon/components/annotations-section/component.js, lib/shared/addon/components/form-labels-annotations/component.js, lib/shared/addon/components/labels-section/component.js, lib/shared/addon/mixins/manage-labels.js, lib/shared/addon/utils/constants.js
======
k3s node annotations/labels should be in the correct read-only and ignore constants.
======
Bugfix
Linked Issues
======
rancher/rancher#25958
======
=> Ensure any k3s annotations/labels are read-only

lib/shared/addon/components/cru-cloud-provider/template.hbs, translations/en-us.yaml
======
Remove duplicate verbiage and fix broken link in azure cloud provider.
======
Bugfix
Linked Issues
======
rancher/rancher#25960
======
=> Azure Cloud Provider Translation Issue

app/authenticated/cluster/cis/scan/controller.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, translations/en-us.yaml
======
- Make table sorting work with scheduled scans
- Make the cis table fit on laptop screen
- Add an appropriate placeholder for the scheduled scans cron field
======
Linked Issues
======
rancher/rancher#25937
rancher/rancher#25939
=> Make several small tweaks to the CIS UI

lib/shared/addon/components/cluster-driver/driver-import/component.js, lib/shared/addon/components/cluster-driver/driver-import/template.hbs
======
Without the value in place when the user visited this page with only one node when we auto select the dropdown wouldn't have an initialized value.
======
Bugfix
Linked Issues
======
rancher/rancher#25966
======
=> Tweak K3S nodeForInfo getters/setters

lib/global-admin/addon/clusters/new/select/controller.js, lib/shared/addon/components/annotations-section/component.js, lib/shared/addon/components/cluster-driver/driver-import/component.js, lib/shared/addon/components/cluster-driver/driver-import/template.hbs, lib/shared/addon/components/k3s-cluster-info/template.hbs, lib/shared/addon/components/labels-section/component.js, translations/en-us.yaml
======
Fixes a bug where users can input negative values for concurrency inputs.
Wraps k3s docs link in import box in prevent default so we can have link in link in link in link in link. 
Removes the read-only node info from the edit cluster page until we can edit the config.
Drops the filter of the k3s labels and annotations in there respective accordions on the node detail page. 
======
Linked Issues
======
rancher/rancher#25981
rancher/rancher#25982
======
=> K3s Import Feedback

app/components/container/form-ports/template.hbs, app/components/container/form-scale/template.hbs, lib/shared/addon/components/input-integer/component.js
======
======
Linked Issues
======
rancher/rancher#25974
======
=> Fix incorrect min/max values for workloads

lib/global-admin/addon/components/cru-cloud-credential/component.js, lib/global-admin/addon/components/cru-cloud-credential/template.hbs, translations/en-us.yaml
======
This reverts commit 94d48efcdf12b1ffd20102cbd8ee6c6b9aa58725.
======
Revert
Linked Issues
======
rancher/rancher#23060
======
=> Revert "Expose region on Amazon Cloud Credential"

app/components/page-header/template.hbs, app/styles/components/_page-header.scss
no issue just polishing the try button to look more like a button
=> try dashboard button

lib/global-admin/addon/components/feature-flags/component.js, lib/global-admin/addon/components/feature-flags/template.hbs, translations/en-us.yaml
======
======
New Feature
Linked Issues
======
rancher/rancher#25421
======
=> Add restart required text and column to features page

.drone.yml, translations/ar-sa.yaml, translations/de-de.yaml, translations/es-es.yaml, translations/fa-ir.yaml, translations/fr-fr.yaml, translations/hu-hu.yaml, translations/ja-jp.yaml, translations/nb-no.yaml, translations/pt-br.yaml, translations/tr-tr.yaml, translations/uk-ua.yaml, translations/vi-vn.yaml
======
Sync translations from Crowdin
======
Linked Issues
======
======
=> Translations Update

app/styles/components/_page-header.scss
bg color was incorrect on dark theme
=> fix bg color of try on dark

lib/global-admin/addon/components/feature-flags/template.hbs
======
======
Linked Issues
======
======
=> Flip checkmark icon for dynamic features

app/authenticated/cluster/backups/controller.js, app/authenticated/cluster/backups/template.hbs, app/components/modal-restore-backup/component.js, app/components/modal-restore-backup/template.hbs, app/models/cluster.js, app/models/etcdbackup.js
======
- Added a Snapshot Now button to the top of the table
- Added a Restore Snapshot option to the actions of each row which will
select the current row when opening the modal
======
Linked Issues
======
rancher/rancher#25511
=> Improve the UX of our Snapshots page

app/authenticated/cluster/cis/scan/detail/route.js, app/authenticated/cluster/cis/scan/route.js, app/authenticated/cluster/cis/scan/template.hbs, app/components/cluster/cis/scan/detail/table-row/template.hbs, lib/shared/addon/cis-helpers/service.js, lib/shared/addon/components/run-scan-modal/component.js, lib/shared/addon/components/run-scan-modal/template.hbs, lib/shared/addon/security-scan-config/service.js, translations/en-us.yaml
======
- Label change for scheduled scans
- Fixed a table rendering bug that occured due to the incorrect value
of colspan
- Disabled the alert and scheduled scan button on the cis page for
windows clusters
- Fixed an issues where two scans couldnt run at the same time due
to a profile not being defined for a second run scan modal.
======
Linked Issues
======
rancher/rancher#26009
rancher/rancher#26021
rancher/rancher#25987
rancher/rancher#25983
=> Various CIS fixes

app/authenticated/cluster/cis/scan/controller.js, app/components/cluster/cis/scan/table-row/component.js, app/components/cluster/cis/scan/table-row/template.hbs
======
We now support displaying an error message when CIS scan fails to execute
properly.
======
Linked Issues
======
rancher/rancher#25792
=> Adding support for CIS error messages

app/authenticated/cluster/cis/scan/detail/controller.js, app/components/cluster/cis/scan/detail/nodes-table/table-row/component.js
======
When a test is N/A the nodes will also be N/A
======
Linked Issues
======
rancher/rancher#26067
=> When a test is N/A the nodes will also be N/A

lib/shared/addon/mixins/cattle-transitioning-resource.js
======
This will allow the available actions to dynamically change if
the underlying store changes. This was specifically to enable
the node template actions to update based on a cluster
being deleted.
======
Linked Issues
======
rancher/rancher#25452
=> Allow available actions to be dynamically changed

lib/shared/addon/cis-helpers/service.js, lib/shared/addon/components/run-scan-modal/component.js, lib/shared/addon/components/run-scan-modal/template.hbs, translations/en-us.yaml
======
Update the UX to reflect new requirements
======
Linked Issues
======
rancher/rancher#26066
=> Update the UX to reflect new requirements

lib/shared/addon/components/run-scan-modal/template.hbs
======
Update text styling on the run scan modal
======
Linked Issues
======
rancher/rancher#26122
=> Update text styling on the run scan modal

translations/en-us.yaml
======
Updating the doc urls on the run security scan modal
======
Linked Issues
======
rancher/rancher#28570
=> Updating the doc urls on the run security scan modal

lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, lib/shared/addon/components/drain-node/template.hbs
======
Add override support for the upgradeStrategy fields in RKE Template
======
Linked Issues
======
rancher/rancher#26142
=> Add override support for the upgradeStrategy fields in RKE Template

app/components/modal-drain-node/component.js, lib/shared/addon/components/check-override-allowed/template.hbs, lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, lib/shared/addon/components/drain-node/component.js, lib/shared/addon/components/drain-node/template.hbs
======
Refactor scheduleScan and upgradeStrategy
The refactor was necessary to get the two to work with all aspects of
rke templates.
======
Linked Issues
======
rancher/rancher#26149
rancher/rancher#26188
rancher/rancher#26187
=> Refactor scheduleScan and upgradeStrategy

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js, lib/shared/addon/components/cluster-driver/driver-amazoneks/template.hbs
======
This adds disabled to some fields that were not previously disabled on edit. 
Also takes you to step 6 (final step) after entering and sending your credentials on edit because there are no fields in any of the steps that are editable besides the k8s version so there should be no need to go through and fetch all that data again that happens when we are proceeding through the steps. 
Updates the k8s version list as well. 
======
Bugfix
Linked Issues
======
rancher/rancher#26231
======
=> Edit Amazon EKS Issues

lib/shared/addon/components/custom-catalog/component.js
======
I did not know we did this but now when you delete the helm3 rancher catalog it won't be removed from the catalog list. 
======
Bugfix
Linked Issues
======
rancher/rancher#26213
======
=> Add helm 3 to the list of fake catalogs we show as "disabled" if deleted

lib/shared/addon/mixins/cattle-transitioning-resource.js, lib/shared/addon/utils/constants.js
======
======
Bugfix
Linked Issues
======
rancher/rancher#25917
======
=> updating state map and transitions map for rke workers

lib/shared/addon/cis-helpers/service.js
======
Fix run scan issue with invalid skip config
======
Linked Issues
======
https://github.com/rancher/rancher/issues/26248
======
=> [2.4.0] Fix run scan issue with invalid skip config

lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
======
Removed another case of 'true'
======
Linked Issues
======
rancher/rancher#26245
=> Removed another case of 'true'

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js
======
======
Linked Issues
======
rancher/rancher#26281
======
=> Drop EKS k8s 1.12 from versions list

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js
======
======
Linked Issues
======
rancher/rancher#26285
======
=> [2.3] Drop EKS k8s 1.12 from versions list

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js
======
Remove sort versions for EKS since we control versions array
======
Bugfix
Linked Issues
======
rancher/rancher#26296
======
=> EKS Version Sort

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js
======
Remove sort versions for EKS since we control versions array
======
Bugfix
Linked Issues
======
rancher/rancher#26296
======
=> [2.3]EKS Version Sort

app/models/cluster.js, lib/monitoring/addon/components/cluster-basic-info/template.hbs
======
Display hosted k8s cluster region in cluster dashboard
======
Linked Issues
======
https://github.com/rancher/rancher/issues/25656
======
=> [Master] Display hosted k8s cluster region in cluster dashboard

app/models/cluster.js, lib/monitoring/addon/components/cluster-basic-info/template.hbs
======
Display hosted k8s cluster region in cluster dashboard
======
Linked Issues
======
https://github.com/rancher/rancher/issues/25656
======
=> [2.4] Display hosted k8s cluster region in cluster dashboard

translations/zh-hant-tw.yaml
======
Although Rancher already provides traditional Chinese translation(zh-hant), but it uses the words that are used in China, so I translated a version for Taiwanese wording habits.
雖然 Rancher 已經有提供繁體中文翻譯，但是是使用的是中國所習慣的用詞，因此為其翻譯了較為符合臺灣用詞習慣的版本。
======
- Translations Chinese(zh-hant-tw)
Linked Issues
======
======
=> Translations Chinese(zh-hant-tw)

lib/shared/addon/oauth/service.js, translations/zh-hant-tw.yaml
======
======
Linked Issues
======
======
=> 2.4 Backport Sync

lib/nodes/addon/components/driver-aliyunecs/component.js, lib/nodes/addon/components/driver-aliyunecs/template.hbs, translations/en-us.yaml, translations/zh-hans.yaml
======
Support InternetChargeType field in Aliyun ECS template
======
- New feature 
Linked Issues
======
https://github.com/rancher/rancher/issues/15847
======
Related PR:
https://github.com/rancher/rancher/pull/26306
=> [Master] Update aliyun node driver to support internetChargeType field

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js
======
- Add 2 newly launched EKS China regions `cn-northwest-1` and `cn-north-1`
======
Linked Issues
======
https://github.com/rancher/rancher/issues/25613
======
=> [2.4] Support EKS cn-northwest-1 and cn-north-1

app/components/new-edit-project/template.hbs
======
Allow project members to be removed on edit.
======
Linked Issues
======
rancher/rancher#26428
======
=> Project Edit Cant Remove Members

app/components/new-edit-project/template.hbs
======
Allow project members to be removed on edit.
======
Linked Issues
======
rancher/rancher#26428
======
=> [2.4] Project Edit Cant Remove Members

lib/nodes/addon/components/driver-aliyunecs/component.js, lib/nodes/addon/components/driver-aliyunecs/template.hbs, translations/en-us.yaml, translations/zh-hans.yaml
======
Support InternetChargeType field in Aliyun ECS template
======
- New feature
Linked Issues
======
https://github.com/rancher/rancher/issues/15847
======
Related PR:
https://github.com/rancher/rancher/pull/26527
=> [2.4] Update aliyun node driver to support internetChargeType field

app/components/new-edit-project/template.hbs
======
======
Bugfix
Linked Issues
======
rancher/rancher#26428
======
=> new and edit projects should be able to remove members

app/components/new-edit-project/template.hbs
======
======
Bugfix
Linked Issues
======
rancher/rancher#26428
======
=> new and edit projects should be able to remove mem

app/models/roletemplate.js, lib/global-admin/addon/components/new-edit-role/component.js, lib/global-admin/addon/security/roles/index/controller.js
======
We weren't passing context around correctly for non-global roles.
======
Linked Issues
======
rancher/rancher#26547
======
=> Clone Role Context Bugs

app/components/new-edit-project/template.hbs, app/models/roletemplate.js, lib/global-admin/addon/components/new-edit-role/component.js, lib/global-admin/addon/security/roles/index/controller.js
======
We weren't passing context around correctly for non-global roles.
======
Bugfix
Linked Issues
======
rancher/rancher#26547
======
=> [2.4] Clone Role Context Bugs

package.json, yarn.lock
======
Long awaited update to ember-api-store that allows deeply nested schemas to be validate. Additionally updates deps and adds resolutions that had security alerts. 
======
Linked Issues
======
N/A
======
=> [Master]Bump UI Dependencies

translations/zh-hans.yaml
======
======
Linked Issues
======
======
=> [2.4] Update zh-hans

translations/zh-hans.yaml
======
======
Linked Issues
======
======
=> [Master] Update zh-hans

lib/monitoring/addon/components/cluster-dashboard/component.js, lib/monitoring/addon/components/cluster-dashboard/template.hbs, lib/shared/addon/utils/constants.js, translations/en-us.yaml
======
K3s clusters don't use etcd so it should match the other component status designs.
======
Linked Issues
======
rancher/rancher#26402
======
N/A
=> k3s Imported Cluster Etcd Indicator

lib/monitoring/addon/components/cluster-dashboard/component.js, lib/monitoring/addon/components/cluster-dashboard/template.hbs, lib/shared/addon/utils/constants.js, translations/en-us.yaml
======
K3s clusters don't use etcd so it should match the other component status designs.
======
Linked Issues
======
rancher/rancher#26402
======
N/A
=> [2.4] k3s Imported Cluster Etcd Indicator

package.json, yarn.lock
======
the store was throwing a false positive when validating answers which revealed
a bug with required and nullable fields.
======
Bugfix
Linked Issues
======
N/A
======
=> bump ember-api-store version

app/models/app.js, app/models/catalog.js, app/models/multiclusterapp.js, app/models/templateversion.js, lib/shared/addon/utils/constants.js
======
Add additional helm3 id to catalog constants and update checks on catalogs helm version.
======
New Feature
Linked Issues
======
rancher/rancher#26560
======
=> Loosen Catalog isHelm3 checks

app/models/app.js, app/models/catalog.js, app/models/multiclusterapp.js, app/models/templateversion.js, lib/shared/addon/utils/constants.js
======
Add additional helm3 id to catalog constants and update checks on catalogs helm version.
======
New Feature
Linked Issues
======
rancher/rancher#26560
======
=> [2.4] Loosen Catalog isHelm3 checks

lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, translations/en-us.yaml
======
Undefined error would be thrown when Global Template Enforcement is enabled and editing an existing cluster without a template.
Adds a translation string to alert the user they can not edit this cluster
Adds cancel to allow user to go back.
======
Bugfix
Linked Issues
======
rancher/rancher#26491
======
=> Edit Cluster With Templates On Bug

lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, translations/en-us.yaml
======
Undefined error would be thrown when Global Template Enforcement is enabled and editing an existing cluster without a template.
Adds a translation string to alert the user they can not edit this cluster
Adds cancel to allow user to go back.
======
Bugfix
Linked Issues
======
rancher/rancher#26491
======
=> [2.4.3] Edit Cluster With Templates On Bug

app/components/cru-storage-class/template.hbs, lib/shared/addon/components/storage-class/provisioner-longhorn/component.js, lib/shared/addon/components/storage-class/provisioner-longhorn/template.hbs
======
Longhorn storage class parameters are not editable.
On edit the initial parameters were incorrect, uses the model instead.
Makes a couple more fields that are editable not editable. 
======
Bugfix
Linked Issues
======
rancher/rancher#26617
======
=> Longhorn Edit Bugs

app/components/cru-storage-class/template.hbs, lib/shared/addon/components/storage-class/provisioner-longhorn/component.js, lib/shared/addon/components/storage-class/provisioner-longhorn/template.hbs
======
Longhorn storage class parameters are not editable.
On edit the initial parameters were incorrect, uses the model instead.
Makes a couple more fields that are editable not editable. 
======
Bugfix
Linked Issues
======
rancher/rancher#26617
======
=> [2.4] Longhorn Edit Bugs

app/catalog-tab/launch/route.js, app/components/cru-persistent-volume/component.js, app/models/app.js, lib/shared/addon/components/upgrade-btn/component.js, lib/shared/addon/components/upgrade-btn/template.hbs
======
When editing a Longhorn PV the component selecting computed property would incorrectly select the CSI driver rather than the Longhorn CSI driver. 
Catalog versions can't be downgraded unless using rollback, filter versions less that current on upgrade.
Hide upgrade action menu item if catalog app is latest version.
Disable upgrade-btn if the current version of the app is the latest version of the app.
======
Bugfix
Linked Issues
======
rancher/rancher#26642
rancher/rancher#26661
======
=> Longhorn Bugs

app/catalog-tab/launch/route.js, app/components/cru-persistent-volume/component.js, app/models/app.js, lib/shared/addon/components/upgrade-btn/component.js, lib/shared/addon/components/upgrade-btn/template.hbs
======
When editing a Longhorn PV the component selecting computed property would incorrectly select the CSI driver rather than the Longhorn CSI driver. 
Catalog versions can't be downgraded unless using rollback, filter versions less that current on upgrade.
Hide upgrade action menu item if catalog app is latest version.
Disable upgrade-btn if the current version of the app is the latest version of the app.
======
Bugfix
Linked Issues
======
rancher/rancher#26642
rancher/rancher#26661
======
=> [2.4] Longhorn Bugs

lib/nodes/addon/components/driver-vmwarevsphere/component.js
https://github.com/rancher/rancher/issues/25052
=> adding check for Resources to pull more descriptive label

lib/nodes/addon/components/driver-vmwarevsphere/component.js
=> [2.4] Backport vsphere fixes

lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/utils/util.js
======
Backport node local and extra args changes from https://github.com/rancher/ui/pull/3784 and https://github.com/rancher/ui/pull/3800
======
Linked Issues
======
======
=> [2.3] Backport Nodelocal and related changes

app/models/volume.js
======
When creating a new volume the configName computed property wasn't recomputed
properly because we were not watching all the correct values
======
Bugfix
Linked Issues
======
rancher/rancher#26693
======
=> Longhorn Driver Displayname Bug

app/models/volume.js
======
When creating a new volume the configName computed property wasn't recomputed
properly because we were not watching all the correct values
======
Bugfix
Linked Issues
======
rancher/rancher#26693
======
=> [2.4] Longhorn Driver Displayname Bug

app/application/controller.js, app/application/template.hbs, app/styles/layout/_layout.scss, app/styles/pages/_settings.scss, lib/shared/addon/components/settings-overridable-banner/component.js, lib/shared/addon/components/settings-overridable-banner/template.hbs, lib/shared/addon/components/settings/danger-zone/template.hbs, lib/shared/addon/settings/service.js, lib/shared/addon/utils/constants.js, lib/shared/app/components/settings-overridable-banner/component.js, translations/en-us.yaml
======
Adds new ui-banners feature that exposes a user customizable header and footer banner. 
======
New Feature
Linked Issues
======
rancher/rancher#25694
======
=> Add new ui-banner component

app/application/controller.js, app/application/template.hbs, app/styles/layout/_layout.scss, app/styles/pages/_settings.scss, lib/shared/addon/components/settings-overridable-banner/component.js, lib/shared/addon/components/settings-overridable-banner/template.hbs, lib/shared/addon/components/settings/danger-zone/template.hbs, lib/shared/addon/settings/service.js, lib/shared/addon/utils/constants.js, lib/shared/app/components/settings-overridable-banner/component.js, translations/en-us.yaml
======
Adds new ui-banners feature that exposes a user customizable header and footer banner. 
======
New Feature
Linked Issues
======
rancher/rancher#25694
======
=> [2.4] Add new ui-banner component

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js, lib/shared/addon/components/cluster-driver/driver-amazoneks/template.hbs
======
======
Linked Issues
======
rancher/rancher#26518
======
=> [2.3] Disable Inputs on Edit of EKS Cluster

lib/nodes/addon/components/driver-digitalocean/component.js
======
======
Linked Issues
======
rancher/rancher#26748
======
=> Change default digital ocean node template image

lib/nodes/addon/components/driver-digitalocean/component.js
======
======
Linked Issues
======
rancher/rancher#26748
======
=> [2.4] Change default digital ocean node template image

lib/nodes/addon/components/driver-azure/template.hbs, translations/en-us.yaml
======
Availability Set label now includes managed or unmanaged depending on the disk type selected.
Image includes the following help block below the input `Providing an ARM resource identifier requires using managed disk`
Disk type includes the follow help block below the input, "Creates a unmanaged availability set " or  "Creates a managed availability set", depending on what disk is selected.
======
Documentation 
Linked Issues
======
rancher/rancher#26804
======
=> Provide additional help text for azure node templates

lib/nodes/addon/components/driver-azure/template.hbs, translations/en-us.yaml
======
Availability Set label now includes managed or unmanaged depending on the disk type selected.
Image includes the following help block below the input `Providing an ARM resource identifier requires using managed disk`
Disk type includes the follow help block below the input, "Creates a unmanaged availability set " or  "Creates a managed availability set", depending on what disk is selected.
======
Documentation 
Linked Issues
======
rancher/rancher#26804
======
=> [2.4] Provide additional help text for azure node templates

app/models/app.js, lib/shared/addon/components/upgrade-btn/component.js
======
Roll back a few upgrade btn changes, did not realize that upgrade was used as an edit button of sorts. 
======
Bugfix
Linked Issues
======
rancher/rancher#26810
======
=> Upgrade Btn

app/models/app.js, lib/shared/addon/components/upgrade-btn/component.js, package.json
======
Roll back a few upgrade btn changes, did not realize that upgrade was used as an edit button of sorts. 
======
Bugfix
Linked Issues
======
rancher/rancher#26810
======
=> [2.4] Upgrade Btn

app/components/cru-registry/component.js
======
Not sure this every put registry secrets into the desired namespace. The
`namespaceId` was never set on the primaryResource by the namespace components,
rather those components worked on a namespace object. Ive gotten rid of
`namespaceId` and refactored to use the namespace object in its place.
======
Bugfix
Linked Issues
======
rancher/rancher#26813
======
=> refactor cru-registry ns save logic

app/components/cru-registry/component.js
======
Not sure this every put registry secrets into the desired namespace. The
`namespaceId` was never set on the primaryResource by the namespace components,
rather those components worked on a namespace object. Ive gotten rid of
`namespaceId` and refactored to use the namespace object in its place.
======
Bugfix
Linked Issues
======
rancher/rancher#26864
======
=> [2.3] refactor cru-registry ns save logic

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js
======
set subnets to empty array if it's null until backend fix
======
Bugfix
Linked Issues
======
rancher/rancher#26909
======
=> [2.3] Missing Backport EKS Fixes

app/components/volume-source/source-custom-log-path/template.hbs
======
Users cannot click the button for using custom logging format when use log volume
======
Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/26731
======
=> [Master] Fix log volume format button issue

app/components/container/form-scheduling/component.js, app/models/node.js
======
- The hostname format is `cn-shenzhen.i-x5xxxxxx`. In Rancher, we will take the prefix. But in this case, we need to fallback to use suffix
- Not all node has `hostname` field, but we can use dispalyName field
======
Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/26760
======
=> [Master] Fix node name display issue

app/components/container/form-scheduling/component.js, app/models/node.js
======
- The hostname format is `cn-shenzhen.i-x5xxxxxx`. In Rancher, we will take the prefix. But in this case, we need to fallback to use suffix
- Not all node has `hostname` field, but we can use dispalyName field
======
Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/26760
======
=> [2.4] Fix node name display issue

lib/monitoring/addon/components/system-info-section/component.js, translations/en-us.yaml, translations/zh-hans.yaml
======
The key should be Containerd Version instead of Docker Version if the node is using containerd
======
Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/26857
======
=> Fix dockerVersion display issue

app/models/node.js
======
Fix this case https://github.com/rancher/rancher/issues/26760#issuecomment-626351370
Should fall back to node name if the suffix is number.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/26760
======
=> [2.4.4] Fix node name display issue

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js, lib/shared/addon/components/cluster-driver/driver-amazoneks/template.hbs, translations/en-us.yaml
======
Adds a check to ensure that [on edit users can only upgrade by 1 minor version](https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html#aws-management-console). A help block is also rendered to indicate this as well. 
======
New Feature
Linked Issues
======
rancher/rancher#26908
======
=> Prevent EKS K8s version upgrades > 1 minor version

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js
======
Import for `semver` casing got changed somehow and it was missed. 
======
Bugfix
Linked Issues
======
rancher/rancher#26908
======
=> fix incorrectly cased import

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js
======
Import for `semver` casing got changed somehow and it was missed. 
======
Bugfix
Linked Issues
======
rancher/rancher#26908
======
=> [2.4] fix incorrectly cased import

app/components/container-default-limit/template.hbs
======
The schemas do not reflect a default value and they are nullable. By placing min's on the input we don't allow the user to clear the input if they want and because there are no defaults it doesn't make sense to place these minimums on the inputs.
======
Bugfix
Linked Issues
======
rancher/rancher#27038
======
=> Remove arbitrary limits on container resource limit inputs

lib/global-admin/addon/components/cru-cloud-credential/component.js
======
To ensure that the private keys are no longer present if the model is edited again
======
Bugfix
Linked Issues
======
======
=> Clear Cloud Cred Data On Done

lib/global-admin/addon/components/cru-cloud-credential/component.js
======
To ensure that the private keys are no longer present if the model is edited again
======
Bugfix
Linked Issues
======
======
=> [2.4] Clear Cloud Cred Data On Done

package.json, scripts/build-static
======
======
Linked Issues
======
======
=> Fix bug in drone build

app/components/cru-registry/component.js
======
Object destructuring expects the entire object to be present. When
'Available to all namespaces in this project' is used the namespace
object isn't defined which causes the save to fail due to an null
exception.
======
Linked Issues
======
rancher/rancher#27182
======
=> [backport 2.3] Fix registry credentials so that it doesn't crash 

lib/nodes/addon/components/driver-azure/component.js, lib/nodes/addon/components/driver-azure/template.hbs, translations/en-us.yaml
======
Exposes the NSG parameter on the azure node template config.
======
New Feature
Linked Issues
======
rancher/rancher#26619
======
Backend PR Dependency https://github.com/rancher/machine/pull/77
=> [2.4] Azure Node Template Expose NSG

lib/nodes/addon/components/driver-azure/component.js, lib/nodes/addon/components/driver-azure/template.hbs, translations/en-us.yaml
======
Exposes the NSG parameter on the azure node template config.
======
New Feature
Linked Issues
======
rancher/rancher#26619
======
Backend PR Dependency https://github.com/rancher/machine/pull/77
=> Azure Node Template Expose NSG

app/styles/layout/_medium.scss, server/proxies/api.js
======
Before:
After:
======
Linked Issues
======
======
=> [Master] Fix mobile cluster dropdown issue

app/styles/layout/_medium.scss, server/proxies/api.js
======
Before:
After:
======
Linked Issues
======
======
=> [2.4.4] Fix cluster dropdown style issue on mobile

lib/shared/addon/components/cluster-driver/driver-tencenttke/component.js
======
Add 14.3 and 16.3 options for Tke k8s version selection
======
- New feature
Linked Issues
======
https://github.com/rancher/rancher/issues/27121
======
=> [Master] Add k8s version options  for TKE

lib/shared/addon/components/cluster-driver/driver-tencenttke/component.js
======
Add 14.3 and 16.3 options for Tke k8s version selection
======
- New feature
Linked Issues
======
https://github.com/rancher/rancher/issues/27121
======
=> [2.4.4] Add k8s version options for TKE

lib/shared/addon/oauth/service.js
======
Linked Issues
======
rancher/rancher#27175
=> Removing the scope parameter from github oauth

lib/shared/addon/oauth/service.js
======
Linked Issues
======
rancher/rancher#27175
=> [backport] Removing the scope parameter from github oauth

app/components/page-header-project/component.js
======
Fix project switching issue on mobile
======
Linked Issues
======
======
=> [2.4.4] Fix project switching issue on mobile

app/components/page-header-project/component.js
======
Fix project switching issue on mobile
======
Linked Issues
======
======
=> [Master] Fix project switching issue on mobile

lib/shared/addon/components/storage-class/provisioner-longhorn/component.js
======
The parameters are shown with the known keys but it's
no longer limited to only the known keys. New keys can
be added and they will be sent to the backend as long as
they have values.
======
Linked Issues
======
rancher/rancher#27220
=> Changing Longhorn storage class parameters

lib/shared/addon/components/storage-class/provisioner-longhorn/component.js
======
The parameters are shown with the known keys but it's
no longer limited to only the known keys. New keys can
be added and they will be sent to the backend as long as
they have values.
======
Linked Issues
======
rancher/rancher#27220
=> [backport] Changing Longhorn storage class parameters

app/components/page-header-project/component.js
======
It still doesn't work if users touched the `A` tag.
======
Linked Issues
======
======
=> [2.4.4] Fix project switch issue on mobile

app/components/page-header-project/component.js
======
It still doesn't work if users touched the `A` tag.
======
Linked Issues
======
======
=> [Master] Fix project switch issue on mobile

lib/shared/addon/components/catalog-index/component.js
======
Backport of rancher/rancher#27188
======
Linked Issues
======
======
=> [2.4] Fix JS failure when searching through apps without description

translations/de-de.yaml, translations/es-es.yaml, translations/fr-fr.yaml, translations/it-it.yaml, translations/ja-jp.yaml, translations/ko-kr.yaml, translations/pt-br.yaml, translations/ru-ru.yaml, translations/sh-hr.yaml, translations/tr-tr.yaml, translations/uk-ua.yaml, translations/zh-hans.yaml, translations/zh-hant.yaml
======
Sync approved translations from crowdin.
======
Linked Issues
======
======
=> Translation.sync

translations/de-de.yaml, translations/es-es.yaml, translations/fr-fr.yaml, translations/it-it.yaml, translations/ja-jp.yaml, translations/ko-kr.yaml, translations/pt-br.yaml, translations/ru-ru.yaml, translations/sh-hr.yaml, translations/tr-tr.yaml, translations/uk-ua.yaml, translations/zh-hans.yaml, translations/zh-hant.yaml
======
Sync approved translations from crowdin.
======
Linked Issues
======
======
=> 2.4.translations.sync

lib/login/addon/components/login-saml/component.js, lib/login/addon/login/controller.js, lib/login/addon/login/template.hbs, lib/shared/addon/saml/service.js
======
Updating SAML logins to include a socketId
======
Linked Issues
======
https://github.com/rancherlabs/rancher-security/issues/444
=> Updating SAML logins to include a socketId

lib/login/addon/components/login-saml/component.js, lib/login/addon/login/controller.js, lib/login/addon/login/template.hbs, lib/shared/addon/saml/service.js
======
Updating SAML logins to include a socketId
======
Linked Issues
======
https://github.com/rancherlabs/rancher-security/issues/444
=> [backport] Updating SAML logins to include a socketId

app/models/catalog.js
======
When re-enabling the built in Rancher helm 3 catalog we were not passing the correct version to the api so it wasn't not created as a helm3 catalog. 
======
Bugfix
Linked Issues
======
rancher/rancher#27282
======
=> Re-enable Rancher Helm 3 Catalog Correctly

app/models/catalog.js
======
When re-enabling the built in Rancher helm 3 catalog we were not passing the correct version to the api so it wasn't not created as a helm3 catalog. 
======
Bugfix
Linked Issues
======
rancher/rancher#27282
======
=> [2.4] Re-enable Rancher Helm 3 Catalog Correctly

lib/shared/addon/oauth/service.js
======
The backend is reverting the respective so we're doing the same to stay in line.
======
- Revert
Linked Issues
======
https://github.com/rancher/rancher/pull/27335
=> [backport] Reverting github scope changes

lib/shared/addon/oauth/service.js
======
The backend is reverting the respective so we're doing the same to stay in line.
======
- Revert
Linked Issues
======
https://github.com/rancher/rancher/pull/27335
=> Reverting github scope changes

lib/shared/addon/utils/azure-choices.js
======
Adding missing UAE regions to the list of available Azure regions.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/27370
=> Added UAE regions

lib/shared/addon/utils/azure-choices.js
======
Adding missing UAE regions to the list of available Azure regions.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/27370
=> [2.4] Added UAE regions

app/catalog-tab/launch/route.js
======
Reverting the version filtering added [here](https://github.com/rancher/ui/pull/3920)
======
Linked Issues
======
======
=> [2.4] Revert catalog version filter change

app/catalog-tab/launch/route.js
======
Reverting the version filtering added [here](https://github.com/rancher/ui/pull/3919)
======
Linked Issues
======
======
=> Revert catalog version filter change

lib/nodes/addon/components/driver-digitalocean/component.js
======
======
Linked Issues
======
rancher/rancher#27542
======
=> Add Ubuntu 20.04 LTS to valid images for DO

lib/nodes/addon/components/driver-digitalocean/component.js
======
======
Linked Issues
======
rancher/rancher#27542
======
=> [2.4] Add Ubuntu 20.04 LTS to valid images for DO

lib/shared/addon/components/form-key-value/component.js, lib/shared/addon/components/form-key-value/template.hbs, lib/shared/addon/utils/util.js, translations/en-us.yaml
======
When a editing secret with binary non-UTF-8 data (e.g. pkcs12 encoded cert) the UI will break that data upon save. As we do in dashboard we won't allow users to edit secret data rows that contain non-UTF-8 data. Users can still add and remove rows, included the non-UTF-8 data row.
======
Bugfix
Linked Issues
======
rancher/rancher#27439
======
=> Limit Editable Secret Data

lib/global-admin/addon/security/authentication/template.hbs, translations/en-us.yaml
======
adds a warning banner when auth provider is local clarifying the
permissions and roles you are granting to the external account used
in the configuration process.
======
Enhancement
Linked Issues
======
rancher/rancher#15037
======
=> Clarify Authentication Permissions

lib/global-admin/addon/security/authentication/template.hbs, translations/en-us.yaml
======
adds a warning banner when auth provider is local clarifying the
permissions and roles you are granting to the external account used
in the configuration process.
======
Enhancement
Linked Issues
======
rancher/rancher#15037
======
=> [2.4.6] Clarify Authentication Permissions

app/components/notifier/modal-new-edit/component.js, lib/logging/addon/components/logging/new-edit/component.js
======
Fix bug when `body` is undefined. 
======
Linked Issues
======
https://github.com/rancher/rancher/issues/27695
======
=> Fix logging test bug

lib/shared/addon/components/cluster-driver/driver-rke/component.js
======
adds `extraArgs` cameled string to list since they can come back from the api
this way
======
Bugfix
Linked Issues
======
rancher/rancher#26469
======
Fixed misspelled variable name.
=> Update Cluster Config Yaml Parsing Excluded Keys

lib/shared/addon/components/cluster-driver/driver-rke/component.js
======
adds `extraArgs` cameled string to list since they can come back from the api
this way
======
Bugfix
Linked Issues
======
rancher/rancher#26469
======
Fixed misspelled variable name.
=> [2.4.6] Update Cluster Config Yaml Parsing Excluded Keys

lib/shared/addon/components/form-key-value/component.js
======
We dont show secret data that is non-ascii like. We shouldn't need to encode or decode these values either. This is mucking up the data on edit.  
======
Bugfix
Linked Issues
======
rancher/rancher#27439
======
=> [2.4]Do Not Decode/Encode Non-Asciilike Values

lib/shared/addon/components/form-key-value/component.js
======
We dont show secret data that is non-ascii like. We shouldn't need to encode or decode these values either. This is mucking up the data on edit.  
======
Bugfix
Linked Issues
======
rancher/rancher#27439
======
=> Do Not Decode/Encode Non-Asciilike Values

app/components/notifier/modal-new-edit/component.js, lib/logging/addon/components/logging/new-edit/component.js
======
Backport https://github.com/rancher/ui/pull/4048
Fix bug when `body` is undefined.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/27695
======
=> [2.4] Fix logging test bug

lib/shared/addon/components/marked-down/component.js
======
I saw this while debugging another issue. 
======
Bugfix
Linked Issues
======
======
=> Component Destroyed Error

lib/shared/addon/components/marked-down/component.js
======
I saw this while debugging another issue. 
======
Bugfix
Linked Issues
======
======
=> [2.4] Component Destroyed Error

lib/global-admin/addon/components/form-runasgroup-policy/component.js, lib/global-admin/addon/components/form-runasgroup-policy/template.hbs, lib/global-admin/addon/components/new-edit-policy/template.hbs, translations/en-us.yaml
======
Exposes `RunAsGroup` options on the PSP config.
======
New Feature
Linked Issues
======
rancher/rancher#26827
======
=> PSP's RunAsGroup Config

lib/global-admin/addon/components/form-runasgroup-policy/component.js, lib/global-admin/addon/components/form-runasgroup-policy/template.hbs, lib/global-admin/addon/components/new-edit-policy/template.hbs, translations/en-us.yaml
======
Exposes `RunAsGroup` options on the PSP config.
======
New Feature
Linked Issues
======
rancher/rancher#26827
======
=> [2.4.6] PSP's RunAsGroup Config 

lib/global-admin/addon/components/new-multi-cluster-app/component.js, lib/shared/addon/components/answer-override-row/component.js
======
fetch nested custom answers correctly
add some error checking incase custom answer is missing
======
Bugfix
Linked Issues
======
rancher/rancher#27416
======
=> [2.4.6] MC App Upgrade Error

lib/global-admin/addon/components/new-multi-cluster-app/component.js, lib/shared/addon/components/answer-override-row/component.js
======
fetch nested custom answers correctly
add some error checking incase custom answer is missing
======
Bugfix
Linked Issues
======
rancher/rancher#27416
======
=> MC App Upgrade Error

app/components/cru-registry/component.js
======
Fix regression in creating registry creds. I misunderstood what willSave was doing with the namespaceId when I added the ternary check in a previous fix. I simplified and hopefully clarified what was actually happening when setting temp_id, now use a local flag to set unset the temp namespace, then allow namespace to handle saving or not saving the namespace.
======
Bugfix
Linked Issues
======
rancher/rancher#27769
======
=> [2.3] allow project owners to save reg creds

lib/global-admin/addon/components/feature-flags/component.js, lib/global-admin/addon/components/feature-flags/template.hbs, translations/en-us.yaml
======
======
Linked Issues
======
rancher/rancher#27849
======
=> add additional warning about rancher outage to feature flags

lib/global-admin/addon/components/feature-flags/component.js, lib/global-admin/addon/components/feature-flags/template.hbs, translations/en-us.yaml
======
======
Linked Issues
======
rancher/rancher#27849
======
=> [2.4.6] add additional warning about rancher outage to feature flags

app/components/page-header/component.js, lib/shared/addon/mixins/cattle-transitioning-resource.js
Darren is going to start sending it instead of 'pending'.
Also update the dashboard link when cluster readiness changes.
=> Add in-progress state

lib/shared/addon/components/cluster-driver/driver-rke/component.js
======
Linked Issues
======
rancher/rancher#27333
=> Ensure that the upgradeStrategy.nodeDrainInput.timeout doesn't exceed the min value

lib/shared/addon/components/cluster-driver/driver-rke/component.js
======
Linked Issues
======
rancher/rancher#27333
=> [forwardport] Ensure that the upgradeStrategy.nodeDrainInput.timeout doesn't exceed the min value

lib/shared/addon/components/cluster-driver/driver-eks/component.js, lib/shared/addon/components/cluster-driver/driver-eks/template.hbs
======
======
Linked Issues
======
======
=> small bug fixes for eks v2 kms keys

lib/nodes/addon/components/driver-amazonec2/component.js, lib/nodes/addon/components/driver-amazonec2/template.hbs
======
expose kms secrets on amazon node templates
======
Linked Issues
======
rancher/rancher#27965
======
=> EC2 Node Template KMS Keys/Secrets Encryption

lib/nodes/addon/components/driver-amazonec2/component.js, lib/nodes/addon/components/driver-amazonec2/template.hbs
======
expose kms secrets on amazon node templates
======
Linked Issues
======
rancher/rancher#27965
======
=> [2.4.6] EC2 Node Template KMS Keys/Secrets Encryption

lib/shared/addon/helpers/linkify.js, lib/shared/app/helpers/linkify.js, package.json, yarn.lock
======
======
Linked Issues
======
======
=> Replace URL regex with linkifystr

lib/global-admin/addon/clusters/new/launch/controller.js, lib/global-admin/addon/clusters/new/launch/route.js, lib/global-admin/addon/clusters/new/select/template.hbs, lib/global-admin/addon/clusters/new/template.hbs, lib/shared/addon/components/cru-cluster/template.hbs, translations/en-us.yaml
======
This does not expose any new routes, we're merely distinguishing between a import that we can control (registered) and a import we can't (import).
======
Enhancement
Linked Issues
======
rancher/rancher#28007
======
=> Rework Cluster Import/Register Experience

lib/nodes/addon/components/driver-amazonec2/template.hbs
======
Moved the ec2 kms keys label
======
Bugfix
Linked Issues
======
rancher/rancher#27965
======
=> KMS Keys Bug

lib/shared/addon/utils/amazon.js
Update EKS versions to 1.15, 1.16, 1.17
=> Update EKS version choices

lib/shared/addon/components/cluster-driver/driver-eks/component.js, lib/shared/addon/components/cluster-driver/driver-eks/template.hbs, lib/shared/addon/components/cluster-driver/driver-import-eks/component.js, lib/shared/addon/components/cluster-driver/driver-import-eks/template.hbs, lib/shared/addon/components/node-group-row/template.hbs
======
Fixes a couple small bugs:
Node Groups Tags / Labels always set tags. Was using the setTags function for labels.
Public Access Endpoints were not initializing correctly, pass the correct bool down for formkeyvalue to initialize with empty value.
Register EKS Cluster was incorrectly selecting non-amazon cloud creds.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/28117
https://github.com/rancher/rancher/issues/28124
rancher/rancher#28127
======
=> EKS V2 Bugs

lib/nodes/addon/components/driver-amazonec2/component.js
======
======
Linked Issues
======
rancher/rancher#28146
======
=> Reset KMS Key

lib/nodes/addon/components/driver-amazonec2/component.js
======
======
Linked Issues
======
rancher/rancher#28146
======
=> [2.4] Reset KMS Key

lib/shared/addon/components/cluster-driver/driver-import-eks/component.js
======
Watch the cloud creds to recompute and load new creds
======
Linked Issues
======
rancher/rancher#28174
======
=> EKS V2 Import

lib/nodes/addon/components/driver-amazonec2/component.js, lib/nodes/addon/components/driver-amazonec2/template.hbs, translations/en-us.yaml
======
Add new ec2 metadata http endpoint/tokens props on node template.
======
New Feature
Linked Issues
======
rancher/rancher#28178
======
Sort ec2 nodeTemplate yaml keys.
Fix formatting for ec2 node template handlebars template.
=> EC2 Node Template Metadata Options

lib/nodes/addon/components/driver-amazonec2/component.js, lib/nodes/addon/components/driver-amazonec2/template.hbs, translations/en-us.yaml
======
Add new ec2 metadata http endpoint/tokens props on node template.
======
New Feature
Linked Issues
======
rancher/rancher#28178
======
Sort ec2 nodeTemplate yaml keys.
Fix formatting for ec2 node template handlebars template.
=> [2.4.6] EC2 Node Template Metadata Options

lib/nodes/addon/components/driver-amazonec2/template.hbs
======
Move KMS key markup to correct location on node template.
======
Linked Issues
======
rancher/rancher#28245
======
=> KMS Key Bug

lib/nodes/addon/components/driver-amazonec2/template.hbs
======
Move KMS key markup to correct location on node template.
======
Linked Issues
======
rancher/rancher#28245
======
=> [2.4] KMS Key Bug

lib/shared/addon/components/cluster-driver/driver-eks/template.hbs, translations/en-us.yaml
======
Fixes issue where sg's weren't displaying on create.
Fixes typo in translations.
======
Bugfix
Linked Issues
======
rancher/rancher#28192
======
=> EKS v2 Fixes

app/components/container/form-scale/template.hbs, lib/shared/addon/components/input-integer/component.js
======
Pod scale minimum was incorrectly set to 1. This sets the default back
to 0. Adds a nullible flag to input-int as this is allowed in most cases
where we are using the component. Defaults to false.
Formatting fixes
======
Bugfix
Linked Issues
======
rancher/rancher#28168
======
=> Allow pod scale to be set 0 or null

app/authenticated/cluster/edit/route.js, app/authenticated/cluster/edit/template.hbs, app/models/cluster.js, lib/global-admin/addon/clusters/new/launch/template.hbs, lib/monitoring/addon/components/cluster-dashboard/component.js, lib/shared/addon/components/cluster-driver/driver-eks/template.hbs, translations/en-us.yaml
======
Update cluster model param provider, backend added there own provider param so this just renames the provider to clusterProvider
Tweaks a few labels.
Add help text to eks public private access
======
Bugfix
Linked Issues
======
rancher/rancher#28355
rancher/rancher#28361
rancher/rancher#28369
======
=> Bug: EKSV2

lib/global-admin/addon/clusters/new/launch/template.hbs
======
changed the wrong param provider->clusterProvider, without this fix we can't launch new clusters correctly.
======
Bugfix
Linked Issues
======
rancher/rancher#28355
======
=> Cluster Provider Change Fix

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js
======
update eks versions
======
new feature
Linked Issues
======
https://github.com/rancher/rancher/issues/28385
======
=> Update eks versions 2.3

yarn.lock
======
bumps deps for dot prop alert.
======
Linked Issues
======
======
=> dot prop security update

app/models/cluster.js, lib/global-admin/addon/components/cluster-row/template.hbs, lib/monitoring/addon/components/cluster-dashboard/component.js, lib/monitoring/addon/components/cluster-dashboard/template.hbs, lib/shared/addon/components/cluster-driver/driver-eks/template.hbs, lib/shared/addon/components/node-group-row/component.js, lib/shared/addon/components/node-group-row/template.hbs, lib/shared/addon/components/tooltip-node-group-update/component.js, lib/shared/addon/components/tooltip-node-group-update/template.hbs, lib/shared/app/components/tooltip-node-group-update/component.js, translations/en-us.yaml
======
adds both tooltip warning on cluster row and alert warning on cluster dashboard
version can only be updated on edit when cluster version is different from node group version
all other times we set the node group version to the clusters version
======
New Feature
Linked Issues
======
rancher/rancher#28335
======
Backend Issue that links to backend dependencies: https://github.com/rancher/rancher/issues/27777
=> Expose node group versions on eks v2 node groups

lib/nodes/addon/components/driver-oci/component.js, lib/shared/addon/components/cluster-driver/driver-oracleoke/component.js
======
Update the newly available OKE versions and regions to the OKE and OCI choices manually while we wait for the PRs to pull these values in dynamically to be merged ([OKE](https://github.com/rancher/ui/pull/3953), and [OCI](https://github.com/rancher/ui/pull/3952)).
======
New feature
Linked Issues
======
https://github.com/rancher/rancher/issues/28493
======
=> Update static regions, versions, etc. in OCI and OKE drivers.

translations/en-us.yaml
======
Update register cluster help text to clarify. 
======
Update Text
Linked Issues
======
======
=> Update register cluster help text

lib/shared/addon/settings/service.js
Backport https://github.com/rancher/ui/pull/4136
=> Ensure no exceptions are thrown when handling UI banners

lib/nodes/addon/components/driver-oci/component.js, lib/shared/addon/components/cluster-driver/driver-oracleoke/component.js
======
Update the newly available OKE versions and regions in the **2.4-fixes branch** to the OKE and OCI choices manually while we wait for the PRs to pull these values in dynamically to be merged ([OKE](https://github.com/rancher/ui/pull/3953), and [OCI](https://github.com/rancher/ui/pull/3952)).
======
New feature
Linked Issues
======
https://github.com/rancher/rancher/issues/28493
https://github.com/rancher/ui/pull/4135
======
This PR is just a back-port of [this PR](https://github.com/rancher/ui/pull/4135) into the 2.4-fixes branch.
=> Update static regions, versions, etc. in OCI and OKE drivers in 2.4.

lib/shared/addon/components/cluster-driver/driver-googlegke/component.js
======
A guard was implemented incorrectly, it wasn't appropriately handling
the case where oauthScopes were empty.
======
Linked Issues
======
rancher/rancher#28555
======
Please verify https://github.com/rancher/rancher/issues/19070 wasn't impacted.
=> [backport] Fixing GKE cluster edit

lib/shared/addon/components/cluster-driver/driver-googlegke/component.js
======
A guard was implemented incorrectly, it wasn't appropriately handling
the case where oauthScopes were empty.
======
Linked Issues
======
rancher/rancher#28555
======
Please verify https://github.com/rancher/rancher/issues/19070 wasn't impacted.
=> Fixing GKE cluster edit

app/authenticated/prefs/controller.js, app/authenticated/prefs/template.hbs, app/authenticated/route.js, app/components/modal-edit-setting/template.hbs, app/components/modal-whats-new/component.js, app/components/modal-whats-new/template.hbs, app/components/page-header/template.hbs, app/components/settings/landing-page/component.js, app/components/settings/landing-page/template.hbs, app/components/settings/table-rows/component.js, app/components/settings/table-rows/template.hbs, app/instance-initializers/nav.js, lib/login/addon/login/controller.js, lib/monitoring/addon/index/controller.js, lib/monitoring/addon/index/template.hbs, lib/shared/addon/components/settings/danger-zone/template.hbs, lib/shared/addon/user-theme/service.js, lib/shared/addon/utils/constants.js, translations/en-us.yaml
- Auto theme uses OS theme (rancher/rancher#28561)
- Login to ember or vue pref (rancher/rancher#28534 for the rest of these)
- "What's new" splash screen for 2.5 (needs content)
- "You should use explorer" banner for cluster overview (needs content)
- New products as tools items that link to dashboard
=> Ember<->Vue integration & login

lib/shared/addon/components/cluster-driver/driver-eks/component.js
======
New Node Groups added after edit did not have their version initialized properly. 
======
Bugfix
Linked Issues
======
rancher/rancher#28604
======
=> EKS V2 Node Group Version

app/authenticated/cluster/cis/scan/template.hbs, app/authenticated/dashboard/route.js, app/components/page-footer/component.js, app/components/page-footer/template.hbs, app/components/page-header/component.js, app/components/page-header/template.hbs, app/router.js, app/styles/components/_login.scss, app/update-password/controller.js, app/update-password/template.hbs, lib/logging/addon/components/logging/new-edit/template.hbs, lib/monitoring/addon/components/enable-monitoring/template.hbs, lib/monitoring/addon/index/controller.js, lib/monitoring/addon/index/template.hbs, lib/shared/addon/scope/service.js, translations/en-us.yaml
======
======
Linked Issues
======
======
=> Dashboard bugs

lib/global-admin/addon/components/cru-cloud-credential/component.js, lib/global-admin/addon/components/cru-cloud-credential/template.hbs, lib/nodes/addon/components/driver-oci/component.js, lib/nodes/addon/components/driver-oci/template.hbs, lib/shared/addon/oci/service.js, lib/shared/app/oci/service.js, translations/en-us.yaml
======
This PR adds support for verifying cloud credentials and fetch node-template form values dynamically for the OCI [node driver](https://github.com/rancher-plugins/rancher-machine-driver-oci/).
**Example of invalid OCI credential verification:**
**Example showing node-template form values being fetched dynamically:**
======
Improves usability of OCI cloud-credential and node template creation in a backwards compatible manner. 
Linked Issues
======
- Depends on rancher/rancher#26963
======
Fetching values from the OCI API is a followup from this [review/PR](https://github.com/rancher/ui/pull/3905).
=> Verify OCI cloud credentials and fetch values dynamically from OCI.

app/components/page-header/component.js, app/components/page-header/template.hbs, app/update-password/route.js
======
======
Linked Issues
======
======
=> First login & Dashboard switch bugs

app/update-password/route.js
======
======
Linked Issues
======
======
=> Load all settings instead of explicit list for first login

translations/en-us.yaml
=> Forgot to add a string for the hours units in the Api keys modal

lib/nodes/addon/components/driver-amazonec2/component.js, lib/nodes/addon/components/driver-amazonec2/template.hbs, lib/shared/addon/components/searchable-select/component.js, translations/en-us.yaml
======
Handles the loadKmsKeys call more generically. Prior to this we only displayed the text input for kms keys if the call failed in a specific way but that was too specific. The KMS encryption is not required to create the template so there is no need to throw an error and stop the user from proceeding should the call fail.
======
Bugfix
Linked Issues
======
rancher/rancher#28719
rancher/rancher#28724
======
=> EC2 Node Template KMS Keys Error Handling

lib/shared/addon/components/cluster-driver/driver-eks/component.js, lib/shared/addon/components/cluster-driver/driver-eks/template.hbs, package.json, yarn.lock
======
Handles all kms key errors the same so we dont stop cluster creation if the user doesn't have access to KMS keys.
======
Bugfix
Linked Issues
======
rancher/rancher#28734
======
=> EKS V2 KMS Keys Error Handling

translations/en-us.yaml, translations/zh-hans.yaml
======
Update translation for RKE2 to RKE Federal
======
Translation changes
Linked Issues
======
https://github.com/rancher/rancher/issues/28650
======
Hasn't been tested but it seemed like a simple replacement
=> RKE2 to RKE Federal in translations file

app/models/cluster.js
=> Cluster save completely broken except for EKS

app/components/page-header/component.js, app/components/page-header/template.hbs, app/instance-initializers/nav.js
Move fleet from cluster to global scope
=> Move fleet to global

app/models/cluster.js, lib/shared/addon/components/cluster-driver/driver-eks/component.js
======
- The entire tag collection needs to be sent if it changed
- I noticed that when editing a tag key each letter was added so I resolved that as well
======
Linked Issues
======
rancher/rancher#28949
=> Fixing tags

translations/en-us.yaml
https://github.com/rancher/rancher/issues/29008
=> Update links to direct to the correct product

lib/shared/addon/components/settings/danger-zone/component.js
=> [2.4] Suppress exceptions when parsing JSON setting, default to raw value

lib/shared/addon/components/cluster-driver/driver-azureaks/component.js
Cherry-pick https://github.com/rancher/ui/pull/4163
Issue: https://github.com/rancher/rancher/issues/28880
=> [2.4] AKS only works with lowercase "calico"

lib/nodes/addon/components/driver-oci/component.js
======
This PR updates the available Oracle Linux version to `Oracle Linux 7.8` (7.7 is no longer available on Oracle Cloud) in the UI static map since the 2.4 branch is not yet fetching these types of values [dynamically](https://github.com/rancher/ui/pull/3952).
======
New feature
Linked Issues
======
https://github.com/rancher/rancher/issues/29096
======
=> Update default Oracle Linux to 7.8 in node-template static map.

translations/en-us.yaml
https://github.com/rancher/rancher/issues/29114
=> Update RKE Federal to RKE Government

lib/shared/addon/components/cluster-driver/driver-oracleoke/component.js
======
Adds the newly available OKE version `1.17.9` to the list and makes it the default. These manual updates will continue to be necessary until Rancher 2.5 when they will be fetched [dynamically](https://github.com/rancher/ui/pull/3953).
======
New feature
Linked Issues
======
https://github.com/rancher/rancher/issues/29115
======
=> Update OKE version map to include 1.17.9 (and make it the default) (2.4-fixes)

app/components/modal-whats-new/component.js, app/components/modal-whats-new/template.hbs
The full readme in the what's new modal.
=> What's new text

app/components/input-edit-password/template.hbs, app/components/modal-whats-new/template.hbs, app/styles/components/_forms.scss, app/update-password/controller.js, app/update-password/template.hbs
======
======
Linked Issues
======
======
=> View option

translations/en-us.yaml
https://github.com/rancher/rancher/issues/29192
=> Update in-tree cloud provider info

app/instance-initializers/nav.js, app/models/cluster.js, lib/global-admin/addon/multi-cluster-apps/index/template.hbs, lib/pipeline/addon/components/enable-repositories/component.js, lib/pipeline/addon/components/enable-repositories/template.hbs, lib/pipeline/addon/settings/template.hbs, translations/en-us.yaml
======
Only shows dashboard backup link if we're in local cluster
Some banner link changes
Fix comparison check for node group update check.
======
Linked Issues
======
rancher/rancher#29179
rancher/rancher#29198
rancher/rancher#29180
======
=> 2.5 Bugs/Updates

app/models/cluster.js
======
======
Linked Issues
======
======
=> fix node group check

lib/global-admin/addon/components/cluster-row/template.hbs
======
======
Linked Issues
======
======
=> Dont use scope currentCluster at the global level

app/components/modal-edit-setting/component.js
=> [2.4] Fix frozen settings modal when parsing invalid JSON setting

app/components/new-catalog/template.hbs
Follow up to https://github.com/rancher/ui/pull/4166
Brings the same change into the Project Apps Preview.
=> Cosmetic - project apps preview

lib/monitoring/addon/project-setting/route.js, lib/monitoring/addon/project-setting/template.hbs
======
Displays same warning we added for cluster level. This just go missed. 
======
Bugfix
Linked Issues
======
rancher/rancher#29006
======
=> Monitoring Enabled Warning to Project Monitoring

app/components/modal-whats-new/template.hbs, translations/en-us.yaml
======
======
enhancement
Linked Issues
======
rancher/rancher#29287
======
=> Update fleet references

app/instance-initializers/nav.js
======
comment out rio link as it is hidden in dashboard
======
Linked Issues
======
rancher/rancher#29293
======
=> Remove Rio Nav Link

app/components/page-header/template.hbs, app/instance-initializers/nav.js
======
======
Linked Issues
======
rancher/rancher#29300
======
=> Move continuous delivery from global tools nav -> global nav

lib/global-admin/addon/multi-cluster-apps/index/controller.js, lib/global-admin/addon/multi-cluster-apps/index/template.hbs
======
======
Linked Issues
======
rancher/rancher#29312
======
=> rework when to show multicluster app dep notice

lib/global-admin/addon/components/form-global-roles/component.js, translations/en-us.yaml
======
Move new restricted admin to login access roles
======
Linked Issues
======
rancher/rancher#29315
======
=> Restricted Admin User Roles

translations/en-us.yaml
Part of https://github.com/rancher/rancher/issues/29321
=> Change deprecation messages again.

app/instance-initializers/nav.js
======
======
Linked Issues
======
======
=> Move Continuous Delivery back to global tools

lib/nodes/addon/components/driver-vmwarevsphere/component.js
https://github.com/rancher/rancher/issues/24507
=> [v2.5] Vsphere Resource Pool Sub-Directory Fix

lib/shared/addon/utils/amazon.js
Added new eks version 1.18 and added back version 1.14 as it is not deprecated until december
https://github.com/rancher/rancher/issues/28317
=> added 1.18 and 1.14 eks versions

lib/nodes/addon/components/driver-vmwarevsphere/component.js
https://github.com/rancher/rancher/issues/24507
=> [master] Vsphere Resource Pool Sub-Directory Fix

lib/shared/addon/components/cluster-driver/driver-amazoneks/component.js
Added new eks version 1.18 and added back version 1.14 as it is not deprecated until december
rancher/rancher#28317
=> added version 1.14 and 1.18

app/models/cluster.js
======
ensure eksconfig display name always matches cluster name
======
bugfix
Linked Issues
======
rancher/rancher#29353
======
=> [master] EKS v2 displayName Bug

app/models/cluster.js
======
ensure eksconfig display name always matches cluster name
======
bugfix
Linked Issues
======
rancher/rancher#29353
======
=> [2.5] EKS v2 displayName Bug

app/components/volume-source/source-csi-volume-longhorn/component.js
======
Longhorn driver no longer uses the options key, so use the correct volume attributes key instead. 
======
bug
Linked Issues
======
rancher/rancher#29484
======
=> Longhorn Uses Default Values on View

app/components/page-header-project/component.js, app/components/page-header-project/template.hbs, lib/shared/addon/components/hover-dropdown/component.js
======
Fixes bug where a full-page refresh occurred as a result of clicking the LI in the page-header-project component.
======
Bugfix
Linked Issues
======
N/A
======
=> remove conflicting close action on page-header-project

app/components/page-header-project/component.js, app/components/page-header-project/template.hbs, lib/shared/addon/components/hover-dropdown/component.js
======
Fixes bug where a full-page refresh occurred as a result of clicking the LI in the page-header-project component.
======
Bugfix
Linked Issues
======
N/A
======
=> [2.5] remove conflicting close action on page-header-project

lib/global-admin/addon/templates/-saml-config.hbs, translations/en-us.yaml
======
======
Linked Issues
======
rancher/rancher#29553
======
=> expose new entity id on keycloak

lib/global-admin/addon/templates/-saml-config.hbs, translations/en-us.yaml
======
======
Linked Issues
======
rancher/rancher#29553
======
=> [2.5] expose new entity id on keycloak

lib/logging/addon/components/logging/input-logging-config/component.js, lib/logging/addon/components/logging/new-edit/component.js, lib/logging/addon/components/logging/target-splunk/template.hbs, lib/logging/addon/mixins/parse-fluentd-file.js, lib/shared/addon/utils/constants.js
======
Synchronize logging target base fields when transforming to "Edit as file" view.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/26559
======
=> [v2.4] Synchronize logging form to file

lib/logging/addon/components/logging/input-logging-config/component.js, lib/logging/addon/components/logging/new-edit/component.js, lib/logging/addon/components/logging/target-splunk/template.hbs, lib/logging/addon/mixins/parse-fluentd-file.js, lib/shared/addon/utils/constants.js
======
https://github.com/rancher/rancher/issues/29558
Origin PR: https://github.com/rancher/ui/pull/4214
======
Linked Issues
======
https://github.com/rancher/rancher/issues/29558
======
=> [v2.5] [Forward port] Synchronize logging form to file

lib/logging/addon/components/logging/input-logging-config/component.js, lib/logging/addon/components/logging/new-edit/component.js, lib/logging/addon/components/logging/target-splunk/template.hbs, lib/logging/addon/mixins/parse-fluentd-file.js, lib/shared/addon/utils/constants.js
======
https://github.com/rancher/rancher/issues/29562
Origin PR: https://github.com/rancher/ui/pull/4214
======
Linked Issues
======
https://github.com/rancher/rancher/issues/29562
======
=> [Forward port] Synchronize logging form to file

lib/global-admin/addon/templates/-saml-config.hbs
======
remove required field from keycloak entityId
======
Bugfix
Linked Issues
======
rancher/rancher#29553
======
=> keycloak entityId not required

lib/global-admin/addon/templates/-saml-config.hbs
======
remove required field from keycloak entityId
======
Bugfix
Linked Issues
======
rancher/rancher#29553
======
=> [2.5] keycloak entityId not required

lib/global-admin/addon/components/cru-cloud-credential/component.js, lib/global-admin/addon/components/cru-cloud-credential/template.hbs, lib/nodes/addon/components/driver-oci/component.js, lib/nodes/addon/components/driver-oci/template.hbs, lib/shared/addon/components/cluster-driver/driver-oracleoke/component.js, lib/shared/addon/components/cluster-driver/driver-oracleoke/template.hbs, lib/shared/addon/oci/service.js, lib/shared/app/oci/service.js, translations/en-us.yaml
======
This PR is a backport of of the following two PRs, which update both the OKE cluster driver and OCI node driver to fetch their form values _dynamically_ (regions, shapes, OS, versions, etc.):
- https://github.com/rancher/ui/pull/3953
- https://github.com/rancher/ui/pull/3952
======
Backport of a new feature.
Linked Issues
======
**Depends on:**
- rancher/rancher#29622
Other tracking issues:
- rancher/rancher#27051
- rancher/rancher#29621
======
These changes are already in Rancher v2.5+
**OKE cluster driver populating available OS's dynamically (2.4-fixes branch):**
**OCI node template populating available OS's dynamically (2.4-fixes branch):**
=> [2.4] Populate OKE cluster driver and OCI node driver values dynamically

lib/nodes/addon/components/driver-oci/component.js
======
This PR filters out / hides Oracle-Linux 8.x images from the OCI node template UI until we get OL-8 is working for Docker machine.
Until that point, an OCI cluster will fail to provision if the user selects one of the Oracle-Linux-8.2 images shown.
======
Bugfix
Linked Issues
======
- rancher/rancher#23045
- rancher/rancher#29253
======
=> Filter out OL-8.x images until it is supported by OCI machine driver.

lib/global-admin/addon/multi-cluster-apps/index/controller.js
======
Check for local cluster before checking local cluster id
======
bugfix
Linked Issues
======
rancher/rancher#29636
======
=> Handle MC Apps Index Error

lib/global-admin/addon/multi-cluster-apps/index/controller.js
======
Check for local cluster before checking local cluster id
======
bugfix
Linked Issues
======
rancher/rancher#29636
======
=> [2.5.2] Handle MC Apps Index Error 

translations/en-us.yaml
======
Certificates input was incorrectly labeled CA Cert.
======
Bugfix
Linked Issues
======
rancher/rancher#29734
======
=> Incorrect secret cert labels

translations/en-us.yaml
======
Certificates input was incorrectly labeled CA Cert.
======
Bugfix
Linked Issues
======
rancher/rancher#29734
======
=> [2.5.2] Incorrect secret cert labels

translations/en-us.yaml
======
Backport
======
Bugfix
Linked Issues
======
rancher/rancher#29734
======
=> [2.4] Change incorrect secret cert labels

lib/shared/addon/mixins/store-tweaks.js
======
volatile was deprecated, during the ember 3.12 -> 3.20 upgrade the headers computed property was incorrectly changed to a regular computed property when it should have actually been converted to a native getter as this property is not intended to be tracked.
======
Bugfix
Linked Issues
======
rancher/rancher#29751
======
=> Logout Bug - CSFR not being refetched

lib/shared/addon/components/cluster-driver/driver-azureaks/component.js, lib/shared/addon/components/cluster-driver/driver-azureaks/template.hbs, translations/en-us.yaml
======
New select for loadBalancerSku for AKS clusters. Also rearranged the inputs to make them a bit more cohesive. 
======
New Feature
Linked Issues
======
======
N/A
=> Expose loadBalancerSku on Azure AKS cluster driver

lib/shared/addon/components/cluster-driver/driver-azureaks/component.js, lib/shared/addon/components/cluster-driver/driver-azureaks/template.hbs, translations/en-us.yaml
======
New select for loadBalancerSku for AKS clusters. Also rearranged the inputs to make them a bit more cohesive. 
======
New Feature
Linked Issues
======
======
N/A
=> [2.5.2] Expose loadBalancerSku on Azure AKS cluster driver

lib/shared/addon/components/cluster-driver/driver-azureaks/component.js, lib/shared/addon/components/cluster-driver/driver-azureaks/template.hbs, translations/en-us.yaml
======
New select for loadBalancerSku for AKS clusters. Also rearranged the inputs to make them a bit more cohesive. 
======
New Feature
Linked Issues
======
======
N/A
=> [2.4.9] Expose loadBalancerSku on Azure AKS cluster driver

lib/shared/addon/components/cluster-driver/driver-eks/template.hbs, translations/en-us.yaml
======
======
Linked Issues
======
rancher/rancher#29921
======
=> Disabled EKS public access checkbox

lib/shared/addon/components/cluster-driver/driver-eks/template.hbs, translations/en-us.yaml
======
======
Linked Issues
======
rancher/rancher#29921
======
=> [2.5.2] Disabled EKS public access checkbox

lib/shared/addon/components/cluster-driver/driver-eks/template.hbs, translations/en-us.yaml
======
leave tooltip warning but allow users to enable/disable the checkbox. 
======
Bugfix
Linked Issues
======
rancher/rancher#29921
======
n/a
=> rollback disabling publicAcess on eks

lib/shared/addon/components/cluster-driver/driver-eks/template.hbs, translations/en-us.yaml
======
leave tooltip warning but allow users to enable/disable the checkbox. 
======
Bugfix
Linked Issues
======
rancher/rancher#29921
======
n/a
=> [2.5.2] rollback disabling publicAcess on eks 

lib/shared/addon/components/cluster-driver/driver-azureaks/component.js, lib/shared/addon/components/cluster-driver/driver-azureaks/template.hbs
======
default on the backend was change from `standard` to `""` to alleviate issues with upgrading clusters that didn't have a lb sku before
======
bugfix
Linked Issues
======
======
=> aks create set default loadBalancerSku

lib/shared/addon/components/cluster-driver/driver-azureaks/component.js, lib/shared/addon/components/cluster-driver/driver-azureaks/template.hbs
======
default on the backend was change from `standard` to `""` to alleviate issues with upgrading clusters that didn't have a lb sku before
======
bugfix
Linked Issues
======
======
=> [2.5.2] aks create set default loadBalancerSku

lib/shared/addon/components/cluster-driver/driver-azureaks/component.js, lib/shared/addon/components/cluster-driver/driver-azureaks/template.hbs
======
default on the backend was change from `standard` to `""` to alleviate issues with upgrading clusters that didn't have a lb sku before
======
bugfix
Linked Issues
======
======
=> [2.4.9] aks create set default loadBalancerSku

lib/shared/addon/components/cluster-driver/driver-azureaks/component.js, lib/shared/addon/components/cluster-driver/driver-azureaks/template.hbs
======
for this field anything other than 'standard' is the same as 'basic'
update the ui default to basic, the UI should always send a value not empty string but for clusters created outside the ui or prior to change we will display basic if not standard
======
Linked Issues
======
======
=> Update load balancer sku to be computed to deal with empty value

lib/shared/addon/components/cluster-driver/driver-azureaks/component.js, lib/shared/addon/components/cluster-driver/driver-azureaks/template.hbs
======
for this field anything other than 'standard' is the same as 'basic'
update the ui default to basic, the UI should always send a value not empty string but for clusters created outside the ui or prior to change we will display basic if not standard
======
Linked Issues
======
======
=> [2.5.2] Update load balancer sku to be computed to deal with empty value

lib/shared/addon/components/cluster-driver/driver-azureaks/component.js, lib/shared/addon/components/cluster-driver/driver-azureaks/template.hbs
======
for this field anything other than 'standard' is the same as 'basic'
update the ui default to basic, the UI should always send a value not empty string but for clusters created outside the ui or prior to change we will display basic if not standard
======
Linked Issues
======
======
=> [2.4.9] Update load balancer sku to be computed to deal with empty value

lib/shared/addon/components/cluster-driver/driver-azureaks/component.js
======
set lb sku after config is set so select & config have correct value
======
Linked Issues
======
======
=> AKS LB Sku Bug

lib/shared/addon/components/cluster-driver/driver-azureaks/component.js
======
set lb sku after config is set so select & config have correct value
======
Linked Issues
======
======
=> [2.5.2] AKS LB Sku Bug

lib/shared/addon/components/cluster-driver/driver-azureaks/component.js
======
set lb sku after config is set so select & config have correct value
======
Linked Issues
======
======
=> [2.4.9] AKS LB Sku Bug

app/components/page-footer/template.hbs
======
allow default event pass through so download cli works
======
bugfix
Linked Issues
======
rancher/rancher#29990
======
=> Download CLI Default Action

app/components/page-footer/template.hbs
======
allow default event pass through so download cli works
======
bugfix
Linked Issues
======
rancher/rancher#29990
======
=> [2.5.2] Download CLI Default Action

app/catalog-tab/launch/route.js, lib/global-admin/addon/multi-cluster-apps/catalog/launch/route.js, lib/global-admin/addon/multi-cluster-apps/catalog/launch/template.hbs
======
This fixes a couple bugs in the project and mc app upgrade logic. On project apps when a user clicked upgrade they would be taken to the upgrade page and see the current version of the chart selected. Behind the scenes the upgraded version of the chart was selected but the version key and subsequently the externalId were getting clobbered by the route. Wrapping this check in a !upgrade check prevents version and externalId from getting clobbered by the current version.
Additionally I did some investigation on MC apps and they were facing a similar bug so I added a similar to check to the MC apps. 
======
Bugfix
Linked Issues
======
rancher/rancher#27891
======
N/A
=> Catalog App Upgrade Bugs

lib/shared/addon/components/container-shell/component.js
======
Rather than add a warning the user needs to exit I've added a send to the socket for `exit\r\n` to disconnect the process before the socket closes
======
bugfix
Linked Issues
======
rancher/rancher#16192
======
=> Send exit to container exec on close of container-shell

app/catalog-tab/launch/route.js, lib/global-admin/addon/multi-cluster-apps/catalog/launch/route.js, lib/global-admin/addon/multi-cluster-apps/catalog/launch/template.hbs
======
This fixes a couple bugs in the project and mc app upgrade logic. On project apps when a user clicked upgrade they would be taken to the upgrade page and see the current version of the chart selected. Behind the scenes the upgraded version of the chart was selected but the version key and subsequently the externalId were getting clobbered by the route. Wrapping this check in a !upgrade check prevents version and externalId from getting clobbered by the current version.
Additionally I did some investigation on MC apps and they were facing a similar bug so I added a similar to check to the MC apps. 
======
Bugfix
Linked Issues
======
rancher/rancher#27891
======
N/A
=> [2.5.3] Catalog App Upgrade Bugs

app/catalog-tab/launch/route.js, lib/global-admin/addon/multi-cluster-apps/catalog/launch/route.js, lib/global-admin/addon/multi-cluster-apps/catalog/launch/template.hbs
======
This fixes a couple bugs in the project and mc app upgrade logic. On project apps when a user clicked upgrade they would be taken to the upgrade page and see the current version of the chart selected. Behind the scenes the upgraded version of the chart was selected but the version key and subsequently the externalId were getting clobbered by the route. Wrapping this check in a !upgrade check prevents version and externalId from getting clobbered by the current version.
Additionally I did some investigation on MC apps and they were facing a similar bug so I added a similar to check to the MC apps. 
======
Bugfix
Linked Issues
======
rancher/rancher#27891
======
N/A
=> [2.4.10] Catalog App Upgrade Bugs

app/models/cluster.js, translations/en-us.yaml
======
Exposes the RancherD cluster type on display provider and clusterProvider.
======
New
Linked Issues
======
rancher/rancher#28651
======
=> RancherD Display Provider

app/models/cluster.js, translations/en-us.yaml
======
Exposes the RancherD cluster type on display provider and clusterProvider.
======
New
Linked Issues
======
rancher/rancher#28651
======
=> [2.5.3] RancherD Display Provider

lib/global-admin/addon/components/form-global-roles/component.js, lib/global-admin/addon/security/accounts/new/controller.js, lib/global-admin/addon/security/accounts/new/route.js, lib/global-admin/addon/security/accounts/new/template.hbs
======
If a user was created and the subsequent global role calls failed there was no way to re-save the roles from the create page.
Now if a user creates but the roles fail the creator may select different roles and re-save to create the roles with out creating the new user.
======
Bugfix
Linked Issues
======
rancher/rancher#29315
======
=> Global User Create Error Handling 

lib/shared/addon/utils/azure-choices.js
======
Adding uaecentral and uaenorth to aks regions
======
Linked Issues
======
rancher/rancher#28341
=> Adding uaecentral and uaenorth to aks regions

lib/shared/addon/utils/azure-choices.js
======
Adding uaecentral and uaenorth to aks regions
======
Linked Issues
======
rancher/rancher#28341
=> [forwardport] Adding uaecentral and uaenorth to aks regions

lib/shared/addon/components/cluster-driver/driver-eks/component.js, lib/shared/addon/components/cluster-driver/driver-eks/template.hbs, lib/shared/addon/components/cluster-driver/driver-import-eks/component.js, lib/shared/addon/components/node-group-row/component.js, lib/shared/addon/utils/errors.js, translations/en-us.yaml
======
Updates node group row logic for creating flag to take into account new node groups on an edited cluster.
Update EKS cluster create to make SG's not required and provide a little more guidance about what the selection actually does in v2.
Improve error message util to handle a undefined error better. 
EKS v2 before refetching clusters on Region or Cred change we should clear any errors so the UI loads correctly. 
======
Bugfix
Linked Issues
======
rancher/rancher#29104
rancher/rancher#29431
rancher/rancher#30065
rancher/rancher#30083
======
=> [2.5.4] EKS Bugs

lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, lib/shared/addon/components/modal-show-command/component.js, lib/shared/addon/components/modal-show-command/template.hbs
======
Ensure windows command works in edit and modal show command for custom clusters.
======
bugfix
Linked Issues
======
rancher/rancher#30111
======
=> Custom Clusters Windows Command

lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, lib/shared/addon/components/modal-show-command/component.js, lib/shared/addon/components/modal-show-command/template.hbs
======
Ensure windows command works in edit and modal show command for custom clusters.
======
bugfix
Linked Issues
======
rancher/rancher#30111
======
=> [2.5.x] Custom Clusters Windows Command

lib/global-admin/addon/components/new-edit-role/component.js, lib/global-admin/addon/components/role-rule-row/component.js
======
UI didn't account for nullable fields on a role (global/cluster/project)  
======
bugfix
Linked Issues
======
rancher/rancher#28040
======
=> Global Roles Null Verbs

lib/shared/addon/catalog/service.js
======
Add clusterName qp to fetchTemplate call in order to get a fresh version list of compat k8s version for this cluster
======
new feature
Linked Issues
======
rancher/rancher#29774
======
=> Catalog Template clusterName Filter

lib/shared/addon/catalog/service.js
======
Add clusterName qp to fetchTemplate call in order to get a fresh version list of compat k8s version for this cluster
======
new feature
Linked Issues
======
rancher/rancher#29774
======
=> [2.5.4] Catalog Template clusterName Filter

lib/global-admin/addon/components/new-edit-role/component.js, lib/global-admin/addon/components/role-rule-row/component.js
======
UI didn't account for nullable fields on a role (global/cluster/project)  
======
bugfix
Linked Issues
======
rancher/rancher#28040
======
=> [2.5.4] Global Roles Null Verbs

app/components/cru-persistent-volume/template.hbs, app/components/cru-storage-class/template.hbs, app/models/persistentvolumeclaim.js, app/volumes/index/template.hbs, lib/shared/addon/components/modal-resize-pvc/component.js, lib/shared/addon/components/modal-resize-pvc/template.hbs, lib/shared/app/components/modal-resize-pvc/component.js, translations/en-us.yaml
======
Exposes a new param on the storage class, `Allow Volume Expansion`.
Added pro tip text to the `Edit PV` page for `Capacity` to clarify what editing the capacity does and doesn't do. Only shows on edit of a PV.
Added new `Resize` action to the PVC model that allows a user to open a modal to change the requested capacity. The new modal has similar protip text to, again, help clarify what changing the capacity does. 
======
New Feature
Linked Issues
======
rancher/rancher#27746
======
=> PV and PVC Volume Expansion

app/components/cru-persistent-volume/template.hbs, app/components/cru-storage-class/template.hbs, app/models/persistentvolumeclaim.js, app/volumes/index/template.hbs, lib/shared/addon/components/modal-resize-pvc/component.js, lib/shared/addon/components/modal-resize-pvc/template.hbs, lib/shared/app/components/modal-resize-pvc/component.js, translations/en-us.yaml
======
Exposes a new param on the storage class, `Allow Volume Expansion`.
Added pro tip text to the `Edit PV` page for `Capacity` to clarify what editing the capacity does and doesn't do. Only shows on edit of a PV.
Added new `Resize` action to the PVC model that allows a user to open a modal to change the requested capacity. The new modal has similar protip text to, again, help clarify what changing the capacity does. 
======
New Feature
Linked Issues
======
rancher/rancher#27746
======
=> [2.5.4] PV and PVC Volume Expansion

lib/global-admin/addon/global-dns/providers/new/controller.js, lib/global-admin/addon/global-dns/providers/new/route.js, lib/global-admin/addon/global-dns/providers/new/template.hbs, translations/en-us.yaml
======
Exposes the `additional options` key value entry for the three global dns providers.
======
New Feature
Linked Issues
======
rancher/rancher#30184
======
=> Expose additional options on dns providers

lib/global-admin/addon/global-dns/providers/new/controller.js, lib/global-admin/addon/global-dns/providers/new/route.js, lib/global-admin/addon/global-dns/providers/new/template.hbs, translations/en-us.yaml
======
Exposes the `additional options` key value entry for the three global dns providers.
======
New Feature
Linked Issues
======
rancher/rancher#30184
======
=> [2.5.4] Expose additional options on dns providers

app/models/cluster.js
======
Don't reset the name param from display name for imported clusters.
======
Bugfix
Linked Issues
======
rancher/rancher#30262
======
=> EKS Imported Cluster Name

app/models/cluster.js
======
Don't reset the name param from display name for imported clusters.
======
Bugfix
Linked Issues
======
rancher/rancher#30262
======
=> [2.5.4] EKS Imported Cluster Name

lib/shared/addon/utils/azure-choices.js
=> Removing uae-central since qa hasn't been able to verify

app/models/cluster.js, lib/monitoring/addon/components/cluster-dashboard/template.hbs, lib/shared/addon/components/cluster-driver/driver-eks/component.js, lib/shared/addon/components/cluster-driver/driver-eks/template.hbs, lib/shared/addon/components/cluster-driver/driver-import-eks/component.js, lib/shared/addon/components/cluster-driver/driver-import-eks/template.hbs, lib/shared/addon/components/cluster-driver/driver-import/component.js, lib/shared/addon/components/cluster-driver/driver-import/template.hbs, lib/shared/addon/components/cru-cluster/component.js, lib/shared/addon/components/cru-cluster/template.hbs, lib/shared/addon/components/import-command/component.js, lib/shared/addon/components/modal-show-command/component.js, translations/en-us.yaml
======
On cluster create when the user saves, if the eks cluster has `privateAccess` enabled, the user will be shown the cluster import command. This is the same command we show for the regular import clusters. 
A new action has been exposed for EKS clusters with private access enabled, `Import Host`. Selecting this option will show the cluster registration modal with the import command. The same action exists at the cluster dashboard level. 
On EKS cluster import, the user will be redirected as normal. We can't redirect the user to the import command because we don't know yet if the cluster has private access enabled. We don't know this until the configs have been synced on the backend. The user will have to use the `Import Host` action after the cluster specs sync …
=> Expose Import Command for EKS v2 Clusters with Private Access

app/models/cluster.js, lib/monitoring/addon/components/cluster-dashboard/template.hbs, lib/shared/addon/components/cluster-driver/driver-eks/component.js, lib/shared/addon/components/cluster-driver/driver-eks/template.hbs, lib/shared/addon/components/cluster-driver/driver-import-eks/component.js, lib/shared/addon/components/cluster-driver/driver-import-eks/template.hbs, lib/shared/addon/components/cluster-driver/driver-import/component.js, lib/shared/addon/components/cluster-driver/driver-import/template.hbs, lib/shared/addon/components/cru-cluster/component.js, lib/shared/addon/components/cru-cluster/template.hbs, lib/shared/addon/components/import-command/component.js, lib/shared/addon/components/modal-show-command/component.js, translations/en-us.yaml
======
On cluster create when the user saves, if the eks cluster has `privateAccess` enabled, the user will be shown the cluster import command. This is the same command we show for the regular import clusters. 
A new action has been exposed for EKS clusters with private access enabled, `Import Host`. Selecting this option will show the cluster registration modal with the import command. The same action exists at the cluster dashboard level. 
On EKS cluster import, the user will be redirected as normal. We can't redirect the user to the import command because we don't know yet if the cluster has private access enabled. We don't know this until the configs have been synced on the backend. The user will have to use the `Import Host` action after the cluster specs sync …
=> [2.5.4] Expose Import Command for EKS v2 Clusters with Private Access

lib/global-admin/addon/templates/-ldap-config.hbs, translations/en-us.yaml
======
Exposes the starttls param for ldap auth configurations.
======
New Feature
Linked Issues
======
rancher/rancher#30283
======
Formatting*
=> Expose starttls param for LDAP

lib/global-admin/addon/templates/-ldap-config.hbs, translations/en-us.yaml
======
Exposes the starttls param for ldap auth configurations.
======
New Feature
Linked Issues
======
rancher/rancher#30283
======
Formatting*
=> [2.5.4] Expose starttls param for LDAP

translations/en-us.yaml
======
Small requests for verbiage changes in resize modal
======
Bugfix
Linked Issues
======
rancher/rancher#30316
======
=> PVC resize verbiage changes

translations/en-us.yaml
======
Small requests for verbiage changes in resize modal
======
Bugfix
Linked Issues
======
rancher/rancher#30316
======
=> [2.5.4] PVC resize verbiage changes

app/models/cluster.js, lib/shared/addon/components/cluster-driver/driver-eks/component.js, lib/shared/addon/components/cluster-driver/driver-import-eks/component.js
======
Only show the import command for EKS clusters with privateAccess set true and publicAccess set false.
Redirect users correctly when they don't select privateAccess.
======
Bugfix
Linked Issues
======
rancher/rancher#30332
======
=> Bug EKS Import Command

app/models/cluster.js, lib/shared/addon/components/cluster-driver/driver-eks/component.js, lib/shared/addon/components/cluster-driver/driver-import-eks/component.js
======
Only show the import command for EKS clusters with privateAccess set true and publicAccess set false.
Redirect users correctly when they don't select privateAccess.
======
Bugfix
Linked Issues
======
rancher/rancher#30332
======
=> [2.5.4] Bug EKS Import Command

app/components/cru-persistent-volume-claim/template.hbs, lib/shared/addon/components/resource-condition-list/component.js, lib/shared/addon/components/resource-condition-list/template.hbs
======
Adds condition list to the PVC detail page. 
======
New Feature
Linked Issues
======
rancher/rancher#30319
======
=> Add conditions list to PVC detail page

app/components/cru-persistent-volume-claim/template.hbs, lib/shared/addon/components/resource-condition-list/component.js, lib/shared/addon/components/resource-condition-list/template.hbs
======
Adds condition list to the PVC detail page. 
======
New Feature
Linked Issues
======
rancher/rancher#30319
======
=> [2.5.4] Add conditions list to PVC detail page

lib/shared/addon/utils/azure-choices.js
It looks like the forwardport didn't happen for these two commits.
https://github.com/rancher/rancher/issues/30151
=> [forwardport] UAE

app/models/cluster.js, translations/en-us.yaml
======
This is PR for adding a verbose label for OpenTelekomCloud CCE driver:
https://github.com/rancher/rancher/pull/30286/
======
New feature
Linked Issues
======
rancher/rancher#30286
======
This is a minimal possible change for built-in OTC CCE driver support.
UI component is managed under [opentelekomcloud/ui-cluster-driver-otc](https://github.com/opentelekomcloud/ui-cluster-driver-otc/)
=> Add OTC CCE label translation

app/models/cluster.js, translations/en-us.yaml
======
Update display provider to account for RKE windows
======
New
Linked Issues
======
rancher/rancher#30046
======
=> RKE Windows Display Provider

app/models/cluster.js, translations/en-us.yaml
======
Update display provider to account for RKE windows
======
New
Linked Issues
======
rancher/rancher#30046
======
=> [2.5.4] RKE Windows Display Provider

lib/shared/addon/components/cluster-driver/driver-eks/template.hbs, lib/shared/addon/components/import-command/component.js, lib/shared/addon/components/import-command/template.hbs, lib/shared/addon/components/modal-show-command/template.hbs, translations/en-us.yaml
======
Update import command to remove gke ref's and add banner info for eks
======
Feedback
Linked Issues
======
rancher/rancher#30337
======
=> EKS Import Command Feedback

lib/shared/addon/components/cluster-driver/driver-eks/template.hbs, lib/shared/addon/components/import-command/component.js, lib/shared/addon/components/import-command/template.hbs, lib/shared/addon/components/modal-show-command/template.hbs, translations/en-us.yaml
======
Update import command to remove gke ref's and add banner info for eks
======
Feedback
Linked Issues
======
rancher/rancher#30337
======
=> [2.5.4] EKS Import Command Feedback 

lib/global-admin/addon/templates/-ldap-config.hbs
======
======
Bugfix
Linked Issues
======
rancher/rancher#30283
======
=> Only show starttls on OpenLdap config

lib/global-admin/addon/templates/-ldap-config.hbs
======
======
Bugfix
Linked Issues
======
rancher/rancher#30283
======
=> [2.5.4] Only show starttls on OpenLdap config

lib/shared/addon/catalog/service.js
======
send cluster id instead of cluster name
======
bugfix
Linked Issues
======
rancher/rancher#29774
======
=> Catalog App Version Filter Bug

lib/shared/addon/catalog/service.js
======
send cluster id instead of cluster name
======
bugfix
Linked Issues
======
rancher/rancher#29774
======
=> [2.5.4] Catalog App Version Filter Bug

lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, translations/en-us.yaml
======
======
New Feature
Linked Issues
======
rancher/rancher#30272
======
=> Expose rke ingress defaultBackend param

lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, translations/en-us.yaml
======
======
New Feature
Linked Issues
======
rancher/rancher#30272
======
=> [2.5.4] Expose rke ingress defaultBackend param

lib/shared/addon/components/cru-cluster/component.js
======
When we changed up how the cluster selection and creation was done to account for the provider param there was a bug in HA local clusters that prevented the save and cancel buttons from showing up. 
======
Bugfix
Linked Issues
======
rancher/rancher#30354
======
=> Missing Save/Cancel Buttons Imported Cluster

lib/global-admin/addon/templates/-ldap-config.hbs
======
add starttls view mode of OpenLDAP config page. 
======
Bugfix
Linked Issues
======
rancher/rancher#30359
======
=> OpenLDAP StartTLS View Mode

lib/global-admin/addon/templates/-ldap-config.hbs
======
add starttls view mode of OpenLDAP config page. 
======
Bugfix
Linked Issues
======
rancher/rancher#30359
======
=> [2.5.4] OpenLDAP StartTLS View Mode

lib/shared/addon/components/cluster-driver/driver-rke/component.js
======
After some discussion this original change was reverted. Going forward we will not embed rancher comments in the cluster yaml on edit. 
======
Bugfix
Linked Issues
======
rancher/rancher#28532
======
=> [2.5.4] Edit Yaml Comments Nesting Level

translations/en-us.yaml
======
Requirements clarification.
======
Bugfix
Linked Issues
======
rancher/rancher#30046
======
=> Display windows cluster as Windows not RKE1

translations/en-us.yaml
======
Requirements clarification.
======
Bugfix
Linked Issues
======
rancher/rancher#30046
======
=> [2.5.4] Display windows cluster as Windows not RKE1

app/components/container/form-upgrade-daemon-set/component.js, app/components/container/form-upgrade-stateful-set/component.js
======
undefined error in workload strategy switching because the config hasn't been populated yet
======
bugfix
Linked Issues
======
rancher/rancher#30399
======
=> [2.5.4] Workload Undefined Error

app/components/container/form-upgrade-daemon-set/component.js, app/components/container/form-upgrade-stateful-set/component.js
======
undefined error in workload strategy switching because the config hasn't been populated yet
======
bugfix
Linked Issues
======
rancher/rancher#30399
======
=> Workload Undefined Error

lib/shared/addon/components/cluster-driver/driver-eks/component.js, lib/shared/addon/components/cluster-driver/driver-eks/template.hbs, lib/shared/addon/components/cru-cluster/component.js, lib/shared/addon/components/cru-cluster/template.hbs, lib/shared/addon/components/hover-dropdown/component.js
======
Update eks cluster to redirect when going from pending to active when the cluster is private access only. similar to regular import.
Also disables on edit, the name, members, and labels sections if eks cluster is pending so it doesn't look like you can save. 
======
Bugfix
Linked Issues
======
N/A
======
=> EKS Import Command Bugs

lib/shared/addon/components/cluster-driver/driver-eks/component.js, lib/shared/addon/components/cluster-driver/driver-eks/template.hbs, lib/shared/addon/components/cru-cluster/component.js, lib/shared/addon/components/cru-cluster/template.hbs, lib/shared/addon/components/hover-dropdown/component.js
======
Update eks cluster to redirect when going from pending to active when the cluster is private access only. similar to regular import.
Also disables on edit, the name, members, and labels sections if eks cluster is pending so it doesn't look like you can save. 
======
Bugfix
Linked Issues
======
N/A
======
=> [2.5.4] EKS Import Command Bugs

app/models/cluster.js
======
There was a missed logical else if step for showing the Add Host action. 
======
Bugfix
Linked Issues
======
rancher/rancher#30447
======
=> EKS v2 Add Host modal bug

app/models/cluster.js
======
There was a missed logical else if step for showing the Add Host action. 
======
Bugfix
Linked Issues
======
rancher/rancher#30447
======
=> [2.5.4] EKS v2 Add Host modal bug

package.json, yarn.lock
======
Small security bumps 
======
Linked Issues
======
======
=> security resolutions

package.json, yarn.lock
======
Small security bumps 
======
Linked Issues
======
======
=> [2.5] security resolutions

lib/shared/addon/components/form-labels-annotations/component.js, lib/shared/addon/utils/constants.js
======
The new cattle cluster agent label needs to be available to the end user to edit. 
======
Enhancement
Linked Issues
======
rancher/rancher#30445
======
=> Add explicit exclusion of cattle cluster agent label

lib/shared/addon/components/form-labels-annotations/component.js, lib/shared/addon/utils/constants.js
======
The new cattle cluster agent label needs to be available to the end user to edit. 
======
Enhancement
Linked Issues
======
rancher/rancher#30445
======
=> [2.5.4] Add explicit exclusion of cattle cluster agent label

app/models/cluster.js, lib/shared/addon/components/cluster-driver/driver-eks/component.js
======
I introduced a regression when I refactored the code to check private access. I should have used the double bang to check the truthyness of public access. Also adds provisioning to the pending list.
======
Bugfix
Linked Issues
======
rancher/rancher#30403
======
=> EKS V2 Import Command Not Showing Edit

app/models/cluster.js, lib/shared/addon/components/cluster-driver/driver-eks/component.js
======
I introduced a regression when I refactored the code to check private access. I should have used the double bang to check the truthyness of public access. Also adds provisioning to the pending list.
======
Bugfix
Linked Issues
======
rancher/rancher#30403
======
=> [2.5.4] EKS V2 Import Command Not Showing Edit

lib/shared/addon/mixins/catalog-upgrade.js
======
add projectId to monitoring v1 upgrade calls
======
bugfix
Linked Issues
======
rancher/rancher#30455
======
=> Monitoring V1 Upgrade Bug

lib/shared/addon/mixins/catalog-upgrade.js
======
add projectId to monitoring v1 upgrade calls
======
bugfix
Linked Issues
======
rancher/rancher#30455
======
=> [2.5.4] Monitoring V1 Upgrade Bug

lib/shared/addon/catalog/service.js
======
Backports adding the cluster id to the template get request
======
Enhancement 
Linked Issues
======
rancher/rancher#30504
======
=> [2.4.12] Cluster ID on Template Request

lib/global-admin/addon/global-dns/providers/new/controller.js, lib/global-admin/addon/global-dns/providers/new/route.js, lib/global-admin/addon/global-dns/providers/new/template.hbs, translations/en-us.yaml
======
Backport of rancher/ui#4310
======
Enhancement
Linked Issues
======
rancher/rancher#30197
======
=> [2.4.12] Expose additional options on dns providers

app/styles/layout/_medium.scss, app/styles/pages/_host.scss, lib/global-admin/addon/clusters/new/select/template.hbs, translations/en-us.yaml
======
adds the translation to node driver key which is what is used on in the driver-name helper, this was smaller fix than trying to change the helper to look up an additional key
addresses styling issues from the extra long name and ensures the height is always the same through screen sizes
weird concat spacing issue
======
Linked Issues
======
rancher/rancher#30297
======
=> Ensure OTC CCE driver name shows up correctly on cluster select pages

app/styles/layout/_medium.scss, app/styles/pages/_host.scss, lib/global-admin/addon/clusters/new/select/template.hbs, translations/en-us.yaml
======
adds the translation to node driver key which is what is used on in the driver-name helper, this was smaller fix than trying to change the helper to look up an additional key
addresses styling issues from the extra long name and ensures the height is always the same through screen sizes
weird concat spacing issue
======
Linked Issues
======
rancher/rancher#30297
======
=> [2.5.x] Ensure OTC CCE driver name shows up correctly on cluster select pages

lib/shared/addon/utils/amazon.js
======
1.14 was deprecated this month. 
======
Bugfix
Linked Issues
======
rancher/rancher#30518
======
=> Drop EKS K8s 1.14

lib/shared/addon/utils/amazon.js
======
1.14 was deprecated this month. 
======
Bugfix
Linked Issues
======
rancher/rancher#30518
======
=> [2.5.x] Drop EKS K8s 1.14

lib/global-admin/addon/templates/-ldap-config.hbs, translations/en-us.yaml
=> [2.4] Expose starttls param for LDAP authentication configs

lib/shared/addon/components/container-shell/component.js
======
reorder the calls to fit
use the component method for fit instead of accessing directly in the initial load
wrap calls to fit in next to ensure the modal is rendered before fitting
======
Bugfix
Linked Issues
======
rancher/rancher#30402
======
N/A
=> Xterm Width Issues

lib/shared/addon/components/container-shell/component.js
======
reorder the calls to fit
use the component method for fit instead of accessing directly in the initial load
wrap calls to fit in next to ensure the modal is rendered before fitting
======
Bugfix
Linked Issues
======
rancher/rancher#30402
======
N/A
=> [2.5.X] Xterm Width Issues

app/models/nodetemplate.js
======
Remove dynamicComputeKeyName from node template, it was added to deal with a lint error about not using arrow functions, but it never needed to be added. The watched keys are sufficient dependent keys for the computed property.
======
Bugfix
Linked Issues
======
rancher/rancher#30506
======
=> Node Template Location 

app/models/nodetemplate.js
======
Remove dynamicComputeKeyName from node template, it was added to deal with a lint error about not using arrow functions, but it never needed to be added. The watched keys are sufficient dependent keys for the computed property.
======
Bugfix
Linked Issues
======
rancher/rancher#30506
======
=> [2.5.x] Node Template Location

lib/shared/addon/components/cluster-driver/driver-eks/component.js, lib/shared/addon/components/cluster-driver/driver-eks/template.hbs, lib/shared/addon/components/node-group-row/template.hbs, translations/en-us.yaml
======
Fixes various EKS launch template bugs:
Removes empty set
Adds help text to AMI input
Fixes edit view for pending eks v2 clusters
Fixes edit state of user data in launch template node groups
======
Bugfix
Linked Issues
======
rancher/rancher#31008
rancher/rancher#31032
rancher/rancher#31013
rancher/rancher#31033
======
=> Launch Template Bugs

lib/shared/addon/components/cluster-driver/driver-eks/component.js, lib/shared/addon/components/cluster-driver/driver-eks/template.hbs, lib/shared/addon/components/node-group-row/template.hbs, translations/en-us.yaml
======
Fixes various EKS launch template bugs:
Removes empty set
Adds help text to AMI input
Fixes edit view for pending eks v2 clusters
Fixes edit state of user data in launch template node groups
======
Bugfix
Linked Issues
======
rancher/rancher#31008
rancher/rancher#31032
rancher/rancher#31013
rancher/rancher#31033
======
=> [2.5.x] Launch Template Bugs

lib/shared/addon/components/cluster-driver/driver-eks/component.js
======
Resolving other bugs and I mistaking didn't check the "create" mode and missed this.
======
Bugfix
Linked Issues
======
rancher/rancher#31048
======
=> fix undefined check on eks v2

lib/shared/addon/components/cluster-driver/driver-eks/component.js
======
Resolving other bugs and I mistaking didn't check the "create" mode and missed this.
======
Bugfix
Linked Issues
======
rancher/rancher#31048
======
=> [2.5.x] fix undefined check on eks v2

lib/shared/addon/components/node-group-row/component.js, lib/shared/addon/components/node-group-row/template.hbs, translations/en-us.yaml
======
when requesting spot instances you can not include instance type
======
Bugfix
Linked Issues
======
rancher/rancher#31049
======
=> Launch Template Instance Types Bug

lib/shared/addon/components/node-group-row/component.js, lib/shared/addon/components/node-group-row/template.hbs, translations/en-us.yaml
======
when requesting spot instances you can not include instance type
======
Bugfix
Linked Issues
======
rancher/rancher#31049
======
=> [2.5.x] Launch Template Instance Types Bug

app/models/cluster.js, lib/shared/addon/components/cluster-driver/driver-eks/component.js, lib/shared/addon/components/node-group-row/component.js, lib/shared/addon/components/node-group-row/template.hbs
======
Reset the node group data as the user cycles through different launch templates as well as versions.
Fix create of new node group on cluster edit not able to select launch template. 
======
Linked Issues
======
rancher/rancher#31064
rancher/rancher#31063
======
=> Launch Template Node Group Reset Bugs

app/models/cluster.js, lib/shared/addon/components/cluster-driver/driver-eks/component.js, lib/shared/addon/components/node-group-row/component.js, lib/shared/addon/components/node-group-row/template.hbs
======
Reset the node group data as the user cycles through different launch templates as well as versions.
Fix create of new node group on cluster edit not able to select launch template. 
======
Linked Issues
======
rancher/rancher#31064
rancher/rancher#31063
======
=> [2.5.x] Launch Template Node Group Reset Bugs

app/models/cluster.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, lib/shared/addon/components/form-value-array/component.js, lib/shared/addon/components/modal-show-command/template.hbs, lib/shared/addon/components/node-group-row/component.js, lib/shared/addon/components/node-group-row/template.hbs, translations/en-us.yaml
======
Fixes incorrect eks warning in import command modal
Changes `Add Host` label
Fixes uncapped styles on custom certs for RKE templates
Parse spot instance type from EKS launch template
Do not overwrite node group details when cycling through launch template versions.
======
Bugfix
Linked Issues
======
rancher/rancher#30904
rancher/rancher#30920
rancher/rancher#27165
rancher/rancher#31077
rancher/rancher#31078
======
=> Cluster Create/Edit Bugs

app/models/cluster.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, lib/shared/addon/components/form-value-array/component.js, lib/shared/addon/components/modal-show-command/template.hbs, lib/shared/addon/components/node-group-row/component.js, lib/shared/addon/components/node-group-row/template.hbs, translations/en-us.yaml
======
Fixes incorrect eks warning in import command modal
Changes `Add Host` label
Fixes uncapped styles on custom certs for RKE templates
Parse spot instance type from EKS launch template
Do not overwrite node group details when cycling through launch template versions.
======
Bugfix
Linked Issues
======
rancher/rancher#30904
rancher/rancher#30920
rancher/rancher#27165
rancher/rancher#31077
rancher/rancher#31078
======
=> [2.5.x] Cluster Create/Edit Bugs

app/models/cluster.js
======
======
Bugfix
Linked Issues
======
rancher/rancher#31087
======
=> Subnets can not be undefined

app/models/cluster.js
======
======
Bugfix
Linked Issues
======
rancher/rancher#31087
======
=> [2.5.x] Subnets can not be undefined

translations/en-us.yaml
======
In k8s 1.20 deleteLocalData was renamed deleteEmptyDirData, we wont be updating the api field name but the label is updated to match the new field name. 
======
Bugfix
Linked Issues
======
rancher/rancher#30386
======
=> Update Label for Drain Node Delete Local Data

translations/en-us.yaml
======
In k8s 1.20 deleteLocalData was renamed deleteEmptyDirData, we wont be updating the api field name but the label is updated to match the new field name. 
======
Bugfix
Linked Issues
======
rancher/rancher#30386
======
=> [2.5.x] Update Label for Drain Node Delete Local Data

lib/shared/addon/components/modal-show-command/template.hbs
======
show admin warning for non-eks imports
======
Bugfix
Linked Issues
======
rancher/rancher#30904
======
=> Import Command Warning 

lib/shared/addon/components/modal-show-command/template.hbs
======
show admin warning for non-eks imports
======
Bugfix
Linked Issues
======
rancher/rancher#30904
======
=> [2.5.x] Import Command Warning 

lib/shared/addon/components/custom-command/component.js
======
windows nodes can only be workers, if a user switches to windows and has cp or etcd set we need to set it to false
======
bugfix
Linked Issues
======
rancher/rancher#30903
======
=> custom cluster command set etcd/cp false if windows

lib/nodes/addon/components/driver-amazonec2/component.js, lib/shared/addon/components/form-engine-opts/component.js, lib/shared/addon/components/form-engine-opts/template.hbs, translations/en-us.yaml
======
add 'None' option to docker install url for node templates
adds warning for 'None' option
commented out some consoles
======
New Feature
Linked Issues
======
rancher/rancher#30895
======
=> Docker Install URL Options

lib/nodes/addon/components/driver-amazonec2/component.js, lib/shared/addon/components/form-engine-opts/component.js, lib/shared/addon/components/form-engine-opts/template.hbs, translations/en-us.yaml
======
add 'None' option to docker install url for node templates
adds warning for 'None' option
commented out some consoles
======
New Feature
Linked Issues
======
rancher/rancher#30895
======
=> [2.5.x] Docker Install URL Options

lib/shared/addon/utils/constants.js, translations/en-us.yaml
======
ui-offline-preferred affects the ui-index so there is no reason to not expose it as well
======
Linked Issues
======
n/a
======
=> expose ui-offline-preferred and dashboard-index

lib/shared/addon/utils/constants.js, translations/en-us.yaml
======
ui-offline-preferred affects the ui-index so there is no reason to not expose it as well
======
Linked Issues
======
n/a
======
=> [2.5.x] expose ui-offline-preferred and dashboard-index

lib/shared/addon/components/form-engine-opts/component.js
======
the value in the ticket was incorrect, should have been `none`
======
bugfix
Linked Issues
======
rancher/rancher#30895
======
=> Update Install Engine URL Value

app/models/cluster.js
======
When transitioning to the edit route we need to ensure a config exists before showing the cru-cluster component that lets you edit. 
======
Bugfix
Linked Issues
======
rancher/rancher#30977
======
=> Prevent Edit of Clusters without Config

app/models/cluster.js
======
When transitioning to the edit route we need to ensure a config exists before showing the cru-cluster component that lets you edit. 
======
Bugfix
Linked Issues
======
rancher/rancher#30977
======
=> [2.5.x] Prevent Edit of Clusters without Config

lib/global-admin/addon/components/cru-cloud-credential/component.js, lib/global-admin/addon/components/cru-cloud-credential/template.hbs, lib/nodes/addon/components/driver-vmwarevsphere/component.js
======
Changing how we reset values when switching credentials for vsphere node templates
======
Linked Issues
======
rancher/rancher#30690
=> Changing how we reset values when switching credentials for vsphere node templates

lib/shared/addon/components/node-group-row/component.js
======
prevented the correct choice from being selected on init.
======
bugfix
Linked Issues
======
rancher/rancher#31146
======
=> Launch Template version was not correct type

lib/shared/addon/components/node-group-row/component.js
======
prevented the correct choice from being selected on init.
======
bugfix
Linked Issues
======
rancher/rancher#31146
======
=> [2.5.x] Template version was not correct type

app/models/node.js
======
Change node `displayName` to actually return the prefix (unique data) of a node that has siblings with the same domain in the name.
======
Linked Issues
======
rancher/rancher#27873
======
see https://github.com/rancher/ui/pull/4415
=> [2.5.x] display prefix of node name (drop domain)

app/models/cluster.js, app/models/nodegroup.js, lib/shared/addon/components/cluster-driver/driver-eks/component.js, lib/shared/addon/components/cluster-driver/driver-eks/template.hbs, lib/shared/addon/components/node-group-row/component.js, lib/shared/addon/components/node-group-row/template.hbs, lib/shared/addon/components/textarea-autogrow/component.js, translations/en-us.yaml
======
The bulk of this PR is reworking the spot instance ux. Spot instance types are now required if a user selects `Request Spot Instances` and the `Instance Type` input will be replaced with static text indicating a user needs to include spot instance types. 
Adds better error handling for failures during cluster creation so we dont replace the active model with new data when we error out. This caused an observer to fire in the node-group-row component that would reset the node group config to defaults. So in addition to not replacing the model I've added some logic to ensure the cluster isn't saving or just saved (when we replace data on success).
Also fixed another error where user data wasn't being synced as a result of fixing the above issue.
Improves logic used …
=> Launch Template UX Updates

app/models/cluster.js, app/models/nodegroup.js, lib/shared/addon/components/cluster-driver/driver-eks/component.js, lib/shared/addon/components/cluster-driver/driver-eks/template.hbs, lib/shared/addon/components/node-group-row/component.js, lib/shared/addon/components/node-group-row/template.hbs, lib/shared/addon/components/textarea-autogrow/component.js, translations/en-us.yaml
======
The bulk of this PR is reworking the spot instance ux. Spot instance types are now required if a user selects `Request Spot Instances` and the `Instance Type` input will be replaced with static text indicating a user needs to include spot instance types. 
Adds better error handling for failures during cluster creation so we dont replace the active model with new data when we error out. This caused an observer to fire in the node-group-row component that would reset the node group config to defaults. So in addition to not replacing the model I've added some logic to ensure the cluster isn't saving or just saved (when we replace data on success).
Also fixed another error where user data wasn't being synced as a result of fixing the above issue.
Improves logic used …
=> [2.5.x] Launch Template UX Updates

app/models/node.js, translations/en-us.yaml
adds node context scale down button and multiselect button for node scaledown action.
https://github.com/rancher/rancher/issues/22871
=> adding scale down buttons

app/styles/components/_node-group-row.scss, lib/shared/addon/components/form-value-array/component.js, lib/shared/addon/components/form-value-array/template.hbs, lib/shared/addon/components/node-group-row/template.hbs, translations/en-us.yaml
======
Updates the translation for Image ID to AMI ID.
Updates the spot instance type select input widths to fill empty space. 
======
Enhancement 
Linked Issues
======
https://github.com/rancher/rancher/issues/31341
https://github.com/rancher/rancher/issues/31322
======
N/A
=> EKS V2 NG Enhancements

app/styles/components/_node-group-row.scss, lib/shared/addon/components/form-value-array/component.js, lib/shared/addon/components/form-value-array/template.hbs, lib/shared/addon/components/node-group-row/template.hbs, translations/en-us.yaml
======
Updates the translation for Image ID to AMI ID.
Updates the spot instance type select input widths to fill empty space. 
======
Enhancement 
Linked Issues
======
https://github.com/rancher/rancher/issues/31341
https://github.com/rancher/rancher/issues/31322
======
N/A
=> [2.5.x] EKS V2 NG Enhancements

lib/shared/addon/components/cru-node-pools/component.js, lib/shared/addon/components/cru-node-pools/template.hbs, lib/shared/addon/components/node-pool-row/template.hbs, translations/en-us.yaml
======
expose drainBeforeDelete option on node pools
======
new feature
Linked Issues
======
rancher/rancher#31308
======
Also formatted the HBS file.
=> Node Pools - drainBeforeDelete

lib/shared/addon/components/cru-node-pools/component.js, lib/shared/addon/components/cru-node-pools/template.hbs, lib/shared/addon/components/node-pool-row/template.hbs, translations/en-us.yaml
======
expose drainBeforeDelete option on node pools
======
new feature
Linked Issues
======
rancher/rancher#31308
======
Also formatted the HBS file.
=> [2.5.x] Node Pools - drainBeforeDelete

lib/logging/addon/components/logging/new-edit/component.js, lib/logging/addon/components/logging/target-flentd/component.js
======
Another sync issue when creating the logging target from the yaml custom entry first then going back to the form. 
======
Bugfix
Linked Issues
======
rancher/rancher#31149
======
=> ensure on the round trip back to logging form edit that fields update

lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/utils/util.js
======
Add dns options to excluded keys to camel list
======
enhancement
Linked Issues
======
rancher/rancher#31230
======
Organized imports.
=> YAML DNS Options

lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/utils/util.js
======
Add dns options to excluded keys to camel list
======
enhancement
Linked Issues
======
rancher/rancher#31230
======
Organized imports.
=> [2.5.x] YAML DNS Options

lib/logging/addon/components/logging/new-edit/component.js, lib/logging/addon/components/logging/target-flentd/component.js
======
Another sync issue when creating the logging target from the yaml custom entry first then going back to the form. 
======
Bugfix
Linked Issues
======
rancher/rancher#31149
======
=> [2.5.x] ensure on the round trip back to logging form edit that fields update

lib/global-admin/addon/templates/-saml-config.hbs
======
expose entityId on Ping auth provider
======
New Feature
Linked Issues
======
rancher/rancher#31287
======
=> Ping entityId

lib/global-admin/addon/templates/-saml-config.hbs
======
expose entityId on Ping auth provider
======
New Feature
Linked Issues
======
rancher/rancher#31287
======
=> [2.5.x] Ping entityId

lib/shared/addon/components/form-engine-opts/component.js
======
======
enhancement
Linked Issues
======
rancher/rancher#31340
======
=> remove docker 1.13 from eng options

lib/shared/addon/components/form-engine-opts/component.js
======
======
enhancement
Linked Issues
======
rancher/rancher#31340
======
=> [2.5.x] remove docker 1.13 from nt eng options

lib/shared/addon/components/node-group-row/component.js
======
allow set on managed fields with a rancher launch templates
======
bugfix
Linked Issues
======
rancher/rancher#31415
======
=> Bug EKS LT Rancher Managed Template

lib/shared/addon/components/node-group-row/component.js
======
allow set on managed fields with a rancher launch templates
======
bugfix
Linked Issues
======
rancher/rancher#31415
======
=> [2.5.x] Bug EKS LT Rancher Managed Template

lib/global-admin/addon/components/cru-cloud-credential/component.js, lib/global-admin/addon/components/cru-cloud-credential/template.hbs, lib/nodes/addon/components/driver-oci/component.js, lib/nodes/addon/components/driver-oci/template.hbs, lib/shared/addon/components/cluster-driver/driver-oracleoke/component.js, lib/shared/addon/components/cluster-driver/driver-oracleoke/template.hbs, lib/shared/addon/utils/oci.js, translations/en-us.yaml
======
This PR is a back-port of of the following two PRs:
- https://github.com/rancher/ui/pull/4249
- https://github.com/rancher/ui/pull/4324
======
Backport of two small, but important bug-fixes.
Linked Issues
======
======
=> [2.5] backport support for custom boot-volume sizes, oCPUs, static region list

lib/shared/addon/components/cru-cloud-provider/component.js, lib/shared/addon/components/cru-cloud-provider/template.hbs, translations/en-us.yaml
======
These are feature change requests to the new in/out-of-tree messaging we recently added.
======
Linked Issues
======
https://github.com/rancher/rancher/issues/31162#issuecomment-783636347
https://github.com/rancher/rancher/issues/31162#issuecomment-783638299
=> Removing in-tree deprecating messaging and adding out-of-tree indicator

lib/shared/addon/components/cluster-driver/driver-oracleoke/component.js, lib/shared/addon/components/cluster-driver/driver-oracleoke/template.hbs, translations/en-us.yaml
======
This PR is a back-port of of the following PR:
- https://github.com/rancher/ui/pull/4249
======
Backport of additional functionality supported by driver.
Linked Issues
======
**Depends on:**
- rancher/rancher#31429
======
=> [2.4] backport support for custom boot-volume sizes and oCPUs

translations/en-us.yaml
======
Add in additional text to clarify that each role is required for a cluster
======
Translation Change
Linked Issues
======
Required in order to identify why this issue exists: https://github.com/rancher/rancher/issues/31244
======
=> Update cluster node options text

app/authenticated/cluster/edit/route.js, lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, lib/shared/addon/components/form-agent-env-var/component.js, lib/shared/addon/components/form-agent-env-var/template.hbs, lib/shared/addon/components/new-select/component.js, lib/shared/addon/components/new-select/template.hbs, lib/shared/app/components/form-agent-env-var/component.js, translations/en-us.yaml
======
Adding the agent env vars to rke drivers.
======
Linked Issues
======
rancher/rancher#31023
=> Adding the agent env vars to rke drivers.

app/models/node.js
======
Disable node scale down action when the node is the last node in pool.
======
Bugfix
Linked Issues
======
rancher/rancher#31424
======
=> Scale Down UX Improvements

app/models/node.js
======
Disable node scale down action when the node is the last node in pool.
======
Bugfix
Linked Issues
======
rancher/rancher#31424
======
=> [2.5.x] Scale Down UX Improvements

app/models/node.js
======
account for missing actions links object on can scale check
======
bugfix
Linked Issues
======
rancher/rancher#31452
======
=> Scale Down Undefined Bug

app/models/node.js
======
account for missing actions links object on can scale check
======
bugfix
Linked Issues
======
rancher/rancher#31452
======
=> [2.5.x] Scale Down Undefined Bug

app/authenticated/cluster/edit/route.js, lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, lib/shared/addon/components/cru-cluster/component.js, lib/shared/addon/components/cru-cluster/template.hbs, lib/shared/addon/components/form-agent-env-var/component.js
======
- Fixed issues with determining the provider when editing clusters that are still provisioning.
- Fixed empty values causing problems
- Fixed an issue where the default value wasn't getting set properly for configmaps and secrets when selecting the type and nothing else
- Adding agent env vars to import cluster
======
Linked Issues
======
https://github.com/rancher/rancher/issues/31023#issuecomment-784717552
rancher/rancher#31505
=> Fixing several issues with agentEnvVars/adding to import cluster

app/authenticated/cluster/edit/route.js, lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, lib/shared/addon/components/cru-cluster/component.js, lib/shared/addon/components/cru-cluster/template.hbs, lib/shared/addon/components/form-agent-env-var/component.js, lib/shared/addon/components/form-agent-env-var/template.hbs
======
After some discussions we decided to simplify things since all that's actually needed are keyValues.
======
Linked Issues
======
rancher/rancher#31545
=> Switching over to having the envVars just be keyValues

app/authenticated/cluster/edit/route.js, lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, lib/shared/addon/components/cru-cluster/component.js, lib/shared/addon/components/cru-cluster/template.hbs, lib/shared/addon/components/form-agent-env-var/component.js, lib/shared/addon/components/form-agent-env-var/template.hbs
======
After some discussions we decided to simplify things since all that's actually needed are keyValues.
======
Linked Issues
======
rancher/rancher#31545
=> [backport] Switching over to having the envVars just be keyValues

lib/shared/addon/components/cru-cloud-provider/template.hbs, translations/en-us.yaml
======
Updating the verbiage of the vsphere out-of-tree messaging
======
Linked Issues
======
none
=> Updating the verbiage of the vsphere out-of-tree messaging

lib/shared/addon/components/cru-cloud-provider/template.hbs, translations/en-us.yaml
======
Updating the verbiage of the vsphere out-of-tree messaging
======
Linked Issues
======
none
=> [backport] Updating the verbiage of the vsphere out-of-tree messaging

translations/en-us.yaml
=> [backport] We had a doc url change

translations/en-us.yaml
=> We had a doc url change

lib/istio/addon/components/istio-nav/component.js
related https://github.com/rancher/rancher/issues/30990
=> Bugfix link in local cluster

lib/shared/addon/oauth/service.js
fixes the regex used for url-safe base64 encoding
=> fix base64 encode/decode url regex

app/instance-initializers/nav.js, lib/istio/addon/cluster-setting/route.js
======
Hide monitoring link on isActive condition. Hides istio for some condition and removes redirect to cluster index when cluster is not ready and user clicks istio (just don't show it)
======
bugfix
Linked Issues
======
rancher/rancher#29234
======
=> Cluster Monitoring 503

app/instance-initializers/nav.js, lib/istio/addon/cluster-setting/route.js
======
Hide monitoring link on isActive condition. Hides istio for some condition and removes redirect to cluster index when cluster is not ready and user clicks istio (just don't show it)
======
bugfix
Linked Issues
======
rancher/rancher#29234
======
=> [2.5.x] Cluster Monitoring 503

app/models/cloudcredential.js, lib/global-admin/addon/components/cru-cloud-credential/component.js, lib/global-admin/addon/components/cru-cloud-credential/template.hbs, lib/shared/addon/components/input-text-file/template.hbs
======
Exposes the new Google cloud credential. The new cloud cred is only useful with the incoming GKE v2 cluster provisioning UX. 
======
New Feature
Linked Issues
======
rancher/rancher#31346
======
=> Google Cloud Credentials

package.json, yarn.lock
======
======
Linked Issues
======
======
=> Dependency Updates

package.json, yarn.lock
======
======
Linked Issues
======
======
=> update ember api store for some security vuln

lib/login/addon/login/controller.js
======
We were attempting to access `const` before declaration which threw an error and hosed up the redirect from login.
======
Bugfix
Linked Issues
======
N/A
======
=> Redirect Login Bug

lib/login/addon/login/controller.js
======
We were attempting to access `const` before declaration which threw an error and hosed up the redirect from login.
======
Bugfix
Linked Issues
======
N/A
======
=> [2.5.x] Redirect Login Bug

lib/shared/addon/components/node-group-row/component.js
======
======
Ensure that instance type is set null when using a launch template that has spot instances enabled. 
Linked Issues
======
rancher/rancher#31908
======
=> EKS V2 LT Spot Instances Bug

lib/shared/addon/components/node-group-row/component.js
======
======
Ensure that instance type is set null when using a launch template that has spot instances enabled. 
Linked Issues
======
rancher/rancher#31908
======
=> [2.5.x] EKS V2 LT Spot Instances Bug

translations/de-de.yaml, translations/en-us.yaml, translations/es-es.yaml, translations/ja-jp.yaml, translations/ru-ru.yaml, translations/uk-ua.yaml, translations/zh-hans.yaml, translations/zh-hant-tw.yaml, translations/zh-hant.yaml
======
======
Translations change
Linked Issues
======
rancher/rancher#31845
======
=> [2.5.x] Change all refs Aliyun to Alicloud

translations/de-de.yaml, translations/en-us.yaml, translations/es-es.yaml, translations/ja-jp.yaml, translations/ru-ru.yaml, translations/uk-ua.yaml, translations/zh-hans.yaml, translations/zh-hant-tw.yaml, translations/zh-hant.yaml
======
======
translations change
Linked Issues
======
rancher/rancher#31845
======
=> Change all refs Aliyun to Alicloud

app/models/cluster.js, lib/shared/addon/components/cluster-driver/driver-import/component.js, lib/shared/addon/components/cluster-driver/driver-import/template.hbs, lib/shared/addon/components/cru-cluster/component.js
======
Added extra logic for excluding docker cluster from edit/upgrade as k3s clusters that do not have a config should not allow editing of items on the config. A null k3s config indicates a docker installed cluster so I've added extra logic to check if the config exists and if it does not we don't show the manage import cluster info component.
I also added logic to the final save method in cru cluster to only show the registration step if the cluster is pending
and not a null k3s config.
======
Bugfix
Linked Issues
======
rancher/rancher#30977
======
=> Edit Local Cluster Bugs

app/models/cluster.js, lib/shared/addon/components/cluster-driver/driver-import/component.js, lib/shared/addon/components/cluster-driver/driver-import/template.hbs, lib/shared/addon/components/cru-cluster/component.js
======
Added extra logic for excluding docker cluster from edit/upgrade as k3s clusters that do not have a config should not allow editing of items on the config. A null k3s config indicates a docker installed cluster so I've added extra logic to check if the config exists and if it does not we don't show the manage import cluster info component.
I also added logic to the final save method in cru cluster to only show the registration step if the cluster is pending
and not a null k3s config.
======
Bugfix
Linked Issues
======
rancher/rancher#30977
======
=> [2.5.x] Edit Local Cluster Bugs

app/models/cloudcredential.js, lib/global-admin/addon/components/cru-cloud-credential/component.js, lib/global-admin/addon/components/cru-cloud-credential/template.hbs, lib/shared/addon/components/input-text-file/template.hbs
======
Exposes the new Google cloud credential. The new cloud cred is only useful with the incoming GKE v2 cluster provisioning UX. 
======
New Feature
Linked Issues
======
rancher/rancher#31346
======
Hold until https://github.com/rancher/rancher/pull/31680 is in.
=> [2.5.x] Google GCP cloud credentials

lib/shared/addon/components/cluster-driver/driver-gke/component.js, lib/shared/addon/components/cluster-driver/driver-gke/template.hbs
======
Fixes the wrong conditional check for post save and private clusters
======
Linked Issues
======
======
=> fix import command for gke v2 private cluster

lib/shared/addon/components/cluster-driver/driver-gke/component.js, lib/shared/addon/components/cluster-driver/driver-gke/template.hbs
======
fix import command for gke v2 private cluster
======
Linked Issues
======
======
=> [2.5.x] fix import command for gke v2 private cluster

app/models/cluster.js, lib/global-admin/addon/components/cru-cloud-credential/component.js, lib/shared/addon/components/cluster-driver/driver-gke/component.js, lib/shared/addon/components/cluster-driver/driver-googlegke/component.js, lib/shared/addon/components/cluster-driver/driver-import-gke/component.js, lib/shared/addon/components/cluster-driver/driver-import-gke/template.hbs, lib/shared/addon/components/cru-private-cluster/template.hbs, translations/en-us.yaml
======
Handle invalid json for GKE cloud creds.
Update location observer watch list to prevent conflicts that caused value to get overwritten.
Add masterIpv4CidrBlock validator.
Remove logic that auto-sets secondary range names on gke cluster.
Update secondary range dropdowns when subnet updates .
======
Bugfixes
Linked Issues
======
rancher/rancher#32020
rancher/rancher#32044
rancher/rancher#32032
rancher/rancher#32046
rancher/rancher#27696
======
=> [2.5.x] GKE Bugs

app/models/cluster.js, lib/global-admin/addon/components/cluster-row/template.hbs, lib/shared/addon/components/gke-node-pool-row/component.js, lib/shared/addon/components/tooltip-node-group-update/template.hbs, translations/en-us.yaml
======
Fixes a bug in node version upgrade where the node was always set to latest version regardless.
Also fixes a label on the upgrade warning to indicate node pools instead of node groups.
======
Bugfix
Linked Issues
======
======
=> [2.5.x] node version update bugs

app/models/cluster.js, lib/global-admin/addon/components/cluster-row/template.hbs, lib/shared/addon/components/gke-node-pool-row/component.js, lib/shared/addon/components/tooltip-node-group-update/template.hbs, translations/en-us.yaml
======
Fixes a bug in node version upgrade where the node was always set to latest version regardless.
Also fixes a label on the upgrade warning to indicate node pools instead of node groups.
======
Bugfix
Linked Issues
======
======
=> node version update bugs 

app/models/cluster.js
======
Show registration command for custom and imported clusters regardless of node count.
======
Bug
Linked Issues
======
rancher/rancher#31529
rancher/rancher#32031
======
=> [2.5.x] Show Registration Command Bugs

app/models/cluster.js
======
Show registration command for custom and imported clusters regardless of node count.
======
Bug
Linked Issues
======
rancher/rancher#31529
rancher/rancher#32031
======
=> Show Registration Command Bugs

lib/shared/addon/components/gke-node-pool-row/component.js
======
======
Bugfx
Linked Issues
======
======
=> [2.5.x] fix missing node version on a new node pool for gke

lib/shared/addon/components/gke-node-pool-row/component.js
======
======
bugfix
Linked Issues
======
======
=> fix missing node version on a new node pool for gke

lib/shared/addon/components/cluster-driver/driver-eks/component.js, lib/shared/addon/components/cluster-driver/driver-eks/template.hbs, lib/shared/addon/components/node-group-row/component.js, translations/en-us.yaml
======
Adds fix for an undefined error when getting market types off of a launch template that does not have this param.
Adds fix to display the correct subnets and security groups or a message about rancher auto created if none are present on edit of EKS v2 cluster. 
======
Bugfix
Linked Issues
======
rancher/rancher#32004
rancher/rancher#32057
======
=> [2.5.x] EKS Bugs

lib/shared/addon/components/cluster-driver/driver-gke/component.js, lib/shared/addon/components/form-gke-taints/component.js, lib/shared/addon/components/form-gke-taints/template.hbs, lib/shared/addon/components/gke-node-pool-row/component.js, lib/shared/addon/components/gke-node-pool-row/template.hbs, lib/shared/addon/version-choices/service.js
======
Fixes an Error on create where the node version would not update when selecting a new master version.
Fixes an error with some data mapping in the node pools taints row.
Fixes an error where the node version upgrade checkbox would not show when upgrading the cluster version, they can occur at the same time.
Adds some better logic to handle the semver list and ranges, including versioning our previous cloud provider parser to make it more robust and native to library implementation  
======
Bugfix
Linked Issues
======
rancher/rancher#32143
======
=> [2.5.x] GKE V2 Node Version Bugs

lib/shared/addon/components/cluster-driver/driver-gke/component.js, lib/shared/addon/components/form-gke-taints/component.js, lib/shared/addon/components/form-gke-taints/template.hbs, lib/shared/addon/components/gke-node-pool-row/component.js, lib/shared/addon/components/gke-node-pool-row/template.hbs, lib/shared/addon/version-choices/service.js
======
Fixes an Error on create where the node version would not update when selecting a new master version.
Fixes an error with some data mapping in the node pools taints row.
Fixes an error where the node version upgrade checkbox would not show when upgrading the cluster version, they can occur at the same time.
Adds some better logic to handle the semver list and ranges, including versioning our previous cloud provider parser to make it more robust and native to library implementation  
======
Bugfix
Linked Issues
======
rancher/rancher#32143
======
=> GKE V2 Node Version Bugs

lib/shared/addon/components/form-network-config/component.js, lib/shared/addon/utils/constants.js, translations/en-us.yaml
======
Update RKE network provider dropdown for new pni updates. Network Isolation is now allowed in everything but Flannel. 
======
Enhancement
Linked Issues
======
rancher/rancher#32106
======
=> [2.5.x] RKE CNI Dropdown Updates

lib/shared/addon/components/form-network-config/component.js, lib/shared/addon/utils/constants.js, translations/en-us.yaml
======
Update RKE network provider dropdown for new pni updates. Network Isolation is now allowed in everything but Flannel. 
======
Enhancement
Linked Issues
======
rancher/rancher#32106
======
=> RKE CNI Dropdown Updates

lib/shared/addon/components/form-network-config/component.js
======
reset networkpolicy if flannel provider is chosen
======
bugfix
Linked Issues
======
rancher/rancher#32106
======
=> CNI Provider Flannel Bug

lib/shared/addon/components/form-network-config/component.js
======
reset networkpolicy if flannel provider is chosen
======
bugfix
Linked Issues
======
rancher/rancher#32106
======
=> [2.5.x] CNI Provider Flannel Bug

lib/shared/addon/components/cluster-driver/driver-gke/component.js, lib/shared/addon/components/cluster-driver/driver-gke/template.hbs, lib/shared/addon/components/input-cidr/component.js, translations/en-us.yaml
======
Add very basic validation logic surrounding ipAllocationPolicy min/max cidr ranges to ensure the user is with in the absolute min/max for the ip allocation policy cidr ranges.
======
bugfixes
Linked Issues
======
======
=> [2.5.x] GKE V2 IP Allocation CIDR Validation

lib/shared/addon/components/cluster-driver/driver-gke/component.js, lib/shared/addon/components/cluster-driver/driver-gke/template.hbs, lib/shared/addon/components/input-cidr/component.js, translations/en-us.yaml
======
Add very basic validation logic surrounding ipAllocationPolicy min/max cidr ranges to ensure the user is with in the absolute min/max for the ip allocation policy cidr ranges.
======
bugfixes
Linked Issues
======
======
=> GKE V2 IP Allocation CIDR Validation

lib/shared/addon/components/form-engine-opts/component.js, translations/en-us.yaml
======
Attempt to Display default docker engine script version on the node template create view when a user opens the default engine dropdown. If we can't parse a version from the string then we just show the old ux.
======
Bugfix
Linked Issues
======
rancher/rancher#31216
======
=> Display default docker engine script version

app/components/cru-persistent-volume/component.js, app/components/cru-persistent-volume/template.hbs, app/components/modal-edit-apikey/template.hbs, lib/global-admin/addon/components/form-google-auth/component.js, lib/global-admin/addon/components/form-google-auth/template.hbs, lib/global-admin/addon/security/authentication/googleoauth/template.hbs, lib/monitoring/addon/components/enable-monitoring/template.hbs, lib/pipeline/addon/components/bitbucketserver-setting/template.hbs, lib/shared/addon/components/authorized-endpoint/component.js, lib/shared/addon/components/authorized-endpoint/template.hbs, lib/shared/addon/components/cru-cloud-provider/component.js, lib/shared/addon/components/cru-cloud-provider/template.hbs, lib/shared/addon/components/cru-private-cluster/template.hbs, lib/shared/addon/components/custom-command/component.js, lib/shared/addon/components/custom-command/template.hbs, lib/shared/addon/components/modal-resize-pvc/component.js, lib/shared/addon/components/modal-resize-pvc/template.hbs, lib/shared/addon/components/run-scan-modal/component.js, lib/shared/addon/settings/service.js, translations/en-us.yaml
======
The >=2.5 docs have been split into a different route and the <2.5 docs have been split into another. This adds logic to try and parse the version and see if it satisfies a range of >=2.5.
Addeded docsBase to translations that were missing it as well.
======
Bugfix
Linked Issues
======
rancher/rancher#31860
======
=> Update docs base logic for 2.5+

app/components/cru-persistent-volume/component.js, app/components/cru-persistent-volume/template.hbs, app/components/modal-edit-apikey/template.hbs, lib/global-admin/addon/components/form-google-auth/component.js, lib/global-admin/addon/components/form-google-auth/template.hbs, lib/global-admin/addon/security/authentication/googleoauth/template.hbs, lib/monitoring/addon/components/enable-monitoring/template.hbs, lib/pipeline/addon/components/bitbucketserver-setting/template.hbs, lib/shared/addon/components/authorized-endpoint/component.js, lib/shared/addon/components/authorized-endpoint/template.hbs, lib/shared/addon/components/cru-cloud-provider/component.js, lib/shared/addon/components/cru-cloud-provider/template.hbs, lib/shared/addon/components/cru-private-cluster/template.hbs, lib/shared/addon/components/custom-command/component.js, lib/shared/addon/components/custom-command/template.hbs, lib/shared/addon/components/modal-resize-pvc/component.js, lib/shared/addon/components/modal-resize-pvc/template.hbs, lib/shared/addon/components/run-scan-modal/component.js, lib/shared/addon/settings/service.js, translations/en-us.yaml
======
The >=2.5 docs have been split into a different route and the <2.5 docs have been split into another. This adds logic to try and parse the version and see if it satisfies a range of >=2.5.
Addeded docsBase to translations that were missing it as well.
======
Bugfix
Linked Issues
======
rancher/rancher#31860
======
=> [2.5.x] Update docs base logic for 2.5+

app/models/cluster.js, lib/shared/addon/components/cluster-driver/driver-gke/component.js, lib/shared/addon/components/cluster-driver/driver-gke/template.hbs, lib/shared/addon/components/cru-master-auth-network/component.js, lib/shared/addon/components/cru-master-auth-network/template.hbs, lib/shared/addon/components/cru-private-cluster/component.js, lib/shared/addon/components/cru-private-cluster/template.hbs, lib/shared/addon/components/import-command/template.hbs, lib/shared/addon/components/input-cidr/component.js, translations/en-us.yaml
======
This pr adds logic to prevent the master authorize networks from be disabled if the enablePrivateEndpoint param is set true. If not the field is optional. 
Additionally this reverts the changes for InputCidr min max validation as this logic is just not robust enough to handle the validation correctly. 
Sets node pool auto upgrade and auto repair true by default as this is what is done in GKE. 
Adds links to GKE docs.
======
Bugfixes
Linked Issues
======
rancher/rancher#32251
rancher/rancher#32030
======
=> GKE MasterAuthorizedNetwork Tweaks

app/models/cluster.js, lib/shared/addon/components/cluster-driver/driver-gke/component.js, lib/shared/addon/components/cluster-driver/driver-gke/template.hbs, lib/shared/addon/components/cru-master-auth-network/component.js, lib/shared/addon/components/cru-master-auth-network/template.hbs, lib/shared/addon/components/cru-private-cluster/component.js, lib/shared/addon/components/cru-private-cluster/template.hbs, lib/shared/addon/components/import-command/template.hbs, lib/shared/addon/components/input-cidr/component.js, translations/en-us.yaml
======
This pr adds logic to prevent the master authorize networks from be disabled if the enablePrivateEndpoint param is set true. If not the field is optional. 
Additionally this reverts the changes for InputCidr min max validation as this logic is just not robust enough to handle the validation correctly. 
Sets node pool auto upgrade and auto repair true by default as this is what is done in GKE. 
Adds links to GKE docs.
======
Bugfixes
Linked Issues
======
rancher/rancher#32251
rancher/rancher#32030
======
=> [2.5.x] GKE MasterAuthorizedNetwork Tweaks

lib/shared/addon/components/cluster-driver/driver-gke/template.hbs, translations/en-us.yaml
======
Move ipAllocationPolicy cluster and service cidr blocks to conditional, weonly want to show them when auto creating a subnetwork, otherwise the values are ignored.
======
Enhancement
Linked Issues
======
N/A
======
=> IP Allocation Cidr Blocks Cleanup

lib/shared/addon/components/cluster-driver/driver-gke/template.hbs, translations/en-us.yaml
======
Move ipAllocationPolicy cluster and service cidr blocks to conditional, weonly want to show them when auto creating a subnetwork, otherwise the values are ignored.
======
Enhancement
Linked Issues
======
N/A
======
=> [2.5.x] IP Allocation Cidr Blocks Cleanup

lib/shared/addon/components/cluster-driver/driver-gke/component.js
======
Rather than hide the versions we can not use from the list, show them but make them disabled.
======
Bugfix
Linked Issues
======
rancher/rancher#32339
======
=> Update GKE version dropdowns to match EKS Edit

lib/shared/addon/components/cluster-driver/driver-gke/component.js
======
Rather than hide the versions we can not use from the list, show them but make them disabled.
======
Bugfix
Linked Issues
======
rancher/rancher#32339
======
=> [2.5.x] Update GKE version dropdowns to match EKS Edit

lib/shared/addon/components/cluster-driver/driver-gke/template.hbs
======
Fixes a bug where we should have passed down editing not the new isNewOrEditable. 
======
Bugfix
Linked Issues
======
======
=> GKE v2 Error State Edit Bug

lib/shared/addon/components/cluster-driver/driver-gke/template.hbs, translations/en-us.yaml
======
======
Bugfix
Linked Issues
======
rancher/rancher#32346
======
=> GKE V2 Update secondary range labels

lib/shared/addon/components/cluster-driver/driver-gke/template.hbs, translations/en-us.yaml
======
======
Bugfix
Linked Issues
======
rancher/rancher#32346
======
=> [2.5.x] GKE V2 Update secondary range labels

lib/shared/addon/components/cluster-driver/driver-gke/component.js, lib/shared/addon/components/gke-node-pool-row/component.js, translations/en-us.yaml
======
Fixes an incorrect label in the cluster versions dropdown.
Fixes bug where on init of editing a cluster the node pool auto scaling settings would be reset. 
======
Bugfixes
Linked Issues
======
https://github.com/rancher/rancher/issues/32339
https://github.com/rancher/rancher/issues/32359
======
=> [2.5.x] Minor GKE Bugs

app/models/cluster.js
======
These values should be null which the on(init change from the previous commit was handling.
======
bugfix
Linked Issues
======
======
=> GKE Min/Max Node counts should be null

app/models/cluster.js, lib/shared/addon/components/cluster-driver/driver-gke/component.js, lib/shared/addon/components/gke-node-pool-row/component.js, translations/en-us.yaml
======
Fixes an incorrect label in the cluster versions dropdown.
Fixes bug where on init of editing a cluster the node pool auto scaling settings would be reset. 
======
Bugfixes
Linked Issues
======
https://github.com/rancher/rancher/issues/32339
https://github.com/rancher/rancher/issues/32359
======
=> Minor GKE Bugs

lib/shared/addon/components/custom-command/template.hbs, translations/en-us.yaml
======
Add warning to custom command that rancher needs nodes with all roles before it will fully provision. If all three roles are selected the warning will be removed.
======
Enhancement 
Linked Issues
======
rancher/rancher#32404
======
=> Custom Cluster Command Warning

lib/shared/addon/components/custom-command/template.hbs, translations/en-us.yaml
======
Add warning to custom command that rancher needs nodes with all roles before it will fully provision. If all three roles are selected the warning will be removed.
======
Enhancement 
Linked Issues
======
rancher/rancher#32404
======
=> [2.5.x] Custom Cluster Command Warning

lib/shared/addon/components/cluster-driver/driver-gke/template.hbs, lib/shared/addon/components/cluster-driver/driver-import-gke/component.js, lib/shared/addon/components/cluster-driver/driver-import-gke/template.hbs, translations/en-us.yaml
======
Exposes GKE cluster description.
Update import gke to use zonal by default.
======
Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/32430
https://github.com/rancher/rancher/issues/32439
======
=> GKE Cluster Description

lib/shared/addon/components/cluster-driver/driver-gke/template.hbs, lib/shared/addon/components/cluster-driver/driver-import-gke/component.js, lib/shared/addon/components/cluster-driver/driver-import-gke/template.hbs, translations/en-us.yaml
======
Exposes GKE cluster description.
Update import gke to use zonal by default.
======
Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/32430
https://github.com/rancher/rancher/issues/32439
======
=> [2.5.x] GKE Cluster Description

lib/shared/addon/components/cluster-driver/driver-gke/component.js, lib/shared/addon/components/cluster-driver/driver-gke/template.hbs, lib/shared/addon/google/service.js, translations/en-us.yaml
======
Lookup imported gke cluster object on edit to find release channels. If the imported cluster is on a release channel we can then limit the versions available to the user for upgrade scenarios to those that exist in the release channel.
======
rancher/rancher#32360
Linked Issues
======
Bugfix
======
=> [2.5.x] GKE Imported Cluster Lookup

lib/shared/addon/components/cluster-driver/driver-gke/component.js, lib/shared/addon/components/cluster-driver/driver-gke/template.hbs, lib/shared/addon/google/service.js, translations/en-us.yaml
======
Lookup imported gke cluster object on edit to find release channels. If the imported cluster is on a release channel we can then limit the versions available to the user for upgrade scenarios to those that exist in the release channel.
======
rancher/rancher#32360
Linked Issues
======
Bugfix
======
=> GKE Imported Cluster Lookup

lib/shared/addon/components/gke-node-pool-row/component.js
======
Fix gke node pools labels, was using a type array but should have been type map.
======
Bugfix
Linked Issues
======
rancher/rancher#32435
======
=> [2.5.x] GKE Node Pool Labels

lib/shared/addon/components/gke-node-pool-row/component.js
======
Fix gke node pools labels, was using a type array but should have been type map.
======
Bugfix
Linked Issues
======
rancher/rancher#32435
======
=> GKE Node Pool Labels

lib/nodes/addon/components/driver-amazonec2/component.js
======
change aws node template instance type for `me` regions
======
bugfix
Linked Issues
======
rancher/rancher#31980
======
=> [2.5.x] AWS Node Template `me` Region Changes

lib/nodes/addon/components/driver-amazonec2/component.js
======
change aws node template instance type for `me` regions
======
bugfix
Linked Issues
======
rancher/rancher#31980
======
=> AWS Node Template `me` Region Changes

lib/shared/addon/components/gke-node-pool-row/component.js, lib/shared/addon/components/gke-node-pool-row/template.hbs
======
======
Bugfix
Linked Issues
======
rancher/rancher#32435
======
=> Bug Initial Map Node Pool Labels

lib/shared/addon/components/gke-node-pool-row/component.js, lib/shared/addon/components/gke-node-pool-row/template.hbs
======
======
Bugfix
Linked Issues
======
rancher/rancher#32435
======
=> [2.5.x] Bug Initial Map Node Pool Labels

lib/shared/addon/components/form-members/component.js
======
If a cluster errors out and user tries to save again they'll see an error that they need at least one owner role. moving to destroy ensures we're leaving the route.
======
Bugfix
Linked Issues
======
rancher/rancher#32447
======
=> [2.5.x] Form Members Reset Bug

lib/shared/addon/components/form-members/component.js
======
If a cluster errors out and user tries to save again they'll see an error that they need at least one owner role. moving to destroy ensures we're leaving the route.
======
Bugfix
Linked Issues
======
rancher/rancher#32447
======
=> Form Members Reset Bug

app/models/cluster.js, lib/shared/addon/components/cluster-driver/driver-gke/component.js, lib/shared/addon/components/cluster-driver/driver-gke/template.hbs, translations/en-us.yaml
======
Release channels can be changed in the GKE console during an upgrade/edit. I was not aware of this when I implemented the original fix for finding the imported clusters release channel. Dropped the check for imported from this logic so now we'll look up the cluster on ever edit and find the correct set of versions from its release channel.
Exposes cluster labels on GKE create. 
======
Bugfix
Enhancement 
Linked Issues
======
https://github.com/rancher/rancher/issues/32360
https://github.com/rancher/rancher/issues/32433
======
=> [2.5.x] GKE V2 Updates

app/models/cluster.js, lib/shared/addon/components/cluster-driver/driver-gke/component.js, lib/shared/addon/components/cluster-driver/driver-gke/template.hbs, translations/en-us.yaml
======
Release channels can be changed in the GKE console during an upgrade/edit. I was not aware of this when I implemented the original fix for finding the imported clusters release channel. Dropped the check for imported from this logic so now we'll look up the cluster on ever edit and find the correct set of versions from its release channel.
Exposes cluster labels on GKE create. 
======
Bugfix
Enhancement 
Linked Issues
======
https://github.com/rancher/rancher/issues/32360
https://github.com/rancher/rancher/issues/32433
======
=> GKE V2 Updates

app/models/cluster.js, lib/shared/addon/components/cluster-driver/driver-gke/component.js
======
Fixes bug so we only send updated details and full node groups/pools for V2 clusters when editing. 
Fixes undefined bug that I found while fixing the above and I edited a imported cluster before the sync finished. 
======
Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/32441
======
=> V2 Clusters Changed Deltas

app/models/cluster.js, lib/shared/addon/components/cluster-driver/driver-gke/component.js
======
Fixes bug so we only send updated details and full node groups/pools for V2 clusters when editing. 
Fixes undefined bug that I found while fixing the above and I edited a imported cluster before the sync finished. 
======
Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/32441
======
=> [2.5.x] V2 Clusters Changed Deltas

lib/shared/addon/components/cluster-driver/driver-gke/template.hbs
======
Cluster labels are editable. 
======
Linked Issues
======
Bugfix
======
=> GKE V2 Cluster Labels Editable

lib/shared/addon/components/cluster-driver/driver-gke/template.hbs
======
Cluster labels are editable. 
======
Linked Issues
======
Bugfix
======
=> [2.5.x] GKE V2 Cluster Labels Editable

app/models/cluster.js
======
if the upstream spec is not an empty object but our config is then we need to send the empty object because this indicates the user removed contents of a map.
======
bugfix
Linked Issues
======
======
=> [2.5.x] Bug in v2 cluster config compare

app/models/cluster.js
======
if the upstream spec is not an empty object but our config is then we need to send the empty object because this indicates the user removed contents of a map.
======
bugfix
Linked Issues
======
======
=> Bug in v2 cluster config compare

lib/shared/addon/components/cluster-driver/driver-gke/component.js, lib/shared/addon/components/cluster-driver/driver-import-gke/component.js, lib/shared/addon/google/service.js
======
update gke proxy calls to send cluster id if editing
======
Linked Issues
======
======
=> [2.5.x]  GKE Proxy Calls Update

lib/shared/addon/components/cluster-driver/driver-gke/component.js, lib/shared/addon/components/cluster-driver/driver-import-gke/component.js, lib/shared/addon/google/service.js
======
update gke proxy calls to send cluster id if editing
======
Linked Issues
======
======
=> GKE Proxy Calls Update

lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
======
Fixes bug where the edit as yaml button shows on the custom command page
Fixes bug where windows selection doesn't show up on custom command page.
======
Bugs
Linked Issues
======
https://github.com/rancher/rancher/issues/32521
https://github.com/rancher/rancher/issues/32522
======
n/a
=> [2.5.x] Custom Command Bug

lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
======
Fixes bug where the edit as yaml button shows on the custom command page
Fixes bug where windows selection doesn't show up on custom command page.
======
Bugs
Linked Issues
======
https://github.com/rancher/rancher/issues/32521
https://github.com/rancher/rancher/issues/32522
======
n/a
=> Custom Command Bug 

app/models/cluster.js
======
I added labels to the diffUpstreamSpec comparison exclusion block. we already check for equality (eg no changes) in the JSON string compare higher in the function so that handled the labels that were equal but we need to exclude the labels from further comparison because if they are different in the user config, meaning the user changed them, then we know we need to send the entire labels object to update. If we didn't do this the comparison fails because we're only comparing the differences one way not both and removals on the map shorts the comparison functions further on in the function.
======
bugfix
Linked Issues
======
======
=> [2.5.x] GKE Sync Labels Bug

app/models/cluster.js
======
I added labels to the diffUpstreamSpec comparison exclusion block. we already check for equality (eg no changes) in the JSON string compare higher in the function so that handled the labels that were equal but we need to exclude the labels from further comparison because if they are different in the user config, meaning the user changed them, then we know we need to send the entire labels object to update. If we didn't do this the comparison fails because we're only comparing the differences one way not both and removals on the map shorts the comparison functions further on in the function.
======
bugfix
Linked Issues
======
======
=> GKE Sync Labels Bug 

package.json, yarn.lock
======
For dependabot update
======
Linked Issues
======
======
=> [2.5.x] Dependency Update

translations/de-de.yaml, translations/en-us.yaml, translations/es-es.yaml, translations/ja-jp.yaml, translations/nb-no.yaml, translations/uk-ua.yaml, translations/zh-hans.yaml, translations/zh-hant-tw.yaml, translations/zh-hant.yaml
======
Replace instances of `RackSpace` with `Rackspace`.
======
Bugfix (Translations)
=> Fix Rackspace Case

lib/shared/addon/utils/amazon.js
======
1.19 is now supported by EKS. 
======
Enhancement
Linked Issues
======
======
=> [2.5.x] Add 1.19 to eks versions for official support

lib/shared/addon/utils/amazon.js
======
1.19 is now supported by EKS. 
======
Enhancement
Linked Issues
======
======
=> Add 1.19 to eks versions for official support

app/models/cluster.js, lib/shared/addon/components/cluster-driver/driver-gke/component.js, lib/shared/addon/google/service.js
======
change defaults for `clusterIpv4Cidr` & `maintenanceWindow` in GKEv2
======
Enhancement 
Linked Issues
======
https://github.com/rancher/rancher/issues/32770
======
=> GKE V2 Default Values

lib/monitoring/addon/components/cluster-dashboard/component.js
======
Adds imported branch to check for AKS, Tencent, and LKE in the greyed out component status provider list. 
======
Enhancment
Linked Issues
======
rancher/rancher#11496
======
=> Add Additional Providers to Status Component Exclusion List

lib/monitoring/addon/components/cluster-dashboard/component.js
======
Adds imported branch to check for AKS, Tencent, and LKE in the greyed out component status provider list. 
======
Enhancment
Linked Issues
======
rancher/rancher#11496
======
=> [2.5.x] Add Additional Providers to Status Component Exclusion List

app/authenticated/project/controller.js, app/authenticated/project/template.hbs
This PR updates the UI so that when it is embedded, we don't show the warning message for system projects.
=> Embedding; Hide system project notice when embedded

lib/shared/addon/components/cluster-driver/driver-oracleoke/component.js, lib/shared/addon/components/cluster-driver/driver-oracleoke/template.hbs
======
This PR is a back-port of:
- https://github.com/rancher/ui/pull/4637
======
Backport of a small bug-fix / UI enhancment.
Linked Issues
======
======
=> [2.5] backport: Add helper to detect when any flexible shape is selected.

lib/monitoring/addon/components/cluster-dashboard/component.js, lib/monitoring/addon/components/cluster-dashboard/template.hbs
======
refactor logic of when to grey out component status indicators, the logic prior to this relied on a static list, ive updated the logic to actually check the component status objects and there health.
======
Bugfix
Linked Issues
======
rancher/rancher#11496
======
=> [2.5.x] Refactor Component Status Logic

lib/shared/addon/components/cluster-driver/driver-gke/template.hbs
======
only allow location change for zonal clusters on edit
======
Enhancement 
Linked Issues
======
rancher/rancher#32345
======
=> GKEv2 Zonal Location Edit

lib/shared/addon/components/cluster-driver/driver-gke/template.hbs
======
only allow location change for zonal clusters on edit
======
Enhancement 
Linked Issues
======
rancher/rancher#32345
======
=> [2.5.x] GKEv2 Zonal Location Edit

app/models/cluster.js, app/styles/components/_forms.scss, app/styles/components/_searchable-select.scss, app/styles/pages/_host.scss, lib/global-admin/addon/clusters/new/select/controller.js, lib/global-admin/addon/clusters/new/select/template.hbs, lib/global-admin/addon/clusters/new/template.hbs, lib/global-admin/addon/components/cloud-credential-azure/component.js, lib/global-admin/addon/components/cloud-credential-azure/template.hbs, lib/global-admin/addon/components/cru-cloud-credential/component.js, lib/global-admin/addon/components/cru-cloud-credential/template.hbs, lib/global-admin/app/components/cloud-credential-azure/component.js, lib/shared/addon/components/aks-node-pool-row/component.js, lib/shared/addon/components/aks-node-pool-row/template.hbs, lib/shared/addon/components/cluster-driver/driver-aks/component.js, lib/shared/addon/components/cluster-driver/driver-aks/template.hbs, lib/shared/addon/components/cluster-driver/driver-import-aks/component.js, lib/shared/addon/components/cluster-driver/driver-import-aks/template.hbs, lib/shared/addon/components/cru-cluster/component.js, lib/shared/addon/components/input-cidr/component.js, lib/shared/addon/components/input-cidr/template.hbs, lib/shared/addon/components/modal-show-command/component.js, lib/shared/addon/components/searchable-select/template.hbs, lib/shared/addon/utils/azure-choices.js, lib/shared/app/components/aks-node-pool-row/component.js, lib/shared/app/components/cluster-driver/driver-aks/component.js, lib/shared/app/components/cluster-driver/driver-import-aks/component.js, lib/shared/app/utils/azure-choices.js, translations/en-us.yaml
======
Exposes the Azure AKS v2 cluster provisioner. 
======
Linked Issues
======
rancher/rancher#31315
======
=> [WIP] Azure AKS v2

lib/shared/addon/components/aks-node-pool-row/component.js
======
======
Linked Issues
======
======
=> fix is new node pool check

lib/shared/addon/components/aks-node-pool-row/component.js
======
======
Linked Issues
======
======
=> lint fixes

lib/shared/addon/components/cluster-driver/driver-aks/template.hbs
======
Expose httpApplicationRouting on AKS v2 cluster create/edit.
======
New Feature
Linked Issues
======
rancher/rancher#32991
======
=> AKS v2 httpApplicationRouting 

lib/shared/addon/components/cluster-driver/driver-gke/template.hbs
======
make networkPolicyConfig un-editable
======
Bugfix
Linked Issues
======
rancher/rancher#32998
======
=> GKE V2 - networkPolicyConfig

lib/shared/addon/components/cluster-driver/driver-gke/component.js, lib/shared/addon/components/cluster-driver/driver-gke/template.hbs, lib/shared/addon/components/cluster-driver/driver-import-gke/template.hbs, lib/shared/addon/components/cru-cluster/template.hbs, translations/en-us.yaml
======
Exposes the PNI (cluster.enableNetworkPolicy) for generic import and GKE v2 clusters. 
======
Feature
Linked Issues
======
rancher/rancher#33024
rancher/rancher#33026
======
=> Expose PNI (Generic Import and GKE) 

lib/shared/addon/components/cluster-driver/driver-aks/template.hbs
======
allow empty values aks v2 tags
======
Bugfix
Linked Issues
======
rancher/rancher#33017
======
=> AKS V2 Empty Tags Bug

package.json, yarn.lock
======
======
Linked Issues
======
======
=> Dep upgrades

lib/shared/addon/components/aks-node-pool-row/component.js, lib/shared/addon/components/aks-node-pool-row/template.hbs, lib/shared/addon/components/cluster-driver/driver-aks/template.hbs, translations/en-us.yaml
======
fix aks np autoscaling bugs when enabled -> disabled
change placeholders
======
Bugfix
Linked Issues
======
rancher/rancher#33049
======
=> AKS V2 NP Autoscaling Bugs

lib/shared/addon/components/gke-access-scope/component.js, lib/shared/addon/components/gke-access-scope/template.hbs, lib/shared/addon/components/gke-node-pool-row/component.js, lib/shared/addon/components/gke-node-pool-row/template.hbs
======
Incorrectly used a the model param instead of config for gke v2 scopes. 
Added an action to the gke access component to alert a change happened. When this happens we update the custom scope config. In GKE v1 this happened on save. 
======
Bugfix
Linked Issues
======
rancher/rancher#32994
======
=> Fix GKE v2 oauth scopes logic

lib/global-admin/addon/components/cloud-credential-azure/component.js, lib/global-admin/addon/components/cloud-credential-azure/template.hbs, lib/global-admin/addon/components/cru-cloud-credential/component.js, lib/shared/addon/components/cluster-driver/driver-aks/component.js, translations/en-us.yaml
======
Adds support for azure cloud creds with or without the tenant id for backwards compatibility with AKS v1
======
Enhancement 
Linked Issues
======
rancher/rancher#33097
======
=> Support Azure Cloud Cred with or without tenant id

lib/shared/addon/components/cluster-driver/driver-import/template.hbs
======
we still randomly would hit a case where the cluster was active post save, checking if we're post save will ensure the cluster shows the command all the time.
======
Bugfix
Linked Issues
======
rancher/rancher#33136
======
=> Generic Import Post Save Bug

lib/shared/addon/components/cluster-driver/driver-aks/component.js, lib/shared/addon/components/cluster-driver/driver-aks/template.hbs, translations/en-us.yaml
======
Exposes the monitoring boolean and the log analytics workspace group and name inputs. 
======
New Feature
Linked Issues
======
rancher/rancher#33142
======
=> AKS v2 expose monitoring

lib/shared/addon/settings/service.js
======
change docs base for master head versions to go to 2.5
======
Bugfixes
Linked Issues
======
rancher/rancher#32258
======
=> Docs Base masterhead

app/authenticated/prefs/template.hbs
======
remove landing page settings
======
Enhancement
Linked Issues
======
rancher/rancher#33147
======
=> Langing Page Prefs

lib/shared/addon/components/gke-access-scope/component.js, lib/shared/addon/components/gke-access-scope/template.hbs, lib/shared/addon/components/gke-node-pool-row/component.js, lib/shared/addon/components/gke-node-pool-row/template.hbs
======
Backport of GKE scope logic fixes
======
Backport
Linked Issues
======
https://github.com/rancher/rancher/issues/33154
======
=> [2.5.x] Fix GKE v2 oauth scopes logic

translations/en-us.yaml, translations/ja-jp.yaml, translations/zh-hans.yaml, translations/zh-hant-tw.yaml, translations/zh-hant.yaml
======
Packet is now Equinix Metal.
The Packet translation strings are copied to a 'metal' provider, for
Equinix Metal.
======
Introduces `metal` translation stanzas.
Linked Issues
======
These translation strings are needed for https://github.com/packethost/ui-driver-packet/pull/29 (which is a precursor PR to ui-driver-packet being renamed with Equinix Metal branding).
======
=> add Equinix Metal translations based on Packet provider

package.json, yarn.lock
======
upgrade ember api store and can-i-use
======
Linked Issues
======
======
=> Dep updates

lib/shared/addon/components/cluster-driver/driver-aks/template.hbs
======
Make monitoring & monitoring related fields uneditable
moved monitoring options to the cluster options section
======
bugfix
Linked Issues
======
rancher/rancher#33239
rancher/rancher#33240
======
=> AKS v2 Monitoring Change

app/styles/components/_forms.scss
======
remove firefox workaround bug fixed in firefox
======
bug
Linked Issues
======
rancher/rancher#33313
======
=> Select Opt CSS Bug

app/styles/components/_forms.scss, lib/monitoring/addon/index/controller.js, lib/monitoring/addon/index/template.hbs, lib/shared/addon/components/cluster-driver/driver-import-aks/component.js, lib/shared/addon/components/cluster-driver/driver-import-aks/template.hbs, translations/en-us.yaml
======
Adds a warning to the AKS import page when importing a cluster that does not have `rbacEnabled`.
Adds a warning to the cluster dashboard when viewing a cluster that does not have `rbacEnabled`. 
======
New Feature
Linked Issues
======
rancher/rancher#33307
======
Reverts a change for some firefox quirks which started showing up in my new version of firefox today.
=> AKS V2 RBAC Warning

app/styles/components/_forms.scss
======
This updates the styles for disabled select options making the colors more clear. This really only affects Windows browsers or firefox on mac as Chrome on mac seems to respect the OS system them no mater what. 
======
Bugfix
Linked Issues
======
rancher/rancher#33313
======
=> Select Opt CSS Quirk

lib/shared/addon/components/cluster-driver/driver-gke/component.js, lib/shared/addon/components/cluster-driver/driver-gke/template.hbs, translations/en-us.yaml
======
Re-implement ui validation for gke v2 network policy to more closely mimic the google ux and prevent users from falling into a hole with network policy.
======
Linked Issues
======
rancher/rancher#32998
======
=> GKE v2 Network Policy Validation

lib/shared/addon/user-theme/service.js
======
When the legacy UI does not have a user theme we set the default theme to ui-light. Normally this isn't a problem because users have visited the legacy UI before. In some upgrade scenarios this is not the case and when viewing the iframed ui through the dashboard the  pref does not get set because its undefined. Since the dashboard defaults to a dark ui the two opposite. This adds some logic to default the theme to dark if we meet the above conditions.  
======
Bugfix
Linked Issues
======
rancher/dashboard#3088
======
=> Embedded Deafult Theme

app/authenticated/cluster/storage/classes/index/template.hbs, lib/shared/addon/components/containers-header/template.hbs
======
fixes a couple more engine link issues that cropped up during the upgrade to 3.24
======
Linked Issues
======
======
=> Engine Links

app/initializers/aws-sdk.js, lib/shared/addon/components/cluster-driver/driver-eks/component.js
======
Add cluster id to aws request handler and populate cluster id on edit eksv2.
======
Linked Issues
======
======
=> EKS V2 Proxy Update

app/initializers/aws-sdk.js, lib/shared/addon/components/cluster-driver/driver-eks/component.js
======
Add cluster id to aws request handler and populate cluster id on edit eksv2.
======
Linked Issues
======
======
=> [2.5.10] EKS V2 Proxy Update

app/initializers/aws-sdk.js, lib/shared/addon/components/cluster-driver/driver-eks/component.js
======
Add cluster id to aws request handler and populate cluster id on edit eksv2.
======
Linked Issues
======
======
=> [2.5.9] EKS V2 Proxy Update

lib/shared/addon/components/cluster-driver/driver-aks/component.js, lib/shared/addon/components/cluster-driver/driver-aks/template.hbs
======
Allow users to enable aks monitoring on edit.
======
Bugfix
Linked Issues
======
rancher/rancher#33239
======
=> AKS v2 Monitoring Edit

translations/en-us.yaml
======
Be more explicit about what happens when creating a new RKE template from a cluster
======
- minor Bugfix
Linked Issues
======
improves rancher/rancher/issues/26261
======
=> write clearer about new rke template from cluster

lib/shared/addon/utils/azure-choices.js
======
Added German location to the AKS choices based on this PR: https://github.com/rancher/ui/pull/4095 
======
Linked Issues
======
https://github.com/rancher/rancher/issues/28216
=> Added Germany West Central as a new AKS region

lib/nodes/addon/components/driver-pnap/component.js, lib/nodes/addon/components/driver-pnap/template.hbs, lib/shared/addon/pnap/service.js, lib/shared/app/pnap/service.js, translations/en-us.yaml
=> Implementation for pnap driver to fetch data dynamically from ui

lib/shared/addon/mixins/catalog-app.js
https://github.com/rancher/rancher/issues/32394
=> feat(catalog) Convert Template Files encoding format to utf-8

app/models/cluster.js, lib/shared/addon/components/gke-node-pool-row/template.hbs, translations/en-us.yaml
======
Exposes the new tags param on the gke node pool config.
======
New Feature
Linked Issues
======
rancher/rancher#33416
======
Should be held until the back-end is in
=> [2.6.x] GKE V2 Node Tags

app/models/cluster.js, lib/shared/addon/components/gke-node-pool-row/template.hbs, translations/en-us.yaml
======
Exposes the new tags param on the gke node pool config.
======
New Feature
Linked Issues
======
rancher/rancher#33415
======
Should be held until the back-end is in
=> [2.5.10] GKE V2 Node Tags

app/initializers/aws-sdk.js, lib/shared/addon/components/cluster-driver/driver-eks/component.js
backport of https://github.com/rancher/ui/pull/4694
=> Fix EKS cluster ID string case

lib/shared/addon/components/cluster-driver/driver-googlegke/component.js, lib/shared/addon/google/service.js
https://github.com/rancher/rancher/issues/33527
=> Making use of region instead of zone while querying meta/gkeVersion when available

lib/shared/addon/components/cluster-driver/driver-googlegke/component.js, lib/shared/addon/google/service.js
=> Gke versions region 2.5.9 fixes

lib/shared/addon/components/cluster-driver/driver-googlegke/component.js, lib/shared/addon/google/service.js
=> Gke versions region 2.5 fixes

lib/shared/addon/components/cluster-driver/driver-googlegke/component.js
=> Clear the cluster/service secondary range names if a new subnet is not being created

lib/shared/addon/components/cluster-driver/driver-import-aks/component.js
=> Send cluster resourceLocation

app/authenticated/project/template.hbs, app/components/page-header/template.hbs, app/styles/components/_accordion.scss, app/styles/components/_badges.scss, app/styles/components/_button.scss, app/styles/components/_tables.scss, app/styles/components/_tabs.scss, app/styles/layout/_header.scss, lib/global-admin/addon/catalog/template.hbs, lib/global-admin/addon/global-dns/providers/index/template.hbs, lib/shared/addon/components/form-agent-env-var/template.hbs, lib/shared/addon/mixins/sticky-table-header.js
This PR addresses a few more issues with the recent changes to the styling to align the styling with the Dashboard UI
=> More style fixes to address problems from recent update

lib/shared/addon/components/cluster-driver/driver-aks/template.hbs
Addresses https://github.com/rancher/dashboard/issues/3475
=> Fix minor checkbox alignment issue

app/styles/components/_tables.scss
Addresses https://github.com/rancher/dashboard/issues/3497
=> Fix table border colors in dark mode

app/apps-tab/detail/template.hbs, app/components/container/new-edit/template.hbs, app/ingresses/index/template.hbs, lib/global-admin/addon/security/roles/index/template.hbs, lib/pipeline/addon/components/settings-git/template.hbs, lib/shared/addon/components/catalog-index/template.hbs, lib/shared/addon/components/cru-node-pools/template.hbs, lib/shared/addon/components/input-text-file/template.hbs
#3518 - this issue is specifically generated by problems in [here](https://github.com/mantis-toboggan-md/ui/blob/bc710929a696d23c7d1a7405625c6efe21363810/app/ingresses/index/template.hbs) in the ingress list template but the overall problem is the addition of leading white spaces in a bunch of places. I've removed all ones that were inadvertently added in the recent round of style tweaks in this PR.
=> remove leading white spaces

lib/global-admin/addon/components/cru-cloud-credential/component.js
======
because the cluster driver and node driver use the same cloud credential, so when one of the states is active, we should be able to create this cloud credential
======
Bugfix
Linked Issues
======
======
=> fix: add cluster driver filter when create a cloud credential

lib/global-admin/addon/components/cru-cloud-credential/component.js
======
add filtered inactive nodeDriver
======
Bugfix
Linked Issues
======
https://github.com/rancher/rancher/issues/33821
======
=> fix: add filter inactive nodeDriver

app/authenticated/cluster/cis/scan/template.hbs, app/models/cluster.js, lib/istio/addon/components/istio-catalog/template.hbs, lib/logging/addon/components/logging/new-edit/template.hbs, lib/pipeline/addon/components/enable-repositories/template.hbs, lib/pipeline/addon/settings/template.hbs, lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, lib/shared/addon/utils/constants.js, translations/en-us.yaml
https://github.com/rancher/dashboard/issues/3589
=> Inform the user that Logging, CIS Scans, Istio and Pipelines aren't supported in k8s 1.21+

lib/shared/addon/utils/amazon.js
https://github.com/rancher/dashboard/issues/3673
=> Removing k8s 1.15 from eks

app/application/route.js, app/logout/route.js, lib/login/addon/login/controller.js
======
======
Linked Issues
======
======
=> Login & Logout should go to dashboard

app/styles/components/_forms.scss, lib/shared/addon/components/node-pool-row/template.hbs
Addresses https://github.com/rancher/dashboard/issues/3730
=> Fix truncation of dropdown in table

app/styles/base/_color.scss, app/styles/pages/_host.scss, app/styles/themes/_dark.scss
Addresses https://github.com/rancher/dashboard/issues/3729
=> Fix dark mode colors

app/styles/components/_forms.scss, app/styles/themes/_dark.scss
Addresses https://github.com/rancher/dashboard/issues/3713
=> Fix dark mode border color on plain select

app/styles/components/_forms.scss, app/styles/components/_tables.scss, app/styles/themes/_dark.scss, lib/shared/addon/components/sortable-thead/template.hbs
Fixes minor issue seen on Global DNS Providers page - the first column is not sortable and its vertical alignment does not match the other columns.
This PR fixes this.
=> Fix table header alignment

app/styles/components/_forms.scss, app/styles/components/_tables.scss, app/styles/themes/_dark.scss, lib/shared/addon/components/node-taints/template.hbs, lib/shared/addon/components/sortable-thead/template.hbs
Addresses https://github.com/rancher/dashboard/issues/3814
=> Fix another truncated dropdown

translations/en-us.yaml
======
======
Linked Issues
======
======
=> There is no tenant id

app/styles/components/_forms.scss, app/styles/components/_new-select.scss, app/styles/themes/_dark.scss, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, lib/shared/addon/components/save-cancel/template.hbs
Addresses:
https://github.com/rancher/dashboard/issues/3817
https://github.com/rancher/dashboard/issues/3837
=> Fix more dark mode issues resulting from styling changes

translations/en-us.yaml
Addresses https://github.com/rancher/dashboard/issues/3855
=> Update warning prompts for k8s 1.21

lib/shared/addon/components/project-member-row/component.js
======
======
Linked Issues
======
======
=> Handle role with no name

lib/shared/addon/components/cluster-driver/driver-gke/component.js
======
======
Linked Issues
======
======
=> Check the right field for useIpAliases

app/authenticated/project/certificates/index/template.hbs
Addresses https://github.com/rancher/dashboard/issues/4076
=> Remove extra border in certificates list

lib/shared/addon/components/cru-node-pools/template.hbs
Addresses https://github.com/rancher/dashboard/issues/4034
=> Fix mis-alingment of number of nodes required on add cluster

lib/shared/addon/components/cru-cluster/component.js
Addresses https://github.com/rancher/dashboard/issues/4089
=> Fix banner message missing application name

lib/shared/addon/components/cru-cluster/component.js
Addresses https://github.com/rancher/dashboard/issues/4089
=> Fix error saving changes to local cluster

translations/en-us.yaml
======
This updates labels for the Packet node driver to Equinix Metal. I understand that this change only requires updates to the labels and that the actual name of the driver will stay the same. 
======
Updates to English translations.
Linked Issues
======
rancher/dashboard#4161
rancher/rancher#33758
======
=> Update the name for the Packet node driver to Equinix Metal

lib/shared/addon/components/cru-cluster/component.js
Addresses  https://github.com/rancher/dashboard/issues/4201
=> Fix broken cluster edit

lib/shared/addon/components/cluster-driver/driver-aks/component.js
https://github.com/rancher/dashboard/issues/4103
=> Switching over to using the aks-upgrades api when editing an existing cluster

lib/monitoring/addon/components/enable-monitoring/component.js
https://github.com/rancher/rancher/issues/34850#issuecomment-926012429
=> Updating the default prometheus memory limit

lib/shared/addon/components/cluster-driver/driver-eks/component.js, lib/shared/addon/components/form-auth-cloud-credential/component.js, lib/shared/addon/components/form-auth-cloud-credential/template.hbs, translations/en-us.yaml
https://github.com/rancherlabs/rancher-security/issues/820
=> Preventing users from editing an eks cluster when the cloud credential is inaccessible

lib/shared/addon/components/form-auth-cloud-credential/component.js
https://github.com/rancher/dashboard/issues/3559
=> Making the cloud credential in gkev2 be observed properly

lib/nodes/addon/components/driver-azure/template.hbs, translations/en-us.yaml
=> Adding the plan field to the azure driver

lib/shared/addon/utils/amazon.js
======
Remove EKS versions that are no longer supported: https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html.
======
Enhancement really
Linked Issues
======
https://github.com/rancher/rancher/issues/33825
=> Remove unsupported EKS versions

.drone.yml, scripts/build-static, scripts/ci
======
======
Linked Issues
======
======
=> Build on-tag in master

app/styles/components/_forms.scss, app/styles/themes/_dark.scss, app/styles/themes/_light.scss
Addresses https://github.com/rancher/dashboard/issues/3925
=> Fix placeholder text color in light and dark modes

lib/nodes/addon/components/driver-harvester/template.hbs, translations/en-us.yaml, translations/zh-hans.yaml
======
Add Harvester node driver config placeholder
======
Linked Issues
======
https://github.com/harvester/harvester/issues/1030
======
=> HARVESTER: Add Harvester node driver config placeholder

lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, lib/shared/addon/components/cru-cloud-provider/component.js, lib/shared/addon/components/cru-cloud-provider/template.hbs, translations/en-us.yaml
======
======
Linked Issues
======
- https://github.com/rancher/rancher/issues/35000
- https://github.com/harvester/harvester/issues/1396
======
Waiting these backend PR to merge: 
- https://github.com/rancher/rke/pull/2733
- https://github.com/rancher/charts/pull/1595
=> HARVESTER: Add rke1 cloud provider for harvester

lib/shared/addon/components/authorized-endpoint/component.js, lib/shared/addon/components/managed-import-cluster-info/component.js, lib/shared/addon/components/managed-import-cluster-info/template.hbs, lib/shared/addon/mixins/cluster-driver.js
=> Show ACE for imported rke2/k3s clusters

lib/shared/addon/components/cru-cloud-provider/component.js, lib/shared/addon/components/cru-cluster/template.hbs, lib/shared/addon/components/cru-node-pools/component.js, translations/en-us.yaml
======
Change the Kubeconfig API, Harvester needs the Kubeconfig contains VM namespace and Serviceaccout Name
======
Linked Issues
======
- https://github.com/harvester/harvester/issues/1396
======
=> HARVESTER: Change kubeconfig API

lib/shared/addon/google/service.js
Please Add GCP asia-southeast2 (Jakarta) region to register / import GKE Cluster
=> Add GCP asia-southeast2 (Jakarta) region

translations/en-us.yaml, translations/zh-hans.yaml
======
======
Linked Issues
======
https://github.com/harvester/harvester/issues/1671
======
=> HARVESTER: Mark harvester as experimental

lib/shared/addon/components/cluster-driver/driver-aks/template.hbs, translations/en-us.yaml
======
Providing better UX for AKS network policies
- Provide better messaging for Network Policy and Project Network Isolation when editing
- Disable Project Network Isolation when editing
======
Linked Issues
======
rancher/dashboard#4454
=> Providing better UX for AKS network policies

lib/shared/addon/components/cluster-driver/driver-aks/component.js, lib/shared/addon/components/cluster-driver/driver-aks/template.hbs, translations/en-us.yaml
======
Only allow PNI to be selected if a network policy is selected
======
Linked Issues
======
rancher/dashboard#4452
=> Only allow PNI to be selected if a network policy is selected

lib/nodes/addon/components/driver-harvester/component.js
======
Add a condition to filter images which is ready.
======
Linked Issues
======
- https://github.com/harvester/harvester/issues/1663
======
=> HARVESTER: Image needs ready when create node driver

lib/shared/addon/components/cluster-driver/driver-rke/component.js
Addresses https://github.com/rancher/dashboard/issues/4870
=> Fix bug where % keeps getting added to max worker nodes unavailable

lib/nodes/addon/components/driver-amazonec2/template.hbs, translations/en-us.yaml
=> Remove Rancher OS AMI link from EC2 provisioning

translations/en-us.yaml
https://github.com/rancher/dashboard/issues/4894
@Shavindra This is the same change that you already reviewed, except that this time the change is being made to the branch for the patch release.
=> Clarify that GKE maintenance window time is UTC

lib/shared/addon/components/cluster-driver/driver-aks/component.js
=> Fix Azure Cloud Credential bug when embedded

lib/nodes/addon/components/driver-amazonec2/template.hbs
Fixes 2 issues in dashboard (same issue) - reporting a broken link:
https://github.com/rancher/dashboard/issues/5017
https://github.com/rancher/dashboard/issues/5263
=> Fix broken docs link

lib/nodes/addon/components/driver-vmwarevsphere/template.hbs
Addresses https://github.com/rancher/dashboard/issues/4865
=> Remove vsphere note template cpu max

app/catalog-tab/launch/route.js, app/models/app.js, lib/global-admin/addon/multi-cluster-apps/catalog/launch/route.js, lib/shared/addon/catalog/service.js
[Reference](https://github.com/rancher/dashboard/issues/4947)
Backport for 2.5.13
=> [2.5.13] Backport

.drone.yml, scripts/create-pr-in-rancher
======
Add a dispatch step in Drone to automatically create a PR in the repository `rancher/rancher` when a new tag is created in this repository. This saves time when creating release (candidates) and avoids manual errors.
======
Add step to Drone when a new tag is created
Linked Issues
======
======
@mantis-toboggan-md @rak-phillip Can you check if there is a reason we can't do this? I'm creating it as draft PR as EIO needs to do some work before we can merge. Thanks!
=> Add dispatch step to update tag in rancher/rancher

app/components/workload-row/template.hbs
Addresses https://github.com/rancher/dashboard/issues/5786
Simple fix for the above issue.
With this PR:
=> Fix workload port wrapping

scripts/create-pr-in-rancher
Follow up to https://github.com/rancher/ui/pull/4840, needs correct input variables to work.
@richard-cox Can you review and merge so it can be tested in next 2.6.6 rc?
=> Use correct inputs when creating PR in rancher

lib/nodes/addon/components/driver-harvester/component.js, lib/nodes/addon/components/driver-harvester/template.hbs, lib/shared/addon/components/cru-node-pools/component.js, lib/shared/addon/components/sortable-thead/template.hbs, translations/en-us.yaml
======
- Limit namespace by disabeld template option which is different with the first template VM namespace.
- Add loading component to improve UX.
======
Linked Issues
======
https://github.com/harvester/harvester/issues/2354
======
=> HARVESTER: Limit all VMs of the Harvester guest cluster in the same namespace

lib/shared/addon/components/cru-node-pools/component.js, lib/shared/addon/components/form-members/component.js
Reverts rancher/ui#4824
The issue this was intended to fix, https://github.com/rancher/dashboard/issues/5343, was ultimately resolved on the dashboard side, https://github.com/rancher/dashboard/pull/5766
=> Revert "reinitialize node pools and members when cluster changes"

lib/shared/addon/components/cru-cluster/template.hbs
=> Enabling member removal for RKE2 cluster imports

app/styles/components/_new-select.scss
Addresses https://github.com/rancher/dashboard/issues/5724
=> Fix select drop down so text is not clipped

app/styles/components/_forms.scss
Addresses https://github.com/rancher/dashboard/issues/5844
Before:
After:
=> Fix checked-disabled radio button style

lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/mixins/cluster-driver.js
Addresses https://github.com/rancher/dashboard/issues/6095
Ensure if the form fails to save because of validation error coming from backend, that we remove the % character tha was added, otherwise they keep getting added.
=> Fix % creep on custom cluster create with RKE template

app/authenticated/controller.js, app/authenticated/template.hbs, app/components/modal-edit-setting/template.hbs, app/styles/layout/_layout.scss, lib/global-admin/addon/components/azuread-endpoints/component.js, lib/global-admin/addon/security/authentication/azuread/controller.js, lib/global-admin/addon/security/authentication/azuread/template.hbs, lib/shared/addon/azure-ad/service.js, lib/shared/addon/components/modal-update-azuread/component.js, lib/shared/addon/components/modal-update-azuread/template.hbs, lib/shared/addon/utils/constants.js, lib/shared/app/components/modal-update-azuread/component.js, translations/en-us.yaml
https://github.com/rancher/dashboard/issues/6316
Waiting on https://github.com/rancher/rancher/issues/37228
=> Backport azuread endpoint migration

app/components/form-node-requirement/component.js, app/components/form-node-requirement/template.hbs, app/components/form-node-scheduling-row/component.js, app/components/form-node-scheduling-row/template.hbs, app/components/form-pod-scheduling-row/component.js, app/components/form-pod-scheduling-row/template.hbs, lib/nodes/addon/components/driver-harvester/component.js, lib/nodes/addon/components/driver-harvester/template.hbs, translations/en-us.yaml, translations/zh-hans.yaml
======
======
Linked Issues
======
- https://github.com/harvester/harvester/issues/2316
Add the configuration of node/pod scheduling on RKE1 Harvester Node Template
======
=> Harvester: Add Node/Pod Scheduling to Harvester node driver(RKE1)

lib/global-admin/addon/clusters/index/controller.js, lib/global-admin/addon/clusters/index/template.hbs, lib/shared/addon/components/form-network-config/template.hbs, translations/en-us.yaml
rancher/dashboard#5995
Backport of https://github.com/rancher/ui/pull/4851
=> [backport] Adding windows deprecated banners for rke1 on the clusters and provisioning pages

translations/en-us.yaml
https://github.com/rancher/dashboard/issues/5995#issuecomment-1199824263
=> Updating the windows deprecation banner

translations/en-us.yaml
https://github.com/rancher/dashboard/issues/6549#issuecomment-1203010880
=> Change the windows deprecation messaging

translations/en-us.yaml
Issue: 
https://github.com/rancher/dashboard/issues/6681
https://github.com/rancher/rancher/issues/38014
=> Update EKS security group details

lib/shared/addon/utils/amazon.js
This PR addresses https://github.com/rancher/dashboard/issues/6826#event-7357591802 by adding v1.23 to the hardcoded EKS version options.
=> Add EKS v1.23 option

lib/shared/addon/components/cru-cloud-provider/component.js, translations/en-us.yaml
======
Disable Harvester cloud provider option when the credential is external
======
Linked Issues
======
- https://github.com/harvester/harvester/issues/2605
======
=> HARVESTER: Disable Harvester cloud provider option when the credential is external

lib/nodes/addon/components/driver-harvester/component.js
======
- Filter namespace by `links.update`
======
Linked Issues
======
- https://github.com/harvester/harvester/issues/2485
======
=> HARVESTER: Add node driver namespace filter

app/components/form-pod-scheduling-row/component.js, app/components/form-pod-scheduling-row/template.hbs, lib/nodes/addon/components/driver-harvester/component.js, lib/nodes/addon/components/driver-harvester/template.hbs
Related issues at: https://github.com/harvester/harvester/issues/2567
======
======
Linked Issues
======
- https://github.com/rancher/rancher/issues/38465
======
=> Harvester: node/pod affinity enhancement on harvester cluster(RKE1)

lib/nodes/addon/components/driver-harvester/component.js
======
The harvester needs to filter the system namespace
======
Linked Issues
======
======
=> HARVESTER: filter harvester rke1 systemNamespace

lib/global-admin/addon/components/cru-cloud-credential/template.hbs, translations/en-us.yaml
======
Remove External Harvester Cloud Credentials Support
======
Linked Issues
======
- https://github.com/harvester/harvester/issues/3319
======
=> HARVESTER: Remove External Harvester Cloud Credentails Support

translations/en-us.yaml
======
Change Input label `Cluster` to `Imported Harvester Cluster`
======
Linked Issues
======
- https://github.com/harvester/harvester/issues/3319
======
=> HARVESTER: Label text change

lib/shared/addon/utils/amazon.js
This PR addresses https://github.com/rancher/dashboard/issues/7931
It is a backport of:
- https://github.com/rancher/ui/pull/4890
- https://github.com/rancher/ui/pull/4908
- https://github.com/rancher/ui/pull/4899/
=> Add EKS v1.23 and v1.24, remove older versions

lib/nodes/addon/components/boot-order-select/component.js, lib/nodes/addon/components/boot-order-select/template.hbs, lib/nodes/addon/components/driver-harvester/component.js, lib/nodes/addon/components/driver-harvester/template.hbs, lib/nodes/app/components/boot-order-select/component.js, lib/shared/addon/helpers/has-property.js, lib/shared/app/helpers/has-property.js, translations/en-us.yaml
======
- https://github.com/harvester/harvester/issues/2426
======
- New feature
Linked Issues
======
test step:
- https://github.com/harvester/docker-machine-driver-harvester/pull/35#issue-1506001382
======
=> HARVESTER: Support multi nic

lib/shared/addon/components/cru-cloud-provider/component.js
======
Add role name for Harvester CSI driver
======
Linked Issues
======
- https://github.com/harvester/harvester/pull/3357#issuecomment-1381252772
- https://github.com/harvester/harvester/issues/3052
======
=> Harvester: Generate the clusterRoleBinding for harvester-csi-driver

app/styles/components/_forms.scss, lib/nodes/addon/components/driver-digitalocean/component.js
Addresses https://github.com/rancher/dashboard/issues/6774
Backport of this PR: https://github.com/rancher/ui/pull/4894/files
=> [2.6 Backport] Add Ubuntu 22.04 support for Digital Ocean

lib/global-admin/addon/components/cru-cloud-credential/template.hbs, lib/nodes/addon/components/boot-order-select/component.js, lib/nodes/addon/components/boot-order-select/template.hbs, lib/nodes/addon/components/driver-harvester/component.js, lib/nodes/addon/components/driver-harvester/template.hbs, lib/nodes/app/components/boot-order-select/component.js, lib/shared/addon/helpers/has-property.js, lib/shared/app/helpers/has-property.js, translations/en-us.yaml
======
This is a backport pr:  https://github.com/rancher/ui/pull/4941
At the same time, for consistency, I cherry-pick the changes related to namesapce and external harvester
======
Linked Issues
======
======
=> [backport] support multi nics

lib/shared/addon/components/cru-cloud-provider/component.js, translations/en-us.yaml
======
Backport of 
- https://github.com/rancher/ui/pull/4940
- https://github.com/rancher/ui/pull/4947
======
=> [2.6 Backport] Remove External Harvester Cloud Credentails Support & Add csiClusterRoleName

translations/en-us.yaml
Follow up to #4873 - I messed up the dashboard link
=> Forwardport azuread migration warning part 2 electric bugaloo

lib/shared/addon/components/cru-cloud-provider/component.js, translations/en-us.yaml
======
Disable Harvester cloud provider option when the credential is external
======
Linked Issues
======
- https://github.com/harvester/harvester/issues/2605
======
backport #4881
reference rancher/dashboard#8183
=> BACKPORT: HARVESTER: Disable Harvester cloud provider option when the credential is external

lib/shared/addon/components/form-members/component.js, lib/shared/addon/components/form-members/template.hbs
Addresses https://github.com/rancher/dashboard/issues/8275
Forward port from 2.6.11
=> [2.7.2] Fix add members for standard user

app/authenticated/cluster/edit/route.js, lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs
Backport of https://github.com/rancher/ui/pull/4980
=> [2.7.2] clear defaultPodSecurityPolicyTemplateId when disable psp support is selected during rke1 provisioning

translations/en-us.yaml
https://github.com/rancher/dashboard/issues/8385
=> tweak 1.25 psp upgrade warning

lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, translations/en-us.yaml
https://github.com/rancher/dashboard/issues/8385
=> remove psp-in-cluster rke1 upgrade warning banner

lib/shared/addon/components/cluster-driver/driver-rke/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, translations/en-us.yaml
backport of https://github.com/rancher/ui/pull/4991
=> [2.7.2] remove psp-in-cluster rke1 upgrade warning banner

translations/en-us.yaml
https://github.com/rancher/dashboard/issues/8442
=> update rke2 hardened cluster upgrade doc link

translations/en-us.yaml
backport of https://github.com/rancher/ui/pull/4993
https://github.com/rancher/dashboard/issues/8444
=> [2.7.2]update rke2 hardened cluster upgrade doc link

lib/shared/addon/components/modal-confirm-imported-upgrade/component.js
https://github.com/rancher/dashboard/issues/8454
=> fix k3s-specific imported cluster upgrade warning

lib/shared/addon/components/modal-confirm-imported-upgrade/component.js
https://github.com/rancher/dashboard/issues/8478
backport of https://github.com/rancher/ui/pull/4995
=> [2.7.2]fix k3s-specific imported cluster upgrade warning 

lib/nodes/addon/components/driver-harvester/template.hbs
======
hide macAddress field
======
Linked Issues
======
- https://github.com/harvester/harvester/issues/3698
======
=> HARVESTER: hide macAddress

lib/nodes/addon/components/driver-harvester/template.hbs
======
This is a backport pr: https://github.com/rancher/ui/pull/5000
======
Linked Issues
======
- https://github.com/harvester/harvester/issues/3698
======
=> [2.7.2] HARVESTER: hide macAddress

lib/nodes/addon/components/driver-harvester/template.hbs
======
This is a backport pr:  https://github.com/rancher/ui/pull/5000
======
Linked Issues
======
======
=> [2.6] hide macaddress

translations/en-us.yaml
Backport of https://github.com/rancher/ui/pull/5003
=> [2.7.2]update k3s hardened cluster doc link

lib/nodes/addon/components/driver-harvester/template.hbs, translations/en-us.yaml
======
======
Linked Issues
======
- https://github.com/harvester/harvester/issues/2317
======
=> HARVESTER: Implement pod affinity in RKE1 node driver

lib/shared/addon/utils/amazon.js
Signed-off by: Furkat Gofurov (furkat.gofurov@suse.com)
Noticed this was missing mainly due to https://github.com/rancher/ui/commit/35b60f96650e992af0746ed4ee6bf1d8bcec738a
=> 🌱 Add 'ap-northeast-3' EKS region

lib/shared/addon/components/scheduling-toleration/template.hbs, lib/shared/addon/utils/constants.js, translations/en-us.yaml
https://github.com/rancher/dashboard/issues/8910#issuecomment-1552740472 - Updated Tolerations' 'Label Key' to 'Key'
https://github.com/rancher/dashboard/issues/8930 - update '(custom)' effect to 'All'
=> update agent config tolerations translations

lib/nodes/addon/components/driver-harvester/template.hbs
======
This is a backport pr:  https://github.com/rancher/ui/pull/5016
======
Linked Issues
======
======
=> HARVESTER: remove cpu max value limit

lib/nodes/addon/components/driver-harvester/template.hbs
======
Remove the maximum CPU limit when creating a Harvester guest cluster through rke1.
======
Linked Issues
======
https://github.com/harvester/harvester/issues/3878
======
=> Remove cpu max value limit

app/models/cluster.js
https://github.com/rancher/dashboard/issues/8968#issuecomment-1560366808
When EKS clusters are edited, only changed values are sent in the request and the rest are preserved (more info on why [here](https://github.com/rancher/rancher/issues/28541)). When a user clears out previously-defined cluster/fleet agent customization the relevant fields are deleted from the cluster spec; consequently, with imported EKS clusters specifically, the previously-set values are preserved. 
This PR updates the EKS cluster save function to set any cluster/fleet agent fields the user has cleared out to `null`, which will properly overwrite the previous value.
I found another bug in the same area (editing agent config) that appears to have a different underlying cause, issue here: …
=> fix eks edit removal of agent config fields

.drone.yml, README.md, config/environment.js, package.json, scripts/build-static, scripts/ci
- Used https://github.com/rancher/ui/pull/4896 as a template
=> Updated build process to work from the new `release-2.7.5` branch

lib/shared/addon/utils/amazon.js
======
- Forward port of https://github.com/rancher/ui/pull/5039
Linked Issues
======
https://github.com/rancher/dashboard/issues/9181
=> [master] Ensure new EKS regions can be selected when validating creds

app/components/form-pod-scheduling-row/component.js, app/components/form-pod-scheduling-row/template.hbs, lib/nodes/addon/components/driver-harvester/component.js, lib/nodes/addon/components/driver-harvester/template.hbs, translations/en-us.yaml
======
- Add the option `All Namespaces`
- Polish translation
======
Linked Issues
======
https://github.com/harvester/harvester/issues/2317
======
=> [RKE1]HARVESTER: polish vm scheduling for harvester driver

README.md
======
======
Linked Issues
======
======
=> Update README.md to specify correct versions

app/application/route.js, app/initializers/extend-ember-input.js, lib/shared/addon/components/accordion-list-item/component.js, lib/shared/addon/components/cluster-driver/driver-rke/template.hbs, lib/shared/addon/components/form-affinity-k8s/template.hbs, lib/shared/addon/components/form-agent-config/component.js, lib/shared/addon/components/form-agent-config/template.hbs, lib/shared/addon/components/form-match-expressions-k8s/component.js, lib/shared/addon/components/form-match-expressions-k8s/template.hbs, lib/shared/addon/components/form-name-description/template.hbs, lib/shared/addon/components/form-node-affinity-k8s/component.js, lib/shared/addon/components/form-node-affinity-k8s/template.hbs, lib/shared/addon/components/form-node-selector-term-k8s/component.js, lib/shared/addon/components/form-node-selector-term-k8s/template.hbs, lib/shared/addon/components/form-pod-affinity-k8s/component.js, lib/shared/addon/components/form-pod-affinity-k8s/template.hbs, lib/shared/addon/components/form-pod-affinity-term-k8s/component.js, lib/shared/addon/components/form-pod-affinity-term-k8s/template.hbs, lib/shared/addon/components/input-array-as-string/component.js, lib/shared/addon/components/input-integer/component.js, lib/shared/addon/components/resource-list/component.js, lib/shared/addon/components/resource-list/template.hbs, lib/shared/addon/components/save-cancel/component.js, lib/shared/addon/components/scheduling-toleration/component.js, lib/shared/addon/components/scheduling-toleration/template.hbs, lib/shared/addon/components/searchable-select/component.js
Needed for https://github.com/rancher/dashboard/pull/9247
=> Add Data-testid attributes to support agent config e2e tests

.drone.yml, README.md, package.json, scripts/build-static, scripts/ci
see https://github.com/rancher/ui/pull/5038
=> update build references to work from the release-2.7.6 branch

lib/shared/addon/utils/parse-version.js
https://github.com/rancher/dashboard/issues/9734
Dashboard side: https://github.com/rancher/dashboard/pull/9740
=> update isdevbuild to include -alpha versions

lib/shared/addon/components/cluster-driver/driver-aks/component.js, lib/shared/addon/components/cluster-driver/driver-gke/component.js
AKS Issue: https://github.com/rancher/aks-operator/issues/281
GKE Issue: https://github.com/rancher/gke-operator/issues/186
=> Remove support for K8s v1.23-v1.24 AKS/GKE for Rancher v2.8

lib/shared/addon/components/cru-cloud-provider/template.hbs, translations/en-us.yaml
https://github.com/rancher/dashboard/issues/9933
rke1 ec2 cluster creation:
rke1 custom cluster creation:
=> add external-aws cloudProvider option

lib/shared/addon/components/cru-cloud-provider/component.js
https://github.com/rancher/dashboard/issues/9933#issuecomment-1773548959
https://github.com/rancher/ui/assets/42977925/03628593-7843-43ce-9c25-53f4709898e9
=> set useInstanceMetadataHostname when selecting external-aws provider

lib/shared/addon/components/cluster-driver/driver-aks/component.js
======
The entire error object was passed to show on the UI, now only the error message instead.
Fixes https://github.com/rancher/dashboard/issues/7285
Before:
After:
=> Show error message from AKS locations endpoint properly

lib/nodes/addon/components/driver-vmwarevsphere/template.hbs, lib/shared/addon/components/cluster-driver/driver-aks/component.js, translations/en-us.yaml
As per title - merged changes to release-2.8.0 that should not have been there
=> Revert changes made by mistake to release-2.8.0

lib/shared/addon/components/cru-cloud-provider/component.js, lib/shared/addon/components/cru-cloud-provider/template.hbs, lib/shared/addon/components/radio-button/component.js, translations/en-us.yaml
Backport of aws external banners to master.
See: https://github.com/rancher/ui/pull/5082
=> Fix external aws banners

README.md
=> Update copyright year to 2024

lib/shared/addon/utils/amazon.js
https://github.com/rancher/dashboard/issues/9786
Backport of https://github.com/rancher/ui/pull/5070
=> [2.7] Add v1.27 k8s versions to EKS hardcoded list

app/models/cluster.js, lib/shared/addon/components/cluster-driver/driver-eks/template.hbs, translations/en-us.yaml
======
Addresses https://github.com/rancher/dashboard/issues/9043
QA note: This needs a real test making sure both backend and frontend work together properly to achieve the goal in #9043.
https://github.com/rancher/ui/assets/135728925/e44fde31-63fb-443b-bdec-e17bb179bb0d
=> Added new out of tree ebsCSIDriver option

.drone.yml, README.md, config/environment.js, package.json, scripts/build-static, scripts/ci
Update build process for 2.7.11
=> Update build process for 2.7.11

lib/shared/addon/utils/amazon.js
(cherry picked from commit 366219968be184546f6c3032a02ddf309a190cee)
======
======
Linked Issues
======
======
=> [v2.8] Add v1.28 k8s versions to EKS hardcoded list

lib/shared/addon/utils/amazon.js
Addresses https://github.com/rancher/dashboard/issues/10294
Adds `ca-west-1` for EC2.
=> Add ca-west-1 for EC2

lib/nodes/addon/components/driver-vmwarevsphere/template.hbs, translations/en-us.yaml
Fixes https://github.com/rancher/dashboard/issues/10495
Backport of PR to 2.8 => https://github.com/rancher/ui/pull/5081
=> [2.8 Backport] Add vSphere Graceful Shutdown Option

lib/shared/addon/components/cluster-driver/driver-gke/template.hbs, lib/shared/addon/components/gke-node-pool-row/component.js, lib/shared/addon/components/gke-node-pool-row/template.hbs
Fixes https://github.com/rancher/dashboard/issues/10267
Backport of PR to 2.8 => https://github.com/rancher/ui/pull/5099
=> [2.8 Backport] Fix GKE Node Version Inconsistency

lib/shared/addon/components/cru-cloud-provider/template.hbs
https://github.com/rancher/dashboard/issues/10359
=> Provide an expected variable to a string translation

lib/shared/addon/utils/amazon.js
======
======
Linked Issues
======
======
=> Add v1.29 k8s version to EKS list

.drone.yml, .github/workflows/test.yaml, scripts/bootstrap
This PR moves the test and lint from drone to GitHub actions.
=> Move test and lints to GitHub actions

app/instance-initializers/nav.js, translations/en-us.yaml
Part of these two 'epic' backports:
https://github.com/rancher/dashboard/issues/10276
https://github.com/rancher/dashboard/issues/10277
Backport of https://github.com/rancher/dashboard/issues/10617
=> [backport v2.8.x] Removing monitoring, alerts, notifiers, logging

lib/shared/addon/utils/amazon.js
Isuue: https://github.com/rancher/eks-operator/issues/622
======
======
Linked Issues
======
======
=> Drop support for Kubernetes v1.25 and v1.26

lib/shared/addon/utils/amazon.js
======
======
Linked Issues
======
======
=> Add v1.30 k8s version to EKS list

README.md, package.json, scripts/build-static
As per https://github.com/rancher/ui/pull/5096. Given the move from drone to gh though there's less to do
=> Branch for 2.9

lib/shared/addon/components/form-engine-opts/component.js
Fixes https://github.com/rancher/dashboard/issues/11581 -> Reverts rancher/ui#5158
=> Revert "BP: Add docker install URL for 27.0 and 27.1"

lib/shared/addon/components/cru-cloud-provider/component.js, lib/shared/addon/components/cru-cloud-provider/template.hbs, translations/en-us.yaml
Backport issue: https://github.com/rancher/dashboard/issues/11521
Original issue: https://github.com/rancher/dashboard/issues/11520
=> Backport Azure changes for RKE1

lib/shared/addon/utils/parse-version.js
https://github.com/rancher/dashboard/issues/11667
See https://github.com/rancher/dashboard/pull/11669 for details
=> add check for -main versions in isDevBuild

lib/shared/addon/components/form-engine-opts/component.js
Addresses https://github.com/rancher/dashboard/issues/11530
This PR adds the requested docker install URLs.
=> [2.9] Add docker install URL for 27.0 and 27.1

lib/shared/addon/components/form-engine-opts/component.js
Addresses https://github.com/rancher/dashboard/issues/11523
See issue above for manual testing instructions.
=>  [2.10] Add docker install URL for 27.0 and 27.1

lib/shared/addon/components/form-engine-opts/component.js
Addresses https://github.com/rancher/dashboard/issues/11968
Adds 27.2.x Docker URL
=> Add docker 27.2.x URL

lib/shared/addon/components/form-engine-opts/component.js
Backport of https://github.com/rancher/ui/pull/5173
Addresses https://github.com/rancher/dashboard/issues/11968
=> add option for docker 27.2.x

translations/en-us.yaml
======
Update Azure image placeholder
======
non-breaking change
Linked Issues
======
https://github.com/rancher/rancher/issues/47666
======
=> update azure image placeholder

README.md
=> Update copyright message

lib/shared/addon/components/form-engine-opts/component.js
Addresses https://github.com/rancher/dashboard/issues/13229
This PR adds the requested docker install URL
=> Add docker install URL for 27.5

translations/en-us.yaml
======
Updated the RKE1 deprecation message.
Linked Issues
======
https://github.com/rancher/dashboard/issues/13284
=> Update RKE1 deprecation message

README.md, package.json, scripts/build-static
Similar to https://github.com/rancher/ui/pull/5153/files we need to update version references in the release-2.11 branch
=> update references from latest2 to release-2.11

lib/shared/addon/components/form-engine-opts/component.js
Addresses [rancher/dashboard#14300](https://github.com/rancher/dashboard/issues/14300)
This PR adds the requested docker install URL
=> Add docker install URL for 28.1

lib/shared/addon/components/form-engine-opts/component.js
Addresses https://github.com/rancher/dashboard/issues/14302
This PR adds the requested docker install URL
=> Add docker install URL for 28.0
